with source as (
    select * from {{ ref('thaedw_integration__edw_th_jbp_analysis') }}
),
final as (
    select 
        bar_code as "bar_code",
        region_desc as "region_desc",
        bottom_line_discount as "bottom_line_discount",
        ar_code as "ar_code",
        cn_reason_code as "cn_reason_code",
        district as "district",
        sales_quantity as "sales_quantity",
        year as "year",
        credit_note_amount as "credit_note_amount",
        whgroup as "whgroup",
        ar_type_code as "ar_type_code",
        month_year as "month_year",
        month_number as "month_number",
        distributor_name as "distributor_name",
        distributor_id as "distributor_id",
        target_calls as "target_calls",
        sap_cust_id as "sap_cust_id",
        mcl_barcd as "mcl_barcd",
        segment as "segment",
        ar_type_name as "ar_type_name",
        str_count as "str_count",
        sales_office_code as "sales_office_code",
        gross_trade_sales as "gross_trade_sales",
        ar_name as "ar_name",
        inventory_quantity as "inventory_quantity",
        salesman_code as "salesman_code",
        whcode as "whcode",
        quantity_dz as "quantity_dz",
        salesman_name as "salesman_name",
        variant as "variant",
        brand as "brand",
        channel_code as "channel_code",
        si_gross_trade_sales_value as "si_gross_trade_sales_value",
        put_up_description as "put_up_description",
        sku_description as "sku_description",
        line_discount as "line_discount",
        channel as "channel",
        sku_code as "sku_code",
        net_invoice as "net_invoice",
        target_sales as "target_sales",
        data_type as "data_type",
        order_date as "order_date",
        si_sellin_target as "si_sellin_target",
        cluster as "cluster",
        cn_damaged_goods as "cn_damaged_goods",
        city as "city",
        year_quarter as "year_quarter",
        inventory as "inventory",
        sales_group as "sales_group",
        sales_office_name as "sales_office_name",
        cn_reason_description as "cn_reason_description",
        franchise as "franchise",
        return_quantity as "return_quantity"
    from source
)
select * from final