with source as (
    select * from {{ ref('thaedw_integration__edw_th_siso_analysis') }}
),
final as (
    select
        franchise as "franchise",
        so_net_invoice as "so_net_invoice",
        data_type as "data_type",
        si_gross_trade_sales_value as "si_gross_trade_sales_value",
        retail_env as "retail_env",
        sap_customer_name as "sap_customer_name",
        so_quantity_dz as "so_quantity_dz",
        sap_sales_group_code as "sap_sales_group_code",
        go_to_model_description as "go_to_model_description",
        sap_sales_office_description as "sap_sales_office_description",
        sap_sub_chnl_desc as "sap_sub_chnl_desc",
        si_sales_quantity as "si_sales_quantity",
        so_sales_quantity as "so_sales_quantity",
        year_month_jnj as "year_month_jnj",
        item_code as "item_code",
        si_base_value as "si_base_value",
        sap_prnt_cust_desc as "sap_prnt_cust_desc",
        sap_bnr_frmt_key as "sap_bnr_frmt_key",
        banner_description as "banner_description",
        sap_bnr_frmt_desc as "sap_bnr_frmt_desc",
        sap_bnr_key as "sap_bnr_key",
        si_return_value as "si_return_value",
        si_net_trade_sales_quantity as "si_net_trade_sales_quantity",
        sap_sls_org as "sap_sls_org",
        so_cn_damaged_goods as "so_cn_damaged_goods",
        so_credit_note_amount as "so_credit_note_amount",
        prod_subsegment as "prod_subsegment",
        si_return_quantity as "si_return_quantity",
        item_description as "item_description",
        sap_cust_chnl_desc as "sap_cust_chnl_desc",
        si_sales_less_return_quantity as "si_sales_less_return_quantity",
        sap_go_to_mdl_key as "sap_go_to_mdl_key",
        so_gross_trade_sales as "so_gross_trade_sales",
        so_return_quantity as "so_return_quantity",
        so_target_sales as "so_target_sales",
        brand as "brand",
        prod_subcategory as "prod_subcategory",
        sap_sales_office_code as "sap_sales_office_code",
        variant as "variant",
        prod_sub_brand as "prod_sub_brand",
        month_number_jnj as "month_number_jnj",
        sap_sales_group_description as "sap_sales_group_description",
        so_target_calls as "so_target_calls",
        sap_prnt_cust_key as "sap_prnt_cust_key",
        year_quarter_jnj as "year_quarter_jnj",
        si_gross_trade_sales_less_return_value as "si_gross_trade_sales_less_return_value",
        sap_cust_sub_chnl_key as "sap_cust_sub_chnl_key",
        si_tp_value as "si_tp_value",
        prod_category as "prod_category",
        year_jnj as "year_jnj",
        so_line_discount as "so_line_discount",
        so_bottom_line_discount as "so_bottom_line_discount",
        customer_id as "customer_id",
        sap_cust_chnl_key as "sap_cust_chnl_key",
        put_up as "put_up",
        si_net_trade_sales_value as "si_net_trade_sales_value",
        segment as "segment"
    from source
)
select * from final