with source as (
    select * from {{ ref('thaitg_integration__itg_th_dstrbtr_material_dim') }}
),
final as (
    select 
        item_cd as "item_cd",
        name_thai as "name_thai",
        name_eng as "name_eng",
        defstk_unt_cd as "defstk_unt_cd",
        unt_thai as "unt_thai",
        unt_eng as "unt_eng",
        prod_grp_id as "prod_grp_id",
        grp_cd as "grp_cd",
        typ_cd as "typ_cd",
        catgry_cd as "catgry_cd",
        brnd_cd as "brnd_cd",
        format_cd as "format_cd",
        bar_cd as "bar_cd",
        sls_prc_van as "sls_prc_van",
        sls_prc_credit as "sls_prc_credit",
        sls_prc3 as "sls_prc3",
        sls_prc4 as "sls_prc4",
        tax_typ as "tax_typ",
        from_qty as "from_qty",
        to_qty as "to_qty",
        prc_remark as "prc_remark",
        color_cd as "color_cd",
        mygrade as "mygrade",
        myclass as "myclass",
        unit_typ as "unit_typ",
        cost_typ as "cost_typ",
        stock_typ as "stock_typ",
        def_sls_unt_cd as "def_sls_unt_cd",
        def_buy_unt_cd as "def_buy_unt_cd",
        mysize as "mysize",
        weight as "weight",
        exceptax as "exceptax",
        mydesc as "mydesc",
        actv_status as "actv_status",
        barcd_actv_status as "barcd_actv_status",
        barcd_remark as "barcd_remark",
        canmakepo as "canmakepo",
        buy_prc1 as "buy_prc1",
        buy_prc2 as "buy_prc2",
        buy_prc3 as "buy_prc3",
        buy_prc4 as "buy_prc4",
        trnsprt_tm as "trnsprt_tm",
        vend_cd as "vend_cd",
        def_sls_wh_cd as "def_sls_wh_cd",
        def_buy_wh_cd as "def_buy_wh_cd",
        def_sls_shelf as "def_sls_shelf",
        def_buy_shelf as "def_buy_shelf",
        cost_level1 as "cost_level1",
        cost_level2 as "cost_level2",
        cost_level3 as "cost_level3",
        cost_level4 as "cost_level4",
        uom as "uom",
        unit_per_case as "unit_per_case",
        isexception as "isexception",
        isforvmr as "isforvmr",
        th_shrt_nm as "th_shrt_nm",
        en_shrt_nm as "en_shrt_nm",
        crt_dt as "crt_dt",
        updt_dt as "updt_dt",
        is_hero as "is_hero",
        is_npi as "is_npi",
        npi_start_dt as "npi_start_dt",
        npi_end_dt as "npi_end_dt",
        cdl_dttm as "cdl_dttm",
        crtd_dttm as "crtd_dttm",
        updt_dttm as "updt_dttm",
        parentcode as "parentcode"
    from source
)
select * from final