with source as (
    select * from {{ ref('thaedw_integration__edw_th_inventory_analysis') }}
),
final as (
    select 
        sap_sls_office_cd as "sap_sls_office_cd",
        si_tp_value as "si_tp_value",
        sap_cust_id as "sap_cust_id",
        sap_cust_sub_chnl_key as "sap_cust_sub_chnl_key",
        sap_cust_chnl_desc as "sap_cust_chnl_desc",
        prod_category as "prod_category",
        country_name as "country_name",
        month_year as "month_year",
        retail_env as "retail_env",
        sap_state_cd as "sap_state_cd",
        sku_description as "sku_description",
        sap_bnr_frmt_key as "sap_bnr_frmt_key",
        sap_city as "sap_city",
        prod_subsegment as "prod_subsegment",
        sap_sls_org as "sap_sls_org",
        sap_cust_nm as "sap_cust_nm",
        sap_addr as "sap_addr",
        year_week_number as "year_week_number",
        sap_chnl_desc as "sap_chnl_desc",
        sap_bnr_desc as "sap_bnr_desc",
        sap_sls_grp_cd as "sap_sls_grp_cd",
        sap_chnl_cd as "sap_chnl_cd",
        sap_bnr_frmt_desc as "sap_bnr_frmt_desc",
        franchise as "franchise",
        sap_go_to_mdl_desc as "sap_go_to_mdl_desc",
        segment as "segment",
        sap_sub_chnl_desc as "sap_sub_chnl_desc",
        return_quantity as "return_quantity",
        data_type as "data_type",
        sap_cntry_nm as "sap_cntry_nm",
        sap_cntry_cd as "sap_cntry_cd",
        sku_code as "sku_code",
        year_quarter as "year_quarter",
        sap_bnr_key as "sap_bnr_key",
        inventory as "inventory",
        distributor_id as "distributor_id",
        sap_cust_chnl_key as "sap_cust_chnl_key",
        sap_region as "sap_region",
        brand as "brand",
        variant as "variant",
        sap_cmp_id as "sap_cmp_id",
        amount_before_discount as "amount_before_discount",
        whcode as "whcode",
        gross_trade_sales as "gross_trade_sales",
        month_week_number as "month_week_number",
        year as "year",
        si_gross_trade_sales_value as "si_gross_trade_sales_value",
        put_up_description as "put_up_description",
        inventory_quantity as "inventory_quantity",
        prod_subcategory as "prod_subcategory",
        sap_prnt_cust_key as "sap_prnt_cust_key",
        order_date as "order_date",
        month_number as "month_number",
        sap_go_to_mdl_key as "sap_go_to_mdl_key",
        prod_sub_brand as "prod_sub_brand",
        sap_sls_office_desc as "sap_sls_office_desc",
        country_code as "country_code",
        sales_quantity as "sales_quantity",
        sap_prnt_cust_desc as "sap_prnt_cust_desc",
        si_net_trade_sales_value as "si_net_trade_sales_value",
        sap_sls_grp_desc as "sap_sls_grp_desc",
        sap_post_cd as "sap_post_cd",
        whgroup as "whgroup"
    from source
)
select * from final