version: 2

sources:
  - name: myssdl_raw
    database: "{{ env_var('DBT_ENV_LOAD_DB') }}"
    schema: myssdl_raw
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: sdl_my_as_watsons_inventory
        tags: ["j_rg_watsons_inv_ingestion","ingestion"]
        tests:
          - test_duplicate__ff:
              group_by_columns: ["cust_cd","store_cd","year","mth_id","matl_num","inv_qty_pc","inv_value","filename"]
              failure_reason: "Duplicate date exists"
              name: TRATBL_sdl_my_as_watsons_inventory__duplicate_test
              config:
                store_failures: true
                schema: myswks_integration
          - test_null__ff:
              not_null_columns: ["matl_num"]
              failure_reason: "Material Code is null"
              name: TRATBL_sdl_my_as_watsons_inventory__null_test
              config:
                store_failures: true
                schema: myswks_integration