{{
    config(
        sql_header = "alter session set week_start= 7;"
    )
}}
with final as
(
    select * from {{ ref('aspitg_integration__itg_yimian_price_data') }}
)
select cntry_cd::varchar(10) as cntry_cd,
    processing_date::date as processing_date,
    acquisition_date::timestamp_ntz(9) as acquisition_date,
    manufacturer::varchar(200) as manufacturer,
    retailer::varchar(200) as retailer,
    brand::varchar(150) as brand,
    is_competitor::varchar(10) as is_competitor,
    category::varchar(150) as category,
    subcat1::varchar(150) as subcat1,
    subcat2::varchar(150) as subcat2,
    substore::varchar(150) as substore,
    substore_name_cn::varchar(200) as substore_name_cn,
    substore_name_en::varchar(250) as substore_name_en,
    trusted_upc::varchar(150) as trusted_upc,
    trusted_mpc::varchar(150) as trusted_mpc,
    sap_code::number(38,0) as sap_code,
    product_id::varchar(150) as product_id,
    sku_id::varchar(150) as sku_id,
    rpc::varchar(150) as rpc,
    product_description_cn::varchar(1000) as product_description_cn,
    product_description_en::varchar(1000) as product_description_en,
    harvest_url::varchar(200) as harvest_url,
    harvest_image_url::varchar(200) as harvest_image_url,
    variant_cn::varchar(150) as variant_cn,
    variant_en::varchar(150) as variant_en,
    std_sku_name_cn::varchar(200) as std_sku_name_cn,
    std_sku_name_en::varchar(200) as std_sku_name_en,
    is_bundle::varchar(10) as is_bundle,
    volume::number(23,5) as volume,
    pcs::number(23,5) as pcs,
    std_pack_size::number(23,5) as std_pack_size,
    std_pack_size_unit::varchar(10) as std_pack_size_unit,
    on_promotion::varchar(10) as on_promotion,
    promotion_text::varchar(65535) as promotion_text,
    promotion_effective_cn::varchar(1000) as promotion_effective_cn,
    promotion_effective_en::varchar(1000) as promotion_effective_en,
    promotion_type::varchar(300) as promotion_type,
    portfolio_availability::varchar(50) as portfolio_availability,
    ratings::number(23,5) as ratings,
    reviews::varchar(20) as reviews,
    listed_price_rmb::number(23,5) as listed_price_rmb,
    observed_price_rmb::number(23,5) as observed_price_rmb,
    msrp_rmb::number(23,5) as msrp_rmb,
    net_price_rmb::number(23,5) as net_price_rmb,
    discount_rmb::number(23,5) as discount_rmb,
    discount_rate::number(23,8) as discount_rate,
    price_per_vol_rmb::number(23,5) as price_per_vol_rmb,
    has_gift::varchar(10) as has_gift,
    gift_info::varchar(500) as gift_info,
    gift_volume::number(23,5) as gift_volume,
    gift_value::number(23,8) as gift_value,
    price_per_vol_with_gift_rmb::number(23,8) as price_per_vol_with_gift_rmb,
    crtd_dttm::timestamp_ntz(9) as crtd_dttm,
    updt_dttm::timestamp_ntz(9) as updt_dttm
 from final