with kesai_m_data_mart_mv as (
    select * from {{ source('jpdcledw_integration', 'kesai_m_data_mart_mv') }}
),

final as (
select saleno_key as "saleno_key",
    saleno as "saleno",
    gyono as "gyono",
    bun_gyono as "bun_gyono",
    meisaikbn as "meisaikbn",
    itemcode as "itemcode",
    setitemnm as "setitemnm",
    bun_itemcode as "bun_itemcode",
    diid as "diid",
    disetid as "disetid",
    suryo as "suryo",
    tanka as "tanka",
    kingaku as "kingaku",
    meisainukikingaku as "meisainukikingaku",
    wariritu as "wariritu",
    hensu as "hensu",
    warimaekomitanka as "warimaekomitanka",
    warimaekomikingaku as "warimaekomikingaku",
    warimaenukikingaku as "warimaenukikingaku",
    meisaitax as "meisaitax",
    dispsaleno as "dispsaleno",
    kesaiid as "kesaiid",
    saleno_trim as "saleno_trim",
    diorderid as "diorderid",
    henpinsts as "henpinsts",
    c_dspointitemflg as "c_dspointitemflg",
    c_diitemtype as "c_diitemtype",
    c_diadjustprc as "c_diadjustprc",
    ditotalprc as "ditotalprc",
    c_diitemtotalprc as "c_diitemtotalprc",
    c_didiscountmeisai as "c_didiscountmeisai",
    bun_suryo as "bun_suryo",
    bun_tanka as "bun_tanka",
    bun_kingaku as "bun_kingaku",
    bun_meisainukikingaku as "bun_meisainukikingaku",
    bun_wariritu as "bun_wariritu",
    bun_hensu as "bun_hensu",
    bun_warimaekomitanka as "bun_warimaekomitanka",
    bun_warimaekomikingaku as "bun_warimaekomikingaku",
    bun_warimaenukikingaku as "bun_warimaenukikingaku",
    bun_meisaitax as "bun_meisaitax",
    maker as "maker",
    kakokbn as "kakokbn",
    saleno_p as "saleno_p",
    gyono_p as "gyono_p",
    bun_gyono_p as "bun_gyono_p"
from kesai_m_data_mart_mv
)

select * from final