with cim01kokya as (
    select * from {{ ref('jpndcledw_integration__cim01kokya') }}
),

final as (
select kokyano as "kokyano",
    zipcode as "zipcode",
    todofukenname as "todofukenname",
    seibetukbn as "seibetukbn",
    birthday as "birthday",
    birthdayedit as "birthdayedit",
    kokyakbn as "kokyakbn",
    kokyataiokbn as "kokyataiokbn",
    kokyasts as "kokyasts",
    dmtenpoflg as "dmtenpoflg",
    dmtsuhanflg as "dmtsuhanflg",
    teltenpoflg as "teltenpoflg",
    teltsuhanflg as "teltsuhanflg",
    firstmediacode as "firstmediacode",
    deleteflg as "deleteflg",
    carrername as "carrername",
    insertdate as "insertdate",
    inserttime as "inserttime",
    insertid as "insertid",
    updatedate as "updatedate",
    rank as "rank",
    hcardcontractdate as "hcardcontractdate",
    hcardcanceldate as "hcardcanceldate",
    hcardclass as "hcardclass",
    cardkokyano as "cardkokyano",
    fskbn as "fskbn",
    rowid01 as "rowid01",
    rowid02 as "rowid02",
    todofukencode as "todofukencode",
    testusrflg as "testusrflg",
    name1 as "name1",
    name2 as "name2",
    kana1 as "kana1",
    kana2 as "kana2",
    city as "city",
    addr as "addr",
    tatemono as "tatemono",
    mail_pc as "mail_pc",
    tel as "tel",
    taikai_flg as "taikai_flg",
    point as "point",
    sndflg as "sndflg",
    webno as "webno",
    mail_mobile as "mail_mobile",
    tel_mobile as "tel_mobile",
    tel_other as "tel_other",
    main_tel as "main_tel",
    main_mail as "main_mail",
    pastpaykbn as "pastpaykbn",
    buyruikei as "buyruikei",
    buyruikeisamplein as "buyruikeisamplein",
    buyfirst as "buyfirst",
    buylast_estheup4 as "buylast_estheup4",
    buylast_estheupcab as "buylast_estheupcab",
    buylast_soniclift as "buylast_soniclift",
    buylast_acg as "buylast_acg",
    buylast_gel as "buylast_gel",
    buynum_estheup4 as "buynum_estheup4",
    buynum_estheupcab as "buynum_estheupcab",
    buynum_soniclift as "buynum_soniclift",
    buynum_acg as "buynum_acg",
    buynum_gel as "buynum_gel",
    nopay_yen as "nopay_yen",
    channel_regist as "channel_regist",
    mailmemb_flg as "mailmemb_flg",
    mailbihada_flg as "mailbihada_flg",
    mailcilabo_flg as "mailcilabo_flg",
    addr_kana as "addr_kana",
    mailtenki_flg as "mailtenki_flg",
    mailstore_flg as "mailstore_flg",
    sndnewsletter_flg as "sndnewsletter_flg",
    sndmousikomi_flg as "sndmousikomi_flg",
    hcardupdate as "hcardupdate",
    hcardgroupno as "hcardgroupno",
    okurijo_memo as "okurijo_memo",
    pointguide_flg as "pointguide_flg",
    eccontractdate as "eccontractdate",
    faxno as "faxno",
    memo as "memo",
    updateid as "updateid",
    inserted_date as "inserted_date",
    inserted_by as "inserted_by",
    updated_date as "updated_date",
    updated_by as "updated_by"
from cim01kokya
)

select * from final