with dm_kesai_mart_dly_general as (
    select * from {{ ref('jpndcledw_integration__dm_kesai_mart_dly_general') }}
),

final as (
select kokyano as "kokyano",
    saleno_key as "saleno_key",
    saleno as "saleno",
    gyono as "gyono",
    bun_gyono as "bun_gyono",
    order_dt as "order_dt",
    ship_dt as "ship_dt",
    tokuiname as "tokuiname",
    storename as "storename",
    f_order as "f_order",
    f_ship445 as "f_ship445",
    channel as "channel",
    dspromcode as "dspromcode",
    dspromname as "dspromname",
    juchkbn as "juchkbn",
    meisaikbn as "meisaikbn",
    h_o_item_code as "h_o_item_code",
    h_o_item_name as "h_o_item_name",
    h_o_item_cname as "h_o_item_cname",
    h_o_item_anbun_qty as "h_o_item_anbun_qty",
    h_item_code as "h_item_code",
    z_o_item_code as "z_o_item_code",
    z_item_code as "z_item_code",
    ratio as "ratio",
    z_item_suryo as "z_item_suryo",
    z_item_hen_suryo as "z_item_hen_suryo",
    anbun_amount_tax110_ex as "anbun_amount_tax110_ex",
    z_item_amount_tax_ex as "z_item_amount_tax_ex",
    ratio2 as "ratio2",
    anbun_soryo as "anbun_soryo",
    anbun_point_tax_ex as "anbun_point_tax_ex",
    anbun_tokuten as "anbun_tokuten",
    gts as "gts",
    gts_qty as "gts_qty",
    ciw_discount as "ciw_discount",
    ciw_point as "ciw_point",
    ciw_return as "ciw_return",
    ciw_return_qty as "ciw_return_qty",
    nts as "nts",
    teikikeiyaku as "teikikeiyaku",
    f as "f",
    meisainukikingaku as "meisainukikingaku",
    warimaenukikingaku as "warimaenukikingaku",
    soryo as "soryo",
    point as "point",
    discount as "discount",
    h_o_suryo as "h_o_suryo",
    hensu as "hensu",
    y_order_f as "y_order_f",
    y_ship_f as "y_ship_f",
    h_koseritsu as "h_koseritsu",
    z_koseritsu as "z_koseritsu",
    h_bun_suryo as "h_bun_suryo",
    z_bun_suryo as "z_bun_suryo",
    c_diregularcontractid as "c_diregularcontractid",
    smkeiroid as "smkeiroid",
    uketsuketelcompanycd as "uketsuketelcompanycd",
    diordercode as "diordercode",
    kesaiid as "kesaiid",
    diorderid as "diorderid",
    new_discount as "new_discount",
    ciw_discount_notax as "ciw_discount_notax",
    sub_cnt as "sub_cnt",
    inserted_date as "inserted_date",
    inserted_by as "inserted_by",
    updated_date as "updated_date",
    updated_by as "updated_by"
from dm_kesai_mart_dly_general
)

select * from final