with edw_mds_jp_dcl_product_master as (
    select * from {{ ref('jpndcledw_integration__edw_mds_jp_dcl_product_master') }}
),

final as (
select id as "id",
    muid as "muid",
    versionname as "versionname",
    versionnumber as "versionnumber",
    version_id as "version_id",
    versionflag as "versionflag",
    name as "name",
    code as "code",
    changetrackingmask as "changetrackingmask",
    itemcode as "itemcode",
    itemname as "itemname",
    attr01 as "attr01",
    attr02 as "attr02",
    attr03 as "attr03",
    attr04 as "attr04",
    attr05 as "attr05",
    attr06 as "attr06",
    attr07 as "attr07",
    attr08 as "attr08",
    attr09 as "attr09",
    attr10 as "attr10",
    column01 as "column01",
    column02 as "column02",
    column03 as "column03",
    column04 as "column04",
    column05 as "column05",
    column06 as "column06",
    column07 as "column07",
    column08 as "column08",
    column09 as "column09",
    column10 as "column10",
    column11 as "column11",
    column12 as "column12",
    column13 as "column13",
    column14 as "column14",
    column15 as "column15",
    column16 as "column16",
    column17 as "column17",
    column18 as "column18",
    column19 as "column19",
    column20 as "column20",
    column21 as "column21",
    column22 as "column22",
    column23 as "column23",
    enterdatetime as "enterdatetime",
    enterusername as "enterusername",
    enterversionnumber as "enterversionnumber",
    lastchgdatetime as "lastchgdatetime",
    lastchgusername as "lastchgusername",
    lastchgversionnumber as "lastchgversionnumber",
    validationstatus as "validationstatus",
    inserted_date as "inserted_date",
    inserted_by as "inserted_by",
    updated_date as "updated_date",
    updated_by as "updated_by"
from edw_mds_jp_dcl_product_master
)

select * from final