with dm_kesai_mart_dly as (
    select * from {{ ref('jpndcledw_integration__dm_kesai_mart_dly') }}
),

final as (
select kokyano as "kokyano",
    saleno_key as "saleno_key",
    saleno as "saleno",
    order_dt as "order_dt",
    ship_dt as "ship_dt",
    pl_order_dt as "pl_order_dt",
    pl_ship_dt as "pl_ship_dt",
    f_order as "f_order",
    f_ship445 as "f_ship445",
    channel as "channel",
    juchkbn as "juchkbn",
    kesai_itemcode as "kesai_itemcode",
    setitemnm as "setitemnm",
    total_price as "total_price",
    qty as "qty",
    "誕生日" as "誕生日",
    "顧客現在ランク" as "顧客現在ランク",
    "性別コード" as "性別コード",
    "職業" as "職業",
    itemcode as "itemcode",
    itemname as "itemname",
    itemcname as "itemcname",
    tanka as "tanka",
    chubuncode as "chubuncode",
    chubunname as "chubunname",
    chubuncname as "chubuncname",
    daibuncode as "daibuncode",
    daibunname as "daibunname",
    daibuncname as "daibuncname",
    daidaibuncode as "daidaibuncode",
    daidaibunname as "daidaibunname",
    daidaibuncname as "daidaibuncname",
    bunkai_itemcode as "bunkai_itemcode",
    bunkai_itemname as "bunkai_itemname",
    bunkai_itemcname as "bunkai_itemcname",
    bunkai_tanka as "bunkai_tanka",
    bunkai_kossu as "bunkai_kossu",
    bunkai_kosritu as "bunkai_kosritu",
    kose_itemcode as "kose_itemcode",
    koseiocode as "koseiocode",
    kosecode as "kosecode",
    suryo as "suryo",
    koseritsu as "koseritsu",
    mds_itemcode as "mds_itemcode",
    mds_itemname as "mds_itemname",
    attr01 as "attr01",
    attr02 as "attr02",
    attr03 as "attr03",
    attr04 as "attr04",
    attr05 as "attr05",
    attr06 as "attr06",
    attr07 as "attr07",
    attr08 as "attr08",
    attr09 as "attr09",
    attr10 as "attr10",
    i13_itemcode as "i13_itemcode",
    settanpinsetkbn as "settanpinsetkbn",
    teikikeiyaku as "teikikeiyaku",
    f as "f",
    latest_stage as "latest_stage",
    stage_ym as "stage_ym",
    y_order_f as "y_order_f",
    y_ship_f as "y_ship_f"
from dm_kesai_mart_dly
)

select * from final