with 
wks_indonesia_noo_analysis as
(
    select * from idnwks_integration.wks_indonesia_noo_analysis
),
edw_product_dim as 
(
    select * from idnedw_integration.edw_product_dim
),
edw_distributor_dim as 
(
    select * from idnedw_integration.edw_distributor_dim
),
edw_time_dim as 
(
    select * from idnedw_integration.edw_time_dim
),
itg_target_dist_brand_channel as 
(
    select * from idnitg_integration.itg_target_dist_brand_channel
),

trans as 
(
SELECT T1.JJ_YEAR,
       T1.JJ_QRTR,
       T1.JJ_MNTH,
       T1.JJ_WK,
       T1.JJ_MNTH_WK_NO,
       T1.JJ_MNTH_NO,
       T1.BILL_DOC,
       T1.BILL_DT,
       T1.DSTRBTR_GRP_CD,
       T1.DSTRBTR_GRP_NM,
       T1.JJ_SAP_DSTRBTR_ID,
       T1.JJ_SAP_DSTRBTR_NM,
       T1.DSTRBTR_CD_NM,
       T1.AREA,
       T1.REGION,
       T1.BDM_NM,
       T1.RBM_NM,
       T1.DSTRBTR_STATUS,
       T1.CUST_ID_MAP,
       T1.CUST_NM_MAP,
       T1.DSTRBTR_CUST_CD_NM,
       T1.CUST_GRP,
       T1.CHNL,
       T1.OUTLET_TYPE,
       T1.CHNL_GRP,
       T1.JJID,
       T1.CHNL_GRP2,
       T1.CITY,
       T1.CUST_STATUS,
       T1.JJ_SAP_PROD_ID,
       T1.JJ_SAP_PROD_DESC,
       T1.JJ_SAP_UPGRD_PROD_ID,
       T1.JJ_SAP_UPGRD_PROD_DESC,
       T1.JJ_SAP_CD_MP_PROD_ID,
       T1.JJ_SAP_CD_MP_PROD_DESC,
       T1.SAP_PROD_CODE_NAME,
       T1.FRANCHISE,
       T1.BRAND,
       T1.VARIANT1,
       T1.VARIANT2,
       T1.VARIANT,
       T1.PUT_UP,
       T1.PROD_STATUS,
       T1.SLSMN_ID,
       T1.SLSMN_NM,
       T1.SALESMAN_KEY,
	   T1. SFA_ID,
       T1.SLS_QTY,
       T1.HNA,
       T1.NIV,
       T1.TRD_DSCNT,
       T1.DSTRBTR_NIV,
       T1.RTRN_QTY,
       T1.RTRN_VAL,
       T1.HSKU_TARGET_GROWTH,
       T1.HSKU_TARGET_COVERAGE,
       T1.JJ_MNTH_LONG,
       T1.TRGT_HNA,
       T1.TRGT_NIV,
       T1.NPI_FLAG,
       T1.BENCHMARK_SKU_CODE,
       T1.SKU_BENCHMARK,
       T1.HERO_SKU_FLAG,
       T1.TRGT_DIST_BRND_CHNL_FLAG,
       T1.TIERING,
	   T1.LATEST_CHNL,
	   T1.LATEST_OUTLET_TYPE,
	   T1.LATEST_CHNL_GRP,
	   T1.LATEST_CUST_GRP2,
	   T1.LATEST_CUST_GRP,
	   T1.LATEST_CUST_NM_MAP,
	   T1.LATEST_REGION,
	   T1.LATEST_AREA,
	   T1.LATEST_RBM,
	   T1.LATEST_AREA_PIC,
     T1.LATEST_JJID,
     T1.LATEST_PUT_UP,
     T1.LATEST_FRANCHISE,
     T1.LATEST_BRAND,
     T1.LATEST_MSL,
     T1.LATEST_COUNT_LOCAL_VARIANT,
	 T1.LATEST_CHNL_GRP2,
	T1.Latest_Distributor_Group,
 T1.Latest_Dstrbtr_grp_cd
FROM wks_indonesia_noo_analysis T1 
UNION ALL 
SELECT CAST(YEAR AS INTEGER) AS JJ_YEAR,
       ETD.JJ_QRTR AS JJ_QRTR,
       ETD.JJ_MNTH AS JJ_MNTH,
       0 AS JJ_WK,
       0 AS JJ_MNTH_WK_NO,
       ETD.JJ_MNTH_NO AS JJ_MNTH_NO,
       NULL AS BILL_DOC,
       NULL AS BILL_DT,
       NULL AS DSTRBTR_GRP_CD,
       NULL AS DSTRBTR_GRP_NM,
       TRIM(UPPER(h.JJ_SAP_DSTRBTR_ID)) AS JJ_SAP_DSTRBTR_ID,
       h.JJ_SAP_DSTRBTR_NM AS JJ_SAP_DSTRBTR_NM,
       h.JJ_SAP_DSTRBTR_NM || ' ^' || h.JJ_SAP_DSTRBTR_ID AS DSTRBTR_CD_NM,
       d.area AS AREA,
       d.region AS REGION,
       d.bdm_nm AS BDM_NM,
       d.rbm_nm AS RBM_NM,
       d.STATUS AS DSTRBTR_STATUS,
       NULL AS CUST_ID_MAP,
       NULL AS CUST_NM_MAP,
       NULL AS DSTRBTR_CUST_CD_NM,
       NULL AS CUST_GRP,
       TRIM(UPPER(h.channel)) AS CHNL,
       NULL AS OUTLET_TYPE,
       NULL AS CHNL_GRP,
       NULL AS JJID,
       NULL AS CHNL_GRP2,
       NULL AS CITY,
       NULL AS CUST_STATUS,
       NULL AS JJ_SAP_PROD_ID,
       NULL AS JJ_SAP_PROD_DESC,
       NULL AS JJ_SAP_UPGRD_PROD_ID,
       NULL AS JJ_SAP_UPGRD_PROD_DESC,
       NULL AS JJ_SAP_CD_MP_PROD_ID,
       NULL AS JJ_SAP_CD_MP_PROD_DESC,
       NULL AS SAP_PROD_CODE_NAME,
       CASE
         WHEN h.brand IS NOT NULL THEN EPD.franchise
         ELSE h.franchise
       END AS FRANCHISE,
       h.BRAND AS BRAND,
       NULL AS VARIANT1,
       NULL AS VARIANT2,
       NULL AS VARIANT,
       NULL AS PUT_UP,
       NULL AS PROD_STATUS,
       NULL AS SLSMN_ID,
       NULL AS SLSMN_NM,
        NULL AS SALESMAN_KEY,
          NULL AS SFA_ID,
       0 AS SLS_QTY,
       0 AS HNA,
       0 AS NIV,
       0 AS TRD_DSCNT,
       0 AS DSTRBTR_NIV,
       0 AS RTRN_QTY,
       0 AS RTRN_VAL,
       0 AS HSKU_TARGET_GROWTH,
       0 AS HSKU_TARGET_COVERAGE,
       h.jj_mnth_long AS jj_mnth_long,
       h.trgt_hna AS trgt_hna,
       h.trgt_niv AS trgt_niv,
       NULL AS NPI_FLAG,
       NULL AS BENCHMARK_SKU_CODE,
       NULL AS SKU_BENCHMARK,
       NULL AS HERO_SKU_FLAG,
       'Y' AS TRGT_DIST_BRND_CHNL_FLAG,
       NULL AS Tiering,
	   NULL AS LATEST_CHNL,
	   NULL AS LATEST_OUTLET_TYPE,
	   NULL AS LATEST_CHNL_GRP,
	   NULL AS LATEST_CUST_GRP2,
	   NULL AS LATEST_CUST_GRP,
	   NULL AS LATEST_CUST_NM_MAP,
	   NULL AS LATEST_REGION,
	   NULL AS LATEST_AREA,
	   NULL AS LATEST_RBM,
	   NULL AS LATEST_AREA_PIC,
     NULL AS LATEST_JJID,
     NULL AS LATEST_PUT_UP,
     NULL AS LATEST_FRANCHISE,
     NULL AS LATEST_BRAND,
     NULL AS LATEST_MSL,
	 NULL AS LATEST_COUNT_LOCAL_VARIANT,
	   NULL AS LATEST_CHNL_GRP2,
	  NULL AS Latest_Distributor_Group,
     NULL AS Latest_Dstrbtr_grp_cd
FROM itg_target_dist_brand_channel h
  LEFT JOIN (SELECT DISTINCT JJ_YEAR,
                    JJ_QRTR_NO,
                    JJ_QRTR,
                    JJ_MNTH_ID,
                    JJ_MNTH,
                    JJ_MNTH_NO,
                    JJ_MNTH_SHRT,
                    JJ_MNTH_LONG
             FROM EDW_TIME_DIM) AS ETD
         ON h.year = ETD.jj_year
        AND UPPER (TRIM (h.jj_mnth_long)) = UPPER (TRIM (ETD.JJ_MNTH_LONG))
  LEFT JOIN edw_distributor_dim d ON TRIM (UPPER (h.jj_sap_dstrbtr_id)) = TRIM (UPPER (d.jj_sap_dstrbtr_id))
  and concat(h.year,decode(upper(trim(h.jj_mnth_long)),'JANUARY','01','FEBRUARY','02','MARCH','03','APRIL','04','MAY','05','JUNE','06','JULY','07','AUGUST','08',
'SEPTEMBER','09','OCTOBER','10','NOVEMBER','11','DECEMBER','12','00')) between d.effective_from and d.effective_to
  LEFT JOIN (SELECT DISTINCT brand, franchise,effective_from,effective_to FROM edw_product_dim) EPD
         ON CASE WHEN h.brand IS NOT NULL
        AND UPPER (TRIM (h.brand)) = UPPER (TRIM (EPD.brand))
		and concat(h.year,decode(upper(trim(h.jj_mnth_long)),'JANUARY','01','FEBRUARY','02','MARCH','03','APRIL','04','MAY','05','JUNE','06','JULY','07','AUGUST','08',
'SEPTEMBER','09','OCTOBER','10','NOVEMBER','11','DECEMBER','12','00')) between EPD.effective_from and EPD.effective_to THEN 1 END = 1
),
final as 
(
    select 
    jj_year::number(18,0) as jj_year,
	jj_qrtr::varchar(24) as jj_qrtr,
	jj_mnth::varchar(25) as jj_mnth,
	jj_wk::number(18,0) as jj_wk,
	jj_mnth_wk_no::number(38,0) as jj_mnth_wk_no,
	jj_mnth_no::number(18,0) as jj_mnth_no,
	bill_doc::varchar(100) as bill_doc,
	bill_dt::timestamp_ntz(9) as bill_dt,
	dstrbtr_grp_cd::varchar(25) as dstrbtr_grp_cd,
	dstrbtr_grp_nm::varchar(155) as dstrbtr_grp_nm,
	jj_sap_dstrbtr_id::varchar(75) as jj_sap_dstrbtr_id,
	jj_sap_dstrbtr_nm::varchar(75) as jj_sap_dstrbtr_nm,
	dstrbtr_cd_nm::varchar(152) as dstrbtr_cd_nm,
	area::varchar(50) as area,
	region::varchar(50) as region,
	bdm_nm::varchar(50) as bdm_nm,
	rbm_nm::varchar(50) as rbm_nm,
	dstrbtr_status::varchar(50) as dstrbtr_status,
	cust_id_map::varchar(100) as cust_id_map,
	cust_nm_map::varchar(100) as cust_nm_map,
	dstrbtr_cust_cd_nm::varchar(304) as dstrbtr_cust_cd_nm,
	cust_grp::varchar(100) as cust_grp,
	chnl::varchar(100) as chnl,
	outlet_type::varchar(100) as outlet_type,
	chnl_grp::varchar(100) as chnl_grp,
	jjid::varchar(100) as jjid,
	chnl_grp2::varchar(100) as chnl_grp2,
	city::varchar(229) as city,
	cust_status::varchar(8) as cust_status,
	jj_sap_prod_id::varchar(50) as jj_sap_prod_id,
	jj_sap_prod_desc::varchar(100) as jj_sap_prod_desc,
	jj_sap_upgrd_prod_id::varchar(50) as jj_sap_upgrd_prod_id,
	jj_sap_upgrd_prod_desc::varchar(100) as jj_sap_upgrd_prod_desc,
	jj_sap_cd_mp_prod_id::varchar(50) as jj_sap_cd_mp_prod_id,
	jj_sap_cd_mp_prod_desc::varchar(100) as jj_sap_cd_mp_prod_desc,
	sap_prod_code_name::varchar(152) as sap_prod_code_name,
	franchise::varchar(50) as franchise,
	brand::varchar(50) as brand,
	variant1::varchar(50) as variant1,
	variant2::varchar(50) as variant2,
	variant::varchar(50) as variant,
	put_up::varchar(62) as put_up,
	prod_status::varchar(50) as prod_status,
	slsmn_id::varchar(100) as slsmn_id,
	slsmn_nm::varchar(100) as slsmn_nm,
	sls_qty::number(18,4) as sls_qty,
	hna::number(18,4) as hna,
	niv::number(18,4) as niv,
	trd_dscnt::number(18,4) as trd_dscnt,
	dstrbtr_niv::number(18,4) as dstrbtr_niv,
	rtrn_qty::number(18,4) as rtrn_qty,
	rtrn_val::number(18,4) as rtrn_val,
	hsku_target_growth::number(18,4) as hsku_target_growth,
	hsku_target_coverage::number(18,4) as hsku_target_coverage,
	jj_mnth_long::varchar(10) as jj_mnth_long,
	trgt_hna::number(38,4) as trgt_hna,
	trgt_niv::number(38,4) as trgt_niv,
	npi_flag::varchar(1) as npi_flag,
	benchmark_sku_code::varchar(75) as benchmark_sku_code,
	sku_benchmark::varchar(75) as sku_benchmark,
	hero_sku_flag::varchar(1) as hero_sku_flag,
	trgt_dist_brnd_chnl_flag::varchar(1) as trgt_dist_brnd_chnl_flag,
	tiering::varchar(100) as tiering,
    null::number(18,0) as count_sku_code,
    null::varchar(20) as mcs_status,
    null::varchar(2000) as local_variant,
    null::number(18,0) as count_local_variant,
    null::varchar(70) as salesman_key,
    null::varchar(255) as sfa_id,
	latest_chnl::varchar(100) as latest_chnl,
	latest_outlet_type::varchar(100) as latest_outlet_type,
	latest_chnl_grp::varchar(100) as latest_chnl_grp,
	latest_cust_grp2::varchar(100) as latest_cust_grp2,
	latest_cust_grp::varchar(100) as latest_cust_grp,
	latest_cust_nm_map::varchar(100) as latest_cust_nm_map,
	latest_region::varchar(100) as latest_region,
	latest_area::varchar(100) as latest_area,
	latest_rbm::varchar(100) as latest_rbm,
	latest_area_pic::varchar(100) as latest_area_pic,
	latest_jjid::varchar(200) as latest_jjid,
	latest_put_up::varchar(200) as latest_put_up,
	latest_franchise::varchar(200) as latest_franchise,
	latest_brand::varchar(200) as latest_brand,
	latest_msl::varchar(200) as latest_msl,
	latest_count_local_variant::varchar(200) as latest_count_local_variant,
	latest_chnl_grp2::varchar(200) as latest_chnl_grp2,
	latest_distributor_group::varchar(200) as latest_distributor_group,
	latest_dstrbtr_grp_cd::varchar(200) as latest_dstrbtr_grp_cd
    from trans
)

select * from final