with source as
(
    select * from {{ source('phlsdl_raw', 'sdl_mds_ph_rka_customers_adftemp') }}
),

transformed as (
select 
code as code,
CUST_CD as cust_cd,
BRNCH_CD as brnch_cd,
BRNCH_NM as brnch_nm,
PROV_CD as prov_cd,
prov_nm  as prov_nm,
REGION_CD as region_cd,
REGION_NM as region_nm,
MNCPLTY_CD as mncplty_cd,
mncplty_nm as mncplty_nm,
null as city_cd,
null as city_nm,
null as chnl_sub_grp_cd,
null as pms_nm,
null as ash_no,
null as ash_nm,
null as address1,
null as address2,
null as jj_chnl_cd,
null as tsr,
null as pmr,
null as chnl,
null as area_cd,
null as area_nm,
null as region_nm2,
null as wsman,
null as route,
null as status,
null as operating_hrs,
null as da_tag,
null as dizr_tag,
null as brnch_grp1,
null as brnch_grp2,
null as outlet_typ,
null as store_typ_cd,
null as store_type_desc,
null as prov_cd2,
null as data_compln_status,
null as ae_nm,
null as dt_opnd,
null as store_tin_no,
null as store_size_cd,
null as store_size,
null as store_mtrx_cd,
null as store_mtrx,
null as class,
null as store_clsfn,
null as jj_sold_to,
null as jj_ship_to,
null as bp,
null as sales_grp,
null as dsm,
null as sales_man_tag,
null as branch_no,
null as mdc_tag,
null as derived_branchno,
LASTCHGDATETIME as last_chg_datetime,
'1990-01-01 00:00:00' as effective_from,
'9999-12-31 00:00:00.000' as effective_to,
'Y ' as active,
current_timestamp as crtd_dtm,
current_timestamp as updt_dttm,
null as zip_code,
null as zip_cd_name,
null as barangay_code,
null as  barangay_cd_name,
null as long_lat_source,
null as latitude,
null as longitude,
from source

)
select * from transformed