--Import CTE
with source as (
    select * from {{ ref('aspwks_integration__wks_sap_mara_extract') }}
),

--Logical CTE

--Final CTE
final as (
    select
        matnr as matl_num, 
        to_date(ersda, 'yyyymmdd') as crt_on, 
        ernam as crt_by_nm, 
        to_date(laeda, 'yyyymmdd') as chg_dttm, 
        aenam as chg_by_nm, 
        vpsta as maint_sts_cmplt_matl, 
        pstat as maint_sts, 
        lvorm as fl_matl_del_clnt_lvl, 
        mtart as matl_type_cd, 
        mbrsh as indstr_sectr, 
        matkl as matl_grp_cd, 
        bismt as old_matl_num, 
        meins as base_uom_cd, 
        bstme as prch_uom_cd, 
        zeinr as doc_num, 
        zeiar as doc_type, 
        zeivr as doc_vers, 
        zeifo as pg_fmt__doc, 
        aeszn as doc_chg_num, 
        blatt as pg_num_doc, 
        try_cast(blanz as int) as num_sht, 
        ferth as prdtn_memo_txt, 
        formt as pg_fmt_prdtn_memo, 
        groes as size_dims_txt, 
        wrkst as bsc_matl, 
        normt as indstr_std_desc, 
        labor as mercia_plan, 
        ekwsl as prchsng_val_key, 
        brgew as grs_wt_meas, 
        ntgew as net_wt_meas, 
        gewei as wt_uom_cd, 
        volum as vol_meas, 
        voleh as vol_uom_cd, 
        behvo as cntnr_rqr, 
        raube as strg_cond, 
        tempb as temp_cond_ind, 
        disst as low_lvl_cd, 
        tragr as trspn_grp, 
        stoff as haz_matl_num, 
        spart as div, 
        kunnr as cmpt, 
        eannr as ean_obsol, 
        wesch as gr_prtd_qty, 
        bwvor as prcmt_rule, 
        bwscl as src_supl, 
        saiso as seasn_cat, 
        etiar as lbl_type_cd, 
        etifo as lbl_form, 
        entar as deact, 
        ean11 as prmry_upc_cd, 
        numtp as ean_cat, 
        laeng as lgth_meas, 
        breit as wdth_meas, 
        hoehe as hght_meas, 
        meabm as dim_uom_cd, 
        prdha as prod_hier_cd, 
        aeklk as stk_tfr_chg_cost, 
        cadkz as cad_ind, 
        qmpur as qm_prcmt_act, 
        ergew as allw_pkgng_wt, 
        ergei as wt_unit, 
        ervol as allw_pkgng_vol, 
        ervoe as vol_unit, 
        gewto as exces_wt_tlrnc, 
        volto as exces_vol_tlrnc, 
        vabme as var_prch_ord_unit, 
        kzrev as rvsn_lvl_asgn_matl, 
        kzkfg as configurable_matl_ind, 
        xchpf as btch_mgmt_reqt_ind, 
        vhart as pkgng_matl_type_cd, 
        fuelg as max_lvl_vol, 
        try_cast(stfak as int) as stack_fact, 
        magrv as pkgng_matl_grp, 
        begru as auth_grp, 
        to_date(datab, 'yyyymmdd') as vld_from_dt, 
        to_date(liqdt, 'yyyymmdd') as del_dt, 
        saisj as seasn_yr, 
        plgtp as prc_bnd_cat, 
        mlgut as bill_of_matl, 
        extwg as extrnl_matl_grp_txt, 
        satnr as cross_plnt_cnfg_matl, 
        attyp as matl_cat, 
        kzkup as matl_coprod_ind, 
        kznfm as fllp_matl_ind, 
        pmata as prc_ref_matl, 
        mstae as cros_plnt_matl_sts, 
        mstav as cros_dstn_chn_matl_sts, 
        to_date(mstde, 'yyyymmdd') as cros_plnt_matl_sts_vld_dt, 
        to_date(mstdv, 'yyyymmdd') as chn_matl_vld_from_dt, 
        taklv as tax_clsn_matl, 
        rbnrm as catlg_prfl, 
        mhdrz as min_rmn_shlf_lif, 
        mhdhb as tot_shlf_lif, 
        mhdlp as strg_pct, 
        inhme as cntnt_uom_cd, 
        inhal as net_cntnt_meas, 
        vpreh as cmpr_prc_unit, 
        etiag as isr_matl_grp, 
        inhbr as grs_cntnt_meas, 
        cmeth as qty_conv_meth, 
        try_cast(cuobf as int) as intrnl_obj_num, 
        kzumw as envmt_rlvnt, 
        kosch as prod_allc_dtrmn_proc, 
        trim(sprof) as prc_prfl_vrnt, 
        trim(nrfhg) as matl_qual_disc, 
        null as mfr_part_num,
        trim(mfrnr) as mfr_num, 
        trim(bmatn) as intrnl_inv_mgmt, 
        mprof as mfr_part_prfl, 
        kzwsm as meas_usg_unit, 
        saity as rollout_seasn, 
        profl as dngrs_goods_ind_prof, 
        ihivi as hi_viscous_ind, 
        iloos as in_bulk_lqd_ind, 
        serlv as lvl_explc_ser_num, 
        kzgvh as pkgng_matl_clse_pkgng, 
        xgchp as appr_btch_rec_ind, 
        kzeff as ovrd_chg_num, 
        try_cast(compl as int) as matl_cmplt_lvl, 
        iprkz as per_ind_shlf_lif_expn_dt, 
        rdmhd as rd_rule_sled, 
        przus as prod_cmpos_prtd_pkgng, 
        mtpos_mara as genl_item_cat_grp, 
        bflme as gn_matl_logl_vrnt, 
        zz_mvgr1 as prod_base, 
        zz_mvgr2 as vrnt, 
        zz_mvgr3 as put_up, 
        zz_mvgr4 as mega_brnd_cd, 
        zz_mvgr5 as brnd_cd, 
        zz_technology as tech, 
        zz_color as color, 
        zz_stack_factor as seasonality, 
        zz_mfgsource as mfg_src_cd, 
        trim(mfrpn) as mfr_part_num_new, 
        zz_fornum as formulation_num, 
        zz_fran as pka_franchise_cd, 
        ztranfran_zfrandesc as pka_franchise_desc, 
        zz_brand as pka_brand_cd, 
        ztranbrand_zbrandesc as pka_brand_desc, 
        zz_sbrand as pka_sub_brand_cd, 
        ztransbrand_zsbrandesc as pka_sub_brand_desc, 
        zz_variant as pka_variant_cd, 
        ztranvariant_zvardesc as pka_variant_desc, 
        zz_svariant as pka_sub_variant_cd, 
        ztransvariant_zsvardesc as pka_sub_variant_desc, 
        zz_flav as pka_flavor_cd, 
        ztranflav_zflavdesc as pka_flavor_desc, 
        zz_ingr as pka_ingredient_cd, 
        ztraningr_zingrdesc as pka_ingredient_desc, 
        zz_appl as pka_application_cd, 
        ztranappl_zappldesc as pka_application_desc, 
        zz_leng as pka_length_cd, 
        ztranleng_zlengdesc as pka_length_desc, 
        zz_shape as pka_shape_cd, 
        ztranshape_zzshapedesc as pka_shape_desc, 
        zz_spf as pka_spf_cd, 
        ztranspf_zzspfdesc as pka_spf_desc, 
        zz_cover as pka_cover_cd, 
        ztrancover_zcoverdesc as pka_cover_desc, 
        zz_form as pka_form_cd, 
        ztranform_zzformdesc as pka_form_desc, 
        zz_size as pka_size_cd, 
        ztransize_zsizedesc as pka_size_desc, 
        zz_char as pka_character_cd, 
        ztranchar_zchardesc as pka_character_desc, 
        zz_pack as pka_package_cd, 
        ztranpack_zpackdesc as pka_package_desc, 
        zz_attrib13 as pka_attribute_13_cd, 
        ztranattrib13_zattrib13desc as pka_attribute_13_desc, 
        zz_attrib14 as pka_attribute_14_cd, 
        ztranattrib14_zattrib14desc as pka_attribute_14_desc, 
        zz_sku as pka_sku_identification_cd, 
        ztransku_zskudesc as pka_sku_identification_desc, 
        zz_relabel as pka_one_time_relabeling_cd, 
        ztranrelabel_zrelabeldesc as pka_one_time_relabeling_desc, 
        zz_prodkey as pka_product_key, 
        zz_proddesc1 as pka_product_key_description, 
        zz_proddesc2 as pka_product_key_description_2, 
        zz_rootcode as pka_root_code, 
        zz_rootdesc1 as pka_root_code_desc_1, 
        zz_rootdesc2 as pka_root_code_desc_2, 
        current_timestamp()::timestamp_ntz(9)as crt_dttm, 
        current_timestamp()::timestamp_ntz(9)as updt_dttm
    from source
)


--Final CTE
select * from final