{{
  config(
    sql_header= "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
    materialized="incremental",
    incremental_strategy="merge",
    unique_key=["cust_num_1"],
    merge_exclude_columns=["crt_dttm"]
  )
}}
with
source as
(
  select * from {{ ref('aspwks_integration__wks_itg_cust_base') }}
),

final as
(
select
        mandt as clnt,
        kunnr as cust_num_1,
        adrnr as addr,
        anred as title,
        aufsd as cntrl_ordr_blk_cust,
        bahne as exp_train_stn,
        bahns as train_stn,
        bbbnr as intnl_loc_num1,
        bbsnr as intnl_loc_num2,
        begru as auth_grp,
        brsch as indstr_key,
        bubkz as chk_dig_intnl_loc_num,
        datlt as data_comm_line_no,
        erdat as dt_on_rec_crt,
        ernam as nm_prsn_crt_obj,
        exabl as unld_pt_exist_ind,
        faksd as cent_bill_blk_cust,
        fiskn as acct_num_mstr_rec_fisc_addr,
        knazk as wrk_num_cal,
        knrza as acct_num_alt_pyr,
        konzs as grp_key,
        ktokd as cust_acct_grp,
        kukla as cust_clsn,
        land1 as ctry_key,
        lifnr as acct_num_vend,
        lifsd as cent_delv_blk_cust,
        locco as city_coordnt,
        loevm as cent_del_fl_mstr_rec,
        name1 as nm_1,
        name2 as nm_2,
        name3 as nm_3,
        name4 as nm_4,
        niels as nlsn_id,
        ort01 as city,
        ort02 as dstrc,
        pfach as po_box,
        pstl2 as po_box_pstl_cd,
        pstlz as pstl_cd,
        regio as rgn,
        counc as cnty_cd,
        cityc as city_cd,
        rpmkr as fcst_chnl,
        sortl as srt_fld,
        sperr as cent_pstng_blk,
        spras as lang_key,
        stcd1 as tax_num_1,
        stcd2 as tax_num_2,
        stkza as busn_ptnr_subj_eqlztn_tax_ind,
        stkzu as liab_for_vat,
        stras as hs_num_and_street,
        telbx as telebox_num,
        telf1 as fst_phn_num,
        telf2 as sec_phn_num,
        telfx as fax_num,
        teltx as teletex_num,
        telx1 as telex_num,
        lzone as trspn_zn_goods_delv,
        xcpdk as is_acct_one_time_acct_ind,
        xzemp as alt_payee_doc_allw_ind,
        vbund as co_id_trad_ptnr,
        stceg as vat_regs_num,
        dear1 as cmpt_ind,
        dear2 as sls_ptnr_ind,
        dear3 as sls_prosp_ind,
        dear4 as for_cust_type4_ind,
        dear5 as id_dflt_sold_to_prty,
        dear6 as in_cnsmr,
        gform as legal_sts,
        bran1 as indstr_cd_1,
        bran2 as indstr_cd_2,
        bran3 as indstr_cd_3,
        bran4 as indstr_cd_4,
        bran5 as indstr_cd_5,
        ekont as init_cntct,
        umsat as annl_sls_1,
        umjah as yr_for_sls_gvn,
        uwaer as crncy_sls_fig,
        jmzah as yr_num_emp,
        jmjah as yr_for_num_emp_gvn,
        katr1 as attr_1,
        katr2 as attr_2,
        katr3 as attr_3,
        katr4 as attr_4,
        katr5 as attr_5,
        katr6 as attr_6,
        katr7 as attr_7,
        katr8 as attr_8,
        katr9 as attr_9,
        katr10 as attr_10,
        stkzn as ntrl_prsn,
        umsa1 as annl_sls_2,
        txjcd as tax_juris,
        mcod1 as srch_term_match_cd_srch1,
        mcod2 as srch_term_match_cd_srch2,
        mcod3 as srch_term_match_cd_srch3,
        periv as fisc_yr_vrnt,
        abrvw as usg_ind,
        inspbydebi as insp_carr_out_by_cust,
        inspatdebi as insp_delv_note_after_outb_delv,
        ktocd as ref_acct_grp_one_time_acct,
        pfort as po_box_city,
        werks as plnt,
        dtams as data_med_exch_ind,
        dtaws as instr_key_data_med_exch,
        duefl as sts_data_tfr_subsq_rlse,
        hzuor as asgnmt_hier,
        sperz as pmt_blk,
        etikg as cust_grp,
        civve as id_mn_non_mil_use,
        milve as id_mn_mil_use,
        kdkg1 as cust_cond_grp_1,
        kdkg2 as cust_cond_grp_2,
        kdkg3 as cust_cond_grp_3,
        kdkg4 as cust_cond_grp_4,
        kdkg5 as cust_cond_grp_5,
        xknza as alt_pyr_acct_num_ind,
        fityp as tax_type,
        stcdt as tax_num_type,
        stcd3 as tax_num3,
        stcd4 as tax_num4,
        xicms as cust_is_icms_expt,
        xxipi as cust_is_ipi_expt,
        xsubt as cust_grp_tax_subst,
        cfopc as cust_cfop_cat,
        txlw1 as tax_law_icms,
        txlw2 as tax_law_ipi,
        ccc01 as biochem_wf_ind,
        ccc02 as nuclr_np_ind,
        ccc03 as natl_scty_ind,
        ccc04 as missile_tech_ind,
        cassd as cent_sls_blk_cust,
        knurl as unifm_rsrs_lctr,
        current_timestamp()::timestamp_ntz(9) as crt_dttm,
        current_timestamp()::timestamp_ntz(9) as updt_dttm
    from source
)
select * from final
