{{
    config(
        sql_header="ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized="incremental",
        incremental_strategy = "merge",
        unique_key=["plnt","matl_plnt_view"],
        merge_exclude_columns = ["crt_dttm"]
    )
}}

with 

source as (

    select * from {{ ref('aspwks_integration__wks_itg_matl_plnt') }}
),

final as (
    select
    plant as plnt,
    mat_plant as matl_plnt_view,
    abckey as abc_in,
    del_flag as del_fl,
    dismm as mrp_type,
    gr_pr_time as gr_prcsg_time,
    mrp_contrl as mrp_ctl,
    stge_pd_un as time_unit,
    plnd_delry as plan_delv_time,
    prodsched as prdtn_schd,
    co_area as cntl_area,
    profit_ctr as prctr,
    pur_group as prchsng_gr,
    replentime as tot_rl_time_repl,
    rpa_qtyuom as uom_basis_mov_ave,
    base_uom as base_unit,
    country as ctry,
    val_class as valut_cls,
    currency as cncnc,
    g_avv040 as std_matl_cost,
    zsproctyp as spl_prcmt,
    zminlot as min_lot_size,
    zrndgval as rd_val_po_qty,
    material as matl,
    vendor as vend,
    zproctyp as prcmt_type,
    zprdcssor as predecessor,
    zbaseqtyb as base_qty_matplant,
    zcostlotb as cost_lot_size_in,
    zladgr as ld_gr,
    zitark as mil_goods_ind,
    zavl_chk as availability_check,
    zmmppstat as mm_pp_sts,
    zkautb as auto_po_allw,
    stocktype as stk_type,
    zsrlt_ind as src_list_ind,
    zusequ as qta_usg,
    zdisgr as mrp_grp,
    zreord as reordr_pt_mat_plant,
    zfxhor as plng_time_fence,
    zlfrhy as plng_cyc,
    zlotsz as lot_size_mat_plan,
    zbstma as max_lot_size,
    zbstfe as fx_lot_size_zbstfe,
    zmabst as max_stk_lvl,
    ztakzt as cyc_time,
    zkzech as btch_ent,
    zlgpro as iss_strg_loc,
    zrgekz as backflush_ind,
    zlgfsb as strge_loc_ext_proc,
    zplan_cal as plng_cal,
    zfhori as sched_mrgn_key,
    eisbe_qty as sfty_stk,
    zrwpro as cvge_prfl,
    zper_ind as per_in,
    zstrgr as strtgy_gr,
    zvrmod as cnsmptn_mode,
    zvint1 as cnsmptn_per_bw,
    zvint2 as cnsmptn_per_fw,
    zaltsl as alt_bom,
    zfrtme as prdtn_unit,
    zsfcpf as prdtn_sched_pro,
    undelivtol as tlrnc_under_delv,
    ovdelivtol as overdeliv_tlrnc,
    zausme as unit_iss,
    zabcin as cc_phys_inv,
    zins_int as insp_intv,
    zssqss as cntl_key,
    zcert_typ as cert_type,
    zqssys as qm_sys_req,
    zsobsk as spec_proc_cst,
    zawsls as var_key,
    price_ctrl as prc_cntl,
    price_avg as mvg_prc,
    zdevalind as devaluation_ind,
    zekalr as prod_cost_ind,
    origingrp as orig_gr,
    zorig_ind as matl_orig_ind,
    zpln_prc as fut_pind_prc,
    zpln_prc1 as fut_pind_prc_1,
    zpprc1dat as plan_prc_dt,
    zkosgr as cost_ovhd_grp,
    price_unit as prc_unit,
    zmrp_ctl as mrp_ctl_zmrp,
    zlaunchd as lunch_dt,
    znpi_ind as npi_id,
    zprv_prc as prev_pind_prc,
    zpln_prc2 as fut_pind_prc_2,
    zpprc2dat as plan_prc_dt_2,
    zpln_prc3 as fut_pind_prc_3,
    zpprc3dat as plan_prc_dt_3,
    zlaunchw as npi_launch_wk,
    zlaunchmt as npi_launch_mo,
    zskuseg as sku_sgmnt,
    zsuccecsr as successor_on_going,
    zsui_ind as sui_in,
    ztmarkup as toll_mkup_cost,
    zimarkup as intco_mkup,
    zmdactind as act_sku_in,
    zsnp_plnr as snp_plnr,
    ztrp_plnr as transpotatn_plnr,
    ztlb_swch as auto_tlb_off,
    zmin_stck as sfty_stk_min_in,
    zmax_stck as sfty_stk_max_in_zmax_stck,
    zrfs_ind as rfs_in,
    zexpiry as bulk_exp,
    zdmd_plnr as dmand_plnr,
    zdmd_prof as dmand_prfl,
    zday_supl as trgt_days_supl_zday,
    zmin_shlf as min_shlf_lif,
    zgi_prcet as gi_prcsg_time,
    zppds_hzn as pp_ds_hrzn_zppds,
    zserv_lev as srvc_lvl,
    zzncost as do_not_cost,
    zmmstd as vld_from_dt,
    zpstat as maint_sts,
    zrondval as rd_val,
    zsnpph as snp_prdtn_horiz,
    zsnpphp as snp_prod_horiz_perd,
    zsstkres as sfty_stk_res_percentage_zsstk,
    zstkth as snp_stk_trn_hor,
    zstkthp as snp_stk_trn_hor_peri,
    zreglic as rglt_lic,
    zmsdpsbm as sfty_stk_meth,
    zschkhor as snp_checkg_hor,
    zreqctyp as per_fact,
    zreqcflg as use_per_fact,
    zpegpmax as dyn_peg_max_bkwd,
    zdplpu as push_dstn,
    zdplfsso as cnsdr_sls_ordr,
    zdplfsfc as cnsdr_fcst,
    zatdsp as atd_rcpt,
    zatddm as atd_iss,
    zpegstatg as pegging_strtgy,
    zfedem as dmand_fcast_err_percentage,
    zdplfs as fair_shr_rule,
    zsnppullh as pull_depl_hor,
    zsnppushh as push_depl_hor,
    apo_prdcst as prdtn_cost,
    zfutmax as max_earliness,
    zpastmax as max_lateness,
    apo_scost as strg_costs_prod,
    unit as uom,
    apo_bstfe as fx_lot_size,
    apo_lsexct as exact_lot_size,
    zpervr as per_type,
    apo_numper as nr_per_cap,
    zppdshozn as pp_ds_hrzn,
    zz_expiry as bulk_exp_dur,
    apo_pplnnr as apo_prod_plnr,
    zsnpshipf as fix_stk_tfr,
    zlapen as delay_pnlty,
    zmaxla as max_delay,
    zndpen as non_del_penal,
    zprodh as snp_prdtn_horiz_zprodh,
    znpi_indr as npi_in_apo,
    zkstdcst as std_mat_cost_wo_pu,
    id_credat as crt_on,
    zprdtype as prod_type_apo,
    zparent as mstr_cd,
    zcpy_hist as copy_hist_apo,
    zabc as prod_classftn,
    zfc_indc as fcst_indc_apo,
    zjitind as jit_in,
    zrpltm_s as tot_rl_time,
    zminstk_s as sfty_stk_min_in_zminstk,
    zmaxstk_s as sfty_stk_max_in,
    zdayspl_s as trgt_days_supl,
    zservlv_s as srvc_lvl_zservlv,
    zfedem_s as dmand_fcast_err_percentage_zfedem,
    fiscvarnt as fisc_yr_vrnt,
    zcostyear as cost_yr,
    zfutstpr as fut_std_prc,
    current_timestamp()::timestamp_ntz(9) as crt_dttm,
    current_timestamp()::timestamp_ntz(9) as updt_dttm
  from source
)

select * from final