with source as(
    select * from {{ ref('aspitg_integration__vw_stg_sdl_sap_billing_condition') }}
),
final as(
    SELECT
  x.bill_num,
  x.bill_item,
  x.zstepnum,
  x.kncounter,
  x.doc_number,
  x.s_ord_item,
  x.knart,
  x.ch_on,
  x.comp_code,
  x.sales_dist,
  x.bill_type,
  x.bill_date,
  x.bill_cat,
  x.loc_currcy,
  x.cust_group,
  x.sold_to,
  x.payer,
  x.exrate_acc,
  x.stat_curr,
  x.doc_categ,
  x.salesorg,
  x.distr_chan,
  x.doc_currcy,
  x.createdon,
  x.co_area,
  x.costcenter,
  x.trans_date,
  x.exchg_rate,
  x.cust_grp1,
  x.cust_grp2,
  x.cust_grp3,
  x.cust_grp4,
  x.cust_grp5,
  x.matl_group,
  x.material,
  x.mat_entrd,
  x.matl_grp_1,
  x.matl_grp_2,
  x.matl_grp_3,
  x.matl_grp_4,
  x.matl_grp_5,
  x.billtoprty,
  x.ship_to,
  x.itm_type,
  x.prod_hier,
  x.prov_group,
  x.price_date,
  x.item_categ,
  x.div_head,
  x.division,
  x.stat_date,
  x.refer_doc,
  x.refer_itm,
  x.sales_off,
  x.sales_grp,
  x.wbs_elemt,
  x.calday,
  x.calmonth,
  x.calweek,
  x.fiscper,
  x.fiscvarnt,
  x.knclass,
  x.knorigin,
  x.kntyp,
  (
    x.knval * POWER(10, (
      2 - x.currdec
    ))
  ) AS knval,
  x.kprice,
  x.kinak,
  x.kstat,
  x.storno,
  x.rt_promo,
  x.rebate_grp,
  x.bwapplnm,
  x.processkey,
  x.eanupc,
  x.createdby,
  x.serv_date,
  x.inv_qty,
  x.actual_quantity_pc,
  x.forwagent,
  x.salesemply,
  x.sales_unit,
  x.kappl,
  x.acrn_id,
  x.recordmode,
  x.crt_dttm,
  x.source_file_name
FROM (
  SELECT
    sbc.bill_num,
    sbc.bill_item,
    sbc.zstepnum,
    sbc.kncounter,
    sbc.doc_number,
    sbc.s_ord_item,
    sbc.knart,
    sbc.ch_on,
    sbc.comp_code,
    sbc.sales_dist,
    sbc.bill_type,
    sbc.bill_date,
    sbc.bill_cat,
    sbc.loc_currcy,
    sbc.cust_group,
    sbc.sold_to,
    sbc.payer,
    sbc.exrate_acc,
    sbc.stat_curr,
    sbc.doc_categ,
    sbc.salesorg,
    sbc.distr_chan,
    sbc.doc_currcy,
    sbc.createdon,
    sbc.co_area,
    sbc.costcenter,
    sbc.trans_date,
    sbc.exchg_rate,
    sbc.cust_grp1,
    sbc.cust_grp2,
    sbc.cust_grp3,
    sbc.cust_grp4,
    sbc.cust_grp5,
    sbc.matl_group,
    sbc.material,
    sbc.mat_entrd,
    sbc.matl_grp_1,
    sbc.matl_grp_2,
    sbc.matl_grp_3,
    sbc.matl_grp_4,
    sbc.matl_grp_5,
    sbc.billtoprty,
    sbc.ship_to,
    sbc.itm_type,
    sbc.prod_hier,
    sbc.prov_group,
    sbc.price_date,
    sbc.item_categ,
    sbc.div_head,
    sbc.division,
    sbc.stat_date,
    sbc.refer_doc,
    sbc.refer_itm,
    sbc.sales_off,
    sbc.sales_grp,
    sbc.wbs_elemt,
    sbc.calday,
    sbc.calmonth,
    sbc.calweek,
    sbc.fiscper,
    sbc.fiscvarnt,
    sbc.knclass,
    sbc.knorigin,
    sbc.kntyp,
    sbc.knval,
    sbc.kprice,
    sbc.kinak,
    sbc.kstat,
    sbc.storno,
    sbc.rt_promo,
    sbc.rebate_grp,
    sbc.bwapplnm,
    sbc.processkey,
    sbc.eanupc,
    sbc.createdby,
    sbc.serv_date,
    sbc.inv_qty,
    CASE WHEN knart = 'ZKSD' THEN (
      emu.uomz1d * sbc.inv_qty
    ) ELSE 0 END AS actual_quantity_pc,
    sbc.forwagent,
    sbc.salesemply,
    sbc.sales_unit,
    sbc.kappl,
    sbc.acrn_id,
    sbc.recordmode,
    sbc.crt_dttm,
    sbc.source_file_name,
    currx.currkey,
    CASE WHEN CAST(LENGTH(currx.currkey) AS INT) > 0 THEN currx.currdec ELSE 2 END AS currdec
  FROM source AS sbc
  LEFT JOIN {{ source('SNAPASPITG_INTEGRATION', 'itg_crncy_mult') }} AS currx
    ON sbc.loc_currcy = currx.currkey
  LEFT JOIN {{ ref('aspedw_integration__edw_material_uom') }} AS emu
    ON LTRIM(sbc.material, 0) = LTRIM(emu.material, 0) AND sbc.sales_unit = emu.unit
) AS x
)

select * from final