{{
    config(
        sql_header= "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
    )
}}


with source as(
    select * from {{ ref('aspitg_integration__vw_stg_sdl_sap_bw_delivery') }}
),
final as(
    select 
    deliv_num as deliv_num,
    deliv_item as deliv_item,
    incoterms as incoterms,
    incoterms2 as incoterms2,
    unload_pt as unload_pt,
    cast(replace(grs_wgt_dl, ',', '') as decimal(20,4)) as grs_wgt_dl,
    unit_of_wt   as unit_of_wt,
    cast(replace(dlv_qty, ',', '') as decimal(20,4)) as dlv_qty,
    cast(replace(denomintr, ',', '') as decimal(20,4)) as denomintr,
    cast(replace(numerator, ',', '') as decimal(20,4)) as numerator,
    shp_pr_tmf as shp_pr_tmf,
    shp_pr_tmv as shp_pr_tmv,
    sls_unit as sls_unit,
    volume_unit as volume_unit,
    no_del_it as no_del_it,
    cast(replace(volume_dl, ',', '') as decimal(20,4)) as volume_dl,
    cast(replace(act_dl_qty, ',', '') as decimal(20,4)) as act_dl_qty,
    cast(replace(net_wgt_dl, ',', '') as decimal(20,4)) as net_wgt_dl,
    base_uom as base_uom,
    refer_doc as refer_doc,
    refer_item as refer_item,
    fisc_varnt as fisc_varnt,
    sold_to as sold_to,
    cust_grp as cust_grp,
    bill_block as bill_block,
    ship_to as ship_to,
    load_pt as load_pt,
    sls_org as sls_org,
    created_by as created_by,
    to_date(created_on, 'yyyymmdd') as created_on,
    whse_num as whse_num,
    strge_bin as strge_bin,
    strge_type as strge_type,
    matl_grp_3 as matl_grp_3,
    matl_grp_4 as matl_grp_4,
    sls_off as sls_off,
    del_wa_dh as del_wa_dh,
    wbs_elemt as wbs_elemt,
    prvdoc_ctg as prvdoc_ctg,
    to_date(st_up_dt, 'yyyymmdd') as st_up_dt,
    distr_chan as distr_chan,
    zactdldte as zactdldte,
    matl_grp_5 as matl_grp_5,
    division as division,
    itm_type as itm_type,
    sls_grp as sls_grp,
    stat_dt as stat_dt,
    crea_time as crea_time,
    item_categ as item_categ,
    plant as plant,
    bwapplnm as bwapplnm,
    creditor as creditor,
    doc_categ as doc_categ,
    forwagent as forwagent,
    matl_grp as matl_grp,
    sls_emply as sls_emply,
    material as material,
    prod_hier as prod_hier,
    payer as payer,
    bill_to_prty as bill_to_prty,
    matl_grp_2 as matl_grp_2,
    matl_grp_1 as matl_grp_1,
    mat_entrd as mat_entrd,
    stor_loc as stor_loc,
    eanupc as eanupc,
    pick_indc as pick_indc,
    consu_flag as consu_flag,
    cust_grp3 as cust_grp3,
    bus_area as bus_area,
    cust_grp5 as cust_grp5,
    cust_grp4 as cust_grp4,
    cust_grp2 as cust_grp2,
    cust_grp1 as cust_grp1,
    bilblk_dl as bilblk_dl,
    batch as batch,
    route as route,
    ship_point as ship_point,
    del_block as del_block,
    del_type as del_type,
    to_date(ship_dt, 'yyyymmdd') as ship_dt,
    goodsmv_st as goodsmv_st,
    sales_dist as sales_dist,
    to_date(gi_dt, 'yyyymmdd') as gi_dt,
    act_gi_dt as act_gi_dt,
    comp_cd as comp_cd,
    rt_promo as rt_promo,
    process_key as process_key,
    ch_on as ch_on,
    pick_conf as pick_conf,
    sts_pick as sts_pick,
    stor_no as stor_no,
    record_mode as record_mode,
    cast(replace(zdelqtybu, ',', '') as decimal(20,4)) as zdelqtybu,
    cast(replace(zdlqtycse, ',', '') as decimal(20,4)) as zdlqtycse,
    cdl_dttm as cdl_dttm,
    current_timestamp()::timestamp_ntz(9) as crtd_dttm,
    current_timestamp()::timestamp_ntz(9) as updt_dttm,
    file_name as file_name
    from source

)
select * from final