{{
    config(
        sql_header= "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized="incremental",
        incremental_strategy= "merge",
        unique_key=  ['request_number','data_packet','data_record'],
        merge_exclude_columns=["crt_dttm"]
    )
}}

--import CTE

with source as (
    select * from {{ ref('aspwks_integration__wks_itg_invc_sls')}}
),
final as(
    select 
    request as request_number,
    datapakid as data_packet,
    record as data_record,
    zactdldte as act_delv_dt,
    act_gi_dte as act_good_iss_dt,
    billtoprty as bill_to_prty,
    bill_date as bill_dt,
    bill_type as bill_ty,
    bill_num as bill_doc,
    comp_code as cmpy_cd,
    customer as cust_no,
    zdelcrdat as delv_doc_crt_dt,
    distr_chan as dstr_chnl,
    division as div,
    createdon as doc_crt_dt,
    doc_date as doc_dt,
    gi_date as good_iss_dt,
    material as mat,
    matav_date as mat_avail_dt,
    ord_reason as ord_rsn,
    zzabstk as ovrl_rej_sts,
    zcmgst as ovrl_sts_crd_chk,
    payer as payer,
    plant as plant,
    zzp_itm as prec_doc_itm,
    zzp_num as prec_doc_num,
    zsd_pod as proof_delv_dt,
    zrcodekey as rsn_cd_key,
    reason_rej as rsn_rej,
    gt_cmfre as rlse_dt_cr_mgmt,
    zreq_date as rqst_delv_dt,
    route as route,
    doc_number as sls_doc,
    doc_categ as sls_doc_cat,
    s_ord_item as sls_doc_itm,
    doc_type as sls_doc_typ,
    salesemply as sls_emp_hist,
    salesorg as sls_org,
    item_categ as sls_doc_itm_cat,
    ship_to as ship_to_prty,
    sold_to as sold_to_prty,
    zblqtycse as bill_qty_cse,
    bill_qty as bill_qty_pc,
    zbilqdift as bill_qty_difot,
    zbilqotif as bill_qty_otif,
    inv_qty as bill_qty_sls_uom,
    zcfmqdift as cnfrm_qty_difot,
    cml_cd_qty as cnfrm_qty_pc,
    zdlqtycse as delv_qty_cse,
    zdelqtybu as delv_qty_pc,
    dlv_qty as delv_qty_sls_uom,
    subtotal_6 as est_nts,
    zfs_ntsb as nts_bill,
    zfs_ninv as net_invc_sls,
    zfs_qtybu as fut_sls_qty,
    subtotal_1 as gros_trd_sls,
    subtotal_5 as net_amt,
    net_price as net_prc,
    netval_inv as net_bill_val,
    net_value as net_ord_val,
    zorqtycse as ord_qty_cse,
    zordqtybu as ord_qty_pc,
    zordqty as ord_pc_qty,
    cml_or_qty as ord_sls_qty,
    zktranlt as tran_ldtm,
    zunsuppc as unspp_qty,
    zunsupva as unspp_val,
    volume_dl as vol_delv,
    volume_ap as vol_ord,
    calday as cal_day,
    base_uom as base_uom,
    currency as curr_key,
    doc_currcy as doc_curr,
    sales_unit as sls_unit,
    fiscper as fisc_yr,
    current_timestamp()::timestamp_ntz(9) as crt_dttm, 
    current_timestamp()::timestamp_ntz(9) as updt_dttm
    from source

)

select * from final