{{
    config(
        sql_header="ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized="incremental",
        incremental_strategy = "merge",
        unique_key=["plnt","matl_plnt_view"],
        merge_exclude_columns = ["crt_dttm"]
    )
}}

with 

source as (

    select * from {{ ref('aspwks_integration__wks_itg_matl_plnt') }}
),

final as (
    select
    plant :: varchar(4) as plnt,
    mat_plant :: varchar(18) as matl_plnt_view,
    abckey :: varchar(1) as abc_in,
    del_flag :: varchar(1) as del_fl,
    dismm :: varchar(2) as mrp_type,
    gr_pr_time as gr_prcsg_time,
    mrp_contrl :: varchar(3) as mrp_ctl,
    stge_pd_un :: varchar(3) as time_unit,
    plnd_delry as plan_delv_time,
    prodsched :: varchar(3) as prdtn_schd,
    co_area :: varchar(4) as cntl_area,
    profit_ctr :: varchar(10) as prctr,
    pur_group :: varchar(3) as prchsng_gr,
    replentime as tot_rl_time_repl,
    rpa_qtyuom :: varchar(3) as uom_basis_mov_ave,
    base_uom :: varchar(3) as base_unit,
    country :: varchar(3) as ctry,
    val_class :: varchar(4) as valut_cls,
    currency :: varchar(5) as cncnc,
    g_avv040 as std_matl_cost,
    zsproctyp :: varchar(2) as spl_prcmt,
    zminlot as min_lot_size,
    zrndgval as rd_val_po_qty,
    material :: varchar(18) as matl,
    vendor :: varchar(10) as vend,
    zproctyp :: varchar(1) as prcmt_type,
    zprdcssor :: varchar(18) as predecessor,
    zbaseqtyb as base_qty_matplant,
    zcostlotb as cost_lot_size_in,
    zladgr :: varchar(4) as ld_gr,
    zitark :: varchar(1) as mil_goods_ind,
    zavl_chk :: varchar(2) as availability_check,
    zmmppstat :: varchar(2) as mm_pp_sts,
    zkautb :: varchar(1) as auto_po_allw,
    stocktype :: varchar(1) as stk_type,
    zsrlt_ind :: varchar(1) as src_list_ind,
    zusequ :: varchar(1) as qta_usg,
    zdisgr :: varchar(4) as mrp_grp,
    zreord as reordr_pt_mat_plant,
    zfxhor as plng_time_fence,
    zlfrhy :: varchar(3) as plng_cyc,
    zlotsz :: varchar(2) as lot_size_mat_plan,
    zbstma as max_lot_size,
    zbstfe as fx_lot_size_zbstfe,
    zmabst as max_stk_lvl,
    ztakzt :: varchar(3) as cyc_time,
    zkzech :: varchar(1) as btch_ent,
    zlgpro :: varchar(4) as iss_strg_loc,
    zrgekz :: varchar(1) as backflush_ind,
    zlgfsb :: varchar(4) as strge_loc_ext_proc,
    zplan_cal :: varchar(3) as plng_cal,
    zfhori :: varchar(3) as sched_mrgn_key,
    eisbe_qty as sfty_stk,
    zrwpro :: varchar(3) as cvge_prfl,
    zper_ind :: varchar(1) as per_in,
    zstrgr :: varchar(2) as strtgy_gr,
    zvrmod :: varchar(1) as cnsmptn_mode,
    zvint1 as cnsmptn_per_bw,
    zvint2 as cnsmptn_per_fw,
    zaltsl :: varchar(1) as alt_bom,
    zfrtme :: varchar(3) as prdtn_unit,
    zsfcpf :: varchar(6) as prdtn_sched_pro,
    undelivtol :: varchar(4) as tlrnc_under_delv,
    ovdelivtol :: varchar(4) as overdeliv_tlrnc,
    zausme :: varchar(3) as unit_iss,
    zabcin :: varchar(1) as cc_phys_inv,
    zins_int :: varchar(5) as insp_intv,
    zssqss :: varchar(8) as cntl_key,
    zcert_typ :: varchar(4) as cert_type,
    zqssys :: varchar(4) as qm_sys_req,
    zsobsk :: varchar(2) as spec_proc_cst,
    zawsls :: varchar(6) as var_key,
    price_ctrl :: varchar(1) as prc_cntl,
    price_avg as mvg_prc,
    zdevalind as devaluation_ind,
    zekalr :: varchar(1) as prod_cost_ind,
    origingrp :: varchar(4) as orig_gr,
    zorig_ind :: varchar(1) as matl_orig_ind,
    zpln_prc as fut_pind_prc,
    zpln_prc1 as fut_pind_prc_1,
    zpprc1dat as plan_prc_dt,
    zkosgr :: varchar(10) as cost_ovhd_grp,
    price_unit as prc_unit,
    zmrp_ctl :: varchar(3) as mrp_ctl_zmrp,
    zlaunchd as lunch_dt,
    znpi_ind :: varchar(1) as npi_id,
    zprv_prc as prev_pind_prc,
    zpln_prc2 as fut_pind_prc_2,
    zpprc2dat as plan_prc_dt_2,
    zpln_prc3 as fut_pind_prc_3,
    zpprc3dat as plan_prc_dt_3,
    zlaunchw as npi_launch_wk,
    zlaunchmt as npi_launch_mo,
    zskuseg :: varchar(1) as sku_sgmnt,
    zsuccecsr :: varchar(18) as successor_on_going,
    zsui_ind :: varchar(1) as sui_in,
    ztmarkup as toll_mkup_cost,
    zimarkup as intco_mkup,
    zmdactind :: varchar(1) as act_sku_in,
    zsnp_plnr :: varchar(3) as snp_plnr,
    ztrp_plnr :: varchar(3) as transpotatn_plnr,
    ztlb_swch :: varchar(1) as auto_tlb_off,
    zmin_stck :: varchar(4) as sfty_stk_min_in,
    zmax_stck :: varchar(4) as sfty_stk_max_in_zmax_stck,
    zrfs_ind :: varchar(1) as rfs_in,
    zexpiry :: varchar(4) as bulk_exp,
    zdmd_plnr :: varchar(3) as dmand_plnr,
    zdmd_prof :: varchar(10) as dmand_prfl,
    zday_supl :: varchar(3) as trgt_days_supl_zday,
    zmin_shlf :: varchar(4) as min_shlf_lif,
    zgi_prcet :: varchar(3) as gi_prcsg_time,
    zppds_hzn :: varchar(4) as pp_ds_hrzn_zppds,
    zserv_lev as srvc_lvl,
    zzncost :: varchar(1) as do_not_cost,
    zmmstd as vld_from_dt,
    zpstat :: varchar(15) as maint_sts,
    zrondval as rd_val,
    zsnpph :: varchar(3) as snp_prdtn_horiz,
    zsnpphp :: varchar(2) as snp_prod_horiz_perd,
    zsstkres :: varchar(4) as sfty_stk_res_percentage_zsstk,
    zstkth :: varchar(3) as snp_stk_trn_hor,
    zstkthp :: varchar(3) as snp_stk_trn_hor_peri,
    zreglic :: varchar(20) as rglt_lic,
    zmsdpsbm :: varchar(2) as sfty_stk_meth,
    zschkhor as snp_checkg_hor,
    zreqctyp as per_fact,
    zreqcflg :: varchar(1) as use_per_fact,
    zpegpmax as dyn_peg_max_bkwd,
    zdplpu :: varchar(1) as push_dstn,
    zdplfsso :: varchar(1) as cnsdr_sls_ordr,
    zdplfsfc :: varchar(1) as cnsdr_fcst,
    zatdsp :: varchar(3) as atd_rcpt,
    zatddm :: varchar(3) as atd_iss,
    zpegstatg as pegging_strtgy,
    zfedem as dmand_fcast_err_percentage,
    zdplfs :: varchar(2) as fair_shr_rule,
    zsnppullh as pull_depl_hor,
    zsnppushh as push_depl_hor,
    apo_prdcst as prdtn_cost,
    zfutmax as max_earliness,
    zpastmax as max_lateness,
    apo_scost as strg_costs_prod,
    unit :: varchar(3) as uom,
    apo_bstfe as fx_lot_size,
    apo_lsexct :: varchar(1) as exact_lot_size,
    zpervr :: varchar(1) as per_type,
    apo_numper as nr_per_cap,
    zppdshozn as pp_ds_hrzn,
    zz_expiry :: varchar(4) as bulk_exp_dur,
    apo_pplnnr :: varchar(3) as apo_prod_plnr,
    zsnpshipf :: varchar(1) as fix_stk_tfr,
    zlapen as delay_pnlty,
    zmaxla as max_delay,
    zndpen as non_del_penal,
    zprodh as snp_prdtn_horiz_zprodh,
    znpi_indr as npi_in_apo,
    zkstdcst as std_mat_cost_wo_pu,
    id_credat as crt_on,
    zprdtype as prod_type_apo,
    zparent :: varchar(18) as mstr_cd,
    zcpy_hist :: varchar(1) as copy_hist_apo,
    zabc :: varchar(2) as prod_classftn,
    zfc_indc :: varchar(1) as fcst_indc_apo,
    zjitind :: varchar(1) as jit_in,
    zrpltm_s as tot_rl_time,
    zminstk_s :: varchar(4) as sfty_stk_min_in_zminstk,
    zmaxstk_s :: varchar(4) as sfty_stk_max_in,
    zdayspl_s :: varchar(3) as trgt_days_supl,
    zservlv_s as srvc_lvl_zservlv,
    zfedem_s as dmand_fcast_err_percentage_zfedem,
    fiscvarnt :: varchar(2) as fisc_yr_vrnt,
    zcostyear as cost_yr,
    zfutstpr as fut_std_prc,
    current_timestamp()::timestamp_ntz(9) as crt_dttm,
    current_timestamp()::timestamp_ntz(9) as updt_dttm
  from source
)

select * from final