{{
    config(
        sql_header= "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized="incremental",
        incremental_strategy="delete+insert",
        unique_key=["file_name"]
    )
}}


with source as(
    select * from {{ ref('aspitg_integration__vw_stg_sdl_sap_bw_delivery') }}
),
final as(
    select 
    deliv_num::VARCHAR(50) as deliv_num,
    deliv_item::VARCHAR(50) as deliv_item,
    incoterms::VARCHAR(100) as incoterms,
    incoterms2::VARCHAR(100) as incoterms2,
    unload_pt::VARCHAR(100) as unload_pt,
    cast(replace(grs_wgt_dl, ',', '') as decimal(20,4)) as grs_wgt_dl,
    unit_of_wt::VARCHAR(30) as unit_of_wt,
    cast(replace(dlv_qty, ',', '') as decimal(20,4)) as dlv_qty,
    cast(replace(denomintr, ',', '') as decimal(20,4)) as denomintr,
    cast(replace(numerator, ',', '') as decimal(20,4)) as numerator,
    shp_pr_tmf::VARCHAR(50) as shp_pr_tmf,
    shp_pr_tmv::VARCHAR(50)as shp_pr_tmv,
    sls_unit::VARCHAR(30) as sls_unit,
    volume_unit::VARCHAR(30) as volume_unit,
    no_del_it::VARCHAR(100) as no_del_it,
    cast(replace(volume_dl, ',', '') as decimal(20,4)) as volume_dl,
    cast(replace(act_dl_qty, ',', '') as decimal(20,4)) as act_dl_qty,
    cast(replace(net_wgt_dl, ',', '') as decimal(20,4)) as net_wgt_dl,
    base_uom::VARCHAR(30) as base_uom,
    refer_doc::VARCHAR(100) as refer_doc,
    refer_item::VARCHAR(100) as refer_item,
    fisc_varnt::VARCHAR(30) as fisc_varnt,
    sold_to::VARCHAR(100) as sold_to,
    cust_grp::VARCHAR(50) as cust_grp,
    bill_block::VARCHAR(50) as bill_block,
    ship_to::VARCHAR(100) as ship_to,
    load_pt::VARCHAR(100) as load_pt,
    sls_org::VARCHAR(30) as sls_org,
    created_by::VARCHAR(100) as created_by,
    to_date(created_on, 'YYYYMMDD')::DATE as created_on,
    whse_num::VARCHAR(100) as whse_num,
    strge_bin::VARCHAR(100) as strge_bin,
    strge_type::VARCHAR(100) as strge_type,
    matl_grp_3::VARCHAR(50) as matl_grp_3,
    matl_grp_4::VARCHAR(50)as matl_grp_4,
    sls_off::VARCHAR(50) as sls_off,
    del_wa_dh::VARCHAR(50) as del_wa_dh,
    wbs_elemt::VARCHAR(100) as wbs_elemt,
    prvdoc_ctg::VARCHAR(50) as prvdoc_ctg,
    to_date(st_up_dt, 'YYYYMMDD')::DATE as st_up_dt,
    distr_chan::VARCHAR(30) as distr_chan,
    zactdldte::VARCHAR(100) as zactdldte,
    matl_grp_5::VARCHAR(50) as matl_grp_5,
    division::VARCHAR(50) as division,
    itm_type::VARCHAR(50) as itm_type,
    sls_grp::VARCHAR(50) as sls_grp,
    stat_dt::VARCHAR(50) as stat_dt,
    crea_time::VARCHAR(50) as crea_time,
    item_categ::VARCHAR(50) as item_categ,
    plant::VARCHAR(50) as plant,
    bwapplnm::VARCHAR(50) as bwapplnm,
    creditor::VARCHAR(50) as creditor,
    doc_categ::VARCHAR(50) as doc_categ,
    forwagent::VARCHAR(100) as forwagent,
    matl_grp::VARCHAR(100) as matl_grp,
    sls_emply::VARCHAR(100) as sls_emply,
    material::VARCHAR(50) as material,
    prod_hier::VARCHAR(100) as prod_hier,
    payer::VARCHAR(100) as payer,
    bill_to_prty::VARCHAR(100) as bill_to_prty,
    matl_grp_2::VARCHAR(50) as matl_grp_2,
    matl_grp_1::VARCHAR(50) as matl_grp_1,
    mat_entrd::VARCHAR(100) as mat_entrd,
    stor_loc::VARCHAR(50) as stor_loc,
    eanupc::VARCHAR(50) as eanupc,
    pick_indc::VARCHAR(50) as pick_indc,
    consu_flag::VARCHAR(100) as consu_flag,
    cust_grp3::VARCHAR(100) as cust_grp3,
    bus_area::VARCHAR(100) as bus_area,
    cust_grp5::VARCHAR(100) as cust_grp5,
    cust_grp4::VARCHAR(100) as cust_grp4,
    cust_grp2::VARCHAR(100)as cust_grp2,
    cust_grp1::VARCHAR(100) as cust_grp1,
    bilblk_dl::VARCHAR(100) as bilblk_dl,
    batch::VARCHAR(100)as batch,
    route::VARCHAR(100) as route,
    ship_point::VARCHAR(50)as ship_point,
    del_block::VARCHAR(100) as del_block,
    del_type::VARCHAR(50)as del_type,
    to_date(ship_dt, 'YYYYMMDD')::DATE as ship_dt,
    goodsmv_st::VARCHAR(30) as goodsmv_st,
    sales_dist::VARCHAR(50) as sales_dist,
    to_date(gi_dt, 'YYYYMMDD')::DATE as gi_dt,
    act_gi_dt::VARCHAR(100) as act_gi_dt,
    comp_cd::VARCHAR(50) as comp_cd,
    rt_promo::VARCHAR(100) as rt_promo,
    process_key::VARCHAR(100) as process_key,
    ch_on::VARCHAR(100) as ch_on,
    pick_conf::VARCHAR(50) as pick_conf,
    sts_pick::VARCHAR(50) as sts_pick,
    stor_no::VARCHAR(100) as stor_no,
    record_mode::VARCHAR(100) as record_mode,
    cast(replace(zdelqtybu, ',', '') as decimal(20,4)) as zdelqtybu,
    cast(replace(zdlqtycse, ',', '') as decimal(20,4)) as zdlqtycse,
    cdl_dttm::VARCHAR(255) as cdl_dttm,
    current_timestamp()::timestamp_ntz(9) as crtd_dttm,
    current_timestamp()::timestamp_ntz(9) as updt_dttm,
    file_name::VARCHAR(255) as file_name
    from source

)
select * from final