{{
    config(
        materialized= "incremental",
        incremental_strategy= "merge",
        unique_key= ["matl_num"],
        merge_exclude_columns= ["crt_dttm"]
    )
}}

--Import CTE
with source as (
    select * from {{ ref('aspwks_integration__wks_itg_matl_base') }}
),

--Logical CTE

--Final CTE
final as (
    select
        mandt as clnt,
        matnr as matl_num,
        ersda as crt_on,
        ernam as crt_by_nm,
        laeda as chg_dttm,
        aenam as chg_by_nm,
        vpsta as maint_sts_cmplt_matl,
        pstat as maint_sts,
        lvorm as fl_matl_del_clnt_lvl,
        mtart as matl_type_cd,
        mbrsh as indstr_sectr,
        matkl as matl_grp_cd,
        bismt as old_matl_num,
        meins as base_uom_cd,
        bstme as prch_uom_cd,
        zeinr as doc_num,
        zeiar as doc_type,
        zeivr as doc_vers,
        zeifo as pg_fmt__doc,
        aeszn as doc_chg_num,
        blatt as pg_num_doc,
        blanz as num_sht,
        ferth as prdtn_memo_txt,
        formt as pg_fmt_prdtn_memo,
        groes as size_dims_txt,
        wrkst as bsc_matl,
        normt as indstr_std_desc,
        labor as mercia_plan,
        ekwsl as prchsng_val_key,
        brgew as grs_wt_meas,
        ntgew as net_wt_meas,
        gewei as wt_uom_cd,
        volum as vol_meas,
        voleh as vol_uom_cd,
        behvo as cntnr_rqr,
        raube as strg_cond,
        tempb as temp_cond_ind,
        disst as low_lvl_cd,
        tragr as trspn_grp,
        stoff as haz_matl_num,
        spart as div,
        kunnr as cmpt,
        eannr as ean_obsol,
        wesch as gr_prtd_qty,
        bwvor as prcmt_rule,
        bwscl as src_supl,
        saiso as seasn_cat,
        etiar as lbl_type_cd,
        etifo as lbl_form,
        entar as deact,
        ean11 as prmry_upc_cd,
        numtp as ean_cat,
        laeng as lgth_meas,
        breit as wdth_meas,
        hoehe as hght_meas,
        meabm as dim_uom_cd,
        prdha as prod_hier_cd,
        aeklk as stk_tfr_chg_cost,
        cadkz as cad_ind,
        qmpur as qm_prcmt_act,
        ergew as allw_pkgng_wt,
        ergei as wt_unit,
        ervol as allw_pkgng_vol,
        ervoe as vol_unit,
        gewto as exces_wt_tlrnc,
        volto as exces_vol_tlrnc,
        vabme as var_prch_ord_unit,
        kzrev as rvsn_lvl_asgn_matl,
        kzkfg as configurable_matl_ind,
        xchpf as btch_mgmt_reqt_ind,
        vhart as pkgng_matl_type_cd,
        fuelg as max_lvl_vol,
        stfak as stack_fact,
        magrv as pkgng_matl_grp,
        begru as auth_grp,
        datab as vld_from_dt,
        liqdt as del_dt,
        saisj as seasn_yr,
        plgtp as prc_bnd_cat,
        mlgut as bill_of_matl,
        extwg as extrnl_matl_grp_txt,
        satnr as cross_plnt_cnfg_matl,
        attyp as matl_cat,
        kzkup as matl_coprod_ind,
        kznfm as fllp_matl_ind,
        pmata as prc_ref_matl,
        mstae as cros_plnt_matl_sts,
        mstav as cros_dstn_chn_matl_sts,
        mstde as cros_plnt_matl_sts_vld_dt,
        mstdv as chn_matl_vld_from_dt,
        taklv as tax_clsn_matl,
        rbnrm as catlg_prfl,
        mhdrz as min_rmn_shlf_lif,
        mhdhb as tot_shlf_lif,
        mhdlp as strg_pct,
        inhme as cntnt_uom_cd,
        inhal as net_cntnt_meas,
        vpreh as cmpr_prc_unit,
        etiag as isr_matl_grp,
        inhbr as grs_cntnt_meas,
        cmeth as qty_conv_meth,
        cuobf as intrnl_obj_num,
        kzumw as envmt_rlvnt,
        kosch as prod_allc_dtrmn_proc,
        sprof as prc_prfl_vrnt,
        nrfhg as matl_qual_disc,
        mfrpn as mfr_part_num,
        mfrnr as mfr_num,
        bmatn as intrnl_inv_mgmt,
        mprof as mfr_part_prfl,
        kzwsm as meas_usg_unit,
        saity as rollout_seasn,
        profl as dngrs_goods_ind_prof,
        ihivi as hi_viscous_ind,
        iloos as in_bulk_lqd_ind,
        serlv as lvl_explc_ser_num,
        kzgvh as pkgng_matl_clse_pkgng,
        xgchp as appr_btch_rec_ind,
        kzeff as ovrd_chg_num,
        compl as matl_cmplt_lvl,
        iprkz as per_ind_shlf_lif_expn_dt,
        rdmhd as rd_rule_sled,
        przus as prod_cmpos_prtd_pkgng,
        mtpos_mara as genl_item_cat_grp,
        bflme as gn_matl_logl_vrnt,
        zz_mvgr1 as prod_base,
        zz_mvgr2 as vrnt,
        zz_mvgr3 as put_up,
        zz_mvgr4 as mega_brand_cd,
        zz_mvgr5 as brand_cd,
        zz_technology as tech,
        zz_color as color,
        zz_stack_factor as seasonality,
        zz_mfgsource as mfg_src_cd,
        current_timestamp()::timestamp_ntz(9) as crt_dttm,
        current_timestamp()::timestamp_ntz(9) as updt_dttm
  from source
)

--Final select
select * from final