{{
    config(
        sql_header= "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized= "table"
        )
}}

--Import CTE
with source as (
    select * from {{ ref('aspitg_integration__vw_stg_sdl_sap_bw_billing') }}
),

--Logical CTE

--Final CTE
final as (
  select
  bill_num,
  bill_item,
  to_date(bill_dt, 'yyyymmdd') as bill_dt,
  bill_type,
  sold_to,
  rt_promo,
  s_ord_item,
  doc_num,
  cast(grs_wgt_dl as decimal(20, 4)) as grs_wgt_dl,
  cast(inv_qty as decimal(20, 4)) as inv_qty,
  cast(bill_qty as decimal(20, 4)) as bill_qty,
  base_uom,
  cast(exchg_rate as decimal(20, 4)) as exchg_rate,
  cast(req_qty as decimal(20, 4)) as req_qty,
  sls_unit,
  payer,
  cast(rebate_bas as decimal(20, 4)) as rebate_bas,
  cast(no_inv_it as decimal(20, 4)) as no_inv_it,
  cast(subtotal_1 as decimal(20, 4)) as subtotal_1,
  cast(subtotal_3 as decimal(20, 4)) as subtotal_3,
  cast(subtotal_4 as decimal(20, 4)) as subtotal_4,
  cast(subtotal_2 as decimal(20, 4)) as subtotal_2,
  cast(netval_inv as decimal(20, 4)) as netval_inv,
  cast(exchg_stat as decimal(20, 4)) as exchg_stat,
  cast(zblqtycse as decimal(20, 4)) as zblqtycse,
  cast(exratexacc as decimal(20, 4)) as exratexacc,
  cast(subtotal_6 as decimal(20, 4)) as subtotal_6,
  cast(gross_val as decimal(20, 4)) as gross_val,
  unit_of_wt,
  cast(subtotal_5 as decimal(20, 4)) as subtotal_5,
  cast(replace(numerator, ',', '') as decimal(20, 4)) as numerator,
  cast(cost as decimal(20, 4)) as cost,
  plant,
  cast(volume_dl as decimal(20, 4)) as volume_dl,
  loc_currcy,
  cast(denomintr as decimal(20, 4)) as denomintr,
  volume_unit,
  scale_qty,
  cast(cshdsc_bas as decimal(20, 4)) as cshdsc_bas,
  cast(net_wgt_dl as decimal(20, 4)) as net_wgt_dl,
  cast(tax_amt as decimal(20, 4)) as tax_amt,
  rate_type,
  sls_org,
  cast(exrate_acc as decimal(20, 4)) as exrate_acc,
  distr_chnl,
  doc_currcy,
  co_area,
  doc_categ,
  fisc_varnt,
  cost_center,
  matl_group,
  division,
  material,
  sls_grp,
  div_head,
  ship_point,
  wbs_elemt,
  bill_rule,
  bwapplnm,
  process_key,
  cust_grp,
  sls_off,
  refer_itm,
  matl_grp_3,
  to_date(price_dt, 'yyyymmdd') as price_dt,
  sls_emply,
  refer_doc,
  to_date(st_up_dte, 'yyyymmdd') as st_up_dte,
  stat_date,
  item_categ,
  prov_grp,
  matl_grp_5,
  prod_hier,
  itm_type,
  matl_grp_4,
  ship_to,
  bill_to_prty,
  rebate_grp,
  matl_grp_2,
  matl_grp_1,
  eanupc,
  mat_entrd,
  batch,
  stor_loc,
  to_date(created_on, 'yyyymmdd') as created_on,
  to_date(serv_date, 'yyyymmdd') as serv_date,
  cust_grp5,
  sls_deal,
  bill_cat,
  cust_grp1,
  cust_grp3,
  to_date(trans_dt, 'yyyymmdd') as trans_dt,
  cust_grp4,
  cust_grp2,
  stat_curr,
  ch_on,
  comp_cd,
  sls_dist,
  stor_no,
  record_mode,
  customer,
  cust_sls,
  oi_ebeln,
  oi_ebelp,
  zsd_pod,
  cdl_dttm,
  current_timestamp()::timestamp_ntz(9) as crtd_dttm,
  --convert_timezone('sgt', current_timestamp()) as updt_dttm,
  current_timestamp()::timestamp_ntz(9) as updt_dttm,
  file_name
  from source
)

--Final select
select * from final 