{{
    config(
        sql_header= "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized="incremental",
        incremental_strategy= "merge",
        unique_key=  ['request_number','data_packet','data_record'],
        merge_exclude_columns=["crt_dttm"]
    )
}}

--import CTE

with source as (
    select * from {{ ref('aspwks_integration__wks_itg_invc_sls')}}
),
final as(
    select 
    request as REQUEST_NUMBER,
    datapakid as DATA_PACKET,
    record as DATA_RECORD,
    zactdldte as ACT_DELV_DT,
    act_gi_dte as ACT_GOOD_ISS_DT,
    billtoprty as BILL_TO_PRTY,
    bill_date as BILL_DT,
    bill_type as BILL_TY,
    bill_num as BILL_DOC,
    comp_code as CMPY_CD,
    customer as CUST_NO,
    zdelcrdat as DELV_DOC_CRT_DT,
    distr_chan as DSTR_CHNL,
    division as DIV,
    createdon as DOC_CRT_DT,
    doc_date as DOC_DT,
    gi_date as GOOD_ISS_DT,
    material as MAT,
    matav_date as MAT_AVAIL_DT,
    ord_reason as ORD_RSN,
    zzabstk as OVRL_REJ_STS,
    zcmgst as OVRL_STS_CRD_CHK,
    payer as PAYER,
    plant as PLANT,
    zzp_itm as PREC_DOC_ITM,
    zzp_num as PREC_DOC_NUM,
    zsd_pod as PROOF_DELV_DT,
    zrcodekey as RSN_CD_KEY,
    reason_rej as RSN_REJ,
    gt_cmfre as RLSE_DT_CR_MGMT,
    zreq_date as RQST_DELV_DT,
    route as ROUTE,
    doc_number as SLS_DOC,
    doc_categ as SLS_DOC_CAT,
    s_ord_item as SLS_DOC_ITM,
    doc_type as SLS_DOC_TYP,
    salesemply as SLS_EMP_HIST,
    salesorg as SLS_ORG,
    item_categ as SLS_DOC_ITM_CAT,
    ship_to as SHIP_TO_PRTY,
    sold_to as SOLD_TO_PRTY,
    zblqtycse as BILL_QTY_CSE,
    bill_qty as BILL_QTY_PC,
    zbilqdift as BILL_QTY_DIFOT,
    zbilqotif as BILL_QTY_OTIF,
    inv_qty as BILL_QTY_SLS_UOM,
    zcfmqdift as CNFRM_QTY_DIFOT,
    cml_cd_qty as CNFRM_QTY_PC,
    zdlqtycse as DELV_QTY_CSE,
    zdelqtybu as DELV_QTY_PC,
    dlv_qty as DELV_QTY_SLS_UOM,
    subtotal_6 as EST_NTS,
    zfs_ntsb as NTS_BILL,
    zfs_ninv as NET_INVC_SLS,
    zfs_qtybu as FUT_SLS_QTY,
    subtotal_1 as GROS_TRD_SLS,
    subtotal_5 as NET_AMT,
    net_price as NET_PRC,
    netval_inv as NET_BILL_VAL,
    net_value as NET_ORD_VAL,
    zorqtycse as ORD_QTY_CSE,
    zordqtybu as ORD_QTY_PC,
    zordqty as ORD_PC_QTY,
    cml_or_qty as ORD_SLS_QTY,
    zktranlt as TRAN_LDTM,
    zunsuppc as UNSPP_QTY,
    zunsupva as UNSPP_VAL,
    volume_dl as VOL_DELV,
    volume_ap as VOL_ORD,
    calday as CAL_DAY,
    base_uom as BASE_UOM,
    currency as CURR_KEY,
    doc_currcy as DOC_CURR,
    sales_unit as SLS_UNIT,
    fiscper as FISC_YR,
    current_timestamp()::timestamp_ntz(9)as crt_dttm, 
    current_timestamp()::timestamp_ntz(9)as updt_dttm
    from source
)

select * from final