with wks_rpurchasedetail as
(
    select * from {{ ref('indwks_integration__wks_rpurchasedetail') }}
),
final as
(
    SELECT distcode,
        compinvno,
        compinvdate,
        salesorderno,
        netvalue,
        totaltax,
        totaldiscount,
        totalschemeamount,
        totaloctroi,
        suppliercode,
        cfacode,
        companyname,
        transportercode,
        lorryrecno,
        lorryrecdate,
        posgrnno,
        posgrndate,
        productcode,
        indentqtycs,
        indentqtypcs,
        uomcode,
        cashdiscrs,
        cashdiscper,
        octroi,
        linelevelamt,
        batchno,
        mnfgdate,
        expdate,
        mrp,
        lsp,
        purtax,
        purdisc,
        purrate,
        sellrate,
        sellrateat,
        sellrateavat,
        vattaxvalue,
        status,
        freescheme,
        schemerefrno,
        waybillno,
        designcode,
        bundledeal,
        createduserid,
        createddate,
        migrationflag,
        mproductcode,
        taxablevalue,
        cgstper,
        sgstper,
        utgstper,
        igstper,
        cessper,
        othertax1per,
        othertax2per,
        othertax3per,
        cgstvalue,
        sgstvalue,
        utgstvalue,
        igstvalue,
        cessvalue,
        othertax1value,
        othertax2value,
        othertax3value,
        reversecharges,
        taxvalueother1,
        taxvalueother2,
        taxvalueother3,
        taxtype,
        createddt,
        downloadflag,
        convert_timezone('Asia/Kolkata',current_timestamp()) AS updt_dttm,
        file_name
    FROM wks_rpurchasedetail
)
select distcode::varchar(50) as distcode,
    compinvno::varchar(25) as compinvno,
    compinvdate::timestamp_ntz(9) as compinvdate,
    salesorderno::varchar(50) as salesorderno,
    netvalue::number(38,6) as netvalue,
    totaltax::number(38,6) as totaltax,
    totaldiscount::number(38,6) as totaldiscount,
    totalschemeamount::number(38,6) as totalschemeamount,
    totaloctroi::number(38,6) as totaloctroi,
    suppliercode::varchar(50) as suppliercode,
    cfacode::varchar(30) as cfacode,
    companyname::varchar(50) as companyname,
    transportercode::varchar(20) as transportercode,
    lorryrecno::varchar(25) as lorryrecno,
    lorryrecdate::timestamp_ntz(9) as lorryrecdate,
    posgrnno::varchar(50) as posgrnno,
    posgrndate::timestamp_ntz(9) as posgrndate,
    productcode::varchar(50) as productcode,
    indentqtycs::number(38,6) as indentqtycs,
    indentqtypcs::number(38,6) as indentqtypcs,
    uomcode::varchar(20) as uomcode,
    cashdiscrs::number(38,6) as cashdiscrs,
    cashdiscper::number(38,6) as cashdiscper,
    octroi::number(38,6) as octroi,
    linelevelamt::number(38,6) as linelevelamt,
    batchno::varchar(50) as batchno,
    mnfgdate::timestamp_ntz(9) as mnfgdate,
    expdate::timestamp_ntz(9) as expdate,
    mrp::number(38,6) as mrp,
    lsp::number(38,6) as lsp,
    purtax::number(38,6) as purtax,
    purdisc::number(38,6) as purdisc,
    purrate::number(38,6) as purrate,
    sellrate::number(38,6) as sellrate,
    sellrateat::number(38,6) as sellrateat,
    sellrateavat::number(38,6) as sellrateavat,
    vattaxvalue::number(38,6) as vattaxvalue,
    status::varchar(50) as status,
    freescheme::number(18,0) as freescheme,
    schemerefrno::varchar(100) as schemerefrno,
    waybillno::varchar(50) as waybillno,
    designcode::varchar(50) as designcode,
    bundledeal::varchar(50) as bundledeal,
    createduserid::number(18,0) as createduserid,
    createddate::timestamp_ntz(9) as createddate,
    migrationflag::varchar(100) as migrationflag,
    mproductcode::varchar(50) as mproductcode,
    taxablevalue::number(18,6) as taxablevalue,
    cgstper::number(18,6) as cgstper,
    sgstper::number(18,6) as sgstper,
    utgstper::number(18,6) as utgstper,
    igstper::number(18,6) as igstper,
    cessper::number(18,6) as cessper,
    othertax1per::number(18,6) as othertax1per,
    othertax2per::number(18,6) as othertax2per,
    othertax3per::number(18,6) as othertax3per,
    cgstvalue::number(18,6) as cgstvalue,
    sgstvalue::number(18,6) as sgstvalue,
    utgstvalue::number(18,6) as utgstvalue,
    igstvalue::number(18,6) as igstvalue,
    cessvalue::number(18,6) as cessvalue,
    othertax1value::number(18,6) as othertax1value,
    othertax2value::number(18,6) as othertax2value,
    othertax3value::number(18,6) as othertax3value,
    reversecharges::number(18,6) as reversecharges,
    taxvalueother1::number(18,6) as taxvalueother1,
    taxvalueother2::number(18,6) as taxvalueother2,
    taxvalueother3::number(18,6) as taxvalueother3,
    taxtype::varchar(10) as taxtype,
    createddt::timestamp_ntz(9) as createddt,
    downloadflag::varchar(3) as downloadflag,
    updt_dttm::timestamp_ntz(9) as updt_dttm,
    file_name::varchar(255) as file_name
from final