with source as (
    select * from {{ ref('phlitg_integration__itg_mds_ph_gt_customer') }}
),
final as
(
    select dstrbtr_cust_id as "dstrbtr_cust_id",
        dstrbtr_cust_nm as "dstrbtr_cust_nm",
        slsmn as "slsmn",
        slsmn_desc as "slsmn_desc",
        rep_grp2 as "rep_grp2",
        rep_grp2_desc as "rep_grp2_desc",
        rep_grp3 as "rep_grp3",
        rep_grp3_desc as "rep_grp3_desc",
        rep_grp4 as "rep_grp4",
        rep_grp4_desc as "rep_grp4_desc",
        rep_grp5 as "rep_grp5",
        rep_grp5_desc as "rep_grp5_desc",
        rep_grp6 as "rep_grp6",
        rep_grp6_desc as "rep_grp6_desc",
        status as "status",
        address as "address",
        zip as "zip",
        slm_grp_cd as "slm_grp_cd",
        frequency_visit as "frequency_visit",
        store_prioritization as "store_prioritization",
        latitude as "latitude",
        longitude as "longitude",
        rpt_grp9 as "rpt_grp9",
        rpt_grp9_desc as "rpt_grp9_desc",
        rpt_grp11 as "rpt_grp11",
        rpt_grp11_desc as "rpt_grp11_desc",
        sls_dist as "sls_dist",
        sls_dist_desc as "sls_dist_desc",
        dstrbtr_grp_cd as "dstrbtr_grp_cd",
        dstrbtr_grp_nm as "dstrbtr_grp_nm",
        rpt_grp_15_desc as "rpt_grp_15_desc",
        last_chg_datetime as "last_chg_datetime",
        effective_from as "effective_from",
        effective_to as "effective_to",
        active as "active",
        crtd_dttm as "crtd_dttm",
        updt_dttm as "updt_dttm",
        zip_code as "zip_code",
        zip_cd_name as "zip_cd_name",
        barangay_code as "barangay_code",
        barangay_cd_name as "barangay_cd_name",
        long_lat_source as "long_lat_source"
    from source
)
select * from final