with source as (
    select * from {{ ref('phlitg_integration__itg_mds_ph_pos_customers') }}
),
final as
(
    select code as "code",
        cust_cd as "cust_cd",
        brnch_cd as "brnch_cd",
        brnch_nm as "brnch_nm",
        prov_cd as "prov_cd",
        prov_nm as "prov_nm",
        region_cd as "region_cd",
        region_nm as "region_nm",
        mncplty_cd as "mncplty_cd",
        mncplty_nm as "mncplty_nm",
        city_cd as "city_cd",
        city_nm as "city_nm",
        chnl_sub_grp_cd as "chnl_sub_grp_cd",
        pms_nm as "pms_nm",
        ash_no as "ash_no",
        ash_nm as "ash_nm",
        address1 as "address1",
        address2 as "address2",
        jj_chnl_cd as "jj_chnl_cd",
        tsr as "tsr",
        pmr as "pmr",
        chnl as "chnl",
        area_cd as "area_cd",
        area_nm as "area_nm",
        region_nm2 as "region_nm2",
        wsman as "wsman",
        route as "route",
        status as "status",
        operating_hrs as "operating_hrs",
        da_tag as "da_tag",
        dizr_tag as "dizr_tag",
        brnch_grp1 as "brnch_grp1",
        brnch_grp2 as "brnch_grp2",
        outlet_typ as "outlet_typ",
        store_typ_cd as "store_typ_cd",
        store_typ_desc as "store_typ_desc",
        prov_cd2 as "prov_cd2",
        data_compln_status as "data_compln_status",
        ae_nm as "ae_nm",
        dt_opnd as "dt_opnd",
        store_tin_no as "store_tin_no",
        store_size_cd as "store_size_cd",
        store_size as "store_size",
        store_mtrx_cd as "store_mtrx_cd",
        store_mtrx as "store_mtrx",
        class as "class",
        store_clsfn as "store_clsfn",
        jj_sold_to as "jj_sold_to",
        jj_ship_to as "jj_ship_to",
        bp as "bp",
        sales_grp as "sales_grp",
        dsm as "dsm",
        sales_man_tag as "sales_man_tag",
        branch_no as "branch_no",
        mdc_tag as "mdc_tag",
        derived_branchno as "derived_branchno",
        last_chg_datetime as "last_chg_datetime",
        effective_from as "effective_from",
        effective_to as "effective_to",
        active as "active",
        crtd_dttm as "crtd_dttm",
        updt_dttm as "updt_dttm",
        zip_code as "zip_code",
        zip_cd_name as "zip_cd_name",
        barangay_code as "barangay_code",
        barangay_cd_name as "barangay_cd_name",
        long_lat_source as "long_lat_source",
        latitude as "latitude",
        longitude as "longitude"
    from source
)
select * from final