with source as (
    select * from {{ ref('phlitg_integration__itg_mds_ph_lav_customer') }}
),
final as
(
    select dstrbtr_grp_cd AS "dstrbtr_grp_cd",
        zip_code AS "zip_code",
        rpt_grp_3_cd AS "rpt_grp_3_cd",
        longitude AS "longitude",
        rpt_grp_9_desc AS "rpt_grp_9_desc",
        sub_chnl_cd AS "sub_chnl_cd",
        channel_desc AS "channel_desc",
        parent_cust_nm AS "parent_cust_nm",
        effective_from AS "effective_from",
        rpt_grp_9_cd AS "rpt_grp_9_cd",
        mun_nm AS "mun_nm",
        region_nm AS "region_nm",
        region_cd AS "region_cd",
        province_cd AS "province_cd",
        zip_cd_name AS "zip_cd_name",
        cust_nm AS "cust_nm",
        parent_cust_cd AS "parent_cust_cd",
        barangay_cd_name AS "barangay_cd_name",
        effective_to AS "effective_to",
        active AS "active",
        province_nm AS "province_nm",
        rpt_grp_4_cd AS "rpt_grp_4_cd",
        rpt_grp_6_desc AS "rpt_grp_6_desc",
        mun_cd AS "mun_cd",
        rpt_grp_3_desc AS "rpt_grp_3_desc",
        updt_dttm AS "updt_dttm",
        dstrbtr_grp_nm AS "dstrbtr_grp_nm",
        rpt_grp_7_cd AS "rpt_grp_7_cd",
        rpt_grp_6_cd AS "rpt_grp_6_cd",
        cust_id AS "cust_id",
        rpt_grp_5_cd AS "rpt_grp_5_cd",
        rpt_grp_7_desc AS "rpt_grp_7_desc",
        barangay_code AS "barangay_code",
        rpt_grp_5_desc AS "rpt_grp_5_desc",
        channel_cd AS "channel_cd",
        long_lat_source AS "long_lat_source",
        latitude AS "latitude",
        crtd_dttm AS "crtd_dttm",
        last_chg_datetime AS "last_chg_datetime",
        rpt_grp_4_desc AS "rpt_grp_4_desc",
        sub_chnl_desc AS "sub_chnl_desc"
    from source
)
select * from final