{{
  config(
    alias="itg_cust_base",
    materialized="incremental",
    incremental_strategy="merge",
    unique_key=["cust_num_1"],
    tags= [""]
  )
}}
with
source as
(
  select * from {{ ref('aspwks_integration__wks_itg_cust_base') }}
),

final as
(
select
mandt as CLNT,
kunnr as CUST_NUM_1,
adrnr as ADDR,
anred as TITLE,
aufsd as CNTRL_ORDR_BLK_CUST,
bahne as EXP_TRAIN_STN,
bahns as TRAIN_STN,
bbbnr as INTNL_LOC_NUM1,
bbsnr as INTNL_LOC_NUM2,
begru as AUTH_GRP,
brsch as INDSTR_KEY,
bubkz as CHK_DIG_INTNL_LOC_NUM,
datlt as DATA_COMM_LINE_NO,
erdat as DT_ON_REC_CRT,
ernam as NM_PRSN_CRT_OBJ,
exabl as UNLD_PT_EXIST_IND,
faksd as CENT_BILL_BLK_CUST,
fiskn as ACCT_NUM_MSTR_REC_FISC_ADDR,
knazk as WRK_NUM_CAL,
knrza as ACCT_NUM_ALT_PYR,
konzs as GRP_KEY,
ktokd as CUST_ACCT_GRP,
kukla as CUST_CLSN,
land1 as CTRY_KEY,
lifnr as ACCT_NUM_VEND,
lifsd as CENT_DELV_BLK_CUST,
locco as CITY_COORDNT,
loevm as CENT_DEL_FL_MSTR_REC,
name1 as NM_1,
name2 as NM_2,
name3 as NM_3,
name4 as NM_4,
niels as NLSN_ID,
ort01 as CITY,
ort02 as DSTRC,
pfach as PO_BOX,
pstl2 as PO_BOX_PSTL_CD,
pstlz as PSTL_CD,
regio as RGN,
counc as CNTY_CD,
cityc as CITY_CD,
rpmkr as FCST_CHNL,
sortl as SRT_FLD,
sperr as CENT_PSTNG_BLK,
spras as LANG_KEY,
stcd1 as TAX_NUM_1,
stcd2 as TAX_NUM_2,
stkza as BUSN_PTNR_SUBJ_EQLZTN_TAX_IND,
stkzu as LIAB_FOR_VAT,
stras as HS_NUM_AND_STREET,
telbx as TELEBOX_NUM,
telf1 as FST_PHN_NUM,
telf2 as SEC_PHN_NUM,
telfx as FAX_NUM,
teltx as TELETEX_NUM,
telx1 as TELEX_NUM,
lzone as TRSPN_ZN_GOODS_DELV,
xcpdk as IS_ACCT_ONE_TIME_ACCT_IND,
xzemp as ALT_PAYEE_DOC_ALLW_IND,
vbund as CO_ID_TRAD_PTNR,
stceg as VAT_REGS_NUM,
dear1 as CMPT_IND,
dear2 as SLS_PTNR_IND,
dear3 as SLS_PROSP_IND,
dear4 as FOR_CUST_TYPE4_IND,
dear5 as ID_DFLT_SOLD_TO_PRTY,
dear6 as IN_CNSMR,
gform as LEGAL_STS,
bran1 as INDSTR_CD_1,
bran2 as INDSTR_CD_2,
bran3 as INDSTR_CD_3,
bran4 as INDSTR_CD_4,
bran5 as INDSTR_CD_5,
ekont as INIT_CNTCT,
umsat as ANNL_SLS_1,
umjah as YR_FOR_SLS_GVN,
uwaer as CRNCY_SLS_FIG,
jmzah as YR_NUM_EMP,
jmjah as YR_FOR_NUM_EMP_GVN,
katr1 as ATTR_1,
katr2 as ATTR_2,
katr3 as ATTR_3,
katr4 as ATTR_4,
katr5 as ATTR_5,
katr6 as ATTR_6,
katr7 as ATTR_7,
katr8 as ATTR_8,
katr9 as ATTR_9,
katr10 as ATTR_10,
stkzn as NTRL_PRSN,
umsa1 as ANNL_SLS_2,
txjcd as TAX_JURIS,
mcod1 as SRCH_TERM_MATCH_CD_SRCH1,
mcod2 as SRCH_TERM_MATCH_CD_SRCH2,
mcod3 as SRCH_TERM_MATCH_CD_SRCH3,
periv as FISC_YR_VRNT,
abrvw as USG_IND,
inspbydebi as INSP_CARR_OUT_BY_CUST,
inspatdebi as INSP_DELV_NOTE_AFTER_OUTB_DELV,
ktocd as REF_ACCT_GRP_ONE_TIME_ACCT,
pfort as PO_BOX_CITY,
werks as PLNT,
dtams as DATA_MED_EXCH_IND,
dtaws as INSTR_KEY_DATA_MED_EXCH,
duefl as STS_DATA_TFR_SUBSQ_RLSE,
hzuor as ASGNMT_HIER,
sperz as PMT_BLK,
etikg as CUST_GRP,
civve as ID_MN_NON_MIL_USE,
milve as ID_MN_MIL_USE,
kdkg1 as CUST_COND_GRP_1,
kdkg2 as CUST_COND_GRP_2,
kdkg3 as CUST_COND_GRP_3,
kdkg4 as CUST_COND_GRP_4,
kdkg5 as CUST_COND_GRP_5,
xknza as ALT_PYR_ACCT_NUM_IND,
fityp as TAX_TYPE,
stcdt as TAX_NUM_TYPE,
stcd3 as TAX_NUM3,
stcd4 as TAX_NUM4,
xicms as CUST_IS_ICMS_EXPT,
xxipi as CUST_IS_IPI_EXPT,
xsubt as CUST_GRP_TAX_SUBST,
cfopc as CUST_CFOP_CAT,
txlw1 as TAX_LAW_ICMS,
txlw2 as TAX_LAW_IPI,
ccc01 as BIOCHEM_WF_IND,
ccc02 as NUCLR_NP_IND,
ccc03 as NATL_SCTY_IND,
ccc04 as MISSILE_TECH_IND,
cassd as CENT_SLS_BLK_CUST,
knurl as UNIFM_RSRS_LCTR,
current_timestamp() as crt_dttm,
current_timestamp() as updt_dttm
from source
)
select * from final
