with source as (
    select * from {{ ref('ntaedw_integration__vw_kr_gt_sellout') }}
),
final as (
    select
        ims_txn_dt as "ims_txn_dt",
        dstr_cd as "dstr_cd",
        dstr_nm as "dstr_nm",
        cust_cd as "cust_cd",
        cust_nm as "cust_nm",
        prod_nm as "prod_nm",
        ean_num as "ean_num",
        ctry_cd as "ctry_cd",
        crncy_cd as "crncy_cd",
        sap_code as "sap_code",
        sku_type as "sku_type",
        unit_prc as "unit_prc",
        sls_amt as "sls_amt",
        sls_qty as "sls_qty",
        cal_day as "cal_day",
        fisc_yr as "fisc_yr",
        fisc_wk_num as "fisc_wk_num",
        fisc_per as "fisc_per",
        ex_rt_typ as "ex_rt_typ",
        from_crncy as "from_crncy",
        to_crncy as "to_crncy",
        vld_from as "vld_from",
        ex_rt as "ex_rt",
        sap_matl_num as "sap_matl_num",
        prod_hier_l1 as "prod_hier_l1",
        prod_hier_l2 as "prod_hier_l2",
        prod_hier_l3 as "prod_hier_l3",
        prod_hier_l4 as "prod_hier_l4",
        prod_hier_l5 as "prod_hier_l5",
        prod_hier_l6 as "prod_hier_l6",
        prod_hier_l7 as "prod_hier_l7",
        prod_hier_l8 as "prod_hier_l8",
        prod_hier_l9 as "prod_hier_l9",
        store_typ as "store_typ",
        channel as "channel",
        sls_grp as "sls_grp",
        lcl_prod_nm as "lcl_prod_nm",
        sub_customer_code as "sub_customer_code",
        sub_customer_name as "sub_customer_name",
        sales_priority as "sales_priority",
        sales_stores as "sales_stores",
        sales_rate as "sales_rate"
    from source
)
select * from final