with source as (
    select * from ntaedw_integration.v_rpt_pos_offtake_daily_nonkorea
),
final as (
    select
        pos_dt as "pos_dt",
        fisc_per as "fisc_per",
        fisc_wk as "fisc_wk",
        fisc_wk_strt_dt as "fisc_wk_strt_dt",
        fisc_wk_end_dt as "fisc_wk_end_dt",
        promo_per as "promo_per",
        promo_wk as "promo_wk",
        promo_wk_strt_dt as "promo_wk_strt_dt",
        promo_wk_end_dt as "promo_wk_end_dt",
        univ_per as "univ_per",
        univ_wk as "univ_wk",
        univ_wk_strt_dt as "univ_wk_strt_dt",
        univ_wk_end_dt as "univ_wk_end_dt",
        sls_qty as "sls_qty",
        sls_amt_customer as "sls_amt_customer",
        invnt_qty as "invnt_qty",
        invnt_amt as "invnt_amt",
        sls_amt as "sls_amt",
        str_cd as "str_cd",
        str_nm as "str_nm",
        crncy_cd as "crncy_cd",
        src_sys_cd as "src_sys_cd",
        ctry_nm as "ctry_nm",
        sls_grp as "sls_grp",
        sls_grp_cd as "sls_grp_cd",
        sold_to_party as "sold_to_party",
        my_sls_brand_nm as "my_sls_brand_nm",
        mysls_catg as "mysls_catg",
        vend_prod_cd as "vend_prod_cd",
        matl_num as "matl_num",
        matl_desc as "matl_desc",
        ean_num as "ean_num",
        to_crncy as "to_crncy",
        ex_rt_typ as "ex_rt_typ",
        ex_rt as "ex_rt",
        channel as "channel",
        store_typ as "store_typ",
        cust_hier_l1 as "cust_hier_l1",
        cust_hier_l2 as "cust_hier_l2",
        cust_hier_l3 as "cust_hier_l3",
        cust_hier_l4 as "cust_hier_l4",
        cust_hier_l5 as "cust_hier_l5",
        prod_hier_l1 as "prod_hier_l1",
        prod_hier_l2 as "prod_hier_l2",
        prod_hier_l3 as "prod_hier_l3",
        prod_hier_l4 as "prod_hier_l4",
        prod_hier_l5 as "prod_hier_l5",
        prod_hier_l6 as "prod_hier_l6",
        prod_hier_l7 as "prod_hier_l7",
        prod_hier_l8 as "prod_hier_l8",
        prod_hier_l9 as "prod_hier_l9",
        price as "price",
        lcl_prod_nm as "lcl_prod_nm"
    from source
)
select * from final