with source as (
    select * from {{ ref('ntaedw_integration__v_rpt_dly_plan_ims_enrich') }}
),
final as (
    select
        ims_txn_dt as "ims_txn_dt",
        fisc_per as "fisc_per",
        fisc_wk as "fisc_wk",
        no_of_wks as "no_of_wks",
        fisc_wk_num as "fisc_wk_num",
        visit_dt as "visit_dt",
        visit_jj_mnth_id as "visit_jj_mnth_id",
        visit_jj_wk_no as "visit_jj_wk_no",
        visit_jj_wkdy_no as "visit_jj_wkdy_no",
        visit_end_dt as "visit_end_dt",
        actl_ims_txn_dt as "actl_ims_txn_dt",
        ctry_cd as "ctry_cd",
        dstr_cd as "dstr_cd",
        dstr_nm as "dstr_nm",
        sls_rep_cd as "sls_rep_cd",
        sls_rep_typ as "sls_rep_typ",
        sls_rep_nm as "sls_rep_nm",
        store_cd as "store_cd",
        store_nm as "store_nm",
        store_class as "store_class",
        from_crncy_cd as "from_crncy_cd",
        dly_store_tgt as "dly_store_tgt",
        dly_plan_flg as "dly_plan_flg",
        prod_cd as "prod_cd",
        non_sellable_product as "non_sellable_product",
        prod_hier_l1 as "prod_hier_l1",
        prod_hier_l2 as "prod_hier_l2",
        prod_hier_l3 as "prod_hier_l3",
        prod_hier_l4 as "prod_hier_l4",
        prod_hier_l5 as "prod_hier_l5",
        prod_hier_l6 as "prod_hier_l6",
        prod_hier_l7 as "prod_hier_l7",
        prod_hier_l8 as "prod_hier_l8",
        prod_hier_l9 as "prod_hier_l9",
        prnt_prod_hier_l9 as "prnt_prod_hier_l9",
        sap_matl_num as "sap_matl_num",
        lcl_prod_nm as "lcl_prod_nm",
        msl_flg as "msl_flg",
        period_sls_amt as "period_sls_amt",
        dly_prod_cnt as "dly_prod_cnt",
        store_sls_amt as "store_sls_amt",
        ean_num as "ean_num",
        prnt_ean_num as "prnt_ean_num",
        to_crncy as "to_crncy",
        ex_rt as "ex_rt",
        sls_amt as "sls_amt",
        sls_qty as "sls_qty",
        rtrn_qty as "rtrn_qty",
        rtrn_amt as "rtrn_amt",
        hq as "hq",
        store_type as "store_type",
        sell_in_price_manual as "sell_in_price_manual",
        sell_out_unit_price as "sell_out_unit_price"
    from source
)
select * from final