with source as (
    select * from {{ ref('ntaedw_integration__v_rpt_kr_trade_promotion') }}
),
final as (
    select
        promo_begin_date as "promo_begin_date",
        promo_end_date as "promo_end_date",
        ctry_cd as "ctry_cd",
        crncy_cd as "crncy_cd",
        fisc_wk as "fisc_wk",
        fisc_yr as "fisc_yr",
        fisc_mon as "fisc_mon",
        year as "year",
        week as "week",
        month as "month",
        customer_code as "customer_code",
        customer_name as "customer_name",
        store_typ as "store_typ",
        customer_channel as "customer_channel",
        sls_grp as "sls_grp",
        sls_ofc as "sls_ofc",
        sls_ofc_desc as "sls_ofc_desc",
        sls_grp_cd as "sls_grp_cd",
        activity_name as "activity_name",
        material_code as "material_code",
        ean as "ean",
        prod_hier_l1 as "prod_hier_l1",
        prod_hier_l2 as "prod_hier_l2",
        prod_hier_l3 as "prod_hier_l3",
        prod_hier_l4 as "prod_hier_l4",
        prod_hier_l5 as "prod_hier_l5",
        prod_hier_l6 as "prod_hier_l6",
        prod_hier_l7 as "prod_hier_l7",
        prod_hier_l8 as "prod_hier_l8",
        prod_hier_l9 as "prod_hier_l9",
        unit_tpr_price as "unit_tpr_price",
        estimated_quantity as "estimated_quantity",
        estimated_unit_price as "estimated_unit_price",
        estimated_amount_lcy as "estimated_amount_lcy",
        estimated_amount_usd as "estimated_amount_usd",
        actual_quantity as "actual_quantity",
        actual_quantity_pc as "actual_quantity_pc",
        actual_unit_price as "actual_unit_price",
        actual_amount_lcy as "actual_amount_lcy",
        actual_amount_usd as "actual_amount_usd",
        application_code as "application_code",
        remark as "remark"
    from source
)
select * from final