with source as (
    select * from {{ ref('ntaedw_integration__edw_vw_kr_tp_tracker') }}
),
final as (
    select
        identifier as "identifier",
        sls_org as "sls_org",
        matl_num as "matl_num",
        cust_num as "cust_num",
        acct_num as "acct_num",
        sls_ofc as "sls_ofc",
        ctry_nm as "ctry_nm",
        ctry_key as "ctry_key",
        sls_grp as "sls_grp",
        caln_day as "caln_day",
        caln_yr_mo as "caln_yr_mo",
        fisc_yr as "fisc_yr",
        fisc_yr_per as "fisc_yr_per",
        b3_base_prod as "b3_base_prod",
        b4_var as "b4_var",
        b5_put_up as "b5_put_up",
        b1_mega_brnd as "b1_mega_brnd",
        b2_brnd as "b2_brnd",
        prod_minor as "prod_minor",
        prod_maj as "prod_maj",
        prod_fran as "prod_fran",
        fran as "fran",
        matl_sls as "matl_sls",
        prod_hier as "prod_hier",
        amt_obj_crncy as "amt_obj_crncy",
        nts_actuals as "nts_actuals",
        tp_actuals as "tp_actuals",
        nts_qty as "nts_qty",
        tp_qty as "tp_qty",
        sls_grp_desc as "sls_grp_desc",
        sls_ofc_desc as "sls_ofc_desc",
        matl_desc as "matl_desc",
        mega_brnd_desc as "mega_brnd_desc",
        brnd_desc as "brnd_desc",
        varnt_desc as "varnt_desc",
        base_prod_desc as "base_prod_desc",
        put_up_desc as "put_up_desc",
        channel as "channel",
        med_desc as "med_desc",
        edw_cust_nm as "edw_cust_nm",
        from_crncy as "from_crncy",
        to_crncy as "to_crncy",
        ex_rt_typ as "ex_rt_typ",
        ex_rt as "ex_rt",
        acct_hier_desc as "acct_hier_desc",
        acct_hier_shrt_desc as "acct_hier_shrt_desc",
        company_nm as "company_nm",
        ean_num as "ean_num",
        prod_hier_lvl1 as "prod_hier_lvl1",
        prod_hier_lvl2 as "prod_hier_lvl2",
        prod_hier_lvl3 as "prod_hier_lvl3",
        prod_hier_lvl4 as "prod_hier_lvl4",
        prod_hier_lvl5 as "prod_hier_lvl5",
        prod_hier_lvl6 as "prod_hier_lvl6",
        prod_hier_lvl7 as "prod_hier_lvl7",
        prod_hier_lvl8 as "prod_hier_lvl8",
        prod_hier_lvl9 as "prod_hier_lvl9",
        store_type as "store_type",
        account_classification as "account_classification",
        target_type as "target_type",
        tgt_value_per as "tgt_value_per",
        tgt_value as "tgt_value"
    from source
)
select * from final