with source as (
    select * from {{ ref('ntaedw_integration__v_rpt_invc') }}
),
final as (
    select
        sls_doc_typ as "sls_doc_typ",
        billing_type as "billing_type",
        cust_no as "cust_no",
        fisc_yr as "fisc_yr",
        fisc_mo as "fisc_mo",
        cal_day as "cal_day",
        fisc_wk_num as "fisc_wk_num",
        sls_ofc_cv_cd as "sls_ofc_cv_cd",
        sls_ofc_cv as "sls_ofc_cv",
        sls_grp_cv_cd as "sls_grp_cv_cd",
        sls_grp_cv as "sls_grp_cv",
        sls_ofc_cy as "sls_ofc_cy",
        mega_brnd_cd as "mega_brnd_cd",
        brnd_desc as "brnd_desc",
        mother_sku as "mother_sku",
        prod_hier_l2 as "prod_hier_l2",
        prod_hier_l3 as "prod_hier_l3",
        category_1 as "category_1",
        categroy_2 as "categroy_2",
        platform_ca as "platform_ca",
        core_plat as "core_plat",
        prod_hier_l9 as "prod_hier_l9",
        key_acct_nm as "key_acct_nm",
        channel as "channel",
        store_cd as "store_cd",
        store_nm as "store_nm",
        store_typ as "store_typ",
        mat as "mat",
        matl_desc as "matl_desc",
        ean_num as "ean_num",
        tot_invc_val as "tot_invc_val",
        tot_invc_qty as "tot_invc_qty",
        country as "country",
        edw_cust_nm as "edw_cust_nm",
        currency as "currency",
        from_crncy as "from_crncy",
        to_crncy as "to_crncy",
        ex_rt_typ as "ex_rt_typ",
        ex_rt as "ex_rt",
        country_cd as "country_cd",
        company_nm as "company_nm",
        current_fisc_per as "current_fisc_per"
    from source
)
select * from final