with source as (
    select * from {{ ref('ntaedw_integration__v_kr_ecommerce_sellout') }}
),
final as (
    select
        country as "country",
        product_name as "product_name",
        distributor_code as "distributor_code",
        distributor_name as "distributor_name",
        subcustomer_name as "subcustomer_name",
        ean as "ean",
        ex_rt as "ex_rt",
        sales_qty as "sales_qty",
        sales_value_lcy as "sales_value_lcy",
        from_crncy as "from_crncy",
        to_crncy as "to_crncy",
        fisc_year as "fisc_year",
        fisc_month as "fisc_month",
        fisc_day as "fisc_day",
        cal_year as "cal_year",
        cal_month as "cal_month",
        cal_day as "cal_day",
        fisc_wk as "fisc_wk",
        ims_txn_dt as "ims_txn_dt",
        gcph_franchise as "gcph_franchise",
        gcph_brand as "gcph_brand",
        gcph_subbrand as "gcph_subbrand",
        gcph_variant as "gcph_variant",
        put_up_description as "put_up_description",
        gcph_needstate as "gcph_needstate",
        gcph_category as "gcph_category",
        gcph_subcategory as "gcph_subcategory",
        gcph_segment as "gcph_segment",
        gcph_subsegment as "gcph_subsegment",
        jnj_sku_code as "jnj_sku_code",
        sku_type as "sku_type",
        prod_hier_l1 as "prod_hier_l1",
        prod_hier_l2 as "prod_hier_l2",
        prod_hier_l3 as "prod_hier_l3",
        prod_hier_l4 as "prod_hier_l4",
        prod_hier_l5 as "prod_hier_l5",
        prod_hier_l6 as "prod_hier_l6",
        prod_hier_l7 as "prod_hier_l7",
        prod_hier_l8 as "prod_hier_l8",
        prod_hier_l9 as "prod_hier_l9",
        store_type as "store_type",
        sls_grp as "sls_grp",
        sls_grp_cd as "sls_grp_cd"
    from source
)
select * from final