with source as (
    select * from {{ ref('ntaedw_integration__v_rpt_copa') }}
),
final as (
    select
        cntry_key as "cntry_key",
        acct_num as "acct_num",
        cust_num as "cust_num",
        channel as "channel",
        prft_ctr as "prft_ctr",
        matl as "matl",
        matl_desc as "matl_desc",
        ean_num as "ean_num",
        prod_hier_lvl1 as "prod_hier_lvl1",
        prod_hier_lvl2 as "prod_hier_lvl2",
        prod_hier_lvl3 as "prod_hier_lvl3",
        mega_brnd_desc as "mega_brnd_desc",
        brnd_desc as "brnd_desc",
        prod_minor as "prod_minor",
        sls_grp as "sls_grp",
        sls_grp_desc as "sls_grp_desc",
        sls_ofc as "sls_ofc",
        sls_ofc_desc as "sls_ofc_desc",
        category_1 as "category_1",
        categroy_2 as "categroy_2",
        platform_ca as "platform_ca",
        prod_hier_lvl8 as "prod_hier_lvl8",
        prod_hier_lvl9 as "prod_hier_lvl9",
        amt_obj_crncy as "amt_obj_crncy",
        obj_crncy_co_obj as "obj_crncy_co_obj",
        edw_cust_nm as "edw_cust_nm",
        from_crncy as "from_crncy",
        to_crncy as "to_crncy",
        ex_rt_typ as "ex_rt_typ",
        ex_rt as "ex_rt",
        brand_group as "brand_group",
        fisc_day as "fisc_day",
        fisc_yr_per as "fisc_yr_per",
        caln_day as "caln_day",
        caln_yr_mo as "caln_yr_mo",
        qty as "qty",
        uom as "uom",
        acct_hier_desc as "acct_hier_desc",
        acct_hier_shrt_desc as "acct_hier_shrt_desc",
        cntry_cd as "cntry_cd",
        company_nm as "company_nm",
        store_type as "store_type",
        plnt as "plnt"
    from source
)
select * from final