
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'DNA_CORE_ASP'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  DNA_CORE_ASP:
    access:
      materialized: view
      schema: CORE_ACCESS
    integration:
      materialized: table
      schema: CORE_INTEGRATION 
      arsadpprd001_raw:
        materialized: view
    asp_regional:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      aspedw_access:
        +materialized: view
        +schema: ASPEDW_ACCESS
      aspitg_integration:
        +materialized: table
        +schema: ASPITG_INTEGRATION
        +transient: false
        sap_and_sellin:
          staging:
            +materialized: view
      aspedw_integration:
        +materialized: table
        +transient: false
        +schema: ASPEDW_INTEGRATION
        sap_and_sellin:
          view:
            +materialized: view
      aspwks_integration:
        +materialized: table
        +schema: ASPWKS_INTEGRATION
    singapore:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      sgpedw_access:
        +materialized: view
        +schema: SGPEDW_ACCESS
      sgpedw_integration:
        +materialized: table
        +schema: SGPEDW_INTEGRATION
        +transient: false
        common:
          view:
            +materialized: view
        currency:
          master:
            view:
              +materialized: view
        listprice:
          master:
            view:
              +materialized: view
        pos:
          datamart:
            view:
              +materialized: view
        sellin:
          datamart:
            view:
              +materialized: view
      sgpitg_integration:
        +materialized: table
        +transient: false
        +schema: SGPITG_INTEGRATION
      sgpwks_integration:
        +materialized: table
        +schema: SGPWKS_INTEGRATION
    malaysia:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      mysitg_integration:
        +materialized: table
        +transient: false
        +schema: MYSITG_INTEGRATION
      mysedw_integration:
        +materialized: table
        +transient: false
        +schema: MYSEDW_INTEGRATION
        currency:
          master:
            view:
              +materialized: view
        customer:
          master:
            view:
              +materialized: view
        sellin:
            view:
              +materialized: view
      myswks_integration:
        +materialized: table
        +schema: MYSWKS_INTEGRATION