
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'DNA_CORE_ASP'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'default'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"
# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

vars:
  source_freshness_run_project_hooks: False
# In this example config, we tell dbt to build all models in the example/ directory
# as tables. These settings can be overridden in the individual model files
# using the `{{ config(...) }}` macro.
models:
  dbt_artifacts:
    +enabled: false
    sources:
      +enabled: true
      +database: "{{ env_var('DBT_ENV_CORE_DB') }}" # optional, default is your target database
      +schema: CORE_INTEGRATION
  DNA_CORE_ASP:
    access:
      materialized: view
      schema: CORE_ACCESS
    integration:
      materialized: table
      schema: CORE_INTEGRATION 
      arsadpprd001_raw:
        materialized: view
    asp_regional:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      aspedw_access:
        +materialized: view
        +schema: ASPEDW_ACCESS
      aspitg_integration:
        +materialized: table
        +schema: ASPITG_INTEGRATION
        +transient: false
        sap_and_sellin:
          staging:
            +materialized: view
      aspedw_integration:
        +materialized: table
        +transient: false
        +schema: ASPEDW_INTEGRATION
        sap_and_sellin:
          view:
            +materialized: view
        sfmc:
          view:
            +materialized: view
      aspwks_integration:
        +materialized: table
        +schema: ASPWKS_INTEGRATION
    singapore:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      sgpedw_access:
        +materialized: view
        +schema: SGPEDW_ACCESS
      sgpedw_integration:
        +materialized: table
        +schema: SGPEDW_INTEGRATION
        +transient: false
        common:
          view:
            +materialized: view
        currency:
          master:
            view:
              +materialized: view
        listprice:
          master:
            view:
              +materialized: view
        pos:
          datamart:
            view:
              +materialized: view
        sellin:
          datamart:
            view:
              +materialized: view
      sgpitg_integration:
        +materialized: table
        +transient: false
        +schema: SGPITG_INTEGRATION
      sgpwks_integration:
        +materialized: table
        +schema: SGPWKS_INTEGRATION
    malaysia:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      mysitg_integration:
        +materialized: table
        +transient: false
        +schema: MYSITG_INTEGRATION
      mysedw_integration:
        +materialized: table
        +transient: false
        +schema: MYSEDW_INTEGRATION
        currency:
          view:
            +materialized: view
        customer:
          view:
            +materialized: view
        sellin:
            view:
              +materialized: view
        customer_distributor:
            view:
              +materialized: view
        listprice:
            view:
              +materialized: view
        material:
            view:
              +materialized: view
        orders:
            view:
              +materialized: view
        pos:
            view:
              +materialized: view
        sellin_and_pos:
            view:
              +materialized: view
        sellin_and_sellout:
            view:
              +materialized: view
        sellout:
            view:
              +materialized: view
      myswks_integration:
        +materialized: table
        +schema: MYSWKS_INTEGRATION
      mysedw_access:
        +materialized: view
        +schema: MYSEDW_ACCESS
    vietnam:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      vnmitg_integration:
        +materialized: table
        +transient: false
        +schema: VNMITG_INTEGRATION
      vnmedw_integration:
        +materialized: table
        +transient: false
        +schema: VNMEDW_INTEGRATION
        customer:
          view:
            +materialized: view
        distributor_and_customer:
          view:
            +materialized: view
        material:
          view:
            +materialized: view
        pos:
          view:
            +materialized: view
        product:
          view:
            +materialized: view
        sales:
          view:
            +materialized: view
        sellin:
          view:
            +materialized: view
        sellin_and_sellout:
          view:
            +materialized: view
        sellout:
          view:
            +materialized: view
        sellthrgh:
          view:
            +materialized: view
      vnmwks_integration:
        +materialized: table
        +schema: VNMWKS_INTEGRATION
      vnmedw_access:
        +materialized: view
        +schema: VNMEDW_ACCESS
    thailand:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      thaitg_integration:
        +materialized: table
        +transient: false
        +schema: THAITG_INTEGRATION
      thaedw_integration:
        +materialized: table
        +transient: false
        +schema: THAEDW_INTEGRATION
        customer:
          view:
            +materialized: view
        distributor_and_customer:
          view:
            +materialized: view
        distributor_and_material:
          view:
            +materialized: view
        gt:
          view:
            +materialized: view
        inventory:
          view:
            +materialized: view
        jbp:
          view:
            +materialized: view
        market_share:
          view:
            +materialized: view
        material:
          view:
            +materialized: view
        mt:
          view:
            +materialized: view
        pos:
          view:
            +materialized: view
        sellin:
          view:
            +materialized: view
        sellin_and_sellout:
          view:
            +materialized: view
        sellout:
          view:
            +materialized: view
      thawks_integration:
        +materialized: table
        +schema: THAWKS_INTEGRATION
      thaedw_access:
        +materialized: view
        +schema: THAEDW_ACCESS
    pacific:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      pcfedw_integration:
        +materialized: table
        +transient: false
        +schema: PCFEDW_INTEGRATION
        currency_exchange:
          view:
            +materialized: view
        common:
          view:
            +materialized: view
        customer:
          view:
            +materialized: view
        forecast:
          view:
            +materialized: view
        material:
          view:
            +materialized: view
        product:
          view:
            +materialized: view
        sales:
          view:
            +materialized: view
        sellout:
          view:
            +materialized: view
      pcfitg_integration:
        +materialized: table
        +transient: false
        +schema: PCFITG_INTEGRATION
        sales:
          staging:
            +materialized: view
      pcfwks_integration:
        +materialized: table
        +schema: PCFWKS_INTEGRATION
      pcfedw_access:
        +materialized: view
        +schema: PCFEDW_ACCESS
    philippines:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      phledw_integration:
        +materialized: table
        +transient: false
        +schema: PHLEDW_INTEGRATION
        common:
          view:
            +materialized: view
        customer:
          view:
            +materialized: view
        material:
          view:
            +materialized: view
        npi:
          view:
            +materialized: view
        pos:
          view:
            +materialized: view
        sales:
          view:
            +materialized: view
        sellin:
          view:
            +materialized: view
        sellout:
          view:
            +materialized: view
        sfmc:
          view:
            +materialized: view
        sipos:
          view:
            +materialized: view
        siso:
          view:
            +materialized: view
      phlitg_integration:
        +materialized: table
        +transient: false
        +schema: PHLITG_INTEGRATION
      phlwks_integration:
        +materialized: table
        +schema: PHLWKS_INTEGRATION
      phledw_access:
        +materialized: view
        +schema: PHLEDW_ACCESS

    indonesia:
      config:
        +enabled: true
        +sql_header: "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
      idnedw_integration:
        +materialized: table
        +transient: false
        +schema: IDNEDW_INTEGRATION
      idnitg_integration:
        +materialized: table
        +transient: false
        +schema: IDNITG_INTEGRATION
      idnwks_integration:
        +materialized: table
        +schema: IDNWKS_INTEGRATION
      idnedw_access:
        +materialized: view
        +schema: IDNEDW_ACCESS