version: 2

sources:
  - name: phlsdl_raw
    database: "{{ env_var('DBT_ENV_LOAD_DB') }}"
    schema: phlsdl_raw
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: sdl_ph_as_watsons_inventory
        tags: ["j_rg_watsons_inv_ingestion","ingestion"]
        tests:
            - test_null__ff:
                not_null_columns: ["item_cd"]
                name: TRATBL_sdl_ph_as_watsons_inventory__test_null__ff
                config:
                  store_failures: true
                  schema: phlwks_integration
            - test_duplicate__ff:
                group_by_columns: ["item_cd","item_desc","total_units","total_cost","avg_sales_cost","wks_sup","remarks","br_ol_pl_ex","group_name","dept_name","class_name","sub_class_name","br_ol_pl_ex_subclass","subclass","catman","item_status","item_class","hold_reason_code","site_code","site_name","gwp","ret_non_ret","good_bad_13_wks","filename"]
                name: TRATBL_sdl_ph_as_watsons_inventory__test_duplicate__ff
                config:
                  store_failures: true
                  schema: phlwks_integration
            - test_lookup__ff:
                failure_reason: "SUBSCRIBER_KEY NOT PRESENT IN COMSUMER MASTER LOOK UP TABLE :"
                column: "nvl(item_cd, '#')"
                lookup_column: "nvl(item_cd, '#')"
                lookup_table: " {{ ref('phlitg_integration__itg_mds_ph_pos_product') }}"
                name: TRATBL_sdl_ph_as_watsons_inventory__test_lookup__ff
                config:
                  store_failures: true
                  schema: phlwks_integration

  - name: phlwks_integration
    database: "{{ env_var('DBT_ENV_CORE_DB') }}"
    schema: sshukl02_workspace
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: TRATBL_sdl_ph_as_watsons_inventory__test_null__ff
      - name: TRATBL_sdl_ph_as_watsons_inventory__test_duplicate__ff
      - name: TRATBL_sdl_ph_as_watsons_inventory__test_lookup__ff
      - name: TRATBL_sdl_ph_bp_trgt__null_test
      - name: TRATBL_sdl_ph_bp_trgt__duplicate_test
      - name: TRATBL_sdl_ph_bp_trgt__format_test
      - name: TRATBL_sdl_ph_clobotics_store_raw_data__null_test
      - name: TRATBL_sdl_ph_clobotics_store_raw_data__format_test1
      - name: TRATBL_sdl_ph_clobotics_store_raw_data__format_test2
      - name: TRATBL_sdl_ph_clobotics_store_raw_data__format_test3
      - name: TRATBL_sdl_ph_clobotics_survey_data__null_test
      - name: TRATBL_sdl_ph_clobotics_survey_data__format_test1
      - name: TRATBL_sdl_ph_clobotics_survey_data__format_test2
      - name: TRATBL_sdl_ph_clobotics_survey_data__format_test3
      - name: TRATBL_sdl_ph_clobotics_task_raw_data__null_test
      - name: TRATBL_sdl_ph_clobotics_task_raw_data__format_test1
      - name: TRATBL_sdl_ph_clobotics_task_raw_data__format_test2
      - name: TRATBL_sdl_ph_clobotics_task_raw_data__format_test3
      - name: TRATBL_sdl_ph_cpg_calls__null_test
      - name: TRATBL_sdl_ph_dms_sellout_sales_fact__null_test
      - name: TRATBL_sdl_ph_dms_sellout_sales_fact__lookup_test
      - name: TRATBL_sdl_ph_dms_sellout_stock_fact__lookup_test
      - name: TRATBL_sdl_ph_dms_sellout_stock_fact__null_test
      - name: TRATBL_sdl_ph_ecommerce_offtake_acommerce__null_test
      - name: TRATBL_sdl_ph_iop_trgt__null_test
      - name: TRATBL_sdl_ph_iop_trgt__duplicate_test
      - name: TRATBL_sdl_ph_iop_trgt__format_test
      - name: TRATBL_sdl_ph_iop_trgt__lookup_test_brand
      - name: TRATBL_sdl_ph_iop_trgt__lookup_test_segment
      - name: TRATBL_sdl_ph_iop_trgt__lookup_test_customer_code
      - name: TRATBL_sdl_ph_tbl_acctexec__null_test
      - name: TRATBL_sdl_ph_tbl_acctexec__duplicate_test
      - name: TRATBL_sdl_ph_tbl_isebranchmaster__null_test
      - name: TRATBL_sdl_ph_tbl_isebranchmaster__duplicate_test
      - name: TRATBL_sdl_ph_tbl_surveynotes__null_test
      - name: TRATBL_sdl_ph_tbl_surveynotes__duplicate_test
      - name: TRATBL_sdl_ph_tbl_surveyisequestion__null_test
      - name: TRATBL_sdl_ph_tbl_surveyisequestion__duplicate_test
      - name: TRATBL_sdl_ph_tbl_surveyisehdr__null_test
      - name: TRATBL_sdl_ph_tbl_surveyisehdr__duplicate_test
      - name: TRATBL_sdl_ph_tbl_surveycustomers__null_test
      - name: TRATBL_sdl_ph_tbl_surveycustomers__duplicate_test
      - name: TRATBL_sdl_ph_tbl_surveycpg__null_test
      - name: TRATBL_sdl_ph_tbl_surveycpg__duplicate_test
      - name: TRATBL_sdl_ph_tbl_surveychoices__null_test
      - name: TRATBL_sdl_ph_tbl_surveychoices__duplicate_test
      - name: TRATBL_sdl_ph_tbl_surveyanswers__null_test
      - name: TRATBL_sdl_ph_tbl_surveyanswers__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_landmark_ds__null_test
      - name: TRATBL_sdl_ph_non_ise_landmark_ds__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_landmark_ds__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_landmark_ds__lookup_test
      - name: TRATBL_sdl_ph_non_ise_landmark_sm__null_test
      - name: TRATBL_sdl_ph_non_ise_landmark_sm__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_landmark_sm__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_landmark_sm__lookup_test
      - name: TRATBL_sdl_ph_non_ise_puregold__null_test
      - name: TRATBL_sdl_ph_non_ise_puregold__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_puregold__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_puregold__lookup_test
      - name: TRATBL_sdl_ph_non_ise_robinsons_ds__null_test
      - name: TRATBL_sdl_ph_non_ise_robinsons_ds__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_robinsons_ds__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_robinsons__lookup_test
      - name: TRATBL_sdl_ph_non_ise_robinsons_sm__null_test
      - name: TRATBL_sdl_ph_non_ise_robinsons_sm__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_robinsons_sm__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_robinsons_sm__lookup_test
      - name: TRATBL_sdl_ph_non_ise_rustans__null_test
      - name: TRATBL_sdl_ph_non_ise_rustans__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_rustans__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_rustans__lookup_test
      - name: TRATBL_sdl_ph_non_ise_shm__null_test
      - name: TRATBL_sdl_ph_non_ise_shm__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_shm__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_shm__lookup_test
      - name: TRATBL_sdl_ph_non_ise_super_8__null_test
      - name: TRATBL_sdl_ph_non_ise_super_8__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_super_8__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_super_8__lookup_test
      - name: TRATBL_sdl_ph_non_ise_svi_smc__null_test
      - name: TRATBL_sdl_ph_non_ise_svi_smc__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_svi_smc__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_svi_smc__lookup_test
      - name: TRATBL_sdl_ph_non_ise_waltermart__null_test
      - name: TRATBL_sdl_ph_non_ise_waltermart__duplicate_test
      - name: TRATBL_sdl_ph_non_ise_waltermart__test_date_format_odd_eve_leap
      - name: TRATBL_sdl_ph_non_ise_waltermart__lookup_test
      - name: tratbl_sdl_ph_pos_sm_goods__null_test
      - name: tratbl_sdl_ph_pos_sm_goods__lookup_sm_CUST_CD
      - name: tratbl_sdl_ph_pos_sm_goods__lookup_sm_SAP_ITEM_CD
      - name: tratbl_sdl_ph_pos_sm_goods__lookup_sm_JNJ_PC_PER_CUST_UNIT
      - name: tratbl_sdl_ph_pos_sm_goods__lookup_sm_LST_PRICE_UNIT
      - name: tratbl_sdl_ph_pos_sm_goods__lookup_sm_PL_JJ_MNTH_ID
      - name: TRATBL_sdl_ph_sfmc_bounce_data__duplicate_test
      - name: TRATBL_sdl_ph_sfmc_bounce_data__null_test
      - name: TRATBL_sdl_ph_sfmc_bounce_data__format_test
      - name: TRATBL_sdl_ph_sfmc_children_data__test_null__ff
      - name: TRATBL_sdl_ph_sfmc_children_data__test_duplicate__ff
      - name: TRATBL_sdl_ph_sfmc_children_data__test_lookup__ff
      - name: TRATBL_sdl_ph_sfmc_click_data__test_null__ff
      - name: TRATBL_sdl_ph_sfmc_click_data__test_duplicate__ff
      - name: TRATBL_sdl_ph_sfmc_click_data__test_lookup__ff
      - name: TRATBL_sdl_ph_sfmc_complaint_data__test_null__ff
      - name: TRATBL_sdl_ph_sfmc_complaint_data__test_duplicate__ff
      - name: TRATBL_sdl_ph_sfmc_complaint_data__test_lookup__ff
      - name: TRATBL_sdl_ph_sfmc_complaint_data_format_test
      - name: TRATBL_sdl_ph_sfmc_consumer_master__test_null__ff
      - name: TRATBL_sdl_ph_sfmc_consumer_master__test_duplicate__ff
      - name: TRATBL_sdl_ph_sfmc_sent_data__test_null__ff
      - name: TRATBL_sdl_ph_sfmc_sent_data__test_duplicate__ff
      - name: TRATBL_sdl_ph_sfmc_sent_data__test_lookup__ff
      - name: TRATBL_sdl_ph_sfmc_sent_data_format_test
      - name: TRATBL_sdl_ph_sfmc_unsubscribe_data__test_null__ff
      - name: TRATBL_sdl_ph_sfmc_unsubscribe_data__test_duplicate__ff
      - name: TRATBL_sdl_ph_sfmc_unsubscribe_data__test_lookup__ff
      - name: TRATBL_sdl_ph_sfmc_unsubscribe_data_format_test
      - name: TRATBL_sdl_ph_sfmc_open_data__test_null__ff
      - name: TRATBL_sdl_ph_sfmc_open_data__test_duplicate__ff
      - name: TRATBL_sdl_ph_sfmc_open_data__test_lookup__ff
      - name: TRATBL_sdl_ph_sfmc_open_data_format_test
