with EDW_RPT_REGIONAL_SELLOUT_OFFTAKE as(
    select * from {{ source('aspedw_integration', 'edw_rpt_regional_sellout_offtake') }}
),
WKS_TH_REGIONAL_SELLOUT_MAPPED_SKU_CD as(
    select * from {{ ref('thawks_integration__wks_th_regional_sellout_mapped_sku_cd') }}
),
edw_vw_cal_Retail_excellence_Dim as(
    select * from {{ source('aspedw_integration', 'edw_vw_cal_retail_excellence_dim') }}
),

transformation as (SELECT  COUNTRY_CODE AS CNTRY_CD,
            MD5(NVL (DISTRIBUTOR_CODE,'DC') ||NVL (STORE_CODE,'SC') ||NVL (DISTRIBUTOR_NAME,'DN')||nvl (MAPPED_SKU_Code,'SKU')||nvl(EAN_CODE,'EAN')||NVL (CHANNEL,'CH')||nvl (MAPPED_SKU_DESCRIPTION,'SKU_DESC')
            || NVL (STORE_TYPE,'ST') || NVL (STORE_NAME,'SN')||NVL (SAP_PARENT_CUSTOMER_KEY,'SPCK') ||NVL (SAP_PARENT_CUSTOMER_DESCRIPTION,'SPSCD')
            || NVL (SAP_CUSTOMER_CHANNEL_KEY,'SCCK') ||NVL (SAP_CUSTOMER_CHANNEL_DESCRIPTION,'SCCD') ||NVL (SAP_CUSTOMER_SUB_CHANNEL_KEY,'SCSCK') ||NVL (SAP_SUB_CHANNEL_DESCRIPTION,'SSCD')
            ||NVL (CUSTOMER_SEGMENT_KEY,'CSK') ||NVL (CUSTOMER_SEGMENT_DESCRIPTION,'CSD') || NVL (SAP_GO_TO_MDL_KEY,'SGMK') ||NVL (SAP_GO_TO_MDL_DESCRIPTION,'SGMD')
            ||NVL (SAP_BANNER_KEY,'SBK')||NVL(soldto_code,'STC')
            ||NVL (SAP_BANNER_DESCRIPTION,'SBD') ||NVL (SAP_BANNER_FORMAT_KEY,'SBFK') ||NVL (SAP_BANNER_FORMAT_DESCRIPTION,'SBFD') ||NVL (RETAIL_ENVIRONMENT,'RE')
            || NVL (GLOBAL_PRODUCT_FRANCHISE,'GPF') ||NVL (GLOBAL_PRODUCT_BRAND,'GPB') ||NVL (GLOBAL_PRODUCT_SUB_BRAND,'GPSB') || NVL (GLOBAL_PRODUCT_VARIANT,'GPV')
            ||NVL (GLOBAL_PRODUCT_SEGMENT,'GPS') ||NVL (GLOBAL_PRODUCT_SUBSEGMENT,'GPSS') || NVL (GLOBAL_PRODUCT_CATEGORY,'GPC') ||NVL (GLOBAL_PRODUCT_SUBCATEGORY,'GPSC')
            ||NVL (GLOBAL_PUT_UP_DESCRIPTION,'GPUD') ||NVL (PKA_PRODUCT_KEY,'PK')||NVL (REGION,'RG')||NVL (ZONE,'ZONE')||NVL(PKA_PRODUCT_KEY_DESCRIPTION,'PKD')) AS SELLOUT_DIM_KEY,
             COUNTRY_NAME AS CNTRY_NM,
             DATA_SOURCE AS DATA_SRC,
             DISTRIBUTOR_CODE,
             DISTRIBUTOR_NAME,
             STORE_CODE,
             STORE_TYPE,
             STORE_NAME,
             EAN_CODE,
             MAPPED_SKU_Code,
             MAPPED_SKU_DESCRIPTION,
             YEAR,
             MNTH_ID,
             soldto_code,
             SAP_PARENT_CUSTOMER_KEY,
             SAP_PARENT_CUSTOMER_DESCRIPTION,
             SAP_CUSTOMER_CHANNEL_KEY,
             SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             SAP_CUSTOMER_SUB_CHANNEL_KEY,
             SAP_SUB_CHANNEL_DESCRIPTION,
             SAP_GO_TO_MDL_KEY,
             SAP_GO_TO_MDL_DESCRIPTION,
             SAP_BANNER_KEY,
             SAP_BANNER_DESCRIPTION,
             SAP_BANNER_FORMAT_KEY,
             SAP_BANNER_FORMAT_DESCRIPTION,
             RETAIL_ENVIRONMENT,
             CHANNEL,
             REGION,
             ZONE,
             CUSTOMER_SEGMENT_KEY,
             CUSTOMER_SEGMENT_DESCRIPTION,
             GLOBAL_PRODUCT_FRANCHISE,
             GLOBAL_PRODUCT_BRAND,
             GLOBAL_PRODUCT_SUB_BRAND,
             GLOBAL_PRODUCT_VARIANT,
             GLOBAL_PRODUCT_SEGMENT,
             GLOBAL_PRODUCT_SUBSEGMENT,
             GLOBAL_PRODUCT_CATEGORY,
             GLOBAL_PRODUCT_SUBCATEGORY,
             GLOBAL_PUT_UP_DESCRIPTION,
             PKA_PRODUCT_KEY,
             PKA_PRODUCT_KEY_DESCRIPTION,
            SUM(SELLOUT_SALES_QUANTITY) AS SLS_QTY,
            SUM(SELLOUT_SALES_VALUE) AS SLS_VALUE,
            CAST(AVG(SELLOUT_SALES_QUANTITY) AS numeric(38,6)) AS AVG_QTY,		--// AVG
            SUM(SALES_VALUE_LIST_PRICE)AS SALES_VALUE_LIST_PRICE,
SYSDATE()	as created_date	--// SYSDATE
    FROM (SELECT COUNTRY_CODE,
                COUNTRY_NAME,
                 MAIN.DISTRIBUTOR_NAME||'#'||LTRIM(MAIN.Distributor_CODE,'0') AS Distributor_Name,		--//                  MAIN.Distributor_Name||'#'||LTRIM(MAIN.Distributor_CODE,'0') AS Distributor_Name,
                 DISTRIBUTOR_CODE,
                 soldto_code,
                 store_code,
		         MAIN.STORE_NAME||'#'||ltrim(MAIN.STORE_CODE,'0') AS STORE_NAME,		--// 		         MAIN.STORE_Name||'#'||ltrim(MAIN.STORE_CODE,'0') AS STORE_NAME,
		         store_type,
                 EAN_CODE,
                 PD.SKU_CODE as MAPPED_SKU_Code,		--//                  pd.sku_code as MAPPED_SKU_Code,
                 PD.SKU_DESCRIPTION as MAPPED_sku_description,		--//                  pd.sku_description as MAPPED_sku_description,
                 DATA_Source,
                 YEAR AS YEAR,
                 MNTH_ID AS MNTH_ID,
                 --CUSTOMER_PRODUCT_DESC,
                 SAP_PARENT_CUSTOMER_KEY,
                 SAP_PARENT_CUSTOMER_DESCRIPTION,
                 SAP_CUSTOMER_CHANNEL_KEY,
                 SAP_CUSTOMER_CHANNEL_DESCRIPTION,
                 SAP_CUSTOMER_SUB_CHANNEL_KEY,
                 SAP_SUB_CHANNEL_DESCRIPTION,
                 SAP_GO_TO_MDL_KEY,
                 SAP_GO_TO_MDL_DESCRIPTION,
                 SAP_BANNER_KEY,
                 SAP_BANNER_DESCRIPTION,
                 SAP_BANNER_FORMAT_KEY,
                 SAP_BANNER_FORMAT_DESCRIPTION,
                 RETAIL_ENVIRONMENT,
                 CHANNEL,
                 REGION,
                 ZONE,
                 CUSTOMER_SEGMENT_KEY,
                 CUSTOMER_SEGMENT_DESCRIPTION,
                 GLOBAL_PRODUCT_FRANCHISE,
                 GLOBAL_PRODUCT_BRAND,
                 GLOBAL_PRODUCT_SUB_BRAND,
                 GLOBAL_PRODUCT_VARIANT,
                 GLOBAL_PRODUCT_SEGMENT,
                 GLOBAL_PRODUCT_SUBSEGMENT,
                 GLOBAL_PRODUCT_CATEGORY,
                 GLOBAL_PRODUCT_SUBCATEGORY,
                 GLOBAL_PUT_UP_DESCRIPTION,
                 PKA_PRODUCT_KEY,
                 PKA_PRODUCT_KEY_DESCRIPTION,
                 SELLOUT_SALES_QUANTITY,
                 SELLOUT_SALES_VALUE,
                 SALES_VALUE_LIST_PRICE
          FROM (SELECT COUNTRY_CODE,
                COUNTRY_NAME,
                 max(distributor_name) over (PARTITION BY LTRIM(DISTRIBUTOR_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS distributor_name,
                 LTRIM(DISTRIBUTOR_CODE,'0') as DISTRIBUTOR_CODE,
                 max(soldto_code) over ( PARTITION BY mnth_id,LTRIM(DISTRIBUTOR_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS  soldto_code,
                 LTRIM(STORE_CODE,'0') as STORE_CODE,
                 STORE_TYPE,
                 max(store_name) over (PARTITION BY LTRIM(STORE_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS STORE_NAME,
                 ltrim(MSL_PRODUCT_CODE,'0') AS EAN_CODE,
                 DATA_Source,
                 YEAR AS YEAR,
                 MNTH_ID AS MNTH_ID,
                 SAP_PARENT_CUSTOMER_KEY,
                 SAP_PARENT_CUSTOMER_DESCRIPTION,
                 SAP_CUSTOMER_CHANNEL_KEY,
                 SAP_CUSTOMER_CHANNEL_DESCRIPTION,
                 SAP_CUSTOMER_SUB_CHANNEL_KEY,
                 SAP_SUB_CHANNEL_DESCRIPTION,
                 SAP_GO_TO_MDL_KEY,
                 SAP_GO_TO_MDL_DESCRIPTION,
                 SAP_BANNER_KEY,
                 SAP_BANNER_DESCRIPTION,
                 SAP_BANNER_FORMAT_KEY,
                 SAP_BANNER_FORMAT_DESCRIPTION,
                 RETAIL_ENV AS RETAIL_ENVIRONMENT,
                 CHANNEL,
                 REGION,
                 ZONE_OR_AREA as ZONE,
                 CUSTOMER_SEGMENT_KEY,
                 CUSTOMER_SEGMENT_DESCRIPTION,
                 GLOBAL_PRODUCT_FRANCHISE,
                 GLOBAL_PRODUCT_BRAND,
                 GLOBAL_PRODUCT_SUB_BRAND,
                 GLOBAL_PRODUCT_VARIANT,
                 GLOBAL_PRODUCT_SEGMENT,
                 GLOBAL_PRODUCT_SUBSEGMENT,
                 GLOBAL_PRODUCT_CATEGORY,
                 GLOBAL_PRODUCT_SUBCATEGORY,
                 GLOBAL_PUT_UP_DESCRIPTION,
                 PKA_PRODUCT_KEY,
                 PKA_PRODUCT_KEY_DESCRIPTION,
                 SELLOUT_SALES_QUANTITY,
                 SELLOUT_SALES_VALUE,
                 sellout_value_list_price as SALES_VALUE_LIST_PRICE
                  FROM EDW_RPT_REGIONAL_SELLOUT_OFFTAKE		--//                   FROM RG_EDW.EDW_RPT_REGIONAL_SELLOUT_OFFTAKE
                 WHERE COUNTRY_NAME='Thailand'
                  AND   DATA_SOURCE IN ('SELL-OUT','POS')
                  /*and MNTH_ID >= (select last_36mnths from RG_EDW.EDW_VW_CAL_RETAIL_EXCELLENCE_DIM)::numeric		--//                   /*and MNTH_ID >= (select last_36mnths from rg_edw.edw_vw_cal_Retail_excellence_Dim)::numeric
	           and mnth_id <= (select  prev_mnth from RG_EDW.EDW_VW_CAL_RETAIL_EXCELLENCE_DIM)::numeric*/		--// 	           and mnth_id <= (select  prev_mnth from rg_edw.edw_vw_cal_Retail_excellence_Dim)::numeric*/
                ) MAIN
    	   LEFT JOIN WKS_TH_REGIONAL_SELLOUT_MAPPED_SKU_CD PD		--//     	   LEFT JOIN OS_WKS.WKS_TH_REGIONAL_SELLOUT_MAPPED_SKU_CD PD
            ON LTRIM(MAIN.EAN_CODE, '0')= LTRIM(PD.EAN, '0')		--//             ON LTRIM(main.EAN_CODE, '0')= LTRIM(PD.EAN, '0')
           )
    GROUP BY COUNTRY_CODE,
             COUNTRY_NAME,
             DATA_SOURCE,
             YEAR,
             MNTH_ID,
             DISTRIBUTOR_CODE,
            DISTRIBUTOR_NAME,
             STORE_CODE,
             STORE_NAME,
             STORE_TYPE,
             soldto_code,
             SAP_PARENT_CUSTOMER_KEY,
             SAP_PARENT_CUSTOMER_DESCRIPTION,
             SAP_CUSTOMER_CHANNEL_KEY,
             SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             SAP_CUSTOMER_SUB_CHANNEL_KEY,
             SAP_SUB_CHANNEL_DESCRIPTION,
             SAP_GO_TO_MDL_KEY,
             SAP_GO_TO_MDL_DESCRIPTION,
             SAP_BANNER_KEY,
             SAP_BANNER_DESCRIPTION,
             SAP_BANNER_FORMAT_KEY,
             SAP_BANNER_FORMAT_DESCRIPTION,
             RETAIL_ENVIRONMENT,
             CHANNEL,
             REGION,
             ZONE,
             CUSTOMER_SEGMENT_KEY,
             CUSTOMER_SEGMENT_DESCRIPTION,
             GLOBAL_PRODUCT_FRANCHISE,
             GLOBAL_PRODUCT_BRAND,
             GLOBAL_PRODUCT_SUB_BRAND,
             GLOBAL_PRODUCT_VARIANT,
             GLOBAL_PRODUCT_SEGMENT,
             GLOBAL_PRODUCT_SUBSEGMENT,
             GLOBAL_PRODUCT_CATEGORY,
             GLOBAL_PRODUCT_SUBCATEGORY,
             GLOBAL_PUT_UP_DESCRIPTION,
             EAN_CODE,
             MAPPED_SKU_CODE,
             mapped_SKU_DESCRIPTION,
             PKA_PRODUCT_KEY,
             PKA_PRODUCT_KEY_DESCRIPTION),

final as (
    select
    cntry_cd::varchar(2) AS cntry_cd,
sellout_dim_key::varchar(32) AS sellout_dim_key,
cntry_nm::varchar(50) AS cntry_nm,
data_src::varchar(14) AS data_src,
distributor_code::varchar(100) AS distributor_code,
distributor_name::varchar(356) AS distributor_name,
store_code::varchar(100) AS store_code,
store_type::varchar(255) AS store_type,
store_name::varchar(601) AS store_name,
ean_code::varchar(150) AS ean_code,
mapped_sku_code::varchar(40) AS mapped_sku_code,
mapped_sku_description::varchar(225) AS mapped_sku_description,
year::integer AS year,
mnth_id::varchar(23) AS mnth_id,
soldto_code::varchar(255) AS soldto_code,
sap_parent_customer_key::varchar(12) AS sap_parent_customer_key,
sap_parent_customer_description::varchar(75) AS sap_parent_customer_description,
sap_customer_channel_key::varchar(12) AS sap_customer_channel_key,
sap_customer_channel_description::varchar(75) AS sap_customer_channel_description,
sap_customer_sub_channel_key::varchar(12) AS sap_customer_sub_channel_key,
sap_sub_channel_description::varchar(75) AS sap_sub_channel_description,
sap_go_to_mdl_key::varchar(12) AS sap_go_to_mdl_key,
sap_go_to_mdl_description::varchar(75) AS sap_go_to_mdl_description,
sap_banner_key::varchar(12) AS sap_banner_key,
sap_banner_description::varchar(75) AS sap_banner_description,
sap_banner_format_key::varchar(12) AS sap_banner_format_key,
sap_banner_format_description::varchar(75) AS sap_banner_format_description,
retail_environment::varchar(150) AS retail_environment,
channel::varchar(150) AS channel,
region::varchar(150) AS region,
zone::varchar(150) AS zone,
customer_segment_key::varchar(12) AS customer_segment_key,
customer_segment_description::varchar(50) AS customer_segment_description,
global_product_franchise::varchar(30) AS global_product_franchise,
global_product_brand::varchar(30) AS global_product_brand,
global_product_sub_brand::varchar(100) AS global_product_sub_brand,
global_product_variant::varchar(100) AS global_product_variant,
global_product_segment::varchar(50) AS global_product_segment,
global_product_subsegment::varchar(100) AS global_product_subsegment,
global_product_category::varchar(50) AS global_product_category,
global_product_subcategory::varchar(50) AS global_product_subcategory,
global_put_up_description::varchar(100) AS global_put_up_description,
pka_product_key::varchar(68) AS pka_product_key,
pka_product_key_description::varchar(255) AS pka_product_key_description,
sls_qty::numeric(38,6) AS sls_qty,
sls_value::numeric(38,6) AS sls_value,
avg_qty::numeric(38,6) AS avg_qty,
sales_value_list_price::numeric(38,12) AS sales_value_list_price,
created_date::timestamp AS created_date
from transformation
)             

select * from final
