with wks_edw_pos_fact_korea as (
select * from DEV_DNA_CORE.SNAPNTAWKS_INTEGRATION.WKS_EDW_POS_FACT_KOREA
),
itg_pos_invoice_prc_lookup as (
select * from DEV_DNA_CORE.SNAPNTAITG_INTEGRATION.ITG_POS_INVOICE_PRC_LOOKUP
),
transformed as (
select 
src.pos_dt	,
src.vend_cd	,
src.vend_nm	,
src.prod_nm	,
src.vend_prod_cd	,
src.vend_prod_nm	,
src.brnd_nm	,
ltrim(src.ean_num,0) as ean_num	,
ltrim(src.str_cd,0) as str_cd	,
CASE
         WHEN src.str_nm IS NULL OR src.str_nm = '' THEN '#'
         ELSE trim(src.str_nm)
       END AS str_nm,
ltrim(src.sold_to_party,0) as sold_to_party	,
src.sls_grp	,
src.mysls_brnd_nm	,
src.sls_qty	,
src.sls_amt	,
src.unit_prc_amt	,
src.sls_excl_vat_amt	,
src.stk_rtrn_amt	,
src.stk_recv_amt	,
src.avg_sell_qty	,
src.cum_ship_qty	,
src.cum_rtrn_qty	,
src.web_ordr_takn_qty	,
src.web_ordr_acpt_qty	,
src.dc_invnt_qty	,
src.invnt_qty	,
src.invnt_amt	,
src.invnt_dt	,
src.serial_num	,
src.prod_delv_type	,
src.prod_type	,
src.dept_cd	,
src.dept_nm	,
src.spec_1_desc	,
src.spec_2_desc	,
src.cat_big	,
src.cat_mid	,
src.cat_small	,
src.dc_prod_cd	,
src.cust_dtls	,
src.dist_cd	,
src.crncy_cd	,
src.src_txn_sts	,
src.src_seq_num	,
src.src_sys_cd	,
src.ctry_cd	,
src.mysls_catg	,
lkp.matl_num	,
lkp.matl_desc	,
(src.sls_qty*lkp.calc_invoice_price)  as prom_sls_amt ,
lkp.calc_invoice_price as prom_prc_amt ,
src.hist_flg	,
src.sls_grp_cd	,
src.channel	,
src.store_type	,
src.crt_dttm	,
src.updt_dttm	 from 
wks_edw_pos_fact_korea src
left outer join 
itg_pos_invoice_prc_lookup lkp 
on src.pos_dt = lkp.pos_dt 
and ltrim (src.sold_to_party,0) = ltrim (lkp.sold_to_party ,0 )
and ltrim(src.ean_num,0) = ltrim (lkp.ean_num ,0 )
),
final as (
select
pos_dt::date as pos_dt,
vend_cd::varchar(40) as vend_cd,
vend_nm::varchar(100) as vend_nm,
prod_nm::varchar(100) as prod_nm,
vend_prod_cd::varchar(40) as vend_prod_cd,
vend_prod_nm::varchar(600) as vend_prod_nm,
brnd_nm::varchar(40) as brnd_nm,
ean_num::varchar(100) as ean_num,
str_cd::varchar(40) as str_cd,
str_nm::varchar(100) as str_nm,
sold_to_party::varchar(100) as sold_to_party,
sls_grp::varchar(100) as sls_grp,
mysls_brnd_nm::varchar(500) as mysls_brnd_nm,
sls_qty::number(18,0) as sls_qty,
sls_amt::number(16,5) as sls_amt,
unit_prc_amt::number(16,5) as unit_prc_amt,
sls_excl_vat_amt::number(16,5) as sls_excl_vat_amt,
stk_rtrn_amt::number(16,5) as stk_rtrn_amt,
stk_recv_amt::number(16,5) as stk_recv_amt,
avg_sell_qty::number(16,5) as avg_sell_qty,
cum_ship_qty::number(18,0) as cum_ship_qty,
cum_rtrn_qty::number(18,0) as cum_rtrn_qty,
web_ordr_takn_qty::number(18,0) as web_ordr_takn_qty,
web_ordr_acpt_qty::number(18,0) as web_ordr_acpt_qty,
dc_invnt_qty::number(18,0) as dc_invnt_qty,
invnt_qty::number(18,0) as invnt_qty,
invnt_amt::number(16,5) as invnt_amt,
invnt_dt::date as invnt_dt,
serial_num::varchar(40) as serial_num,
prod_delv_type::varchar(40) as prod_delv_type,
prod_type::varchar(40) as prod_type,
dept_cd::varchar(40) as dept_cd,
dept_nm::varchar(100) as dept_nm,
spec_1_desc::varchar(100) as spec_1_desc,
spec_2_desc::varchar(100) as spec_2_desc,
cat_big::varchar(100) as cat_big,
cat_mid::varchar(40) as cat_mid,
cat_small::varchar(40) as cat_small,
dc_prod_cd::varchar(40) as dc_prod_cd,
cust_dtls::varchar(100) as cust_dtls,
dist_cd::varchar(40) as dist_cd,
crncy_cd::varchar(10) as crncy_cd,
src_txn_sts::varchar(40) as src_txn_sts,
src_seq_num::number(18,0) as src_seq_num,
src_sys_cd::varchar(30) as src_sys_cd,
ctry_cd::varchar(10) as ctry_cd,
mysls_catg::varchar(500) as mysls_catg,
matl_num::varchar(40) as matl_num,
matl_desc::varchar(100) as matl_desc,
prom_sls_amt::number(27,5) as prom_sls_amt,
prom_prc_amt::number(16,5) as prom_prc_amt,
hist_flg::varchar(1) as hist_flg,
sls_grp_cd::varchar(20) as sls_grp_cd,
channel::varchar(25) as channel,
store_type::varchar(25) as store_type,
crt_dttm::timestamp_ntz(9) as crt_dttm,
updt_dttm::timestamp_ntz(9) as updt_dttm
from transformed)
select * from final
