with EDW_SALES_REPORTING as
(
  select * from {{ ref('pcfedw_integration__edw_sales_reporting') }}
),
VW_DEMAND_FORECAST_ANALYSIS as
(
  select * from {{ ref('pcfedw_integration__vw_demand_forecast_analysis') }}
),
EDW_GCH_PRODUCTHIERARCHY as
(
  select * from {{ ref('aspedw_integration__GMC_hierarchy_attributes') }}
),
VW_EDW_REG_EXCH_RATE as
(
  select * from {{ ref('aspedw_integration__vw_edw_reg_exch_rate') }}
),
EDW_CALENDAR_DIM as
(
  select * from {{ ref('aspedw_integration__edw_calendar_dim') }}
),
itg_list_price_sap as
(
  select * from {{ source('aspitg_integration','aspitg_integration__itg_list_price_sap') }}
),
sdl_pcf_price_list_exception as
(
  select * from {{ source('pcfsdl_raw', 'sdl_mds_pacific_rf_valuation_exception_list_price_adftemp') }}
),

sdl_pcf_brandcon_mapping as
(
  select * from {{ source('pcfsdl_raw', 'sdl_mds_pacific_brandcon_mapping_adftemp') }}
),

sdl_pcf_planning_channel_mapping as
(
  select * from {{ source('pcfsdl_raw', 'sdl_mds_pacific_planning_channel_mapping_adftemp') }}
),

--ACTUAL/PROMAX/BP 

VW_ACTUAL AS
(select DISTINCT
 sum(sales_qty) as actual_qty,
 sum(gts) as actual_gts,
 sum(nts_val) as actual_nts,
 cust_no ,
 bar_cd ,
 base_prod_cd ,
 base_prod_desc ,
SUM( bp_gts ) AS  bp_gts  ,
SUM( bp_nts ) AS  bp_nts ,
SUM( bp_qty ) as  bp_qty ,
 brnd_cd ,
 brnd_desc ,
 cmp_id ,
 country ,
 cust_curr_cd ,
 exch_rate ,
 fran_cd ,
 fran_desc ,
SUM( goal_gts ) as  goal_gts ,
SUM( goal_nts ) as  goal_nts ,
SUM( goal_qty ) as  goal_qty ,
 grp_fran_cd ,
 grp_fran_desc ,
 jj_mnth ,
 jj_mnth_shrt ,
 jj_period ,
 jj_qrtr ,
 jj_year ,
SUM( ju_gts ) as  ju_gts ,
SUM( ju_nts ) as  ju_nts ,
SUM( ju_qty ) as  ju_qty ,
 master_code ,
 matl_desc ,
 matl_id ,
 matl_type_cd ,
 matl_type_desc ,
 mega_brnd_cd ,
 mega_brnd_desc ,
 pac_source_type ,
 pac_subsource_type ,
 parent_matl_desc ,
 parent_matl_id ,
 pln_cnnl_cd ,
 post_cd ,
 prod_fran_cd ,
 prod_fran_desc ,
 prod_hier_cd ,
 prod_hier_desc ,
 prod_mjr_cd ,
 prod_mjr_desc ,
 prod_mnr_cd ,
 prod_mnr_desc ,
SUM( nu_gts ) AS  NU_gts  ,
SUM( nu_nts ) AS  NU_nts ,
SUM( nu_qty ) as  NU_qty ,
SUM( projected_nts ) as  projected_nts ,
SUM( projected_qty ) as  projected_qty ,
SUM( projected_gts_less_rtrn ) as  projected_gts ,
SUM( px_gts ) as  px_gts ,
SUM( px_nts ) as  px_nts ,
SUM( px_qty )as  px_qty ,
 sales_grp_desc 
from EDW_SALES_REPORTING 
where  jj_year >=EXTRACT(YEAR FROM CURRENT_DATE)-1
GROUP BY
sales_qty,
 gts,
 nts_val,
 cust_no ,
 bar_cd ,
 base_prod_cd ,
 base_prod_desc ,
 brnd_cd ,
 brnd_desc ,
 cmp_id ,
 country ,
 cust_curr_cd ,
 exch_rate ,
 fran_cd ,
 fran_desc ,
 grp_fran_cd ,
 grp_fran_desc,
 jj_mnth ,
 jj_mnth_shrt ,
 jj_period ,
 jj_qrtr ,
 jj_year ,
 master_code ,
 matl_desc ,
 matl_id ,
 matl_type_cd ,
 matl_type_desc ,
 mega_brnd_cd ,
 mega_brnd_desc ,
 pac_source_type ,
 pac_subsource_type ,
 parent_matl_desc ,
 parent_matl_id ,
 pln_cnnl_cd ,
 post_cd ,
 prod_fran_cd ,
 prod_fran_desc ,
 prod_hier_cd ,
 prod_hier_desc ,
 prod_mjr_cd ,
 prod_mjr_desc ,
 prod_mnr_cd ,
 prod_mnr_desc ,
 sales_grp_desc )

--APO 
,VW_APO as
(select
sum( apo_base_frcst ) as  apo_base_frcst ,
sum( apo_promo_frcst )as  apo_promo_frcst ,
sum( apo_tot_frcst )as  apo_tot_frcst ,
 bar_cd ,
 base_prod_cd ,
 base_prod_desc ,
 brnd_cd ,
 brnd_desc ,
 cmp_id ,
 country ,
 fran_cd ,
 fran_desc ,
 fcst_chnl ,
 fcst_chnl_desc ,
 grp_fran_cd ,
 grp_fran_desc ,
 jj_mnth ,
 jj_mnth_shrt ,
 jj_period ,
 jj_qrtr ,
 jj_year ,
 master_code ,
 matl_desc ,
 matl_no ,
 matl_type_cd ,
 matl_type_desc ,
 mega_brnd_cd ,
 mega_brnd_desc ,
 pac_source_type ,
 pac_subsource_type ,
 parent_id ,
 parent_matl_desc ,
 post_cd ,
 prod_fran_cd ,
 prod_fran_desc ,
 prod_hier_cd ,
 prod_hier_desc ,
 prod_mjr_cd ,
 prod_mjr_desc ,
 prod_mnr_cd ,
 prod_mnr_desc 
from VW_DEMAND_FORECAST_ANALYSIS
 where  pac_subsource_type ='SAPBW_APO_FORECAST' AND  jj_year >=EXTRACT(YEAR FROM CURRENT_DATE)
 group by
 bar_cd ,
 base_prod_cd ,
 base_prod_desc ,
 brnd_cd ,
 brnd_desc ,
 cmp_id ,
 country ,
 fran_cd ,
 fran_desc ,
 fcst_chnl ,
 fcst_chnl_desc ,
 grp_fran_cd ,
 grp_fran_desc ,
 jj_mnth ,
 jj_mnth_shrt ,
 jj_period ,
 jj_qrtr ,
 jj_year ,
 master_code ,
 matl_desc ,
 matl_no ,
 matl_type_cd ,
 matl_type_desc ,
 mega_brnd_cd ,
 mega_brnd_desc ,
 pac_source_type ,
 pac_subsource_type ,
 parent_id ,
 parent_matl_desc ,
 post_cd ,
 prod_fran_cd ,
 prod_fran_desc ,
 prod_hier_cd ,
 prod_hier_desc ,
 prod_mjr_cd ,
 prod_mjr_desc ,
 prod_mnr_cd ,
 prod_mnr_desc )

--LIST PRICE MAIN TABLE INTEGRATION FOR APO

,VW_LIST_PRICE AS
(select distinct ltrim(ITG_LIST.material,'0') AS material,ITG_LIST. VALID_TO ,ITG_LIST. DT_FROM ,
CASE
        WHEN cast(LEFT(ITG_LIST.DT_FROM, 6)as number) < APO. jj_period 
             AND cast(LEFT(ITG_LIST.VALID_TO, 6)as number) >= APO. jj_period  THEN ITG_LIST.AMOUNT
             ELSE NULL END AS  AMOUNT 
		,ITG_LIST.currency 
		from VW_APO APO
	LEFT JOIN itg_list_price_sap  ITG_LIST

ON apo. matl_no =ltrim(ITG_LIST.material,'0') and case when apo. country ='Australia' then 'AUD' when apo. country ='New Zealand' then 'NZD'
else null end =ITG_LIST.currency
where 
    cast(LEFT(ITG_LIST.DT_FROM, 6)as number) < APO. jj_period 
             AND cast(LEFT(ITG_LIST.VALID_TO, 6)as number) >= APO. jj_period  AND ITG_LIST.sls_org in ('3410','3300')
)

--EXCEPTION LIST PRICE INTEGRATION FOR APO

,VW_EXP_LIST AS 
( select distinct concat(e_list.country,'D') AS COUNTRY, ltrim(e_list.material_code,'0') AS product,e_list.list_price_local 
from  VW_APO APO
LEFT JOIN sdl_pcf_price_list_exception e_list

on  apo. matl_no =ltrim(e_list.material_code,'0')  and case when apo. country ='Australia' then 'AUD' when apo. country ='New Zealand' then 'NZD'
else null end =concat(e_list.country,'D')
WHERE e_list.list_price_local IS NOT NULL
)

--FINAL LIST PRICE CALCULATION FOR APO
 
,LIST_PRICE_CAL AS
(
select distinct
 apo_base_frcst ,
 apo_promo_frcst ,
 apo_tot_frcst ,
 bar_cd ,
 base_prod_cd ,
 base_prod_desc ,
 brnd_cd ,
 brnd_desc ,
 cmp_id ,
 apo.country ,
 fran_cd ,
 fran_desc ,
 GMC_SKU_CODE,
GMC_SKU_NAME,
UNIQUE_ID,
GMC_REGION,
GMC_CD,
GMC_DESCRIPTION,
GMC_CODE,
GMC_SUBCATEGORY_CODE,
GMC_SUBCATEGORY_NAME,
GMC_LABEL_BRAND_CODE,
GMC_LABEL_BRAND_NAME,
GMC_LABEL_SUBBRAND_CODE,
GMC_LABEL_SUBBRAND_NAME,
GMC_VARIANT_CODE,
GMC_VARIANT_NAME,
GMC_SUBVARIANT_CODE,
GMC_SUBVARIANT_NAME,
GMC_FLAVOR_CODE,
GMC_FLAVOR_NAME,
GMC_INGREDIENT_CODE,
GMC_INGREDIENT_NAME,
GMC_APPLICATION_CODE,
GMC_APPLICATION_NAME,
GMC_LENGTH_STRENGTH_CODE,
GMC_LENGTH_STRENGTH_NAME,
GMC_SHAPE_CODE,
GMC_SHAPE_NAME,
GMC_SPF_CONCENTRATION_CODE,
GMC_SPF_CONCENTRATION_NAME,
GMC_COVER_PRODUCT_TYPE_CODE,
GMC_COVER_PRODUCT_TYPE_NAME,
GMC_FORM_CODE,
GMC_FORM_NAME,
GMC_SIZE_CODE,
GMC_SIZE_NAME,
GMC_CHARACTERS_SPECIAL_EDITION_CODE,
GMC_CHARACTERS_SPECIAL_EDITION_NAME,
GMC_PACKAGE_CODE,
GMC_PACKAGE_NAME,
GMC_UOM_CODE,
GMC_UOM_NAME,
P4_BRAND_CATEGORY_CODE,
P4_BRAND_CATEGORY,
B2_SUB_BRAND_CODE,
B2_SUB_BRAND,
C5_SUB_CATEGORY_CODE,
C5_SUB_CATEGORY,
C1_BUSINESS_SEGMENT_CODE,
C1_BUSINESS_SEGMENT,
C2_BUSINESS_SUBSEGMENT_CODE,
C2_BUSINESS_SUBSEGMENT,
C3_NEED_STATE_CODE,
C3_NEED_STATE,
C4_CATEGORY_CODE,
C4_CATEGORY,
C5_SUBCATEGORY_CODE,
C5_SUBCATEGORY,
B1_BRAND_CODE,
B1_BRAND,
B2_SUBBRAND_CODE,
B2_SUBBRAND,
P1_CODE,
P1_BUSINESS_SEGMENT,
PS_CODE,
PS_BUSINESS_SUBSEGMENT,
P2_CODE,
P2_NEED_STATE,
P3_CODE,
P3_BRAND_CATEGORY,
P4_CODE,
P4_BRAND_CATEGORY_PLACEHOLDER,
 grp_fran_cd ,
 grp_fran_desc ,
 jj_mnth ,
 jj_mnth_shrt ,
 jj_period ,
 jj_qrtr ,
 jj_year ,
    CASE
        WHEN LIST_PRICE.AMOUNT IS NOT NULL THEN LIST_PRICE.AMOUNT
             WHEN EXP_LIST.list_price_local IS NOT NULL THEN EXP_LIST.list_price_local
			 ELSE '0.00'
    END AS  List_price ,
	LIST_PRICE. VALID_TO ,LIST_PRICE. DT_FROM ,
 master_code ,
 matl_desc ,
 matl_no ,
 matl_type_cd ,
 matl_type_desc ,
 mega_brnd_cd ,
 mega_brnd_desc ,
 pac_source_type ,
 pac_subsource_type ,
 parent_id ,
 parent_matl_desc ,
 fcst_chnl ,
 fcst_chnl_desc ,
 post_cd ,
 prod_fran_cd ,
 prod_fran_desc ,
 prod_hier_cd ,
 prod_hier_desc ,
 prod_mjr_cd ,
 prod_mjr_desc ,
 prod_mnr_cd ,
 prod_mnr_desc 

from VW_APO APO
LEFT JOIN VW_LIST_PRICE LIST_PRICE
ON APO. matl_no =LIST_PRICE.material
and cast(LEFT(DT_FROM, 6)as number) < APO. jj_period 
AND cast(LEFT(VALID_TO, 6)as number) >= APO. jj_period 
and case when apo. country ='Australia' then 'AUD' when apo. country ='New Zealand' then 'NZD'
else null end =LIST_PRICE.currency

LEFT JOIN VW_EXP_LIST EXP_LIST
ON APO. matl_no =EXP_LIST.PRODUCT 
and  case when apo. country ='Australia' then 'AUD' when apo. country ='New Zealand' then 'NZD'
else null end =EXP_LIST.country

left join 
(select distinct  
GMC_SKU_CODE,
GMC_SKU_NAME,
UNIQUE_ID,
GMC_REGION,
GMC_CD,
GMC_DESCRIPTION,
GMC_CODE,
GMC_SUBCATEGORY_CODE,
GMC_SUBCATEGORY_NAME,
GMC_LABEL_BRAND_CODE,
GMC_LABEL_BRAND_NAME,
GMC_LABEL_SUBBRAND_CODE,
GMC_LABEL_SUBBRAND_NAME,
GMC_VARIANT_CODE,
GMC_VARIANT_NAME,
GMC_SUBVARIANT_CODE,
GMC_SUBVARIANT_NAME,
GMC_FLAVOR_CODE,
GMC_FLAVOR_NAME,
GMC_INGREDIENT_CODE,
GMC_INGREDIENT_NAME,
GMC_APPLICATION_CODE,
GMC_APPLICATION_NAME,
GMC_LENGTH_STRENGTH_CODE,
GMC_LENGTH_STRENGTH_NAME,
GMC_SHAPE_CODE,
GMC_SHAPE_NAME,
GMC_SPF_CONCENTRATION_CODE,
GMC_SPF_CONCENTRATION_NAME,
GMC_COVER_PRODUCT_TYPE_CODE,
GMC_COVER_PRODUCT_TYPE_NAME,
GMC_FORM_CODE,
GMC_FORM_NAME,
GMC_SIZE_CODE,
GMC_SIZE_NAME,
GMC_CHARACTERS_SPECIAL_EDITION_CODE,
GMC_CHARACTERS_SPECIAL_EDITION_NAME,
GMC_PACKAGE_CODE,
GMC_PACKAGE_NAME,
GMC_UOM_CODE,
GMC_UOM_NAME,
P4_BRAND_CATEGORY_CODE,
P4_BRAND_CATEGORY,
B2_SUB_BRAND_CODE,
B2_SUB_BRAND,
C5_SUB_CATEGORY_CODE,
C5_SUB_CATEGORY,
C1_BUSINESS_SEGMENT_CODE,
C1_BUSINESS_SEGMENT,
C2_BUSINESS_SUBSEGMENT_CODE,
C2_BUSINESS_SUBSEGMENT,
C3_NEED_STATE_CODE,
C3_NEED_STATE,
C4_CATEGORY_CODE,
C4_CATEGORY,
C5_SUBCATEGORY_CODE,
C5_SUBCATEGORY,
B1_BRAND_CODE,
B1_BRAND,
B2_SUBBRAND_CODE,
B2_SUBBRAND,
P1_CODE,
P1_BUSINESS_SEGMENT,
PS_CODE,
PS_BUSINESS_SUBSEGMENT,
P2_CODE,
P2_NEED_STATE,
P3_CODE,
P3_BRAND_CATEGORY,
P4_CODE,
P4_BRAND_CATEGORY_PLACEHOLDER,
   from EDW_GCH_PRODUCTHIERARCHY) gch
on REGEXP_REPLACE(GMC_SKU_CODE, '^[A-Za-z]+0*', '')=apo. matl_no )


--FINAL SELECT FOR ACTUAL/PROMAX/BP
,final as
(select distinct
actual_qty,
actual_gts,
actual_nts,
'0.00' AS  apo_base_frcst ,
'0.00' AS  apo_promo_frcst ,
'0.00' AS  apo_tot_frcst ,
'0.00' AS  APO_GTS ,
 bar_cd ,
 base_prod_cd ,
 base_prod_desc ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  BRAND_SC  ELSE 'NOT ASSIGNED' end AS  Brand_SC ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  BRANDCON_MAPPING_FINAL  ELSE 'NOT ASSIGNED' end AS BRANDCON_MAPPING_FINAL ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  BRANDCON_MAPPING_SUMMARY  ELSE 'NOT ASSIGNED' end AS BRANDCON_MAPPING_SUMMARY,
 bp_gts ,
 bp_nts ,
 bp_qty ,
 brnd_cd ,
 brnd_desc ,
 cmp_id ,
 country ,
 cust_curr_cd ,
 exch_rate ,
 fran_cd ,
 fran_desc ,
 GMC_SKU_CODE,
GMC_SKU_NAME,
UNIQUE_ID,
GMC_REGION,
GMC_CD,
GMC_DESCRIPTION,
GMC_CODE,
GMC_SUBCATEGORY_CODE,
GMC_SUBCATEGORY_NAME,
GMC_LABEL_BRAND_CODE,
GMC_LABEL_BRAND_NAME,
GMC_LABEL_SUBBRAND_CODE,
GMC_LABEL_SUBBRAND_NAME,
GMC_VARIANT_CODE,
GMC_VARIANT_NAME,
GMC_SUBVARIANT_CODE,
GMC_SUBVARIANT_NAME,
GMC_FLAVOR_CODE,
GMC_FLAVOR_NAME,
GMC_INGREDIENT_CODE,
GMC_INGREDIENT_NAME,
GMC_APPLICATION_CODE,
GMC_APPLICATION_NAME,
GMC_LENGTH_STRENGTH_CODE,
GMC_LENGTH_STRENGTH_NAME,
GMC_SHAPE_CODE,
GMC_SHAPE_NAME,
GMC_SPF_CONCENTRATION_CODE,
GMC_SPF_CONCENTRATION_NAME,
GMC_COVER_PRODUCT_TYPE_CODE,
GMC_COVER_PRODUCT_TYPE_NAME,
GMC_FORM_CODE,
GMC_FORM_NAME,
GMC_SIZE_CODE,
GMC_SIZE_NAME,
GMC_CHARACTERS_SPECIAL_EDITION_CODE,
GMC_CHARACTERS_SPECIAL_EDITION_NAME,
GMC_PACKAGE_CODE,
GMC_PACKAGE_NAME,
GMC_UOM_CODE,
GMC_UOM_NAME,
P4_BRAND_CATEGORY_CODE,
P4_BRAND_CATEGORY,
B2_SUB_BRAND_CODE,
B2_SUB_BRAND,
C5_SUB_CATEGORY_CODE,
C5_SUB_CATEGORY,
C1_BUSINESS_SEGMENT_CODE,
C1_BUSINESS_SEGMENT,
C2_BUSINESS_SUBSEGMENT_CODE,
C2_BUSINESS_SUBSEGMENT,
C3_NEED_STATE_CODE,
C3_NEED_STATE,
C4_CATEGORY_CODE,
C4_CATEGORY,
C5_SUBCATEGORY_CODE,
C5_SUBCATEGORY,
B1_BRAND_CODE,
B1_BRAND,
B2_SUBBRAND_CODE,
B2_SUBBRAND,
P1_CODE,
P1_BUSINESS_SEGMENT,
PS_CODE,
PS_BUSINESS_SUBSEGMENT,
P2_CODE,
P2_NEED_STATE,
P3_CODE,
P3_BRAND_CATEGORY,
P4_CODE,
P4_BRAND_CATEGORY_PLACEHOLDER,
 goal_gts ,
 goal_nts ,
 goal_qty ,
 grp_fran_cd ,
 grp_fran_desc ,
 jj_mnth ,
 jj_mnth_shrt ,
 jj_period ,
 jj_qrtr ,
 edw.jj_year ,
 ju_gts ,
 ju_nts ,
 ju_qty ,
'0.00' AS  list_price ,
'99991231' as VALID_TO ,
'99991231' as DT_FROM ,
 master_code ,
 matl_desc ,
 matl_id ,
 matl_type_cd ,
 matl_type_desc ,
 mega_brnd_cd ,
 mega_brnd_desc ,
 pac_source_type ,
 pac_subsource_type ,
 parent_matl_id ,
 parent_matl_desc ,
CASE WHEN  cust_no  <> '123801' or  cust_no  is null THEN  pln_cnnl_cd 
	when  cust_no  ='123801' then 'AU9' 
	else null end as  pln_cnnl_cd ,
CASE WHEN  cust_no  <> '123801' or  cust_no  is null THEN  HARMONIZED_PLANNING_CHANNEL_DESC 
	when  cust_no  ='123801' then 'AU-SLOBS' 
	else null end as  HARMONIZED_PLANNING_CHANNEL_DESC ,
 post_cd ,
 prod_fran_cd ,
 prod_fran_desc ,
 prod_hier_cd ,
 prod_hier_desc ,
 prod_mjr_cd ,
 prod_mjr_desc ,
 prod_mnr_cd ,
 prod_mnr_desc ,
 NU_gts  ,
 NU_nts ,
 NU_qty ,
 projected_nts ,
 projected_qty ,
 projected_gts ,
 px_gts ,
 px_nts ,
 px_qty ,
 sales_grp_desc ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  STRONGHOLD_V3  ELSE 'NOT ASSIGNED' end AS  STRONGHOLD_V3 ,
CURRENT_DATE - EXTRACT (DOW FROM CURRENT_DATE -1) AS  UPDATE_DATE ,
 PSTNG_PER  AS  CURRENT_JJ_MONTH ,
 FISC_YR  AS  CURRENT_JJ_YEAR 
from VW_ACTUAL edw
left join 
sdl_pcf_planning_channel_mapping pln
on edw. pln_cnnl_cd =pln.CODE 
left join sdl_pcf_brandcon_mapping brandcon
on lower(edw. prod_mjr_desc )=lower(brandcon. PRODUCT_MAJOR )
LEFT JOIN EDW_CALENDAR_DIM JJ_CAL
ON CURRENT_DATE - EXTRACT (DOW FROM CURRENT_DATE -1)=JJ_CAL.CAL_DAY
left join 
(select distinct  
GMC_SKU_CODE,
GMC_SKU_NAME,
UNIQUE_ID,
GMC_REGION,
GMC_CD,
GMC_DESCRIPTION,
GMC_CODE,
GMC_SUBCATEGORY_CODE,
GMC_SUBCATEGORY_NAME,
GMC_LABEL_BRAND_CODE,
GMC_LABEL_BRAND_NAME,
GMC_LABEL_SUBBRAND_CODE,
GMC_LABEL_SUBBRAND_NAME,
GMC_VARIANT_CODE,
GMC_VARIANT_NAME,
GMC_SUBVARIANT_CODE,
GMC_SUBVARIANT_NAME,
GMC_FLAVOR_CODE,
GMC_FLAVOR_NAME,
GMC_INGREDIENT_CODE,
GMC_INGREDIENT_NAME,
GMC_APPLICATION_CODE,
GMC_APPLICATION_NAME,
GMC_LENGTH_STRENGTH_CODE,
GMC_LENGTH_STRENGTH_NAME,
GMC_SHAPE_CODE,
GMC_SHAPE_NAME,
GMC_SPF_CONCENTRATION_CODE,
GMC_SPF_CONCENTRATION_NAME,
GMC_COVER_PRODUCT_TYPE_CODE,
GMC_COVER_PRODUCT_TYPE_NAME,
GMC_FORM_CODE,
GMC_FORM_NAME,
GMC_SIZE_CODE,
GMC_SIZE_NAME,
GMC_CHARACTERS_SPECIAL_EDITION_CODE,
GMC_CHARACTERS_SPECIAL_EDITION_NAME,
GMC_PACKAGE_CODE,
GMC_PACKAGE_NAME,
GMC_UOM_CODE,
GMC_UOM_NAME,
P4_BRAND_CATEGORY_CODE,
P4_BRAND_CATEGORY,
B2_SUB_BRAND_CODE,
B2_SUB_BRAND,
C5_SUB_CATEGORY_CODE,
C5_SUB_CATEGORY,
C1_BUSINESS_SEGMENT_CODE,
C1_BUSINESS_SEGMENT,
C2_BUSINESS_SUBSEGMENT_CODE,
C2_BUSINESS_SUBSEGMENT,
C3_NEED_STATE_CODE,
C3_NEED_STATE,
C4_CATEGORY_CODE,
C4_CATEGORY,
C5_SUBCATEGORY_CODE,
C5_SUBCATEGORY,
B1_BRAND_CODE,
B1_BRAND,
B2_SUBBRAND_CODE,
B2_SUBBRAND,
P1_CODE,
P1_BUSINESS_SEGMENT,
PS_CODE,
PS_BUSINESS_SUBSEGMENT,
P2_CODE,
P2_NEED_STATE,
P3_CODE,
P3_BRAND_CATEGORY,
P4_CODE,
P4_BRAND_CATEGORY_PLACEHOLDER,
   from EDW_GCH_PRODUCTHIERARCHY) gch
on REGEXP_REPLACE(GMC_SKU_CODE, '^[A-Za-z]+0*', '')=edw. matl_id 


UNION



select distinct
 '0.00' as actual_qty,
 '0.00' as actual_gts,
 '0.00' as actual_nts,
 apo_base_frcst ,
 apo_promo_frcst ,
 apo_tot_frcst ,
( apo_tot_frcst  *  List_price ) AS  APO_GTS ,
 bar_cd ,
 base_prod_cd ,
 base_prod_desc ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  BRAND_SC  ELSE 'NOT ASSIGNED' end AS  Brand_SC ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  BRANDCON_MAPPING_FINAL  ELSE 'NOT ASSIGNED' end AS BrandCon_Mapping_Final ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  BRANDCON_MAPPING_SUMMARY  ELSE 'NOT ASSIGNED' end AS BrandCon_Mapping_Summary ,
'0.00' AS  bp_gts ,
'0.00' AS  bp_nts ,
'0.00' AS  bp_qty ,
 brnd_cd ,
 brnd_desc ,
 cmp_id ,
 country ,
case when  country ='Australia' then 'AUD' when  country ='New Zealand' then 'NZD'
else null end as  display_currency ,
'0.00' AS  exch_rate ,
 fran_cd ,
 fran_desc ,
 GMC_SKU_CODE,
GMC_SKU_NAME,
UNIQUE_ID,
GMC_REGION,
GMC_CD,
GMC_DESCRIPTION,
GMC_CODE,
GMC_SUBCATEGORY_CODE,
GMC_SUBCATEGORY_NAME,
GMC_LABEL_BRAND_CODE,
GMC_LABEL_BRAND_NAME,
GMC_LABEL_SUBBRAND_CODE,
GMC_LABEL_SUBBRAND_NAME,
GMC_VARIANT_CODE,
GMC_VARIANT_NAME,
GMC_SUBVARIANT_CODE,
GMC_SUBVARIANT_NAME,
GMC_FLAVOR_CODE,
GMC_FLAVOR_NAME,
GMC_INGREDIENT_CODE,
GMC_INGREDIENT_NAME,
GMC_APPLICATION_CODE,
GMC_APPLICATION_NAME,
GMC_LENGTH_STRENGTH_CODE,
GMC_LENGTH_STRENGTH_NAME,
GMC_SHAPE_CODE,
GMC_SHAPE_NAME,
GMC_SPF_CONCENTRATION_CODE,
GMC_SPF_CONCENTRATION_NAME,
GMC_COVER_PRODUCT_TYPE_CODE,
GMC_COVER_PRODUCT_TYPE_NAME,
GMC_FORM_CODE,
GMC_FORM_NAME,
GMC_SIZE_CODE,
GMC_SIZE_NAME,
GMC_CHARACTERS_SPECIAL_EDITION_CODE,
GMC_CHARACTERS_SPECIAL_EDITION_NAME,
GMC_PACKAGE_CODE,
GMC_PACKAGE_NAME,
GMC_UOM_CODE,
GMC_UOM_NAME,
P4_BRAND_CATEGORY_CODE,
P4_BRAND_CATEGORY,
B2_SUB_BRAND_CODE,
B2_SUB_BRAND,
C5_SUB_CATEGORY_CODE,
C5_SUB_CATEGORY,
C1_BUSINESS_SEGMENT_CODE,
C1_BUSINESS_SEGMENT,
C2_BUSINESS_SUBSEGMENT_CODE,
C2_BUSINESS_SUBSEGMENT,
C3_NEED_STATE_CODE,
C3_NEED_STATE,
C4_CATEGORY_CODE,
C4_CATEGORY,
C5_SUBCATEGORY_CODE,
C5_SUBCATEGORY,
B1_BRAND_CODE,
B1_BRAND,
B2_SUBBRAND_CODE,
B2_SUBBRAND,
P1_CODE,
P1_BUSINESS_SEGMENT,
PS_CODE,
PS_BUSINESS_SUBSEGMENT,
P2_CODE,
P2_NEED_STATE,
P3_CODE,
P3_BRAND_CATEGORY,
P4_CODE,
P4_BRAND_CATEGORY_PLACEHOLDER,
'0.00' AS  goal_gts ,
'0.00' AS  goal_nts ,
'0.00' AS  goal_qty ,
 grp_fran_cd ,
 grp_fran_desc ,
 jj_mnth ,
 jj_mnth_shrt ,
 jj_period ,
 jj_qrtr ,
 cal.jj_year ,
'0.00' AS  ju_gts ,
'0.00' AS  ju_nts ,
'0.00' AS  ju_qty ,
 List_price ,
 VALID_TO ,
 DT_FROM ,
 master_code ,
 matl_desc ,
 matl_no ,
 matl_type_cd ,
 matl_type_desc ,
 mega_brnd_cd ,
 mega_brnd_desc ,
 pac_source_type ,
 pac_subsource_type ,
 parent_id ,
 parent_matl_desc ,
 fcst_chnl ,
 fcst_chnl_desc ,
 post_cd ,
 prod_fran_cd ,
 prod_fran_desc ,
 prod_hier_cd ,
 prod_hier_desc ,
 prod_mjr_cd ,
 prod_mjr_desc ,
 prod_mnr_cd ,
 prod_mnr_desc ,
'0.00' AS  NU_gts  ,
'0.00' AS  NU_nts ,
'0.00' as  NU_qty ,
'0.00' AS  projected_nts ,
'0.00' AS  projected_qty ,
'0.00' as  projected_gts ,
'0.00' AS  px_gts ,
'0.00' AS  px_nts ,
'0.00' AS  px_qty ,
'NA' AS  sales_grp_desc ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  STRONGHOLD_V3  ELSE 'NOT ASSIGNED' end AS  STRONGHOLD_V3 ,
CURRENT_DATE - EXTRACT (DOW FROM CURRENT_DATE -1) AS  UPDATE_DATE ,
 PSTNG_PER  AS  CURRENT_JJ_MONTH ,
 FISC_YR  AS  CURRENT_JJ_YEAR 
FROM LIST_PRICE_CAL cal
left join sdl_pcf_brandcon_mapping brandcon
on lower(cal. prod_mjr_desc )=lower(brandcon. PRODUCT_MAJOR )
LEFT JOIN EDW_CALENDAR_DIM JJ_CAL
ON CURRENT_DATE - EXTRACT (DOW FROM CURRENT_DATE -1)=JJ_CAL.CAL_DAY

UNION



select distinct
 '0.00' as actual_qty,
 '0.00' as actual_gts,
 '0.00' as actual_nts,
apo_base_frcst ,
apo_promo_frcst,
apo_tot_frcst ,
( apo_tot_frcst  *  List_price *  EXCH_RATE ) AS  APO_GTS ,
 bar_cd ,
 base_prod_cd ,
 base_prod_desc ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  BRAND_SC  ELSE 'NOT ASSIGNED' end AS  Brand_SC ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  BRANDCON_MAPPING_FINAL  ELSE 'NOT ASSIGNED' end AS BrandCon_Mapping_Final ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  BRANDCON_MAPPING_SUMMARY  ELSE 'NOT ASSIGNED' end AS BrandCon_Mapping_Summary ,
'0.00' AS  bp_gts ,
'0.00' AS  bp_nts ,
'0.00' AS  bp_qty ,
 brnd_cd ,
 brnd_desc ,
 cmp_id ,
 country ,
'USD' as  display_currency ,
 EXCH_RATE ,
 fran_cd ,
 fran_desc ,
 GMC_SKU_CODE,
GMC_SKU_NAME,
UNIQUE_ID,
GMC_REGION,
GMC_CD,
GMC_DESCRIPTION,
GMC_CODE,
GMC_SUBCATEGORY_CODE,
GMC_SUBCATEGORY_NAME,
GMC_LABEL_BRAND_CODE,
GMC_LABEL_BRAND_NAME,
GMC_LABEL_SUBBRAND_CODE,
GMC_LABEL_SUBBRAND_NAME,
GMC_VARIANT_CODE,
GMC_VARIANT_NAME,
GMC_SUBVARIANT_CODE,
GMC_SUBVARIANT_NAME,
GMC_FLAVOR_CODE,
GMC_FLAVOR_NAME,
GMC_INGREDIENT_CODE,
GMC_INGREDIENT_NAME,
GMC_APPLICATION_CODE,
GMC_APPLICATION_NAME,
GMC_LENGTH_STRENGTH_CODE,
GMC_LENGTH_STRENGTH_NAME,
GMC_SHAPE_CODE,
GMC_SHAPE_NAME,
GMC_SPF_CONCENTRATION_CODE,
GMC_SPF_CONCENTRATION_NAME,
GMC_COVER_PRODUCT_TYPE_CODE,
GMC_COVER_PRODUCT_TYPE_NAME,
GMC_FORM_CODE,
GMC_FORM_NAME,
GMC_SIZE_CODE,
GMC_SIZE_NAME,
GMC_CHARACTERS_SPECIAL_EDITION_CODE,
GMC_CHARACTERS_SPECIAL_EDITION_NAME,
GMC_PACKAGE_CODE,
GMC_PACKAGE_NAME,
GMC_UOM_CODE,
GMC_UOM_NAME,
P4_BRAND_CATEGORY_CODE,
P4_BRAND_CATEGORY,
B2_SUB_BRAND_CODE,
B2_SUB_BRAND,
C5_SUB_CATEGORY_CODE,
C5_SUB_CATEGORY,
C1_BUSINESS_SEGMENT_CODE,
C1_BUSINESS_SEGMENT,
C2_BUSINESS_SUBSEGMENT_CODE,
C2_BUSINESS_SUBSEGMENT,
C3_NEED_STATE_CODE,
C3_NEED_STATE,
C4_CATEGORY_CODE,
C4_CATEGORY,
C5_SUBCATEGORY_CODE,
C5_SUBCATEGORY,
B1_BRAND_CODE,
B1_BRAND,
B2_SUBBRAND_CODE,
B2_SUBBRAND,
P1_CODE,
P1_BUSINESS_SEGMENT,
PS_CODE,
PS_BUSINESS_SUBSEGMENT,
P2_CODE,
P2_NEED_STATE,
P3_CODE,
P3_BRAND_CATEGORY,
P4_CODE,
P4_BRAND_CATEGORY_PLACEHOLDER,
'0.00' AS  goal_gts ,
'0.00' AS  goal_nts ,
'0.00' AS  goal_qty ,
 grp_fran_cd ,
 grp_fran_desc ,
 jj_mnth ,
 jj_mnth_shrt ,
 jj_period ,
 jj_qrtr ,
 LP_CAL.jj_year ,
'0.00' AS  ju_gts ,
'0.00' AS  ju_nts ,
'0.00' AS  ju_qty ,
( List_price  * EXCH_RATE ) as  List_price ,
VALID_TO ,
DT_FROM ,
 master_code ,
 matl_desc ,
 matl_no ,
 matl_type_cd ,
 matl_type_desc ,
 mega_brnd_cd ,
 mega_brnd_desc ,
 pac_source_type ,
 pac_subsource_type ,
 parent_id ,
 parent_matl_desc ,
 fcst_chnl ,
 fcst_chnl_desc ,
 post_cd ,
 prod_fran_cd ,
 prod_fran_desc ,
 prod_hier_cd ,
 prod_hier_desc ,
 prod_mjr_cd ,
 prod_mjr_desc ,
 prod_mnr_cd ,
 prod_mnr_desc ,
'0.00' AS  NU_gts  ,
'0.00' AS  NU_nts ,
'0.00' as  NU_qty ,
'0.00' AS  projected_nts ,
'0.00' AS  projected_qty ,
'0.00' as  projected_gts ,
'0.00' AS  px_gts ,
'0.00' AS  px_nts ,
'0.00' AS  px_qty ,
'NA' AS  sales_grp_desc ,
CASE WHEN  prod_mjr_desc  IS NOT NULL THEN  STRONGHOLD_V3  ELSE 'NOT ASSIGNED' end AS  STRONGHOLD_V3 ,
CURRENT_DATE - EXTRACT (DOW FROM CURRENT_DATE -1) AS  UPDATE_DATE ,
 PSTNG_PER  AS  CURRENT_JJ_MONTH ,
 FISC_YR  AS  CURRENT_JJ_YEAR 
FROM LIST_PRICE_CAL LP_CAL
LEFT JOIN VW_EDW_REG_EXCH_RATE EXCH
ON case when LP_CAL. country ='Australia' then 'AUD' when LP_CAL. country ='New Zealand' then 'NZD'
else null end =EXCH.FROM_CCY
left join sdl_pcf_brandcon_mapping brandcon
on lower(LP_CAL. prod_mjr_desc )=lower(brandcon. PRODUCT_MAJOR )
LEFT JOIN EDW_CALENDAR_DIM JJ_CAL
ON CURRENT_DATE - EXTRACT (DOW FROM CURRENT_DATE -1)=JJ_CAL.CAL_DAY)

select * from final