version: 2

models:
  - name: aspwks_integration__wks_india_inventory_health_analysis_propagation_prestep
    config:
      alias: wks_india_inventory_health_analysis_propagation_prestep
      tags: ["J_ap_china_reg_data_refresh","transformation"]
  - name: aspwks_integration__wks_india_inventory_health_analysis_propagation
    config:
      alias: wks_india_inventory_health_analysis_propagation
      tags: ["J_ap_china_reg_data_refresh","transformation"]
  - name: aspwks_integration__wks_india_inventory_health_analysis_propagation_final
    config:
      alias: wks_india_inventory_health_analysis_propagation_final
      tags: ["J_ap_china_reg_data_refresh","transformation"]