with itg_vn_mt_sellin_dksh_history as 
(
    select * from snaposeitg_integration.itg_vn_mt_sellin_dksh_history
),
itg_vn_mt_sellin_dksh as 
(
    select * from snaposeitg_integration.itg_vn_mt_sellin_dksh
),
dksh as
(
select supplier_code,
    supplier_name,
    plant,
    productid,
    product,
    brand,
    sellin_category,
    product_group,
    product_sub_group,
    unit_of_measurement,
    custcode,
    customer,
    address,
    district,
    province,
    region,
    zone,
    channel,
    sellin_sub_channel,
    cust_group,
    billing_no,
    invoice_date,
    qty_include_foc,
    qty_exclude_foc,
    foc,
    net_price_wo_vat,
    tax,
    net_amount_wo_vat,
    net_amount_w_vat,
    gross_amount_wo_vat,
    gross_amount_w_vat,
    list_price_wo_vat,
    vendor_lot,
    order_type,
    red_invoice_no,
    expiry_date,
    order_no,
    order_date,
    period,
    sellout_sub_channel,
    group_account,
    account,
    name_st_or_ddp,
    zone_or_area,
    franchise,
    sellout_category,
    sub_cat,
    sub_brand,
    barcode,
    base_or_bundle,
    size,
    key_chain,
    status
from itg_vn_mt_sellin_dksh
WHERE channel != 'ECOM'
),
hist as 
(
select supplier_code,
    supplier_name,
    plant,
    productid,
    product,
    brand,
    sellin_category,
    product_group,
    product_sub_group,
    unit_of_measurement,
    custcode,
    customer,
    address,
    district,
    province,
    region,
    zone,
    channel,
    sellin_sub_channel,
    cust_group,
    billing_no,
    invoice_date,
    qty_include_foc,
    qty_exclude_foc,
    foc,
    net_price_wo_vat,
    tax,
    net_amount_wo_vat,
    net_amount_w_vat,
    gross_amount_wo_vat,
    gross_amount_w_vat,
    list_price_wo_vat,
    vendor_lot,
    order_type,
    red_invoice_no,
    expiry_date,
    order_no,
    order_date,
    period,
    sellout_sub_channel,
    group_account,
    account,
    name_st_or_ddp,
    zone_or_area,
    franchise,
    sellout_category,
    sub_cat,
    sub_brand,
    barcode,
    base_or_bundle,
    size,
    key_chain,
    status
from itg_vn_mt_sellin_dksh_history
WHERE channel != 'ECOM'
),
trans as 
(
    select * from dksh
    union all
    select * from hist
),
final as 
(
    select
    supplier_code::varchar(10) as supplier_code,
	supplier_name::varchar(100) as supplier_name,
	plant::varchar(10) as plant,
	productid::varchar(20) as productid,
	product::varchar(255) as product,
	brand::varchar(100) as brand,
	sellin_category::varchar(100) as sellin_category,
	product_group::varchar(100) as product_group,
	product_sub_group::varchar(100) as product_sub_group,
	unit_of_measurement::varchar(10) as unit_of_measurement,
	custcode::varchar(20) as custcode,
	customer::varchar(100) as customer,
	address::varchar(100) as address,
	district::varchar(100) as district,
	province::varchar(50) as province,
	region::varchar(20) as region,
	zone::varchar(20) as zone,
	channel::varchar(10) as channel,
	sellin_sub_channel::varchar(50) as sellin_sub_channel,
	cust_group::varchar(50) as cust_group,
	billing_no::varchar(20) as billing_no,
	invoice_date::varchar(20) as invoice_date,
	qty_include_foc::number(18,0) as qty_include_foc,
	qty_exclude_foc::number(18,0) as qty_exclude_foc,
	foc::varchar(100) as foc,
	net_price_wo_vat::number(20,5) as net_price_wo_vat,
	tax::number(20,5) as tax,
	net_amount_wo_vat::number(20,5) as net_amount_wo_vat,
	net_amount_w_vat::number(20,5) as net_amount_w_vat,
	gross_amount_wo_vat::number(20,5) as gross_amount_wo_vat,
	gross_amount_w_vat::number(20,5) as gross_amount_w_vat,
	list_price_wo_vat::number(20,5) as list_price_wo_vat,
	vendor_lot::varchar(100) as vendor_lot,
	order_type::varchar(100) as order_type,
	red_invoice_no::varchar(100) as red_invoice_no,
	expiry_date::varchar(100) as expiry_date,
	order_no::varchar(100) as order_no,
	order_date::varchar(100) as order_date,
	period::varchar(100) as period,
	sellout_sub_channel::varchar(100) as sellout_sub_channel,
	group_account::varchar(100) as group_account,
	account::varchar(100) as account,
	name_st_or_ddp::varchar(100) as name_st_or_ddp,
	zone_or_area::varchar(100) as zone_or_area,
	franchise::varchar(100) as franchise,
	sellout_category::varchar(100) as sellout_category,
	sub_cat::varchar(100) as sub_cat,
	sub_brand::varchar(100) as sub_brand,
	barcode::varchar(100) as barcode,
	base_or_bundle::varchar(100) as base_or_bundle,
	size::varchar(100) as size,
	key_chain::varchar(100) as key_chain,
	status::varchar(100) as status
    from trans
)
select * from final