with wks_skurecom_mi_actuals_tmp5 as(
    select * from {{ ref('indwks_integration__wks_skurecom_mi_actuals_tmp5') }}
),
final as(
    select
    cust_cd::varchar(100) as cust_cd,
    retailer_cd::varchar(100) as retailer_cd,
    '(unknown)' as product_code,
    mother_sku_cd::varchar(50) as mother_sku_cd,
    salesman_code::varchar(50) as salesman_code,
    route_code::varchar(50) as route_code,
    rtruniquecode::varchar(100) as rtruniquecode,
    customer_name::varchar(200) as customer_name,
    region_name::varchar(200) as region_name,
    zone_name::varchar(200) as zone_name,
    territory_name::varchar(200) as territory_name,
    class_desc::varchar(50) as class_desc,
    channel_name::varchar(50) as channel_name,
    business_channel::varchar(50) as business_channel,
    status_desc::varchar(100) as status_desc,
    '(unknown)'as product_name,
    franchise_name::varchar(255) as franchise_name,
    brand_name::varchar(255) as brand_name,
    product_category_name::varchar(255) as product_category_name,
    variant_name::varchar(255) as variant_name,
    mothersku_name::varchar(255) as mothersku_name,
    quarter::number(18,0) as qtr,
    year::number(18,0) as fisc_yr,
    retailer_name::varchar(255) as retailer_name,
    salesman_name::varchar(255) as salesman_name,
    unique_sales_code::varchar(50) as unique_sales_code,
    route_name::varchar(255) as route_name,
    quantity::number(38,4) as quantity,
    achievement_nr_val::number(38,4) as achievement_nr_val,
    0 as achievement_amt,
    0 as num_packs,
    0 as num_lines,
    retailer_category_name::varchar(50) as retailer_category_name,
    csrtrcode::varchar(100) as csrtrcode,
    oos_flag::varchar(50) as oos_flag,
    ms_flag::varchar(50) as ms_flag,
    cs_flag::varchar(50) as cs_flag,
    soq::varchar(50) as soq,
    0 as hit_oos_flag,
    hit_ms_flag::varchar(10) as hit_ms_flag,
    0 as hit_cs_flag,
    br_flag::varchar(10) as br_flag,
    '(unknown)' as target_ms_mothersku_name,
    '(unknown)' as target_cs_mothersku_name,
    0 as orange_percentage,
    retailer_channel_level_1::varchar(200) as retailer_channel_level_1,
    retailer_channel_level_2::varchar(200) as retailer_channel_level_2,
    retailer_channel_level_3::varchar(200) as retailer_channel_level_3,
    actv_flg::varchar(1) as actv_flg,
    convert_timezone('UTC', current_timestamp())::timestamp_ntz(9) as crt_dttm,
    convert_timezone('UTC', current_timestamp())::timestamp_ntz(9) as updt_dttm
    from wks_skurecom_mi_actuals_tmp5
    )
select * from final
