with wks_rev_sku_recom_tbl5 as
(
    select * from {{ ref('indwks_integration__wks_rev_sku_recom_tbl5') }}
),
final as
(
    SELECT
        cust_cd,
        retailer_cd,
        '(unknown)' as product_code,
        mother_sku_cd,
        salesman_code,
        route_code,
        rtruniquecode,
        customer_name,
        region_name,
        zone_name,
        territory_name,
        class_desc,
        channel_name,
        business_channel,
        status_desc,
        '(unknown)' as product_name,
        franchise_name,
        brand_name,
        product_category_name,
        variant_name,
        mothersku_name,
        mth_mm,
        qtr,
        fisc_yr,
        month,
        retailer_name,
        salesman_name,
        unique_sales_code,
        route_name,
        quantity,
        achievement_nr_val,
        0 as achievement_amt,
        0 as num_packs,
        0 as num_lines,
        retailer_category_name,
        csrtrcode,
        oos_flag,
        ms_flag,
        cs_flag,
        soq,
        0 as hit_oos_flag,
        hit_ms_flag,
        0 as hit_cs_flag,
        br_flag,
        '(unknown)' as target_ms_mothersku_name,
        '(unknown)' as target_cs_mothersku_name,
        0 as orange_percentage,
        retailer_channel_level_1,
        retailer_channel_level_2,
        retailer_channel_level_3,
        actv_flg,
        current_timestamp()::timestamp_ntz(9) as crt_dttm,
        current_timestamp()::timestamp_ntz(9) as updt_dttm
    FROM wks_rev_sku_recom_tbl5
)
select * from final
