WITH isight_dim_employee_snapshot_xref
AS (
    SELECT *
    FROM DEV_DNA_CORE.HCPOSEEDW_INTEGRATION.ISIGHT_DIM_EMPLOYEE_SNAPSHOT_XREF
    ),
result
AS (
    SELECT year,
        month,
        employee_key,
        country_code,
        employee_source_id,
        modified_dt,
        modified_id,
        employee_name,
        employee_wwid,
        mobile_phone,
        email_id,
        username,
        nickname,
        local_employee_number,
        profile_id,
        profile_name,
        function_name,
        employee_profile_id,
        company_name,
        division_name,
        department_name,
        country_name,
        address,
        alias,
        timezonesidkey,
        user_role_source_id,
        receives_info_emails,
        federation_identifier,
        last_ipad_sync,
        user_license,
        title,
        phone,
        last_login_date,
        region,
        profile_group_ap,
        manager_name,
        manager_wwid,
        active_flag,
        my_organization_code,
        my_organization_name,
        organization_l1_code,
        organization_l1_name,
        organization_l2_code,
        organization_l2_name,
        organization_l3_code,
        organization_l3_name,
        organization_l4_code,
        organization_l4_name,
        organization_l5_code,
        organization_l5_name,
        organization_l6_code,
        organization_l6_name,
        organization_l7_code,
        organization_l7_name,
        organization_l8_code,
        organization_l8_name,
        organization_l9_code,
        organization_l9_name,
        common_organization_l1_code,
        common_organization_l1_name,
        common_organization_l2_code,
        common_organization_l2_name,
        common_organization_l3_code,
        common_organization_l3_name,
        inserted_date,
        updated_date
    FROM isight_dim_employee_snapshot_xref
    WHERE year > extract(year FROM current_timestamp) - 3
    ),

final as (
    select
        year::number(38,0) as year,
        month::number(38,0) as month,
        employee_key::varchar(32) as employee_key,
        country_code::varchar(8) as country_code,
        employee_source_id::varchar(18) as employee_source_id,
        modified_dt::timestamp_ntz(9) as modified_dt,
        modified_id::varchar(18) as modified_id,
        employee_name::varchar(121) as employee_name,
        employee_wwid::varchar(20) as employee_wwid,
        mobile_phone::varchar(40) as mobile_phone,
        email_id::varchar(128) as email_id,
        username::varchar(80) as username,
        nickname::varchar(40) as nickname,
        local_employee_number::varchar(20) as local_employee_number,
        profile_id::varchar(18) as profile_id,
        profile_name::varchar(255) as profile_name,
        function_name::varchar(255) as function_name,
        employee_profile_id::varchar(18) as employee_profile_id,
        company_name::varchar(80) as company_name,
        division_name::varchar(80) as division_name,
        department_name::varchar(80) as department_name,
        country_name::varchar(80) as country_name,
        address::varchar(255) as address,
        alias::varchar(18) as alias,
        timezonesidkey::varchar(40) as timezonesidkey,
        user_role_source_id::varchar(18) as user_role_source_id,
        receives_info_emails::number(38,0) as receives_info_emails,
        federation_identifier::varchar(512) as federation_identifier,
        last_ipad_sync::timestamp_ntz(9) as last_ipad_sync,
        user_license::varchar(1300) as user_license,
        title::varchar(1300) as title,
        phone::varchar(43) as phone,
        last_login_date::timestamp_ntz(9) as last_login_date,
        region::varchar(1300) as region,
        profile_group_ap::varchar(1030) as profile_group_ap,
        manager_name::varchar(80) as manager_name,
        manager_wwid::varchar(18) as manager_wwid,
        active_flag::number(2,0) as active_flag,
        my_organization_code::varchar(18) as my_organization_code,
        my_organization_name::varchar(80) as my_organization_name,
        organization_l1_code::varchar(18) as organization_l1_code,
        organization_l1_name::varchar(80) as organization_l1_name,
        organization_l2_code::varchar(18) as organization_l2_code,
        organization_l2_name::varchar(80) as organization_l2_name,
        organization_l3_code::varchar(18) as organization_l3_code,
        organization_l3_name::varchar(80) as organization_l3_name,
        organization_l4_code::varchar(18) as organization_l4_code,
        organization_l4_name::varchar(80) as organization_l4_name,
        organization_l5_code::varchar(18) as organization_l5_code,
        organization_l5_name::varchar(80) as organization_l5_name,
        organization_l6_code::varchar(18) as organization_l6_code,
        organization_l6_name::varchar(80) as organization_l6_name,
        organization_l7_code::varchar(18) as organization_l7_code,
        organization_l7_name::varchar(80) as organization_l7_name,
        organization_l8_code::varchar(18) as organization_l8_code,
        organization_l8_name::varchar(80) as organization_l8_name,
        organization_l9_code::varchar(18) as organization_l9_code,
        organization_l9_name::varchar(80) as organization_l9_name,
        common_organization_l1_code::varchar(18) as common_organization_l1_code,
        common_organization_l1_name::varchar(80) as common_organization_l1_name,
        common_organization_l2_code::varchar(18) as common_organization_l2_code,
        common_organization_l2_name::varchar(80) as common_organization_l2_name,
        common_organization_l3_code::varchar(18) as common_organization_l3_code,
        common_organization_l3_name::varchar(80) as common_organization_l3_name,
        current_timestamp()::timestamp_ntz(9) as inserted_date,
        current_timestamp()::timestamp_ntz(9) as updated_date
    from result
)

select * from final
