with source as (
    select * from {{ ref('aspitg_integration__itg_invnt') }}
),
final as(
    SELECT
    nvl(trim(lcl_crncy)::string,'') as lcl_crncy,
    nvl(trim(base_unit)::string,'') as base_unit,
    nvl(trim(matl_no)::string,'') as matl_no,
    nvl(trim(strg_loc)::string,'') as strg_loc,
    nvl(trim(stk_type)::string,'') as stk_type,
    nvl(trim(stk_cat)::string,'') as stk_cat,
    nvl(trim(co_cd)::string,'') as co_cd,
    nvl(trim(matl_plnt_view)::string,'') as matl_plnt_view,
    nvl(trim(btch_num)::string,'') as btch_num,
    nvl(trim(plnt)::string,'') as plnt,
    nvl(trim(whse_num)::string,'') as whse_num,
    nvl(trim(strg_bin)::string,'') as strg_bin,
    nvl(trim(strg_type)::string,'') as strg_type,
    nvl(trim(spl_stck_val)::string,'') as spl_stck_val,
    nvl(trim(spl_stck_indica)::string,'') as spl_stck_indica,
    trim(doc_dt) as doc_dt,
    nvl(trim(valut_cls)::string,'') as valut_cls,
    nvl(trim(valut_area)::string,'') as valut_area,
    nvl(trim(valut_type)::string,'') as valut_type,
    trim(pstng_dt) as pstng_dt,
    trim(cal_day) as cal_day,
    nvl(trim(wh_mstr)::string,'') as wh_mstr,
    nvl(trim(vers)::string,'') as vers,
    trim(val_type) as val_type,
    nvl(trim(vend)::string,'') as vend,
    nvl(trim(sold_to_prty)::string,'') as sold_to_prty,
    nvl(trim(mvmt_ind_sec)::string,'') as mvmt_ind_sec,
    nvl(trim(crncy)::string,'') as crncy,
    nvl(trim(fisc_yr_vrnt)::string,'') as fisc_yr_vrnt,
    trim(fisc_yr) as fisc_yr,
    trim(cal_yr) as cal_yr,
    trim(cal_mo) as cal_mo,
    trim(qtr) as qtr,
    trim(cal_yr_qtr) as cal_yr_qtr,
    trim(cal_yr_wk) as cal_yr_wk,
    trim(pstng_per) as pstng_per,
    trim(half_yr) as half_yr,
    trim(wkday) as wkday,
    trim(fisc_yr_per) as fisc_yr_per,
    trim(cal_yr_mon) as cal_yr_mon,
    SUM(stck_rec_val) as stck_rec_val,
    SUM(iss_stck_val) as iss_stck_val,
    SUM(iss_blok_qty) as iss_blok_qty,
    SUM(cng_stk_qty_iss) as cng_stk_qty_iss,
    SUM(iss_qty_qual) as iss_qty_qual,
    SUM(iss_qty_trst) as iss_qty_trst,
    SUM(rcpt_qty_blok) as rcpt_qty_blok,
    SUM(cns_stck_rcpt) as cns_stck_rcpt,
    SUM(rcpt_qty_qual) as rcpt_qty_qual,
    SUM(rcpt_qty_trst) as rcpt_qty_trst,
    SUM(iss_qty_scrap) as iss_qty_scrap,
    SUM(iss_val_scrap) as iss_val_scrap,
    SUM(rcpt_tot_stck) as rcpt_tot_stck,
    SUM(iss_tot_stck) as iss_tot_stck,
    SUM(iss_qty_stck_val) as iss_qty_stck_val,
    SUM(rec_qty_val_stck) as rec_qty_val_stck,
    SUM(vdr_cnsgnmnt_stck_cnval) as vdr_cnsgnmnt_stck_cnval,
    SUM(rec_val_q_stck) as rec_val_q_stck,
    SUM(rec_val_blok) as rec_val_blok,
    SUM(iss_val_blok) as iss_val_blok,
    SUM(iss_val_q_stck) as iss_val_q_stck,
    SUM(rec_val_trst) as rec_val_trst,
    SUM(iss_val_trst) as iss_val_trst,
    SUM(iss_val_cons_stck) as iss_val_cons_stck,
    SUM(rcpt_val_cons_stk) as rcpt_val_cons_stk,
    SUM(bw_prch_val) as bw_prch_val,
    SUM(bw_amt_bunitm) as bw_amt_bunitm,
    SUM(delv_cost) as delv_cost,
    SUM(std_matl_cost) as std_matl_cost,
    SUM(prc_unit) as prc_unit,
    SUM(line_cnt) as line_cnt
FROM source
GROUP BY
    nvl(trim(lcl_crncy)::string,''),
    nvl(trim(base_unit)::string,''),
    nvl(trim(matl_no)::string,''),
    nvl(trim(strg_loc)::string,''),
    nvl(trim(stk_type)::string,''),
    nvl(trim(stk_cat)::string,''),
    nvl(trim(co_cd)::string,''),
    nvl(trim(matl_plnt_view)::string,''),
    nvl(trim(btch_num)::string,''),
    nvl(trim(plnt)::string,''),
    nvl(trim(whse_num)::string,''),
    nvl(trim(strg_bin)::string,''),
    nvl(trim(strg_type)::string,''),
    nvl(trim(spl_stck_val)::string,''),
    nvl(trim(spl_stck_indica)::string,''),
    trim(doc_dt),
    nvl(trim(valut_cls)::string,''),
    nvl(trim(valut_area)::string,''),
    nvl(trim(valut_type)::string,''),
    trim(pstng_dt),
    trim(cal_day),
    nvl(trim(wh_mstr)::string,''),
    nvl(trim(vers)::string,''),
    trim(val_type),
    nvl(trim(vend)::string,''),
    nvl(trim(sold_to_prty)::string,''),
    nvl(trim(mvmt_ind_sec)::string,''),
    nvl(trim(crncy)::string,''),
    nvl(trim(fisc_yr_vrnt)::string,''),
    trim(fisc_yr),
    trim(cal_yr),
    trim(cal_mo),
    trim(qtr),
    trim(cal_yr_qtr),
    trim(cal_yr_wk),
    trim(pstng_per),
    trim(half_yr),
    trim(wkday),
    trim(fisc_yr_per),
    trim(cal_yr_mon)
)

select * from final