{{
    config(
        alias="wks_edw_customer_base_dim",
        sql_header="ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized="incremental",
        incremental_strategy="merge",
        unique_key=["cust_num_1"],
        merge_exclude_columns=["crt_dttm"],
        tags=[""]
    )
}}
with
    itg_cust_base as 
        (select * from {{ ref('aspitg_integration__itg_cust_base') }}
        ),
    itg_cust_text as 
        (select * from {{ ref('aspitg_integration__itg_cust_text') }}
        ),
    final as (
        select
    clnt,
    cust_num_1,
    nm,
    addr,
    title,
    cntrl_ordr_blk_cust,
    exp_train_stn,
    train_stn,
    intnl_loc_num1,
    intnl_loc_num2,
    auth_grp,
    indstr_key,
    chk_dig_intnl_loc_num,
    data_comm_line_no,
    dt_on_rec_crt,
    nm_prsn_crt_obj,
    unld_pt_exist_ind,
    cent_bill_blk_cust,
    acct_num_mstr_rec_fisc_addr,
    wrk_num_cal,
    acct_num_alt_pyr,
    grp_key,
    cust_acct_grp,
    cust_clsn,
    ctry_key,
    acct_num_vend,
    cent_delv_blk_cust,
    city_coordnt,
    cent_del_fl_mstr_rec,
    nm_1,
    nm_2,
    nm_3,
    nm_4,
    nlsn_id,
    city,
    dstrc,
    po_box,
    po_box_pstl_cd,
    pstl_cd,
    rgn,
    cnty_cd,
    city_cd,
    fcst_chnl,
    srt_fld,
    cent_pstng_blk,
    lang_key,
    tax_num_1,
    tax_num_2,
    busn_ptnr_subj_eqlztn_tax_ind,
    liab_for_vat,
    hs_num_and_street,
    telebox_num,
    fst_phn_num,
    sec_phn_num,
    fax_num,
    teletex_num,
    telex_num,
    trspn_zn_goods_delv,
    is_acct_one_time_acct_ind,
    alt_payee_doc_allw_ind,
    co_id_trad_ptnr,
    vat_regs_num,
    cmpt_ind,
    sls_ptnr_ind,
    sls_prosp_ind,
    for_cust_type4_ind,
    id_dflt_sold_to_prty,
    in_cnsmr,
    legal_sts,
    indstr_cd_1,
    indstr_cd_2,
    indstr_cd_3,
    indstr_cd_4,
    indstr_cd_5,
    init_cntct,
    annl_sls_1,
    yr_for_sls_gvn,
    crncy_sls_fig,
    yr_num_emp,
    yr_for_num_emp_gvn,
    attr_1,
    attr_2,
    attr_3,
    attr_4,
    attr_5,
    attr_6,
    attr_7,
    attr_8,
    attr_9,
    attr_10,
    ntrl_prsn,
    annl_sls_2,
    tax_juris,
    srch_term_match_cd_srch1,
    srch_term_match_cd_srch2,
    srch_term_match_cd_srch3,
    fisc_yr_vrnt,
    usg_ind,
    insp_carr_out_by_cust,
    insp_delv_note_after_outb_delv,
    ref_acct_grp_one_time_acct,
    po_box_city,
    plnt,
    data_med_exch_ind,
    instr_key_data_med_exch,
    sts_data_tfr_subsq_rlse,
    asgnmt_hier,
    pmt_blk,
    cust_grp,
    id_mn_non_mil_use,
    id_mn_mil_use,
    cust_cond_grp_1,
    cust_cond_grp_2,
    cust_cond_grp_3,
    cust_cond_grp_4,
    cust_cond_grp_5,
    alt_pyr_acct_num_ind,
    tax_type,
    tax_num_type,
    tax_num3,
    tax_num4,
    cust_is_icms_expt,
    cust_is_ipi_expt,
    cust_grp_tax_subst,
    cust_cfop_cat,
    tax_law_icms,
    tax_law_ipi,
    biochem_wf_ind,
    nuclr_np_ind,
    natl_scty_ind,
    missile_tech_ind,
    cent_sls_blk_cust,
    unifm_rsrs_lctr,
    current_timestamp()::timestamp_ntz(9) as crt_dttm,
    current_timestamp()::timestamp_ntz(9) as updt_dttm
  from (
    select
      a.*,
      b.nm as nm
    from itg_cust_base as a
    left outer join itg_cust_text as b
      on a.cust_num_1 = b.cust_num1
  ) as src
)

select * from final
