with source as (
    select * from {{ ref('aspitg_integration__itg_invnt') }}
),
final as(
    SELECT
    lcl_crncy,
    base_unit,
    matl_no,
    strg_loc,
    stk_type,
    stk_cat,
    co_cd,
    matl_plnt_view,
    btch_num,
    plnt,
    whse_num,
    strg_bin,
    strg_type,
    spl_stck_val,
    spl_stck_indica,
    doc_dt,
    valut_cls,
    valut_area,
    valut_type,
    pstng_dt,
    cal_day,
    wh_mstr,
    vers,
    val_type,
    vend,
    sold_to_prty,
    mvmt_ind_sec,
    crncy,
    fisc_yr_vrnt,
    fisc_yr,
    cal_yr,
    cal_mo,
    qtr,
    cal_yr_qtr,
    cal_yr_wk,
    pstng_per,
    half_yr,
    wkday,
    fisc_yr_per,
    cal_yr_mon,
    SUM(stck_rec_val) AS stck_rec_val,
    SUM(iss_stck_val) AS iss_stck_val,
    SUM(iss_blok_qty) AS iss_blok_qty,
    SUM(cng_stk_qty_iss) AS cng_stk_qty_iss,
    SUM(iss_qty_qual) AS iss_qty_qual,
    SUM(iss_qty_trst) AS iss_qty_trst,
    SUM(rcpt_qty_blok) AS rcpt_qty_blok,
    SUM(cns_stck_rcpt) AS cns_stck_rcpt,
    SUM(rcpt_qty_qual) AS rcpt_qty_qual,
    SUM(rcpt_qty_trst) AS rcpt_qty_trst,
    SUM(iss_qty_scrap) AS iss_qty_scrap,
    SUM(iss_val_scrap) AS iss_val_scrap,
    SUM(rcpt_tot_stck) AS rcpt_tot_stck,
    SUM(iss_tot_stck) AS iss_tot_stck,
    SUM(iss_qty_stck_val) AS iss_qty_stck_val,
    SUM(rec_qty_val_stck) AS rec_qty_val_stck,
    SUM(vdr_cnsgnmnt_stck_cnval) AS vdr_cnsgnmnt_stck_cnval,
    SUM(rec_val_q_stck) AS rec_val_q_stck,
    SUM(rec_val_blok) AS rec_val_blok,
    SUM(iss_val_blok) AS iss_val_blok,
    SUM(iss_val_q_stck) AS iss_val_q_stck,
    SUM(rec_val_trst) AS rec_val_trst,
    SUM(iss_val_trst) AS iss_val_trst,
    SUM(iss_val_cons_stck) AS iss_val_cons_stck,
    SUM(rcpt_val_cons_stk) AS rcpt_val_cons_stk,
    SUM(bw_prch_val) AS bw_prch_val,
    SUM(bw_amt_bunitm) AS bw_amt_bunitm,
    SUM(delv_cost) AS delv_cost,
    SUM(std_matl_cost) AS std_matl_cost,
    SUM(prc_unit) AS prc_unit,
    SUM(line_cnt) AS line_cnt
FROM source
GROUP BY
    lcl_crncy,
    base_unit,
    matl_no,
    strg_loc,
    stk_type,
    stk_cat,
    co_cd,
    matl_plnt_view,
    btch_num,
    plnt,
    whse_num,
    strg_bin,
    strg_type,
    spl_stck_val,
    spl_stck_indica,
    doc_dt,
    valut_cls,
    valut_area,
    valut_type,
    pstng_dt,
    cal_day,
    wh_mstr,
    vers,
    val_type,
    vend,
    sold_to_prty,
    mvmt_ind_sec,
    crncy,
    fisc_yr_vrnt,
    fisc_yr,
    cal_yr,
    cal_mo,
    qtr,
    cal_yr_qtr,
    cal_yr_wk,
    pstng_per,
    half_yr,
    wkday,
    fisc_yr_per,
    cal_yr_mon
)

select * from final