--Import CTE
with source as (
    select *
    from {{ ref('aspitg_intgeration__vw_stg_sdl_sap_ecc_material_base') }}
),

--Logical CTE

--Final CTE
final as (
    select
        mandt,
        matnr,
        ersda,
        ernam,
        laeda,
        aenam,
        vpsta,
        pstat,
        lvorm,
        mtart,
        mbrsh,
        matkl,
        bismt,
        meins,
        bstme,
        zeinr,
        zeiar,
        zeivr,
        zeifo,
        aeszn,
        blatt,
        blanz,
        ferth,
        formt,
        groes,
        wrkst,
        normt,
        labor,
        ekwsl,
        brgew,
        ntgew,
        gewei,
        volum,
        voleh,
        behvo,
        raube,
        tempb,
        disst,
        tragr,
        stoff,
        spart,
        kunnr,
        eannr,
        wesch,
        bwvor,
        bwscl,
        saiso,
        etiar,
        etifo,
        entar,
        ean11,
        numtp,
        laeng,
        breit,
        hoehe,
        meabm,
        prdha,
        aeklk,
        cadkz,
        qmpur,
        ergew,
        ergei,
        ervol,
        ervoe,
        gewto,
        volto,
        vabme,
        kzrev,
        kzkfg,
        xchpf,
        vhart,
        fuelg,
        stfak,
        magrv,
        begru,
        datab,
        liqdt,
        saisj,
        plgtp,
        mlgut,
        extwg,
        satnr,
        attyp,
        kzkup,
        kznfm,
        pmata,
        mstae,
        mstav,
        mstde,
        mstdv,
        taklv,
        rbnrm,
        mhdrz,
        mhdhb,
        mhdlp,
        inhme,
        inhal,
        vpreh,
        etiag,
        inhbr,
        cmeth,
        cuobf,
        kzumw,
        kosch,
        sprof,
        nrfhg,
        mfrpn,
        mfrnr,
        bmatn,
        mprof,
        kzwsm,
        saity,
        profl,
        ihivi,
        iloos,
        serlv,
        kzgvh,
        xgchp,
        kzeff,
        compl,
        iprkz,
        rdmhd,
        przus,
        mtpos_mara,
        bflme,
        zz_mvgr1,
        zz_mvgr2,
        zz_mvgr3,
        zz_mvgr4,
        zz_mvgr5,
        zz_technology,
        zz_color,
        zz_stack_factor,
        zz_mfgsource,
        --tgt.crt_dttm as tgt_crt_dttm,
        updt_dttm
        --case when tgt.crt_dttm is null then 'i' else 'u' end as chng_flg
    from source
)

--Final select
select * from final
