with sources as(
    SELECT *
    FROM {{ ref('aspitg_integration__vw_stg_sdl_sap_bw_inventory') }}
),
--logical CTE
final as (
    select
    request_number,
    data_packet,
    data_record,
    loc_currcy,
    base_uom,
    material,
    stor_loc,
    stocktype,
    stockcat,
    comp_code,
    mat_plant,
    bic_zbatch,
    plant,
    whse_num,
    strge_bin,
    strge_type,
    indspecstk,
    bic_zmdsobkz,
    doc_date,
    val_class,
    id_valarea,
    val_type,
    pstng_date,
    calday,
    bic_zmat_wh,
    version,
    vtype,
    vendor,
    sold_to,
    bic_zmoveinds,
    currency,
    fiscvarnt,
    fiscyear,
    calyear,
    calmonth2,
    calquart1,
    calquarter,
    calweek,
    fiscper3,
    halfyear1,
    weekday1,
    fiscper,
    calmonth,
    recvs_val,
    issvs_val,
    issblostck,
    isscnsstck,
    issqmstck,
    isstransst,
    recblostck,
    reccnsstck,
    recqmstck,
    rectransst,
    issscrp,
    issvalscrp,
    rectotstck,
    isstotstck,
    issvalstck,
    recvalstck,
    venconcon,
    recvalqm,
    recvalblo,
    issvalbloc,
    issvalqm,
    rectrfstva,
    isstrfstva,
    issccnsval,
    recccnsval,
    cppvlc,
    cpquabu,
    bic_zmddelct,
    g_avv040,
    price_unit,
    bic_zlincount,
    updt_dttm
     FROM {{ ref('aspitg_integration__vw_stg_sdl_sap_bw_inventory') }}

)

select * from final