--import CTE

with sources as(
    SELECT *
    FROM {{ ref('aspitg_integration__vw_stg_sdl_sap_bw_copa17') }}
),
--logical CTE
final as(
    SELECT
    request_number,
    data_packet,
    data_record,
    fiscper,
    fiscvarnt,
    fiscyear,
    calday,
    fiscper3,
    calmonth,
    calyear,
    version,
    vtype,
    comp_code,
    co_area,
    profit_ctr,
    salesemply,
    salesorg,
    sales_grp,
    sales_off,
    cust_group,
    distr_chan,
    sales_dist,
    customer,
    material,
    cust_sales,
    division,
    plant,
    zmercref,
    zz_mvgr1,
    zz_mvgr2,
    zz_mvgr3,
    zz_mvgr4,
    zz_mvgr5,
    region,
    country,
    prodh6,
    prodh5,
    prodh4,
    prodh3,
    prodh2,
    prodh1,
    zfis_quar,
    mat_sales,
    bill_type,
    jjfiscwe,
    amocac,
    amoccc,
    currency,
    obj_curr,
    account,
    chrt_accts,
    zz_wwme,
    zsalesper,
    bus_area,
    grossamttc,
    curkey_tc,
    mat_plant,
    quantity,
    unit,
    zqtyieu,
    zunitieu,
    zbpt_dc,
    --TGT.CRT_DTTM AS TGT_CRT_DTTM,
    updt_dttm
from sources
)
--final select
select * from final