with source as(
    select * from {{ ref('aspitg_integration__vw_stg_sdl_sap_bw_zc_sd') }}
),

final as(
    SELECT
    request,
    datapakid,
    record,
    zactdldte,
    act_gi_dte,
    billtoprty,
    bill_date,
    bill_type,
    bill_num,
    comp_code,
    customer,
    zdelcrdat,
    distr_chan,
    division,
    createdon,
    doc_date,
    gi_date,
    material,
    matav_date,
    ord_reason,
    zzabstk,
    zcmgst,
    payer,
    plant,
    zzp_itm,
    zzp_num,
    zsd_pod,
    zrcodekey,
    reason_rej,
    gt_cmfre,
    zreq_date,
    route,
    doc_number,
    doc_categ,
    s_ord_item,
    doc_type,
    salesemply,
    salesorg,
    item_categ,
    ship_to,
    sold_to,
    zblqtycse,
    bill_qty,
    zbilqdift,
    zbilqotif,
    inv_qty,
    zcfmqdift,
    cml_cd_qty,
    zdlqtycse,
    zdelqtybu,
    dlv_qty,
    subtotal_6,
    zfs_ntsb,
    zfs_ninv,
    zfs_qtybu,
    subtotal_1,
    subtotal_5,
    net_price,
    netval_inv,
    net_value,
    zorqtycse,
    zordqtybu,
    zordqty,
    cml_or_qty,
    zktranlt,
    zunsuppc,
    zunsupva,
    volume_dl,
    volume_ap,
    calday,
    base_uom,
    currency,
    doc_currcy,
    sales_unit,
    fiscper,
    UPDT_DTTM
  FROM source

)

select * from final