with source as (
    select * from {{ ref('aspitg_integration__itg_invc_sls') }}
),
edw_calendar_dim as (
select * from {{ ref('aspedw_integration__edw_calendar_dim') }} 
),
final as(
  SELECT
    act_delv_dt,
    act_good_iss_dt,
    bill_to_prty,
    bill_dt,
    bill_ty,
    bill_doc,
    cmpy_cd,
    cust_no,
    delv_doc_crt_dt,
    dstr_chnl,
    div,
    doc_crt_dt,
    doc_dt,
    good_iss_dt,
    mat,
    mat_avail_dt,
    ord_rsn,
    ovrl_rej_sts,
    ovrl_sts_crd_chk,
    payer,
    plant,
    prec_doc_itm,
    prec_doc_num,
    proof_delv_dt,
    rsn_cd_key,
    rsn_rej,
    rlse_dt_cr_mgmt,
    rqst_delv_dt,
    route,
    sls_doc,
    sls_doc_cat,
    sls_doc_itm,
    sls_doc_typ,
    sls_emp_hist,
    sls_org,
    sls_doc_itm_cat,
    ship_to_prty,
    sold_to_prty,
    SUM(bill_qty_cse) AS bill_qty_cse,
    SUM(bill_qty_pc) AS bill_qty_pc,
    SUM(bill_qty_difot) AS bill_qty_difot,
    SUM(bill_qty_otif) AS bill_qty_otif,
    SUM(bill_qty_sls_uom) AS bill_qty_sls_uom,
    SUM(cnfrm_qty_difot) AS cnfrm_qty_difot,
    SUM(cnfrm_qty_pc) AS cnfrm_qty_pc,
    SUM(delv_qty_cse) AS delv_qty_cse,
    SUM(delv_qty_pc) AS delv_qty_pc,
    SUM(delv_qty_sls_uom) AS delv_qty_sls_uom,
    SUM(est_nts) AS est_nts,
    SUM(nts_bill) AS nts_bill,
    SUM(net_invc_sls) AS net_invc_sls,
    SUM(fut_sls_qty) AS fut_sls_qty,
    SUM(gros_trd_sls) AS gros_trd_sls,
    SUM(net_amt) AS net_amt,
    SUM(net_prc) AS net_prc,
    SUM(net_bill_val) AS net_bill_val,
    SUM(net_ord_val) AS net_ord_val,
    SUM(ord_qty_cse) AS ord_qty_cse,
    SUM(ord_qty_pc) AS ord_qty_pc,
    SUM(ord_pc_qty) AS ord_pc_qty,
    SUM(ord_sls_qty) AS ord_sls_qty,
    SUM(tran_ldtm) AS tran_ldtm,
    SUM(unspp_qty) AS unspp_qty,
    SUM(unspp_val) AS unspp_val,
    SUM(vol_delv) AS vol_delv,
    SUM(vol_ord) AS vol_ord,
    itg_invc_sls.cal_day as cal_day,
    base_uom,
    curr_key,
    doc_curr,
    sls_unit,
    CASE
      WHEN edw_calendar_dim.fisc_per IS NULL
      THEN CAST(itg_invc_sls.fisc_yr as int)
      ELSE edw_calendar_dim.fisc_per
    END AS fisc_yr,
    itg_invc_sls.fisc_yr AS fisc_yr_src
  FROM source as itg_invc_sls
  LEFT OUTER JOIN edw_calendar_dim
    ON itg_invc_sls.bill_dt = edw_calendar_dim.cal_day
  GROUP BY
    act_delv_dt,
    act_good_iss_dt,
    bill_to_prty,
    bill_dt,
    bill_ty,
    bill_doc,
    cmpy_cd,
    cust_no,
    delv_doc_crt_dt,
    dstr_chnl,
    DIV,
    doc_crt_dt,
    doc_dt,
    good_iss_dt,
    mat,
    mat_avail_dt,
    ord_rsn,
    ovrl_rej_sts,
    ovrl_sts_crd_chk,
    payer,
    plant,
    prec_doc_itm,
    prec_doc_num,
    proof_delv_dt,
    rsn_cd_key,
    rsn_rej,
    rlse_dt_cr_mgmt,
    rqst_delv_dt,
    route,
    sls_doc,
    sls_doc_cat,
    sls_doc_itm,
    sls_doc_typ,
    sls_emp_hist,
    sls_org,
    sls_doc_itm_cat,
    ship_to_prty,
    sold_to_prty,
    itg_invc_sls.cal_day,
    base_uom,
    curr_key,
    doc_curr,
    sls_unit,
    itg_invc_sls.fisc_yr,
    edw_calendar_dim.fisc_per

)

select * from final
