{{
    config(
        alias= "wks_material_dim",
        sql_header= "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        tags= ["daily"]
    )
}}


with itg_material_base as (
    select * from {{ ref('aspitg_integration__itg_material_base') }}
),
itg_matl_text as (
    select * from {{ ref('aspitg_integration__itg_matl_text') }}
),
itg_mega_brnd_text as (
    select * from {{ ref('aspitg_integration__itg_mega_brnd_text') }}
),
itg_brnd_text as (
    select * from {{ ref('aspitg_integration__itg_brnd_text') }}
),
itg_varnt_text as (
    select * from {{ ref('aspitg_integration__itg_varnt_text') }}
),
itg_base_prod_text as(
    select * from {{ ref('aspitg_integration__itg_base_prod_text') }}
),
itg_put_up_text as (
    select * from {{ ref('aspitg_integration__itg_put_up_text') }}
),
src as (
    select itg_material_base.*,
             itg_matl_text.matl_desc,
             itg_mega_brnd_text.de as mega_brnd_desc,
             itg_brnd_text.brnd_desc as ibrnd_desc,
             itg_varnt_text.varnt_desc as varnt_desc,
             itg_base_prod_text.base_prod_desc as base_prod_desc,
             itg_put_up_text.put_up_desc as put_up_desc
      from  itg_material_base
        left outer join itg_matl_text
                     on itg_material_base.matl_num = itg_matl_text.matl_no
                    and itg_matl_text.lang_key = 'E'
        left outer join itg_mega_brnd_text
                     on itg_material_base.mega_brnd_cd = itg_mega_brnd_text.mega_brnd
                    and itg_mega_brnd_text.lang_key = 'E'
        left outer join itg_brnd_text
                     on itg_material_base.brnd_cd = itg_brnd_text.brnd
                    and itg_brnd_text.lang_key = 'E'
        left outer join itg_varnt_text
                     on itg_material_base.vrnt = itg_varnt_text.varnt
                    and itg_varnt_text.lang_key = 'E'
        left outer join itg_base_prod_text
                     on itg_material_base.prod_base = itg_base_prod_text.base_prod
                    and itg_base_prod_text.lang_key = 'E'
        left outer join itg_put_up_text
                     on itg_material_base.put_up = itg_put_up_text.put_up
                    and itg_put_up_text.lang_key = 'E'
),
final as (
    select 
        src.matl_num,
        matl_desc,
        crt_on,
        crt_by_nm,
        chg_dttm,
        chg_by_nm,
        maint_sts_cmplt_matl,
        maint_sts,
        fl_matl_del_clnt_lvl,
        matl_type_cd,
        indstr_sectr,
        matl_grp_cd,
        old_matl_num,
        base_uom_cd,
        prch_uom_cd,
        doc_num,
        doc_type,
        doc_vers,
        pg_fmt__doc,
        doc_chg_num,
        pg_num_doc,
        num_sht,
        prdtn_memo_txt,
        pg_fmt_prdtn_memo,
        size_dims_txt,
        bsc_matl,
        indstr_std_desc,
        mercia_plan,
        prchsng_val_key,
        grs_wt_meas,
        net_wt_meas,
        wt_uom_cd,
        vol_meas,
        vol_uom_cd,
        cntnr_rqr,
        strg_cond,
        temp_cond_ind,
        low_lvl_cd,
        trspn_grp,
        haz_matl_num,
        div,
        cmpt,
        ean_obsol,
        gr_prtd_qty,
        prcmt_rule,
        src_supl,
        seasn_cat,
        lbl_type_cd,
        lbl_form,
        deact,
        prmry_upc_cd,
        ean_cat,
        lgth_meas,
        wdth_meas,
        hght_meas,
        dim_uom_cd,
        prod_hier_cd,
        stk_tfr_chg_cost,
        cad_ind,
        qm_prcmt_act,
        allw_pkgng_wt,
        wt_unit,
        allw_pkgng_vol,
        vol_unit,
        exces_wt_tlrnc,
        exces_vol_tlrnc,
        var_prch_ord_unit,
        rvsn_lvl_asgn_matl,
        configurable_matl_ind,
        btch_mgmt_reqt_ind,
        pkgng_matl_type_cd,
        max_lvl_vol,
        stack_fact,
        pkgng_matl_grp,
        auth_grp,
        vld_from_dt,
        del_dt,
        seasn_yr,
        prc_bnd_cat,
        bill_of_matl,
        extrnl_matl_grp_txt,
        cross_plnt_cnfg_matl,
        matl_cat,
        matl_coprod_ind,
        fllp_matl_ind,
        prc_ref_matl,
        cros_plnt_matl_sts,
        cros_dstn_chn_matl_sts,
        cros_plnt_matl_sts_vld_dt,
        chn_matl_vld_from_dt,
        tax_clsn_matl,
        catlg_prfl,
        min_rmn_shlf_lif,
        tot_shlf_lif,
        strg_pct,
        cntnt_uom_cd,
        net_cntnt_meas,
        cmpr_prc_unit,
        isr_matl_grp,
        grs_cntnt_meas,
        qty_conv_meth,
        intrnl_obj_num,
        envmt_rlvnt,
        prod_allc_dtrmn_proc,
        prc_prfl_vrnt,
        matl_qual_disc,
        mfr_part_num,
        mfr_num,
        intrnl_inv_mgmt,
        mfr_part_prfl,
        meas_usg_unit,
        rollout_seasn,
        dngrs_goods_ind_prof,
        hi_viscous_ind,
        in_bulk_lqd_ind,
        lvl_explc_ser_num,
        pkgng_matl_clse_pkgng,
        appr_btch_rec_ind,
        ovrd_chg_num,
        matl_cmplt_lvl,
        per_ind_shlf_lif_expn_dt,
        rd_rule_sled,
        prod_cmpos_prtd_pkgng,
        genl_item_cat_grp,
        gn_matl_logl_vrnt,
        prod_base,
        vrnt,
        put_up,
        mega_brnd_cd,
        brnd_cd,
        tech,
        color,
        seasonality,
        mfg_src_cd,
        null as tgt_crt_dttm,
        updt_dttm,
        null as chng_flg,
        mega_brnd_desc,
        ibrnd_desc,
        varnt_desc,
        base_prod_desc,
        put_up_desc,
        mfr_part_num_new,
        formulation_num,               
        pka_franchise_cd,               
        pka_franchise_desc,             
        pka_brand_cd,            
        pka_brand_desc,                 
        pka_sub_brand_cd,               
        pka_sub_brand_desc,             
        pka_variant_cd,                 
        pka_variant_desc,               
        pka_sub_variant_cd,             
        pka_sub_variant_desc,           
        pka_flavor_cd,                  
        pka_flavor_desc,                
        pka_ingredient_cd,              
        pka_ingredient_desc,            
        pka_application_cd,             
        pka_application_desc,           
        pka_length_cd,                  
        pka_length_desc,                
        pka_shape_cd,                   
        pka_shape_desc,                 
        pka_spf_cd,                     
        pka_spf_desc,                   
        pka_cover_cd,                   
        pka_cover_desc,                 
        pka_form_cd,                    
        pka_form_desc,                  
        pka_size_cd,                    
        pka_size_desc,                  
        pka_character_cd,               
        pka_character_desc,             
        pka_package_cd,                 
        pka_package_desc,               
        pka_attribute_13_cd,            
        pka_attribute_13_desc,          
        pka_attribute_14_cd,            
        pka_attribute_14_desc,          
        pka_sku_identification_cd,      
        pka_sku_identification_desc,    
        pka_one_time_relabeling_cd,     
        pka_one_time_relabeling_desc,   
        pka_product_key,                
        pka_product_key_description,  
        pka_product_key_description_2,  
        pka_root_code,                  
        pka_root_code_desc_1,           
        pka_root_code_desc_2
from  src
)

select * from final