with source as 
(
    select * from {{ source('indedw_integration', 'edw_rpt_sku_recom_management') }}
)
select
    dataset as "dataset",
    mth_mm as "mth_mm",
    region_name as "region_name",
    zone_name as "zone_name",
    territory_name as "territory_name",
    cust_cd as "cust_cd",
    salesman_code as "salesman_code",
    salesman_name as "salesman_name",
    unique_sales_code as "unique_sales_code",
    channel_name as "channel_name",
    class_desc as "class_desc",
    retailer_channel_level_3 as "retailer_channel_level_3",
    franchise_name as "franchise_name",
    brand_name as "brand_name",
    product_category_name as "product_category_name",
    variant_name as "variant_name",
    mothersku_name as "mothersku_name",
    total_stores as "total_stores",
    total_recos as "total_recos",
    total_hits as "total_hits",
    total_os as "total_os",
    total_os_perc as "total_os_perc",
    store_tag as "store_tag",
    os_week0 as "os_week0",
    os_week1 as "os_week1",
    os_week2 as "os_week2",
    os_week3 as "os_week3",
    os_week4 as "os_week4",
    os_week5 as "os_week5",
    os_perc_week0 as "os_perc_week0",
    os_perc_week1 as "os_perc_week1",
    os_perc_week2 as "os_perc_week2",
    os_perc_week3 as "os_perc_week3",
    os_perc_week4 as "os_perc_week4",
    os_perc_week5 as "os_perc_week5",
    achievement_nr_all_msku as "achievement_nr_all_msku",
    achievement_nr_msl_msku as "achievement_nr_msl_msku",
    crt_dttm as "crt_dttm",
    updt_dttm as "updt_dttm",
    week as "week",
    retailer_cd as "retailer_cd",
    quantity as "quantity",
    ret_msku as "ret_msku",
    ms_flag as "ms_flag",
    os_flag as "os_flag"
from source
