with source as 
(
    select * from {{ ref('indedw_integration__edw_rpt_decision_cockpit_details') }}
)
select
    dataset as "dataset",
    mth_mm as "mth_mm",
    week as "week",
    region_name as "region_name",
    zone_name as "zone_name",
    territory_name as "territory_name",
    customer_code as "customer_code",
    retailer_code as "retailer_code",
    customer_name as "customer_name",
    retailer_name as "retailer_name",
    channel_name as "channel_name",
    brand_name as "brand_name",
    franchise_name as "franchise_name",
    territory_classification as "territory_classification",
    class_desc as "class_desc",
    retailer_category_name as "retailer_category_name",
    salesman_name as "salesman_name",
    salesman_code as "salesman_code",
    uniquesalescode as "uniquesalescode",
    sales_cube_program_name as "sales_cube_program_name",
    target_value as "target_value",
    achievement_nr as "achievement_nr",
    num_buying_retailers as "num_buying_retailers",
    num_bills as "num_bills",
    num_packs as "num_packs",
    num_lines as "num_lines",
    customer_type as "customer_type",
    closing_stock as "closing_stock",
    billing_value as "billing_value",
    measure_type as "measure_type",
    brand_focus_target as "brand_focus_target",
    business_plan_target as "business_plan_target",
    schemeamt as "schemeamt",
    franchise_channel as "franchise_channel",
    franchise_datasource as "franchise_datasource",
    sls_actl_val as "sls_actl_val",
    targetbills as "targetbills",
    product_category1 as "product_category1",
    product_category2 as "product_category2",
    product_category3 as "product_category3",
    product_category4 as "product_category4",
    retailer_channel_level1 as "retailer_channel_level1",
    retailer_channel_level2 as "retailer_channel_level2",
    fiscyr as "fiscyr",
    fiscmonth as "fiscmonth",
    day as "day",
    salesman_status as "salesman_status",
    net_amt as "net_amt",
    crt_dttm as "crt_dttm",
    retailer_channel_level3 as "retailer_channel_level3",
    rtruniquecode as "rtruniquecode",
    mothersku_code as "mothersku_code"
from source
