with source as 
(
    select * from {{ ref('indedw_integration__v_rpt_order_details') }}
)
select
    customer_code as "customer_code",
    customer_name as "customer_name",
    region_name as "region_name",
    zone_name as "zone_name",
    territory_name as "territory_name",
    salesman_code as "salesman_code",
    route_code as "route_code",
    retailer_code as "retailer_code",
    salesman_name as "salesman_name",
    route_name as "route_name",
    retailer_name as "retailer_name",
    product_code as "product_code",
    product_name as "product_name",
    franchise_name as "franchise_name",
    brand_name as "brand_name",
    variant_name as "variant_name",
    product_category_name as "product_category_name",
    mothersku_name as "mothersku_name",
    invoice_no as "invoice_no",
    order_date as "order_date",
    order_no as "order_no",
    ord_dt_week as "ord_dt_week",
    ord_dt_month as "ord_dt_month",
    ord_dt_year as "ord_dt_year",
    invoice_product_quantity as "invoice_product_quantity",
    invoice_product_nr_amount as "invoice_product_nr_amount",
    invoice_tax_amount as "invoice_tax_amount",
    order_product_quantity as "order_product_quantity",
    order_product_nr_amount as "order_product_nr_amount",
    csrtrcode as "csrtrcode",
    abi_ntid as "abi_ntid",
    flm_ntid as "flm_ntid",
    bdm_ntid as "bdm_ntid",
    rsm_ntid as "rsm_ntid",
    class_desc as "class_desc",
    retailer_category_name as "retailer_category_name",
    channel_name as "channel_name",
    cfa as "cfa",
    cfa_name as "cfa_name"
from source
