with source as 
(
    select * from {{ ref('indedw_integration__v_rpt_gt_target_vs_actuals') }}
)
select
    year as "year",
    month as "month",
    week as "week",
    customer_code as "customer_code",
    retailer_code as "retailer_code",
    customer_name as "customer_name",
    salesman_code as "salesman_code",
    salesman_name as "salesman_name",
    brand_name as "brand_name",
    route_code as "route_code",
    route_name as "route_name",
    region_name as "region_name",
    region_code as "region_code",
    zone_code as "zone_code",
    zone_name as "zone_name",
    territory_code as "territory_code",
    territory_name as "territory_name",
    territory_classification as "territory_classification",
    state_code as "state_code",
    state_name as "state_name",
    town_code as "town_code",
    town_name as "town_name",
    town_classification as "town_classification",
    city as "city",
    type_code as "type_code",
    type_name as "type_name",
    targetgt as "targetgt",
    nrvalue as "nrvalue",
    targetbills as "targetbills",
    bills as "bills",
    targetpack as "targetpack",
    packs as "packs",
    sm_tgt_amt as "sm_tgt_amt",
    measure_type as "measure_type",
    abi_ntid as "abi_ntid",
    flm_ntid as "flm_ntid",
    bdm_ntid as "bdm_ntid",
    rsm_ntid as "rsm_ntid",
    num_buying_retailers as "num_buying_retailers",
    active_flag as "active_flag",
    status_desc as "status_desc",
    achievement_amt as "achievement_amt",
    channel_name as "channel_name",
    day as "day",
    salesman_status as "salesman_status"
from source
