with cit80saleh_uri as (
    select * from {{ source('jpdcledw_integration', 'cit80saleh_uri_mv') }}
),
cit80saleh_hen as (
    select * from {{ source('jpdcledw_integration', 'cit80saleh_hen_mv') }}
),
t1 as (
    SELECT cit80saleh_uri.saleno,
    cit80saleh_uri.juchkbn,
    cit80saleh_uri.torikeikbn,
    cit80saleh_uri.juchdate,
    cit80saleh_uri.kokyano,
    cit80saleh_uri.hanrocode,
    cit80saleh_uri.syohanrobunname,
    cit80saleh_uri.chuhanrobunname,
    cit80saleh_uri.daihanrobunname,
    cit80saleh_uri.mediacode,
    cit80saleh_uri.kessaikbn,
    cit80saleh_uri.shohingokei,
    cit80saleh_uri.soryo,
    cit80saleh_uri.tax,
    cit80saleh_uri.sogokei,
    cit80saleh_uri.komiwarikingaku,
    cit80saleh_uri.warimaenukigokei,
    cit80saleh_uri.warimaetax,
    cit80saleh_uri.transbincode,
    cit80saleh_uri.shukadate,
    cit80saleh_uri.cardcorpcode,
    cit80saleh_uri.henreasoncode,
    cit80saleh_uri.cancelflg,
    cit80saleh_uri.nyuhenkin,
    cit80saleh_uri.nyuhenkanflg,
    cit80saleh_uri.insertid,
    cit80saleh_uri.updateid,
    cit80saleh_uri.kaisha,
    cit80saleh_uri.nukikingaku,
    cit80saleh_uri.insertdate,
    cit80saleh_uri.inserttime,
    cit80saleh_uri.updatedate,
    cit80saleh_uri.updatetime,
    cit80saleh_uri.riyopoint,
    cit80saleh_uri.okurino,
    cit80saleh_uri.kiboudate,
    cit80saleh_uri.juchno,
    cit80saleh_uri.juchnibuno,
    cit80saleh_uri.shkano,
    cit80saleh_uri.kakokbn,
    cit80saleh_uri.henreasonname,
    cit80saleh_uri.uketsukeusrid,
    cit80saleh_uri.uketsuketelcompanycd,
    cit80saleh_uri.dispsaleno,
    cit80saleh_uri.smkeiroid,
    cit80saleh_uri.smkeironame,
    cit80saleh_uri.dipromid,
    cit80saleh_uri.happenpoint,
    cit80saleh_uri.contea,
    cit80saleh_uri.conteb,
    cit80saleh_uri.contec,
    cit80saleh_uri.conted,
    cit80saleh_uri.contee,
    cit80saleh_uri.contef,
    cit80saleh_uri.conteg,
    cit80saleh_uri.conteh,
    cit80saleh_uri.contei,
    cit80saleh_uri.contej,
    cit80saleh_uri.marker,
    cit80saleh_uri.fskbn,
    cit80saleh_uri.bmn_hyouji_cd,
    cit80saleh_uri.bmn_nms,
    cit80saleh_uri.pointkominukikingaku
FROM cit80saleh_uri
),
t2 as (
    SELECT cit80saleh_hen.saleno,
    cit80saleh_hen.juchkbn,
    cit80saleh_hen.torikeikbn,
    cit80saleh_hen.juchdate,
    cit80saleh_hen.kokyano,
    cit80saleh_hen.hanrocode,
    cit80saleh_hen.syohanrobunname,
    cit80saleh_hen.chuhanrobunname,
    cit80saleh_hen.daihanrobunname,
    cit80saleh_hen.mediacode,
    cit80saleh_hen.kessaikbn,
    cit80saleh_hen.shohingokei,
    cit80saleh_hen.soryo,
    cit80saleh_hen.tax,
    cit80saleh_hen.sogokei,
    cit80saleh_hen.komiwarikingaku,
    cit80saleh_hen.warimaenukigokei,
    cit80saleh_hen.warimaetax,
    cit80saleh_hen.transbincode,
    cit80saleh_hen.shukadate,
    cit80saleh_hen.cardcorpcode,
    cit80saleh_hen.henreasoncode,
    cit80saleh_hen.cancelflg,
    cit80saleh_hen.nyuhenkin,
    cit80saleh_hen.nyuhenkanflg,
    cit80saleh_hen.insertid,
    cit80saleh_hen.updateid,
    cit80saleh_hen.kaisha,
    cit80saleh_hen.nukikingaku,
    cit80saleh_hen.insertdate,
    cit80saleh_hen.inserttime,
    cit80saleh_hen.updatedate,
    cit80saleh_hen.updatetime,
    cit80saleh_hen.riyopoint,
    cit80saleh_hen.okurino,
    cit80saleh_hen.kiboudate,
    cit80saleh_hen.juchno,
    cit80saleh_hen.juchnibuno,
    cit80saleh_hen.shkano,
    cit80saleh_hen.kakokbn,
    cit80saleh_hen.henreasonname,
    cit80saleh_hen.uketsukeusrid,
    cit80saleh_hen.uketsuketelcompanycd,
    cit80saleh_hen.dispsaleno,
    cit80saleh_hen.smkeiroid,
    cit80saleh_hen.smkeironame,
    cit80saleh_hen.dipromid,
    cit80saleh_hen.happenpoint,
    cit80saleh_hen.contea,
    cit80saleh_hen.conteb,
    cit80saleh_hen.contec,
    cit80saleh_hen.conted,
    cit80saleh_hen.contee,
    cit80saleh_hen.contef,
    cit80saleh_hen.conteg,
    cit80saleh_hen.conteh,
    cit80saleh_hen.contei,
    cit80saleh_hen.contej,
    cit80saleh_hen.marker,
    cit80saleh_hen.fskbn,
    cit80saleh_hen.bmn_hyouji_cd,
    cit80saleh_hen.bmn_nms,
    cit80saleh_hen.pointkominukikingaku
FROM cit80saleh_hen
),
final as (
    SELECT *
    FROM t1
    
    UNION ALL
    
    SELECT *
    FROM t2 
)
Select * from final