with kesai_h_data_mart_sub_old_chsi_tbl
AS
(
    select * from {{ source('jpdcledw_integration', 'kesai_h_data_mart_sub_old_chsi_tbl') }}
),
final as
(
    SELECT 	saleno_key::VARCHAR(36) AS SALENO_KEY ,
        	saleno::VARCHAR(20) AS SALENO,
        	juchkbn::VARCHAR(3) AS JUCHKBN,
        	juchym::NUMBER(18,0) AS JUCHYM,
        	juchdate::NUMBER(18,0) AS JUCHDATE,
        	juchquarter::VARCHAR(3) AS JUCHQUARTER,
        	juchjigyoki::VARCHAR(60) AS JUCHJIGYOKI,
        	kokyano::VARCHAR(15) AS KOKYANO,
        	torikeikbn::VARCHAR(3) AS TORIKEIKBN,
        	cancelflg::VARCHAR(60) AS CANCELFLG,
        	hanrocode::VARCHAR(60) AS HANROCODE,
        	syohanrobunname::VARCHAR(60) AS SYOHANROBUNNAME,
        	chuhanrobunname::VARCHAR(60) AS CHUHANROBUNNAME,
        	daihanrobunname::VARCHAR(60) AS DAIHANROBUNNAME,
        	mediacode::VARCHAR(8) AS MEDIACODE,
        	tenpocode::VARCHAR(8) AS TENPOCODE,
        	shukaym::NUMBER(18,0) AS SHUKAYM,
        	shukadate::NUMBER(18,0) AS SHUKADATE,
        	shukaquarter::VARCHAR(3) AS SHUKAQUARTER,
        	shukajigyoki::VARCHAR(60) AS SHUKAJIGYOKI,
        	zipcode::VARCHAR(15) AS ZIPCODE,
        	todofukencode::VARCHAR(15) AS TODOFUKENCODE,
        	kessaikbn::VARCHAR(3) AS KESSAIKBN,
        	cardcorpcode::VARCHAR(11) AS CARDCORPCODE,
        	henreasoncode::VARCHAR(5) AS HENREASONCODE,
        	motoinsertid::VARCHAR(15) AS MOTOINSERTID,
        	motoinsertdate::NUMBER(18,0) AS MOTOINSERTDATE,
        	motoupdatedate::NUMBER(18,0) AS MOTOUPDATEDATE,
        	insertdate::NUMBER(18,0) AS INSERTDATE,
        	inserttime::NUMBER(18,0) AS INSERTTIME,
        	insertid::VARCHAR(15) AS INSERTID,
        	updatedate::NUMBER(18,0) AS UPDATEDATE,
        	updatetime::NUMBER(18,0) AS UPDATETIME,
        	updateid::VARCHAR(9) AS UPDATEID,
        	rank::VARCHAR(3) AS RANK,
        	dispsaleno::VARCHAR(18) AS DISPSALENO,
        	kesaiid::VARCHAR(60) AS KESAIID,
        	ordercode::VARCHAR(60) AS ORDERCODE,
        	maker::VARCHAR(3) AS MAKER,
        	todofuken_code::VARCHAR(60) AS TODOFUKEN_CODE,
        	henreasonname::VARCHAR(48) AS HENREASONNAME,
        	smkeiroid::NUMBER(18,0) AS SMKEIROID,
        	shukkasts::VARCHAR(6) AS SHUKKASTS,
        	shukadate_p::NUMBER(18,0) AS SHUKADATE_P,
        	transbincode::VARCHAR(3) AS TRANSBINCODE,
        	kaisha::VARCHAR(8) AS KAISHA,
        	kiboudate::NUMBER(18,0) AS KIBOUDATE,
        	tokuicode::VARCHAR(15) AS TOKUICODE,
        	sendenno::VARCHAR(9) AS SENDENNO,
        	updatedate_p::NUMBER(18,0) AS UPDATEDATE_P,
        	henreasonname_p::VARCHAR(48) AS HENREASONNAME_P,
        	henreasoncode_p::VARCHAR(8) AS HENREASONCODE_P,
        	torikeikbn_p::VARCHAR(8) AS TORIKEIKBN_P,
        	juchdate_p::NUMBER(18,0) AS JUCHDATE_P,
        	tenpocode_p::VARCHAR(8) AS TENPOCODE_P,
        	transactiontypekbn::VARCHAR(3) AS TRANSACTIONTYPEKBN,
        	inserted_date::TIMESTAMP_NTZ(9) AS INSERTED_DATE,
        	inserted_by::VARCHAR(100) AS INSERTED_BY,
        	updated_date::TIMESTAMP_NTZ(9) AS UPDATED_DATE,
        	updated_by::VARCHAR(100) AS UPDATED_BY
    FROM kesai_h_data_mart_sub_old_chsi_tbl

)
select * from final