WITH wt67itemstrategy_sale AS
(
    SELECT * FROM {{ ref('jpndcledw_integration__wt67itemstrategy_sale') }}
),

final AS
(
    SELECT wt67itemstrategy_sale.shukanengetu AS "出荷年月",
        wt67itemstrategy_sale.channel AS "チャネル",
        wt67itemstrategy_sale.konyuchubuncode AS "通信経路大区分",
        wt67itemstrategy_sale.torikeikbn AS "取引形態区分",
        wt67itemstrategy_sale.tokuicode AS "得意先",
        wt67itemstrategy_sale.hanbaiitem AS "販売商品",
        wt67itemstrategy_sale.kouseiitem AS "商品構成",
        wt67itemstrategy_sale.kosecode AS "在庫商品コード",
        wt67itemstrategy_sale.kuwake1 AS "区分け1",
        wt67itemstrategy_sale.kuwake2 AS "区分け2",
        wt67itemstrategy_sale.juchkbn AS "受注区分コード",
        wt67itemstrategy_sale.juchkbncname AS "c受注区分名",
        wt67itemstrategy_sale.suryo AS "数量",
        wt67itemstrategy_sale.hensu AS "返品数量",
        wt67itemstrategy_sale.urisuryo AS "純売上数量",
        wt67itemstrategy_sale.anbunmaegaku_tyouseimae AS "按分前金額_調整前",
        wt67itemstrategy_sale.meisainukikingaku_tyouseimae AS "明細金額_調整前",
        wt67itemstrategy_sale.anbunmaegaku_tyouseigo AS "按分前金額_調整後",
        wt67itemstrategy_sale.meisainukikingaku_tyouseigo AS "明細金額_調整後",
        wt67itemstrategy_sale.anbunmeisainukikingaku AS "伝票値引按分後売上金額",
        wt67itemstrategy_sale.channelname AS "チャネル名",
        wt67itemstrategy_sale.kuwakename1 AS "区分け1名",
        wt67itemstrategy_sale.kuwakename2 AS "区分け2名",
        wt67itemstrategy_sale.henreasoncode AS "返品理由コード",
        wt67itemstrategy_sale.henreasonname AS "返品理由",
        wt67itemstrategy_sale.sokoname AS "店舗名",
        wt67itemstrategy_sale.kubun2 AS "区分2",
        wt67itemstrategy_sale.syohingun AS "商品群",
        wt67itemstrategy_sale.jyuutenitem AS "重点商品",
        wt67itemstrategy_sale.brandno AS "ブランドno",
        wt67itemstrategy_sale.brand AS "ブランド",
        wt67itemstrategy_sale.categoryno AS "カテゴリno",
        wt67itemstrategy_sale.category AS "カテゴリ",
        wt67itemstrategy_sale.LINENO AS "ラインno",
        wt67itemstrategy_sale.line AS "ライン",
        wt67itemstrategy_sale.itemcategoryno AS "商品カテゴリno",
        wt67itemstrategy_sale.itemcategory AS "商品カテゴリ",
        wt67itemstrategy_sale.kubun2_old AS "旧区分",
        wt67itemstrategy_sale.bumon7_add_attr1 AS "部門7追加属性1",
        wt67itemstrategy_sale.bumon7_add_attr2 AS "部門7追加属性2",
        wt67itemstrategy_sale.bumon7_add_attr3 AS "部門7追加属性3",
        wt67itemstrategy_sale.bumon7_add_attr4 AS "部門7追加属性4",
        wt67itemstrategy_sale.bumon7_add_attr5 AS "部門7追加属性5",
        wt67itemstrategy_sale.bumon7_add_attr6 AS "部門7追加属性6",
        wt67itemstrategy_sale.bumon7_add_attr7 AS "部門7追加属性7",
        wt67itemstrategy_sale.bumon7_add_attr8 AS "部門7追加属性8",
        wt67itemstrategy_sale.bumon7_add_attr9 AS "部門7追加属性9",
        wt67itemstrategy_sale.bumon7_add_attr10 AS "部門7追加属性10",
        wt67itemstrategy_sale.bumon6_20kisyohingun AS "商品群_20期",
        wt67itemstrategy_sale.bumon6_20kinaieki1 AS "内訳①_20期",
        wt67itemstrategy_sale.bumon6_20kinaieki2 AS "内訳②_20期",
        wt67itemstrategy_sale.bumon6_20kinaieki3 AS "内訳③_20期",
        wt67itemstrategy_sale.bumon6_zyutensyohinyobi1 AS "重点商品予備1",
        wt67itemstrategy_sale.bumon6_zyutensyohinyobi2 AS "重点商品予備2",
        wt67itemstrategy_sale.bumon6_zyutensyohinyobi3 AS "重点商品予備3",
        wt67itemstrategy_sale.bumon6_zyutensyohinyobi4 AS "重点商品予備4",
        wt67itemstrategy_sale.bumon6_zyutensyohinyobi5 AS "重点商品予備5",
        wt67itemstrategy_sale.bumon6_okikaename AS "置き換え_名称",
        wt67itemstrategy_sale.bumon6_zukyuyosoku1 AS "需給予測1",
        wt67itemstrategy_sale.bumon6_zukyuyosoku2 AS "需給予測2",
        wt67itemstrategy_sale.bumon6_zukyuyosoku3 AS "需給予測3"
    FROM wt67itemstrategy_sale
)

SELECT * FROM final