
with tbecordermeisai_mv_tbl as 
(
    select * from {{ ref('jpndcledw_integration__tbecordermeisai_mv_tbl') }}
),final as 
(
SELECT tbecordermeisai_mv_tbl.row_number,
    tbecordermeisai_mv_tbl.dimeisaiid,
    tbecordermeisai_mv_tbl.diorderid,
    tbecordermeisai_mv_tbl.disetid,
    tbecordermeisai_mv_tbl.diid,
    tbecordermeisai_mv_tbl.c_diitemtype,
    tbecordermeisai_mv_tbl.dsitemid,
    tbecordermeisai_mv_tbl.dsitemname,
    tbecordermeisai_mv_tbl.c_dsitemnameryaku,
    tbecordermeisai_mv_tbl.diusualprc,
    tbecordermeisai_mv_tbl.ditotalprc,
    tbecordermeisai_mv_tbl.diitemtax,
    tbecordermeisai_mv_tbl.diitemnum,
    tbecordermeisai_mv_tbl.c_diitemtotalprc,
    tbecordermeisai_mv_tbl.c_didiscountmeisai,
    tbecordermeisai_mv_tbl.dishukkasts,
    tbecordermeisai_mv_tbl.c_dipresentgrantcord,
    tbecordermeisai_mv_tbl.c_dikesaiid,
    tbecordermeisai_mv_tbl.c_dsregularmeisaiid,
    tbecordermeisai_mv_tbl.c_dsordertype,
    tbecordermeisai_mv_tbl.c_disubscriptionkubun,
    tbecordermeisai_mv_tbl.c_diregularcourseid,
    tbecordermeisai_mv_tbl.dipromid,
    tbecordermeisai_mv_tbl.c_disetitemprc,
    tbecordermeisai_mv_tbl.c_dssetitemkbn,
    tbecordermeisai_mv_tbl.c_dssetitemflg,
    tbecordermeisai_mv_tbl.c_dspickingflg,
    tbecordermeisai_mv_tbl.c_dspointflg,
    tbecordermeisai_mv_tbl.c_dspointitemflg,
    tbecordermeisai_mv_tbl.c_dsnoshinshooutputflg,
    tbecordermeisai_mv_tbl.dicancel,
    tbecordermeisai_mv_tbl.c_dshenpinflg,
    tbecordermeisai_mv_tbl.dsshukaflg,
    tbecordermeisai_mv_tbl.dihenpinyoteinum,
    tbecordermeisai_mv_tbl.c_dinoshinshoitemprc,
    tbecordermeisai_mv_tbl.c_dssampleclasscd,
    tbecordermeisai_mv_tbl.c_dssamplelogicd,
    tbecordermeisai_mv_tbl.disokoid,
    tbecordermeisai_mv_tbl.dirouteid,
    tbecordermeisai_mv_tbl.c_distockchanelid,
    tbecordermeisai_mv_tbl.c_dihikiatenum,
    tbecordermeisai_mv_tbl.c_diadjustprc,
    tbecordermeisai_mv_tbl.c_dsdemandkbn,
    tbecordermeisai_mv_tbl.c_dsdiscpritekiyoflg,
    tbecordermeisai_mv_tbl.c_didiscountrate,
    tbecordermeisai_mv_tbl.c_dsmessage,
    tbecordermeisai_mv_tbl.c_diorderlineno,
    tbecordermeisai_mv_tbl.c_dikesailineno,
    tbecordermeisai_mv_tbl.c_dspotsalesno,
    tbecordermeisai_mv_tbl.c_dipotlineno,
    tbecordermeisai_mv_tbl.disetmeisaiid,
    tbecordermeisai_mv_tbl.c_difrontsortorder,
    tbecordermeisai_mv_tbl.c_dinondispflg,
    tbecordermeisai_mv_tbl.c_dsfreekbn,
    tbecordermeisai_mv_tbl.c_diusepoint,
    tbecordermeisai_mv_tbl.dsprep,
    tbecordermeisai_mv_tbl.dsren,
    tbecordermeisai_mv_tbl.dselim,
    tbecordermeisai_mv_tbl.diprepusr,
    tbecordermeisai_mv_tbl.direnusr,
    tbecordermeisai_mv_tbl.dielimusr,
    tbecordermeisai_mv_tbl.dielimflg,
    tbecordermeisai_mv_tbl.c_diwarnitemid,
    tbecordermeisai_mv_tbl.c_diyoyakuhenpinflg,
    tbecordermeisai_mv_tbl.c_dihenpinzuminum,
    tbecordermeisai_mv_tbl.c_diregulardiscountrate,
    tbecordermeisai_mv_tbl.c_dstaxkbn,
    tbecordermeisai_mv_tbl.ditaxrate
FROM TBECORDERMEISAI_MV_TBL
)
select * from final 
