WITH dm_kesai_mart_dly_general
AS (
    SELECT *
    FROM snapjpdcledw_integration.dm_kesai_mart_dly_general
    ),
final
AS (
    SELECT {{encryption_1('kokyano')}}::VARCHAR(256) AS kokyano,
        saleno_key::VARCHAR(83) AS saleno_key,
        saleno::VARCHAR(63) AS saleno,
        gyono::numeric(18,0) AS gyono,
        bun_gyono::numeric(18,0) AS bun_gyono,
        order_dt::date AS order_dt,
        ship_dt::date AS ship_dt,
        tokuiname::VARCHAR(346) AS tokuiname,
        storename::VARCHAR(131) AS storename,
        f_order::VARCHAR(5) AS f_order,
        f_ship445::VARCHAR(5) AS f_ship445,
        channel::VARCHAR(20) AS channel,
        dspromcode::numeric(18,0) AS dspromcode,
        dspromname::VARCHAR(384) AS dspromname,
        juchkbn::VARCHAR(3) AS juchkbn,
        meisaikbn::VARCHAR(36) AS meisaikbn,
        h_o_item_code::VARCHAR(30) AS h_o_item_code,
        h_o_item_name::VARCHAR(200) AS h_o_item_name,
        h_o_item_cname::VARCHAR(240) AS h_o_item_cname,
        h_o_item_anbun_qty::numeric(16,8) AS h_o_item_anbun_qty,
        h_item_code::VARCHAR(60) AS h_item_code,
        z_o_item_code::VARCHAR(45) AS z_o_item_code,
        z_item_code::VARCHAR(45) AS z_item_code,
        ratio::numeric(16,8) AS ratio,
        z_item_suryo::numeric(18,0) AS z_item_suryo,
        z_item_hen_suryo::numeric(18,0) AS z_item_hen_suryo,
        anbun_amount_tax110_ex::double AS anbun_amount_tax110_ex,
        z_item_amount_tax_ex::double AS z_item_amount_tax_ex,
        ratio2::numeric(16,8) AS ratio2,
        anbun_soryo::double AS anbun_soryo,
        anbun_point_tax_ex::double AS anbun_point_tax_ex,
        anbun_tokuten::double AS anbun_tokuten,
        gts::double AS gts,
        gts_qty::double AS gts_qty,
        ciw_discount::double AS ciw_discount,
        ciw_point::double AS ciw_point,
        ciw_return::double AS ciw_return,
        ciw_return_qty::double AS ciw_return_qty,
        nts::double AS nts,
        teikikeiyaku::VARCHAR(20) AS teikikeiyaku,
        f::numeric(38,18) AS f,
        meisainukikingaku::numeric(18,0) AS meisainukikingaku,
        warimaenukikingaku::numeric(18,0) AS warimaenukikingaku,
        soryo::numeric(18,0) AS soryo,
        point::numeric(18,0) AS point,
        discount::numeric(18,0) AS discount,
        h_o_suryo::numeric(18,0) AS h_o_suryo,
        hensu::numeric(18,0) AS hensu,
        y_order_f::numeric(18,0) AS y_order_f,
        y_ship_f::numeric(18,0) AS y_ship_f,
        h_koseritsu::numeric(16,8) AS h_koseritsu,
        z_koseritsu::numeric(16,8) AS z_koseritsu,
        h_bun_suryo::numeric(18,0) AS h_bun_suryo,
        z_bun_suryo::numeric(18,0) AS z_bun_suryo,
        c_diregularcontractid::NUMBER AS c_diregularcontractid,
        smkeiroid::numeric(18,0) AS smkeiroid,
        uketsuketelcompanycd::VARCHAR(8) AS uketsuketelcompanycd,
        diordercode::VARCHAR(16) AS diordercode,
        kesaiid::VARCHAR(62) AS kesaiid,
        diorderid::numeric(18,0) AS diorderid,
        new_discount::double AS new_discount,
        ciw_discount_notax::double AS ciw_discount_notax,
        sub_cnt::numeric(18,0) AS sub_cnt,
        inserted_date::timestamp without time zone AS inserted_date,
        inserted_by::VARCHAR(100) AS inserted_by,
        updated_date::timestamp without time zone AS updated_date,
        updated_by::VARCHAR(100)  AS updated_by
    FROM dm_kesai_mart_dly_general
    )
SELECT *
FROM final
