
with sdl_mds_th_product_master as (
select * from dev_dna_load.snaposesdl_raw.sdl_mds_th_product_master
),
transformed as (
select
  trim(code) as item_cd,
  trim(name) as name1,
  trim(name2) as name2,
  trim(defstkunitcode_code) as defstk_unt_cd,
  null as prod_grp_id,
  trim(groupcode) as grp_cd,
  trim(typecode) as typ_cd,
  trim(cateorycode) as catgry_cd,
  trim(brandcode) as brnd_cd,
  trim(formatcode) as format_cd,
  trim(barcode) as barcd,
  cast(trim(saleprice1) as decimal(19, 6)) as sls_prc1,
  cast(trim(saleprice2) as decimal(19, 6)) as sls_prc2,
  cast(trim(saleprice3) as decimal(19, 6)) as sls_prc3,
  cast(trim(saleprice4) as decimal(19, 6)) as sls_prc4,
  cast(trim(taxtype) as int) as tax_typ,
  cast(trim(formqty) as decimal(19, 6)) as from_qty,
  cast(trim(toqty) as decimal(19, 6)) as to_qty,
  trim(priceremark) as prc_remark,
  trim(colorcode) as color_cd,
  trim(mygrade_code) as mygrade,
  trim(myclass_code) as myclass,
  cast(trim(unittype) as int) as unit_typ,
  cast(trim(costtype) as int) as cost_typ,
  cast(trim(stocktype) as int) as stock_typ,
  trim(defsaleunitcode_code) as def_sls_unt_cd,
  trim(defbuyunitcode_code) as def_buy_unt_cd,
  cast(trim(mysize) as varchar) as mysize,
  cast(trim(replace(weight, '', null)) as decimal(19, 6)) as weight,
  cast(trim(exceptax) as int) as exceptax,
  trim(mydescription) as mydesc,
  cast(trim(activestatus_code) as int) as actv_status,
  cast(trim(barcodeactivestatus) as int) as barcd_actv_status,
  trim(barcoderemark) as barcd_remark,
  cast(trim(replace(canmakepo, '', null)) as int) as canmakepo,
  cast(trim(buyprice1) as decimal(19, 6)) as buy_prc1,
  cast(trim(buyprice2) as decimal(19, 6)) as buy_prc2,
  cast(trim(buyprice3) as decimal(19, 6)) as buy_prc3,
  cast(trim(buyprice4) as decimal(19, 6)) as buy_prc4,
  cast(trim(transporttime) as int) as trnsprt_tm,
  trim(vendercode) as vend_cd,
  trim(defsalewhcode) as def_sls_wh_cd,
  trim(defbuywhcode) as def_buy_wh_cd,
  trim(defsaleshelf) as def_sls_shelf,
  trim(defbuyshelf) as def_buy_shelf,
  null as cost_level1,
  null as cost_level2,
  null as cost_level3,
  null as cost_level4,
  trim(unit1_code) as uom,
  cast(trim(unit3r1) as decimal) as unit_per_case,
  null as isexception,
  null as isforvmr,
  null as th_shrt_nm,
  trim(name2) as en_shrt_nm,
  null as crt_dt,
  null as updt_dt,
  trim(is_hero) as is_hero,
  to_char(cast(current_timestamp() as timestampntz), 'YYYYMMDDHH24MISSFF3') as cdl_dttm,
  current_timestamp() as curr_date,
  current_timestamp() as updt_dttm,
  trim(parentcode) as parentcode
from sdl_mds_th_product_master
where
  upper(exceptionflag) = 'N'),
final as (
    select
    item_cd::varchar(50) as item_cd,
    name1::varchar(500) as name1,
    name2::varchar(500) as name2,
    defstk_unt_cd::varchar(10) as defstk_unt_cd,
    prod_grp_id::varchar(10) as prod_grp_id,
    grp_cd::varchar(10) as grp_cd,
    typ_cd::varchar(10) as typ_cd,
    catgry_cd::varchar(10) as catgry_cd,
    brnd_cd::varchar(10) as brnd_cd,
    format_cd::varchar(10) as format_cd,
    barcd::varchar(20) as barcd,
    sls_prc1::number(19,6) as sls_prc1,
    sls_prc2::number(19,6) as sls_prc2,
    sls_prc3::number(19,6) as sls_prc3,
    sls_prc4::number(19,6) as sls_prc4,
    tax_typ::number(18,0) as tax_typ,
    from_qty::number(19,6) as from_qty,
    to_qty::number(19,6) as to_qty,
    prc_remark::varchar(100) as prc_remark,
    color_cd::varchar(100) as color_cd,
    mygrade::varchar(40) as mygrade,
    myclass::varchar(20) as myclass,
    unit_typ::number(18,0) as unit_typ,
    cost_typ::number(18,0) as cost_typ,
    stock_typ::number(18,0) as stock_typ,
    def_sls_unt_cd::varchar(10) as def_sls_unt_cd,
    def_buy_unt_cd::varchar(10) as def_buy_unt_cd,
    mysize::varchar(40) as mysize,
    weight::number(19,6) as weight,
    exceptax::number(18,0) as exceptax,
    mydesc::varchar(255) as mydesc,
    actv_status::number(18,0) as actv_status,
    barcd_actv_status::number(18,0) as barcd_actv_status,
    barcd_remark::varchar(400) as barcd_remark,
    canmakepo::number(18,0) as canmakepo,
    buy_prc1::number(19,6) as buy_prc1,
    buy_prc2::number(19,6) as buy_prc2,
    buy_prc3::number(19,6) as buy_prc3,
    buy_prc4::number(19,6) as buy_prc4,
    trnsprt_tm::number(18,0) as trnsprt_tm,
    vend_cd::varchar(10) as vend_cd,
    def_sls_wh_cd::varchar(10) as def_sls_wh_cd,
    def_buy_wh_cd::varchar(10) as def_buy_wh_cd,
    def_sls_shelf::varchar(10) as def_sls_shelf,
    def_buy_shelf::varchar(10) as def_buy_shelf,
    cost_level1::number(19,6) as cost_level1,
    cost_level2::number(19,6) as cost_level2,
    cost_level3::number(19,6) as cost_level3,
    cost_level4::number(19,6) as cost_level4,
    uom::varchar(10) as uom,
    unit_per_case::number(18,0) as unit_per_case,
    isexception::varchar(1) as isexception,
    isforvmr::number(18,0) as isforvmr,
    th_shrt_nm::varchar(200) as th_shrt_nm,
    en_shrt_nm::varchar(200) as en_shrt_nm,
    crt_dt::timestamp_ntz(9) as crt_dt,
    updt_dt::timestamp_ntz(9) as updt_dt,
    is_hero::varchar(1) as is_hero,
    cdl_dttm::varchar(255) as cdl_dttm,
    curr_date::timestamp_ntz(9) as crtd_dttm,
    updt_dttm::timestamp_ntz(9) as updt_dttm,
    parentcode::varchar(600) as parentcode
    from transformed
)
  
select * from final