--import cte

with wks_ph_rpt_retail_excellence_sop as 
(
    select * from {{ ref('phlwks_integration__wks_ph_rpt_retail_excellence_sop' )}}
),
wks_ph_re_target_compliance as 
(
    select * from {{ ref('phlwks_integration__wks_ph_re_target_compliance' )}}
),

--final cte

edw_ph_rpt_retail_excellence as 
(
    SELECT FISC_YR,
        FISC_PER,
        "cluster",
        MARKET,
        DATA_SRC,
        UPPER(CHANNEL_NAME) AS CHANNEL_NAME,
        SOLD_TO_CODE,
        UPPER(DISTRIBUTOR_CODE) AS DISTRIBUTOR_CODE,
        DISTRIBUTOR_NAME,
        SELL_OUT_CHANNEL,
        STORE_TYPE,
        PRIORITIZATION_SEGMENTATION,
        STORE_CATEGORY,
        STORE_CODE,
        STORE_NAME,
        STORE_GRADE,
        STORE_SIZE,
        REGION,
        ZONE_NAME,
        POST_CODE,
        CITY,
        RTRLATITUDE,
        RTRLONGITUDE,
        CUSTOMER_SEGMENT_KEY,
        CUSTOMER_SEGMENT_DESCRIPTION,
        RETAIL_ENVIRONMENT,
        SAP_CUSTOMER_CHANNEL_KEY,
        SAP_CUSTOMER_CHANNEL_DESCRIPTION,
        SAP_CUSTOMER_SUB_CHANNEL_KEY,
        SAP_SUB_CHANNEL_DESCRIPTION,
        SAP_PARENT_CUSTOMER_KEY,
        SAP_PARENT_CUSTOMER_DESCRIPTION,
        SAP_BANNER_KEY,
        SAP_BANNER_DESCRIPTION,
        SAP_BANNER_FORMAT_KEY,
        SAP_BANNER_FORMAT_DESCRIPTION,
        CUSTOMER_NAME,
        CUSTOMER_CODE,
        PRODUCT_CODE,
        PRODUCT_NAME,
        PROD_HIER_L1,
        PROD_HIER_L2,
        PROD_HIER_L3,
        PROD_HIER_L4,
        PROD_HIER_L5,
        PROD_HIER_L6,
        PROD_HIER_L7,
        PROD_HIER_L8,
        PROD_HIER_L9,
        MAPPED_SKU_CD,
        SAP_PROD_SGMT_CD,
        SAP_PROD_SGMT_DESC,
        SAP_BASE_PROD_DESC,
        SAP_MEGA_BRND_DESC,
        SAP_BRND_DESC,
        SAP_VRNT_DESC,
        SAP_PUT_UP_DESC,
        SAP_GRP_FRNCHSE_CD,
        SAP_GRP_FRNCHSE_DESC,
        SAP_FRNCHSE_CD,
        SAP_FRNCHSE_DESC,
        SAP_PROD_FRNCHSE_CD,
        SAP_PROD_FRNCHSE_DESC,
        SAP_PROD_MJR_CD,
        SAP_PROD_MJR_DESC,
        SAP_PROD_MNR_CD,
        SAP_PROD_MNR_DESC,
        SAP_PROD_HIER_CD,
        SAP_PROD_HIER_DESC,
        PKA_FRANCHISE_DESC,
        PKA_BRAND_DESC,
        PKA_SUB_BRAND_DESC,
        PKA_VARIANT_DESC,
        PKA_SUB_VARIANT_DESC,
        GLOBAL_PRODUCT_FRANCHISE,
        GLOBAL_PRODUCT_BRAND,
        GLOBAL_PRODUCT_SUB_BRAND,
        GLOBAL_PRODUCT_VARIANT,
        GLOBAL_PRODUCT_SEGMENT,
        GLOBAL_PRODUCT_SUBSEGMENT,
        GLOBAL_PRODUCT_CATEGORY,
        GLOBAL_PRODUCT_SUBCATEGORY,
        GLOBAL_PUT_UP_DESCRIPTION,
        EAN,
        SKU_CODE,
        SKU_DESCRIPTION,
        PKA_PRODUCT_KEY,
        PKA_PRODUCT_KEY_DESCRIPTION,
        SALES_VALUE,
        SALES_QTY,
        AVG_SALES_QTY,
        SALES_VALUE_LIST_PRICE,
        LM_SALES,
        LM_SALES_QTY,
        LM_AVG_SALES_QTY,
        LM_SALES_LP,
        P3M_SALES,
        P3M_QTY,
        P3M_AVG_QTY,
        P3M_SALES_LP,
        P6M_SALES,
        P6M_QTY,
        P6M_AVG_QTY,
        P6M_SALES_LP,
        P12M_SALES,
        P12M_QTY,
        P12M_AVG_QTY,
        P12M_SALES_LP,
        F3M_SALES,
        F3M_QTY,
        F3M_AVG_QTY,
        LM_SALES_FLAG,
        P3M_SALES_FLAG,
        P6M_SALES_FLAG,
        P12M_SALES_FLAG,
        MDP_FLAG,
        --TARGET_COMPLAINCE,
        CASE 
            WHEN (MDP_FLAG = 'Y' AND UPPER(SOP.global_product_brand) = UPPER(TRGT_CMP.global_product_brand)) THEN TRGT_CMP.TARGET_COMPLAINCE
            ELSE 100
            END AS TARGET_COMPLAINCE,
        LIST_PRICE,
        TOTAL_SALES_LM,
        TOTAL_SALES_P3M,
        TOTAL_SALES_P6M,
        TOTAL_SALES_P12M,
        TOTAL_SALES_BY_STORE_LM,
        TOTAL_SALES_BY_STORE_P3M,
        TOTAL_SALES_BY_STORE_P6M,
        TOTAL_SALES_BY_STORE_P12M,
        TOTAL_SALES_BY_SKU_LM,
        TOTAL_SALES_BY_SKU_P3M,
        TOTAL_SALES_BY_SKU_P6M,
        TOTAL_SALES_BY_SKU_P12M,
        STORE_CONTRIBUTION_LM,
        SKU_CONTRIBUTION_LM,
        SIZE_OF_PRICE_LM,
        STORE_CONTRIBUTION_P3M,
        SKU_CONTRIBUTION_P3M,
        SIZE_OF_PRICE_P3M,
        STORE_CONTRIBUTION_P6M,
        SKU_CONTRIBUTION_P6M,
        SIZE_OF_PRICE_P6M,
        STORE_CONTRIBUTION_P12M,
        SKU_CONTRIBUTION_P12M,
        SIZE_OF_PRICE_P12M,
        TOTAL_SALES_LM_LP,
        TOTAL_SALES_P3M_LP,
        TOTAL_SALES_P6M_LP,
        TOTAL_SALES_P12M_LP,
        TOTAL_SALES_BY_STORE_LM_LP,
        TOTAL_SALES_BY_STORE_P3M_LP,
        TOTAL_SALES_BY_STORE_P6M_LP,
        TOTAL_SALES_BY_STORE_P12M_LP,
        TOTAL_SALES_BY_SKU_LM_LP,
        TOTAL_SALES_BY_SKU_P3M_LP,
        TOTAL_SALES_BY_SKU_P6M_LP,
        TOTAL_SALES_BY_SKU_P12M_LP,
        STORE_CONTRIBUTION_LM_LP,
        SKU_CONTRIBUTION_LM_LP,
        SIZE_OF_PRICE_LM_LP,
        STORE_CONTRIBUTION_P3M_LP,
        SKU_CONTRIBUTION_P3M_LP,
        SIZE_OF_PRICE_P3M_LP,
        STORE_CONTRIBUTION_P6M_LP,
        SKU_CONTRIBUTION_P6M_LP,
        SIZE_OF_PRICE_P6M_LP,
        STORE_CONTRIBUTION_P12M_LP,
        SKU_CONTRIBUTION_P12M_LP,
        SIZE_OF_PRICE_P12M_LP,
        COUNT(LM_SALES_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,LM_SALES_FLAG,MDP_FLAG) AS lM_SALES_FLAG_COUNT,
        COUNT(P3M_SALES_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,P3M_SALES_FLAG,MDP_FLAG) AS P3M_SALES_FLAG_COUNT,
        COUNT(P6M_SALES_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,P6M_SALES_FLAG,MDP_FLAG) AS P6M_SALES_FLAG_COUNT,
        COUNT(P12M_SALES_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,P12M_SALES_FLAG,MDP_FLAG) AS P12M_SALES_FLAG_COUNT,
        COUNT(MDP_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,MDP_FLAG) AS MDP_FLAG_COUNT,
        SYSDATE() AS CRTD_DTTM
    FROM WKS_PH_RPT_RETAIL_EXCELLENCE_SOP SOP
    LEFT JOIN wks_ph_re_target_compliance TRGT_CMP on (SOP.fisc_per=TRGT_CMP.fisc_per and UPPER(SOP.global_product_brand)=UPPER(TRGT_CMP.global_product_brand))
),

final as 
(
    select fisc_yr :: numeric(18,0) as fisc_yr,
    fisc_per :: numeric(18,0) as fisc_per,
    "cluster" :: varchar(100) as "cluster",
    market :: varchar(30) as market,
    data_src :: varchar(14) as data_src,
    channel_name :: varchar(382) as channel_name,
    sold_to_code :: varchar(255) as sold_to_code,
    distributor_code :: varchar(150) as distributor_code,
    distributor_name :: varchar(356) as distributor_name,
    sell_out_channel :: varchar(382) as sell_out_channel,
    store_type :: varchar(255) as store_type,
    prioritization_segmentation :: varchar(13) as prioritization_segmentation,
    store_category :: varchar(13) as store_category,
    store_code :: varchar(100) as store_code,
    store_name :: varchar(601) as store_name,
    store_grade :: varchar(13) as store_grade,
    store_size :: varchar(13) as store_size,
    region :: varchar(255) as region,
    zone_name :: varchar(255) as zone_name,
    post_code :: varchar(100) as post_code,
    city :: varchar(255) as city,
    rtrlatitude :: varchar(13) as rtrlatitude,
    rtrlongitude :: varchar(13) as rtrlongitude,
    customer_segment_key :: varchar(12) as customer_segment_key,
    customer_segment_description :: varchar(50) as customer_segment_description,
    retail_environment :: varchar(382) as retail_environment,
    sap_customer_channel_key :: varchar(12) as sap_customer_channel_key,
    sap_customer_channel_description :: varchar(112) as sap_customer_channel_description,
    sap_customer_sub_channel_key :: varchar(12) as sap_customer_sub_channel_key,
    sap_sub_channel_description :: varchar(112) as sap_sub_channel_description,
    sap_parent_customer_key :: varchar(12) as sap_parent_customer_key,
    sap_parent_customer_description :: varchar(112) as sap_parent_customer_description,
    sap_banner_key :: varchar(12) as sap_banner_key,
    sap_banner_description :: varchar(112) as sap_banner_description,
    sap_banner_format_key :: varchar(12) as sap_banner_format_key,
    sap_banner_format_description :: varchar(112) as sap_banner_format_description,
    customer_name :: varchar(100) as customer_name,
    customer_code :: varchar(10) as customer_code,
    product_code :: varchar(200) as product_code,
    product_name :: varchar(300) as product_name,
    prod_hier_l1 :: varchar(11) as prod_hier_l1,
    prod_hier_l2 :: varchar(1) as prod_hier_l2,
    prod_hier_l3 :: varchar(255) as prod_hier_l3,
    prod_hier_l4 :: varchar(255) as prod_hier_l4,
    prod_hier_l5 :: varchar(255) as prod_hier_l5,
    prod_hier_l6 :: varchar(255) as prod_hier_l6,
    prod_hier_l7 :: varchar(1) as prod_hier_l7,
    prod_hier_l8 :: varchar(1) as prod_hier_l8,
    prod_hier_l9 :: varchar(1) as prod_hier_l9,
    mapped_sku_cd :: varchar(40) as mapped_sku_cd,
    sap_prod_sgmt_cd :: varchar(18) as sap_prod_sgmt_cd,
    sap_prod_sgmt_desc :: varchar(100) as sap_prod_sgmt_desc,
    sap_base_prod_desc :: varchar(100) as sap_base_prod_desc,
    sap_mega_brnd_desc :: varchar(100) as sap_mega_brnd_desc,
    sap_brnd_desc :: varchar(100) as sap_brnd_desc,
    sap_vrnt_desc :: varchar(100) as sap_vrnt_desc,
    sap_put_up_desc :: varchar(100) as sap_put_up_desc,
    sap_grp_frnchse_cd :: varchar(18) as sap_grp_frnchse_cd,
    sap_grp_frnchse_desc :: varchar(100) as sap_grp_frnchse_desc,
    sap_frnchse_cd :: varchar(18) as sap_frnchse_cd,
    sap_frnchse_desc :: varchar(100) as sap_frnchse_desc,
    sap_prod_frnchse_cd :: varchar(18) as sap_prod_frnchse_cd,
    sap_prod_frnchse_desc :: varchar(100) as sap_prod_frnchse_desc,
    sap_prod_mjr_cd :: varchar(18) as sap_prod_mjr_cd,
    sap_prod_mjr_desc :: varchar(100) as sap_prod_mjr_desc,
    sap_prod_mnr_cd :: varchar(18) as sap_prod_mnr_cd,
    sap_prod_mnr_desc :: varchar(100) as sap_prod_mnr_desc,
    sap_prod_hier_cd :: varchar(18) as sap_prod_hier_cd,
    sap_prod_hier_desc :: varchar(100) as sap_prod_hier_desc,
    pka_franchise_desc :: varchar(30) as pka_franchise_desc,
    pka_brand_desc :: varchar(30) as pka_brand_desc,
    pka_sub_brand_desc :: varchar(30) as pka_sub_brand_desc,
    pka_variant_desc :: varchar(30) as pka_variant_desc,
    pka_sub_variant_desc :: varchar(30) as pka_sub_variant_desc,
    global_product_franchise :: varchar(30) as global_product_franchise,
    global_product_brand :: varchar(30) as global_product_brand,
    global_product_sub_brand :: varchar(100) as global_product_sub_brand,
    global_product_variant :: varchar(100) as global_product_variant,
    global_product_segment :: varchar(50) as global_product_segment,
    global_product_subsegment :: varchar(100) as global_product_subsegment,
    global_product_category :: varchar(50) as global_product_category,
    global_product_subcategory :: varchar(50) as global_product_subcategory,
    global_put_up_description :: varchar(100) as global_put_up_description,
    ean :: varchar(40) as ean,
    sku_code :: varchar(40) as sku_code,
    sku_description :: varchar(150) as sku_description,
    pka_product_key :: varchar(68) as pka_product_key,
    pka_product_key_description :: varchar(255) as pka_product_key_description,
    sales_value :: numeric(38,6) as sales_value,
    sales_qty :: numeric(38,6) as sales_qty,
    avg_sales_qty :: numeric(38,6) as avg_sales_qty,
    sales_value_list_price :: numeric(38,12) as sales_value_list_price,
    lm_sales :: numeric(38,6) as lm_sales,
    lm_sales_qty :: numeric(38,6) as lm_sales_qty,
    lm_avg_sales_qty :: numeric(38,6) as lm_avg_sales_qty,
    lm_sales_lp :: numeric(38,12) as lm_sales_lp,
    p3m_sales :: numeric(38,6) as p3m_sales,
    p3m_qty :: numeric(38,6) as p3m_qty,
    p3m_avg_qty :: numeric(38,6) as p3m_avg_qty,
    p3m_sales_lp :: numeric(38,12) as p3m_sales_lp,
    p6m_sales :: numeric(38,6) as p6m_sales,
    p6m_qty :: numeric(38,6) as p6m_qty,
    p6m_avg_qty :: numeric(38,6) as p6m_avg_qty,
    p6m_sales_lp :: numeric(38,12) as p6m_sales_lp,
    p12m_sales :: numeric(38,6) as p12m_sales,
    p12m_qty :: numeric(38,6) as p12m_qty,
    p12m_avg_qty :: numeric(38,6) as p12m_avg_qty,
    p12m_sales_lp :: numeric(38,12) as p12m_sales_lp,
    f3m_sales :: numeric(38,6) as f3m_sales,
    f3m_qty :: numeric(38,6) as f3m_qty,
    f3m_avg_qty :: numeric(38,6) as f3m_avg_qty,
    lm_sales_flag :: varchar(1) as lm_sales_flag,
    p3m_sales_flag :: varchar(1) as p3m_sales_flag,
    p6m_sales_flag :: varchar(1) as p6m_sales_flag,
    p12m_sales_flag :: varchar(1) as p12m_sales_flag,
    mdp_flag :: varchar(1) as mdp_flag,
    target_complaince :: numeric(18,0) as target_complaince,
    list_price :: numeric(20,4) as list_price,
    total_sales_lm :: numeric(38,6) as total_sales_lm,
    total_sales_p3m :: numeric(38,6) as total_sales_p3m,
    total_sales_p6m :: numeric(38,6) as total_sales_p6m,
    total_sales_p12m :: numeric(38,6) as total_sales_p12m,
    total_sales_by_store_lm :: numeric(38,6) as total_sales_by_store_lm,
    total_sales_by_store_p3m :: numeric(38,6) as total_sales_by_store_p3m,
    total_sales_by_store_p6m :: numeric(38,6) as total_sales_by_store_p6m,
    total_sales_by_store_p12m :: numeric(38,6) as total_sales_by_store_p12m,
    total_sales_by_sku_lm :: numeric(38,6) as total_sales_by_sku_lm,
    total_sales_by_sku_p3m :: numeric(38,6) as total_sales_by_sku_p3m,
    total_sales_by_sku_p6m :: numeric(38,6) as total_sales_by_sku_p6m,
    total_sales_by_sku_p12m :: numeric(38,6) as total_sales_by_sku_p12m,
    store_contribution_lm :: numeric(38,4) as store_contribution_lm,
    sku_contribution_lm :: numeric(38,4) as sku_contribution_lm,
    size_of_price_lm :: numeric(38,14) as size_of_price_lm,
    store_contribution_p3m :: numeric(38,4) as store_contribution_p3m,
    sku_contribution_p3m :: numeric(38,4) as sku_contribution_p3m,
    size_of_price_p3m :: numeric(38,14) as size_of_price_p3m,
    store_contribution_p6m :: numeric(38,4) as store_contribution_p6m,
    sku_contribution_p6m :: numeric(38,4) as sku_contribution_p6m,
    size_of_price_p6m :: numeric(38,14) as size_of_price_p6m,
    store_contribution_p12m :: numeric(38,4) as store_contribution_p12m,
    sku_contribution_p12m :: numeric(38,4) as sku_contribution_p12m,
    size_of_price_p12m :: numeric(38,14) as size_of_price_p12m,
    total_sales_lm_lp :: numeric(38,12) as total_sales_lm_lp,
    total_sales_p3m_lp :: numeric(38,12) as total_sales_p3m_lp,
    total_sales_p6m_lp :: numeric(38,12) as total_sales_p6m_lp,
    total_sales_p12m_lp :: numeric(38,12) as total_sales_p12m_lp,
    total_sales_by_store_lm_lp :: numeric(38,12) as total_sales_by_store_lm_lp,
    total_sales_by_store_p3m_lp :: numeric(38,12) as total_sales_by_store_p3m_lp,
    total_sales_by_store_p6m_lp :: numeric(38,12) as total_sales_by_store_p6m_lp,
    total_sales_by_store_p12m_lp :: numeric(38,12) as total_sales_by_store_p12m_lp,
    total_sales_by_sku_lm_lp :: numeric(38,12) as total_sales_by_sku_lm_lp,
    total_sales_by_sku_p3m_lp :: numeric(38,12) as total_sales_by_sku_p3m_lp,
    total_sales_by_sku_p6m_lp :: numeric(38,12) as total_sales_by_sku_p6m_lp,
    total_sales_by_sku_p12m_lp :: numeric(38,12) as total_sales_by_sku_p12m_lp,
    store_contribution_lm_lp :: numeric(38,4) as store_contribution_lm_lp,
    sku_contribution_lm_lp :: numeric(38,4) as sku_contribution_lm_lp,
    size_of_price_lm_lp :: numeric(38,20) as size_of_price_lm_lp,
    store_contribution_p3m_lp :: numeric(38,4) as store_contribution_p3m_lp,
    sku_contribution_p3m_lp :: numeric(38,4) as sku_contribution_p3m_lp,
    size_of_price_p3m_lp :: numeric(38,20) as size_of_price_p3m_lp,
    store_contribution_p6m_lp :: numeric(38,4) as store_contribution_p6m_lp,
    sku_contribution_p6m_lp :: numeric(38,4) as sku_contribution_p6m_lp,
    size_of_price_p6m_lp :: numeric(38,20) as size_of_price_p6m_lp,
    store_contribution_p12m_lp :: numeric(38,4) as store_contribution_p12m_lp,
    sku_contribution_p12m_lp :: numeric(38,4) as sku_contribution_p12m_lp,
    size_of_price_p12m_lp :: numeric(38,20) as size_of_price_p12m_lp,
    lm_sales_flag_count :: numeric(38,0) as lm_sales_flag_count,
    p3m_sales_flag_count :: numeric(38,0) as p3m_sales_flag_count,
    p6m_sales_flag_count :: numeric(38,0) as p6m_sales_flag_count,
    p12m_sales_flag_count :: numeric(38,0) as p12m_sales_flag_count,
    mdp_flag_count :: numeric(38,0) as mdp_flag_count,
    crtd_dttm :: timestamp without time zone as crtd_dttm
    from edw_ph_rpt_retail_excellence
)

--final select

select * from final 
