with wks_mi_psr_perf_tracker as
(
    select * from {{ ref('indwks_integration__wks_mi_psr_perf_tracker') }}
),
final as
(
    SELECT year,
       month,
       qtr,
       rtruniquecode_rt_dim,
       customer_code_rt_dim,
       retailer_code_rt_dim,
       smcode_rt_dim,
       smname_rt_dim,
       uniquesalescode_rt_dim,
       region_name_rt_dim,
       zone_name_rt_dim,
       territory_name_rt_dim,
       Channel_Name,
       achievement_amt_sales_cube,
       rtruniquecode_sales_cube,
       retailer_code_sales_cube,
       latest_customer_code,
       latest_customer_name,
       latest_salesman_code,
       latest_salesman_name,
       latest_uniquesalescode,
       rtruniquecode_RT_cube,
       subd_retailer_code,
       Total_Number_of_bills,
       No_of_Packs,
       achievement_amt_RT_CUBE,
       total_outlets_subd_dim,
       total_outlets_cust_subd_dim,
       os_flag,
       convert_timezone('UTC',current_timestamp()) as crt_dttm,
       convert_timezone('UTC',current_timestamp()) as updt_dttm
       from wks_mi_psr_perf_tracker
)
select year::varchar(200) as year,
month::varchar(200) as month,
qtr::varchar(200) as qtr,
rtruniquecode_rt_dim::varchar(200) as rtruniquecode_rt_dim,
customer_code_rt_dim::varchar(200) as customer_code_rt_dim,
retailer_code_rt_dim::varchar(200) as retailer_code_rt_dim,
smcode_rt_dim::varchar(200) as smcode_rt_dim,
smname_rt_dim::varchar(200) as smname_rt_dim,
uniquesalescode_rt_dim::varchar(200) as uniquesalescode_rt_dim,
region_name_rt_dim::varchar(200) as region_name_rt_dim,
zone_name_rt_dim::varchar(200) as zone_name_rt_dim,
territory_name_rt_dim::varchar(200) as territory_name_rt_dim,
channel_name::varchar(200) as channel_name,
achievement_amt_sales_cube::varchar(200) as achievement_amt_sales_cube,
rtruniquecode_sales_cube::varchar(200) as rtruniquecode_sales_cube,
retailer_code_sales_cube::varchar(200) as retailer_code_sales_cube,
latest_customer_code::varchar(200) as latest_customer_code,
latest_customer_name::varchar(200) as latest_customer_name,
latest_salesman_code::varchar(200) as latest_salesman_code,
latest_salesman_name::varchar(200) as latest_salesman_name,
latest_uniquesalescode::varchar(200) as latest_uniquesalescode,
rtruniquecode_rt_cube::varchar(200) as rtruniquecode_rt_cube,
subd_retailer_code::varchar(200) as subd_retailer_code,
total_number_of_bills::varchar(200) as total_number_of_bills,
no_of_packs::varchar(200) as no_of_packs,
achievement_amt_rt_cube::varchar(200) as achievement_amt_rt_cube,
total_outlets_subd_dim::varchar(200) as total_outlets_subd_dim,
total_outlets_cust_subd_dim::varchar(200) as total_outlets_cust_subd_dim,
os_flag::varchar(200) as os_flag,
crt_dttm::timestamp_ntz(9) as crt_dttm,
updt_dttm::timestamp_ntz(9) as updt_dttm
from final