{{
    config
    (
        pre_hook="{{build_itg_mds_ph_pos_customers()}}"
    )
}}
with sdl_mds_ph_pos_customers as (
    select * from {{ source('phlsdl_raw', 'sdl_mds_ph_pos_customers') }}
),

wks as (
    select
        code,
        cust_cd,
        brnch_cd,
        brnch_nm,
        prov_cd,
        prov_nm,
        region_cd,
        region_nm,
        mncplty_cd,
        mncplty_nm,
        city_cd,
        city_nm,
        chnl_sub_grp_cd,
        pms_nm,
        ash_no,
        ash_nm,
        address1,
        address2,
        jj_chnl_cd,
        tsr,
        pmr,
        chnl,
        area_cd,
        area_nm,
        region_nm2,
        wsman,
        route,
        status,
        operating_hrs,
        da_tag,
        dizr_tag,
        brnch_grp1,
        brnch_grp2,
        outlet_typ,
        store_typ_cd,
        store_typ_desc,
        prov_cd2,
        data_compln_status,
        ae_nm,
        dt_opnd,
        store_tin_no,
        store_size_cd,
        store_size,
        store_mtrx_cd,
        store_mtrx,
        class,
        store_clsfn,
        jj_sold_to,
        jj_ship_to,
        bp,
        sales_grp,
        dsm,
        sales_man_tag,
        branch_no,
        mdc_tag,
        derived_branchno,
        last_chg_datetime,
        effective_from,
        case
            when
                to_date(effective_to) = '9999-12-31'
                then dateadd(day, -1, current_timestamp)
            else effective_to
        end as effective_to,
        'N' as active,
        crtd_dttm,
        current_timestamp as updt_dttm,
        zip_code,
        zip_cd_name,
        barangay_code,
        barangay_cd_name,
        long_lat_source,
        latitude,
        longitude
    from
        (
            select itg.*
            from {{ this }} AS itg,
                sdl_mds_ph_pos_customers AS sdl
            where
                sdl.lastchgdatetime != itg.last_chg_datetime
                and sdl.brnch_cd = itg.brnch_cd
                and sdl.prefix = itg.cust_cd
        )
    union all
    select
        code,
        prefix as cust_cd,
        brnch_cd,
        brnch_nm,
        prov_cd_code as prov_cd,
        prov_cd_name as prov_nm,
        region_cd_code as region_cd,
        region_cd_name as region_nm,
        mncplty_cd_code as mncplty_cd,
        mncplty_cd_name as mncplty_nm,
        city_cd,
        city_nm,
        chnl_sub_grp_cd,
        pms_nm,
        ash_no,
        ash_nm,
        address1,
        address2,
        jj_chnl_cd,
        tsr,
        pmr,
        chnl,
        area_cd,
        area_nm,
        region_nm as region_nm2,
        wsman,
        route,
        status,
        operating_hrs,
        da_tag,
        dizr_tag,
        brnch_grp1,
        brnch_grp2,
        outlet_typ,
        store_typ_cd,
        store_typ_desc,
        prov_cd2,
        data_compln_status,
        ae_nm,
        dt_opnd,
        store_tin_no,
        store_size_cd,
        store_size,
        store_mtrx_cd,
        store_mtrx,
        class,
        store_clsfn,
        jj_sold_to,
        jj_ship_to,
        bp,
        sales_grp,
        dsm,
        salesmantag as sales_man_tag,
        branchno as branch_no,
        mdctag as mdc_tag,
        derived_branchno,
        lastchgdatetime as last_chg_datetime,
        current_timestamp as effective_from,
        '9999-12-31' as effective_to,
        'Y' as active,
        current_timestamp as crtd_dttm,
        current_timestamp as updt_dttm,
        trim(zipcode_code) as zip_code,
        trim(zipcode_name) as zip_cd_name,
        trim(barangaycode_code) as barangay_code,
        trim(barangaycode_name) as barangay_cd_name,
        longlatsource as long_lat_source,
        latitude,
        longitude
    from
        (
            select sdl.*
            from {{ this }} AS itg,
                sdl_mds_ph_pos_customers AS sdl
            where
                sdl.lastchgdatetime != itg.last_chg_datetime
                and sdl.brnch_cd = itg.brnch_cd
                and sdl.prefix = itg.cust_cd
                and itg.active = 'Y'
        )
    union all
    select
        code,
        prefix as cust_cd,
        brnch_cd,
        brnch_nm,
        prov_cd_code as prov_cd,
        prov_cd_name as prov_nm,
        region_cd_code as region_cd,
        region_cd_name as region_nm,
        mncplty_cd_code as mncplty_cd,
        mncplty_cd_name as mncplty_nm,
        city_cd,
        city_nm,
        chnl_sub_grp_cd,
        pms_nm,
        ash_no,
        ash_nm,
        address1,
        address2,
        jj_chnl_cd,
        tsr,
        pmr,
        chnl,
        area_cd,
        area_nm,
        region_nm as region_nm2,
        wsman,
        route,
        status,
        operating_hrs,
        da_tag,
        dizr_tag,
        brnch_grp1,
        brnch_grp2,
        outlet_typ,
        store_typ_cd,
        store_typ_desc,
        prov_cd2,
        data_compln_status,
        ae_nm,
        dt_opnd,
        store_tin_no,
        store_size_cd,
        store_size,
        store_mtrx_cd,
        store_mtrx,
        class,
        store_clsfn,
        jj_sold_to,
        jj_ship_to,
        bp,
        sales_grp,
        dsm,
        salesmantag as sales_man_tag,
        branchno as branch_no,
        mdctag as mdc_tag,
        derived_branchno,
        lastchgdatetime as last_chg_datetime,
        effective_from,
        '9999-12-31' as effective_to,
        'Y' as active,
        current_timestamp as crtd_dttm,
        current_timestamp as updt_dttm,
        trim(zipcode_code) as zip_code,
        trim(zipcode_name) as zip_cd_name,
        trim(barangaycode_code) as barangay_code,
        trim(barangaycode_name) as barangay_cd_name,
        longlatsource as long_lat_source,
        latitude,
        longitude
    from
        (
            select
                sdl.*,
                itg.effective_from
            from {{ this }} AS itg,
                sdl_mds_ph_pos_customers AS sdl
            where
                sdl.lastchgdatetime = itg.last_chg_datetime
                and sdl.brnch_cd = itg.brnch_cd
                and sdl.prefix = itg.cust_cd
        )
    union all
    select
        code,
        prefix as cust_cd,
        brnch_cd,
        brnch_nm,
        prov_cd_code as prov_cd,
        prov_cd_name as prov_nm,
        region_cd_code as region_cd,
        region_cd_name as region_nm,
        mncplty_cd_code as mncplty_cd,
        mncplty_cd_name as mncplty_nm,
        city_cd,
        city_nm,
        chnl_sub_grp_cd,
        pms_nm,
        ash_no,
        ash_nm,
        address1,
        address2,
        jj_chnl_cd,
        tsr,
        pmr,
        chnl,
        area_cd,
        area_nm,
        region_nm as region_nm2,
        wsman,
        route,
        status,
        operating_hrs,
        da_tag,
        dizr_tag,
        brnch_grp1,
        brnch_grp2,
        outlet_typ,
        store_typ_cd,
        store_typ_desc,
        prov_cd2,
        data_compln_status,
        ae_nm,
        dt_opnd,
        store_tin_no,
        store_size_cd,
        store_size,
        store_mtrx_cd,
        store_mtrx,
        class,
        store_clsfn,
        jj_sold_to,
        jj_ship_to,
        bp,
        sales_grp,
        dsm,
        salesmantag as sales_man_tag,
        branchno as branch_no,
        mdctag as mdc_tag,
        derived_branchno,
        lastchgdatetime as last_chg_datetime,
        current_timestamp as effective_from,
        '9999-12-31' as effective_to,
        'Y' as active,
        current_timestamp as crtd_dttm,
        current_timestamp as updt_dttm,
        trim(zipcode_code) as zip_code,
        trim(zipcode_name) as zip_cd_name,
        trim(barangaycode_code) as barangay_code,
        trim(barangaycode_name) as barangay_cd_name,
        longlatsource as long_lat_source,
        latitude,
        longitude
    from
        (
            select *
            from sdl_mds_ph_pos_customers sdl 
            where prefix || brnch_cd not in (
                select distinct cust_cd || brnch_cd
                from {{ this }}
            )
        )
),

transformed as (
    select * from wks
    union all
    select * from {{ this }}
    where
        cust_cd || brnch_cd not in
        (
            select cust_cd || brnch_cd from wks
        )
),

final as (
    select
        code::varchar(50) as code,
        cust_cd::varchar(50) as cust_cd,
        brnch_cd::varchar(50) as brnch_cd,
        brnch_nm::varchar(255) as brnch_nm,
        prov_cd::varchar(50) as prov_cd,
        prov_nm::varchar(255) as prov_nm,
        region_cd::varchar(50) as region_cd,
        region_nm::varchar(255) as region_nm,
        mncplty_cd::varchar(50) as mncplty_cd,
        mncplty_nm::varchar(255) as mncplty_nm,
        city_cd::varchar(50) as city_cd,
        city_nm::varchar(255) as city_nm,
        chnl_sub_grp_cd::varchar(50) as chnl_sub_grp_cd,
        pms_nm::varchar(255) as pms_nm,
        ash_no::varchar(255) as ash_no,
        ash_nm::varchar(255) as ash_nm,
        address1::varchar(255) as address1,
        address2::varchar(255) as address2,
        jj_chnl_cd::varchar(255) as jj_chnl_cd,
        tsr::varchar(255) as tsr,
        pmr::varchar(255) as pmr,
        chnl::varchar(255) as chnl,
        area_cd::varchar(255) as area_cd,
        area_nm::varchar(255) as area_nm,
        region_nm2::varchar(255) as region_nm2,
        wsman::varchar(255) as wsman,
        route::varchar(255) as route,
        status::varchar(255) as status,
        operating_hrs::varchar(255) as operating_hrs,
        da_tag::varchar(255) as da_tag,
        dizr_tag::varchar(255) as dizr_tag,
        brnch_grp1::varchar(255) as brnch_grp1,
        brnch_grp2::varchar(255) as brnch_grp2,
        outlet_typ::varchar(255) as outlet_typ,
        store_typ_cd::varchar(255) as store_typ_cd,
        store_typ_desc::varchar(255) as store_typ_desc,
        prov_cd2::varchar(255) as prov_cd2,
        data_compln_status::varchar(255) as data_compln_status,
        ae_nm::varchar(255) as ae_nm,
        dt_opnd::varchar(255) as dt_opnd,
        store_tin_no::varchar(255) as store_tin_no,
        store_size_cd::varchar(255) as store_size_cd,
        store_size::varchar(255) as store_size,
        store_mtrx_cd::varchar(255) as store_mtrx_cd,
        store_mtrx::varchar(255) as store_mtrx,
        class::varchar(255) as class,
        store_clsfn::varchar(255) as store_clsfn,
        jj_sold_to::varchar(255) as jj_sold_to,
        jj_ship_to::varchar(255) as jj_ship_to,
        bp::varchar(255) as bp,
        sales_grp::varchar(255) as sales_grp,
        dsm::varchar(255) as dsm,
        sales_man_tag::varchar(255) as sales_man_tag,
        branch_no::varchar(255) as branch_no,
        mdc_tag::varchar(255) as mdc_tag,
        derived_branchno::varchar(255) as derived_branchno,
        last_chg_datetime::timestamp_ntz(9) as last_chg_datetime,
        effective_from::timestamp_ntz(9) as effective_from,
        effective_to::timestamp_ntz(9) as effective_to,
        active::varchar(10) as active,
        crtd_dttm::timestamp_ntz(9) as crtd_dttm,
        updt_dttm::timestamp_ntz(9) as updt_dttm,
        zip_code::varchar(100) as zip_code,
        zip_cd_name::varchar(255) as zip_cd_name,
        barangay_code::varchar(100) as barangay_code,
        barangay_cd_name::varchar(255) as barangay_cd_name,
        long_lat_source::number(20, 10) as long_lat_source,
        latitude::number(20, 10) as latitude,
        longitude::number(20, 10) as longitude
    from transformed
)

select * from final
