with wks_prox_report_bi_contract_temp as
(
    select * from rg_wks.wks_prox_report_bi_contract_temp
),
final as
(
    Select
    RowID,
	BudgetYear,
	ExpenseSubCategory,
	AccountGroupCode,
	AccountGroupName,
	CustomerType,
	HQSoldToCode,
	HQSoldToName,
	ContractNo,
	ContractTempNo,
	ContractTitle,
	ThemeCode,
	ThemeName,
	Objective,
	FeesPaid,
	ContractRevenueRecognitionStartDate,
	ContractRevenueRecognitionEndDate,
	ContractPromoExecutionStartDate,
	ContractPromoExecutionEndDate,
	ContractCreateDate,
	ContractApprovalDate,
	ContractStatus,
	DateBack,
	DateBackReason,
	ExpenseID,
	CustomerCode,
	CustomerName,
	RebateNo,
	RebateActivityName,
	CustomerContractNo,
	ExpenseRevenueRecognitionStartDate,
	ExpenseRevenueRecognitionEndDate,
	ExpensePromoExecutionStartDate,
	ExpensePromoExecutionEndDate,
	ExpenseClosed,
	CloseUser,
	CloseTime,
	ContractType,
	ConditionType,
	GLAccount,
	ExpenseTypeName,
	ProfitCenter,
	PPGCode,
	PPGName,
	Rate,
	MaterialCode,
	MaterialName,
	BudgetOwner,
	Channel,
	RTMChannel,
	PaymentMethod,
	ExpenseAmount,
	CommitmentAmount,
	AccrualReleaseAmountWithoutTax,
	CloseAmount,
	PaidAmount,
	ApprovedAmount,
	UnpaidAmount,
	AvailableToPay,
	AgingDays,
	Aging,
	Applicant,
	ContractDescription,
	DocumentLink,
	WithAttachment,
	DTSMarkupRate,
	ApplicationID,
	'"+(String)globalMap.get("File_Name")+"' AS filename,
	'"+context.run_id+"' AS run_id,
	convert_timezone('Asia/Kolkata', sysdate) AS crt_dttm
    from wks_prox_report_bi_contract_temp
)
select * from final