with source as(
    select * from {{ source('thasdl_raw', 'sdl_mds_th_htc_customer') }}
),
transformed as(
    select
        trim(distributorid) as distributorid,
        trim(code) as arcode,
        trim(name) as arname,
        trim(araddress) as araddress,
        trim(telephone) as telephone,
        trim(fax) as fax,
        trim(city) as city,
        trim(region) as region,
        trim(saledistrict) as saledistrict,
        trim(saleoffice) as saleoffice,
        trim(salegroup) as salegroup,
        trim(artypecode) as artypecode,
        trim(saleemployee) as saleemployee,
        trim(salename) as salename,
        trim(billno) as billno,
        trim(billmoo) as billmoo,
        trim(billsoi) as billsoi,
        trim(billroad) as billroad,
        trim(billsubdist) as billsubdist,
        trim(billdistrict) as billdistrict,
        trim(billprovince) as billprovince,
        trim(billzipcode) as billzipcode,
        cast(trim(activestatus) as int) as activestatus,
        trim(routestep1) as routestep1,
        trim(routestep2) as routestep2,
        trim(routestep3) as routestep3,
        trim(routestep4) as routestep4,
        trim(routestep5) as routestep5,
        trim(routestep6) as routestep6,
        trim(routestep7) as routestep7,
        trim(routestep8) as routestep8,
        trim(routestep9) as routestep9,
        trim(routestep10) as routestep10,
        trim(store) as store,
        trim(pricelevel) as pricelevel,
        trim(salesareaname) as salesareaname,
        trim(branchcode) as branchcode,
        trim(branchname) as branchname,
        trim(frequencyofvisit) as frequencyofvisit,
        null as run_id,
        current_timestamp()::timestampntz(9) crt_dttm
    from source
),
final as(
    select
        distributorid::varchar(10) as distributorid,
        arcode::varchar(20) as arcode,
        arname::varchar(500) as arname,
        araddress::varchar(500) as araddress,
        telephone::varchar(150) as telephone,
        fax::varchar(150) as fax,
        city::varchar(500) as city,
        region::varchar(20) as region,
        saledistrict::varchar(200) as saledistrict,
        saleoffice::varchar(10) as saleoffice,
        salegroup::varchar(10) as salegroup,
        artypecode::varchar(10) as artypecode,
        saleemployee::varchar(150) as saleemployee,
        salename::varchar(250) as salename,
        billno::varchar(500) as billno,
        billmoo::varchar(250) as billmoo,
        billsoi::varchar(255) as billsoi,
        billroad::varchar(255) as billroad,
        billsubdist::varchar(30) as billsubdist,
        billdistrict::varchar(30) as billdistrict,
        billprovince::varchar(30) as billprovince,
        billzipcode::varchar(50) as billzipcode,
        activestatus::number(18,0) as activestatus,
        routestep1::varchar(30) as routestep1,
        routestep2::varchar(30) as routestep2,
        routestep3::varchar(30) as routestep3,
        routestep4::varchar(30) as routestep4,
        routestep5::varchar(30) as routestep5,
        routestep6::varchar(30) as routestep6,
        routestep7::varchar(30) as routestep7,
        routestep8::varchar(30) as routestep8,
        routestep9::varchar(30) as routestep9,
        routestep10::varchar(30) as routestep10,
        store::varchar(200) as store,
        pricelevel::varchar(50) as pricelevel,
        salesareaname::varchar(150) as salesareaname,
        branchcode::varchar(50) as branchcode,
        branchname::varchar(150) as branchname,
        frequencyofvisit::varchar(50) as frequencyofvisit,
        run_id::varchar(50) as run_id,
        crt_dttm as crt_dttm
    from transformed
)
select * from final