with source as(
    select * from {{ ref('thaitg_integration__itg_mds_th_myanmar_customer_master') }}
),
final as(
    select distinct
        'MYM'::varchar(10) AS dstrbtr_id,
        customer_code::varchar(20) AS ar_cd,
        'N/A'::varchar(25) AS old_cust_id,
        customer_name::varchar(500) AS ar_nm,
        'N/A'::varchar(500) AS ar_adres,
        'N/A'::varchar(150) AS tel_phn,
        'N/A'::varchar(150) AS fax,
        'N/A'::varchar(500) AS city,
        'N/A'::varchar(20) AS region,
        'N/A'::varchar(20) AS ar_typ_cd,
        'N/A'::varchar(10) AS sls_dist,
        sales_office::varchar(30) AS sls_office,
        sales_group::varchar(30) AS sls_grp,
        'N/A'::varchar(150) AS sls_emp,
        'N/A'::varchar(250) AS sls_nm,
        'N/A'::varchar(255) AS src_file,
        'N/A'::varchar(500) AS bill_no,
        'N/A'::varchar(250) AS bill_moo,
        'N/A'::varchar(255) AS bill_soi,
        'N/A'::varchar(255) AS bill_rd,
        'N/A'::varchar(30) AS bill_subdist,
        'N/A'::varchar(30) AS bill_dist,
        'N/A'::varchar(30) AS bill_prvnce,
        'N/A'::varchar(50) AS bill_zip_cd,
        null::timestamp_ntz(9) as modify_dt,
        'N/A'::varchar(10) AS routestep1,
        'N/A'::varchar(10) AS routestep2,
        'N/A'::varchar(10) AS routestep3,
        'N/A'::varchar(10) AS routestep4,
        'N/A'::varchar(10) AS routestep5,
        'N/A'::varchar(10) AS routestep6,
        'N/A'::varchar(10) AS routestep7,
        'N/A'::varchar(10) AS routestep8,
        'N/A'::varchar(10) AS routestep9,
        'N/A'::varchar(10) AS routestep10,
        1::number(18,0) as actv_status,
        'N/A'::varchar(50) AS cust_type,
        distributor_name::varchar(100) AS dstrbtr_nm,
        null::number(18,0) as dstrbtr_cost_lvl,
        'N/A'::varchar(10) AS dstrbtr_status,
        'N/A'::varchar(20) AS dstrbtr_region,
        'N/A'::varchar(20) AS dstrbtr_cntry,
        'N/A'::varchar(10) AS curnt_dist,
        null::number(3,0) as dstrbtr_inv_day,
        'N/A'::varchar(255) AS dstrbtr_cd,
        null::FLOAT as dstrbtr_fee,
        customer_re::varchar(100) AS grp_nm,
        'N/A'::varchar(10) AS ar_typ_grp,
        customer_re::varchar(50) AS typ_grp_nm,
        'N/A'::varchar(50) AS sales_district,
        'N/A'::varchar(100) AS sls_dist_city,
        'N/A'::varchar(100) AS sls_dist_region,
        'N/A'::varchar(100) AS sls_dist_city_eng,
        'N/A'::varchar(5) AS sls_dist_blng_to_dstrbtr,
        'N/A'::varchar(100) AS region_desc,
        'N/A'::varchar(100) AS dist_nm,
        'N/A'::varchar(100) AS sub_dist_nm,
        'N/A'::varchar(50) AS pricelevel,
        'N/A'::varchar(150) AS salesareaname,
        'N/A'::varchar(50) AS branchcode,
        'N/A'::varchar(150) AS branchname,
        'N/A'::varchar(50) AS frequencyofvisit,
        'N/A'::varchar(200) AS store,
        customer_re::varchar(100) AS re_nm,
        current_timestamp()::timestamp_ntz(9) AS crt_dttm,
        current_timestamp()::timestamp_ntz(9) AS updt_dttm
  from source
)
select * from final