with EDW_RPT_REGIONAL_SELLOUT_OFFTAKE as (
    select * from {{ source('aspedw_integration', 'edw_rpt_regional_sellout_offtake') }}
),

transformation as (
    SELECT  COUNTRY_CODE AS CNTRY_CD,
        MD5(NVL (DISTRIBUTOR_CODE,'DC') ||NVL (DISTRIBUTOR_NAME,'DN') ||NVL (STORE_CODE,'SC') ||NVL (SKU_CODE,'SKU') ||nvl(SOLD_TO_CODE,'STC')||NVL (STORE_NAME,'Store_name')
||NVL (CUSTOMER_PRODUCT_DESC,'CPD') ||NVL (SAP_PARENT_CUSTOMER_KEY,'SPCK') ||NVL (SAP_PARENT_CUSTOMER_DESCRIPTION,'SPSCD') 
|| NVL (SAP_CUSTOMER_CHANNEL_KEY,'SCCK') ||NVL (SAP_CUSTOMER_CHANNEL_DESCRIPTION,'SCCD') ||NVL (SAP_CUSTOMER_SUB_CHANNEL_KEY,'SCSCK') ||NVL (SAP_SUB_CHANNEL_DESCRIPTION,'SSCD') 
||NVL (CUSTOMER_SEGMENT_KEY,'CSK') ||NVL (CUSTOMER_SEGMENT_DESCRIPTION,'CSD') || NVL (SAP_GO_TO_MDL_KEY,'SGMK') ||NVL (SAP_GO_TO_MDL_DESCRIPTION,'SGMD') ||NVL (SAP_BANNER_KEY,'SBK') 
||NVL (SAP_BANNER_DESCRIPTION,'SBD') ||NVL (SAP_BANNER_FORMAT_KEY,'SBFK') ||NVL (SAP_BANNER_FORMAT_DESCRIPTION,'SBFD') ||NVL (RETAIL_ENVIRONMENT,'RE') 
|| NVL (GLOBAL_PRODUCT_FRANCHISE,'GPF') ||NVL (GLOBAL_PRODUCT_BRAND,'GPB') ||NVL (GLOBAL_PRODUCT_SUB_BRAND,'GPSB') || NVL (GLOBAL_PRODUCT_VARIANT,'GPV') 
||NVL (GLOBAL_PRODUCT_SEGMENT,'GPS') ||NVL (GLOBAL_PRODUCT_SUBSEGMENT,'GPSS') || NVL (GLOBAL_PRODUCT_CATEGORY,'GPC') ||NVL (GLOBAL_PRODUCT_SUBCATEGORY,'GPSC') 
||NVL (GLOBAL_PUT_UP_DESCRIPTION,'GPUD') ||NVL (PKA_PRODUCT_KEY,'PK') ||NVL (PKA_PRODUCT_KEY_DESCRIPTION,'PKD')
|| NVL (REGION,'region')|| NVL (ZONE_OR_AREA,'ZONE_OR_AREA')|| NVL (CHANNEL,'CHANNEL')
)AS SELLOUT_DIM_KEY,
       'Japan' AS cntry_nm,
       DATA_SOURCE,
       DISTRIBUTOR_CODE,
       DISTRIBUTOR_NAME,
       STORE_CODE,
	   store_name,
       SOLD_TO_CODE,
       SKU_CODE,
       YEAR,
       MNTH_ID,  
       CUSTOMER_PRODUCT_DESC,
             SAP_PARENT_CUSTOMER_KEY,
             SAP_PARENT_CUSTOMER_DESCRIPTION,
             SAP_CUSTOMER_CHANNEL_KEY,
             SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             SAP_CUSTOMER_SUB_CHANNEL_KEY,
             SAP_SUB_CHANNEL_DESCRIPTION,
             SAP_GO_TO_MDL_KEY,
             SAP_GO_TO_MDL_DESCRIPTION,
             SAP_BANNER_KEY,
             SAP_BANNER_DESCRIPTION,
             SAP_BANNER_FORMAT_KEY,
             SAP_BANNER_FORMAT_DESCRIPTION,
             RETAIL_ENVIRONMENT,
             REGION,
             ZONE_OR_AREA,
             CHANNEL,
             CUSTOMER_SEGMENT_KEY,
             CUSTOMER_SEGMENT_DESCRIPTION,
             GLOBAL_PRODUCT_FRANCHISE,
             GLOBAL_PRODUCT_BRAND,
             GLOBAL_PRODUCT_SUB_BRAND,
             GLOBAL_PRODUCT_VARIANT,
             GLOBAL_PRODUCT_SEGMENT,
             GLOBAL_PRODUCT_SUBSEGMENT,
             GLOBAL_PRODUCT_CATEGORY,
             GLOBAL_PRODUCT_SUBCATEGORY,
             GLOBAL_PUT_UP_DESCRIPTION,
             PKA_PRODUCT_KEY,
             PKA_PRODUCT_KEY_DESCRIPTION,       
       CAST(SUM(SELLOUT_SALES_QUANTITY)AS DECIMAL(38,6)) AS SO_SLS_QTY,
       CAST(SUM(SELLOUT_SALES_VALUE) AS NUMERIC (38,6))AS SO_SLS_VALUE,
       CAST(AVG(SELLOUT_SALES_QUANTITY) AS DECIMAL(38,6)) AS SO_AVG_QTY,
       SUM(SALES_VALUE_LIST_PRICE)AS SALES_VALUE_LIST_PRICE,
	   SYSDATE() AS CRT_DTTM
FROM (SELECT COUNTRY_CODE,
             COUNTRY_NAME,
             DATA_SOURCE,
             YEAR AS YEAR,
             MNTH_ID AS MNTH_ID,
             DISTRIBUTOR_CODE,
             MAIN.Distributor_Name||'#'||LTRIM(MAIN.Distributor_CODE,'0') AS Distributor_Name,
             SOLD_TO_CODE,
             STORE_CODE,
             SKU_CODE,
	      MAIN.STORE_Name||'#'||ltrim(MAIN.STORE_CODE,'0') AS STORE_NAME,
             CUSTOMER_PRODUCT_DESC,
             SAP_PARENT_CUSTOMER_KEY,
             SAP_PARENT_CUSTOMER_DESCRIPTION,
             SAP_CUSTOMER_CHANNEL_KEY,
             SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             SAP_CUSTOMER_SUB_CHANNEL_KEY,
             SAP_SUB_CHANNEL_DESCRIPTION,
             SAP_GO_TO_MDL_KEY,
             SAP_GO_TO_MDL_DESCRIPTION,
             SAP_BANNER_KEY,
             SAP_BANNER_DESCRIPTION,
             SAP_BANNER_FORMAT_KEY,
             SAP_BANNER_FORMAT_DESCRIPTION,
             RETAIL_ENVIRONMENT,
             REGION,
             ZONE_OR_AREA,
             CHANNEL,
             CUSTOMER_SEGMENT_KEY,
             CUSTOMER_SEGMENT_DESCRIPTION,
             GLOBAL_PRODUCT_FRANCHISE,
             GLOBAL_PRODUCT_BRAND,
             GLOBAL_PRODUCT_SUB_BRAND,
             GLOBAL_PRODUCT_VARIANT,
             GLOBAL_PRODUCT_SEGMENT,
             GLOBAL_PRODUCT_SUBSEGMENT,
             GLOBAL_PRODUCT_CATEGORY,
             GLOBAL_PRODUCT_SUBCATEGORY,
             GLOBAL_PUT_UP_DESCRIPTION,
             SKU_DESCRIPTION,
             PKA_PRODUCT_KEY,
             PKA_PRODUCT_KEY_DESCRIPTION,
             SELLOUT_SALES_QUANTITY,
             SELLOUT_SALES_VALUE,
             SALES_VALUE_LIST_PRICE
FROM (SELECT COUNTRY_CODE,
             COUNTRY_NAME,
             DATA_SOURCE,
             YEAR AS YEAR,
             MNTH_ID AS MNTH_ID,
             ltrim(DISTRIBUTOR_CODE,'0') AS DISTRIBUTOR_CODE,
             max(distributor_name) over (PARTITION BY ltrim(distributor_code,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS distributor_name,
             max(soldto_code) over ( PARTITION BY mnth_id,ltrim(distributor_code,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS SOLD_TO_CODE,
             ltrim(STORE_CODE,'0') AS STORE_CODE,
             ltrim(msl_product_code,'0') AS SKU_CODE,
	      max(store_name) over (PARTITION BY ltrim(store_code,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS STORE_NAME,
             CUSTOMER_PRODUCT_DESC,
             SAP_PARENT_CUSTOMER_KEY,
             SAP_PARENT_CUSTOMER_DESCRIPTION,
             SAP_CUSTOMER_CHANNEL_KEY,
             SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             SAP_CUSTOMER_SUB_CHANNEL_KEY,
             SAP_SUB_CHANNEL_DESCRIPTION,
             SAP_GO_TO_MDL_KEY,
             SAP_GO_TO_MDL_DESCRIPTION,
             SAP_BANNER_KEY,
             SAP_BANNER_DESCRIPTION,
             SAP_BANNER_FORMAT_KEY,
             SAP_BANNER_FORMAT_DESCRIPTION,
             RETAIL_ENVIRONMENT,
             REGION,
             ZONE_OR_AREA,
             CHANNEL,
             CUSTOMER_SEGMENT_KEY,
             CUSTOMER_SEGMENT_DESCRIPTION,
             GLOBAL_PRODUCT_FRANCHISE,
             GLOBAL_PRODUCT_BRAND,
             GLOBAL_PRODUCT_SUB_BRAND,
             GLOBAL_PRODUCT_VARIANT,
             GLOBAL_PRODUCT_SEGMENT,
             GLOBAL_PRODUCT_SUBSEGMENT,
             GLOBAL_PRODUCT_CATEGORY,
             GLOBAL_PRODUCT_SUBCATEGORY,
             GLOBAL_PUT_UP_DESCRIPTION,
             max(msl_product_desc) over (PARTITION BY ltrim(msl_product_code,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SKU_DESCRIPTION,
             PKA_PRODUCT_KEY,
             PKA_PRODUCT_KEY_DESCRIPTION,
             SELLOUT_SALES_QUANTITY,
             SELLOUT_SALES_VALUE,
             sellout_value_list_price as SALES_VALUE_LIST_PRICE
      FROM EDW_RPT_REGIONAL_SELLOUT_OFFTAKE 
       WHERE COUNTRY_NAME='Japan'
       --and MNTH_ID >= (select last_36mnths from rg_edw.edw_vw_cal_Retail_excellence_Dim)
	  --and mnth_id <= (select prev_mnth from rg_edw.edw_vw_cal_Retail_excellence_Dim)
	  )MAIN)                 
GROUP BY  COUNTRY_CODE,
         COUNTRY_NAME,
         DATA_SOURCE,
         YEAR,
         MNTH_ID,
         DISTRIBUTOR_CODE,
         DISTRIBUTOR_NAME,
         SOLD_TO_CODE,
         STORE_CODE,
		 store_name,
         CHANNEL,
         CUSTOMER_PRODUCT_DESC,
         SAP_PARENT_CUSTOMER_KEY,
         SAP_PARENT_CUSTOMER_DESCRIPTION,
         SAP_CUSTOMER_CHANNEL_KEY,
         SAP_CUSTOMER_CHANNEL_DESCRIPTION,
         SAP_CUSTOMER_SUB_CHANNEL_KEY,
         SAP_SUB_CHANNEL_DESCRIPTION,
         SAP_GO_TO_MDL_KEY,
         SAP_GO_TO_MDL_DESCRIPTION,
         SAP_BANNER_KEY,
         SAP_BANNER_DESCRIPTION,
         SAP_BANNER_FORMAT_KEY,
         SAP_BANNER_FORMAT_DESCRIPTION,
         RETAIL_ENVIRONMENT,
         REGION,
         ZONE_OR_AREA,
         CUSTOMER_SEGMENT_KEY,
         CUSTOMER_SEGMENT_DESCRIPTION,
         GLOBAL_PRODUCT_FRANCHISE,
         GLOBAL_PRODUCT_BRAND,
         GLOBAL_PRODUCT_SUB_BRAND,
         GLOBAL_PRODUCT_VARIANT,
         GLOBAL_PRODUCT_SEGMENT,
         GLOBAL_PRODUCT_SUBSEGMENT,
         GLOBAL_PRODUCT_CATEGORY,
         GLOBAL_PRODUCT_SUBCATEGORY,
         GLOBAL_PUT_UP_DESCRIPTION,
         SKU_CODE,
         PKA_PRODUCT_KEY,
         PKA_PRODUCT_KEY_DESCRIPTION
),

final as (
select 
cntry_cd::varchar(2) AS cntry_cd,
sellout_dim_key::varchar(32) AS sellout_dim_key,
cntry_nm::varchar(5) AS cntry_nm,
data_source::varchar(14) AS data_source,
distributor_code::varchar(100) AS distributor_code,
distributor_name::varchar(356) AS distributor_name,
store_code::varchar(100) AS store_code,
store_name::varchar(601) AS store_name,
sold_to_code::varchar(255) AS sold_to_code,
sku_code::varchar(150) AS sku_code,
year::integer AS year,
mnth_id::varchar(23) AS mnth_id,
customer_product_desc::varchar(300) AS customer_product_desc,
sap_parent_customer_key::varchar(12) AS sap_parent_customer_key,
sap_parent_customer_description::varchar(75) AS sap_parent_customer_description,
sap_customer_channel_key::varchar(12) AS sap_customer_channel_key,
sap_customer_channel_description::varchar(75) AS sap_customer_channel_description,
sap_customer_sub_channel_key::varchar(12) AS sap_customer_sub_channel_key,
sap_sub_channel_description::varchar(75) AS sap_sub_channel_description,
sap_go_to_mdl_key::varchar(12) AS sap_go_to_mdl_key,
sap_go_to_mdl_description::varchar(75) AS sap_go_to_mdl_description,
sap_banner_key::varchar(12) AS sap_banner_key,
sap_banner_description::varchar(75) AS sap_banner_description,
sap_banner_format_key::varchar(12) AS sap_banner_format_key,
sap_banner_format_description::varchar(75) AS sap_banner_format_description,
retail_environment::varchar(50) AS retail_environment,
region::varchar(150) AS region,
zone_or_area::varchar(150) AS zone_or_area,
channel::varchar(150) AS channel,
customer_segment_key::varchar(12) AS customer_segment_key,
customer_segment_description::varchar(50) AS customer_segment_description,
global_product_franchise::varchar(30) AS global_product_franchise,
global_product_brand::varchar(30) AS global_product_brand,
global_product_sub_brand::varchar(100) AS global_product_sub_brand,
global_product_variant::varchar(100) AS global_product_variant,
global_product_segment::varchar(50) AS global_product_segment,
global_product_subsegment::varchar(100) AS global_product_subsegment,
global_product_category::varchar(50) AS global_product_category,
global_product_subcategory::varchar(50) AS global_product_subcategory,
global_put_up_description::varchar(100) AS global_put_up_description,
pka_product_key::varchar(68) AS pka_product_key,
pka_product_key_description::varchar(255) AS pka_product_key_description,
so_sls_qty::numeric(38,6) AS so_sls_qty,
so_sls_value::numeric(38,6) AS so_sls_value,
so_avg_qty::numeric(38,6) AS so_avg_qty,
sales_value_list_price::numeric(38,12) AS sales_value_list_price,
crt_dttm::timestamp AS crt_dttm
from transformation
)


select * from final