with source as(
    select * from {{ source('jpnedw_integration', 'mt_cld') }}
),
final as(
    select
        ymd_dt::timestamp_ntz(9) as ymd_dt,
        year::varchar(4) as year,
        year_445::varchar(4) as year_445,
        year_15::varchar(4) as year_15,
        year_20::varchar(4) as year_20,
        half::varchar(1) as half,
        half_nm::varchar(10) as half_nm,
        half_445::varchar(1) as half_445,
        half_445_nm::varchar(10) as half_445_nm,
        half_15::varchar(1) as half_15,
        half_15_nm::varchar(10) as half_15_nm,
        half_20::varchar(1) as half_20,
        half_20_nm::varchar(10) as half_20_nm,
        quarter::varchar(2) as quarter,
        quarter_nm::varchar(20) as quarter_nm,
        quarter_445::varchar(2) as quarter_445,
        quarter_445_nm::varchar(20) as quarter_445_nm,
        quarter_15::varchar(2) as quarter_15,
        quarter_15_nm::varchar(20) as quarter_15_nm,
        quarter_20::varchar(2) as quarter_20,
        quarter_20_nm::varchar(20) as quarter_20_nm,
        month::varchar(2) as month,
        month_nm::varchar(20) as month_nm,
        month_445::varchar(2) as month_445,
        month_445_nm::varchar(20) as month_445_nm,
        month_15::varchar(2) as month_15,
        month_15_nm::varchar(20) as month_15_nm,
        month_20::varchar(2) as month_20,
        month_20_nm::varchar(20) as month_20_nm,
        ymonth_445::varchar(20) as ymonth_445,
        ymonth_15::varchar(20) as ymonth_15,
        ymonth_20::varchar(20) as ymonth_20,
        week_ms::varchar(6) as week_ms,
        week_ss::varchar(6) as week_ss,
        mweek_445::varchar(20) as mweek_445,
        mweek_15ms::varchar(20) as mweek_15ms,
        mweek_15ss::varchar(20) as mweek_15ss,
        mweek_20::varchar(20) as mweek_20,
        mweek_445_iso::varchar(20) as mweek_445_iso,
        mweek_15ms_iso::varchar(20) as mweek_15ms_iso,
        mweek_15ss_iso::varchar(20) as mweek_15ss_iso,
        mweek_20_iso::varchar(20) as mweek_20_iso,
        week::varchar(6) as week,
        day::varchar(2) as day,
        day_of_week::varchar(3) as day_of_week,
        opr_flg::varchar(2) as opr_flg,
        sls_flg::varchar(2) as sls_flg
    from source
)
select * from final