{{
    config(
        materialized='view'
    )
}}


with source as(
    select * from {{ ref('hcpedw_integration__edw_hcp360_iqvia_kpi_rpt') }}
),
transformed as(
    select 
        brand as "brand",
        ventasys_id as "ventasys_id",
        ventasys_name as "ventasys_name",
        ventasys_mobile as "ventasys_mobile",
        ventasys_email as "ventasys_email",
        veeva_id as "veeva_id",
        veeva_name as "veeva_name",
        veeva_mobile as "veeva_mobile",
        veeva_email as "veeva_email",
        sfmc_id as "sfmc_id",
        sfmc_name as "sfmc_name",
        sfmc_mobile as "sfmc_mobile",
        sfmc_email as "sfmc_email",
        master_hcp_key as "master_hcp_key",
        source_system as "source_system",
        hcp_id as "hcp_id",
        customer_name as "customer_name",
        cell_phone as "cell_phone",
        email as "email",
        account_source_id as "account_source_id",
        ventasys_team_name as "ventasys_team_name",
        ventasys_custid as "ventasys_custid",
        subscriber_key as "subscriber_key",
        data_source as "data_source",
        country_code as "country_code",
        region as "region",
        zone as "zone",
        area as "area",
        classification as "classification",
        speciality as "speciality",
        core_noncore as "core_noncore",
        year as "year",
        upper(month) as "month",
        hcp_created_date as "hcp_created_date",
        territory_id as "territory_id",
        region_hq as "region_hq",
        is_active as "is_active",
        is_active_msr as "is_active_msr",
        first_prescription_date as "first_prescription_date",
        prescriber_type as "prescriber_type",
        total_prescriptions as "total_prescriptions",
        prescription_units as "prescription_units",
        unique_product_type as "unique_product_type",
        planned_visits as "planned_visits",
        actual_visits as "actual_visits",
        phone_connects as "phone_connects",
        video_connects as "video_connects",
        f2f_connects as "f2f_connects",
        avg_prod_detailed as "avg_prod_detailed",
        lbl_given as "lbl_given",
        samples_given as "samples_given",
        emails_sent as "emails_sent",
        emails_delivered as "emails_delivered",
        emails_opened as "emails_opened",
        emails_clicked as "emails_clicked",
        emails_unique_clicked as "emails_unique_clicked",
        emails_unsusbscribed as "emails_unsusbscribed",
        emails_forwarded as "emails_forwarded",
        average_call_duration as "average_call_duration",
        events_registered as "events_registered",
        events_attended as "events_attended",
        events_as_speaker as "events_as_speaker",
        avg_key_msgs_delivered as "avg_key_msgs_delivered",
        master_id as "master_id",
        activity_date as "activity_date",
        prescription_id as "prescription_id",
        all_visitor as "all_visitor",
        total_session_duration as "total_session_duration",
        sessions as "sessions",
        total_bounces as "total_bounces",
        sales_value as "sales_value",
        iqvia_brand as "iqvia_brand",
        brand_category as "brand_category",
        report_brand_reference as "report_brand_reference",
        iqvia_product_description as "iqvia_product_description",
        totalprescriptions_iqvia as "totalprescriptions_iqvia",
        totalprescriptions_by_brand as "totalprescriptions_by_brand",
        totalprescriptions_jnj_brand as "totalprescriptions_jnj_brand",
        num_buying_retailer as "num_buying_retailer",
        num_buying_retailer_ytd as "num_buying_retailer_ytd",
        num_buying_retailer_mat as "num_buying_retailer_mat",
        consent_flag as "consent_flag",
        projected_doctors as "projected_doctors",
        consent_date as "consent_date",
        ventasys_hcp_id as "ventasys_hcp_id",
    from source
)
select * from transformed