{{
    config(
        materialized= "incremental",
        incremental_strategy= "append",
        pre_hook = "{% if is_incremental() %}
                delete from {{this}}
where call_sample_id in (select stg.call_sample_id
                         from {{ source('hcposesdl_raw', 'sdl_hcp_osea_call_sample') }} stg
                         where stg.call_sample_id = call_sample_id);
                    {% endif %}"
    )
}}
with 
sdl_hcp_osea_call_sample as
(
	select * from {{ source('hcposesdl_raw', 'sdl_hcp_osea_call_sample') }}
)
,
transformed 
AS
(
SELECT CALL_SAMPLE_ID,
       (CASE WHEN UPPER(IS_DELETED) = 'TRUE' THEN 1 WHEN UPPER(IS_DELETED) IS NULL THEN 0 WHEN UPPER(IS_DELETED) = ' ' THEN 0 ELSE 0 END) AS IS_DELETED,
       CALL_SAMPLE_NAME,
       CREATED_DATE,
       CREATED_BY_ID,
       LAST_MODIFIED_DATE,
       LAST_MODIFIED_BY_ID,
       SYSTEM_MODSTAMP,
LAST_ACTIVITY_DATE,
MAY_EDIT,
 CASE WHEN UPPER(IS_LOCKED) = 'TRUE' THEN 1 WHEN UPPER(IS_LOCKED) = 'FALSE' THEN 0 ELSE 0 END AS IS_LOCKED,	          
LAST_VIEWED_DATE,
LAST_REFERENCE_DATE,
ACCOUNT,
DATE,
IS_PARENT_CALL,
QUANTITY,
LOT_NO,
MOBILE_ID,
CALL,
PRODUCT,
OVERRIDE_LOCK,
DISTRIBUTOR,
ATTENDEE_TYPE,
ENTITY_REFERENCE_ID,
DELIVERY_STATUS,
APPLY_LIMIT,
LIMIT_APPLIED,
MANUFACTURER,
CALL_MOBILE_ID,
AMOUNT,
PRODUCT_VALUE,
COLD_CHAIN_STATUS,
CUSTOM_TEXT,
TAG_ALERT_NUMBER,
BARCODE_SCAN,
LEGACY_ID,
ACCOUNT_EMAIL,
ADDRESS,
current_timestamp() as INSERTED_DATE,
       NULL as UPDATED_DATE 
FROM sdl_hcp_osea_call_sample
)
,
final as 
(
	select 
	CALL_SAMPLE_ID::VARCHAR(40) AS CALL_SAMPLE_ID,
IS_DELETED::NUMBER(38,0) as IS_DELETED,
CALL_SAMPLE_NAME::VARCHAR(80) AS CALL_SAMPLE_NAME,
CREATED_DATE::TIMESTAMP_NTZ(9) AS CREATED_DATE,
CREATED_BY_ID::VARCHAR(18)AS CREATED_BY_ID,
LAST_MODIFIED_DATE::TIMESTAMP_NTZ(9) AS LAST_MODIFIED_DATE,
LAST_MODIFIED_BY_ID::VARCHAR(18) AS LAST_MODIFIED_BY_ID,
SYSTEM_MODSTAMP::TIMESTAMP_NTZ(9) AS SYSTEM_MODSTAMP,
LAST_ACTIVITY_DATE::DATE AS LAST_ACTIVITY_DATE,
MAY_EDIT::VARCHAR(10) AS MAY_EDIT,
IS_LOCKED::NUMBER(38,0) as IS_LOCKED,
LAST_VIEWED_DATE::TIMESTAMP_NTZ(9) AS LAST_VIEWED_DATE,
LAST_REFERENCE_DATE::TIMESTAMP_NTZ(9) AS LAST_REFERENCE_DATE,
ACCOUNT::VARCHAR(50) AS ACCOUNT,
DATE::DATE AS DATE,
IS_PARENT_CALL::NUMBER(6,0) AS IS_PARENT_CALL,
QUANTITY::NUMBER(18,1) AS QUANTITY,
LOT_NO::VARCHAR(80) AS LOT_NO,
MOBILE_ID::VARCHAR(100) AS MOBILE_ID,
CALL::VARCHAR(50) AS CALL,
PRODUCT::VARCHAR(50) AS PRODUCT,
OVERRIDE_LOCK::VARCHAR(50) AS OVERRIDE_LOCK,
DISTRIBUTOR::VARCHAR(255) AS DISTRIBUTOR,
ATTENDEE_TYPE::VARCHAR(100) AS ATTENDEE_TYPE,
ENTITY_REFERENCE_ID::VARCHAR(100) AS ENTITY_REFERENCE_ID,
DELIVERY_STATUS::VARCHAR(100) AS DELIVERY_STATUS,
APPLY_LIMIT::VARCHAR(100) AS APPLY_LIMIT,
LIMIT_APPLIED::VARCHAR(100) AS LIMIT_APPLIED,
MANUFACTURER::VARCHAR(255) AS MANUFACTURER,
CALL_MOBILE_ID::VARCHAR(100) AS CALL_MOBILE_ID,
AMOUNT::VARCHAR(100) AS AMOUNT,
PRODUCT_VALUE::VARCHAR(40) AS PRODUCT_VALUE,
COLD_CHAIN_STATUS::VARCHAR(100) AS COLD_CHAIN_STATUS,
CUSTOM_TEXT::VARCHAR(80) AS CUSTOM_TEXT,
TAG_ALERT_NUMBER::VARCHAR(80) AS TAG_ALERT_NUMBER,
BARCODE_SCAN::VARCHAR(100) AS BARCODE_SCAN,
LEGACY_ID::VARCHAR(255) AS LEGACY_ID,
ACCOUNT_EMAIL::VARCHAR(200) AS ACCOUNT_EMAIL,
ADDRESS::VARCHAR(1300) AS ADDRESS,
inserted_date::timestamp_ntz(9) as inserted_date,
	updated_date::timestamp_ntz(9) as updated_date
    from transformed 

)

select * from final 