--import cte
with itg_ph_re_msl_list as (
    select * from {{ ref('phlitg_integration__itg_ph_re_msl_list') }}
),
wks_philippines_regional_sellout_actuals as (
    select * from {{ ref('phlwks_integration__wks_philippines_regional_sellout_actuals' )}}
),
itg_mds_ph_lav_product as (
    select * from {{ ref('phlitg_integration__itg_mds_ph_lav_product') }}
),
customer_hierarchy as (
    select * from {{ ref('aspedw_integration__edw_generic_customer_hierarchy') }}
),
product_heirarchy as (
    select * from {{ ref('aspedw_integration__edw_generic_product_hierarchy') }}
),
edw_company_dim as (
    select * from {{ ref('aspedw_integration__edw_company_dim') }}
),
itg_mds_ph_lav_customer as (
    select * from {{ ref('phlitg_integration__itg_mds_ph_lav_customer')}}
),
wks_philippines_base_retail_excellence as (
    select * from {{ ref('phlwks_integration__wks_philippines_base_retail_excellence')}}
),
itg_mds_ph_gt_customer as (
    select * from {{ ref('phlitg_integration__itg_mds_ph_gt_customer')}}
),
itg_mds_ph_ref_parent_customer as (
    select * from {{ ref('phlitg_integration__itg_mds_ph_ref_parent_customer')}}
),
itg_mds_ph_pos_customers as (
    select * from {{ ref('phlitg_integration__itg_mds_ph_pos_customers')}}
),

--final cte

ph_rpt_retail_excellence_mdp as 
(
    SELECT DISTINCT MDP.*,		--// (SELECT DISTINCT MDP.*,
       COM.*,		--//        COM.*,
       SYSDATE() AS CRTD_DTTM 
    FROM ( SELECT TARGET.FISC_YR,		--// FROM ( SELECT TARGET.FISC_YR,
                TARGET.FISC_PER,		--//              TARGET.FISC_PER,
                COALESCE(ACTUAL.CNTRY_NM, 'Philippines') AS MARKET,		--// 			 COALESCE(ACTUAL.CNTRY_NM, 'Philippines') AS MARKET,
                COALESCE(ACTUAL.DATA_SOURCE, TARGET.DATA_SRC) AS DATA_SRC,		--// 			 COALESCE(ACTUAL.DATA_SOURCE, TARGET.DATA_SRC) AS DATA_SRC,
                COALESCE(TARGET.CHANNEL, ACTUAL.CHANNEL) AS CHANNEL_NAME,		--//              COALESCE(TARGET.CHANNEL, ACTUAL.CHANNEL) AS CHANNEL_NAME,
                COALESCE(TARGET.CUSTOMER_L0, ACTUAL.SOLD_TO_CODE) AS SOLD_TO_CODE,		--//              COALESCE(TARGET.CUSTOMER_L0, ACTUAL.SOLD_TO_CODE) AS SOLD_TO_CODE,
                COALESCE(TARGET.DISTRIBUTOR_CODE, ACTUAL.DISTRIBUTOR_CODE) AS DISTRIBUTOR_CODE,		--//              COALESCE(TARGET.DISTRIBUTOR_CODE, ACTUAL.DISTRIBUTOR_CODE) AS DISTRIBUTOR_CODE,
                COALESCE(TARGET.DISTRIBUTOR_NAME, ACTUAL.DISTRIBUTOR_NAME) AS DISTRIBUTOR_NAME,		--// 			 COALESCE(TARGET.DISTRIBUTOR_NAME, ACTUAL.DISTRIBUTOR_NAME) AS DISTRIBUTOR_NAME,
                TARGET.SELL_OUT_CHANNEL AS SELL_OUT_CHANNEL,		--//              TARGET.SELL_OUT_CHANNEL AS SELL_OUT_CHANNEL,
                COALESCE(TARGET.RETAIL_ENVIRONMENT, ACTUAL.RETAIL_ENVIRONMENT) AS RETAIL_ENVIRONMENT,		--// 			 COALESCE(TARGET.RETAIL_ENVIRONMENT, ACTUAL.RETAIL_ENVIRONMENT) AS RETAIL_ENVIRONMENT,
                COALESCE(TARGET.STORE_CODE, ACTUAL.STORE_CODE) AS STORE_CODE,		--//              COALESCE(TARGET.STORE_CODE, ACTUAL.STORE_CODE) AS STORE_CODE,
                COALESCE(TARGET.STORE_NAME, ACTUAL.STORE_NAME) AS STORE_NAME,		--//              COALESCE(TARGET.STORE_NAME, ACTUAL.STORE_NAME) AS STORE_NAME,
                COALESCE(ACTUAL.STORE_TYPE, 'NA') AS STORE_TYPE,		--//              COALESCE(ACTUAL.STORE_TYPE, 'NA') AS STORE_TYPE,
                COALESCE(TARGET.REGION, ACTUAL.REGION) AS REGION,		--// 			 COALESCE(TARGET.REGION, ACTUAL.REGION) AS REGION,
                TARGET.STORE_ADDRESS,		--//              TARGET.STORE_ADDRESS,
                TARGET.STORE_POSTCODE AS POST_CODE,		--//              TARGET.STORE_POSTCODE AS POST_CODE,
                COALESCE(TARGET."Area/Zone/Province", ACTUAL.ZONE_OR_AREA) AS ZONE_NAME,		--//              COALESCE(TARGET."Area/Zone/Province", ACTUAL.ZONE_OR_AREA) AS ZONE_NAME,
                TARGET.CITY AS CITY,		--//              TARGET.CITY AS CITY,
                COALESCE(ACTUAL.MASTER_CODE, TARGET.MASTER_CODE) AS PRODUCT_CODE,		--// 			 COALESCE(ACTUAL.MASTER_CODE, TARGET.MASTER_CODE) AS PRODUCT_CODE,
                COALESCE(ACTUAL.MSL_PRODUCT_DESC, TARGET.MSL_PRODUCT_DESC) AS PRODUCT_NAME,		--// 			 COALESCE(ACTUAL.MSL_PRODUCT_DESC, TARGET.MSL_PRODUCT_DESC) AS PRODUCT_NAME,
                COALESCE(ACTUAL.MAPPED_SKU_CD, TARGET.MAPPED_SKU_CD) AS MAPPED_SKU_CD,		--// 			 COALESCE(ACTUAL.MAPPED_SKU_CD, TARGET.MAPPED_SKU_CD) AS MAPPED_SKU_CD,
                'Philippines' AS PROD_HIER_L1,
                NULL AS PROD_HIER_L2,
                IMPLP.SCARD_FRANCHISE_DESC AS PROD_HIER_L3,		--//              IMPLP.scard_franchise_desc AS PROD_HIER_L3,
                IMPLP.SCARD_BRAND_DESC AS PROD_HIER_L4,		--//              IMPLP.scard_brand_desc AS PROD_HIER_L4,
                IMPLP.SCARD_VARIENT_DESC AS PROD_HIER_L5,		--//              IMPLP.scard_varient_desc AS PROD_HIER_L5,
                IMPLP.SCARD_PUT_UP_DESC AS PROD_HIER_L6,		--//              IMPLP.scard_put_up_desc AS PROD_HIER_L6,
                NULL AS PROD_HIER_L7,
                NULL AS PROD_HIER_L8,
                NULL AS PROD_HIER_L9,
                COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,
                COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,
                COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,
                COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,
                COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,
                COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,
                COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,
                COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,
                COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,
                COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,
                COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,
                COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,
                TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,
                TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,
                COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,		--//              COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,
                TRIM(NVL (NULLIF(PRODUCT.EAN,''),'NA')) AS EAN,		--//              TRIM(NVL (NULLIF(PRODUCT.EAN,''),'NA')) AS EAN,
                TRIM(NVL (NULLIF(PRODUCT.SAP_MATL_NUM,''),'NA')) AS SKU_CODE,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MATL_NUM,''),'NA')) AS SKU_CODE,
                TRIM(NVL (NULLIF(PRODUCT.SAP_MAT_DESC,''),'NA')) AS SKU_DESCRIPTION,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MAT_DESC,''),'NA')) AS SKU_DESCRIPTION,
                TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,
                TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,
                TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,
                TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,
                TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,
                COALESCE(ACTUAL.PKA_PRODUCT_KEY,PRODUCT.PKA_PRODUCT_KEY) AS PKA_PRODUCT_KEY,		--//              COALESCE(ACTUAL.PKA_PRODUCT_KEY,PRODUCT.PKA_PRODUCT_KEY) AS PKA_PRODUCT_KEY,
                COALESCE(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION) AS PKA_PRODUCT_KEY_DESCRIPTION,		--//              COALESCE(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION) AS PKA_PRODUCT_KEY_DESCRIPTION,
                ACTUAL.CM_SALES AS SALES_VALUE,		--//              ACTUAL.CM_SALES AS SALES_VALUE,
                ACTUAL.CM_SALES_QTY AS SALES_QTY,		--//              ACTUAL.CM_SALES_QTY AS SALES_QTY,
                ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,		--//              ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,
                ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,		--//              ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,
                ACTUAL.LM_SALES AS LM_SALES,		--//              ACTUAL.LM_SALES AS LM_SALES,
                ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,		--//              ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,
                ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,		--//              ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,
                ACTUAL.LM_SALES_LP AS LM_SALES_LP,		--//              ACTUAL.LM_SALES_LP AS LM_SALES_LP,
                ACTUAL.P3M_SALES AS P3M_SALES,		--//              ACTUAL.P3M_SALES AS P3M_SALES,
                ACTUAL.P3M_QTY AS P3M_QTY,		--//              ACTUAL.P3M_QTY AS P3M_QTY,
                ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,		--//              ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,
                ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,		--//              ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,
                ACTUAL.F3M_SALES AS F3M_SALES,		--//              ACTUAL.F3M_SALES AS F3M_SALES,
                ACTUAL.F3M_QTY AS F3M_QTY,		--//              ACTUAL.F3M_QTY AS F3M_QTY,
                ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,		--//              ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,
                ACTUAL.P6M_SALES AS P6M_SALES,		--//              ACTUAL.P6M_SALES AS P6M_SALES,
                ACTUAL.P6M_QTY AS P6M_QTY,		--//              ACTUAL.P6M_QTY AS P6M_QTY,
                ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,		--//              ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,
                ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,		--//              ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,
                ACTUAL.P12M_SALES AS P12M_SALES,		--//              ACTUAL.P12M_SALES AS P12M_SALES,
                ACTUAL.P12M_QTY AS P12M_QTY,		--//              ACTUAL.P12M_QTY AS P12M_QTY,
                ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,		--//              ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,
                ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,		--//              ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,
                COALESCE(ACTUAL.LM_SALES_FLAG,'N') AS LM_SALES_FLAG,		--//              COALESCE(ACTUAL.LM_SALES_FLAG,'N') AS LM_SALES_FLAG,
                COALESCE(ACTUAL.P3M_SALES_FLAG,'N') AS P3M_SALES_FLAG,		--//              COALESCE(ACTUAL.P3M_SALES_FLAG,'N') AS P3M_SALES_FLAG,
                COALESCE(ACTUAL.P6M_SALES_FLAG,'N') AS P6M_SALES_FLAG,		--//              COALESCE(ACTUAL.P6M_SALES_FLAG,'N') AS P6M_SALES_FLAG,
                COALESCE(ACTUAL.P12M_SALES_FLAG,'N') AS P12M_SALES_FLAG,		--//              COALESCE(ACTUAL.P12M_SALES_FLAG,'N') AS P12M_SALES_FLAG,
                'Y' AS MDP_FLAG,
                100 AS TARGET_COMPLAINCE
            FROM ITG_PH_RE_MSL_LIST TARGET		--// 		FROM OS_ITG.ITG_PH_RE_MSL_LIST TARGET
            LEFT JOIN (SELECT * FROM WKS_PHILIPPINES_REGIONAL_SELLOUT_ACTUALS) ACTUAL		--//         LEFT JOIN (SELECT * FROM OS_WKS.WKS_PHILIPPINES_REGIONAL_SELLOUT_ACTUALS) ACTUAL
                ON TARGET.FISC_PER = ACTUAL.MNTH_ID		--//                ON TARGET.FISC_PER = ACTUAL.MNTH_ID
                AND UPPER(LTRIM(TARGET.DISTRIBUTOR_CODE,'0')) = UPPER(LTRIM(ACTUAL.DISTRIBUTOR_CODE,'0'))		--//               AND UPPER(ltrim(TARGET.DISTRIBUTOR_CODE,'0')) = UPPER(ltrim(ACTUAL.DISTRIBUTOR_CODE,'0'))
                AND UPPER(LTRIM(TARGET.STORE_CODE,'0')) = UPPER(LTRIM(ACTUAL.STORE_CODE,'0'))		--//               AND UPPER(ltrim(TARGET.STORE_CODE,'0')) = UPPER(ltrim(ACTUAL.STORE_CODE,'0'))
                AND UPPER(LTRIM(TARGET.MASTER_CODE,'0')) = UPPER(LTRIM(ACTUAL.MASTER_CODE,'0'))		--// 			  AND UPPER(ltrim(TARGET.MASTER_CODE,'0')) = UPPER(ltrim(ACTUAL.MASTER_CODE,'0'))
                AND UPPER(LTRIM(TARGET.CUSTOMER_L0,'0')) = UPPER(LTRIM(ACTUAL.SOLD_TO_CODE,'0'))		--//               AND UPPER(ltrim(TARGET.CUSTOMER_L0,'0')) = UPPER(ltrim(ACTUAL.SOLD_TO_CODE,'0'))
            LEFT JOIN (SELECT DISTINCT ITG_MDS_PH_LAV_PRODUCT.ITEM_CD,		--//         LEFT JOIN (SELECT DISTINCT itg_mds_ph_lav_product.item_cd,
                            ITG_MDS_PH_LAV_PRODUCT.ITEM_NM,		--//                           itg_mds_ph_lav_product.item_nm,
                            ITG_MDS_PH_LAV_PRODUCT.SCARD_FRANCHISE_DESC,		--//                           itg_mds_ph_lav_product.scard_franchise_desc,
                            ITG_MDS_PH_LAV_PRODUCT.SCARD_BRAND_DESC,		--//                           itg_mds_ph_lav_product.scard_brand_desc,
                            ITG_MDS_PH_LAV_PRODUCT.SCARD_VARIENT_DESC,		--//                           itg_mds_ph_lav_product.scard_varient_desc,
                            ITG_MDS_PH_LAV_PRODUCT.SCARD_PUT_UP_DESC		--//                           itg_mds_ph_lav_product.scard_put_up_desc
                    FROM ITG_MDS_PH_LAV_PRODUCT		--//                    FROM os_itg.itg_mds_ph_lav_product
                    WHERE UPPER(ITG_MDS_PH_LAV_PRODUCT.ACTIVE::TEXT) = 'Y'::CHARACTER VARYING::TEXT) IMPLP		--//                    WHERE UPPER(itg_mds_ph_lav_product.active::TEXT) = 'Y'::CHARACTER VARYING::TEXT) IMPLP
                    ON LTRIM (COALESCE(ACTUAL.MAPPED_SKU_CD::TEXT, TARGET.MAPPED_SKU_CD::TEXT),'0'::CHARACTER VARYING::TEXT) = LTRIM (IMPLP.item_cd::TEXT,'0'::CHARACTER VARYING::TEXT)		--// 				   ON LTRIM (COALESCE(ACTUAL.MAPPED_SKU_CD::TEXT, TARGET.MAPPED_SKU_CD::TEXT),'0'::CHARACTER VARYING::TEXT) = LTRIM (IMPLP.item_cd::TEXT,'0'::CHARACTER VARYING::TEXT)

    ----------------customer hierarchy------------------------------
            LEFT JOIN (select * from customer_hierarchy) CUSTOMER 
            ON LTRIM (COALESCE(TARGET.CUSTOMER_L0, ACTUAL.SOLD_TO_CODE),'0') = LTRIM (CUSTOMER.SAP_CUST_ID,'0')
            AND CUSTOMER.RANK = 1

    ----------------product hierarchy------------------------------
        LEFT JOIN (select * from product_heirarchy) PRODUCT 
        ON LTRIM (COALESCE(ACTUAL.MAPPED_SKU_CD, TARGET.MAPPED_SKU_CD),'0') = LTRIM (PRODUCT.SAP_MATL_NUM,'0') 
        AND PRODUCT.RANK = 1 ) MDP,	
        (SELECT DISTINCT "cluster"
        FROM EDW_COMPANY_DIM		--//       FROM RG_EDW.EDW_COMPANY_DIM
        WHERE CTRY_GROUP = 'Philippines') COM
    WHERE FISC_PER <= (SELECT MAX(MNTH_ID)
                    FROM WKS_PHILIPPINES_REGIONAL_SELLOUT_ACTUALS)	--//                    FROM OS_WKS.WKS_PHILIPPINES_REGIONAL_SELLOUT_ACTUALS));
),

ph_rpt_retail_excellence_non_mdp as 
(
    SELECT DISTINCT NON_MDP.*,		--// (SELECT DISTINCT NON_MDP.*,
                 COM.*,		--//                  COM.*,
                 SYSDATE() AS CRT_DTTM		--// SYSDATE
    FROM (SELECT CAST(ACTUAL.YEAR AS numeric(18,0) ) AS YEAR,		--// INTEGER // FROM (SELECT CAST(ACTUAL.YEAR AS numeric(18,0) ) AS YEAR,
                CAST(ACTUAL.MNTH_ID AS numeric(18,0) ) AS MNTH_ID,		--// INTEGER //              CAST(ACTUAL.MNTH_ID AS numeric(18,0) ) AS MNTH_ID,
                COALESCE(ACTUAL.CNTRY_NM, 'Philippines') AS MARKET,		--// 			 COALESCE(ACTUAL.CNTRY_NM, 'Philippines') AS MARKET,
                COALESCE(ACTUAL.DATA_SOURCE, STORE_DET.DATA_SRC) AS DATA_SRC,		--// 			 COALESCE(ACTUAL.DATA_SOURCE, STORE_DET.DATA_SRC) AS DATA_SRC,
                COALESCE(STORE_DET.CHANNEL, ACTUAL.CHANNEL) AS CHANNEL_NAME,		--//              COALESCE(STORE_DET.CHANNEL, ACTUAL.CHANNEL) AS CHANNEL_NAME,
                COALESCE(STORE_DET.CUSTOMER_L0, ACTUAL.SOLD_TO_CODE) AS SOLD_TO_CODE,		--//              COALESCE(STORE_DET.CUSTOMER_L0, ACTUAL.SOLD_TO_CODE) AS SOLD_TO_CODE,
                COALESCE(STORE_DET.DISTRIBUTOR_CODE, ACTUAL.DISTRIBUTOR_CODE) AS DISTRIBUTOR_CODE,		--//              COALESCE(STORE_DET.DISTRIBUTOR_CODE, ACTUAL.DISTRIBUTOR_CODE) AS DISTRIBUTOR_CODE,
                COALESCE(STORE_DET.DISTRIBUTOR_NAME, ACTUAL.DISTRIBUTOR_NAME) AS DISTRIBUTOR_NAME,		--// 			 COALESCE(STORE_DET.DISTRIBUTOR_NAME, ACTUAL.DISTRIBUTOR_NAME) AS DISTRIBUTOR_NAME,
                STORE_DET.SELL_OUT_CHANNEL AS SELL_OUT_CHANNEL,		--//              STORE_DET.SELL_OUT_CHANNEL AS SELL_OUT_CHANNEL,
                COALESCE(STORE_DET.RETAIL_ENVIRONMENT, ACTUAL.RETAIL_ENVIRONMENT) AS RETAIL_ENVIRONMENT,		--// 			 COALESCE(STORE_DET.RETAIL_ENVIRONMENT, ACTUAL.RETAIL_ENVIRONMENT) AS RETAIL_ENVIRONMENT,
                COALESCE(STORE_DET.STORE_CODE, ACTUAL.STORE_CODE) AS STORE_CODE,		--//              COALESCE(STORE_DET.STORE_CODE, ACTUAL.STORE_CODE) AS STORE_CODE,
                COALESCE(STORE_DET.STORE_NAME, ACTUAL.STORE_NAME) AS STORE_NAME,		--//              COALESCE(STORE_DET.STORE_NAME, ACTUAL.STORE_NAME) AS STORE_NAME,
                COALESCE(ACTUAL.STORE_TYPE, 'NA') AS STORE_TYPE,		--//              COALESCE(ACTUAL.STORE_TYPE, 'NA') AS STORE_TYPE,
                COALESCE(STORE_DET.REGION, ACTUAL.REGION) AS REGION,		--// 			 COALESCE(STORE_DET.REGION, ACTUAL.REGION) AS REGION,
                STORE_DET.STORE_ADDRESS,		--//              STORE_DET.STORE_ADDRESS,
                STORE_DET.STORE_POSTCODE AS POST_CODE,		--//              STORE_DET.STORE_POSTCODE AS POST_CODE,
                COALESCE(STORE_DET."Area/Zone/Province", ACTUAL.ZONE_OR_AREA) AS ZONE_NAME,		--//              COALESCE(STORE_DET."Area/Zone/Province", ACTUAL.ZONE_OR_AREA) AS ZONE_NAME,
                STORE_DET.CITY AS CITY,		--//              STORE_DET.CITY AS CITY,
                ACTUAL.MASTER_CODE AS PRODUCT_CODE,		--// 			 ACTUAL.MASTER_CODE AS PRODUCT_CODE,
                ACTUAL.MSL_PRODUCT_DESC AS PRODUCT_NAME,		--// 			 ACTUAL.MSL_PRODUCT_DESC AS PRODUCT_NAME,
                ACTUAL.MAPPED_SKU_CD AS MAPPED_SKU_CD,		--// 			 ACTUAL.MAPPED_SKU_CD AS MAPPED_SKU_CD,
                'Philippines' AS PROD_HIER_L1,
                NULL AS PROD_HIER_L2,
                IMPLP.SCARD_FRANCHISE_DESC AS PROD_HIER_L3,		--//              IMPLP.scard_franchise_desc AS PROD_HIER_L3,
                IMPLP.SCARD_BRAND_DESC AS PROD_HIER_L4,		--//              IMPLP.scard_brand_desc AS PROD_HIER_L4,
                IMPLP.SCARD_VARIENT_DESC AS PROD_HIER_L5,		--//              IMPLP.scard_varient_desc AS PROD_HIER_L5,
                IMPLP.SCARD_PUT_UP_DESC AS PROD_HIER_L6,		--//              IMPLP.scard_put_up_desc AS PROD_HIER_L6,
                NULL AS PROD_HIER_L7,
                NULL AS PROD_HIER_L8,
                NULL AS PROD_HIER_L9,
                COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,		--// 			 COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,
                COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,
                COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,
                COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,
                COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,
                COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,
                COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,
                COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,
                COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,
                COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,
                COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,
                COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,
                TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,
                TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,
                TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,
                COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,
                COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,		--//              COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,
                TRIM(NVL (NULLIF(PRODUCT.EAN,''),'NA')) AS EAN,		--//              TRIM(NVL (NULLIF(PRODUCT.EAN,''),'NA')) AS EAN,
                TRIM(NVL (NULLIF(PRODUCT.SAP_MATL_NUM,''),'NA')) AS SKU_CODE,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MATL_NUM,''),'NA')) AS SKU_CODE,
                TRIM(NVL (NULLIF(PRODUCT.SAP_MAT_DESC,''),'NA')) AS SKU_DESCRIPTION,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MAT_DESC,''),'NA')) AS SKU_DESCRIPTION,
                TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,
                TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,
                TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,
                TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,
                TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,
                COALESCE(ACTUAL.PKA_PRODUCT_KEY,PRODUCT.PKA_PRODUCT_KEY) AS PKA_PRODUCT_KEY,		--//              COALESCE(ACTUAL.PKA_PRODUCT_KEY,PRODUCT.PKA_PRODUCT_KEY) AS PKA_PRODUCT_KEY,
                COALESCE(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION) AS PKA_PRODUCT_KEY_DESCRIPTION,		--//              COALESCE(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION) AS PKA_PRODUCT_KEY_DESCRIPTION,
                ACTUAL.CM_SALES AS SALES_VALUE,		--//              ACTUAL.CM_SALES AS SALES_VALUE,
                ACTUAL.CM_SALES_QTY AS SALES_QTY,		--//              ACTUAL.CM_SALES_QTY AS SALES_QTY,
                ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,		--//              ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,
                ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,		--// 			 ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,
                ACTUAL.LM_SALES AS LM_SALES,		--//              ACTUAL.LM_SALES AS LM_SALES,
                ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,		--//              ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,
                ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,		--//              ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,
                ACTUAL.LM_SALES_LP AS LM_SALES_LP,		--// 			 ACTUAL.LM_SALES_LP AS LM_SALES_LP,
                ACTUAL.P3M_SALES AS P3M_SALES,		--//              ACTUAL.P3M_SALES AS P3M_SALES,
                ACTUAL.P3M_QTY AS P3M_QTY,		--//              ACTUAL.P3M_QTY AS P3M_QTY,
                ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,		--//              ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,
                ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,		--// 			 ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,
                ACTUAL.F3M_SALES AS F3M_SALES,		--//              ACTUAL.F3M_SALES AS F3M_SALES,
                ACTUAL.F3M_QTY AS F3M_QTY,		--//              ACTUAL.F3M_QTY AS F3M_QTY,
                ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,		--//              ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,
                ACTUAL.P6M_SALES AS P6M_SALES,		--//              ACTUAL.P6M_SALES AS P6M_SALES,
                ACTUAL.P6M_QTY AS P6M_QTY,		--//              ACTUAL.P6M_QTY AS P6M_QTY,
                ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,		--//              ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,
                ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,		--// 			 ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,
                ACTUAL.P12M_SALES AS P12M_SALES,		--//              ACTUAL.P12M_SALES AS P12M_SALES,
                ACTUAL.P12M_QTY AS P12M_QTY,		--//              ACTUAL.P12M_QTY AS P12M_QTY,
                ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,		--//              ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,
                ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,		--// 			 ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,
                ACTUAL.LM_SALES_FLAG,		--//              ACTUAL.LM_SALES_FLAG,
                ACTUAL.P3M_SALES_FLAG,		--//              ACTUAL.P3M_SALES_FLAG,
                ACTUAL.P6M_SALES_FLAG,		--//              ACTUAL.P6M_SALES_FLAG,
                ACTUAL.P12M_SALES_FLAG,		--//              ACTUAL.P12M_SALES_FLAG,
                'N' AS MDP_FLAG,
                100 AS TARGET_COMPLAINCE
            FROM (SELECT *
                    FROM WKS_PHILIPPINES_REGIONAL_SELLOUT_ACTUALS A		--//             FROM OS_WKS.WKS_PHILIPPINES_REGIONAL_SELLOUT_ACTUALS A
                    WHERE NOT EXISTS (SELECT 1
                                FROM ITG_PH_RE_MSL_LIST T		--//                               FROM OS_ITG.ITG_PH_RE_MSL_LIST T
                                WHERE A.MNTH_ID = T.FISC_PER		--//                               WHERE A.MNTH_ID = T.FISC_PER
                                AND   UPPER(LTRIM(A.DISTRIBUTOR_CODE,'0')) = UPPER(LTRIM(T.DISTRIBUTOR_CODE,'0'))		--//                               AND   UPPER(ltrim(A.DISTRIBUTOR_CODE,'0')) = UPPER(ltrim(T.DISTRIBUTOR_CODE,'0'))
                                AND   UPPER(LTRIM(A.STORE_CODE,'0')) = UPPER(LTRIM(T.STORE_CODE,'0'))		--//                               AND   UPPER(ltrim(A.STORE_CODE,'0')) = UPPER(ltrim(T.STORE_CODE,'0'))
                                AND   UPPER(LTRIM(A.MASTER_CODE,'0')) = UPPER(LTRIM(T.MASTER_CODE,'0'))		--// 							  AND   UPPER(ltrim(A.MASTER_CODE,'0')) = UPPER(ltrim(T.MASTER_CODE,'0'))
                                AND   UPPER(LTRIM(A.SOLD_TO_CODE,'0')) = UPPER(LTRIM(T.CUSTOMER_L0,'0')))) ACTUAL		--//                               AND   UPPER(ltrim(A.SOLD_TO_CODE,'0')) = UPPER(ltrim(T.CUSTOMER_L0,'0')))) ACTUAL
        LEFT JOIN (SELECT DISTINCT GT.Customer_L0,		--//        LEFT JOIN (SELECT DISTINCT GT."Customer_L0",
                        GT.TRADE_TYPE,		--// 					  GT.trade_type,
                        GT.SALES_GROUP,		--// 					  GT.sales_group,
                        GT.ACCOUNT_GROUP,		--// 					  GT.account_group,
                        GT.DATA_SRC,		--// 					  GT.data_src,
                        GT.CHANNEL,		--// 					  GT.channel,
                        GT.DISTRIBUTOR_CODE,		--// 					  GT.distributor_code,
                        GT.DISTRIBUTOR_NAME|| '#' ||ltrim(GT.distributor_code,'0') AS distributor_name,		--// 					  GT.distributor_name|| '#' ||ltrim(GT.distributor_code,'0') AS distributor_name,
                        GT.PARENT_CUSTOMER,		--// 					  GT.parent_customer,
                        GT.REGION,		--// 					  GT.region,
                        GT."Area/Zone/Province",		--// 					  GT."Area/Zone/Province",
                        GT.CITY,		--// 					  GT.city,
                        GT.SELL_OUT_PARENT_CUSTOMER_L2,		--// 					  GT.Sell_Out_Parent_Customer_L2,
                        GT.SELL_OUT_PARENT_CUSTOMER_L1,		--// 					  GT.Sell_Out_Parent_Customer_L1,
                        GT.SELL_OUT_CHANNEL,		--// 					  GT.sell_out_channel,
                        GT.RETAIL_ENVIRONMENT,		--// 					  GT.retail_environment,
                        GT.STORE_CODE,		--// 					  GT.store_code,
                        GT.STORE_NAME|| '#' ||ltrim(GT.store_code,'0') AS store_name,		--// 					  GT.store_name|| '#' ||ltrim(GT.store_code,'0') AS store_name,
                        GT.STORE_ADDRESS,		--// 					  GT.store_address,
                        GT.STORE_POSTCODE,		--// 					  GT.store_postcode,
                        GT.STORE_LAT,		--// 					  GT.store_lat,
                        GT.STORE_LONG		--// 					  GT.store_long
                FROM ( select * from ((SELECT DISTINCT ltrim(cust_id,'0') AS Customer_L0,
                                            rpt_grp_6_desc AS account_group,
                                            channel_desc AS channel,
                                            ltrim(dstrbtr_grp_cd,'0') AS distributor_code,
                                            MAX(dstrbtr_grp_nm) OVER (PARTITION BY ltrim(dstrbtr_grp_cd,'0') ORDER BY crtd_dttm DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS distributor_name,
                                            upper(ltrim(parent_cust_cd,'0')) AS parent_customer
                                        FROM ITG_MDS_PH_LAV_CUSTOMER WHERE UPPER(active) = 'Y') a		--// 					   FROM OS_ITG.ITG_MDS_PH_LAV_CUSTOMER WHERE UPPER(active) = 'Y') a
                            JOIN (SELECT DISTINCT SOLDTO_CODE,
                                        data_source AS data_src,
                                        MASTER_CODE as msl_product_code,
                                        DISTRIBUTOR_CODE as so_dist_cd
                                    FROM WKS_PHILIPPINES_BASE_RETAIL_EXCELLENCE		--// 									FROM OS_WKS.WKS_PHILIPPINES_BASE_RETAIL_EXCELLENCE
                                    WHERE DATA_SOURCE = 'SELL-OUT') REG_SO
                            ON LTRIM(A.CUSTOMER_L0,'0') = LTRIM(REG_SO.SOLDTO_CODE,'0')		--// 						   ON ltrim(a.Customer_L0,'0') = ltrim(REG_SO.soldto_code,'0')
                            AND LTRIM(A.DISTRIBUTOR_CODE,'0') = LTRIM(REG_SO.SO_DIST_CD,'0')		--// 						  AND ltrim(a.distributor_code,'0') = ltrim(REG_SO.so_dist_cd,'0')
                            JOIN (SELECT DISTINCT rep_grp2_desc AS region,
                                        rep_grp3_desc AS "Area/Zone/Province",
                                        rep_grp5_desc AS city,
                                        sls_dist_desc AS Sell_Out_Parent_Customer_L2,
                                        ltrim(dstrbtr_grp_cd,'0') AS Sell_Out_Parent_Customer_L1,
                                        UPPER(rpt_grp11_desc) AS sell_out_channel,
                                        UPPER(rpt_grp9_desc) AS retail_environment,
                                        ltrim(dstrbtr_cust_id,'0') AS store_code,
                                        MAX(dstrbtr_cust_nm) OVER (PARTITION BY ltrim(dstrbtr_cust_id,'0') ORDER BY crtd_dttm DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS store_name,
                                        address AS store_address,
                                        zip_code AS store_postcode,
                                        latitude::VARCHAR AS store_lat,
                                        longitude::VARCHAR AS store_long,
                                        ROW_NUMBER() OVER (PARTITION BY ltrim(dstrbtr_cust_id,'0') ORDER BY crtd_dttm DESC) AS rno
                                    FROM ITG_MDS_PH_GT_CUSTOMER WHERE UPPER(active) = 'Y') c ON ltrim(a.distributor_code,'0') = ltrim(c.Sell_Out_Parent_Customer_L1,'0')		--// 							   FROM OS_ITG.ITG_MDS_PH_GT_CUSTOMER WHERE UPPER(active) = 'Y') c ON ltrim(a.distributor_code,'0') = ltrim(c.Sell_Out_Parent_Customer_L1,'0')
                            JOIN (SELECT DISTINCT rpt_grp_1_desc AS trade_type,
                                        rpt_grp_12_desc AS sales_group,
                                        parent_cust_cd
                                    FROM ITG_MDS_PH_REF_PARENT_CUSTOMER WHERE UPPER(TRADE_TYPE) = 'GENERAL TRADE' AND UPPER(ACTIVE) = 'Y') B 
                                    ON UPPER(LTRIM(A.PARENT_CUSTOMER,'0')) = UPPER(LTRIM(B.PARENT_CUST_CD,'0'))) where C.RNO = 1) GT		--// 							   FROM OS_ITG.ITG_MDS_PH_REF_PARENT_CUSTOMER WHERE UPPER(trade_type) = 'GENERAL TRADE' AND UPPER(active) = 'Y') b ON upper(ltrim(a.parent_customer,'0')) = upper(ltrim(b.parent_cust_cd,'0'))) where c.rno = 1) GT
                UNION ALL
                    SELECT DISTINCT MT.Customer_L0,		--// 				SELECT DISTINCT MT."Customer_L0",
                            MT.TRADE_TYPE,		--// 						MT.trade_type,
                            MT.SALES_GROUP,		--// 						MT.sales_group,
                            MT.ACCOUNT_GROUP,		--// 						MT.account_group,
                            MT.DATA_SRC,		--// 						MT.data_src,
                            MT.CHANNEL,		--// 						MT.channel,
                            MT.DISTRIBUTOR_CODE,		--// 						MT.distributor_code,
                            MT.DISTRIBUTOR_NAME,		--// 						MT.distributor_name,
                            MT.PARENT_CUSTOMER,		--// 						MT.parent_customer,
                            MT.REGION,		--// 						MT.region,
                            MT."Area/Zone/Province",		--// 						MT."Area/Zone/Province",
                            MT.CITY,		--// 						MT.city,
                            MT.SELL_OUT_PARENT_CUSTOMER_L2,		--// 						MT.Sell_Out_Parent_Customer_L2,
                            MT.SELL_OUT_PARENT_CUSTOMER_L1,		--// 						MT.Sell_Out_Parent_Customer_L1,
                            MT.SELL_OUT_CHANNEL,		--// 						MT.sell_out_channel,
                            MT.RETAIL_ENVIRONMENT,		--// 						MT.retail_environment,
                            MT.STORE_CODE,		--// 						MT.store_code,
                            MT.STORE_NAME|| '#' ||ltrim(MT.store_code,'0') AS store_name,		--// 						MT.store_name|| '#' ||ltrim(MT.store_code,'0') AS store_name,
                            MT.STORE_ADDRESS,		--// 						MT.store_address,
                            MT.STORE_POSTCODE,		--// 						MT.store_postcode,
                            MT.STORE_LAT,		--// 						MT.store_lat,
                            MT.STORE_LONG		--// 						MT.store_long
                    FROM ( select * from ((SELECT DISTINCT ltrim(cust_id,'0') AS Customer_L0,
                                                rpt_grp_6_desc AS account_group,
                                                channel_desc AS channel,
                                                upper(ltrim(parent_cust_cd,'0')) AS parent_customer
                                            FROM ITG_MDS_PH_LAV_CUSTOMER WHERE UPPER(active) = 'Y') a		--// 						  FROM OS_ITG.ITG_MDS_PH_LAV_CUSTOMER WHERE UPPER(active) = 'Y') a
                                JOIN (SELECT DISTINCT SOLDTO_CODE,
                                            data_source AS data_src,
                                            MASTER_CODE AS msl_product_code,
                                            DISTRIBUTOR_CODE,
                                            DISTRIBUTOR_NAME
                                        FROM WKS_PHILIPPINES_BASE_RETAIL_EXCELLENCE		--// 								FROM OS_WKS.WKS_PHILIPPINES_BASE_RETAIL_EXCELLENCE
                                        WHERE DATA_SOURCE = 'POS') REG_SO
                                ON LTRIM(A.CUSTOMER_L0,'0') = LTRIM(REG_SO.SOLDTO_CODE,'0')		--// 							  ON ltrim(a.Customer_L0,'0') = ltrim(REG_SO.soldto_code,'0')
                                JOIN (SELECT DISTINCT region_nm AS region,
                                            prov_nm AS "Area/Zone/Province",
                                            mncplty_nm AS city,
                                            NULL::VARCHAR AS Sell_Out_Parent_Customer_L2,
                                            jj_sold_to AS Sell_Out_Parent_Customer_L1,
                                            UPPER(store_mtrx) AS sell_out_channel,
                                            UPPER(chnl_sub_grp_cd) AS retail_environment,
                                            ltrim(SPLIT_PART(code, '-', 2),'0') AS store_code,
                                            MAX(brnch_nm) OVER (PARTITION BY ltrim(SPLIT_PART(code, '-', 2),'0') ORDER BY crtd_dttm DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS store_name,
                                            (address1||address2) AS store_address,
                                            zip_code AS store_postcode,
                                            latitude::VARCHAR AS store_lat,
                                            longitude::VARCHAR AS store_long,
                                            ROW_NUMBER() OVER (PARTITION BY ltrim(SPLIT_PART(code, '-', 2),'0') ORDER BY crtd_dttm DESC) AS rno
                                        FROM ITG_MDS_PH_POS_CUSTOMERS WHERE UPPER(active) = 'Y') c ON ltrim(a.Customer_L0,'0') = ltrim(c.Sell_Out_Parent_Customer_L1,'0')		--// 								  FROM OS_ITG.ITG_MDS_PH_POS_CUSTOMERS WHERE UPPER(active) = 'Y') c ON ltrim(a.Customer_L0,'0') = ltrim(c.Sell_Out_Parent_Customer_L1,'0')
                                JOIN (SELECT DISTINCT rpt_grp_1_desc AS trade_type,
                                            rpt_grp_12_desc AS sales_group,
                                            parent_cust_cd
                                    FROM ITG_MDS_PH_REF_PARENT_CUSTOMER		--// 								  FROM OS_ITG.ITG_MDS_PH_REF_PARENT_CUSTOMER
                                    WHERE UPPER(TRADE_TYPE) = 'NATIONAL KEY ACCOUNT' AND UPPER(ACTIVE) = 'Y') B 
                                    ON UPPER(LTRIM(A.PARENT_CUSTOMER,'0')) = UPPER(LTRIM(B.PARENT_CUST_CD,'0')))where C.RNO = 1) MT) STORE_DET		--// 								  WHERE UPPER(trade_type) = 'NATIONAL KEY ACCOUNT' AND UPPER(active) = 'Y') b ON upper(ltrim(a.parent_customer,'0')) = upper(ltrim(b.parent_cust_cd,'0')))where c.rno = 1) MT) STORE_DET
                                    ON LTRIM(STORE_DET.STORE_CODE,'0') = LTRIM(ACTUAL.STORE_CODE,'0')		--// 								  ON ltrim(STORE_DET.STORE_CODE,'0') = ltrim(ACTUAL.STORE_CODE,'0')
                                    AND LTRIM(STORE_DET.DISTRIBUTOR_CODE,'0') = LTRIM(ACTUAL.DISTRIBUTOR_CODE,'0')		--// 								  AND ltrim(STORE_DET.DISTRIBUTOR_CODE,'0') = ltrim(ACTUAL.DISTRIBUTOR_CODE,'0')
                                    AND LTRIM(STORE_DET.CUSTOMER_L0,'0') = LTRIM(ACTUAL.SOLD_TO_CODE,'0')		--// 								  AND ltrim(STORE_DET.Customer_L0,'0') = ltrim(ACTUAL.SOLD_TO_CODE,'0')
            LEFT JOIN (SELECT DISTINCT ITG_MDS_PH_LAV_PRODUCT.ITEM_CD,		--//         LEFT JOIN (SELECT DISTINCT itg_mds_ph_lav_product.item_cd,
                            ITG_MDS_PH_LAV_PRODUCT.ITEM_NM,		--//                           itg_mds_ph_lav_product.item_nm,
                            ITG_MDS_PH_LAV_PRODUCT.SCARD_FRANCHISE_DESC,		--//                           itg_mds_ph_lav_product.scard_franchise_desc,
                            ITG_MDS_PH_LAV_PRODUCT.SCARD_BRAND_DESC,		--//                           itg_mds_ph_lav_product.scard_brand_desc,
                            ITG_MDS_PH_LAV_PRODUCT.SCARD_VARIENT_DESC,		--//                           itg_mds_ph_lav_product.scard_varient_desc,
                            ITG_MDS_PH_LAV_PRODUCT.SCARD_PUT_UP_DESC		--//                           itg_mds_ph_lav_product.scard_put_up_desc
                    FROM ITG_MDS_PH_LAV_PRODUCT		--//                    FROM os_itg.itg_mds_ph_lav_product
                    WHERE UPPER(ITG_MDS_PH_LAV_PRODUCT.ACTIVE::TEXT) = 'Y'::CHARACTER VARYING::TEXT) IMPLP		--//                    WHERE UPPER(itg_mds_ph_lav_product.active::TEXT) = 'Y'::CHARACTER VARYING::TEXT) IMPLP
                    ON LTRIM (ACTUAL.MAPPED_SKU_CD::TEXT,'0'::CHARACTER VARYING::TEXT) = LTRIM (IMPLP.ITEM_CD::TEXT,'0'::CHARACTER VARYING::TEXT)		--// 				   ON LTRIM (ACTUAL.MAPPED_SKU_CD::TEXT,'0'::CHARACTER VARYING::TEXT) = LTRIM (IMPLP.item_cd::TEXT,'0'::CHARACTER VARYING::TEXT)

----------------customer hierarchy------------------------------
        LEFT JOIN (select * from customer_hierarchy) CUSTOMER 
        ON LTRIM ( ACTUAL.SOLD_TO_CODE,'0') = LTRIM (CUSTOMER.SAP_CUST_ID,'0')
        AND CUSTOMER.RANK = 1
 
----------------product hierarchy------------------------------
        LEFT JOIN (select * from product_heirarchy) PRODUCT 
        ON LTRIM (ACTUAL.MAPPED_SKU_CD,'0') = LTRIM (PRODUCT.SAP_MATL_NUM,'0') 
        AND PRODUCT.RANK = 1 ) NON_MDP, 
        (SELECT DISTINCT "cluster"
        FROM EDW_COMPANY_DIM		--//       FROM RG_EDW.EDW_COMPANY_DIM
        WHERE CTRY_GROUP = 'Philippines') COM
),

ph_rpt_retail_excellence as 
(
    select * from ph_rpt_retail_excellence_mdp
    union
    select * from ph_rpt_retail_excellence_non_mdp
),

final as 
(
    select fisc_yr :: numeric(18,0) as fisc_yr,
    fisc_per :: varchar(22) as fisc_per,
    market :: varchar(30) as market,
    data_src :: varchar(14) as data_src,
    channel_name :: varchar(255) as channel_name,
    sold_to_code :: varchar(255) as sold_to_code,
    distributor_code :: varchar(100) as distributor_code,
    distributor_name :: varchar(356) as distributor_name,
    sell_out_channel :: varchar(382) as sell_out_channel,
    retail_environment :: varchar(382) as retail_environment,
    store_code :: varchar(100) as store_code,
    store_name :: varchar(601) as store_name,
    store_type :: varchar(255) as store_type,
    region :: varchar(255) as region,
    store_address :: varchar(510) as store_address,
    post_code :: varchar(100) as post_code,
    zone_name :: varchar(255) as zone_name,
    city :: varchar(255) as city,
    product_code :: varchar(200) as product_code,
    product_name :: varchar(300) as product_name,
    mapped_sku_cd :: varchar(40) as mapped_sku_cd,
    prod_hier_l1 :: varchar(11) as prod_hier_l1,
    prod_hier_l2 :: varchar(1) as prod_hier_l2,
    prod_hier_l3 :: varchar(255) as prod_hier_l3,
    prod_hier_l4 :: varchar(255) as prod_hier_l4,
    prod_hier_l5 :: varchar(255) as prod_hier_l5,
    prod_hier_l6 :: varchar(255) as prod_hier_l6,
    prod_hier_l7 :: varchar(1) as prod_hier_l7,
    prod_hier_l8 :: varchar(1) as prod_hier_l8,
    prod_hier_l9 :: varchar(1) as prod_hier_l9,
    customer_segment_key :: varchar(12) as customer_segment_key,
    customer_segment_description :: varchar(50) as customer_segment_description,
    sap_customer_channel_key :: varchar(12) as sap_customer_channel_key,
    sap_customer_channel_description :: varchar(75) as sap_customer_channel_description,
    sap_customer_sub_channel_key :: varchar(12) as sap_customer_sub_channel_key,
    sap_sub_channel_description :: varchar(75) as sap_sub_channel_description,
    sap_parent_customer_key :: varchar(12) as sap_parent_customer_key,
    sap_parent_customer_description :: varchar(75) as sap_parent_customer_description,
    sap_banner_key :: varchar(12) as sap_banner_key,
    sap_banner_description :: varchar(75) as sap_banner_description,
    sap_banner_format_key :: varchar(12) as sap_banner_format_key,
    sap_banner_format_description :: varchar(75) as sap_banner_format_description,
    customer_name :: varchar(100) as customer_name,
    customer_code :: varchar(10) as customer_code,
    sap_prod_sgmt_cd :: varchar(18) as sap_prod_sgmt_cd,
    sap_prod_sgmt_desc :: varchar(100) as sap_prod_sgmt_desc,
    sap_base_prod_desc :: varchar(100) as sap_base_prod_desc,
    sap_mega_brnd_desc :: varchar(100) as sap_mega_brnd_desc,
    sap_brnd_desc :: varchar(100) as sap_brnd_desc,
    sap_vrnt_desc :: varchar(100) as sap_vrnt_desc,
    sap_put_up_desc :: varchar(100) as sap_put_up_desc,
    sap_grp_frnchse_cd :: varchar(18) as sap_grp_frnchse_cd,
    sap_grp_frnchse_desc :: varchar(100) as sap_grp_frnchse_desc,
    sap_frnchse_cd :: varchar(18) as sap_frnchse_cd,
    sap_frnchse_desc :: varchar(100) as sap_frnchse_desc,
    sap_prod_frnchse_cd :: varchar(18) as sap_prod_frnchse_cd,
    sap_prod_frnchse_desc :: varchar(100) as sap_prod_frnchse_desc,
    sap_prod_mjr_cd :: varchar(18) as sap_prod_mjr_cd,
    sap_prod_mjr_desc :: varchar(100) as sap_prod_mjr_desc,
    sap_prod_mnr_cd :: varchar(18) as sap_prod_mnr_cd,
    sap_prod_mnr_desc :: varchar(100) as sap_prod_mnr_desc,
    sap_prod_hier_cd :: varchar(18) as sap_prod_hier_cd,
    sap_prod_hier_desc :: varchar(100) as sap_prod_hier_desc,
    global_product_franchise :: varchar(30) as global_product_franchise,
    global_product_brand :: varchar(30) as global_product_brand,
    global_product_sub_brand :: varchar(100) as global_product_sub_brand,
    global_product_variant :: varchar(100) as global_product_variant,
    global_product_segment :: varchar(50) as global_product_segment,
    global_product_subsegment :: varchar(100) as global_product_subsegment,
    global_product_category :: varchar(50) as global_product_category,
    global_product_subcategory :: varchar(50) as global_product_subcategory,
    global_put_up_description :: varchar(100) as global_put_up_description,
    ean :: varchar(40) as ean,
    sku_code :: varchar(40) as sku_code,
    sku_description :: varchar(100) as sku_description,
    pka_franchise_desc :: varchar(30) as pka_franchise_desc,
    pka_brand_desc :: varchar(30) as pka_brand_desc,
    pka_sub_brand_desc :: varchar(30) as pka_sub_brand_desc,
    pka_variant_desc :: varchar(30) as pka_variant_desc,
    pka_sub_variant_desc :: varchar(30) as pka_sub_variant_desc,
    pka_product_key :: varchar(68) as pka_product_key,
    pka_product_key_description :: varchar(255) as pka_product_key_description,
    sales_value :: numeric(38,6) as sales_value,
    sales_qty :: numeric(38,6) as sales_qty,
    avg_sales_qty :: numeric(38,6) as avg_sales_qty,
    sales_value_list_price :: numeric(38,12) as sales_value_list_price,
    lm_sales :: numeric(38,6) as lm_sales,
    lm_sales_qty :: numeric(38,6) as lm_sales_qty,
    lm_avg_sales_qty :: numeric(38,6) as lm_avg_sales_qty,
    lm_sales_lp :: numeric(38,12) as lm_sales_lp,
    p3m_sales :: numeric(38,6) as p3m_sales,
    p3m_qty :: numeric(38,6) as p3m_qty,
    p3m_avg_qty :: numeric(38,6) as p3m_avg_qty,
    p3m_sales_lp :: numeric(38,12) as p3m_sales_lp,
    f3m_sales :: numeric(38,6) as f3m_sales,
    f3m_qty :: numeric(38,6) as f3m_qty,
    f3m_avg_qty :: numeric(38,6) as f3m_avg_qty,
    p6m_sales :: numeric(38,6) as p6m_sales,
    p6m_qty :: numeric(38,6) as p6m_qty,
    p6m_avg_qty :: numeric(38,6) as p6m_avg_qty,
    p6m_sales_lp :: numeric(38,12) as p6m_sales_lp,
    p12m_sales :: numeric(38,6) as p12m_sales,
    p12m_qty :: numeric(38,6) as p12m_qty,
    p12m_avg_qty :: numeric(38,6) as p12m_avg_qty,
    p12m_sales_lp :: numeric(38,12) as p12m_sales_lp,
    lm_sales_flag :: varchar(1) as lm_sales_flag,
    p3m_sales_flag :: varchar(1) as p3m_sales_flag,
    p6m_sales_flag :: varchar(1) as p6m_sales_flag,
    p12m_sales_flag :: varchar(1) as p12m_sales_flag,
    mdp_flag :: varchar(1) as mdp_flag,
    target_complaince :: numeric(18,0) as target_complaince,
    "cluster" :: varchar(100) as "cluster",
    crtd_dttm :: timestamp without time zone as crtd_dttm
    from ph_rpt_retail_excellence
)

--final select

select * from final 