with source as(
    select * from {{ source('thasdl_raw', 'sdl_mds_th_cbd_item_master') }}
),
transformed as(
    select
        trim(franchise) as franchise,
        trim("sub brand") as "sub brand",
        trim(variant) as variant,
        trim("main brand") as "main brand",
        trim("sap code 1") as "sap code 1",
        trim("sap code 2") as "sap code 2",
        trim("sap code 3") as "sap code 3",
        trim("sap code 4") as "sap code 4",
        trim("hs code") as "hs code",
        trim("2022/suggested hs code") as "2022/suggested hs code",
        trim("CAT. (ext)") as "CAT. (ext)",
        trim("individual barcode") as "individual barcode",
        trim("dksh code") as "dksh code",
        trim("dksh code 1") as "dksh code 1",
        trim("dksh code 2") as "dksh code 2",
        trim("product description") as "product description",
        trim("product name") as "product name",
        trim("active 2022") as "active 2022",
        trim("status 23") as "status 23",
        trim("new sap jnj") as "new sap jnj",
        trim("new description jnj") as "new description jnj",
        trim("status 2023") as "status 2023",
        trim("stock ea") as "stock ea",
        trim("unit per case") as "unit per case",
        trim("stock cse") as "stock cse",
        trim("avg sellout per month") as "avg sellout per month",
        trim(dos) as dos,
        trim("duty fee (int)") as "duty fee (int)",
        trim("tax (int)") as "tax (int)",
        trim(coo_abbrev) as coo_abbrev,
        trim("country of origin") as "country of origin",
        trim(gts) as gts,
        trim(niv) as niv,
        trim("duty fee (ext)") as "duty fee (ext)",
        trim("tax (ext)") as "tax (ext)",
        trim(comments) as comments,
        trim("ccd comments") as "ccd comments",
        current_timestamp()::timestampntz(9) as crt_dttm,
        current_timestamp()::timestampntz(9) as updt_dtt
    from source
),
final as(
    select
    franchise::varchar(200) as franchise,
	"sub brand"::varchar(200) as "sub brand",
	variant::varchar(200) as variant,
	"main brand"::varchar(200) as "main brand",
	"sap code 1"::number(28,0) as "sap code 1",
	"sap code 2"::number(28,0) as "sap code 2",
	"sap code 3"::number(28,0) as "sap code 3",
	"sap code 4"::number(28,0) as "sap code 4",
	"hs code"::varchar(200) as "hs code",
	"2022/suggested hs code"::varchar(200) as "2022/suggested hs code",
	"CAT. (ext)"::varchar(200) as "CAT. (ext)",
	"individual barcode"::number(28,0) as "individual barcode",
	"dksh code"::varchar(200) as "dksh code",
	"dksh code 1"::number(28,0) as "dksh code 1",
	"dksh code 2"::number(28,0) as "dksh code 2",
	"product description"::varchar(200) as "product description",
	"product name"::varchar(200) as "product name",
	"active 2022"::varchar(200) as "active 2022",
	"status 23"::varchar(200) as "status 23",
	"new sap jnj"::varchar(200) as "new sap jnj",
	"new description jnj"::varchar(200) as "new description jnj",
	"status 2023"::varchar(200) as "status 2023",
	"stock ea"::number(28,0) as "stock ea",
	"unit per case"::number(28,0) as "unit per case",
	"stock cse"::number(28,7) as "stock cse",
	"avg sellout per month"::number(28,7) "avg sellout per month",
	dos::varchar(200) as dos,
	"duty fee (int)"::number(28,2) as "duty fee (int)",
	"tax (int)"::number(28,3) as "tax (int)",
	coo_abbrev::varchar(200) as coo_abbrev,
	"country of origin"::varchar(200) as "country of origin",
	gts::number(28,7) as gts,
	niv::number(28,7) as niv,
	"duty fee (ext)"::number(28,2) as "duty fee (ext)",
	"tax (ext)"::number(28,1) as "tax (ext)",
	comments::varchar(200) as comments,
	"ccd comments"::varchar(262) as "ccd comments",
    crt_dttm as crt_dttm,
    updt_dtt as updt_dtt
    from transformed
)
select * from final