DELETE FROM NA_ITG.ITG_KR_GT_DPT_DAISO
WHERE (SUB_CUSTOMER_CODE, CUSTOMER_CODE) IN (
        SELECT CODE AS SUB_CUSTOMER_CODE,
            CAST(customer_code AS VARCHAR) AS CUSTOMER_CODE
        FROM NA_SDL.SDL_MDS_KR_SUB_CUSTOMER_MASTER
        WHERE UPPER(TRIM(RETAILER_CODE)) = 'DEPT & DAISO'
    );
INSERT INTO NA_ITG.ITG_KR_GT_DPT_DAISO
SELECT 'KR',
    NAME AS SUB_CUSTOMER_NAME,
    CODE AS SUB_CUSTOMER_CODE,
    CAST(customer_code AS VARCHAR) AS CUSTOMER_CODE,
    SYSDATE
FROM NA_SDL.SDL_MDS_KR_SUB_CUSTOMER_MASTER
WHERE UPPER(TRIM(RETAILER_CODE)) = 'DEPT & DAISO';