DELETE FROM NA_ITG.ITG_MDS_KR_PRODUCT_HIERARCHY
WHERE PRFT_CTR IN (SELECT DISTINCT CODE FROM NA_SDL.SDL_MDS_KR_PRODUCT_HIERARCHY);

INSERT INTO NA_ITG.ITG_MDS_KR_PRODUCT_HIERARCHY
 (SELECT CODE AS PRFT_CTR,
		 LOCAL_BRAND_CLASSIFICATION_CODE,
		 SYSDATE as CRTD_DTTM
  FROM  NA_SDL.SDL_MDS_KR_PRODUCT_HIERARCHY );

