with edw_all_distributor_lppb_fact as(
	select * from {{ ref('idnedw_integration__edw_all_distributor_lppb_fact') }}
),
EDW_TIME_DIM as(
	select * from {{ source('idnedw_integration', 'edw_time_dim') }}
),
itg_target_dist_brand_channel as(
	select * from {{ ref('idnitg_integration__itg_target_dist_brand_channel') }}
),
edw_distributor_dim as(
	select * from {{ ref('idnedw_integration__edw_distributor_dim') }}
),
edw_product_dim as(
	select * from {{ ref('idnedw_integration__edw_product_dim') }}
),
itg_target_bp_s_op as(
	select * from {{ ref('idnitg_integration__itg_target_bp_s_op') }}
),

union1 as(
SELECT ETD.JJ_YEAR,
             ETD.JJ_QRTR,
             ETD.JJ_MNTH_ID,
             ETD.JJ_MNTH,
             ETD.JJ_MNTH_DESC,
             ETD.JJ_MNTH_NO,
             TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) AS DSTRBTR_GRP_CD,
             EDD.DSTRBTR_GRP_NM,
             TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID)) AS JJ_SAP_DSTRBTR_ID,
             EDD.JJ_SAP_DSTRBTR_NM,
             EDD.JJ_SAP_DSTRBTR_NM || ' ^' || EDD.JJ_SAP_DSTRBTR_ID AS DSTRBTR_CD_NM,
             EDD.AREA,
             EDD.REGION,
             EDD.BDM_NM,
             EDD.RBM_NM,
             EDD.STATUS AS DSTRBTR_STATUS,
             TRIM(UPPER(EPD.JJ_SAP_PROD_ID)) AS JJ_SAP_PROD_ID,
             EPD.JJ_SAP_PROD_DESC,
             EPD.JJ_SAP_UPGRD_PROD_ID,
             EPD.JJ_SAP_UPGRD_PROD_DESC,
             EPD.JJ_SAP_CD_MP_PROD_ID,
             EPD.JJ_SAP_CD_MP_PROD_DESC,
             EPD.JJ_SAP_UPGRD_PROD_DESC || ' ^' || EPD.JJ_SAP_UPGRD_PROD_ID AS SAP_PROD_CODE_NAME,
             EPD.FRANCHISE,
             EPD.BRAND,
             EPD.VARIANT1 AS SKU_GRP_OR_VARIANT,
             EPD.VARIANT2 AS SKU_GRP1_OR_VARIANT1,
             EPD.VARIANT3 AS SKU_GRP2_OR_VARIANT2,
             EPD.VARIANT3 || ' ' || NVL(CAST(EPD.PUT_UP AS VARCHAR),'') AS SKU_GRP3_OR_VARIANT3,
             EPD.STATUS AS PROD_STATUS,
             T1.STRT_INV_QTY,
             T1.SELLIN_QTY,
             T1.SELLOUT_QTY,
             T1.END_INV_QTY,
             T1.STRT_INV_VAL,
             T1.GROSS_STRT_INV_VAL,
             T1.SELLIN_VAL,
             T1.GROSS_SELLIN_VAL,
             T1.SELLOUT_VAL,
             T1.GROSS_SELLOUT_VAL,
             T1.END_INV_VAL,
             T1.GROSS_END_INV_VAL,
             0 AS SELLOUT_LAST_TWO_MNTHS_QTY,
             0 AS SELLOUT_LAST_TWO_MNTHS_VAL,
             0 AS GROSS_SELLOUT_LAST_TWO_MNTHS_VAL,
             T1.STOCK_ON_HAND_QTY,
             T1.STOCK_ON_HAND_VAL,
             NULL AS VARIANT,
             ETD.JJ_MNTH_LONG AS JJ_MNTH_LONG,
             0 AS BP_QTN,
             0 AS BP_VAL,
             0 AS S_OP_QTN,
             0 AS S_OP_VAL,
             0 AS TRGT_HNA,
             0 AS TRGT_NIV,
             NULL AS TRGT_BP_S_OP_FLAG,
             NULL AS TRGT_DIST_BRND_CHNL_FLAG,
             T1.SALEABLE_STOCK_QTY,
             T1.SALEABLE_STOCK_VALUE,
             T1.NON_SALEABLE_STOCK_QTY,
             T1.NON_SALEABLE_STOCK_VALUE,
             T1.INTRANSIT_QTY,
             T1.INTRANSIT_HNA,
             T1.INTRANSIT_NIV,
             CASE
               WHEN TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) = 'DNR' THEN
                 CASE
                   WHEN UPPER(TRIM(EPD.BRAND)) = 'IMODIUM' THEN T1.STOCK_ON_HAND_VAL*0.946
                   WHEN UPPER(TRIM(EPD.BRAND)) = 'MOTILIUM' THEN T1.STOCK_ON_HAND_VAL*0.946
                   WHEN UPPER(TRIM(EPD.BRAND)) = 'NIZORAL' THEN T1.STOCK_ON_HAND_VAL*0.946
                   ELSE T1.STOCK_ON_HAND_VAL*0.92
                 END 
               WHEN TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) = 'SPS' THEN
                 CASE
                   WHEN UPPER(TRIM(EPD.BRAND)) = 'IMODIUM' THEN T1.STOCK_ON_HAND_VAL*0.946
                   WHEN UPPER(TRIM(EPD.BRAND)) = 'MOTILIUM' THEN T1.STOCK_ON_HAND_VAL*0.946
                   WHEN UPPER(TRIM(EPD.BRAND)) = 'NIZORAL' THEN T1.STOCK_ON_HAND_VAL*0.946
                   ELSE T1.STOCK_ON_HAND_VAL*0.93
                 END 
               ELSE
                 CASE
                   WHEN UPPER(TRIM(EPD.BRAND)) = 'IMODIUM' THEN T1.STOCK_ON_HAND_VAL*0.946
                   WHEN UPPER(TRIM(EPD.BRAND)) = 'MOTILIUM' THEN T1.STOCK_ON_HAND_VAL*0.946
                   WHEN UPPER(TRIM(EPD.BRAND)) = 'NIZORAL' THEN T1.STOCK_ON_HAND_VAL*0.946
                   ELSE T1.STOCK_ON_HAND_VAL*0.93*0.99
                 END 
             END AS STOCK_ON_HAND_NIV,
             0 AS P3M_SELLOUT_VAL,
             0 AS P3M_GROSS_SELLOUT_VAL,
             0 AS P6M_SELLOUT_VAL,
             0 AS P6M_GROSS_SELLOUT_VAL
      FROM (SELECT REC_KEY,
                   CUST_PROD_CD,
                   JJ_MNTH_ID,
                   JJ_SAP_DSTRBTR_ID,
                   JJ_SAP_PROD_ID,
                   SELLIN_QTY,
                   SELLOUT_QTY,
                   STRT_INV_QTY,
                   END_INV_QTY,
                   SELLIN_VAL,
                   GROSS_SELLIN_VAL,
                   SELLOUT_VAL,
                   GROSS_SELLOUT_VAL,
                   STRT_INV_VAL,
                   GROSS_STRT_INV_VAL,
                   END_INV_VAL,
                   GROSS_END_INV_VAL,
                   STOCK_ON_HAND_QTY,
                   STOCK_ON_HAND_VAL,
                   CRTD_DTTM,
                   UPTD_DTTM,
                   SALEABLE_STOCK_QTY,
                   SALEABLE_STOCK_VALUE,
                   NON_SALEABLE_STOCK_QTY,
                   NON_SALEABLE_STOCK_VALUE,
                   INTRANSIT_QTY,
                   INTRANSIT_HNA,
                   INTRANSIT_NIV
            FROM EDW_ALL_DISTRIBUTOR_LPPB_FACT
--            WHERE JJ_SAP_DSTRBTR_ID NOT IN (SELECT DISTINCT JJ_SAP_DSTRBTR_ID
--                                            FROM EDW_ALL_DISTRIBUTOR_LPPB_FACT
--                                            WHERE JJ_SAP_DSTRBTR_ID IN ('131677','123881','123877','123878','123879','123880')
--                                            AND   JJ_MNTH_ID = '201711')
											) AS T1,
           EDW_DISTRIBUTOR_DIM AS EDD,
           EDW_PRODUCT_DIM AS EPD,
           --EDW_DISTRIBUTOR_GROUP_DIM AS EDGD,
      (SELECT DISTINCT JJ_YEAR,
              JJ_QRTR_NO,
              JJ_QRTR,
              JJ_MNTH_ID,
              JJ_MNTH,
              JJ_MNTH_DESC,
              JJ_MNTH_NO,
              JJ_MNTH_SHRT,
              JJ_MNTH_LONG
       FROM EDW_TIME_DIM) AS ETD
      WHERE
      --TRIM(UPPER(EDGD.DSTRBTR_GRP_CD (+)))=TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) AND
      TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID(+))) = TRIM(UPPER(T1.JJ_SAP_DSTRBTR_ID))
	  and   T1.jj_mnth_id between EDD.effective_from(+) and EDD.effective_to(+)
      AND   ETD.JJ_MNTH_ID = T1.JJ_MNTH_ID
      AND   TRIM(UPPER(EPD.JJ_SAP_PROD_ID(+))) = TRIM(UPPER(T1.JJ_SAP_PROD_ID))
	  and   T1.jj_mnth_id between EPD.effective_from(+) and EPD.effective_to(+)
      AND   TRIM(UPPER(T1.jj_sap_prod_id)) != 'REBATE'
      AND   TRIM(UPPER(T1.JJ_SAP_DSTRBTR_ID)) != '119683'
      AND   TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) != 'SPLD'
      AND   TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) != 'JYM'
      AND   TRIM(UPPER(T1.JJ_SAP_PROD_ID)) != 'DAOG20'
),
union2 as(
	 SELECT CAST(YEAR AS INTEGER) AS JJ_YEAR,
             ETD.JJ_QRTR AS JJ_QRTR,
             ETD.jj_mnth_id AS jj_mnth_id,
             ETD.jj_mnth AS jj_mnth,
             ETD.jj_mnth_desc AS jj_mnth_desc,
             ETD.jj_mnth_no AS jj_mnth_no,
             NULL AS dstrbtr_grp_cd,
             NULL AS dstrbtr_grp_nm,
             NULL AS jj_sap_dstrbtr_id,
             NULL AS jj_sap_dstrbtr_nm,
             NULL AS dstrbtr_cd_nm,
             NULL AS area,
             NULL AS region,
             NULL AS bdm_mn,
             NULL AS rbm_nm,
             NULL AS DSTRBTR_STATUS,
             NULL AS jj_sap_prod_id,
             NULL AS jj_sap_prod_desc,
             NULL AS jj_sap_upgrd_prod_id,
             NULL AS jj_sap_upgrd_prod_desc,
             NULL AS jj_sap_cd_mp_prod_id,
             NULL AS jj_sap_cd_mp_prod_desc,
             NULL AS sap_prod_code_name,
             ITBSP.franchise AS franchise,
             ITBSP.brand AS brand,
             NULL AS sku_grp_or_variant,
             NULL AS sku_grp1_or_variant1,
             NULL AS sku_grp2_or_variant2,
             NULL AS sku_grp3_or_variant3,
             NULL AS prod_status,
             0 AS strt_inv_qty,
             0 AS sellin_qty,
             0 AS sellout_qty,
             0 AS end_inv_qty,
             0 AS strt_inv_val,
             0 AS gross_strt_inv_val,
             0 AS sellin_val,
             0 AS gross_sellin_val,
             0 AS sellout_val,
             0 AS gross_sellout_val,
             0 AS end_inv_val,
             0 AS gross_end_inv_val,
             0 AS sellout_last_two_mnths_qty,
             0 AS sellout_last_two_mnths_val,
             0 AS gross_sellout_last_two_mnths_val,
             0 AS STOCK_ON_HAND_QTY,
             0 AS STOCK_ON_HAND_VAL,
             variant AS variant,
             ITBSP.jj_mnth_long AS jj_mnth_long,
             bp_qtn AS bp_qtn,
             bp_val AS bp_val,
             s_op_qtn AS s_op_qtn,
             s_op_val AS s_op_val,
             0 AS trgt_hna,
             0 AS trgt_niv,
             'Y' AS TRGT_BP_S_OP_FLAG,
             NULL AS TRGT_DIST_BRND_CHNL_FLAG,
             0 AS SALEABLE_STOCK_QTY,
             0 AS SALEABLE_STOCK_VALUE,
             0 AS NON_SALEABLE_STOCK_QTY,
             0 AS NON_SALEABLE_STOCK_VALUE,
             0 AS INTRANSIT_QTY,
             0 AS INTRANSIT_HNA,
             0 AS INTRANSIT_NIV,
             0 AS stock_on_hand_niv,
             0 AS P3M_SELLOUT_VAL,
             0 AS P3M_GROSS_SELLOUT_VAL,
             0 AS P6M_SELLOUT_VAL,
             0 AS P6M_GROSS_SELLOUT_VAL
      FROM itg_target_bp_s_op ITBSP,
           (SELECT DISTINCT JJ_YEAR,
                   JJ_QRTR_NO,
                   JJ_QRTR,
                   JJ_MNTH_ID,
                   JJ_MNTH,
                   JJ_MNTH_DESC,
                   JJ_MNTH_NO,
                   JJ_MNTH_SHRT,
                   JJ_MNTH_LONG
            FROM EDW_TIME_DIM) AS ETD,
           (SELECT DISTINCT brand, franchise FROM edw_product_dim) EPD
      WHERE TRIM(UPPER(EPD.brand(+))) = TRIM(UPPER(ITBSP.brand))
      AND   TRIM(UPPER(EPD.franchise(+))) = TRIM(UPPER(ITBSP.franchise))
      AND   ETD.jj_mnth_long(+) = ITBSP.jj_mnth_long
      AND   ETD.jj_year(+) = ITBSP.year

),
union3 as(
SELECT CAST(YEAR AS INTEGER) AS JJ_YEAR,
             ITDBC.JJ_QRTR AS JJ_QRTR,
             ITDBC.jj_mnth_id AS jj_mnth_id,
             ITDBC.jj_mnth AS jj_mnth,
             ITDBC.jj_mnth_desc AS jj_mnth_desc,
             ITDBC.jj_mnth_no AS jj_mnth_no,
             NULL AS dstrbtr_grp_cd,
             NULL AS dstrbtr_grp_nm,
             TRIM(UPPER(ITDBC.jj_sap_dstrbtr_id)) AS jj_sap_dstrbtr_id,
             ITDBC.jj_sap_dstrbtr_nm AS jj_sap_dstrbtr_nm,
             EDD.JJ_SAP_DSTRBTR_NM || ' ^' || EDD.JJ_SAP_DSTRBTR_ID AS dstrbtr_cd_nm,
             EDD.area AS area,
             EDD.region AS region,
             EDD.bdm_nm AS bdm_nm,
             EDD.rbm_nm AS rbm_nm,
             EDD.status AS DSTRBTR_STATUS,
             NULL AS jj_sap_prod_id,
             NULL AS jj_sap_prod_desc,
             NULL AS jj_sap_upgrd_prod_id,
             NULL AS jj_sap_upgrd_prod_desc,
             NULL AS jj_sap_cd_mp_prod_id,
             NULL AS jj_sap_cd_mp_prod_desc,
             NULL AS sap_prod_code_name,
             CASE
               WHEN ITDBC.Brand IS NOT NULL THEN EPD.Franchise
               ELSE ITDBC.Franchise
             END AS franchise,
             ITDBC.brand AS brand,
             NULL AS sku_grp_or_variant,
             NULL AS sku_grp1_or_variant1,
             NULL AS sku_grp2_or_variant2,
             NULL AS sku_grp3_or_variant3,
             NULL AS prod_status,
             0 AS strt_inv_qty,
             0 AS sellin_qty,
             0 AS sellout_qty,
             0 AS end_inv_qty,
             0 AS strt_inv_val,
             0 AS gross_strt_inv_val,
             0 AS sellin_val,
             0 AS gross_sellin_val,
             0 AS sellout_val,
             0 AS gross_sellout_val,
             0 AS end_inv_val,
             0 AS gross_end_inv_val,
             0 AS sellout_last_two_mnths_qty,
             0 AS sellout_last_two_mnths_val,
             0 AS gross_sellout_last_two_mnths_val,
             0 AS STOCK_ON_HAND_QTY,
             0 AS STOCK_ON_HAND_VAL,
             NULL AS variant,
             ITDBC.jj_mnth_long AS jj_mnth_long,
             0 AS bp_qtn,
             0 AS bp_val,
             0 AS s_op_qtn,
             0 AS s_op_val,
             ITDBC.trgt_hna AS trgt_hna,
             ITDBC.trgt_niv AS trgt_niv,
             NULL AS TRGT_BP_S_OP_FLAG,
             'Y' AS TRGT_DIST_BRND_CHNL_FLAG,
             0 AS SALEABLE_STOCK_QTY,
             0 AS SALEABLE_STOCK_VALUE,
             0 AS NON_SALEABLE_STOCK_QTY,
             0 AS NON_SALEABLE_STOCK_VALUE,
             0 AS INTRANSIT_QTY,
             0 AS INTRANSIT_HNA,
             0 AS INTRANSIT_NIV,
             0 AS stock_on_hand_niv,
             0 AS P3M_SELLOUT_VAL,
             0 AS P3M_GROSS_SELLOUT_VAL,
             0 AS P6M_SELLOUT_VAL,
             0 AS P6M_GROSS_SELLOUT_VAL
      FROM (select T1.*,ETD.JJ_QRTR,ETD.JJ_MNTH_ID,ETD.JJ_MNTH,ETD.JJ_MNTH_DESC,ETD.JJ_MNTH_NO from itg_target_dist_brand_channel T1 LEFT JOIN (SELECT DISTINCT JJ_YEAR,
                          
                          JJ_QRTR,
                          JJ_MNTH_ID,
                          JJ_MNTH,
                          JJ_MNTH_DESC,
                          JJ_MNTH_NO,
                          JJ_MNTH_LONG
                   FROM EDW_TIME_DIM) AS ETD
               ON T1.year = ETD.jj_year
              AND UPPER (TRIM (T1.jj_mnth_long)) = UPPER (TRIM (ETD.JJ_MNTH_LONG))
              ) ITDBC
              LEFT JOIN edw_distributor_dim EDD ON TRIM (UPPER (ITDBC.jj_sap_dstrbtr_id)) = TRIM (UPPER (EDD.jj_sap_dstrbtr_id))
		and ITDBC.jj_mnth_id between EDD.effective_from and EDD.effective_to
LEFT JOIN (SELECT DISTINCT brand, franchise,effective_from,effective_to FROM edw_product_dim) EPD ON
		               CASE WHEN ITDBC.brand IS NOT NULL
              and UPPER (TRIM (ITDBC.brand)) = UPPER (TRIM (EPD.brand)) and ITDBC.jj_mnth_id between EPD.effective_from and EPD.effective_to  THEN 1 END = 1
),
union4 as(
	      SELECT P2M_SELLOUT.JJ_YEAR,
             P2M_SELLOUT.JJ_QRTR,
             P2M_SELLOUT.JJ_MNTH_ID,
             P2M_SELLOUT.JJ_MNTH,
             P2M_SELLOUT.JJ_MNTH_DESC,
             P2M_SELLOUT.JJ_MNTH_NO,
             TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) AS DSTRBTR_GRP_CD,
             EDD.DSTRBTR_GRP_NM,
             TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID)) AS JJ_SAP_DSTRBTR_ID,
             EDD.JJ_SAP_DSTRBTR_NM,
             EDD.JJ_SAP_DSTRBTR_NM || ' ^' || EDD.JJ_SAP_DSTRBTR_ID AS DSTRBTR_CD_NM,
             EDD.AREA,
             EDD.REGION,
             EDD.BDM_NM,
             EDD.RBM_NM,
             EDD.STATUS AS DSTRBTR_STATUS,
             TRIM(UPPER(EPD.JJ_SAP_PROD_ID)) AS JJ_SAP_PROD_ID,
             EPD.JJ_SAP_PROD_DESC,
             EPD.JJ_SAP_UPGRD_PROD_ID,
             EPD.JJ_SAP_UPGRD_PROD_DESC,
             EPD.JJ_SAP_CD_MP_PROD_ID,
             EPD.JJ_SAP_CD_MP_PROD_DESC,
             EPD.JJ_SAP_UPGRD_PROD_DESC || ' ^' || EPD.JJ_SAP_UPGRD_PROD_ID AS SAP_PROD_CODE_NAME,
             EPD.FRANCHISE,
             EPD.BRAND,
             EPD.VARIANT1 AS SKU_GRP_OR_VARIANT,
             EPD.VARIANT2 AS SKU_GRP1_OR_VARIANT1,
             EPD.VARIANT3 AS SKU_GRP2_OR_VARIANT2,
             EPD.VARIANT3 || ' ' || NVL(CAST(EPD.PUT_UP AS VARCHAR),'') AS SKU_GRP3_OR_VARIANT3,
             EPD.STATUS AS PROD_STATUS,
             0 AS STRT_INV_QTY,
             0 AS SELLIN_QTY,
             0 AS SELLOUT_QTY,
             0 AS END_INV_QTY,
             0 AS STRT_INV_VAL,
             0 AS GROSS_STRT_INV_VAL,
             0 AS SELLIN_VAL,
             0 AS GROSS_SELLIN_VAL,
             0 AS SELLOUT_VAL,
             0 AS GROSS_SELLOUT_VAL,
             0 AS END_INV_VAL,
             0 AS GROSS_END_INV_VAL,
             P2M_SELLOUT.P2M_SELLOUT_QTY AS SELLOUT_LAST_TWO_MNTHS_QTY,
             P2M_SELLOUT.P2M_SELLOUT_VAL AS SELLOUT_LAST_TWO_MNTHS_VAL,
             P2M_SELLOUT.P2M_GROSS_SELLOUT_VAL AS GROSS_SELLOUT_LAST_TWO_MNTHS_VAL,
             0 AS STOCK_ON_HAND_QTY,
             0 AS STOCK_ON_HAND_VAL,
             NULL AS variant,
             P2M_SELLOUT.JJ_MNTH_LONG AS jj_mnth_long,
             0 AS bp_qtn,
             0 AS bp_val,
             0 AS s_op_qtn,
             0 AS s_op_val,
             0 AS trgt_hna,
             0 AS trgt_niv,
             NULL AS TRGT_BP_S_OP_FLAG,
             NULL AS TRGT_DIST_BRND_CHNL_FLAG,
             0 AS SALEABLE_STOCK_QTY,
             0 AS SALEABLE_STOCK_VALUE,
             0 AS NON_SALEABLE_STOCK_QTY,
             0 AS NON_SALEABLE_STOCK_VALUE,
             0 AS INTRANSIT_QTY,
             0 AS INTRANSIT_HNA,
             0 AS INTRANSIT_NIV,
             0 AS STOCK_ON_HAND_NIV,
             0 AS P3M_SELLOUT_VAL,
             0 AS P3M_GROSS_SELLOUT_VAL,
             0 AS P6M_SELLOUT_VAL,
             0 AS P6M_GROSS_SELLOUT_VAL
      FROM (SELECT CAL.JJ_YEAR,
                   CAL.JJ_QRTR,
                   CAL.JJ_MNTH_ID,
                   CAL.JJ_MNTH,
                   CAL.JJ_MNTH_DESC,
                   CAL.JJ_MNTH_NO,
                   CAL.JJ_MNTH_LONG,
                   CAL.JJ_MNTH_ID||TRIM(UPPER(T1.JJ_SAP_DSTRBTR_ID)) ||TRIM(UPPER(T1.JJ_SAP_PROD_ID)) AS REC_KEY,
                   T1.CUST_PROD_CD,
                   T1.JJ_SAP_DSTRBTR_ID,
                   T1.JJ_SAP_PROD_ID,
                   SUM(T1.SELLOUT_QTY) AS P2M_SELLOUT_QTY,
                   SUM(T1.SELLOUT_VAL) AS P2M_SELLOUT_VAL,
                   SUM(T1.GROSS_SELLOUT_VAL) AS P2M_GROSS_SELLOUT_VAL
            FROM (SELECT DISTINCT JJ_YEAR,
                         JJ_QRTR_NO,
                         JJ_QRTR,
                         JJ_MNTH_ID,
                         JJ_MNTH,
                         JJ_MNTH_DESC,
                         JJ_MNTH_NO,
                         JJ_MNTH_SHRT,
                         JJ_MNTH_LONG,
                         TO_CHAR(DATEADD(MONTH, -1, TO_DATE(TO_CHAR(EDW_TIME_DIM.JJ_MNTH_ID), 'YYYYMM')), 'YYYYMM') AS L1_MONTH,
                         TO_CHAR(DATEADD(MONTH, -2, TO_DATE(TO_CHAR(EDW_TIME_DIM.JJ_MNTH_ID), 'YYYYMM')), 'YYYYMM') AS L2_MONTH
                  FROM EDW_TIME_DIM) CAL
              LEFT JOIN (SELECT CUST_PROD_CD,
                                JJ_MNTH_ID,
                                JJ_SAP_DSTRBTR_ID,
                                JJ_SAP_PROD_ID,
                                SELLIN_QTY,
                                SELLOUT_QTY,
                                STRT_INV_QTY,
                                END_INV_QTY,
                                SELLIN_VAL,
                                GROSS_SELLIN_VAL,
                                SELLOUT_VAL,
                                GROSS_SELLOUT_VAL,
                                STRT_INV_VAL,
                                GROSS_STRT_INV_VAL,
                                END_INV_VAL,
                                GROSS_END_INV_VAL,
                                STOCK_ON_HAND_QTY,
                                STOCK_ON_HAND_VAL,
                                CRTD_DTTM,
                                UPTD_DTTM,
                                SALEABLE_STOCK_QTY,
                                SALEABLE_STOCK_VALUE,
                                NON_SALEABLE_STOCK_QTY,
                                NON_SALEABLE_STOCK_VALUE,
                                INTRANSIT_QTY,
                                INTRANSIT_HNA,
                                INTRANSIT_NIV
                         FROM EDW_ALL_DISTRIBUTOR_LPPB_FACT
--                         WHERE JJ_SAP_DSTRBTR_ID NOT IN (SELECT DISTINCT JJ_SAP_DSTRBTR_ID
--                                                         FROM EDW_ALL_DISTRIBUTOR_LPPB_FACT
--                                                         WHERE JJ_SAP_DSTRBTR_ID IN ('131677','123881','123877','123878','123879','123880')
--                                                         AND   JJ_MNTH_ID = '201711')
														 ) T1
                     ON T1.JJ_MNTH_ID >= CAL.L2_MONTH
                    AND T1.JJ_MNTH_ID <= CAL.L1_MONTH
            GROUP BY CAL.JJ_YEAR,
                     CAL.JJ_QRTR,
                     CAL.JJ_MNTH_ID,
                     CAL.JJ_MNTH,
                     CAL.JJ_MNTH_DESC,
                     CAL.JJ_MNTH_NO,
                     CAL.JJ_MNTH_LONG,
                     T1.CUST_PROD_CD,
                     T1.JJ_SAP_DSTRBTR_ID,
                     T1.JJ_SAP_PROD_ID) P2M_SELLOUT,
           EDW_DISTRIBUTOR_DIM AS EDD,
           EDW_PRODUCT_DIM AS EPD
      WHERE TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID(+))) = TRIM(UPPER(P2M_SELLOUT.JJ_SAP_DSTRBTR_ID))
	  and   P2M_SELLOUT.jj_mnth_id between EDD.effective_from(+) and EDD.effective_to(+)
      AND   TRIM(UPPER(EPD.JJ_SAP_PROD_ID(+))) = TRIM(UPPER(P2M_SELLOUT.JJ_SAP_PROD_ID))
	  and   P2M_SELLOUT.jj_mnth_id between EPD.effective_from(+) and EPD.effective_to(+)
      AND   TRIM(UPPER(P2M_SELLOUT.jj_sap_prod_id)) != 'REBATE'
      AND   TRIM(UPPER(P2M_SELLOUT.JJ_SAP_DSTRBTR_ID)) != '119683'
      AND   TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) != 'SPLD'
      AND   TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) != 'JYM'
      AND   TRIM(UPPER(P2M_SELLOUT.JJ_SAP_PROD_ID)) != 'DAOG20'
      AND   P2M_SELLOUT.JJ_MNTH_ID <= (SELECT DISTINCT JJ_MNTH_ID
                                       FROM EDW_TIME_DIM
                                       WHERE to_date(CAL_DATE) = to_date(current_timestamp()::timestamp_ntz(9)))
),
union5 as(
	      SELECT P3M_SELLOUT.JJ_YEAR,
             P3M_SELLOUT.JJ_QRTR,
             P3M_SELLOUT.JJ_MNTH_ID,
             P3M_SELLOUT.JJ_MNTH,
             P3M_SELLOUT.JJ_MNTH_DESC,
             P3M_SELLOUT.JJ_MNTH_NO,
             TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) AS DSTRBTR_GRP_CD,
             EDD.DSTRBTR_GRP_NM,
             TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID)) AS JJ_SAP_DSTRBTR_ID,
             EDD.JJ_SAP_DSTRBTR_NM,
             EDD.JJ_SAP_DSTRBTR_NM || ' ^' || EDD.JJ_SAP_DSTRBTR_ID AS DSTRBTR_CD_NM,
             EDD.AREA,
             EDD.REGION,
             EDD.BDM_NM,
             EDD.RBM_NM,
             EDD.STATUS AS DSTRBTR_STATUS,
             TRIM(UPPER(EPD.JJ_SAP_PROD_ID)) AS JJ_SAP_PROD_ID,
             EPD.JJ_SAP_PROD_DESC,
             EPD.JJ_SAP_UPGRD_PROD_ID,
             EPD.JJ_SAP_UPGRD_PROD_DESC,
             EPD.JJ_SAP_CD_MP_PROD_ID,
             EPD.JJ_SAP_CD_MP_PROD_DESC,
             EPD.JJ_SAP_UPGRD_PROD_DESC || ' ^' || EPD.JJ_SAP_UPGRD_PROD_ID AS SAP_PROD_CODE_NAME,
             EPD.FRANCHISE,
             EPD.BRAND,
             EPD.VARIANT1 AS SKU_GRP_OR_VARIANT,
             EPD.VARIANT2 AS SKU_GRP1_OR_VARIANT1,
             EPD.VARIANT3 AS SKU_GRP2_OR_VARIANT2,
             EPD.VARIANT3 || ' ' || NVL(CAST(EPD.PUT_UP AS VARCHAR),'') AS SKU_GRP3_OR_VARIANT3,
             EPD.STATUS AS PROD_STATUS,
             0 AS STRT_INV_QTY,
             0 AS SELLIN_QTY,
             0 AS SELLOUT_QTY,
             0 AS END_INV_QTY,
             0 AS STRT_INV_VAL,
             0 AS GROSS_STRT_INV_VAL,
             0 AS SELLIN_VAL,
             0 AS GROSS_SELLIN_VAL,
             0 AS SELLOUT_VAL,
             0 AS GROSS_SELLOUT_VAL,
             0 AS END_INV_VAL,
             0 AS GROSS_END_INV_VAL,
             0 AS SELLOUT_LAST_TWO_MNTHS_QTY,
             0 AS SELLOUT_LAST_TWO_MNTHS_VAL,
             0 AS GROSS_SELLOUT_LAST_TWO_MNTHS_VAL,
             0 AS STOCK_ON_HAND_QTY,
             0 AS STOCK_ON_HAND_VAL,
             NULL AS variant,
             P3M_SELLOUT.JJ_MNTH_LONG AS jj_mnth_long,
             0 AS bp_qtn,
             0 AS bp_val,
             0 AS s_op_qtn,
             0 AS s_op_val,
             0 AS trgt_hna,
             0 AS trgt_niv,
             NULL AS TRGT_BP_S_OP_FLAG,
             NULL AS TRGT_DIST_BRND_CHNL_FLAG,
             0 AS SALEABLE_STOCK_QTY,
             0 AS SALEABLE_STOCK_VALUE,
             0 AS NON_SALEABLE_STOCK_QTY,
             0 AS NON_SALEABLE_STOCK_VALUE,
             0 AS INTRANSIT_QTY,
             0 AS INTRANSIT_HNA,
             0 AS INTRANSIT_NIV,
             0 AS STOCK_ON_HAND_NIV,
             P3M_SELLOUT.P3M_SELLOUT_VAL,
             P3M_SELLOUT.P3M_GROSS_SELLOUT_VAL,
             0 AS P6M_SELLOUT_VAL,
             0 AS P6M_GROSS_SELLOUT_VAL
      FROM (SELECT CAL.JJ_YEAR,
                   CAL.JJ_QRTR,
                   CAL.JJ_MNTH_ID,
                   CAL.JJ_MNTH,
                   CAL.JJ_MNTH_DESC,
                   CAL.JJ_MNTH_NO,
                   CAL.JJ_MNTH_LONG,
                   CAL.JJ_MNTH_ID||TRIM(UPPER(T1.JJ_SAP_DSTRBTR_ID)) ||TRIM(UPPER(T1.JJ_SAP_PROD_ID)) AS REC_KEY,
                   T1.CUST_PROD_CD,
                   T1.JJ_SAP_DSTRBTR_ID,
                   T1.JJ_SAP_PROD_ID,
                   SUM(T1.SELLOUT_VAL) P3M_SELLOUT_VAL,
                   SUM(T1.GROSS_SELLOUT_VAL) P3M_GROSS_SELLOUT_VAL
            FROM (SELECT DISTINCT JJ_YEAR,
                         JJ_QRTR_NO,
                         JJ_QRTR,
                         JJ_MNTH_ID,
                         JJ_MNTH,
                         JJ_MNTH_DESC,
                         JJ_MNTH_NO,
                         JJ_MNTH_SHRT,
                         JJ_MNTH_LONG,
                         TO_CHAR(DATEADD(MONTH, -1, TO_DATE(TO_CHAR(EDW_TIME_DIM.JJ_MNTH_ID), 'YYYYMM')), 'YYYYMM') AS L1_MONTH,
                         TO_CHAR(DATEADD(MONTH, -3, TO_DATE(TO_CHAR(EDW_TIME_DIM.JJ_MNTH_ID), 'YYYYMM')), 'YYYYMM') AS L3_MONTH
                  FROM EDW_TIME_DIM) CAL
              LEFT JOIN (SELECT CUST_PROD_CD,
                                JJ_MNTH_ID,
                                JJ_SAP_DSTRBTR_ID,
                                JJ_SAP_PROD_ID,
                                SELLIN_QTY,
                                SELLOUT_QTY,
                                STRT_INV_QTY,
                                END_INV_QTY,
                                SELLIN_VAL,
                                GROSS_SELLIN_VAL,
                                SELLOUT_VAL,
                                GROSS_SELLOUT_VAL,
                                STRT_INV_VAL,
                                GROSS_STRT_INV_VAL,
                                END_INV_VAL,
                                GROSS_END_INV_VAL,
                                STOCK_ON_HAND_QTY,
                                STOCK_ON_HAND_VAL,
                                CRTD_DTTM,
                                UPTD_DTTM,
                                SALEABLE_STOCK_QTY,
                                SALEABLE_STOCK_VALUE,
                                NON_SALEABLE_STOCK_QTY,
                                NON_SALEABLE_STOCK_VALUE,
                                INTRANSIT_QTY,
                                INTRANSIT_HNA,
                                INTRANSIT_NIV
                         FROM EDW_ALL_DISTRIBUTOR_LPPB_FACT
--                         WHERE JJ_SAP_DSTRBTR_ID NOT IN (SELECT DISTINCT JJ_SAP_DSTRBTR_ID
--                                                         FROM EDW_ALL_DISTRIBUTOR_LPPB_FACT
--                                                         WHERE JJ_SAP_DSTRBTR_ID IN ('131677','123881','123877','123878','123879','123880')
--                                                         AND   JJ_MNTH_ID = '201711')
														 ) T1
                     ON T1.JJ_MNTH_ID >= CAL.L3_MONTH
                    AND T1.JJ_MNTH_ID <= CAL.L1_MONTH
            GROUP BY CAL.JJ_YEAR,
                     CAL.JJ_QRTR,
                     CAL.JJ_MNTH_ID,
                     CAL.JJ_MNTH,
                     CAL.JJ_MNTH_DESC,
                     CAL.JJ_MNTH_NO,
                     CAL.JJ_MNTH_LONG,
                     T1.CUST_PROD_CD,
                     T1.JJ_SAP_DSTRBTR_ID,
                     T1.JJ_SAP_PROD_ID) P3M_SELLOUT,
           EDW_DISTRIBUTOR_DIM AS EDD,
           EDW_PRODUCT_DIM AS EPD
      WHERE TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID(+))) = TRIM(UPPER(P3M_SELLOUT.JJ_SAP_DSTRBTR_ID))
	  and   P3M_SELLOUT.jj_mnth_id between EDD.effective_from(+) and EDD.effective_to(+)
      AND   TRIM(UPPER(EPD.JJ_SAP_PROD_ID(+))) = TRIM(UPPER(P3M_SELLOUT.JJ_SAP_PROD_ID))
	  and   P3M_SELLOUT.jj_mnth_id between EPD.effective_from(+) and EPD.effective_to(+)
      AND   TRIM(UPPER(P3M_SELLOUT.jj_sap_prod_id)) != 'REBATE'
      AND   TRIM(UPPER(P3M_SELLOUT.JJ_SAP_DSTRBTR_ID)) != '119683'
      AND   TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) != 'SPLD'
      AND   TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) != 'JYM'
      AND   TRIM(UPPER(P3M_SELLOUT.JJ_SAP_PROD_ID)) != 'DAOG20'
      AND   P3M_SELLOUT.JJ_MNTH_ID <= (SELECT DISTINCT jj_mnth_id
                                       FROM edw_time_dim
                                       WHERE to_date(cal_date) = to_date(current_timestamp()::timestamp_ntz(9)))
),
union6 as(
	     SELECT P6M_SELLOUT.JJ_YEAR,
             P6M_SELLOUT.JJ_QRTR,
             P6M_SELLOUT.JJ_MNTH_ID,
             P6M_SELLOUT.JJ_MNTH,
             P6M_SELLOUT.JJ_MNTH_DESC,
             P6M_SELLOUT.JJ_MNTH_NO,
             TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) AS DSTRBTR_GRP_CD,
             EDD.DSTRBTR_GRP_NM,
             TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID)) AS JJ_SAP_DSTRBTR_ID,
             EDD.JJ_SAP_DSTRBTR_NM,
             EDD.JJ_SAP_DSTRBTR_NM || ' ^' || EDD.JJ_SAP_DSTRBTR_ID AS DSTRBTR_CD_NM,
             EDD.AREA,
             EDD.REGION,
             EDD.BDM_NM,
             EDD.RBM_NM,
             EDD.STATUS AS DSTRBTR_STATUS,
             TRIM(UPPER(EPD.JJ_SAP_PROD_ID)) AS JJ_SAP_PROD_ID,
             EPD.JJ_SAP_PROD_DESC,
             EPD.JJ_SAP_UPGRD_PROD_ID,
             EPD.JJ_SAP_UPGRD_PROD_DESC,
             EPD.JJ_SAP_CD_MP_PROD_ID,
             EPD.JJ_SAP_CD_MP_PROD_DESC,
             EPD.JJ_SAP_UPGRD_PROD_DESC || ' ^' || EPD.JJ_SAP_UPGRD_PROD_ID AS SAP_PROD_CODE_NAME,
             EPD.FRANCHISE,
             EPD.BRAND,
             EPD.VARIANT1 AS SKU_GRP_OR_VARIANT,
             EPD.VARIANT2 AS SKU_GRP1_OR_VARIANT1,
             EPD.VARIANT3 AS SKU_GRP2_OR_VARIANT2,
             EPD.VARIANT3 || ' ' || NVL(CAST(EPD.PUT_UP AS VARCHAR),'') AS SKU_GRP3_OR_VARIANT3,
             EPD.STATUS AS PROD_STATUS,
             0 AS STRT_INV_QTY,
             0 AS SELLIN_QTY,
             0 AS SELLOUT_QTY,
             0 AS END_INV_QTY,
             0 AS STRT_INV_VAL,
             0 AS GROSS_STRT_INV_VAL,
             0 AS SELLIN_VAL,
             0 AS GROSS_SELLIN_VAL,
             0 AS SELLOUT_VAL,
             0 AS GROSS_SELLOUT_VAL,
             0 AS END_INV_VAL,
             0 AS GROSS_END_INV_VAL,
             0 AS SELLOUT_LAST_TWO_MNTHS_QTY,
             0 AS SELLOUT_LAST_TWO_MNTHS_VAL,
             0 AS GROSS_SELLOUT_LAST_TWO_MNTHS_VAL,
             0 AS STOCK_ON_HAND_QTY,
             0 AS STOCK_ON_HAND_VAL,
             NULL AS variant,
             P6M_SELLOUT.JJ_MNTH_LONG AS jj_mnth_long,
             0 AS bp_qtn,
             0 AS bp_val,
             0 AS s_op_qtn,
             0 AS s_op_val,
             0 AS trgt_hna,
             0 AS trgt_niv,
             NULL AS TRGT_BP_S_OP_FLAG,
             NULL AS TRGT_DIST_BRND_CHNL_FLAG,
             0 AS SALEABLE_STOCK_QTY,
             0 AS SALEABLE_STOCK_VALUE,
             0 AS NON_SALEABLE_STOCK_QTY,
             0 AS NON_SALEABLE_STOCK_VALUE,
             0 AS INTRANSIT_QTY,
             0 AS INTRANSIT_HNA,
             0 AS INTRANSIT_NIV,
             0 AS STOCK_ON_HAND_NIV,
             0 AS P3M_SELLOUT_VAL,
             0 AS P3M_GROSS_SELLOUT_VAL,
             P6M_SELLOUT.P6M_SELLOUT_VAL,
             P6M_SELLOUT.P6M_GROSS_SELLOUT_VAL
      FROM (SELECT CAL.JJ_YEAR,
                   CAL.JJ_QRTR,
                   CAL.JJ_MNTH_ID,
                   CAL.JJ_MNTH,
                   CAL.JJ_MNTH_DESC,
                   CAL.JJ_MNTH_NO,
                   CAL.JJ_MNTH_LONG,
                   CAL.JJ_MNTH_ID||TRIM(UPPER(T1.JJ_SAP_DSTRBTR_ID)) ||TRIM(UPPER(T1.JJ_SAP_PROD_ID)) AS REC_KEY,
                   T1.CUST_PROD_CD,
                   T1.JJ_SAP_DSTRBTR_ID,
                   T1.JJ_SAP_PROD_ID,
                   SUM(T1.SELLOUT_VAL) P6M_SELLOUT_VAL,
                   SUM(T1.GROSS_SELLOUT_VAL) P6M_GROSS_SELLOUT_VAL
            FROM (SELECT DISTINCT JJ_YEAR,
                         JJ_QRTR_NO,
                         JJ_QRTR,
                         JJ_MNTH_ID,
                         JJ_MNTH,
                         JJ_MNTH_DESC,
                         JJ_MNTH_NO,
                         JJ_MNTH_SHRT,
                         JJ_MNTH_LONG,
                         TO_CHAR(DATEADD(MONTH, -1, TO_DATE(TO_CHAR(EDW_TIME_DIM.JJ_MNTH_ID), 'YYYYMM')), 'YYYYMM') AS L1_MONTH,
                         TO_CHAR(DATEADD(MONTH, -6, TO_DATE(TO_CHAR(EDW_TIME_DIM.JJ_MNTH_ID), 'YYYYMM')), 'YYYYMM') AS L6_MONTH
                  FROM EDW_TIME_DIM) CAL
              LEFT JOIN (SELECT CUST_PROD_CD,
                                JJ_MNTH_ID,
                                JJ_SAP_DSTRBTR_ID,
                                JJ_SAP_PROD_ID,
                                SELLIN_QTY,
                                SELLOUT_QTY,
                                STRT_INV_QTY,
                                END_INV_QTY,
                                SELLIN_VAL,
                                GROSS_SELLIN_VAL,
                                SELLOUT_VAL,
                                GROSS_SELLOUT_VAL,
                                STRT_INV_VAL,
                                GROSS_STRT_INV_VAL,
                                END_INV_VAL,
                                GROSS_END_INV_VAL,
                                STOCK_ON_HAND_QTY,
                                STOCK_ON_HAND_VAL,
                                CRTD_DTTM,
                                UPTD_DTTM,
                                SALEABLE_STOCK_QTY,
                                SALEABLE_STOCK_VALUE,
                                NON_SALEABLE_STOCK_QTY,
                                NON_SALEABLE_STOCK_VALUE,
                                INTRANSIT_QTY,
                                INTRANSIT_HNA,
                                INTRANSIT_NIV
                         FROM EDW_ALL_DISTRIBUTOR_LPPB_FACT
--                         WHERE JJ_SAP_DSTRBTR_ID NOT IN (SELECT DISTINCT JJ_SAP_DSTRBTR_ID
--                                                         FROM EDW_ALL_DISTRIBUTOR_LPPB_FACT
--                                                         WHERE JJ_SAP_DSTRBTR_ID IN ('131677','123881','123877','123878','123879','123880')
--                                                         AND   JJ_MNTH_ID = '201711')
														 ) T1
                     ON T1.JJ_MNTH_ID >= CAL.L6_MONTH
                    AND T1.JJ_MNTH_ID <= CAL.L1_MONTH
            GROUP BY CAL.JJ_YEAR,
                     CAL.JJ_QRTR,
                     CAL.JJ_MNTH_ID,
                     CAL.JJ_MNTH,
                     CAL.JJ_MNTH_DESC,
                     CAL.JJ_MNTH_NO,
                     CAL.JJ_MNTH_LONG,
                     T1.CUST_PROD_CD,
                     T1.JJ_SAP_DSTRBTR_ID,
                     T1.JJ_SAP_PROD_ID) P6M_SELLOUT,
           EDW_DISTRIBUTOR_DIM AS EDD,
           EDW_PRODUCT_DIM AS EPD
      WHERE TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID(+))) = TRIM(UPPER(P6M_SELLOUT.JJ_SAP_DSTRBTR_ID))
	  and   P6M_SELLOUT.jj_mnth_id between EDD.effective_from(+) and EDD.effective_to(+)
      AND   TRIM(UPPER(EPD.JJ_SAP_PROD_ID(+))) = TRIM(UPPER(P6M_SELLOUT.JJ_SAP_PROD_ID))
	  and   P6M_SELLOUT.jj_mnth_id between EPD.effective_from(+) and EPD.effective_to(+)
      AND   TRIM(UPPER(P6M_SELLOUT.jj_sap_prod_id)) != 'REBATE'
      AND   TRIM(UPPER(P6M_SELLOUT.JJ_SAP_DSTRBTR_ID)) != '119683'
      AND   TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) != 'SPLD'
      AND   TRIM(UPPER(EDD.DSTRBTR_GRP_CD)) != 'JYM'
      AND   TRIM(UPPER(P6M_SELLOUT.JJ_SAP_PROD_ID)) != 'DAOG20'
      AND   P6M_SELLOUT.JJ_MNTH_ID <= (SELECT DISTINCT jj_mnth_id
                                       FROM edw_time_dim
                                       WHERE to_date(cal_date) = to_date(current_timestamp()::timestamp_ntz(9)))
),
transformed as(
	SELECT JJ_YEAR,
       JJ_QRTR,
       JJ_MNTH_ID,
       JJ_MNTH,
       JJ_MNTH_DESC,
       JJ_MNTH_NO,
       DSTRBTR_GRP_CD,
       DSTRBTR_GRP_NM,
       JJ_SAP_DSTRBTR_ID,
       JJ_SAP_DSTRBTR_NM,
       DSTRBTR_CD_NM,
       AREA,
       REGION,
       BDM_NM,
       RBM_NM,
       DSTRBTR_STATUS,
       JJ_SAP_PROD_ID,
       JJ_SAP_PROD_DESC,
       JJ_SAP_UPGRD_PROD_ID,
       JJ_SAP_UPGRD_PROD_DESC,
       JJ_SAP_CD_MP_PROD_ID,
       JJ_SAP_CD_MP_PROD_DESC,
       SAP_PROD_CODE_NAME,
       FRANCHISE,
       BRAND,
       SKU_GRP_OR_VARIANT,
       SKU_GRP1_OR_VARIANT1,
       SKU_GRP2_OR_VARIANT2,
       SKU_GRP3_OR_VARIANT3,
       PROD_STATUS,
       SUM(STRT_INV_QTY) AS STRT_INV_QTY,
       SUM(SELLIN_QTY) AS SELLIN_QTY,
       SUM(SELLOUT_QTY) AS SELLOUT_QTY,
       SUM(END_INV_QTY) AS END_INV_QTY,
       SUM(STRT_INV_VAL) AS STRT_INV_VAL,
       SUM(GROSS_STRT_INV_VAL) AS GROSS_STRT_INV_VAL,
       SUM(SELLIN_VAL) AS SELLIN_VAL,
       SUM(GROSS_SELLIN_VAL) AS GROSS_SELLIN_VAL,
       SUM(SELLOUT_VAL) AS SELLOUT_VAL,
       SUM(GROSS_SELLOUT_VAL) AS GROSS_SELLOUT_VAL,
       SUM(END_INV_VAL) AS END_INV_VAL,
       SUM(GROSS_END_INV_VAL) AS GROSS_END_INV_VAL,
       SUM(SELLOUT_LAST_TWO_MNTHS_QTY) AS SELLOUT_LAST_TWO_MNTHS_QTY,
       SUM(SELLOUT_LAST_TWO_MNTHS_VAL) AS SELLOUT_LAST_TWO_MNTHS_VAL,
       SUM(GROSS_SELLOUT_LAST_TWO_MNTHS_VAL) AS GROSS_SELLOUT_LAST_TWO_MNTHS_VAL,
       SUM(STOCK_ON_HAND_QTY) AS STOCK_ON_HAND_QTY,
       SUM(STOCK_ON_HAND_VAL) AS STOCK_ON_HAND_VAL,
       VARIANT,
       JJ_MNTH_LONG,
       SUM(BP_QTN) AS BP_QTN,
       SUM(BP_VAL) AS BP_VAL,
       SUM(S_OP_QTN) AS S_OP_QTN,
       SUM(S_OP_VAL) AS S_OP_VAL,
       SUM(TRGT_HNA) AS TRGT_HNA,
       SUM(TRGT_NIV) AS TRGT_NIV,
       TRGT_BP_S_OP_FLAG,
       TRGT_DIST_BRND_CHNL_FLAG,
       SUM(SALEABLE_STOCK_QTY) AS SALEABLE_STOCK_QTY,
       SUM(SALEABLE_STOCK_VALUE) AS SALEABLE_STOCK_VALUE,
       SUM(NON_SALEABLE_STOCK_QTY) AS NON_SALEABLE_STOCK_QTY,
       SUM(NON_SALEABLE_STOCK_VALUE) AS NON_SALEABLE_STOCK_VALUE,
       SUM(INTRANSIT_QTY) AS INTRANSIT_QTY,
       SUM(INTRANSIT_HNA) AS INTRANSIT_HNA,
       SUM(INTRANSIT_NIV) AS INTRANSIT_NIV,
       SUM(STOCK_ON_HAND_NIV) AS STOCK_ON_HAND_NIV,
       SUM(P3M_SELLOUT_VAL) AS P3M_SELLOUT_VAL,
       SUM(P3M_GROSS_SELLOUT_VAL) AS P3M_GROSS_SELLOUT_VAL,
       SUM(P6M_SELLOUT_VAL) AS P6M_SELLOUT_VAL,
       SUM(P6M_GROSS_SELLOUT_VAL) AS P6M_GROSS_SELLOUT_VAL
FROM (
	select * from union1
	union all
	select * from union2
	union all
	select * from union3
	union all
	select * from union4
	union all
	select * from union5
    union all
	select * from union6
	
)
GROUP BY JJ_YEAR,
         JJ_QRTR,
         JJ_MNTH_ID,
         JJ_MNTH,
         JJ_MNTH_DESC,
         JJ_MNTH_NO,
         DSTRBTR_GRP_CD,
         DSTRBTR_GRP_NM,
         JJ_SAP_DSTRBTR_ID,
         JJ_SAP_DSTRBTR_NM,
         DSTRBTR_CD_NM,
         AREA,
         REGION,
         BDM_NM,
         RBM_NM,
         DSTRBTR_STATUS,
         JJ_SAP_PROD_ID,
         JJ_SAP_PROD_DESC,
         JJ_SAP_UPGRD_PROD_ID,
         JJ_SAP_UPGRD_PROD_DESC,
         JJ_SAP_CD_MP_PROD_ID,
         JJ_SAP_CD_MP_PROD_DESC,
         SAP_PROD_CODE_NAME,
         FRANCHISE,
         BRAND,
         SKU_GRP_OR_VARIANT,
         SKU_GRP1_OR_VARIANT1,
         SKU_GRP2_OR_VARIANT2,
         SKU_GRP3_OR_VARIANT3,
         PROD_STATUS,
         VARIANT,
         JJ_MNTH_LONG,
         TRGT_BP_S_OP_FLAG,
         TRGT_DIST_BRND_CHNL_FLAG
),
final as(
    select 
    	jj_year::number(18,0) as jj_year,
        jj_qrtr::varchar(24) as jj_qrtr,
        jj_mnth_id::number(18,0) as jj_mnth_id,
        jj_mnth::varchar(25) as jj_mnth,
        jj_mnth_desc::varchar(20) as jj_mnth_desc,
        jj_mnth_no::number(18,0) as jj_mnth_no,
        dstrbtr_grp_cd::varchar(25) as dstrbtr_grp_cd,
        dstrbtr_grp_nm::varchar(155) as dstrbtr_grp_nm,
        jj_sap_dstrbtr_id::varchar(75) as jj_sap_dstrbtr_id,
        jj_sap_dstrbtr_nm::varchar(75) as jj_sap_dstrbtr_nm,
        dstrbtr_cd_nm::varchar(72) as dstrbtr_cd_nm,
        area::varchar(50) as area,
        region::varchar(50) as region,
        bdm_nm::varchar(50) as bdm_nm,
        rbm_nm::varchar(50) as rbm_nm,
        dstrbtr_status::varchar(50) as dstrbtr_status,
        jj_sap_prod_id::varchar(50) as jj_sap_prod_id,
        jj_sap_prod_desc::varchar(100) as jj_sap_prod_desc,
        jj_sap_upgrd_prod_id::varchar(50) as jj_sap_upgrd_prod_id,
        jj_sap_upgrd_prod_desc::varchar(100) as jj_sap_upgrd_prod_desc,
        jj_sap_cd_mp_prod_id::varchar(50) as jj_sap_cd_mp_prod_id,
        jj_sap_cd_mp_prod_desc::varchar(100) as jj_sap_cd_mp_prod_desc,
        sap_prod_code_name::varchar(152) as sap_prod_code_name,
        franchise::varchar(75) as franchise,
        brand::varchar(75) as brand,
        sku_grp_or_variant::varchar(50) as sku_grp_or_variant,
        sku_grp1_or_variant1::varchar(50) as sku_grp1_or_variant1,
        sku_grp2_or_variant2::varchar(50) as sku_grp2_or_variant2,
        sku_grp3_or_variant3::varchar(62) as sku_grp3_or_variant3,
        prod_status::varchar(50) as prod_status,
        strt_inv_qty::number(18,4) as strt_inv_qty,
        sellin_qty::number(18,4) as sellin_qty,
        sellout_qty::number(18,4) as sellout_qty,
        end_inv_qty::number(18,4) as end_inv_qty,
        strt_inv_val::number(18,4) as strt_inv_val,
        gross_strt_inv_val::number(18,4) as gross_strt_inv_val,
        sellin_val::number(18,4) as sellin_val,
        gross_sellin_val::number(18,4) as gross_sellin_val,
        sellout_val::number(18,4) as sellout_val,
        gross_sellout_val::number(18,4) as gross_sellout_val,
        end_inv_val::number(18,4) as end_inv_val,
        gross_end_inv_val::number(18,4) as gross_end_inv_val,
        sellout_last_two_mnths_qty::number(18,4) as sellout_last_two_mnths_qty,
        sellout_last_two_mnths_val::number(18,4) as sellout_last_two_mnths_val,
        gross_sellout_last_two_mnths_val::number(18,4) as gross_sellout_last_two_mnths_val,
        stock_on_hand_qty::number(18,4) as stock_on_hand_qty,
        stock_on_hand_val::number(18,4) as stock_on_hand_val,
        variant::varchar(75) as variant,
        jj_mnth_long::varchar(75) as jj_mnth_long,
        bp_qtn::number(18,4) as bp_qtn,
        bp_val::number(18,4) as bp_val,
        s_op_qtn::number(18,4) as s_op_qtn,
        s_op_val::number(18,4) as s_op_val,
        trgt_hna::number(38,4) as trgt_hna,
        trgt_niv::number(38,4) as trgt_niv,
        trgt_bp_s_op_flag::varchar(1) as trgt_bp_s_op_flag,
        trgt_dist_brnd_chnl_flag::varchar(1) as trgt_dist_brnd_chnl_flag,
        saleable_stock_qty::number(18,4) as saleable_stock_qty,
        saleable_stock_value::number(18,4) as saleable_stock_value,
        non_saleable_stock_qty::number(18,4) as non_saleable_stock_qty,
        non_saleable_stock_value::number(18,4) as non_saleable_stock_value,
        intransit_qty::number(18,4) as intransit_qty,
        intransit_hna::number(18,4) as intransit_hna,
        intransit_niv::number(18,4) as intransit_niv,
        stock_on_hand_niv::number(18,4) as stock_on_hand_niv,
        p3m_sellout_val::number(18,4) as p3m_sellout_val,
        p3m_gross_sellout_val::number(18,4) as p3m_gross_sellout_val,
        p6m_sellout_val::number(18,4) as p6m_sellout_val,
        p6m_gross_sellout_val::number(18,4) as p6m_gross_sellout_val
    from transformed
)
select * from final