

with source as(
    select * from {{ ref('aspwks_integration__wks_edw_invc_fact') }}
),
final as(
    SELECT
    act_delv_dt::DATE as act_delv_dt,
    act_good_iss_dt::DATE as act_good_iss_dt,
    bill_to_prty::VARCHAR(10) as bill_to_prty,
    bill_dt::DATE as bill_dt,
    bill_ty::VARCHAR(4) as bill_typ,
    bill_doc::VARCHAR(10) as bill_doc,
    cmpy_cd::VARCHAR(4) as co_cd,
    cust_no::VARCHAR(10) as cust_num,
    delv_doc_crt_dt::DATE as delv_doc_crt_dt,
    dstr_chnl::VARCHAR(2) as dstr_chnl,
    div::VARCHAR(2) as div,
    doc_crt_dt::DATE as doc_crt_dt,
    doc_dt::DATE as doc_dt,
    good_iss_dt::DATE as good_iss_dt,
    mat::VARCHAR(18) as matl_num,
    mat_avail_dt::DATE as mat_avail_dt,
    ord_rsn::VARCHAR(3) as ord_rsn,
    ovrl_rej_sts::VARCHAR(1) as ovrl_rej_sts,
    ovrl_sts_crd_chk::VARCHAR(1) as ovrl_sts_crd_chk,
    payer::VARCHAR(10) as payer,
    plant::VARCHAR(4) as plnt,
    prec_doc_itm::NUMBER(18,0) as prec_doc_itm,
    prec_doc_num::VARCHAR(10) as prec_doc_num,
    proof_delv_dt::DATE as proof_delv_dt,
    rsn_cd_key::VARCHAR(29) as rsn_cd_key,
    rsn_rej::VARCHAR(2) as rsn_rej,
    rlse_dt_cr_mgmt::DATE as rlse_dt_cr_mgmt,
    rqst_delv_dt::DATE as rqst_delv_dt,
    route::VARCHAR(6) as route,
    sls_doc::VARCHAR(10) as sls_doc,
    sls_doc_cat::VARCHAR(2) as sls_doc_cat,
    sls_doc_itm::NUMBER(18,0) as sls_doc_itm,
    sls_doc_typ::VARCHAR(4) as sls_doc_typ,
    sls_emp_hist::NUMBER(18,0) as sls_emp_hist,
    sls_org::VARCHAR(4) as sls_org,
    sls_doc_itm_cat::VARCHAR(4) as sls_doc_itm_cat,
    ship_to_prty::VARCHAR(10) as ship_to_prty,
    sold_to_prty::VARCHAR(10) as sold_to_prty,
    bill_qty_cse::NUMBER(15,4) as bill_qty_cse,
    bill_qty_pc::NUMBER(15,4) as bill_qty_pc,
    bill_qty_difot::NUMBER(15,4) as bill_qty_difot,
    bill_qty_otif::NUMBER(15,4) as bill_qty_otif,
    bill_qty_sls_uom::NUMBER(15,4) as bill_qty_sls_uom,
    cnfrm_qty_difot::NUMBER(15,4) as cnfrm_qty_difot,
    cnfrm_qty_pc::NUMBER(15,4) as cnfrm_qty_pc,
    delv_qty_cse::NUMBER(15,4) as delv_qty_cse,
    delv_qty_pc::NUMBER(15,4) as delv_qty_pc,
    delv_qty_sls_uom::NUMBER(15,4) as delv_qty_sls_uom,
    est_nts::NUMBER(15,4) as est_nts,
    nts_bill::NUMBER(15,4) as nts_bill,
    net_invc_sls::NUMBER(15,4) as net_invc_sls,
    fut_sls_qty::NUMBER(15,4) as fut_sls_qty,
    gros_trd_sls::NUMBER(15,4) as gros_trd_sls,
    net_amt::NUMBER(15,4) as net_amt,
    net_prc::NUMBER(15,4) as net_prc,
    net_bill_val::NUMBER(15,4) as net_bill_val,
    net_ord_val::NUMBER(15,4) as net_ord_val,
    ord_qty_cse::NUMBER(15,4) as ord_qty_cse,
    ord_qty_pc::NUMBER(15,4) as ord_qty_pc,
    ord_pc_qty::NUMBER(15,4) as ord_pc_qty,
    ord_sls_qty::NUMBER(15,4) as ord_sls_qty,
    tran_ldtm::NUMBER(15,4) as tran_ldtm,
    unspp_qty::NUMBER(15,4) as unspp_qty,
    unspp_val::NUMBER(15,4) as unspp_val,
    vol_delv::NUMBER(15,4) as vol_delv,
    vol_ord::NUMBER(20,4) as vol_ord,
    cal_day::DATE as cal_day,
    base_uom::VARCHAR(4) as base_uom,
    curr_key::VARCHAR(5) as curr_key,
    doc_curr::VARCHAR(5) as doc_curr,
    sls_unit::VARCHAR(4) as sls_unit,
    fisc_yr::VARCHAR(10) as fisc_yr,
    fisc_yr_src::VARCHAR(10) as fisc_yr_src,
    current_timestamp()::timestamp_ntz(9) AS crt_dttm,
    current_timestamp()::timestamp_ntz(9) AS updt_dttm
  FROM source
)

select * from final