
with source as (
    select * from  {{ ref('aspwks_integration__wks_edw_inventory_fact') }}
),
final as(
    select 
    lcl_crncy::VARCHAR(5) as lcl_crncy,
    base_unit::VARCHAR(3) as base_unit,
    matl_no::VARCHAR(18) as matl_no,
    strg_loc::VARCHAR(4) as strg_loc,
    stk_type::VARCHAR(1) as stk_type,
    stk_cat::VARCHAR(1) as stk_cat,
    co_cd::VARCHAR(4) as co_cd,
    matl_plnt_view::VARCHAR(18) as matl_plnt_view,
    btch_num::VARCHAR(10) as btch_num,
    plnt::VARCHAR(4) as plnt,
    whse_num::VARCHAR(3) as whse_num,
    strg_bin::VARCHAR(10) as strg_bin,
    strg_type::VARCHAR(3) as strg_type,
    spl_stck_val::VARCHAR(1) as spl_stck_val,
    spl_stck_indica::VARCHAR(1) as spl_stck_indica,
    doc_dt::DATE as doc_dt,
    valut_cls::VARCHAR(4) as valut_cls,
    valut_area::VARCHAR(4) as valut_area,
    valut_type::VARCHAR(10) as valut_type,
    pstng_dt::DATE as pstng_dt,
    cal_day::DATE as cal_day,
    wh_mstr::VARCHAR(18) as wh_mstr,
    vers::VARCHAR(3) as vers,
    val_type::NUMBER(18,0) as val_type,
    vend::VARCHAR(10) as vend,
    sold_to_prty::VARCHAR(10) as sold_to_prty,
    mvmt_ind_sec::VARCHAR(1) as mvmt_ind_sec,
    crncy::VARCHAR(5) as crncy,
    fisc_yr_vrnt::VARCHAR(2) as fisc_yr_vrnt,
    fisc_yr::NUMBER(18,0) as fisc_yr,
    cal_yr::NUMBER(18,0) as cal_yr,
    cal_mo::NUMBER(18,0) as cal_mo,
    qtr::NUMBER(18,0) as qtr,
    cal_yr_qtr::NUMBER(18,0) as cal_yr_qtr,
    cal_yr_wk::NUMBER(18,0) as cal_yr_wk,
    pstng_per::NUMBER(18,0) as pstng_per,
    half_yr::NUMBER(18,0) as half_yr,
    wkday::NUMBER(18,0) as wkday,
    fisc_yr_per::NUMBER(18,0) as fisc_yr_per,
    cal_yr_mon::NUMBER(18,0) as cal_yr_mon,
    stck_rec_val::NUMBER(19,2) as stck_rec_val,
    iss_stck_val::NUMBER(19,2) as iss_stck_val,
    iss_blok_qty::NUMBER(20,3) as iss_blok_qty,
    cng_stk_qty_iss::NUMBER(20,3) as cng_stk_qty_iss,
    iss_qty_qual::NUMBER(20,3) as iss_qty_qual,
    iss_qty_trst::NUMBER(20,3) as iss_qty_trst,
    rcpt_qty_blok::NUMBER(20,3) as rcpt_qty_blok,
    cns_stck_rcpt::NUMBER(20,3) as cns_stck_rcpt,
    rcpt_qty_qual::NUMBER(20,3) as rcpt_qty_qual,
    rcpt_qty_trst::NUMBER(20,3) as rcpt_qty_trst,
    iss_qty_scrap::NUMBER(20,3) as iss_qty_scrap,
    iss_val_scrap::NUMBER(19,2) as iss_val_scrap,
    rcpt_tot_stck::NUMBER(20,3) as rcpt_tot_stck,
    iss_tot_stck::NUMBER(20,3) as iss_tot_stck,
    iss_qty_stck_val::NUMBER(20,3) as iss_qty_stck_val,
    rec_qty_val_stck::NUMBER(20,3) as rec_qty_val_stck,
    vdr_cnsgnmnt_stck_cnval::NUMBER(19,2) as vdr_cnsgnmnt_stck_cnval,
    rec_val_q_stck::NUMBER(19,2) as rec_val_q_stck,
    rec_val_blok::NUMBER(19,2) as rec_val_blok,
    iss_val_blok::NUMBER(19,2) as iss_val_blok,
    iss_val_q_stck::NUMBER(19,2) as iss_val_q_stck,
    rec_val_trst::NUMBER(19,2) as rec_val_trst,
    iss_val_trst::NUMBER(19,2) as iss_val_trst,
    iss_val_cons_stck::NUMBER(19,2) as iss_val_cons_stck,
    rcpt_val_cons_stk::NUMBER(19,2) as rcpt_val_cons_stk,
    bw_prch_val::NUMBER(19,2) as bw_prch_val,
    bw_amt_bunitm::NUMBER(20,3) as bw_amt_bunitm,
    delv_cost::NUMBER(19,2) as delv_cost,
    std_matl_cost::NUMBER(19,2) as std_matl_cost,
    prc_unit::NUMBER(20,3) as prc_unit,
    line_cnt::NUMBER(18,0) as line_cnt,
    current_timestamp()::timestamp_ntz(9) as crt_dttm,
    current_timestamp()::timestamp_ntz(9) as updt_dttm
    from source

)

select * from final