{{
    config(
        materialized="incremental",
        incremental_strategy= "merge",
        unique_key=  ['cust_num','sls_org','dstr_chnl', 'div'],
        merge_exclude_columns=["crt_dttm"]
    )
}}

with wks_edw_customer_sales_dim as (
    select * from {{ ref('aspwks_integration__wks_edw_customer_sales_dim') }}
),
itg_cust_sls_attr as (
    select  
        division,
        distr_chan,
        salesorg,
        cust_sales,
        cur_sls_emp,
        lcl_cust_grp_1,
        lcl_cust_grp_2,
        lcl_cust_grp_3,
        lcl_cust_grp_4,
        lcl_cust_grp_5,
        lcl_cust_grp_6,
        lcl_cust_grp_7,
        lcl_cust_grp_8,
        prc_proc,
        par_del,
        max_num_pa,
        prnt_cust_key,
        bnr_key,
        bnr_frmt_key,
        go_to_mdl_key,
        chnl_key,
        sub_chnl_key,
        segmt_key,
        cust_set_1,
        cust_set_2,
        cust_set_3,
        cust_set_4,
        cust_set_5
    from {{ ref('aspitg_integration__itg_cust_sls_attr') }}
),
transformed as ( 
    select 
        wks_edw_customer_sales_dim.clnt::varchar(3) as clnt,
        wks_edw_customer_sales_dim.cust_no::varchar(10) as cust_num,
        wks_edw_customer_sales_dim.sls_org::varchar(4) as sls_org,
        wks_edw_customer_sales_dim.dstr_chnl::varchar(2) as dstr_chnl,
        wks_edw_customer_sales_dim.div::varchar(2) as div,
        wks_edw_customer_sales_dim.obj_crt_prsn::varchar(12) as obj_crt_prsn,
        wks_edw_customer_sales_dim.rec_crt_dt::date as rec_crt_dt,
        wks_edw_customer_sales_dim.auth_grp::varchar(4) as auth_grp,
        wks_edw_customer_sales_dim.cust_del_flag::varchar(1) as cust_del_flag,
        wks_edw_customer_sales_dim.cust_stat_grp::varchar(1) as cust_stat_grp,
        wks_edw_customer_sales_dim.cust_ord_blk::varchar(2) as cust_ord_blk,
        wks_edw_customer_sales_dim.prc_pcdr_asgn::varchar(1) as prc_pcdr_asgn,
        wks_edw_customer_sales_dim.cust_grp::varchar(2) as cust_grp,
        wks_edw_customer_sales_dim.sls_dstrc::varchar(6) as sls_dstrc,
        wks_edw_customer_sales_dim.prc_grp::varchar(2) as prc_grp,
        wks_edw_customer_sales_dim.prc_list_typ::varchar(2) as prc_list_typ,
        wks_edw_customer_sales_dim.ord_prob_itm::number(18,0) as ord_prob_itm,
        wks_edw_customer_sales_dim.incoterm1::varchar(3) as incoterm1,
        wks_edw_customer_sales_dim.incoterm2::varchar(28) as incoterm2,
        wks_edw_customer_sales_dim.cust_delv_blk::varchar(2) as cust_delv_blk,
        wks_edw_customer_sales_dim.cmplt_delv_sls_ord::varchar(1) as cmplt_delv_sls_ord,
        wks_edw_customer_sales_dim.max_no_prtl_delv_allw_itm::number(1,0) as max_no_prtl_delv_allw_itm,
        wks_edw_customer_sales_dim.prtl_delv_itm_lvl::varchar(1) as prtl_delv_itm_lvl,
        wks_edw_customer_sales_dim.ord_comb_in::varchar(1) as ord_comb_in,
        wks_edw_customer_sales_dim.btch_splt_allw::varchar(1) as btch_splt_allw,
        wks_edw_customer_sales_dim.delv_prir::number(18,0) as delv_prir,
        wks_edw_customer_sales_dim.vend_acct_no::varchar(12) as vend_acct_num,
        wks_edw_customer_sales_dim.shipping_cond::varchar(2) as shipping_cond,
        wks_edw_customer_sales_dim.bill_blk_cust::varchar(2) as bill_blk_cust,
        wks_edw_customer_sales_dim.man_invc_maint::varchar(1) as man_invc_maint,
        wks_edw_customer_sales_dim.invc_dt::varchar(2) as invc_dt,
        wks_edw_customer_sales_dim.invc_list_sched::varchar(2) as invc_list_sched,
        wks_edw_customer_sales_dim.cost_est_in::varchar(1) as cost_est_in,
        wks_edw_customer_sales_dim.val_lmt_cost_est::number(13,2) as val_lmt_cost_est,
        wks_edw_customer_sales_dim.crncy::varchar(5) as crncy_key,
        wks_edw_customer_sales_dim.cust_clas::varchar(2) as cust_clas,
        wks_edw_customer_sales_dim.acct_asgnmt_grp::varchar(2) as acct_asgnmt_grp,
        wks_edw_customer_sales_dim.delv_plnt::varchar(4) as delv_plnt,
        wks_edw_customer_sales_dim.sls_grp::varchar(3) as sls_grp,
        wks_edw_customer_sales_dim.sls_grp_desc::varchar(40) as sls_grp_desc,
        wks_edw_customer_sales_dim.sls_ofc::varchar(4) as sls_ofc,
        wks_edw_customer_sales_dim.sls_ofc_desc::varchar(40) as sls_ofc_desc,
        wks_edw_customer_sales_dim.itm_props::varchar(10) as itm_props,
        wks_edw_customer_sales_dim.cust_grp1::varchar(3) as cust_grp1,
        wks_edw_customer_sales_dim.cust_grp2::varchar(3) as cust_grp2,
        wks_edw_customer_sales_dim.cust_grp3::varchar(3) as cust_grp3,
        wks_edw_customer_sales_dim.cust_grp4::varchar(3) as cust_grp4,
        wks_edw_customer_sales_dim.cust_grp5::varchar(3) as cust_grp5,
        wks_edw_customer_sales_dim.cust_rebt_in::varchar(1) as cust_rebt_in,
        wks_edw_customer_sales_dim.rebt_indx_cust_strt_prd::date as rebt_indx_cust_strt_prd,
        wks_edw_customer_sales_dim.exch_rt_typ::varchar(4) as exch_rt_typ,
        wks_edw_customer_sales_dim.prc_dtrmn_id::varchar(1) as prc_dtrmn_id,
        wks_edw_customer_sales_dim.prod_attr_id1::varchar(1) as prod_attr_id1,
        wks_edw_customer_sales_dim.prod_attr_id2::varchar(1) as prod_attr_id2,
        wks_edw_customer_sales_dim.prod_attr_id3::varchar(1) as prod_attr_id3,
        wks_edw_customer_sales_dim.prod_attr_id4::varchar(1) as prod_attr_id4,
        wks_edw_customer_sales_dim.prod_attr_id5::varchar(1) as prod_attr_id5,
        wks_edw_customer_sales_dim.prod_attr_id6::varchar(1) as prod_attr_id6,
        wks_edw_customer_sales_dim.prod_attr_id7::varchar(1) as prod_attr_id7,
        wks_edw_customer_sales_dim.prod_attr_id8::varchar(1) as prod_attr_id8,
        wks_edw_customer_sales_dim.prod_attr_id9::varchar(1) as prod_attr_id9,
        wks_edw_customer_sales_dim.prod_attr_id10::varchar(1) as prod_attr_id10,
        wks_edw_customer_sales_dim.pymt_key_term::varchar(4) as pymt_key_term,
        wks_edw_customer_sales_dim.persnl_num::number(8,0) as persnl_num,
        current_timestamp()::timestamp_ntz(9) as crt_dttm ,
        current_timestamp()::timestamp_ntz(9) as updt_dttm,
        itg_cust_sls_attr.cur_sls_emp::number(8,0) as cur_sls_emp,
        itg_cust_sls_attr.lcl_cust_grp_1::varchar(10) as lcl_cust_grp_1,
        itg_cust_sls_attr.lcl_cust_grp_2::varchar(10) as lcl_cust_grp_2,
        itg_cust_sls_attr.lcl_cust_grp_3::varchar(10) as lcl_cust_grp_3,
        itg_cust_sls_attr.lcl_cust_grp_4::varchar(10) as lcl_cust_grp_4,
        itg_cust_sls_attr.lcl_cust_grp_5::varchar(10) as lcl_cust_grp_5,
        itg_cust_sls_attr.lcl_cust_grp_6::varchar(10) as lcl_cust_grp_6,
        itg_cust_sls_attr.lcl_cust_grp_7::varchar(10) as lcl_cust_grp_7,
        itg_cust_sls_attr.lcl_cust_grp_8::varchar(10) as lcl_cust_grp_8,
        itg_cust_sls_attr.prc_proc::varchar(1) as prc_proc,
        itg_cust_sls_attr.par_del::varchar(1) as par_del,
        itg_cust_sls_attr.max_num_pa::varchar(1) as max_num_pa,
        itg_cust_sls_attr.prnt_cust_key::varchar(12) as prnt_cust_key,
        itg_cust_sls_attr.bnr_key::varchar(12) as bnr_key,
        itg_cust_sls_attr.bnr_frmt_key::varchar(12) as bnr_frmt_key,
        itg_cust_sls_attr.go_to_mdl_key::varchar(12) as go_to_mdl_key,
        itg_cust_sls_attr.chnl_key::varchar(12) as chnl_key,
        itg_cust_sls_attr.sub_chnl_key::varchar(12) as sub_chnl_key,
        itg_cust_sls_attr.segmt_key::varchar(12) as segmt_key,
        itg_cust_sls_attr.cust_set_1::varchar(12) as cust_set_1,
        itg_cust_sls_attr.cust_set_2::varchar(12) as cust_set_2,
        itg_cust_sls_attr.cust_set_3::varchar(12) as cust_set_3,
        itg_cust_sls_attr.cust_set_4::varchar(12) as cust_set_4,
        itg_cust_sls_attr.cust_set_5::varchar(12) as cust_set_5
    from wks_edw_customer_sales_dim
    left join itg_cust_sls_attr on 
    wks_edw_customer_sales_dim.div=itg_cust_sls_attr.division
    and itg_cust_sls_attr.distr_chan=wks_edw_customer_sales_dim.dstr_chnl
    and itg_cust_sls_attr.salesorg=wks_edw_customer_sales_dim.sls_org
    and itg_cust_sls_attr.cust_sales=wks_edw_customer_sales_dim.cust_no
)

{% if is_incremental() %}
,
filtered_csd as (
    select * from {{ this }} as csd where concat(cust_num,'_',sls_org,'_',dstr_chnl,'_',div) not in (select concat(cust_num,'_',sls_org,'_',dstr_chnl,'_',div) from transformed)
),
transformed_csd as (
    select 
        filtered_csd.clnt,
        filtered_csd.cust_num,
        filtered_csd.sls_org,
        filtered_csd.dstr_chnl,
        filtered_csd.div,
        filtered_csd.obj_crt_prsn,
        filtered_csd.rec_crt_dt,
        filtered_csd.auth_grp,
        filtered_csd.cust_del_flag,
        filtered_csd.cust_stat_grp,
        filtered_csd.cust_ord_blk,
        filtered_csd.prc_pcdr_asgn,
        filtered_csd.cust_grp,
        filtered_csd.sls_dstrc,
        filtered_csd.prc_grp,
        filtered_csd.prc_list_typ,
        filtered_csd.ord_prob_itm,
        filtered_csd.incoterm1,
        filtered_csd.incoterm2,
        filtered_csd.cust_delv_blk,
        filtered_csd.cmplt_delv_sls_ord,
        filtered_csd.max_no_prtl_delv_allw_itm,
        filtered_csd.prtl_delv_itm_lvl,
        filtered_csd.ord_comb_in,
        filtered_csd.btch_splt_allw,
        filtered_csd.delv_prir,
        filtered_csd.vend_acct_num,
        filtered_csd.shipping_cond,
        filtered_csd.bill_blk_cust,
        filtered_csd.man_invc_maint,
        filtered_csd.invc_dt,
        filtered_csd.invc_list_sched,
        filtered_csd.cost_est_in,
        filtered_csd.val_lmt_cost_est,
        filtered_csd.crncy_key,
        filtered_csd.cust_clas,
        filtered_csd.acct_asgnmt_grp,
        filtered_csd.delv_plnt,
        filtered_csd.sls_grp,
        filtered_csd.sls_grp_desc,
        filtered_csd.sls_ofc,
        filtered_csd.sls_ofc_desc,
        filtered_csd.itm_props,
        filtered_csd.cust_grp1,
        filtered_csd.cust_grp2,
        filtered_csd.cust_grp3,
        filtered_csd.cust_grp4,
        filtered_csd.cust_grp5,
        filtered_csd.cust_rebt_in,
        filtered_csd.rebt_indx_cust_strt_prd,
        filtered_csd.exch_rt_typ,
        filtered_csd.prc_dtrmn_id,
        filtered_csd.prod_attr_id1,
        filtered_csd.prod_attr_id2,
        filtered_csd.prod_attr_id3,
        filtered_csd.prod_attr_id4,
        filtered_csd.prod_attr_id5,
        filtered_csd.prod_attr_id6,
        filtered_csd.prod_attr_id7,
        filtered_csd.prod_attr_id8,
        filtered_csd.prod_attr_id9,
        filtered_csd.prod_attr_id10,
        filtered_csd.pymt_key_term,
        filtered_csd.persnl_num,
        current_timestamp()  as crt_dttm ,
        current_timestamp()  as updt_dttm,
        itg_cust_sls_attr.cur_sls_emp, 
        itg_cust_sls_attr.lcl_cust_grp_1, 
        itg_cust_sls_attr.lcl_cust_grp_2, 
        itg_cust_sls_attr.lcl_cust_grp_3, 
        itg_cust_sls_attr.lcl_cust_grp_4, 
        itg_cust_sls_attr.lcl_cust_grp_5, 
        itg_cust_sls_attr.lcl_cust_grp_6, 
        itg_cust_sls_attr.lcl_cust_grp_7, 
        itg_cust_sls_attr.lcl_cust_grp_8, 
        itg_cust_sls_attr.prc_proc, 
        itg_cust_sls_attr.par_del, 
        itg_cust_sls_attr.max_num_pa, 
        itg_cust_sls_attr.prnt_cust_key, 
        itg_cust_sls_attr.bnr_key, 
        itg_cust_sls_attr.bnr_frmt_key, 
        itg_cust_sls_attr.go_to_mdl_key, 
        itg_cust_sls_attr.chnl_key, 
        itg_cust_sls_attr.sub_chnl_key, 
        itg_cust_sls_attr.segmt_key, 
        itg_cust_sls_attr.cust_set_1, 
        itg_cust_sls_attr.cust_set_2, 
        itg_cust_sls_attr.cust_set_3, 
        itg_cust_sls_attr.cust_set_4, 
        itg_cust_sls_attr.cust_set_5
    from filtered_csd
    left join itg_cust_sls_attr on 
    filtered_csd.div=itg_cust_sls_attr.division
    and itg_cust_sls_attr.distr_chan=filtered_csd.dstr_chnl
    and itg_cust_sls_attr.salesorg=filtered_csd.sls_org
    and itg_cust_sls_attr.cust_sales=filtered_csd.cust_num
)
{% endif %}

--Final select
select * from transformed

--Union logic added here to compensate update on records which exist in edw_customer_sales_dim and not in wks_edw_customer_sales_dim
{% if is_incremental() %}
union 
select * from transformed_csd
{% endif %}