{{
    config(
        sql_header="ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized="incremental",
        incremental_strategy = "merge",
        unique_key=["plnt","matl_plnt_view"],
        merge_exclude_columns = ["crt_dttm"]
    )
}}

with 

source as (

    select * from {{ ref('aspwks_integration__wks_edw_material_plant_dim') }}
),

final as (
    select
        plnt :: varchar(4) as plnt,
        matl_plnt_view :: varchar(18) as matl_plnt_view,
        abc_in :: varchar(1) as abc_in,
        del_fl :: varchar(1) as del_flg,
        mrp_type :: varchar(2) as mrp_type,
        gr_prcsg_time,
        mrp_ctl :: varchar(3) as mrp_ctl,
        time_unit :: varchar(3) as time_unit,
        plan_delv_time,
        prdtn_schd :: varchar(3) as prdtn_schd,
        cntl_area :: varchar(4) as cntl_area,
        prctr :: varchar(10) as prft_ctr,
        prchsng_gr :: varchar(3) as prchsng_gr,
        tot_rl_time_repl,
        uom_basis_mov_ave :: varchar(3) as uom_basis_mov_ave,
        base_unit :: varchar(3) as base_unit,
        ctry :: varchar(3) as ctry_key,
        valut_cls :: varchar(4) as valut_cls,
        cncnc :: varchar(5) as crncy_key,
        std_matl_cost,
        spl_prcmt :: varchar(2) as spl_prcmt,
        min_lot_size,
        rd_val_po_qty,
        matl :: varchar(18) as matl_num,
        vend :: varchar(10) as vend,
        prcmt_type :: varchar(1) as prcmt_type,
        predecessor :: varchar(18) as predecessor,
        base_qty_matplant as base_qty_matl_plnt,
        cost_lot_size_in,
        ld_gr :: varchar(4) as ld_gr,
        mil_goods_ind :: varchar(1) as mil_goods_ind,
        availability_check :: varchar(2) as availability_check,
        mm_pp_sts :: varchar(2) as mm_pp_sts,
        auto_po_allw :: varchar(1) as auto_po_allw,
        stk_type :: varchar(1) as stk_type,
        src_list_ind :: varchar(1) as src_list_ind,
        qta_usg :: varchar(1) as qta_usg,
        mrp_grp :: varchar(4) as mrp_grp,
        reordr_pt_mat_plant as reordr_pt_matl_plnt,
        plng_time_fence,
        plng_cyc :: varchar(3) as plng_cyc,
        lot_size_mat_plan :: varchar(2) as lot_size_matl_plan,
        max_lot_size,
        fx_lot_size_zbstfe,
        max_stk_lvl,
        cyc_time :: varchar(3) as cyc_time,
        btch_ent :: varchar(1) as btch_ent,
        iss_strg_loc :: varchar(4) as iss_strg_loc,
        backflush_ind :: varchar(1) as backflush_ind,
        strge_loc_ext_proc :: varchar(4) as strge_loc_ext_proc,
        plng_cal :: varchar(3) as plng_cal,
        sched_mrgn_key :: varchar(3) as sched_mrgn_key,
        sfty_stk,
        cvge_prfl :: varchar(3) as cvge_prfl,
        per_in :: varchar(1) as per_in,
        strtgy_gr :: varchar(2) as strtgy_gr,
        cnsmptn_mode :: varchar(1) as cnsmptn_mode,
        cnsmptn_per_bw,
        cnsmptn_per_fw,
        alt_bom :: varchar(1) as alt_bom,
        prdtn_unit :: varchar(3) as prdtn_unit,
        prdtn_sched_pro :: varchar(6) as prdtn_sched_pro,
        tlrnc_under_delv :: varchar(4) as tlrnc_under_delv,
        overdeliv_tlrnc :: varchar(4) as overdeliv_tlrnc,
        unit_iss :: varchar(3) as unit_iss,
        cc_phys_inv :: varchar(1) as cc_phys_inv,
        insp_intv :: varchar(5) as insp_intv,
        cntl_key :: varchar(8) as cntl_key,
        cert_type :: varchar(4) as cert_type,
        qm_sys_req :: varchar(4) as qm_sys_req,
        spec_proc_cst :: varchar(2) as spec_proc_cst,
        var_key :: varchar(6) as var_key,
        prc_cntl :: varchar(1) as prc_cntl,
        mvg_prc,
        devaluation_ind,
        prod_cost_ind :: varchar(1) as prod_cost_ind,
        orig_gr :: varchar(4) as orig_gr,
        matl_orig_ind :: varchar(1) as matl_orig_ind,
        fut_pind_prc,
        fut_pind_prc_1,
        plan_prc_dt,
        cost_ovhd_grp :: varchar(10) as cost_ovhd_grp,
        prc_unit,
        mrp_ctl_zmrp :: varchar(3) as mrp_ctl_zmrp,
        lunch_dt,
        npi_id :: varchar(1) as npi_id,
        prev_pind_prc,
        fut_pind_prc_2,
        plan_prc_dt_2,
        fut_pind_prc_3,
        plan_prc_dt_3,
        npi_launch_wk,
        npi_launch_mo,
        sku_sgmnt :: varchar(1) as sku_sgmnt,
        successor_on_going :: varchar(18) as successor_on_going,
        sui_in :: varchar(1) as sui_in,
        toll_mkup_cost,
        intco_mkup,
        act_sku_in :: varchar(1) as act_sku_in,
        snp_plnr :: varchar(3) as snp_plnr,
        transpotatn_plnr :: varchar(3) as transpotatn_plnr,
        auto_tlb_off :: varchar(1) as auto_tlb_off,
        sfty_stk_min_in :: varchar(4) as sfty_stk_min_in,
        sfty_stk_max_in_zmax_stck :: varchar(4) as sfty_stk_max_in_zmax_stck,
        rfs_in :: varchar(1) as rfs_in,
        bulk_exp :: varchar(4) as bulk_exp,
        dmand_plnr :: varchar(3) as dmand_plnr,
        dmand_prfl :: varchar(10) as dmand_prfl,
        trgt_days_supl_zday :: varchar(3) as trgt_days_supl_zday,
        min_shlf_lif :: varchar(4) as min_shlf_lif,
        gi_prcsg_time :: varchar(3) as gi_prcsg_time,
        pp_ds_hrzn_zppds :: varchar(4) as pp_ds_hrzn_zppds,
        srvc_lvl,
        do_not_cost :: varchar(1) as do_not_cost,
        vld_from_dt,
        maint_sts :: varchar(15) as maint_sts,
        rd_val,
        snp_prdtn_horiz :: varchar(3) as snp_prdtn_horiz,
        snp_prod_horiz_perd :: varchar(2) as snp_prod_horiz_perd,
        sfty_stk_res_percentage_zsstk :: varchar(4) as sfty_stk_res_percentage_zsstk,
        snp_stk_trn_hor :: varchar(3) as snp_stk_trn_hor,
        snp_stk_trn_hor_peri :: varchar(3) as snp_stk_trn_hor_peri,
        rglt_lic :: varchar(20) as rglt_lic,
        sfty_stk_meth :: varchar(2) as sfty_stk_meth,
        snp_checkg_hor,
        per_fact,
        use_per_fact :: varchar(1) as use_per_fact,
        dyn_peg_max_bkwd,
        push_dstn :: varchar(1) as push_dstn,
        cnsdr_sls_ordr :: varchar(1) as cnsdr_sls_ordr,
        cnsdr_fcst :: varchar(1) as cnsdr_fcst,
        atd_rcpt :: varchar(3) as atd_rcpt,
        atd_iss :: varchar(3) as atd_iss,
        pegging_strtgy,
        dmand_fcast_err_percentage,
        fair_shr_rule :: varchar(2) as fair_shr_rule,
        pull_depl_hor,
        push_depl_hor,
        prdtn_cost,
        max_earliness,
        max_lateness,
        strg_costs_prod,
        uom :: varchar(3) as uom,
        fx_lot_size,
        exact_lot_size :: varchar(1) as exact_lot_size,
        per_type :: varchar(1) as per_type,
        nr_per_cap,
        pp_ds_hrzn,
        bulk_exp_dur :: varchar(4) as bulk_exp_dur,
        apo_prod_plnr :: varchar(3) as apo_prod_plnr,
        fix_stk_tfr :: varchar(1) as fix_stk_tfr,
        delay_pnlty,
        max_delay,
        non_del_penal,
        snp_prdtn_horiz_zprodh,
        npi_in_apo,
        std_mat_cost_wo_pu as std_matl_cost_wo_pu,
        crt_on,
        prod_type_apo,
        mstr_cd :: varchar(18) as mstr_cd,
        copy_hist_apo :: varchar(1) as copy_hist_apo,
        prod_classftn :: varchar(2) as prod_classftn,
        fcst_indc_apo :: varchar(1) as fcst_indc_apo,
        jit_in :: varchar(1) as jit_in,
        tot_rl_time,
        sfty_stk_min_in_zminstk :: varchar(4) as sfty_stk_min_in_zminstk,
        sfty_stk_max_in :: varchar(4) as sfty_stk_max_in,
        trgt_days_supl :: varchar(3) as trgt_days_supl,
        srvc_lvl_zservlv,
        dmand_fcast_err_percentage_zfedem,
        fisc_yr_vrnt :: varchar(2) as fisc_yr_vrnt,
        cost_yr,
        fut_std_prc,
        med_desc :: varchar(150) as med_desc,
        current_timestamp()::timestamp_ntz(9) as crt_dttm,
        current_timestamp()::timestamp_ntz(9) as updt_dttm
    from source
)

select * from final