with VW_DIM_GMC_ATTRIBUTE_MAPPINGS as(
    select * from {{ source('GLOBALMASTER_ACCESS','VW_DIM_GMC_ATTRIBUTE_MAPPINGS') }}
),
VW_DIM_GMC_GLOBAL_CATEGORY_HIER as(
    select * from {{ source('GLOBALMASTER_ACCESS','VW_DIM_GMC_GLOBAL_CATEGORY_HIER') }}
),
VW_DIM_GMC_GLOBAL_BRAND_HIER as(
    select * from {{ source('GLOBALMASTER_ACCESS','VW_DIM_GMC_GLOBAL_BRAND_HIER') }}
),
VW_DIM_GMC_PROFIT_CENTER_HIER as(
    select * from {{ source('GLOBALMASTER_ACCESS','VW_DIM_GMC_PROFIT_CENTER_HIER') }}
),
VW_DIM_GMC_SKU_MAPPINGS as(
    select * from {{ source('GLOBALMASTER_ACCESS','VW_DIM_GMC_SKU_MAPPINGS') }}
),

transformed as (
Select 
b.GMC_DESCRIPTION	as	GMC_DESCRIPTION	,
b.GMC_CODE	as	GMC_CODE	,
b.GMC_SUBCATEGORY_CODE	as	GMC_SUBCATEGORY_CODE	,
b.GMC_SUBCATEGORY_NAME	as	GMC_SUBCATEGORY_NAME	,
b.GMC_BRAND_CODE	as	GMC_LABEL_BRAND_CODE	,
b.GMC_BRAND_NAME	as	GMC_LABEL_BRAND_NAME	,
b.GMC_SUBBRAND_CODE	as	GMC_LABEL_SUBBRAND_CODE	,
b.GMC_SUBBRAND_NAME	as	GMC_LABEL_SUBBRAND_NAME	,
b.GMC_VARIANT_CODE	as	GMC_VARIANT_CODE	,
b.GMC_VARIANT_NAME	as	GMC_VARIANT_NAME	,
b.GMC_SUBVARIANT_CODE	as	GMC_SUBVARIANT_CODE	,
b.GMC_SUBVARIANT_NAME	as	GMC_SUBVARIANT_NAME	,
b.GMC_FLAVOR_CODE	as	GMC_FLAVOR_CODE	,
b.GMC_FLAVOR_NAME	as	GMC_FLAVOR_NAME	,
b.GMC_INGREDIENT_CODE	as	GMC_INGREDIENT_CODE	,
b.GMC_INGREDIENT_NAME	as	GMC_INGREDIENT_NAME	,
b.GMC_APPLICATION_CODE	as	GMC_APPLICATION_CODE	,
b.GMC_APPLICATION_NAME	as	GMC_APPLICATION_NAME	,
b.GMC_LENGTH_STRENGTH_CODE	as	GMC_LENGTH_STRENGTH_CODE	,
b.GMC_LENGTH_STRENGTH_NAME	as	GMC_LENGTH_STRENGTH_NAME	,
b.GMC_SHAPE_CODE	as	GMC_SHAPE_CODE	,
b.GMC_SHAPE_NAME	as	GMC_SHAPE_NAME	,
b.GMC_SPF_CONCENTRATION_CODE	as	GMC_SPF_CONCENTRATION_CODE	,
b.GMC_SPF_CONCENTRATION_NAME	as	GMC_SPF_CONCENTRATION_NAME	,
b.GMC_COVER_PRODUCT_TYPE_CODE	as	GMC_COVER_PRODUCT_TYPE_CODE	,
b.GMC_COVER_PRODUCT_TYPE_NAME	as	GMC_COVER_PRODUCT_TYPE_NAME	,
b.GMC_FORM_CODE	as	GMC_FORM_CODE	,
b.GMC_FORM_NAME	as	GMC_FORM_NAME	,
b.GMC_SIZE_CODE	as	GMC_SIZE_CODE	,
b.GMC_SIZE_NAME	as	GMC_SIZE_NAME	,
b.GMC_CHARACTERS_SPECIAL_EDITION_CODE	as	GMC_CHARACTERS_SPECIAL_EDITION_CODE	,
b.GMC_CHARACTERS_SPECIAL_EDITION_NAME	as	GMC_CHARACTERS_SPECIAL_EDITION_NAME	,
b.GMC_PACKAGE_CODE	as	GMC_PACKAGE_CODE	,
b.GMC_PACKAGE_NAME	as	GMC_PACKAGE_NAME	,
b.GMC_UOM_CODE	as	GMC_UOM_CODE	,
b.GMC_UOM_NAME	as	GMC_UOM_NAME	,
b.P4_BRAND_CATEGORY_CODE	as	P4_BRAND_CATEGORY_CODE	,
b.P4_BRAND_CATEGORY	as	P4_BRAND_CATEGORY	,
b.B2_SUBBRAND_CODE	as	B2_SUB_BRAND_CODE	,
b.B2_SUBBRAND	as	B2_SUB_BRAND	,
b.C5_SUBCATEGORY_CODE	as	C5_SUB_CATEGORY_CODE	,
b.C5_SUBCATEGORY	as	C5_SUB_CATEGORY	,
c.C1_BUSINESS_SEGMENT_CODE	as	C1_BUSINESS_SEGMENT_CODE	,
c.C1_BUSINESS_SEGMENT	as	C1_BUSINESS_SEGMENT	,
c.C2_BUSINESS_SUBSEGMENT_CODE	as	C2_BUSINESS_SUBSEGMENT_CODE	,
c.C2_BUSINESS_SUBSEGMENT	as	C2_BUSINESS_SUBSEGMENT	,
c.C3_NEED_STATE_CODE	as	C3_NEED_STATE_CODE	,
c.C3_NEED_STATE	as	C3_NEED_STATE	,
c.C4_CATEGORY_CODE	as	C4_CATEGORY_CODE	,
c.C4_CATEGORY	as	C4_CATEGORY	,
c.C5_SUBCATEGORY_CODE	as	C5_SUBCATEGORY_CODE	,
c.C5_SUBCATEGORY	as	C5_SUBCATEGORY	,
d.B1_BRAND_CODE	as	B1_BRAND_CODE	,
d.B1_BRAND	as	B1_BRAND	,
d.B2_SUBBRAND_CODE	as	B2_SUBBRAND_CODE	,
d.B2_SUBBRAND	as	B2_SUBBRAND	,
e.P1_CODE	as	P1_CODE	,
e.P1_BUSINESS_SEGMENT	as	P1_BUSINESS_SEGMENT	,
e.PS_CODE	as	PS_CODE	,
e.PS_BUSINESS_SUBSEGMENT	as	PS_BUSINESS_SUBSEGMENT	,
e.P2_CODE	as	P2_CODE	,
e.P2_NEED_STATE	as	P2_NEED_STATE	,
e.P3_CODE	as	P3_CODE	,
e.P3_BRAND_CATEGORY	as	P3_BRAND_CATEGORY	,
e.P4_CODE	as	P4_CODE	,
e.P4_BRAND_CATEGORY_PLACEHOLDER	as	P4_BRAND_CATEGORY_PLACEHOLDER	
    
FROM VW_DIM_GMC_SKU_MAPPINGS a 
LEFT OUTER JOIN VW_DIM_GMC_ATTRIBUTE_MAPPINGS b 
ON a.GMC_CODE = b.GMC_CODE 
LEFT OUTER JOIN VW_DIM_GMC_GLOBAL_CATEGORY_HIER c 
ON b.C5_SUBCATEGORY_CODE = c.C5_SUBCATEGORY_CODE 
LEFT OUTER JOIN VW_DIM_GMC_GLOBAL_BRAND_HIER d 
ON b.B2_SUBBRAND_CODE = d.B2_SUBBRAND_CODE 
LEFT OUTER JOIN VW_DIM_GMC_PROFIT_CENTER_HIER e
ON b.P4_BRAND_CATEGORY_CODE = e.P4_CODE 
)
select * from transformed