{{
    config(
        sql_header= ""
    )
}}
with source as(
    select * from {{ ref('aspwks_integration__wks_edw_copa_plan_fact') }}
),
final as(
    SELECT
	fisc_yr_per::NUMBER(7,0) as fisc_yr_per,
    fisc_yr_vrnt::VARCHAR(2) as fisc_yr_vrnt,
    fisc_yr::NUMBER(4,0) as fisc_yr,
    cal_day::DATE as cal_day,
    pstng_per::NUMBER(3,0) as pstng_per,
    cal_yr_mo::NUMBER(6,0) as cal_yr_mo,
    cal_yr::NUMBER(4,0) as cal_yr,
    vers::VARCHAR(3) as vers,
    val_type::NUMBER(3,0) as val_type,
    co_cd::VARCHAR(4) as co_cd,
    cntl_area::VARCHAR(4) as cntl_area,
    prft_ctr::VARCHAR(10) as prft_ctr,
    sls_emp_hist::NUMBER(8,0) as sls_emp_hist,
    sls_org::VARCHAR(4) as sls_org,
    sls_grp::VARCHAR(3) as sls_grp,
    sls_off::VARCHAR(4) as sls_ofc,
    cust_grp::VARCHAR(2) as cust_grp,
    dstn_chnl::VARCHAR(2) as dstn_chnl,
    sls_dstrc::VARCHAR(6) as sls_dstrc,
    cust::VARCHAR(10) as cust_num,
    matl::VARCHAR(18) as matl_num,
    cust_sls_view::VARCHAR(10) as cust_sls_view,
    div::VARCHAR(2) as div,
    plnt::VARCHAR(4) as plnt,
    mercia_ref::VARCHAR(5) as mercia_ref,
    b3_base_prod::VARCHAR(3) as b3_base_prod,
    b4_vrnt::VARCHAR(3) as b4_vrnt,
    b5_put_up::VARCHAR(3) as b5_put_up,
    b1_mega_brnd::VARCHAR(3) as b1_mega_brnd,
    b2_brnd::VARCHAR(3) as b2_brnd,
    rgn::VARCHAR(3) as rgn,
    ctry::VARCHAR(3) as ctry_key,
    prod_minor::VARCHAR(18) as prod_minor,
    prod_maj::VARCHAR(18) as prod_maj,
    prod_fran::VARCHAR(18) as prod_fran,
    fran::VARCHAR(18) as fran,
    fran_grp::VARCHAR(18) as fran_grp,
    oper_grp::VARCHAR(18) as oper_grp,
    fisc_qtr::NUMBER(1,0) as fisc_qtr,
    matl2::VARCHAR(18) as matl2,
    bill_type::VARCHAR(4) as bill_typ,
    fisc_wk::DATE as fisc_wk,
    amt_grp_crcy::NUMBER(20,2) as amt_grp_crcy,
    amt_obj_crcy::NUMBER(20,2) as amt_obj_crcy,
    crncy::VARCHAR(5) as crncy_key,
    obj_crncy::VARCHAR(5) as obj_crncy,
    acct_num::VARCHAR(10) as acct_num,
    chrt_of_acct::VARCHAR(4) as chrt_acct,
    mgmt_entity::VARCHAR(6) as mgmt_entity,
    sls_prsn_respons::VARCHAR(30) as sls_prsn_respons,
    busn_area::VARCHAR(4) as busn_area,
    ga::NUMBER(20,2) as ga,
    tc::VARCHAR(5) as tc,
    matl_plnt_view::VARCHAR(18) as matl_plnt_view,
    qty::NUMBER(20,3) as qty,
    uom::VARCHAR(10) as uom,
    sls_vol_ieu::NUMBER(17,3) as sls_vol_ieu,
    un_sls_vol__ieu::VARCHAR(10) as un_sls_vol__ieu,
    bpt_dstn_chnl::VARCHAR(2) as bpt_dstn_chnl,
    measure_name::VARCHAR(100) as acct_hier_desc,
    measure_code::VARCHAR(40) as acct_hier_shrt_desc,
    catagory::VARCHAR(40) as category,
    freq::VARCHAR(40) as freq,
    current_timestamp()::timestamp_ntz(9) AS crt_dttm,
    current_timestamp()::timestamp_ntz(9) AS updt_dttm
  FROM source
)
select * from final