
with source as (
    select * from  {{ ref('aspwks_integration__wks_edw_inventory_fact') }}
),
final as(
    select 
    lcl_crncy,
    base_unit,
    matl_no,
    strg_loc,
    stk_type,
    stk_cat,
    co_cd,
    matl_plnt_view,
    btch_num,
    plnt,
    whse_num,
    strg_bin,
    strg_type,
    spl_stck_val,
    spl_stck_indica,
    doc_dt,
    valut_cls,
    valut_area,
    valut_type,
    pstng_dt,
    cal_day,
    wh_mstr,
    vers,
    val_type,
    vend,
    sold_to_prty,
    mvmt_ind_sec,
    crncy,
    fisc_yr_vrnt,
    fisc_yr,
    cal_yr,
    cal_mo,
    qtr,
    cal_yr_qtr,
    cal_yr_wk,
    pstng_per,
    half_yr,
    wkday,
    fisc_yr_per,
    cal_yr_mon,
    stck_rec_val,
    iss_stck_val,
    iss_blok_qty,
    cng_stk_qty_iss,
    iss_qty_qual,
    iss_qty_trst,
    rcpt_qty_blok,
    cns_stck_rcpt,
    rcpt_qty_qual,
    rcpt_qty_trst,
    iss_qty_scrap,
    iss_val_scrap,
    rcpt_tot_stck,
    iss_tot_stck,
    iss_qty_stck_val,
    rec_qty_val_stck,
    vdr_cnsgnmnt_stck_cnval,
    rec_val_q_stck,
    rec_val_blok,
    iss_val_blok,
    iss_val_q_stck,
    rec_val_trst,
    iss_val_trst,
    iss_val_cons_stck,
    rcpt_val_cons_stk,
    bw_prch_val,
    bw_amt_bunitm,
    delv_cost,
    std_matl_cost,
    prc_unit,
    line_cnt,
    current_timestamp()::timestamp_ntz(9) as crt_dttm,
    current_timestamp()::timestamp_ntz(9) as updt_dttm
    from source

)

select * from final