{{
    config(
        alias="edw_customer_base_dim",
        sql_header="ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized="incremental",
        incremental_strategy = "merge",
        unique_key=["cust_num"],
        merge_exclude_columns = ["crt_dttm"],
        tags=["daily"]
    )
}}

with 
source as (
    select * from {{ ref('aspwks_integration__wks_edw_customer_base_dim') }}
),
final as (
select
clnt as clnt,
cust_num_1 as cust_num,
nm as cust_nm,
addr as addr,
title as title,
cntrl_ordr_blk_cust as cntrl_ordr_blk_cust,
exp_train_stn as exp_train_stn,
train_stn as train_stn,
intnl_loc_num1 as intnl_loc_num1,
intnl_loc_num2 as intnl_loc_num2,
auth_grp as auth_grp,
indstr_key as indstr_key,
chk_dig_intnl_loc_num as chk_dig_intnl_loc_num,
data_comm_line_no as data_comm_line_no,
dt_on_rec_crt as dt_on_rec_crt,
nm_prsn_crt_obj as nm_prsn_crt_obj,
unld_pt_exist_ind as unld_pt_exist_ind,
cent_bill_blk_cust as cent_bill_blk_cust,
acct_num_mstr_rec_fisc_addr as acct_num_mstr_rec_fisc_addr,
wrk_num_cal as wrk_num_cal,
acct_num_alt_pyr as acct_num_alt_pyr,
grp_key as grp_key,
cust_acct_grp as cust_acct_grp,
cust_clsn as cust_clsn,
ctry_key as ctry_key,
acct_num_vend as acct_num_vend,
cent_delv_blk_cust as cent_delv_blk_cust,
city_coordnt as city_coordnt,
cent_del_fl_mstr_rec as cent_del_fl_mstr_rec,
nm_1 as nm_1,
nm_2 as nm_2,
nm_3 as nm_3,
nm_4 as nm_4,
nlsn_id as nlsn_id,
city as city,
dstrc as dstrc,
po_box as po_box,
po_box_pstl_cd as po_box_pstl_cd,
pstl_cd as pstl_cd,
rgn as rgn,
cnty_cd as cnty_cd,
city_cd as city_cd,
fcst_chnl as fcst_chnl,
srt_fld as srt_fld,
cent_pstng_blk as cent_pstng_blk,
lang_key as lang_key,
tax_num_1 as tax_num_1,
tax_num_2 as tax_num_2,
busn_ptnr_subj_eqlztn_tax_ind as busn_ptnr_subj_eqlztn_tax_ind,
liab_for_vat as liab_for_vat,
hs_num_and_street as hs_num_and_street,
telebox_num as telebox_num,
fst_phn_num as fst_phn_num,
sec_phn_num as sec_phn_num,
fax_num as fax_num,
teletex_num as teletex_num,
telex_num as telex_num,
trspn_zn_goods_delv as trspn_zn_goods_delv,
is_acct_one_time_acct_ind as is_acct_one_time_acct_ind,
alt_payee_doc_allw_ind as alt_payee_doc_allw_ind,
co_id_trad_ptnr as co_id_trad_ptnr,
vat_regs_num as vat_regs_num,
cmpt_ind as cmpt_ind,
sls_ptnr_ind as sls_ptnr_ind,
sls_prosp_ind as sls_prosp_ind,
for_cust_type4_ind as for_cust_type4_ind,
id_dflt_sold_to_prty as id_dflt_sold_to_prty,
in_cnsmr as in_cnsmr,
legal_sts as legal_sts,
indstr_cd_1 as indstr_cd_1,
indstr_cd_2 as indstr_cd_2,
indstr_cd_3 as indstr_cd_3,
indstr_cd_4 as indstr_cd_4,
indstr_cd_5 as indstr_cd_5,
init_cntct as init_cntct,
annl_sls_1 as annl_sls_1,
yr_for_sls_gvn as yr_for_sls_gvn,
crncy_sls_fig as crncy_sls_fig,
yr_num_emp as yr_num_emp,
yr_for_num_emp_gvn as yr_for_num_emp_gvn,
attr_1 as attr_1,
attr_2 as attr_2,
attr_3 as attr_3,
attr_4 as attr_4,
attr_5 as attr_5,
attr_6 as attr_6,
attr_7 as attr_7,
attr_8 as attr_8,
attr_9 as attr_9,
attr_10 as attr_10,
ntrl_prsn as ntrl_prsn,
annl_sls_2 as annl_sls_2,
tax_juris as tax_juris,
srch_term_match_cd_srch1 as srch_term_match_cd_srch1,
srch_term_match_cd_srch2 as srch_term_match_cd_srch2,
srch_term_match_cd_srch3 as srch_term_match_cd_srch3,
fisc_yr_vrnt as fisc_yr_vrnt,
usg_ind as usg_ind,
insp_carr_out_by_cust as insp_carr_out_by_cust,
insp_delv_note_after_outb_delv as insp_delv_note_after_outb_delv,
ref_acct_grp_one_time_acct as ref_acct_grp_one_time_acct,
po_box_city as po_box_city,
plnt as plnt,
data_med_exch_ind as data_med_exch_ind,
instr_key_data_med_exch as instr_key_data_med_exch,
sts_data_tfr_subsq_rlse as sts_data_tfr_subsq_rlse,
asgnmt_hier as asgnmt_hier,
pmt_blk as pmt_blk,
cust_grp as cust_grp,
id_mn_non_mil_use as id_mn_non_mil_use,
id_mn_mil_use as id_mn_mil_use,
cust_cond_grp_1 as cust_cond_grp_1,
cust_cond_grp_2 as cust_cond_grp_2,
cust_cond_grp_3 as cust_cond_grp_3,
cust_cond_grp_4 as cust_cond_grp_4,
cust_cond_grp_5 as cust_cond_grp_5,
alt_pyr_acct_num_ind as alt_pyr_acct_num_ind,
tax_type as tax_type,
tax_num_type as tax_num_type,
tax_num3 as tax_num3,
tax_num4 as tax_num4,
cust_is_icms_expt as cust_is_icms_expt,
cust_is_ipi_expt as cust_is_ipi_expt,
cust_grp_tax_subst as cust_grp_tax_subst,
cust_cfop_cat as cust_cfop_cat,
tax_law_icms as tax_law_icms,
tax_law_ipi as tax_law_ipi,
biochem_wf_ind as biochem_wf_ind,
nuclr_np_ind as nuclr_np_ind,
natl_scty_ind as natl_scty_ind,
missile_tech_ind as missile_tech_ind,
cent_sls_blk_cust as cent_sls_blk_cust,
unifm_rsrs_lctr as unifm_rsrs_lctr,
current_timestamp()::timestamp_ntz(9) as crt_dttm,
current_timestamp()::timestamp_ntz(9) as updt_dttm
  from source
)

select * from final