
with source as (
    select * from  {{ ref('aspwks_integration__wks_edw_inventory_fact') }}
),
final as(
    SELECT
    LCL_CRNCY,
    base_unit,
    MATL_no,
    STRG_loc,
    stk_type,
    stk_CAT,
    co_cd,
    matl_plnt_VIEW,
    BTCH_NUM,
    plnt,
    WHSE_NUM,
    STRG_bin,
    strg_type,
    SPL_stck_val,
    spl_stck_indica,
    doc_dt,
    VALUT_cls,
    VALUT_area,
    VALUT_type,
    PSTNG_dt,
    CAL_DAY,
    WH_MSTR,
    VERS,
    val_type,
    VEND,
    sold_to_prty,
    MVMT_ind_sec,
    CRNCY,
    FISC_yr_VRNT,
    fisc_yr,
    Cal_yr,
    CAL_mo,
    QTR,
    Cal_YR_QTR,
    CAL_YR_WK,
    PSTNG_PER,
    Half_yr,
    WKDAY,
    fisc_yr_per,
    CAL_YR_MON,
    STCK_REC_VAL,
    iss_STCK_val,
    iss_BLOK_qty,
    cng_stk_qty_iss,
    iss_qty_QUAL,
    iss_qty_TRST,
    RCPT_qty_blok,
    cns_STCK_RCPT,
    RCPT_qty_qual,
    RCPT_qty_trst,
    iss_qty_SCRAP,
    iss_val_SCRAP,
    RCPT_tot_stck,
    iss_tot_stck,
    iss_qty_stck_val,
    rec_qty_val_stck,
    vdr_cnsgnmnt_stck_cnval,
    rec_val_Q_stck,
    rec_val_blok,
    iss_val_blok,
    iss_val_Q_stck,
    rec_val_trst,
    iss_val_trst,
    iss_val_cons_stck,
    rcpt_val_cons_stk,
    bw_PRCH_val,
    bw_amt_bunitm,
    DELV_cost,
    std_matl_cost,
    PRC_unit,
    LINE_CNT,
    current_timestamp()::timestamp_ntz(9) as crt_dttm,
    current_timestamp()::timestamp_ntz(9) as updt_dttm
  FROM source
)

select * from final