with source as 
(
    select * from {{source ('phlsdl_raw','sdl_mds_ph_hce_portal_target')}}
),
final as 
(
    select 
      ID::NUMBER(10,0) AS ID,
MUID::VARCHAR(40) AS MUID,
VERSIONNAME::VARCHAR(100) AS VERSIONNAME,
VERSIONNUMBER::NUMBER(10,0) AS VERSIONNUMBER,
VERSION_ID::NUMBER(10,0) AS VERSION_ID,
VERSIONFLAG::VARCHAR(100) AS VERSIONFLAG,
NAME::VARCHAR(500) AS NAME,
CODE::VARCHAR(500) AS CODE,
CHANGETRACKINGMASK::NUMBER(10,0) AS CHANGETRACKINGMASK,
DISTRICT_CODE::VARCHAR(500) AS DISTRICT_CODE,
TERRITORY_CODE_CODE::VARCHAR(500) AS TERRITORY_CODE_CODE,
AREA_CODE::VARCHAR(500) AS AREA_CODE,
SALES_REP_CODE::VARCHAR(500) AS SALES_REP_CODE,
SALES_MANAGER_CODE::VARCHAR(500) AS SALES_MANAGER_CODE,
GROUP_VARIANT_CODE::VARCHAR(500) AS GROUP_VARIANT_CODE,
YEAR_MONTH::VARCHAR(756) AS YEAR_MONTH,
GMV_TARGET::NUMBER(38,2) AS GMV_TARGET,
ENTERDATETIME::TIMESTAMP_NTZ(9) AS ENTERDATETIME,
ENTERUSERNAME::VARCHAR(200) AS ENTERUSERNAME,
ENTERVERSIONNUMBER::NUMBER(10,0) AS ENTERVERSIONNUMBER,
LASTCHGDATETIME::TIMESTAMP_NTZ(9) AS LASTCHGDATETIME,
LASTCHGUSERNAME::VARCHAR(200) AS LASTCHGUSERNAME,
LASTCHGVERSIONNUMBER::NUMBER(10,0) AS LASTCHGVERSIONNUMBER,
VALIDATIONSTATUS::VARCHAR(500) AS VALIDATIONSTATUS,
current_timestamp as crtd_dttm
     from source 
)

select * from final