--Import CTE

with wks_anz_pos_rpt_re as 
 (
    select * from {{ ref('pcfwks_integration__wks_anz_pos_rpt_re') }}
),
wks_anz_re_target_compliance as 
(
    select * from {{ ref('pcfwks_integration__wks_anz_pos_re_target_compliance')}}
),
edw_anz_pos_rpt_re  as 
(
SELECT jj_year AS FISC_YR,
       main.jj_mnth_id AS FISC_PER,
       "cluster",
       MARKET,
       data_src,
       CHANNEL_NAME,
       DISTRIBUTOR_CODE,
       DISTRIBUTOR_NAME,
       SELL_OUT_CHANNEL,
       STORE_GRADE,
       REGION,
       ZONE_NAME,
       CITY,
       RETAIL_ENVIRONMENT,
       PRODUCT_CODE,
      
       PROD_HIER_L1,
       PROD_HIER_L2,
       PROD_HIER_L3,
       PROD_HIER_L4,
       PROD_HIER_L5,
       PROD_HIER_L6,
       PROD_HIER_L7,
       PROD_HIER_L8,
       PROD_HIER_L9,
       MAPPED_SKU_CD,
       TRIM(NVL (NULLIF(GLOBAL_PRODUCT_FRANCHISE,''),'NA')) AS GLOBAL_PRODUCT_FRANCHISE,
       TRIM(NVL (NULLIF(main.GLOBAL_PRODUCT_BRAND,''),'NA')) AS GLOBAL_PRODUCT_BRAND,
       TRIM(NVL (NULLIF(GLOBAL_PRODUCT_SUB_BRAND,''),'NA')) AS GLOBAL_PRODUCT_SUB_BRAND,
       TRIM(NVL (NULLIF(GLOBAL_PRODUCT_SEGMENT,''),'NA')) AS GLOBAL_PRODUCT_SEGMENT,
       TRIM(NVL (NULLIF(GLOBAL_PRODUCT_SUBSEGMENT,''),'NA')) AS GLOBAL_PRODUCT_SUBSEGMENT,
       TRIM(NVL (NULLIF(GLOBAL_PRODUCT_CATEGORY,''),'NA')) AS GLOBAL_PRODUCT_CATEGORY,
       TRIM(NVL (NULLIF(GLOBAL_PRODUCT_SUBCATEGORY,''),'NA')) AS GLOBAL_PRODUCT_SUBCATEGORY,
       product_code AS EAN,
       MAPPED_SKU_CD AS SKU_CODE,
       SALES_VALUE,
	   SALES_QTY,
       AVG_SALES_QTY,
       SALES_VALUE_LIST_PRICE,
       LM_SALES,
       LM_SALES_QTY,
       LM_AVG_SALES_QTY,
       LM_SALES_LP,
       P3M_SALES,
       P3M_QTY,
       P3M_AVG_QTY,
       P3M_SALES_LP,
       P6M_SALES,
       P6M_QTY,
       P6M_AVG_QTY,
       P6M_SALES_LP,
       P12M_SALES,
       P12M_QTY,
       P12M_AVG_QTY,
       P12M_SALES_LP,
       F3M_SALES,
       F3M_QTY,
       F3M_AVG_QTY,
       LM_SALES_FLAG,
       P3M_SALES_FLAG,
       P6M_SALES_FLAG,
       P12M_SALES_FLAG,
       MDP_FLAG,
       --TARGET_COMPLAINCE,
       CASE 
            WHEN (MDP_FLAG = 'Y' AND UPPER(main.global_product_brand) = UPPER(TRGT_CMP.global_product_brand)) THEN TRGT_CMP.TARGET_COMPLAINCE
            ELSE 100
            END AS TARGET_COMPLAINCE,
       LIST_PRICE,
       null as TOTAL_SALES_LM,
       null as TOTAL_SALES_P3M,
       null as TOTAL_SALES_P6M,
       null as TOTAL_SALES_P12M,
       null as TOTAL_SALES_BY_STORE_LM,
       null as TOTAL_SALES_BY_STORE_P3M,
       null as TOTAL_SALES_BY_STORE_P6M,
       null as TOTAL_SALES_BY_STORE_P12M,
       null as TOTAL_SALES_BY_SKU_LM,
       null as TOTAL_SALES_BY_SKU_P3M,
       null as TOTAL_SALES_BY_SKU_P6M,
       null as TOTAL_SALES_BY_SKU_P12M,
       null as STORE_CONTRIBUTION_LM,
       null as SKU_CONTRIBUTION_LM,
       null as SIZE_OF_PRICE_LM,
       null as STORE_CONTRIBUTION_P3M,
       null as SKU_CONTRIBUTION_P3M,
       null as SIZE_OF_PRICE_P3M,
       null as STORE_CONTRIBUTION_P6M,
       null as SKU_CONTRIBUTION_P6M,
       null as SIZE_OF_PRICE_P6M,
       null as STORE_CONTRIBUTION_P12M,
       null as SKU_CONTRIBUTION_P12M,
       null as SIZE_OF_PRICE_P12M,
       null as TOTAL_SALES_LM_LP,
       null as TOTAL_SALES_P3M_LP,
       null as TOTAL_SALES_P6M_LP,
       null as TOTAL_SALES_P12M_LP,
       null as TOTAL_SALES_BY_STORE_LM_LP,
       null as TOTAL_SALES_BY_STORE_P3M_LP,
       null as TOTAL_SALES_BY_STORE_P6M_LP,
       null as TOTAL_SALES_BY_STORE_P12M_LP,
       null as TOTAL_SALES_BY_SKU_LM_LP,
       null as TOTAL_SALES_BY_SKU_P3M_LP,
       null as TOTAL_SALES_BY_SKU_P6M_LP,
       null as TOTAL_SALES_BY_SKU_P12M_LP,
       null as STORE_CONTRIBUTION_LM_LP,
       null as SKU_CONTRIBUTION_LM_LP,
       null as SIZE_OF_PRICE_LM_LP,
       null as STORE_CONTRIBUTION_P3M_LP,
       null as SKU_CONTRIBUTION_P3M_LP,
       null as SIZE_OF_PRICE_P3M_LP,
       null as STORE_CONTRIBUTION_P6M_LP,
       null as SKU_CONTRIBUTION_P6M_LP,
       null as SIZE_OF_PRICE_P6M_LP,
       null as STORE_CONTRIBUTION_P12M_LP,
       null as SKU_CONTRIBUTION_P12M_LP,
       null as SIZE_OF_PRICE_P12M_LP,
       SYSDATE() AS CRT_DTTM,
	   CM_actual_stores,CM_universe_stores,CM_numeric_distribution,
       LM_actual_stores,LM_universe_stores,LM_numeric_distribution,
       L3M_actual_stores,L3M_universe_stores,L3M_numeric_distribution,
       L6M_actual_stores,L6M_universe_stores,L6M_numeric_distribution,
       L12M_actual_stores,L12M_universe_stores,L12M_numeric_distribution 
FROM wks_anz_pos_rpt_re main
       LEFT JOIN wks_anz_re_target_compliance TRGT_CMP on (main.jj_mnth_id=TRGT_CMP.jj_mnth_id and UPPER(main.global_product_brand)=UPPER(TRGT_CMP.global_product_brand))
),
final as
(
select 
fisc_yr::VARCHAR(16) AS fisc_yr,
fisc_per::VARCHAR(22) AS fisc_per,
"cluster"::VARCHAR(100) AS "cluster",
market::VARCHAR(50) AS market,
data_src::VARCHAR(14) AS data_src,
channel_name::VARCHAR(150) AS channel_name,
distributor_code::VARCHAR(100) AS distributor_code,
distributor_name::VARCHAR(255) AS distributor_name,
sell_out_channel::VARCHAR(150) AS sell_out_channel,
store_grade::VARCHAR(20) AS store_grade,
region::VARCHAR(150) AS region,
zone_name::VARCHAR(150) AS zone_name,
city::VARCHAR(2) AS city,
retail_environment::VARCHAR(225) AS retail_environment,
product_code::VARCHAR(150) AS product_code,
prod_hier_l1::VARCHAR(1) AS prod_hier_l1,
prod_hier_l2::VARCHAR(1) AS prod_hier_l2,
prod_hier_l3::VARCHAR(384) AS prod_hier_l3,
prod_hier_l4::VARCHAR(384) AS prod_hier_l4,
prod_hier_l5::VARCHAR(384) AS prod_hier_l5,
prod_hier_l6::VARCHAR(1) AS prod_hier_l6,
prod_hier_l7::VARCHAR(1) AS prod_hier_l7,
prod_hier_l8::VARCHAR(1) AS prod_hier_l8,
prod_hier_l9::VARCHAR(2307) AS prod_hier_l9,
mapped_sku_cd::VARCHAR(40) AS mapped_sku_cd,
global_product_franchise::VARCHAR(30) AS global_product_franchise,
global_product_brand::VARCHAR(30) AS global_product_brand,
global_product_sub_brand::VARCHAR(100) AS global_product_sub_brand,
global_product_segment::VARCHAR(50) AS global_product_segment,
global_product_subsegment::VARCHAR(100) AS global_product_subsegment,
global_product_category::VARCHAR(50) AS global_product_category,
global_product_subcategory::VARCHAR(50) AS global_product_subcategory,
ean::VARCHAR(150) AS ean,
sku_code::VARCHAR(40) AS sku_code,
sales_value::NUMERIC(38,6) AS sales_value,
sales_qty::NUMERIC(38,6) AS sales_qty,
avg_sales_qty::NUMERIC(38,6) AS avg_sales_qty,
sales_value_list_price::NUMERIC(38,12) AS sales_value_list_price,
lm_sales::NUMERIC(38,6) AS lm_sales,
lm_sales_qty::NUMERIC(38,6) AS lm_sales_qty,
lm_avg_sales_qty::NUMERIC(10,2) AS lm_avg_sales_qty,
lm_sales_lp::NUMERIC(38,12) AS lm_sales_lp,
p3m_sales::NUMERIC(38,6) AS p3m_sales,
p3m_qty::NUMERIC(38,6) AS p3m_qty,
p3m_avg_qty::NUMERIC(10,2) AS p3m_avg_qty,
p3m_sales_lp::NUMERIC(38,12) AS p3m_sales_lp,
p6m_sales::NUMERIC(38,6) AS p6m_sales,
p6m_qty::NUMERIC(38,6) AS p6m_qty,
p6m_avg_qty::NUMERIC(10,2) AS p6m_avg_qty,
p6m_sales_lp::NUMERIC(38,12) AS p6m_sales_lp,
p12m_sales::NUMERIC(38,6) AS p12m_sales,
p12m_qty::NUMERIC(38,6) AS p12m_qty,
p12m_avg_qty::NUMERIC(10,2) AS p12m_avg_qty,
p12m_sales_lp::NUMERIC(38,12) AS p12m_sales_lp,
f3m_sales::VARCHAR(1) AS f3m_sales,
f3m_qty::VARCHAR(1) AS f3m_qty,
f3m_avg_qty::VARCHAR(1) AS f3m_avg_qty,
lm_sales_flag::VARCHAR(1) AS lm_sales_flag,
p3m_sales_flag::VARCHAR(1) AS p3m_sales_flag,
p6m_sales_flag::VARCHAR(1) AS p6m_sales_flag,
p12m_sales_flag::VARCHAR(1) AS p12m_sales_flag,
mdp_flag::VARCHAR(1) AS mdp_flag,
target_complaince::INTEGER AS target_complaince,
list_price::NUMERIC(38,6) AS list_price,
total_sales_lm::VARCHAR(1) AS total_sales_lm,
total_sales_p3m::VARCHAR(1) AS total_sales_p3m,
total_sales_p6m::VARCHAR(1) AS total_sales_p6m,
total_sales_p12m::VARCHAR(1) AS total_sales_p12m,
total_sales_by_store_lm::VARCHAR(1) AS total_sales_by_store_lm,
total_sales_by_store_p3m::VARCHAR(1) AS total_sales_by_store_p3m,
total_sales_by_store_p6m::VARCHAR(1) AS total_sales_by_store_p6m,
total_sales_by_store_p12m::VARCHAR(1) AS total_sales_by_store_p12m,
total_sales_by_sku_lm::VARCHAR(1) AS total_sales_by_sku_lm,
total_sales_by_sku_p3m::VARCHAR(1) AS total_sales_by_sku_p3m,
total_sales_by_sku_p6m::VARCHAR(1) AS total_sales_by_sku_p6m,
total_sales_by_sku_p12m::VARCHAR(1) AS total_sales_by_sku_p12m,
store_contribution_lm::VARCHAR(1) AS store_contribution_lm,
sku_contribution_lm::VARCHAR(1) AS sku_contribution_lm,
size_of_price_lm::VARCHAR(1) AS size_of_price_lm,
store_contribution_p3m::VARCHAR(1) AS store_contribution_p3m,
sku_contribution_p3m::VARCHAR(1) AS sku_contribution_p3m,
size_of_price_p3m::VARCHAR(1) AS size_of_price_p3m,
store_contribution_p6m::VARCHAR(1) AS store_contribution_p6m,
sku_contribution_p6m::VARCHAR(1) AS sku_contribution_p6m,
size_of_price_p6m::VARCHAR(1) AS size_of_price_p6m,
store_contribution_p12m::VARCHAR(1) AS store_contribution_p12m,
sku_contribution_p12m::VARCHAR(1) AS sku_contribution_p12m,
size_of_price_p12m::VARCHAR(1) AS size_of_price_p12m,
total_sales_lm_lp::VARCHAR(1) AS total_sales_lm_lp,
total_sales_p3m_lp::VARCHAR(1) AS total_sales_p3m_lp,
total_sales_p6m_lp::VARCHAR(1) AS total_sales_p6m_lp,
total_sales_p12m_lp::VARCHAR(1) AS total_sales_p12m_lp,
total_sales_by_store_lm_lp::VARCHAR(1) AS total_sales_by_store_lm_lp,
total_sales_by_store_p3m_lp::VARCHAR(1) AS total_sales_by_store_p3m_lp,
total_sales_by_store_p6m_lp::VARCHAR(1) AS total_sales_by_store_p6m_lp,
total_sales_by_store_p12m_lp::VARCHAR(1) AS total_sales_by_store_p12m_lp,
total_sales_by_sku_lm_lp::VARCHAR(1) AS total_sales_by_sku_lm_lp,
total_sales_by_sku_p3m_lp::VARCHAR(1) AS total_sales_by_sku_p3m_lp,
total_sales_by_sku_p6m_lp::VARCHAR(1) AS total_sales_by_sku_p6m_lp,
total_sales_by_sku_p12m_lp::VARCHAR(1) AS total_sales_by_sku_p12m_lp,
store_contribution_lm_lp::VARCHAR(1) AS store_contribution_lm_lp,
sku_contribution_lm_lp::VARCHAR(1) AS sku_contribution_lm_lp,
size_of_price_lm_lp::VARCHAR(1) AS size_of_price_lm_lp,
store_contribution_p3m_lp::VARCHAR(1) AS store_contribution_p3m_lp,
sku_contribution_p3m_lp::VARCHAR(1) AS sku_contribution_p3m_lp,
size_of_price_p3m_lp::VARCHAR(1) AS size_of_price_p3m_lp,
store_contribution_p6m_lp::VARCHAR(1) AS store_contribution_p6m_lp,
sku_contribution_p6m_lp::VARCHAR(1) AS sku_contribution_p6m_lp,
size_of_price_p6m_lp::VARCHAR(1) AS size_of_price_p6m_lp,
store_contribution_p12m_lp::VARCHAR(1) AS store_contribution_p12m_lp,
sku_contribution_p12m_lp::VARCHAR(1) AS sku_contribution_p12m_lp,
size_of_price_p12m_lp::VARCHAR(1) AS size_of_price_p12m_lp,
crt_dttm::TIMESTAMP AS crt_dttm,
cm_actual_stores::NUMERIC(38,6) AS cm_actual_stores,
cm_universe_stores::NUMERIC(38,6) AS cm_universe_stores,
cm_numeric_distribution::NUMERIC(38,6) AS cm_numeric_distribution,
lm_actual_stores::NUMERIC(38,6) AS lm_actual_stores,
lm_universe_stores::NUMERIC(38,14) AS lm_universe_stores,
lm_numeric_distribution::NUMERIC(20,4) AS lm_numeric_distribution,
l3m_actual_stores::NUMERIC(38,6) AS l3m_actual_stores,
l3m_universe_stores::NUMERIC(38,14) AS l3m_universe_stores,
l3m_numeric_distribution::NUMERIC(20,4) AS l3m_numeric_distribution,
l6m_actual_stores::NUMERIC(38,6) AS l6m_actual_stores,
l6m_universe_stores::NUMERIC(38,14) AS l6m_universe_stores,
l6m_numeric_distribution::NUMERIC(20,4) AS l6m_numeric_distribution,
l12m_actual_stores::NUMERIC(38,6) AS l12m_actual_stores,
l12m_universe_stores::NUMERIC(38,14) AS l12m_universe_stores,
l12m_numeric_distribution::NUMERIC(20,4) AS l12m_numeric_distribution
from edw_anz_pos_rpt_re
)
--Final select
select * from final 