{{
    config(
        alias= "edw_customer_sales_dim",
        sql_header= "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';",
        materialized="incremental",
        incremental_strategy= "merge",
        unique_key=  ['cust_num','sls_org','dstr_chnl', 'div'],
        merge_exclude_columns=["CRT_DTTM"],
        tags= [""]
    )
}}

with wks_edw_customer_sales_dim as (
    select * from {{ ref('aspwks_integration__wks_edw_customer_sales_dim') }}
),
itg_cust_sls_attr as (
    select  
        division,
        distr_chan,
        salesorg,
        cust_sales,
        cur_sls_emp,
        lcl_cust_grp_1,
        lcl_cust_grp_2,
        lcl_cust_grp_3,
        lcl_cust_grp_4,
        lcl_cust_grp_5,
        lcl_cust_grp_6,
        lcl_cust_grp_7,
        lcl_cust_grp_8,
        prc_proc,
        par_del,
        max_num_pa,
        prnt_cust_key,
        bnr_key,
        bnr_frmt_key,
        go_to_mdl_key,
        chnl_key,
        sub_chnl_key,
        segmt_key,
        cust_set_1,
        cust_set_2,
        cust_set_3,
        cust_set_4,
        cust_set_5
    from {{ ref('aspitg_integration__itg_cust_sls_attr') }}
),
final as ( 
    select 
        wks_edw_customer_sales_dim.clnt,
        wks_edw_customer_sales_dim.cust_no as cust_num,
        wks_edw_customer_sales_dim.sls_org,
        wks_edw_customer_sales_dim.dstr_chnl,
        wks_edw_customer_sales_dim.div,
        wks_edw_customer_sales_dim.obj_crt_prsn,
        wks_edw_customer_sales_dim.rec_crt_dt,
        wks_edw_customer_sales_dim.auth_grp,
        wks_edw_customer_sales_dim.cust_del_flag,
        wks_edw_customer_sales_dim.cust_stat_grp,
        wks_edw_customer_sales_dim.cust_ord_blk,
        wks_edw_customer_sales_dim.prc_pcdr_asgn,
        wks_edw_customer_sales_dim.cust_grp,
        wks_edw_customer_sales_dim.sls_dstrc,
        wks_edw_customer_sales_dim.prc_grp,
        wks_edw_customer_sales_dim.prc_list_typ,
        wks_edw_customer_sales_dim.ord_prob_itm,
        wks_edw_customer_sales_dim.incoterm1,
        wks_edw_customer_sales_dim.incoterm2,
        wks_edw_customer_sales_dim.cust_delv_blk,
        wks_edw_customer_sales_dim.cmplt_delv_sls_ord,
        wks_edw_customer_sales_dim.max_no_prtl_delv_allw_itm,
        wks_edw_customer_sales_dim.prtl_delv_itm_lvl,
        wks_edw_customer_sales_dim.ord_comb_in,
        wks_edw_customer_sales_dim.btch_splt_allw,
        wks_edw_customer_sales_dim.delv_prir,
        wks_edw_customer_sales_dim.vend_acct_no as vend_acct_num,
        wks_edw_customer_sales_dim.shipping_cond,
        wks_edw_customer_sales_dim.bill_blk_cust,
        wks_edw_customer_sales_dim.man_invc_maint,
        wks_edw_customer_sales_dim.invc_dt,
        wks_edw_customer_sales_dim.invc_list_sched,
        wks_edw_customer_sales_dim.cost_est_in,
        wks_edw_customer_sales_dim.val_lmt_cost_est,
        wks_edw_customer_sales_dim.crncy as crncy_key,
        wks_edw_customer_sales_dim.cust_clas,
        wks_edw_customer_sales_dim.acct_asgnmt_grp,
        wks_edw_customer_sales_dim.delv_plnt,
        wks_edw_customer_sales_dim.sls_grp,
        wks_edw_customer_sales_dim.sls_grp_desc,
        wks_edw_customer_sales_dim.sls_ofc,
        wks_edw_customer_sales_dim.sls_ofc_desc,
        wks_edw_customer_sales_dim.itm_props,
        wks_edw_customer_sales_dim.cust_grp1,
        wks_edw_customer_sales_dim.cust_grp2,
        wks_edw_customer_sales_dim.cust_grp3,
        wks_edw_customer_sales_dim.cust_grp4,
        wks_edw_customer_sales_dim.cust_grp5,
        wks_edw_customer_sales_dim.cust_rebt_in,
        wks_edw_customer_sales_dim.rebt_indx_cust_strt_prd,
        wks_edw_customer_sales_dim.exch_rt_typ,
        wks_edw_customer_sales_dim.prc_dtrmn_id,
        wks_edw_customer_sales_dim.prod_attr_id1,
        wks_edw_customer_sales_dim.prod_attr_id2,
        wks_edw_customer_sales_dim.prod_attr_id3,
        wks_edw_customer_sales_dim.prod_attr_id4,
        wks_edw_customer_sales_dim.prod_attr_id5,
        wks_edw_customer_sales_dim.prod_attr_id6,
        wks_edw_customer_sales_dim.prod_attr_id7,
        wks_edw_customer_sales_dim.prod_attr_id8,
        wks_edw_customer_sales_dim.prod_attr_id9,
        wks_edw_customer_sales_dim.prod_attr_id10,
        wks_edw_customer_sales_dim.pymt_key_term,
        wks_edw_customer_sales_dim.persnl_num,
        current_timestamp()  as crt_dttm ,
        current_timestamp()  as updt_dttm,
        itg_cust_sls_attr.cur_sls_emp, 
        itg_cust_sls_attr.lcl_cust_grp_1, 
        itg_cust_sls_attr.lcl_cust_grp_2, 
        itg_cust_sls_attr.lcl_cust_grp_3, 
        itg_cust_sls_attr.lcl_cust_grp_4, 
        itg_cust_sls_attr.lcl_cust_grp_5, 
        itg_cust_sls_attr.lcl_cust_grp_6, 
        itg_cust_sls_attr.lcl_cust_grp_7, 
        itg_cust_sls_attr.lcl_cust_grp_8, 
        itg_cust_sls_attr.prc_proc, 
        itg_cust_sls_attr.par_del, 
        itg_cust_sls_attr.max_num_pa, 
        itg_cust_sls_attr.prnt_cust_key, 
        itg_cust_sls_attr.bnr_key, 
        itg_cust_sls_attr.bnr_frmt_key, 
        itg_cust_sls_attr.go_to_mdl_key, 
        itg_cust_sls_attr.chnl_key, 
        itg_cust_sls_attr.sub_chnl_key, 
        itg_cust_sls_attr.segmt_key, 
        itg_cust_sls_attr.cust_set_1, 
        itg_cust_sls_attr.cust_set_2, 
        itg_cust_sls_attr.cust_set_3, 
        itg_cust_sls_attr.cust_set_4, 
        itg_cust_sls_attr.cust_set_5
    from wks_edw_customer_sales_dim
    left join itg_cust_sls_attr on 
    wks_edw_customer_sales_dim.div=itg_cust_sls_attr.division
    and itg_cust_sls_attr.distr_chan=wks_edw_customer_sales_dim.dstr_chnl
    and itg_cust_sls_attr.salesorg=wks_edw_customer_sales_dim.sls_org
    and itg_cust_sls_attr.cust_sales=wks_edw_customer_sales_dim.cust_no
)

select * from final