with source as(
    select * from DEV_DNA_LOAD.SNAPIDNSDL_RAW.sdl_dnr_raw_sellout_sales_fact
),
transformed as(
    select 
        'DNR' as dstrbtr_grp_nm,
        'Sales' as file_type,
        TRIM(SalesOffice_ID) as Col1,
        TRIM(DocType) as Col2,
        TRIM(Bill_Doc) as Col3,
        TRIM(Bill_Date) as Col4,
        TRIM(Cust_ID) as Col5,
        TRIM(DistChan) as Col6,
        TRIM(Salesm_ID) as Col7,
        TRIM(Prd_ID) as Col8,
        TRIM(SalesQty) as Col9,
        TRIM(GrossValue) as Col10,
        TRIM(NetValue) as Col11,
        TRIM(CashDisc) as Col12,
        TRIM(FOCQty) as Col13,
        TRIM(FOCValue) as Col14,
        TRIM(TDisc) as Col15,
        NULL as COL16,
        NULL as COL17,
        NULL as COL18,
        NULL as COL19,
        NULL as COL20,
        NULL as COL21,
        NULL as COL22,
        NULL as COL23,
        NULL as COL24,
        NULL as COL25,
        NULL as COL26,
        NULL as COL27,
        NULL as COL28,
        NULL as COL29,
        NULL as COL30,
        NULL as COL31,
        NULL as COL32,
        NULL as COL33,
        NULL as COL34,
        NULL as COL35,
        NULL as COL36,
        NULL as COL37,
        NULL as COL38,
        NULL as COL39,
        NULL as COL40,
        NULL as COL41,
        NULL as COL42,
        NULL as COL43,
        NULL as COL44,
        NULL as COL45,
        NULL as COL46,
        NULL as COL47,
        NULL as COL48,
        NULL as COL49,
        NULL as COL50,
        convert_timezone('UTC', current_timestamp())::timestamp_ntz(9) as CRTD_DTTM,
        NULL::timestamp_ntz(9) as UPDT_DTTM,
    from source
)
select * from transformed