with SDL_SPR_RAW_SELLOUT_SALES_FACT as(
    select * from DEV_DNA_LOAD.SNAPIDNSDL_RAW.SDL_SPR_RAW_SELLOUT_SALES_FACT
),
EDW_DISTRIBUTOR_CHANNEL_DIM as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_DISTRIBUTOR_CHANNEL_DIM
),
EDW_DISTRIBUTOR_METADATA_LKP as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_DISTRIBUTOR_METADATA_LKP
),
EDW_TIME_DIM as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_TIME_DIM
),
EDW_DISTRIBUTOR_DIM as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_DISTRIBUTOR_DIM
),
EDW_DISTRIBUTOR_PRODUCT_DIM as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_DISTRIBUTOR_PRODUCT_DIM
),
wks_spr_sellout_sales_fact AS (
		SELECT TRIM(UPPER(DECODE(SPRSSF.KD_CABANG, '54', '07', '55', '19', '56', '12', '57', '13', '58', '40', '59', '37', '60', '44', '61', '36', SPRSSF.KD_CABANG) || SPRSSF.CUST_ID || SPRSSF.PRODUK_ID || SPRSSF.FAKTUR || TO_CHAR(SPRSSF.TGL_FAKTUR, 'YYYY-MM-DD'))) AS TRANS_KEY,
			TRIM(SPRSSF.FAKTUR) AS BILL_DOC,
			to_date(SPRSSF.TGL_FAKTUR) AS BILL_DT,
			TRIM(ETD.JJ_MNTH_ID) AS JJ_MNTH_ID,
			TRIM(ETD.JJ_WK) AS JJ_WK,
			TRIM(UPPER(DECODE(SPRSSF.KD_CABANG, '54', '07', '55', '19', '56', '12', '57', '13', '58', '40', '59', '37', '60', '44', '61', '36', SPRSSF.KD_CABANG))) AS DSTRBTR_ID,
			TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID)) AS JJ_SAP_DSTRBTR_ID,
			TRIM(UPPER(SPRSSF.PRODUK_ID)) AS DSTRBTR_PROD_ID,
			TRIM(UPPER(EDPD.JJ_SAP_PROD_ID)) AS JJ_SAP_PROD_ID,
			TRIM(SPRSSF.PRODUK_DESC) AS DSTRBTR_PROD_DESC,
			TRIM(UPPER(SPRSSF.CUST_ID)) AS DSTRBTR_CUST_ID,
			TRIM(SPRSSF.SEGMENT_DESC) AS DSTRBTR_CHNL,
			TRIM(UPPER(EDCD.JNJ_CHNL_TYPE_ID)) AS JNJ_CHNL_TYPE_ID,
			TRIM(UPPER(SPRSSF.SALESMAN_ID)) AS DSTRBTR_SLSMN_ID,
			TRIM(SPRSSF.SALESMAN_DESC) AS DSTRBTR_SLSMN_NM,
			(SPRSSF.QTY / EDPD.denominator) AS SLS_QTY, --------/* New logic */ -------------
			--TRIM(SPRSSF.QTY/decode(EDPD.denominator,0,1,EDPD.denominator)) AS SLS_QTY,  --------/* New logic */ -------------
			CASE 
				WHEN franchise = 'OTX'
					THEN SPRSSF.BRUTO * EDML.NET_VAL_CAL_FACTOR
				ELSE SPRSSF.BRUTO * EDML.GROSS_VAL_CAL_FACTOR
				END AS GRS_VAL,
			(SPRSSF.BRUTO * EDML.NET_VAL_CAL_FACTOR) AS JJ_NET_VAL,
			(CAST((DISC_RUTIN + DISC_PRINSIPAL + DISC_EXTRA + DISC_COD) AS DECIMAL(12, 3)) * EDML.TRADE_DISC_CAL_FACTOR) AS TRD_DSCNT,
			(cast( (NETTO * EDML.DIST_NET_VAL_CAL_FACTOR) as DECIMAL(12, 3))) AS DSTRBTR_NET_VAL,
			(
				(
					CASE 
						WHEN DECODE(EDPD.JJ_SAP_PROD_ID, '43120650', SPRSSF.QTY / 25, '43120651', SPRSSF.QTY / 25, '43138651', SPRSSF.QTY / 12, '43138650', SPRSSF.QTY / 12, '43138654', SPRSSF.QTY / 10, '43138652', SPRSSF.QTY / 10, '47214650', SPRSSF.QTY / 12, '46701654', SPRSSF.QTY / 12, /*Included New codes */
								'46701655', SPRSSF.QTY / 12, SPRSSF.QTY) < 0
							THEN DECODE(EDPD.JJ_SAP_PROD_ID, '43120650', SPRSSF.QTY / 25, '43120651', SPRSSF.QTY / 25, '43138651', SPRSSF.QTY / 12, '43138650', SPRSSF.QTY / 12, '43138654', SPRSSF.QTY / 10, '43138652', SPRSSF.QTY / 10, '47214650', SPRSSF.QTY / 12, '46701654', SPRSSF.QTY / 12, /*Included New codes */
									'46701655', SPRSSF.QTY / 12, SPRSSF.QTY) * - 1
						ELSE 0
						END
					)
				) AS RTRN_QTY,
			(
				(
					CASE 
						WHEN DECODE(EDPD.JJ_SAP_PROD_ID, '43120650', SPRSSF.QTY / 25, '43120651', SPRSSF.QTY / 25, '43138651', SPRSSF.QTY / 12, '43138650', SPRSSF.QTY / 12, '43138654', SPRSSF.QTY / 10, '43138652', SPRSSF.QTY / 10, '47214650', SPRSSF.QTY / 12, '46701654', SPRSSF.QTY / 12, /*Included New codes */
								'46701655', SPRSSF.QTY / 12, SPRSSF.QTY) < 0
							THEN (SPRSSF.BRUTO * 1000 / 1.1 * 0.93) * 0.99 * - 1
						ELSE 0
						END
					)
				) AS RTRN_VAL,
			(
				DECODE(EDPD.JJ_SAP_PROD_ID, '43120650', SPRSSF.QTY / 25, '43120651', SPRSSF.QTY / 25, '43138651', SPRSSF.QTY / 12, '43138650', SPRSSF.QTY / 12, '43138654', SPRSSF.QTY / 10, '43138652', SPRSSF.QTY / 10, '47214650', SPRSSF.QTY / 12, '46701654', SPRSSF.QTY / 12, /*Included New codes */
					'46701655', SPRSSF.QTY / 12, SPRSSF.QTY)
				) AS SLS_QTY_RAW --------/* Existing logic and new column added */ -------------
		FROM SDL_SPR_RAW_SELLOUT_SALES_FACT AS SPRSSF,
			(
				SELECT *
				FROM EDW_DISTRIBUTOR_CHANNEL_DIM
				WHERE trim(upper(DSTRBTR_GRP_CD)) = 'SDN'
				) AS EDCD,
			EDW_DISTRIBUTOR_DIM AS EDD,
			(
				SELECT *
				FROM EDW_DISTRIBUTOR_PRODUCT_DIM
				WHERE trim(upper(DSTRBTR_GRP_CD)) = 'SDN_SPR'
				) AS EDPD,
			EDW_TIME_DIM AS ETD,
			(
				SELECT NET_VAL_CAL_FACTOR,
					GROSS_VAL_CAL_FACTOR,
					TRADE_DISC_CAL_FACTOR,
					DIST_NET_VAL_CAL_FACTOR
				FROM EDW_DISTRIBUTOR_METADATA_LKP
				WHERE trim(upper(DSTRBTR_CD)) = 'SPR'
				) AS EDML
		WHERE TRIM(UPPER(EDD.DSTRBTR_ID(+))) = TRIM(UPPER(DECODE(SPRSSF.KD_CABANG, '54', '07', '55', '19', '56', '12', '57', '13', '58', '40', '59', '37', '60', '44', '61', '36', SPRSSF.KD_CABANG)))
			AND TRIM(UPPER(EDPD.DSTRBTR_PROD_ID(+))) = TRIM(UPPER(SPRSSF.PRODUK_ID))
			AND TRIM(UPPER(EDCD.DSTRBTR_CHNL_TYPE_ID(+))) = TRIM(UPPER(SPRSSF.SEGMENT_ID))
			AND to_date(ETD.CAL_DATE) = to_date(SPRSSF.TGL_FAKTUR)
		),
transformed as(
    SELECT 
        w.TRANS_KEY as TRANS_KEY,
        w.BILL_DOC as BILL_DOC,
        w.BILL_DT as BILL_DT,
        w.JJ_MNTH_ID as JJ_MNTH_ID,
        w.JJ_WK as JJ_WK,
        'SPR' as DSTRBTR_grp_CD,
        w.DSTRBTR_ID as DSTRBTR_ID,
        w.JJ_SAP_DSTRBTR_ID as JJ_SAP_DSTRBTR_ID,
        w.DSTRBTR_CUST_ID as DSTRBTR_CUST_ID,
        w.DSTRBTR_PROD_ID as DSTRBTR_PROD_ID,
        w.JJ_SAP_PROD_ID as JJ_SAP_PROD_ID,
        w.JNJ_CHNL_TYPE_ID as DSTRBTN_CHNL,
        w.JNJ_CHNL_TYPE_ID as GRP_OUTLET,
        w.DSTRBTR_SLSMN_ID as DSTRBTR_SLSMN_ID,
        w.SLS_QTY as SLS_QTY,
        w.GRS_VAL as GRS_VAL,
        w.JJ_NET_VAL as JJ_NET_VAL,
        w.TRD_DSCNT as TRD_DSCNT,
        w.DSTRBTR_NET_VAL as DSTRBTR_NET_VAL,
        w.RTRN_QTY as RTRN_QTY,
        w.RTRN_VAL as RTRN_VAL,
        convert_timezone('UTC', current_timestamp())::timestamp_ntz(9),
        NULL::timestamp_ntz(9) as UPDT_DTTM,
        SLS_QTY_RAW as SLS_QTY_RAW --------/* Existing logic and new column added */ -------------
    FROM WKS_SPR_SELLOUT_SALES_FACT w
)
select * from transformed