with sdl_csa_raw_sellout_sales_fact as(
    select * from DEV_DNA_LOAD.SNAPIDNSDL_RAW.SDL_CSA_RAW_SELLOUT_SALES_FACT
),
EDW_DISTRIBUTOR_CHANNEL_DIM as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_DISTRIBUTOR_CHANNEL_DIM
),
EDW_DISTRIBUTOR_METADATA_LKP as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_DISTRIBUTOR_METADATA_LKP
),
EDW_TIME_DIM as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_TIME_DIM
),
EDW_DISTRIBUTOR_DIM as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_DISTRIBUTOR_DIM
),
EDW_DISTRIBUTOR_PRODUCT_DIM as(
    select * from DEV_DNA_CORE.SNAPIDNEDW_INTEGRATION.EDW_DISTRIBUTOR_PRODUCT_DIM
),
wks_csa_sellout_sales_fact AS (
		SELECT TRIM(UPPER(SCRSSF.CABANG || SCRSSF.KODECUST || DECODE(SCRSSF.SHIPCODE, NULL, '', SCRSSF.SHIPCODE) || SCRSSF.KODEBARANG || SCRSSF.NO_INV || TO_CHAR(SCRSSF.TGL_INV, 'YYYY-MM-DD'))) AS TRANS_KEY,
			TRIM(NO_INV) AS BILL_DOC,
			to_date(SCRSSF.TGL_INV) AS BILL_DT,
			TRIM(UPPER(SCRSSF.CABANG)) AS DSTRBTR_ID,
			TRIM(UPPER(EDD.JJ_SAP_DSTRBTR_ID)) AS JJ_SAP_DSTRBTR_ID,
			TRIM(UPPER(SCRSSF.KODEBARANG)) AS DSTRBTR_PROD_ID,
			TRIM(UPPER(EDPD.JJ_SAP_PROD_ID)) AS JJ_SAP_PROD_ID,
			TRIM(SCRSSF.STOCKNAME) AS DSTRBTR_PROD_DESC,
			TRIM(SCRSSF.PERIODE) AS JJ_MNTH_ID,
			TRIM(ETD.JJ_WK) AS JJ_WK,
			TRIM(UPPER(SCRSSF.KODECUST || DECODE(SCRSSF.SHIPCODE, NULL, '', SCRSSF.SHIPCODE))) AS DSTRBTR_CUST_ID,
			TRIM(SCRSSF.CUSTNAME) AS DSTRBTR_CUST_NM,
			TRIM(DECODE(SCRSSF.ALAMATKIRIM, NULL, SCRSSF.ALAMAT, '', SCRSSF.ALAMAT, SCRSSF.ALAMATKIRIM)) AS DSTRBTR_CUST_ADDR,
			TRIM(UPPER(SCRSSF.SR_CODE)) AS DSTRBTR_SLSMN_ID,
			TRIM(SCRSSF.SR_NAME) AS DSTRBTR_SLSMN_NM,
			TRIM(UPPER(SCRSSF.SEGMENT)) AS DSTRBTR_CHNL,
			TRIM(UPPER(EDCD.JNJ_CHNL_TYPE_ID)) AS JNJ_CHNL_TYPE_ID,
			(SCRSSF.QTY / EDPD.denominator) AS SLS_QTY, -----------/* New Sale_qty calculation */
			--TRIM(SCRSSF.QTY / decode(EDPD.denominator,0,1,EDPD.denominator)) AS SLS_QTY,-----------/* New Sale_qty calculation */
			(SCRSSF.HNA) AS GRS_VAL,
			(SCRSSF.HNA * EDML.NET_VAL_CAL_FACTOR) AS JJ_NET_VAL,
			(CAST(NULL AS NUMERIC)) AS TRD_DSCNT,
			(SCRSSF.DPP) AS DSTRBTR_NET_VAL,
			(
				(
					CASE 
						WHEN DECODE(SCRSSF.KODEBARANG, '43120650', SCRSSF.QTY / 25, '43120651', SCRSSF.QTY / 25, '43138651', SCRSSF.QTY / 12, '43138650', SCRSSF.QTY / 12, '43138654', SCRSSF.QTY / 10, '43138652', SCRSSF.QTY / 10, '47214650', SCRSSF.QTY / 24, '46701654', SCRSSF.QTY / 12, /*Included New codes */
								'46701655', SCRSSF.QTY / 12, SCRSSF.QTY) < 0
							THEN DECODE(SCRSSF.KODEBARANG, '43120650', SCRSSF.QTY / 25, '43120651', SCRSSF.QTY / 25, '43138651', SCRSSF.QTY / 12, '43138650', SCRSSF.QTY / 12, '43138654', SCRSSF.QTY / 10, '43138652', SCRSSF.QTY / 10, '47214650', SCRSSF.QTY / 24, '46701654', SCRSSF.QTY / 12, /*Included New codes */
									'46701655', SCRSSF.QTY / 12, SCRSSF.QTY) * - 1
						ELSE 0
						END
					)
				) AS RTRN_QTY,
			(
				(
					CASE 
						WHEN DECODE(SCRSSF.KODEBARANG, '43120650', SCRSSF.QTY / 25, '43120651', SCRSSF.QTY / 25, '43138651', SCRSSF.QTY / 12, '43138650', SCRSSF.QTY / 12, '43138654', SCRSSF.QTY / 10, '43138652', SCRSSF.QTY / 10, '47214650', SCRSSF.QTY / 24, '46701654', SCRSSF.QTY / 12, /*Included New codes */
								'46701655', SCRSSF.QTY / 12, SCRSSF.QTY) < 0
							THEN SCRSSF.HNA * EDML.NET_VAL_CAL_FACTOR * - 1
						ELSE 0
						END
					)
				) AS RTRN_VAL,
			(
				DECODE(SCRSSF.KODEBARANG, '43120650', SCRSSF.QTY / 25, '43120651', SCRSSF.QTY / 25, '43138651', SCRSSF.QTY / 12, '43138650', SCRSSF.QTY / 12, '43138654', SCRSSF.QTY / 10, '43138652', SCRSSF.QTY / 10, '47214650', SCRSSF.QTY / 24, '46701654', SCRSSF.QTY / 12, /*Included New codes */
					'46701655', SCRSSF.QTY / 12, SCRSSF.QTY)
				) AS SLS_QTY_RAW -----------------------/* Existing Logic */------------------------------
		FROM (
			SELECT cabang,
				kodebarang,
				periode,
				tgl_inv,
				no_inv,
				do_no,
				kodecust,
				sr_code,
				sr_name,
				CASE 
					WHEN hna < 0
						THEN qty * - 1
					ELSE qty
					END AS qty,
				netto,
				dpp,
				hna,
				brand,
				stockname,
				custname,
				alamat,
				shipcode,
				cust_formula,
				shipname,
				alamatkirim,
				segment
			FROM SDL_CSA_RAW_SELLOUT_SALES_FACT
			) AS SCRSSF,
			(
				SELECT *
				FROM EDW_DISTRIBUTOR_CHANNEL_DIM
				WHERE trim(upper(DSTRBTR_grp_CD)) = 'CSA'
				) AS EDCD,
			EDW_DISTRIBUTOR_DIM AS EDD,
			(
				SELECT *
				FROM EDW_DISTRIBUTOR_PRODUCT_DIM ----edw_distributor_product_dim
				WHERE trim(upper(DSTRBTR_grp_CD)) = 'CSA'
				) AS EDPD,
			EDW_TIME_DIM AS ETD,
			(
				SELECT NET_VAL_CAL_FACTOR
				FROM EDW_DISTRIBUTOR_METADATA_LKP
				WHERE trim(upper(DSTRBTR_CD)) = 'CSA'
				) AS EDML
		WHERE TRIM(UPPER(EDD.DSTRBTR_ID(+))) = TRIM(UPPER(SCRSSF.CABANG))
			AND TRIM(UPPER(EDPD.DSTRBTR_PROD_ID(+))) = TRIM(UPPER(SCRSSF.KODEBARANG))
			AND TRIM(UPPER(EDCD.DSTRBTR_CHNL_TYPE_ID(+))) = TRIM(UPPER(SCRSSF.SEGMENT))
			AND to_date(ETD.CAL_DATE) = to_date(SCRSSF.TGL_INV)
		),
transformed as(
    SELECT w.TRANS_KEY as TRANS_KEY,
        w.BILL_DOC as BILL_DOC,
        w.BILL_DT::timestamp_ntz(9) as BILL_DT,
        w.JJ_MNTH_ID as JJ_MNTH_ID,
        w.JJ_WK as JJ_WK,
        'CSA' as DSTRBTR_grp_CD,
        w.DSTRBTR_ID as DSTRBTR_ID,
        w.JJ_SAP_DSTRBTR_ID as JJ_SAP_DSTRBTR_ID,
        w.DSTRBTR_CUST_ID as DSTRBTR_CUST_ID,
        w.DSTRBTR_PROD_ID as DSTRBTR_PROD_ID,
        w.JJ_SAP_PROD_ID as JJ_SAP_PROD_ID,
        w.JNJ_CHNL_TYPE_ID as DSTRBTN_CHNL,
        w.JNJ_CHNL_TYPE_ID as GRP_OUTLET,
        w.DSTRBTR_SLSMN_ID as DSTRBTR_SLSMN_ID,
        w.SLS_QTY as SLS_QTY,
        w.GRS_VAL as GRS_VAL,
        w.JJ_NET_VAL as JJ_NET_VAL,
        w.TRD_DSCNT as TRD_DSCNT,
        w.DSTRBTR_NET_VAL as DSTRBTR_NET_VAL,
        w.RTRN_QTY as RTRN_QTY,
        w.RTRN_VAL as RTRN_VAL,
        convert_timezone('UTC', current_timestamp())::timestamp_ntz(9) as CRTD_DTTM,
        NULL::timestamp_ntz(9) as UPDT_DTTM,
        null as filename,
        w.SLS_QTY_RAW as SLS_QTY_RAW --------------------/*New column added */---------------- 
    FROM WKS_CSA_SELLOUT_SALES_FACT w
)
select * from transformed