{{
    config(
        materialized= "incremental",
        incremental_strategy= "append",
        pre_hook = "{% if is_incremental() %}
                delete from {{this}}
where (cycle_plan_source_id) in (select stg.cycle_plan_source_id
                                 from {{ source('hcposesdl_raw', 'sdl_hcp_osea_cycle_plan') }}
 stg
                                 where stg.cycle_plan_source_id = cycle_plan_source_id)
and   country_code in (select distinct country_code from {{ source('hcposesdl_raw', 'sdl_hcp_osea_cycle_plan') }}
);
                    {% endif %}"
    )
}}

with sdl_hcp_osea_cycle_plan AS
(
	select * from {{ source('hcposesdl_raw', 'sdl_hcp_osea_cycle_plan') }}
)
,
transformed 
AS
(
SELECT CYCLE_PLAN_SOURCE_ID,
       OWNER_SOURCE_ID,
       (CASE WHEN UPPER(IS_DELETED) = 'TRUE' THEN 1 WHEN UPPER(IS_DELETED) IS NULL THEN 0 WHEN UPPER(IS_DELETED) = ' ' THEN 0 ELSE 0 END) AS IS_DELETED,
       CYCLE_PLAN_NAME,
       CREATED_DATE,
       CREATED_BY_ID,
       LAST_MODIFIED_DATE,
       LAST_MODIFIED_BY_ID,
       CASE WHEN UPPER(IS_ACTIVE) = 'TRUE' THEN 1 WHEN UPPER(IS_ACTIVE) = 'FALSE' THEN 0 ELSE 0 END IS_ACTIVE,
       ATTAINMENT,
       END_DATE,
       EXTERNAL_ID,
       START_DATE,
       TERRITORY_NAME,
       ACTUAL_CALLS,
       PLANNED_CALLS,
       STATUS_TYPE,
       MGR_S_EMAIL,
       MANAGER,
       MANAGER_NAME,
       COUNTRY_CODE,
       CP_APPROVAL_TIME,
       APPROVER_NAME,
       NUMBER_OF_TARGETS,
       NUMBER_OF_CFA_100_TARGETS,
       CYCLE_PLAN_ATTAINMENT_CPTARGET,
       MID_DATE,
       HCP_PRODUCT_ACHIEVED_100,
       HCP_PRODUCTS_PLANNED,
       CPA_100,
       CASE WHEN UPPER(CLOSE_OUT) = 'TRUE' THEN 1 WHEN UPPER(CLOSE_OUT) = 'FALSE' THEN 0 ELSE 0  END  AS CLOSE_OUT,
       CASE WHEN UPPER(READY_FOR_APPROVAL_FLAG) = 'TRUE' THEN 1  WHEN UPPER(READY_FOR_APPROVAL_FLAG) = 'FALSE' THEN 0 ELSE 0 END  AS READY_FOR_APPROVAL_FLAG,
       ATTAINMENT_DIFFERENCE,
       EXPECTED_ATTAINMENT,  
       EXPECTED_CALLS,	      
       CASE WHEN UPPER(IS_LOCKED) = 'TRUE' THEN 1 WHEN UPPER(IS_LOCKED) = 'FALSE' THEN 0 ELSE 0 END AS IS_LOCKED,	          
       SUBMITTED_BY	,          
       SUBMITTED_DATE_TIME,	  
       TOTAL_TARGET_REACHED,  
       REMAINING,	
       SYSDATE() as INSERTED_DATE,
       NULL as UPDATED_DATE
FROM SDL_HCP_OSEA_CYCLE_PLAN
)
,
final
AS
(
	select 
	CYCLE_PLAN_SOURCE_ID::VARCHAR(18)  as CYCLE_PLAN_SOURCE_ID, -- NOT NULL
	OWNER_SOURCE_ID::VARCHAR(18) as OWNER_SOURCE_ID,
	IS_DELETED::NUMBER(38,0) as IS_DELETED,
	CYCLE_PLAN_NAME::VARCHAR(80) as CYCLE_PLAN_NAME,
	CREATED_DATE::TIMESTAMP_NTZ(9) as CREATED_DATE,
	CREATED_BY_ID::VARCHAR(18) as CREATED_BY_ID,
	LAST_MODIFIED_DATE::TIMESTAMP_NTZ(9) as LAST_MODIFIED_DATE,
	LAST_MODIFIED_BY_ID::VARCHAR(18) as LAST_MODIFIED_BY_ID,
	IS_ACTIVE::NUMBER(38,0) as IS_ACTIVE,
	ATTAINMENT::NUMBER(18,0) as ATTAINMENT,
	END_DATE::DATE as END_DATE,
	EXTERNAL_ID::VARCHAR(100) as EXTERNAL_ID,
	START_DATE::DATE as START_DATE,
	TERRITORY_NAME::VARCHAR(100) as TERRITORY_NAME,
	ACTUAL_CALLS::NUMBER(6,0) as ACTUAL_CALLS,
	PLANNED_CALLS::NUMBER(3,0) as PLANNED_CALLS,
	STATUS_TYPE::VARCHAR(255) as STATUS_TYPE,
	MGR_S_EMAIL::VARCHAR(80) as MGR_S_EMAIL,
	MANAGER::VARCHAR(18) as MANAGER,
	MANAGER_NAME::VARCHAR(50) as MANAGER_NAME,
	COUNTRY_CODE::VARCHAR(2)  as COUNTRY_CODE, --NOT NULL
	CP_APPROVAL_TIME::TIMESTAMP_NTZ(9) as CP_APPROVAL_TIME,
	APPROVER_NAME::VARCHAR(50) as APPROVER_NAME,
	NUMBER_OF_TARGETS::NUMBER(18,0) as NUMBER_OF_TARGETS,
	NUMBER_OF_CFA_100_TARGETS::NUMBER(18,0) as NUMBER_OF_CFA_100_TARGETS,
	CYCLE_PLAN_ATTAINMENT_CPTARGET::NUMBER(18,1) as CYCLE_PLAN_ATTAINMENT_CPTARGET,
	MID_DATE::DATE as MID_DATE,
	HCP_PRODUCT_ACHIEVED_100::NUMBER(18,0) as HCP_PRODUCT_ACHIEVED_100,
	HCP_PRODUCTS_PLANNED::NUMBER(18,0) as HCP_PRODUCTS_PLANNED,
	CPA_100::NUMBER(18,1) as CPA_100,
	CLOSE_OUT::NUMBER(38,0) as CLOSE_OUT,
	READY_FOR_APPROVAL_FLAG::NUMBER(38,0) as READY_FOR_APPROVAL_FLAG,
	ATTAINMENT_DIFFERENCE::NUMBER(18,1) as ATTAINMENT_DIFFERENCE,
	EXPECTED_ATTAINMENT::NUMBER(18,1) as EXPECTED_ATTAINMENT,
	EXPECTED_CALLS::NUMBER(18,1) as EXPECTED_CALLS,
	IS_LOCKED::NUMBER(38,0) as IS_LOCKED,
	SUBMITTED_BY::VARCHAR(100) as SUBMITTED_BY,
	SUBMITTED_DATE_TIME::TIMESTAMP_NTZ(9) as SUBMITTED_DATE_TIME,
	TOTAL_TARGET_REACHED::NUMBER(18,1) as TOTAL_TARGET_REACHED,
	REMAINING::NUMBER(18,1) as REMAINING,
	INSERTED_DATE::TIMESTAMP_NTZ(9) as INSERTED_DATE,
	UPDATED_DATE::TIMESTAMP_NTZ(9) as UPDATED_DATE,
	--primary key (CYCLE_PLAN_SOURCE_ID, COUNTRY_CODE)
    from transformed 

)

select * from final 