with vw_edw_coupang_brand_and_product_ranking as (
select * from DEV_DNA_CORE.NTAEDW_INTEGRATION.VW_EDW_COUPANG_BRAND_AND_PRODUCT_RANKING
),
VW_EDW_COUPANG_USER_REVIEW as (
select * from DEV_DNA_CORE.SNAPNTAEDW_INTEGRATION.VW_EDW_COUPANG_USER_REVIEW
),
VW_EDW_COUPANG_BRAND_TREND as (
select * from DEV_DNA_CORE.SNAPNTAEDW_INTEGRATION.VW_EDW_COUPANG_BRAND_TREND
),
VW_EDW_COUPANG_SEARCH_KEYWORD as (
select * from DEV_DNA_CORE.SNAPNTAEDW_INTEGRATION.VW_EDW_COUPANG_SEARCH_KEYWORD
),
final as (
SELECT 
  derived_table1.ctry_cd, 
  derived_table1.ctry_nm, 
  derived_table1.data_source, 
  derived_table1.reference_date, 
  derived_table1.data_granularity, 
  derived_table1.category_depth1, 
  derived_table1.category_depth2, 
  derived_table1.category_depth3, 
  derived_table1.ranking, 
  derived_table1.prev_day_ranking, 
  derived_table1.prev_week_ranking, 
  derived_table1.prev_mon_ranking, 
  derived_table1.sku_id, 
  derived_table1.sku_name, 
  derived_table1.jnj_brand, 
  derived_table1.rank_change, 
  derived_table1.vendoritemid, 
  derived_table1.ean, 
  derived_table1.all_brand, 
  derived_table1.jnj_product_flag, 
  derived_table1.coupang_product_name, 
  derived_table1.review_score_star, 
  derived_table1.review_contents, 
  derived_table1.coupang_id, 
  derived_table1.new_user_count, 
  derived_table1.curr_user_count, 
  derived_table1.tot_user_count, 
  derived_table1.new_user_sales_amt, 
  derived_table1.curr_user_sales_amt, 
  derived_table1.new_user_avg_product_sales_price, 
  derived_table1.curr_user_avg_product_sales_price, 
  derived_table1.tot_user_avg_product_sales_price, 
  derived_table1.search_keyword, 
  derived_table1.product_name, 
  derived_table1.by_search_keyword, 
  derived_table1.by_product_ranking, 
  derived_table1.product_ranking, 
  derived_table1.click_rate, 
  derived_table1.cart_transition_rate, 
  derived_table1.purchase_conversion_rate 
FROM 
  (
    (
      (
        SELECT 
          bpr.ctry_cd, 
          bpr.ctry_nm, 
          bpr.data_source, 
          bpr.reference_date, 
          bpr.data_granularity, 
          bpr.category_depth1, 
          bpr.category_depth2, 
          bpr.category_depth3, 
          bpr.ranking, 
          bpr.prev_day_ranking, 
          bpr.prev_week_ranking, 
          bpr.prev_mon_ranking, 
          bpr.sku_id, 
          bpr.sku_name, 
          bpr.jnj_brand, 
          bpr.rank_change, 
          bpr.vendoritemid, 
          bpr.ean, 
          bpr.all_brand, 
          bpr.jnj_product_flag, 
          NULL :: character varying AS coupang_product_name, 
          NULL :: character varying AS review_score_star, 
          NULL :: character varying AS review_contents, 
          NULL :: character varying AS coupang_id, 
          NULL :: character varying AS new_user_count, 
          NULL :: character varying AS curr_user_count, 
          NULL :: character varying AS tot_user_count, 
          (NULL :: numeric):: numeric(18, 0) AS new_user_sales_amt, 
          (NULL :: numeric):: numeric(18, 0) AS curr_user_sales_amt, 
          (NULL :: numeric):: numeric(18, 0) AS new_user_avg_product_sales_price, 
          (NULL :: numeric):: numeric(18, 0) AS curr_user_avg_product_sales_price, 
          (NULL :: numeric):: numeric(18, 0) AS tot_user_avg_product_sales_price, 
          NULL :: character varying AS search_keyword, 
          NULL :: character varying AS product_name, 
          NULL :: character varying AS by_search_keyword, 
          NULL :: character varying AS by_product_ranking, 
          NULL :: character varying AS product_ranking, 
          (NULL :: numeric):: numeric(18, 0) AS click_rate, 
          (NULL :: numeric):: numeric(18, 0) AS cart_transition_rate, 
          (NULL :: numeric):: numeric(18, 0) AS purchase_conversion_rate 
        FROM 
          vw_edw_coupang_brand_and_product_ranking bpr 
        UNION ALL 
        SELECT 
          ur.ctry_cd, 
          ur.ctry_nm, 
          ur.data_source, 
          ur.reference_date, 
          ur.data_granularity, 
          NULL :: character varying AS category_depth1, 
          NULL :: character varying AS category_depth2, 
          NULL :: character varying AS category_depth3, 
          NULL :: character varying AS ranking, 
          NULL :: character varying AS prev_day_ranking, 
          NULL :: character varying AS prev_week_ranking, 
          NULL :: character varying AS prev_mon_ranking, 
          ur.sku_id, 
          NULL :: character varying AS sku_name, 
          NULL :: character varying AS jnj_brand, 
          NULL :: character varying AS rank_change, 
          ur.vendoritemid, 
          ur.ean, 
          ur.all_brand, 
          NULL :: character varying AS jnj_product_flag, 
          ur.coupang_product_name, 
          ur.review_score_star, 
          ur.review_contents, 
          NULL :: character varying AS coupang_id, 
          NULL :: character varying AS new_user_count, 
          NULL :: character varying AS curr_user_count, 
          NULL :: character varying AS tot_user_count, 
          (NULL :: numeric):: numeric(18, 0) AS new_user_sales_amt, 
          (NULL :: numeric):: numeric(18, 0) AS curr_user_sales_amt, 
          (NULL :: numeric):: numeric(18, 0) AS new_user_avg_product_sales_price, 
          (NULL :: numeric):: numeric(18, 0) AS curr_user_avg_product_sales_price, 
          (NULL :: numeric):: numeric(18, 0) AS tot_user_avg_product_sales_price, 
          NULL :: character varying AS search_keyword, 
          NULL :: character varying AS product_name, 
          NULL :: character varying AS by_search_keyword, 
          NULL :: character varying AS by_product_ranking, 
          NULL :: character varying AS product_ranking, 
          (NULL :: numeric):: numeric(18, 0) AS click_rate, 
          (NULL :: numeric):: numeric(18, 0) AS cart_transition_rate, 
          (NULL :: numeric):: numeric(18, 0) AS purchase_conversion_rate 
        FROM 
          vw_edw_coupang_user_review ur
      ) 
      UNION ALL 
      SELECT 
        bt.ctry_cd, 
        bt.ctry_nm, 
        bt.data_source, 
        bt.reference_date, 
        bt.data_granularity, 
        bt.category_depth1, 
        NULL :: character varying AS category_depth2, 
        NULL :: character varying AS category_depth3, 
        NULL :: character varying AS ranking, 
        NULL :: character varying AS prev_day_ranking, 
        NULL :: character varying AS prev_week_ranking, 
        NULL :: character varying AS prev_mon_ranking, 
        NULL :: character varying AS sku_id, 
        NULL :: character varying AS sku_name, 
        NULL :: character varying AS jnj_brand, 
        NULL :: character varying AS rank_change, 
        (NULL :: numeric):: numeric(18, 0) AS vendoritemid, 
        NULL :: character varying AS ean, 
        bt.all_brand, 
        NULL :: character varying AS jnj_product_flag, 
        NULL :: character varying AS coupang_product_name, 
        NULL :: character varying AS review_score_star, 
        NULL :: character varying AS review_contents, 
        bt.coupang_id, 
        bt.new_user_count, 
        bt.curr_user_count, 
        bt.tot_user_count, 
        bt.new_user_sales_amt, 
        bt.curr_user_sales_amt, 
        bt.new_user_avg_product_sales_price, 
        bt.curr_user_avg_product_sales_price, 
        bt.tot_user_avg_product_sales_price, 
        NULL :: character varying AS search_keyword, 
        NULL :: character varying AS product_name, 
        NULL :: character varying AS by_search_keyword, 
        NULL :: character varying AS by_product_ranking, 
        NULL :: character varying AS product_ranking, 
        (NULL :: numeric):: numeric(18, 0) AS click_rate, 
        (NULL :: numeric):: numeric(18, 0) AS cart_transition_rate, 
        (NULL :: numeric):: numeric(18, 0) AS purchase_conversion_rate 
      FROM 
        vw_edw_coupang_brand_trend bt
    ) 
    UNION ALL 
    SELECT 
      sk.ctry_cd, 
      sk.ctry_nm, 
      sk.data_source, 
      sk.reference_date, 
      sk.data_granularity, 
      sk.category_depth1, 
      sk.category_depth2, 
      sk.category_depth3, 
      sk.ranking, 
      NULL :: character varying AS prev_day_ranking, 
      NULL :: character varying AS prev_week_ranking, 
      NULL :: character varying AS prev_mon_ranking, 
      NULL :: character varying AS sku_id, 
      NULL :: character varying AS sku_name, 
      NULL :: character varying AS jnj_brand, 
      NULL :: character varying AS rank_change, 
      (NULL :: numeric):: numeric(18, 0) AS vendoritemid, 
      NULL :: character varying AS ean, 
      NULL :: character varying AS all_brand, 
      sk.jnj_product_flag, 
      NULL :: character varying AS coupang_product_name, 
      NULL :: character varying AS review_score_star, 
      NULL :: character varying AS review_contents, 
      NULL :: character varying AS coupang_id, 
      NULL :: character varying AS new_user_count, 
      NULL :: character varying AS curr_user_count, 
      NULL :: character varying AS tot_user_count, 
      (NULL :: numeric):: numeric(18, 0) AS new_user_sales_amt, 
      (NULL :: numeric):: numeric(18, 0) AS curr_user_sales_amt, 
      (NULL :: numeric):: numeric(18, 0) AS new_user_avg_product_sales_price, 
      (NULL :: numeric):: numeric(18, 0) AS curr_user_avg_product_sales_price, 
      (NULL :: numeric):: numeric(18, 0) AS tot_user_avg_product_sales_price, 
      sk.search_keyword, 
      sk.product_name, 
      sk.by_search_keyword, 
      sk.by_product_ranking, 
      sk.product_ranking, 
      sk.click_rate, 
      sk.cart_transition_rate, 
      sk.purchase_conversion_rate 
    FROM 
      vw_edw_coupang_search_keyword sk
  ) derived_table1
)
select * from final
