with source as
(
    select * from {{ ref('thaedw_integration__edw_vw_th_siso_analysis') }}
),

final as
(
    select 
        data_type::varchar(7) as data_type,
        year_jnj::number(18,0) as year_jnj,
        year_quarter_jnj::varchar(24) as year_quarter_jnj,
        year_month_jnj::varchar(23) as year_month_jnj,
        month_number_jnj::number(18,0) as month_number_jnj,
        item_code::varchar(50) as item_code,
        item_description::varchar(100) as item_description,
        franchise::varchar(30) as franchise,
        brand::varchar(30) as brand,
        variant::varchar(100) as variant,
        segment::varchar(50) as segment,
        put_up::varchar(100) as put_up,
        prod_sub_brand::varchar(100) as prod_sub_brand,
        prod_subsegment::varchar(100) as prod_subsegment,
        prod_category::varchar(50) as prod_category,
        prod_subcategory::varchar(50) as prod_subcategory,
        sap_sls_org::varchar(4) as sap_sls_org,
        sap_prnt_cust_key::varchar(12) as sap_prnt_cust_key,
        sap_prnt_cust_desc::varchar(50) as sap_prnt_cust_desc,
        sap_cust_chnl_key::varchar(12) as sap_cust_chnl_key,
        sap_cust_chnl_desc::varchar(50) as sap_cust_chnl_desc,
        sap_cust_sub_chnl_key::varchar(12) as sap_cust_sub_chnl_key,
        sap_sub_chnl_desc::varchar(50) as sap_sub_chnl_desc,
        sap_go_to_mdl_key::varchar(12) as sap_go_to_mdl_key,
        go_to_model_description::varchar(50) as go_to_model_description,
        sap_bnr_key::varchar(12) as sap_bnr_key,
        banner_description::varchar(50) as banner_description,
        sap_bnr_frmt_key::varchar(12) as sap_bnr_frmt_key,
        sap_bnr_frmt_desc::varchar(50) as sap_bnr_frmt_desc,
        retail_env::varchar(50) as retail_env,
        customer_id::varchar(255) as customer_id,
        sap_customer_name::varchar(100) as sap_customer_name,
        sap_sales_office_code::varchar(4) as sap_sales_office_code,
        sap_sales_office_description::varchar(40) as sap_sales_office_description,
        sap_sales_group_code::varchar(3) as sap_sales_group_code,
        sap_sales_group_description::varchar(40) as sap_sales_group_description,
        so_gross_trade_sales::float as so_gross_trade_sales,
        so_cn_damaged_goods::float as so_cn_damaged_goods,
        so_credit_note_amount::float as so_credit_note_amount,
        so_line_discount::number(38,6) as so_line_discount,
        so_bottom_line_discount::number(38,6) as so_bottom_line_discount,
        so_sales_quantity::number(38,6) as so_sales_quantity,
        so_return_quantity::number(38,6) as so_return_quantity,
        so_quantity_dz::float as so_quantity_dz,
        so_net_invoice::float as so_net_invoice,
        so_target_calls::number(38,0) as so_target_calls,
        so_target_sales::number(38,0) as so_target_sales,
        si_base_value::number(38,5) as si_base_value,
        si_sales_quantity::number(38,5) as si_sales_quantity,
        si_return_quantity::number(38,5) as si_return_quantity,
        si_sales_less_return_quantity::number(38,5) as si_sales_less_return_quantity,
        si_gross_trade_sales_value::number(38,5) as si_gross_trade_sales_value,
        si_return_value::number(38,5) as si_return_value,
        si_gross_trade_sales_less_return_value::number(38,5) as si_gross_trade_sales_less_return_value,
        si_tp_value::number(38,5) as si_tp_value,
        si_net_trade_sales_value::number(38,5) as si_net_trade_sales_value,
        si_net_trade_sales_quantity::number(38,5) as si_net_trade_sales_quantity
    from source
)

select * from final