with itg_rkeyacccustomer as 
(
    select * from {{source('inditg_integration', 'itg_rkeyacccustomer')}}
),
itg_mds_in_sv_winculum_master as 
(
    select * from {{source('inditg_integration', 'itg_mds_in_sv_winculum_master')}}
),

ct1 as 
(
    SELECT customercode AS customercode,
        customername,
        customeraddress1,
        customeraddress2,
        customeraddress3,
        NULL AS customerid,
        sapid,
        regioncode regioncode,
        zonecode AS zonecode,
        territorycode AS territorycode,
        statecode AS statecode,
        towncode AS towncode,
        NULL AS typecode,
        CAST(NULL AS CHAR) AS psnonps,
        emailid,
        mobilell,
        CAST(NULL AS NUMERIC) AS suppliedby,
        CAST(NULL AS CHAR) AS druglicense,
        CAST(NULL AS NUMERIC) AS currentytd,
        CAST(NULL AS NUMERIC) AS dsbychannelcode,
        CAST(NULL AS NUMERIC) AS dsbystrategiccode,
        CAST(NULL AS NUMERIC) AS classificationcode,
        isactive,
        CAST(NULL AS TIMESTAMP) AS deactivedt,
        createddt AS activedt,
        CAST(NULL AS CHAR) AS annualincentiveplan,
        CAST(NULL AS CHAR) AS istarangumang,
        wholesalercode,
        CAST(NULL AS CHAR) AS isime,
        CAST(NULL AS NUMERIC) AS createdby,
        nkacstores,
        NULLIF(parentcustomercode, '') AS parentcustomercode,
        isdirectacct,
        CAST(abicode AS VARCHAR) AS abicode,
        CAST(NULL AS INTEGER) AS distributorcode,
        distributorsapid,
        CAST(NULL AS NUMERIC) AS sapzonecode,
        CAST(NULL AS NUMERIC) AS sapterritorycode,
        isconfirm,
        CAST(NULL AS NUMERIC) AS nkacregion,
        CAST(NULL AS NUMERIC) AS nkaczone,
        CAST(NULL AS NUMERIC) AS nkacterritory,
        NULL AS channel,
        NULL AS gln,
        CAST(NULL AS NUMERIC) AS transitdays,
        CAST(NULL AS NUMERIC) AS transithours,
        NULL AS vmrapply,
        CAST(NULL AS TIMESTAMP) AS custcreatedon,
        CAST(NULL AS TIMESTAMP) AS custlastupdatedon,
        CAST(NULL AS NUMERIC) AS custlastupdatedby,
        CAST(NULL AS CHAR) AS isdisteligibleforclaims,
        isparent,
        crt_dttm,
        updt_dttm
    FROM itg_rkeyacccustomer
),

ct2 as 
(
    SELECT customercode AS customercode,
        customername,
        NULL AS customeraddress1,
        NULL AS customeraddress2,
        NULL AS customeraddress3,
        NULL AS customerid,
        NULL AS sapid,
        regioncode AS regioncode,
        zonecode AS zonecode,
        territorycode AS territorycode,
        statecode AS statecode,
        towncode AS towncode,
        NULL AS typecode,
        psnonps AS psnonps,
        NULL AS emailid,
        NULL AS mobilell,
        CAST(NULL AS NUMERIC) AS suppliedby,
        CAST(NULL AS CHAR) AS druglicense,
        CAST(NULL AS NUMERIC) AS currentytd,
        CAST(NULL AS NUMERIC) AS dsbychannelcode,
        CAST(NULL AS NUMERIC) AS dsbystrategiccode,
        CAST(NULL AS NUMERIC) AS classificationcode,
        CAST(isactive AS CHAR) AS isactive,
        CAST(NULL AS TIMESTAMP) AS deactivedt,
        crtd_dttm AS activedt,
        CAST(NULL AS CHAR) AS annualincentiveplan,
        CAST(NULL AS CHAR) AS istarangumang,
        wholesalercode,
        CAST(NULL AS CHAR) AS isime,
        CAST(NULL AS NUMERIC) AS createdby,
        CAST(NULL AS CHAR) AS nkacstores,
        NULLIF(parentcustomercode, '') AS parentcustomercode,
        isdirectacct AS isdirectacct,
        CAST(abicode AS VARCHAR) AS abicode,
        CAST(NULL AS INTEGER) AS distributorcode,
        distributorsapid,
        CAST(NULL AS NUMERIC) AS sapzonecode,
        CAST(NULL AS NUMERIC) AS sapterritorycode,
        NULL AS isconfirm,
        CAST(NULL AS NUMERIC) AS nkacregion,
        CAST(NULL AS NUMERIC) AS nkaczone,
        CAST(NULL AS NUMERIC) AS nkacterritory,
        NULL AS channel,
        NULL AS gln,
        CAST(NULL AS NUMERIC) AS transitdays,
        CAST(NULL AS NUMERIC) AS transithours,
        NULL AS vmrapply,
        CAST(NULL AS TIMESTAMP) AS custcreatedon,
        CAST(NULL AS TIMESTAMP) AS custlastupdatedon,
        CAST(NULL AS NUMERIC) AS custlastupdatedby,
        CAST(NULL AS CHAR) AS isdisteligibleforclaims,
        'N' AS isparent,
        crtd_dttm AS crt_dttm,
        updt_dttm
    FROM itg_mds_in_sv_winculum_master
    WHERE active = 'Y'
),

transformed as (
    select * from ct1
    union all
    select * from ct2
),

final as (
    select
        customercode::varchar(50) as customercode,
        customername::varchar(50) as customername,
        customeraddress1::varchar(250) as customeraddress1,
        customeraddress2::varchar(250) as customeraddress2,
        customeraddress3::varchar(250) as customeraddress3,
        customerid::varchar(20) as customerid,
        sapid::varchar(20) as sapid,
        regioncode::varchar(50) as regioncode,
        zonecode::varchar(50) as zonecode,
        territorycode::varchar(50) as territorycode,
        statecode::varchar(50) as statecode,
        towncode::varchar(50) as towncode,
        typecode::varchar(50) as typecode,
        psnonps::varchar(10) as psnonps,
        emailid::varchar(50) as emailid,
        mobilell::varchar(50) as mobilell,
        suppliedby::number(18,0) as suppliedby,
        druglicense::varchar(10) as druglicense,
        currentytd::number(18,0) as currentytd,
        dsbychannelcode::number(18,0) as dsbychannelcode,
        dsbystrategiccode::number(18,0) as dsbystrategiccode,
        classificationcode::number(18,0) as classificationcode,
        isactive::varchar(10) as isactive,
        deactivedt::timestamp_ntz(9) as deactivedt,
        activedt::timestamp_ntz(9) as activedt,
        annualincentiveplan::varchar(10) as annualincentiveplan,
        istarangumang::varchar(10) as istarangumang,
        wholesalercode::varchar(50) as wholesalercode,
        isime::varchar(10) as isime,
        createdby::number(18,0) as createdby,
        nkacstores::varchar(10) as nkacstores,
        parentcustomercode::varchar(50) as parentcustomercode,
        isdirectacct::varchar(10) as isdirectacct,
        abicode::varchar(50) as abicode,
        distributorcode::number(18,0) as distributorcode,
        distributorsapid::varchar(50) as distributorsapid,
        sapzonecode::number(18,0) as sapzonecode,
        sapterritorycode::number(18,0) as sapterritorycode,
        isconfirm::varchar(10) as isconfirm,
        nkacregion::number(18,0) as nkacregion,
        nkaczone::number(18,0) as nkaczone,
        nkacterritory::number(18,0) as nkacterritory,
        channel::varchar(10) as channel,
        gln::varchar(50) as gln,
        transitdays::number(9,0) as transitdays,
        transithours::number(9,0) as transithours,
        vmrapply::varchar(10) as vmrapply,
        custcreatedon::timestamp_ntz(9) as custcreatedon,
        custlastupdatedon::timestamp_ntz(9) as custlastupdatedon,
        custlastupdatedby::number(18,0) as custlastupdatedby,
        isdisteligibleforclaims::varchar(10) as isdisteligibleforclaims,
        isparent::varchar(10) as isparent,
        crt_dttm::timestamp_ntz(9) as crt_dttm,
        updt_dttm::timestamp_ntz(9) as updt_dttm
    from transformed
)
select * from final
