with itg_hcp360_veeva_territory as
(
    select * from {{ source('hcpitg_integration', 'itg_hcp360_veeva_territory') }}
),
itg_hcp360_veeva_userterritory as
(
    select * from {{ source('hcpitg_integration', 'itg_hcp360_veeva_userterritory') }}
),
itg_hcp360_veeva_user as
(
    select * from {{ source('hcpitg_integration', 'itg_hcp360_veeva_user') }}
),
edw_hcp360_veeva_wrk_dim_organization as
(
    select * from {{ ref('hcpedw_integration__edw_hcp360_veeva_wrk_dim_organization') }}
),
IQ AS
(
    SELECT DISTINCT
    IU.EMPLOYEE_KEY ,
    IU.COUNTRY_CODE,
    IU.EMPLOYEE_SOURCE_ID,
    IU.LAST_MODIFIED_DATE,
    IU.LAST_MODIFIED_BY_ID,
    IU.EMPLOYEE_NAME,
    IU.WWID,
    IU.MOBILE_PHONE,
    IU.EMAIL,
    IU.USER_NAME,
    IU.NICKNAME,
    IU.LOCAL_EMPLOYEE_NUMBER,
    IU.COMPANY_NAME,
    IU.DIVISION,
    IU.DEPARTMENT,
    IU.COUNTRY,
    IU.ADDRESS,
    IU.ALIAS,
    IU.TIMEZONESIDKEY,
    CAST (IU.RECEIVES_INFO_EMAILS AS INTEGER) AS RECEIVES_INFO_EMAILS,
    IU.FEDERATION_IDENTIFIER,
    IU.LAST_IPAD_SYNC,
    IU.USER_LICENSE,
    IU.title,
    IU.phone,
    IU.last_login_date,
    IU.region,
    IU.manager_name,
    IU.manager_wwid,
    CAST(IU.is_active AS INTEGER ) AS active_flag,
    ORG_HIER.MY_ORGANIZATION_CODE,
    ORG_HIER.MY_ORGANIZATION_NAME,
    ORG_HIER.ORGANIZATION_L1_CODE,
    ORG_HIER.ORGANIZATION_L1_NAME,
    ORG_HIER.ORGANIZATION_L2_CODE,
    ORG_HIER.ORGANIZATION_L2_NAME,
    ORG_HIER.ORGANIZATION_L3_CODE,
    ORG_HIER.ORGANIZATION_L3_NAME,
    ORG_HIER.ORGANIZATION_L4_CODE,
    ORG_HIER.ORGANIZATION_L4_NAME,
    ORG_HIER.ORGANIZATION_L5_CODE,
    ORG_HIER.ORGANIZATION_L5_NAME,
    ORG_HIER.ORGANIZATION_L6_CODE,
    ORG_HIER.ORGANIZATION_L6_NAME,
    ORG_HIER.ORGANIZATION_L7_CODE,
    ORG_HIER.ORGANIZATION_L7_NAME,
    ORG_HIER.ORGANIZATION_L8_CODE,
    ORG_HIER.ORGANIZATION_L8_NAME,
    ORG_HIER.ORGANIZATION_L9_CODE,
    ORG_HIER.ORGANIZATION_L9_NAME,
    ORG_HIER.ORGANIZATION_L1_CODE  as COMMON_ORGANIZATION_L1_CODE,
    ORG_HIER.ORGANIZATION_L1_NAME  as COMMON_ORGANIZATION_L1_NAME,
    ORG_HIER.ORGANIZATION_L2_CODE  as COMMON_ORGANIZATION_L2_CODE,
    ORG_HIER.ORGANIZATION_L2_NAME  as COMMON_ORGANIZATION_L2_NAME,
    ORG_HIER.ORGANIZATION_L3_CODE  as COMMON_ORGANIZATION_L3_CODE,
    ORG_HIER.ORGANIZATION_L3_NAME  as COMMON_ORGANIZATION_L3_NAME,
    IU.MSL_PRIMARY_RESPONSIBLE_TA
    from itg_hcp360_veeva_territory IT , itg_hcp360_veeva_userterritory IUT , itg_hcp360_veeva_user IU ,
    edw_hcp360_veeva_wrk_dim_organization ORG_HIER
    where IU.EMPLOYEE_SOURCE_ID = IUT.USER_TERRITORY_USER_SOURCE_ID(+)
    AND IUT.TERRITORY_SOURCE_ID =IT.TERRITORY_SOURCE_ID(+)
    AND IT.TERRITORY_SOURCE_ID = ORG_HIER.TERRITORY_SOURCE_ID(+)
    AND IT.country_code = ORG_HIER.country_code(+)
),
final as 
(
    SELECT IQ.* ,
    CASE WHEN (IQ.ORGANIZATION_L1_CODE <> '' AND IQ.ORGANIZATION_L2_CODE <> '' AND IQ.ORGANIZATION_L3_CODE <> '' AND IQ.ORGANIZATION_L4_CODE <> '' AND IQ.ORGANIZATION_L5_CODE <> '' AND IQ.ORGANIZATION_L6_CODE <> '' AND IQ.ORGANIZATION_L7_CODE <> '' AND IQ.ORGANIZATION_L8_CODE <> '' AND IQ.ORGANIZATION_L9_CODE <> '') THEN 1 
        WHEN (IQ.ORGANIZATION_L1_CODE <> '' AND IQ.ORGANIZATION_L2_CODE <> '' AND IQ.ORGANIZATION_L3_CODE <> '' AND IQ.ORGANIZATION_L4_CODE <> '' AND IQ.ORGANIZATION_L5_CODE <> '' AND IQ.ORGANIZATION_L6_CODE <> '' AND IQ.ORGANIZATION_L7_CODE <> '' AND IQ.ORGANIZATION_L8_CODE <> '') THEN 2 
        WHEN (IQ.ORGANIZATION_L1_CODE <> '' AND IQ.ORGANIZATION_L2_CODE <> '' AND IQ.ORGANIZATION_L3_CODE <> '' AND IQ.ORGANIZATION_L4_CODE <> '' AND IQ.ORGANIZATION_L5_CODE <> '' AND IQ.ORGANIZATION_L6_CODE <> '' AND IQ.ORGANIZATION_L7_CODE <> '') THEN 3 
        WHEN (IQ.ORGANIZATION_L1_CODE <> '' AND IQ.ORGANIZATION_L2_CODE <> '' AND IQ.ORGANIZATION_L3_CODE <> '' AND IQ.ORGANIZATION_L4_CODE <> '' AND IQ.ORGANIZATION_L5_CODE <> '' AND IQ.ORGANIZATION_L6_CODE <> '') THEN 4
        WHEN (IQ.ORGANIZATION_L1_CODE <> '' AND IQ.ORGANIZATION_L2_CODE <> '' AND IQ.ORGANIZATION_L3_CODE <> '' AND IQ.ORGANIZATION_L4_CODE <> '' AND IQ.ORGANIZATION_L5_CODE <> '') THEN 5 
        WHEN (IQ.ORGANIZATION_L1_CODE <> '' AND IQ.ORGANIZATION_L2_CODE <> '' AND IQ.ORGANIZATION_L3_CODE <> '' AND IQ.ORGANIZATION_L4_CODE <> '') THEN 6 
        WHEN (IQ.ORGANIZATION_L1_CODE <> '' AND IQ.ORGANIZATION_L2_CODE <> '' AND IQ.ORGANIZATION_L3_CODE <> '') THEN 7 
        WHEN (IQ.ORGANIZATION_L1_CODE <> '' AND IQ.ORGANIZATION_L2_CODE <> '') THEN 8
        WHEN (IQ.ORGANIZATION_L1_CODE <> '') THEN 9 
    ELSE 0 END RNK
    FROM IQ
)
select * from final