--REQ000000180060: SSR O&A display points content change
with edw_perenso_call as
(
    select * from {{ ref('pcfedw_integration__edw_perenso_call') }}
),
edw_perenso_compliance as
(
    select * from {{ ref('pcfedw_integration__edw_perenso_compliance') }}
),
edw_perenso_over_and_above as
(
    select * from {{ ref('pcfedw_integration__edw_perenso_over_and_above') }}
),
edw_perenso_survey as
(
    select * from {{ ref('pcfedw_integration__edw_perenso_survey') }}
),
itg_perenso_call_objectives as
(
    select * from {{ ref('pcfitg_integration__itg_perenso_call_objectives') }}
),
itg_perenso_users as
(
    select * from {{ ref('pcfitg_integration__itg_perenso_users') }}
),
itg_perenso_diary_item_time as
(
    select * from {{ ref('pcfitg_integration__itg_perenso_diary_item_time') }}
),
itg_perenso_diary_item as
(
    select * from {{ ref('pcfitg_integration__itg_perenso_diary_item') }}
),
itg_perenso_diary_item_type as
(
    select * from {{ ref('pcfitg_integration__itg_perenso_diary_item_type') }}
),
union_1 as
(
    select 
        perenso_source,
        diary_item_type_desc,
        diary_item_category,
        to_date(diary_start_time) as diary_start_date,
        --diary_start_time,
        substring(diary_start_time, 12,8) as diary_start_time,
        to_date(diary_end_time) as diary_end_date,
        --diary_end_time,
        substring(diary_end_time, 12,8) as diary_end_time,
        diary_complete,
        count_in_call_rate,
        null as todo_type,
        null as to_do_option_desc,
        acct_key,
        create_user_key,
        null as store_chk_date,
        null as prod_grp_key,
        null as todo_desc,
        null as to_do_start_date,
        null as to_do_end_date,
        null as work_item_desc,
        null as work_item_type,
        null as work_item_start_date,
        null as work_item_end_date,
        null as survery_notes,
        null as fail_reason_desc,
        null as req_start_date,
        null as req_end_date,
        null as oa_acct_key,
        null as oa_start_date,
        null as oa_end_date,
        null as oa_points,
        null as batch_count,
        null as activated,
        null as over_and_above_notes,
        null as question_response,
        to_date(diary_start_time) as dash_start_time,
        to_date(diary_end_time) as dash_end_time,
        cycle_start_date,
        cycle_end_date,
        cycle_number,
        null as parent_question,
        null as question_order,
        null as survey_target_type,
        null as survey_target,
        null as survey_category,
        null as objective_key,
        null as call_description,
        null as assigned_user_key,
        null as assigned_user_name,
        null as due_dt,
        null as completed_dt,
        null as status,
        null as diary_session_start_time,
        null as diary_session_end_time,
        null as duration,
        null as latitude,
        null as longitude
    from edw_perenso_call
),
union_2 as
(
    select 
        perenso_source,
        diary_item_type_desc,
        diary_item_category,
        to_date(diary_start_time) as diary_start_date,
        --diary_start_time,
        substring(diary_start_time, 12,8) as diary_start_time,
        to_date(diary_end_time) as diary_end_date,
        --diary_end_time,
        substring(diary_end_time, 12,8) as diary_end_time,
        diary_complete,
        count_in_call_rate,
        todo_type,
        null as to_do_option_desc,
        acct_key,
        create_user_key,
        store_chk_date,
        prod_grp_key,
        todo_desc,
        to_do_start_date,
        to_do_end_date,
        work_item_desc,
        work_item_type,
        work_item_start_date,
        work_item_end_date,
        null as survery_notes,
        fail_reason_desc,
        req_start_date,
        req_end_date,
        null as oa_acct_key,
        null as oa_start_date,
        null as oa_end_date,
        null as oa_points,
        null as batch_count,
        null as activated,
        null as over_and_above_notes,
        case
            when req_state = 'Not Done' then 'Check Failed'
            when req_state = 'Done' then 'Check Passed'
            else req_state
        end as question_response,
        to_date(req_start_date) as dash_start_time,
        to_date(req_end_date) as dash_end_time,
        null as cycle_start_date,
        null as cycle_end_date,
        null as cycle_number,
        null as parent_question,
        null as question_order,
        null as survey_target_type,
        null as survey_target,
        null as survey_category,
        null as objective_key,
        null as call_description,
        null as assigned_user_key,
        null as assigned_user_name,
        null as due_dt,
        null as completed_dt,
        null as status,
        null as diary_session_start_time,
        null as diary_session_end_time,
        null as duration,
        null as latitude,
        null as longitude
    from edw_perenso_compliance
),
union_3 as
(
    select 
        perenso_source,
        diary_item_type_desc,
        diary_item_category,
        to_date(diary_start_time) as diary_start_date,
        --diary_start_time,
        substring(diary_start_time, 12,8) as diary_start_time,
        to_date(diary_end_time) as diary_end_date,
        --diary_end_time,
        substring(diary_end_time, 12,8) as diary_end_time,
        diary_complete,
        count_in_call_rate,
        todo_type,
        null as to_do_option_desc,
        st_chk_acct_key as acct_key,
        create_user_key,
        store_chk_date,
        prod_grp_key as prod_grp_key,
        to_do_option_desc as todo_desc,
        to_do_start_date,
        to_do_end_date,
        work_item_desc,
        work_item_type,
        work_item_start_date,
        work_item_end_date,
        null as survery_notes,
        null as fail_reason_desc,
        null as req_start_date,
        null as req_end_date,
        oa_acct_key,
        oa_start_date,
        oa_end_date,
        oa_points,
        batch_count,
        activated,
        over_and_above_notes,
        batch_count::varchar(10) as question_response,
        to_date(oa_start_date) as dash_start_time,
        to_date(oa_end_date) as dash_end_time,
        cycle_start_date,
        cycle_end_date,
        cycle_number,
        null as parent_question,
        null as question_order,
        null as survey_target_type,
        null as survey_target,
        null as survey_category,
        null as objective_key,
        null as call_description,
        null as assigned_user_key,
        null as assigned_user_name,
        null as due_dt,
        null as completed_dt,
        null as status,
        null as diary_session_start_time,
        null as diary_session_end_time,
        null as duration,
        null as latitude,
        null as longitude
    from edw_perenso_over_and_above
),
union_4 as
(
    select 
        perenso_source,
        diary_item_type_desc,
        diary_item_category,
        to_date(diary_start_time) as diary_start_date,
        --diary_start_time,
        substring(diary_start_time, 12,8) as diary_start_time,
        to_date(diary_end_time) as diary_end_date,
        --diary_end_time,
        substring(diary_end_time, 12,8) as diary_end_time,
        diary_complete,
        count_in_call_rate,
        todo_type,
        to_do_option_desc,
        acct_key,
        create_user_key,
        store_chk_date,
        prod_grp_key,
        todo_desc,
        to_do_start_date,
        to_do_end_date,
        work_item_desc,
        work_item_type,
        work_item_start_date,
        work_item_end_date,
        survery_notes,
        null as fail_reason_desc,
        null as req_start_date,
        null as req_end_date,
        null as oa_acct_key,
        null as oa_start_date,
        null as oa_end_date,
        null as oa_points,
        null as batch_count,
        null as activated,
        null as over_and_above_notes,
        case
            when to_do_option_desc is not null then to_do_option_desc
            when survery_notes is not null then survery_notes
            else null
        end as question_response,
        to_date(diary_start_time) as dash_start_time,
        to_date(diary_end_time) as dash_end_time,
        cycle_start_date,
        cycle_end_date,
        cycle_number,
        parent_ques as parent_question,
        ques_order as question_order,
        target_type as survey_target_type,
        target as survey_target,
        survey_category,
        null as objective_key,
        null as call_description,
        null as assigned_user_key,
        null as assigned_user_name,
        null as due_dt,
        null as completed_dt,
        null as status,
        null as diary_session_start_time,
        null as diary_session_end_time,
        null as duration,
        null as latitude,
        null as longitude
    from edw_perenso_survey
),
union_5 as
(
    select 
        'Objectives' as perenso_source,
        null as diary_item_type_desc,
        null as diary_item_category,
        to_date(call_created_dt) as diary_start_date,
        --diary_start_time,
        null as diary_start_time,
        null as diary_end_date,
        --diary_end_time,
        null as diary_end_time,
        null as diary_complete,
        null as count_in_call_rate,
        null as todo_type,
        null as to_do_option_desc,
        cast(acct_key as numeric(10)) as acct_key,
        cast(created_user_key as numeric(10)) as create_user_key,
        null as store_chk_date,
        null as prod_grp_key,
        null as todo_desc,
        null as to_do_start_date,
        null as to_do_end_date,
        null as work_item_desc,
        null as work_item_type,
        null as work_item_start_date,
        null as work_item_end_date,
        null as survery_notes,
        null as fail_reason_desc,
        null as req_start_date,
        null as req_end_date,
        null as oa_acct_key,
        null as oa_start_date,
        null as oa_end_date,
        null as oa_points,
        null as batch_count,
        null as activated,
        null as over_and_above_notes,
        case
            when to_do_option_desc is not null then to_do_option_desc
            when survery_notes is not null then survery_notes
            else null
        end as question_response,
        null as dash_start_time,
        null as dash_end_time,
        null as cycle_start_date,
        null as cycle_end_date,
        null as cycle_number,
        null as parent_question,
        null as question_order,
        null as survey_target_type,
        null as survey_target,
        null as survey_category,
        objective_key,
        description as call_description,
        assigned_user_key,
        display_name as assigned_user_name,
        to_date(due_dt) as due_dt,
        to_date(completed_dt) as completed_dt,
        status,
        null as diary_session_start_time,
        null as diary_session_end_time,
        null as duration,
        null as latitude,
        null as longitude
    from itg_perenso_call_objectives obj,
        itg_perenso_users ipu
    where obj.assigned_user_key = ipu.user_key(+)
),
union_6 as
(
    select 
        'Call' as perenso_source,
        --null as diary_item_type_desc,
        dity.diary_item_type_desc as diary_item_type_desc,
        null as diary_item_category,
        to_date(ipdi.start_time) as diary_start_date,
        --null as diary_start_time,
        substring(ipdi.start_time, 12,8) as diary_start_time,
        to_date(ipdi.end_time) as diary_end_date,
        --null as diary_end_date,
        --diary_end_time,
        substring(ipdi.end_time, 12,8) as diary_end_time,
        ipdi.complete as diary_complete,
        null as count_in_call_rate,
        null as todo_type,
        null as to_do_option_desc,
        acct_key as acct_key,
        create_user_key as create_user_key,
        null as store_chk_date,
        null as prod_grp_key,
        null as todo_desc,
        null as to_do_start_date,
        null as to_do_end_date,
        null as work_item_desc,
        null as work_item_type,
        null as work_item_start_date,
        null as work_item_end_date,
        null as survery_notes,
        null as fail_reason_desc,
        null as req_start_date,
        null as req_end_date,
        null as oa_acct_key,
        null as oa_start_date,
        null as oa_end_date,
        null as oa_points,
        null as batch_count,
        null as activated,
        null as over_and_above_notes,
        case
            when to_do_option_desc is not null then to_do_option_desc
            when survery_notes is not null then survery_notes
            else null
        end as question_response,
        null as dash_start_time,
        null as dash_end_time,
        null as cycle_start_date,
        null as cycle_end_date,
        null as cycle_number,
        null as parent_question,
        null as question_order,
        null as survey_target_type,
        null as survey_target,
        null as survey_category,
        null as objective_key,
        null as call_description,
        null as assigned_user_key,
        null as assigned_user_name,
        null as due_dt,
        null as completed_dt,
        null as status,
        diary_session_start_time,
        diary_session_end_time,
        duration,
        latitude,
        longitude
    from itg_perenso_diary_item_time dit,
        itg_perenso_diary_item ipdi,
        itg_perenso_diary_item_type dity
    where dit.diary_item_key = ipdi.diary_item_key (+)
        and ipdi.diary_item_type_key = dity.diary_item_type_key(+)
),
combined as
(
    select * from union_1
    union all
    select * from union_2
    union all
    select * from union_3
    union all
    select * from union_4    
    union all
    select * from union_5
    union all
    select * from union_6
),
final as
(
    select
        perenso_source::varchar(20) as perenso_source,
        diary_item_type_desc::varchar(255) as diary_item_type_desc,
        diary_item_category::varchar(255) as diary_item_category,
        diary_start_date::date as diary_start_date,
        diary_start_time::varchar(18) as diary_start_time,
        diary_end_date::date as diary_end_date,
        diary_end_time::varchar(18) as diary_end_time,
        diary_complete::varchar(5) as diary_complete,
        count_in_call_rate::varchar(5) as count_in_call_rate,
        todo_type::varchar(20) as todo_type,
        to_do_option_desc::varchar(256) as to_do_option_desc,
        acct_key::number(10,0) as acct_key,
        create_user_key::number(10,0) as create_user_key,
        store_chk_date::timestamp_ntz(9) as store_chk_date,
        prod_grp_key::number(18,0) as prod_grp_key,
        todo_desc::varchar(256) as todo_desc,
        to_do_start_date::timestamp_ntz(9) as to_do_start_date,
        to_do_end_date::timestamp_ntz(9) as to_do_end_date,
        work_item_desc::varchar(255) as work_item_desc,
        work_item_type::varchar(255) as work_item_type,
        work_item_start_date::timestamp_ntz(9) as work_item_start_date,
        work_item_end_date::timestamp_ntz(9) as work_item_end_date,
        survery_notes::varchar(16777216) as survery_notes,
        fail_reason_desc::varchar(256) as fail_reason_desc,
        req_start_date::timestamp_ntz(9) as req_start_date,
        req_end_date::timestamp_ntz(9) as req_end_date,
        oa_acct_key::number(18,0) as oa_acct_key,
        oa_start_date::timestamp_ntz(9) as oa_start_date,
        oa_end_date::timestamp_ntz(9) as oa_end_date,
        oa_points::number(21,3) as oa_points,
        batch_count::number(18,0) as batch_count,
        activated::varchar(10) as activated,
        over_and_above_notes::varchar(255) as over_and_above_notes,
        question_response::varchar(16777216) as question_response,
        dash_start_time::date as dash_start_time,
        dash_end_time::date as dash_end_time,
        cycle_start_date::date as cycle_start_date,
        cycle_end_date::date as cycle_end_date,
        cycle_number::varchar(25) as cycle_number,
        parent_question::varchar(256) as parent_question,
        question_order::number(18,0) as question_order,
        survey_target_type::varchar(25) as survey_target_type,
        survey_target::number(18,0) as survey_target,
        survey_category::varchar(100) as survey_category,
        objective_key::varchar(50) as objective_key,
        call_description::varchar(255) as call_description,
        assigned_user_key::varchar(50) as assigned_user_key,
        assigned_user_name::varchar(100) as assigned_user_name,
        due_dt::date as due_dt,
        completed_dt::date as completed_dt,
        status::varchar(50) as status,
        diary_session_start_time::timestamp_ntz(9) as diary_session_start_time,
        diary_session_end_time::timestamp_ntz(9) as diary_session_end_time,
        duration::varchar(50) as duration,
        latitude::varchar(50) as latitude,
        longitude::varchar(50) as longitude
    from combined
)
select * from final


