{% macro build_wks_la_gt_sales_order_fact_pre_load() %}
    
    {% set query %}
    CREATE TABLE if not exists thawks_integration.wks_la_gt_sales_order_fact_pre_load		
    (
    hashkey VARCHAR(500),
    saleunit VARCHAR(50),
    orderid VARCHAR(50),
    orderdate DATE,
    customer_id VARCHAR(50),
    customer_name VARCHAR(200),
    city VARCHAR(100),
    region VARCHAR(100),
    saledistrict VARCHAR(100),
    saleoffice VARCHAR(100),
    salegroup VARCHAR(100),
    customertype VARCHAR(200),
    storetype VARCHAR(200),
    saletype VARCHAR(100),
    salesemployee VARCHAR(100),
    salename VARCHAR(100),
    productid VARCHAR(50),
    productname VARCHAR(300),
    megabrand VARCHAR(100),
    brand VARCHAR(100),
    baseproduct VARCHAR(100),
    variant VARCHAR(100),
    putup VARCHAR(100),
    priceref VARCHAR(100),
    backlog VARCHAR(100),
    qty NUMERIC(18,4),
    subamt1 NUMERIC(18,4),
    discount NUMERIC(18,4),
    subamt2 NUMERIC(18,4),
    discountbtline NUMERIC(18,4),
    totalbeforevat NUMERIC(18,4),
    total NUMERIC(18,4),
    sales_order_line_no VARCHAR(50),
    canceled VARCHAR(50),
    documentid VARCHAR(50),
    return_reason VARCHAR(100),
    promotioncode VARCHAR(100),
    promotioncode1 VARCHAR(100),
    promotioncode2 VARCHAR(100),
    promotioncode3 VARCHAR(100),
    promotioncode4 VARCHAR(100),
    promotioncode5 VARCHAR(100),
    promotion_code VARCHAR(100),
    promotion_code2 VARCHAR(100),
    promotion_code3 VARCHAR(100),
    avgdiscount NUMERIC(18,4),
    ordertype VARCHAR(50),
    approverstatus VARCHAR(50),
    pricelevel VARCHAR(100),
    optional3 VARCHAR(100),
    deliverydate DATE,
    ordertime VARCHAR(20),
    shipto VARCHAR(100),
    billto VARCHAR(100),
    deliveryrouteid VARCHAR(50),
    approved_date DATE,
    approved_time VARCHAR(20),
    ref_15 VARCHAR(100),
    paymenttype VARCHAR(50),
    filename VARCHAR(50),
    run_id VARCHAR(14),
    crt_dttm TIMESTAMP WITHOUT TIME ZONE
    );
    TRUNCATE TABLE thawks_integration.wks_la_gt_sales_order_fact_pre_load;
    Insert into thawks_integration.wks_la_gt_sales_order_fact_pre_load
    (
        hashkey ,
        saleunit,
       orderid,
       orderdate,
       customer_id,
       customer_name,
       city,
       region,
       saledistrict,
       saleoffice,
       salegroup,
       customertype,
       storetype,
       saletype,
       salesemployee,
       salename,
       productid,
       productname,
       megabrand,
       brand,
       baseproduct,
       variant,
       putup,
       priceref,
       backlog,
       qty,
       subamt1,
       discount,
       subamt2,
       discountbtline,
       totalbeforevat,
       total,
       sales_order_line_no,
       canceled,
       documentid,
       return_reason,
       promotioncode,
       promotioncode1,
       promotioncode2,
       promotioncode3,
       promotioncode4,
       promotioncode5,
       promotion_code,
       promotion_code2,
       promotion_code3,
       avgdiscount,
       ordertype,
       approverstatus,
       pricelevel,
       optional3,
       deliverydate,
       ordertime,
       shipto,
       billto,
       deliveryrouteid,
       approved_date,
       approved_time,
       ref_15,
       paymenttype,
       filename,
       run_id,
       crt_dttm
    )
    SELECT 
        MD5(COALESCE(UPPER(saleunit),'N/A') ||coalesce (UPPER(orderid),'N/A') ||coalesce (orderdate,'9999-12-31') ||coalesce (UPPER(productid),'N/A') ||coalesce (UPPER(customer_id),'N/A') ||coalesce (sales_order_line_no,'N/A')) AS hashkey,
        saleunit,
        orderid,
        orderdate,
        customer_id,
        customer_name,
        city,
        region,
        saledistrict,
        saleoffice,
        salegroup,
        customertype,
        storetype,
        saletype,
        salesemployee,
        salename,
        productid,
        productname,
        megabrand,
        brand,
        baseproduct,
        variant,
        putup,
        priceref,
        backlog,
        qty,
        subamt1,
        discount,
        subamt2,
        discountbtline,
        totalbeforevat,
        total,
        sales_order_line_no,
        canceled,
        documentid,
        return_reason,
        promotioncode,
        promotioncode1,
        promotioncode2,
        promotioncode3,
        promotioncode4,
        promotioncode5,
        promotion_code,
        promotion_code2,
        promotion_code3,
        avgdiscount,
        ordertype,
        approverstatus,
        pricelevel,
        optional3,
        deliverydate,
        ordertime,
        shipto,
        billto,
        deliveryrouteid,
        approved_date,
        approved_time,
        ref_15,
        paymenttype,
        filename,
        run_id,
        crt_dttm
    FROM 
    {% if target=='prod' %}
                    thaitg_integration.itg_la_gt_sales_order_fact
                {% else %}
                    {{schema}}.thaitg_integration__itg_la_gt_sales_order_fact
                {% endif %}
    WHERE orderdate >= (SELECT MIN( to_date (orderdate , 'yyyy/mm/dd')) FROM {{ source('thasdl_raw', 'sdl_la_gt_sales_order_fact') }}
    )
    AND   UPPER(saleunit) IN (SELECT DISTINCT UPPER(saleunit)
                            FROM {{ source('thasdl_raw', 'sdl_la_gt_sales_order_fact') }}
                            );
    {% endset %}

    {% do run_query(query) %}
{% endmacro %}
