with source as (
    select * from {{ source('bwa_access', 'bwa_cdl_sales') }}
),
final as (
    select
        doc_number as doc_num,
        s_ord_item,
        rejectn_st,
        processkey as process_key,
        batch,
        createdon as created_on,
        salesdeal as sls_deal,
        stor_loc,
        matl_group as matl_grp,
        incoterms2,
        accnt_asgn,
        cust_group as cust_grp,
        cond_pr_un,
        incoterms,
        replace(iff(right(subtotal_4,1)='-',concat('-',replace(subtotal_4,'-','')),subtotal_4),' ','') as subtotal_4,
        replace(iff(right(subtotal_5,1)='-',concat('-',replace(subtotal_5,'-','')),subtotal_5),' ','') as subtotal_5,
        replace(iff(right(net_price,1)='-',concat('-',replace(net_price,'-','')),net_price),' ','') as net_price,
        replace(iff(right(net_value,1)='-',concat('-',replace(net_value,'-','')),net_value),' ','') as net_value,
        replace(iff(right(net_wt_ap,1)='-',concat('-',replace(net_wt_ap,'-','')),net_wt_ap),' ','') as net_wt_ap,
        cond_unit,
        unit_of_wt,
        order_curr,
        stat_curr,
        loc_currcy,
        replace(iff(right(target_qty,1)='-',concat('-',replace(target_qty,'-','')),target_qty),' ','') as target_qty,
        replace(iff(right(targ_value,1)='-',concat('-',replace(targ_value,'-','')),targ_value),' ','') as targ_value,
        replace(iff(right(ord_items,1)='-',concat('-',replace(ord_items,'-','')),ord_items),' ','') as ord_items,
        replace(iff(right(bic_zorqtycse,1)='-',concat('-',replace(bic_zorqtycse,'-','')),bic_zorqtycse),' ','') as zorqtycse,
        replace(iff(right(tax_value,1)='-',concat('-',replace(tax_value,'-','')),tax_value),' ','') as tax_value,
        to_number(exchg_rate,38,4) as exchg_rate,
        target_qu,
        replace(iff(right(cost,1)='-',concat('-',replace(cost,'-','')),cost),' ','') as cost,
        replace(iff(right(volume_ap,1)='-',concat('-',replace(volume_ap,'-','')),volume_ap),' ','') as volume_ap,
        volumeunit as volume_unit,
        replace(iff(right(exchg_stat,1)='-',concat('-',replace(exchg_stat,'-','')),exchg_stat),' ','') as exchg_stat,
        replace(iff(right(reqdel_qty,1)='-',concat('-',replace(reqdel_qty,'-','')),reqdel_qty),' ','') as reqdel_qty,
        replace(iff(right(lowr_bnd,1)='-',concat('-',replace(lowr_bnd,'-','')),lowr_bnd),' ','') as lowr_bnd,
        replace(iff(right(uppr_bnd,1)='-',concat('-',replace(uppr_bnd,'-','')),uppr_bnd),' ','') as uppr_bnd,
        replace(iff(right(numeratorz,1)='-',concat('-',replace(numeratorz,'-','')),numeratorz),' ','') as numeratorz,
        replace(iff(right(denomintrz,1)='-',concat('-',replace(denomintrz,'-','')),denomintrz),' ','') as denomintrz,
        replace(iff(right(numerator,1)='-',concat('-',replace(numerator,'-','')),numerator),' ','') as numerator,
        replace(iff(right(denomintr,1)='-',concat('-',replace(denomintr,'-','')),denomintr),' ','') as denomintr,
        min_dl_qty,
        replace(iff(right(subtotal_6,1)='-',concat('-',replace(subtotal_6,'-','')),subtotal_6),' ','') as subtotal_6,
        replace(iff(right(subtotal_3,1)='-',concat('-',replace(subtotal_3,'-','')),subtotal_3),' ','') as subtotal_3,
        wbs_elemt,
        refer_doc,
        replace(iff(right(subtotal_2,1)='-',concat('-',replace(subtotal_2,'-','')),subtotal_2),' ','') as subtotal_2,
        replace(iff(right(subtotal_1,1)='-',concat('-',replace(subtotal_1,'-','')),subtotal_1),' ','') as subtotal_1,
        doc_currcy,
        replace(iff(right(cml_or_qty,1)='-',concat('-',replace(cml_or_qty,'-','')),cml_or_qty),' ','') as cml_or_qty,
        replace(iff(right(cml_cd_qty,1)='-',concat('-',replace(cml_cd_qty,'-','')),cml_cd_qty),' ','') as cml_cd_qty,
        base_uom,
        material,
        refer_itm,
        fiscvarnt as fisc_varnt,
        apoplanned as apo_planned,
        logsys as log_sys,
        replace(iff(right(cml_cf_qty,1)='-',concat('-',replace(cml_cf_qty,'-','')),cml_cf_qty),' ','') as cml_cf_qty,
        sales_unit as sls_unit,
        doc_date as doc_dt,
        bic_zreq_date as zreq_dt,
        bic_zord_mth as zord_mth,
        sub_reason,
        doc_categr,
        div_head,
        trans_date as trans_dt,
        bill_date as bill_dt,
        prodcat as prod_cat,
        to_number(exchg_crd,38,4) as exchg_crd,
        sales_dist,
        serv_date as serv_dt,
        plant,
        rt_promo,
        mat_entrd,
        ship_point,
        prvdoc_ctg,
        crea_time,
        bilblk_itm,
        matl_grp_1,
        matl_grp_3,
        price_date as price_dt,
        matl_grp_4,
        matl_grp_5,
        route,
        salesemply as sls_emply,
        bnd_ind,
        replace(iff(right(gross_wgt,1)='-',concat('-',replace(gross_wgt,'-','')),gross_wgt),' ','') as gross_wgt,
        stat_date as stat_dt,
        division,
        st_up_dte as st_up_dt,
        ship_stck,
        forwagent,
        billtoprty as bill_to_prty,
        prod_hier,
        item_categ,
        ship_to,
        payer,
        unld_pt_we,
        matl_grp_2,
        eanupc,
        createdby as created_by,
        sts_bill,
        order_prob,
        bwapplnm,
        quot_from,
        ord_reason,
        ch_on,
        reason_rej,
        comp_code as comp_cd,
        distr_chan,
        salesorg as sls_org,
        sales_grp as sls_grp,
        sales_off as sls_off,
        doc_categ,
        rate_type,
        bill_block,
        cust_grp1,
        cust_grp2,
        cust_grp4,
        cust_grp3,
        cust_grp5,
        del_block,
        sold_to,
        quot_to,
        doc_type,
        sts_prc,
        sts_del,
        sts_itm,
        storno as stor_no,
        recordmode as record_mode,
        replace(iff(right(bic_zordqtybu,1)='-',concat('-',replace(bic_zordqtybu,'-','')),bic_zordqtybu),' ','') as zordqtybu,
        bic_zzp_num as zzp_num,
        bic_zzp_itm as zzp_itm,
        bic_ztarqtycu as ztarqtycu,
        bic_ztarqtybu as ztarqtybu,
        bic_zhighritm as zhighritm,
        null as cdl_dttm,
        current_timestamp()::timestamp_ntz(9) as curr_dt,
        trim(split(file_name,'/')[array_size(split(file_name,'/'))-1],'"') as file_name
    from source
    where _deleted_='F'
)

select * from final