with source as(
    select * from {{ source('aspsdl_raw', 'sdl_sap_billing_condition') }}
),
final as(
    SELECT
  bill_num,
  bill_item,
  zstepnum,
  kncounter,
  doc_number,
  s_ord_item,
  knart,
  ch_on,
  comp_code,
  sales_dist,
  bill_type,
  bill_date,
  bill_cat,
  loc_currcy,
  cust_group,
  sold_to,
  payer,
  exrate_acc,
  stat_curr,
  doc_categ,
  salesorg,
  distr_chan,
  doc_currcy,
  createdon,
  co_area,
  costcenter,
  trans_date,
  exchg_rate,
  cust_grp1,
  cust_grp2,
  cust_grp3,
  cust_grp4,
  cust_grp5,
  matl_group,
  material,
  mat_entrd,
  matl_grp_1,
  matl_grp_2,
  matl_grp_3,
  matl_grp_4,
  matl_grp_5,
  billtoprty,
  ship_to,
  itm_type,
  prod_hier,
  prov_group,
  price_date,
  item_categ,
  div_head,
  division,
  stat_date,
  refer_doc,
  refer_itm,
  sales_off,
  sales_grp,
  wbs_elemt,
  calday,
  calmonth,
  calweek,
  fiscper,
  fiscvarnt,
  knclass,
  knorigin,
  kntyp,
  knval,
  kprice,
  kinak,
  kstat,
  storno,
  rt_promo,
  rebate_grp,
  bwapplnm,
  processkey,
  eanupc,
  createdby,
  serv_date,
  inv_qty,
  forwagent,
  salesemply,
  sales_unit,
  kappl,
  acrn_id,
  recordmode,
  CURRENT_TIMESTAMP()::TIMESTAMP_NTZ(9) as crt_dttm,
  NULL as source_file_name,
  NULL as File_name
  from source
)

select * from final
