
with 

source as (

    select * from {{ source('apc_access', 'apc_mbew') }}

),

final as (
    select 
        trim(MANDT) as MANDT,
        trim(MATNR) as MATNR,
        trim(BWKEY) as BWKEY,
        trim(BWTAR) as BWTAR,
        LVORM,
        replace(LBKUM,'*','') as LBKUM,
        replace(SALK3,'*','') as SALK3,
        VPRSV,
        replace(VERPR,'*','') as VERPR,
        replace(STPRS,'*','') as STPRS,
        PEINH,
        BKLAS,
        replace(SALKV,'*','') as SALKV,
        VMKUM,
        replace(VMSAL,'*','') as VMSAL,
        VMVPR,
        VMVER,
        replace(VMSTP,'*','') as VMSTP,
        VMPEI,
        VMBKL,
        replace(VMSAV,'*','') as VMSAV,
        VJKUM,
        replace(VJSAL,'*','') as VJSAL,
        VJVPR,
        VJVER,
        replace(VJSTP,'*','') as VJSTP,
        VJPEI,
        VJBKL,
        VJSAV,
        LFGJA,
        LFMON,
        BWTTY,
        replace(STPRV,'*','') as STPRV,
        LAEPR,
        ZKPRS,
        ZKDAT,
        timestamp as timestamps,
        BWPRS,
        BWPRH,
        VJBWS,
        VJBWH,
        replace(VVJSL,'*','') as VVJSL,
        VVJLB,
        VVMLB,
        replace(VVSAL,'*','') as VVSAL,
        replace(ZPLPR,'*','') as ZPLPR,
        replace(ZPLP1,'*','') as ZPLP1,
        replace(ZPLP2,'*','') as ZPLP2,
        replace(ZPLP3,'*','') as ZPLP3,
        ZPLD1,
        ZPLD2,
        ZPLD3,
        PPERZ,
        PPERL,
        PPERV,
        KALKZ,
        KALKL,
        KALKV,
        KALSC,
        XLIFO,
        MYPOL,
        BWPH1,
        BWPS1,
        ABWKZ,
        PSTAT,
        KALN1,
        KALNR,
        BWVA1,
        BWVA2,
        BWVA3,
        VERS1,
        VERS2,
        VERS3,
        HRKFT,
        KOSGR,
        PPRDZ,
        PPRDL,
        PPRDV,
        PDATZ,
        PDATL,
        PDATV,
        EKALR,
        VPLPR,
        MLMAA,
        MLAST,
        replace(LPLPR,'*','') as LPLPR,
        VKSAL,
        HKMAT,
        SPERW,
        KZIWL,
        WLINL,
        ABCIW,
        BWSPA,
        replace(LPLPX,'*','') as LPLPX,
        VPLPX,
        FPLPX,
        LBWST,
        VBWST,
        FBWST,
        EKLAS,
        QKLAS,
        MTUSE,
        MTORG,
        OWNPR,
        XBEWM,
        BWPEI,
        MBRUE,
        OKLAS,
        OIPPINV,
        current_timestamp()::timestamp_ntz(9) as crt_dttm,
        current_timestamp()::timestamp_ntz(9) as updt_dttm
    from source
    where _deleted_='F' and mandt='888'

)

select * from final
