
with source as(
    select * from {{ source('apc_access', 'apc_mvke') }}
),
final as(
    select
        mandt as mandt,
        matnr as matnr,
        vkorg as vkorg,
        vtweg as vtweg,
        lvorm as lvorm,
        versg as versg,
        bonus as bonus,
        provg as provg,
        sktof as sktof,
        vmsta as vmsta,
        vmstd as vmstd,
        aumng as aumng,
        lfmng as lfmng,
        efmng as efmng,
        scmng as scmng,
        schme as schme,
        vrkme as vrkme,
        mtpos as mtpos,
        dwerk as dwerk,
        prodh as prodh,
        pmatn as pmatn,
        kondm as kondm,
        ktgrm as ktgrm,
        mvgr1 as mvgr1,
        mvgr2 as mvgr2,
        mvgr3 as mvgr3,
        mvgr4 as mvgr4,
        mvgr5 as mvgr5,
        sstuf as sstuf,
        pflks as pflks,
        lstfl as lstfl,
        lstvz as lstvz,
        lstak as lstak,
        ldvfl as ldvfl,
        ldbfl as ldbfl,
        ldvzl as ldvzl,
        ldbzl as ldbzl,
        vdvfl as vdvfl,
        vdbfl as vdbfl,
        vdvzl as vdvzl,
        vdbzl as vdbzl,
        prat1 as prat1,
        prat2 as prat2,
        prat3 as prat3,
        prat4 as prat4,
        prat5 as prat5,
        prat6 as prat6,
        prat7 as prat7,
        prat8 as prat8,
        prat9 as prat9,
        prata as prata,
        rdprf as rdprf,
        megru as megru,
        lfmax as lfmax,
        rjart as rjart,
        pbind as pbind,
        vavme as vavme,
        matkc as matkc,
        pvmso as pvmso,
        _bev1_emlgrp as _bev1_emlgrp,
        _bev1_emdrckspl as _bev1_emdrckspl,
        _bev1_rpbezme as _bev1_rpbezme,
        _bev1_rpsns as _bev1_rpsns,
        _bev1_rpsfa as _bev1_rpsfa,
        _bev1_rpski as _bev1_rpski,
        _bev1_rpsco as _bev1_rpsco,
        _bev1_rpsso as _bev1_rpsso,
        plgtp as plgtp,
        zzbis as zzbis,
        zzean as zzean,
        zpack01 as zpack01,
        zzkos as zzkos,
        zzmattype as zzmattype,
        zzpredece as zzpredece,
        zzlaunchd as zzlaunchd,
        zzpcode as zzpcode,
        zzprodtype as zzprodtype,
        zz_npi as zz_npi,
        -- _deleted_ as _deleted_,
        -- _pk_ as _pk_,
        _createtime_::timestamp_ntz(9) as crt_dttm,
        -- _kafkaoffset_ as _kafkaoffset_,
        -- _upt_ as _upt_,
        -- _kafkatimestamp_ as _kafkatimestamp_,
        -- _infa_bigint_sequence_ as _infa_bigint_sequence_,
        pk_md5 as pk_md5,
        null as file_name
    from source
    where _deleted_='F'

)
select * from final