{{
    config(
        sql_header= "ALTER SESSION SET TIMEZONE = 'Asia/Singapore';"
    )
}}

with source as(
    select * from {{ source('aspsdl_raw', 'sdl_sap_bw_delivery') }}
),
final as(
    SELECT
  deliv_num,
  deliv_item,
  incoterms,
  incoterms2,
  unload_pt,
  grs_wgt_dl,
  unit_of_wt,
  dlv_qty,
  denomintr,
  numerator,
  shp_pr_tmf,
  shp_pr_tmv,
  sls_unit,
  volume_unit,
  no_del_it,
  volume_dl,
  act_dl_qty,
  net_wgt_dl,
  base_uom,
  refer_doc,
  refer_item,
  fisc_varnt,
  sold_to,
  cust_grp,
  bill_block,
  ship_to,
  load_pt,
  sls_org,
  created_by,
  created_on,
  whse_num,
  strge_bin,
  strge_type,
  matl_grp_3,
  matl_grp_4,
  sls_off,
  del_wa_dh,
  wbs_elemt,
  prvdoc_ctg,
  st_up_dt,
  distr_chan,
  zactdldte,
  matl_grp_5,
  division,
  itm_type,
  sls_grp,
  stat_dt,
  crea_time,
  item_categ,
  plant,
  bwapplnm,
  creditor,
  doc_categ,
  forwagent,
  matl_grp,
  sls_emply,
  material,
  prod_hier,
  payer,
  bill_to_prty,
  matl_grp_2,
  matl_grp_1,
  mat_entrd,
  stor_loc,
  eanupc,
  pick_indc,
  consu_flag,
  cust_grp3,
  bus_area,
  cust_grp5,
  cust_grp4,
  cust_grp2,
  cust_grp1,
  bilblk_dl,
  batch,
  route,
  ship_point,
  del_block,
  del_type,
  ship_dt,
  goodsmv_st,
  sales_dist,
  gi_dt,
  act_gi_dt,
  comp_cd,
  rt_promo,
  process_key,
  ch_on,
  pick_conf,
  sts_pick,
  stor_no,
  record_mode,
  zdelqtybu,
  zdlqtycse,
  cdl_dttm as cdl_dttm,
  current_timestamp()::timestamp_ntz(9) as CURR_DT,
  NULL as File_name
  FROM source
)

select * from final