with source as (
    select * from {{ source('bwa_access', 'bwa_cdl_sales') }}
),
final as (
    select
        doc_number,
        s_ord_item,
        rejectn_st,
        processkey,
        batch,
        createdon,
        salesdeal,
        stor_loc,
        matl_group,
        incoterms2,
        accnt_asgn,
        cust_group,
        cond_pr_un,
        incoterms,
        subtotal_4,
        subtotal_5,
        net_price,
        net_value,
        net_wt_ap,
        cond_unit,
        unit_of_wt,
        order_curr,
        stat_curr,
        loc_currcy,
        target_qty,
        targ_value,
        ord_items,
        BIC_zorqtycse,
        tax_value,
        exchg_rate,
        target_qu,
        cost,
        volume_ap,
        volumeunit,
        exchg_stat,
        reqdel_qty,
        lowr_bnd,
        uppr_bnd,
        numeratorz,
        denomintrz,
        numerator,
        denomintr,
        min_dl_qty,
        subtotal_6,
        subtotal_3,
        wbs_elemt,
        refer_doc,
        subtotal_2,
        subtotal_1,
        doc_currcy,
        cml_or_qty,
        cml_cd_qty,
        base_uom,
        material,
        refer_itm,
        fiscvarnt,
        apoplanned,
        logsys,
        cml_cf_qty,
        sales_unit,
        doc_date,
        BIC_zreq_date as zreq_date,
        BIC_zord_mth as zord_mth,
        sub_reason,
        doc_categr,
        div_head,
        trans_date,
        bill_date,
        prodcat,
        TO_NUMBER(exchg_crd,38,4) AS exchg_crd,
        sales_dist,
        serv_date,
        plant,
        rt_promo,
        mat_entrd,
        ship_point,
        prvdoc_ctg,
        crea_time,
        bilblk_itm,
        matl_grp_1,
        matl_grp_3,
        price_date,
        matl_grp_4,
        matl_grp_5,
        route,
        salesemply,
        bnd_ind,
        gross_wgt,
        stat_date,
        division,
        st_up_dte,
        ship_stck,
        forwagent,
        billtoprty,
        prod_hier,
        item_categ,
        ship_to,
        payer,
        unld_pt_we,
        matl_grp_2,
        eanupc,
        createdby,
        sts_bill,
        order_prob,
        bwapplnm,
        quot_from,
        ord_reason,
        ch_on,
        reason_rej,
        comp_code,
        distr_chan,
        salesorg,
        sales_grp,
        sales_off,
        doc_categ,
        rate_type,
        bill_block,
        cust_grp1,
        cust_grp2,
        cust_grp4,
        cust_grp3,
        cust_grp5,
        del_block,
        sold_to,
        quot_to,
        doc_type,
        sts_prc,
        sts_del,
        sts_itm,
        storno,
        recordmode,
        BIC_zordqtybu as zordqtybu,
        BIC_zzp_num as zzp_num,
        BIC_zzp_itm as zzp_itm,
        BIC_ztarqtycu as ztarqtycu,
        BIC_ztarqtybu as ztarqtybu,
        BIC_zhighritm as zhighritm,
        current_timestamp()::timestamp_ntz(9) as crt_dttm,
        current_timestamp()::timestamp_ntz(9) as updt_dttm
    from source
)

select * from final