with

source as (

    select * from {{ source('bwa_access', 'bwa_cdl_billing') }}

),

final as (

    select
        bill_num as bill_num,
        bill_item as bill_item,
        bill_date as bill_dt,
        bill_type as bill_type,
        sold_to as sold_to,
        rt_promo as rt_promo,
        s_ord_item as s_ord_item,
        doc_number as doc_num,
        grs_wgt_dl as grs_wgt_dl,
        inv_qty as inv_qty,
        bill_qty as bill_qty,
        base_uom as base_uom,
        exchg_rate as exchg_rate,
        req_qty as req_qty,
        sales_unit as sls_unit,
        payer as payer,
        rebate_bas as rebate_bas,
        no_inv_it as no_inv_it,
        subtotal_1 as subtotal_1,
        subtotal_3 as subtotal_3,
        subtotal_4 as subtotal_4,
        subtotal_2 as subtotal_2,
        netval_inv as netval_inv,
        exchg_stat as exchg_stat,
        bic_zblqtycse as zblqtycse,
        exratexacc as exratexacc,
        subtotal_6 as subtotal_6,
        gross_val as gross_val,
        unit_of_wt as unit_of_wt,
        subtotal_5 as subtotal_5,
        numerator as numerator,
        cost as cost,
        plant as plant,
        volume_dl as volume_dl,
        loc_currcy as loc_currcy,
        denomintr as denomintr,
        volumeunit as volume_unit,
        scale_qty as scale_qty,
        cshdsc_bas as cshdsc_bas,
        net_wgt_dl as net_wgt_dl,
        tax_amount as tax_amt,
        rate_type as rate_type,
        salesorg as sls_org,
        exrate_acc as exrate_acc,
        distr_chan as distr_chnl,
        doc_currcy as doc_currcy,
        co_area as co_area,
        doc_categ as doc_categ,
        fiscvarnt as fisc_varnt,
        costcenter as cost_center,
        matl_group as matl_group,
        division as division,
        material as material,
        sales_grp as sls_grp,
        div_head as div_head,
        ship_point as ship_point,
        wbs_elemt as wbs_elemt,
        bill_rule as bill_rule,
        bwapplnm as bwapplnm,
        processkey as process_key,
        cust_group as cust_grp,
        sales_off as sls_off,
        refer_itm as refer_itm,
        matl_grp_3 as matl_grp_3,
        price_date as price_dt,
        salesemply as sls_emply,
        refer_doc as refer_doc,
        st_up_dte as st_up_dte,
        stat_date as stat_date,
        item_categ as item_categ,
        prov_group as prov_grp,
        matl_grp_5 as matl_grp_5,
        prod_hier as prod_hier,
        itm_type as itm_type,
        matl_grp_4 as matl_grp_4,
        ship_to as ship_to,
        billtoprty as bill_to_prty,
        rebate_grp as rebate_grp,
        matl_grp_2 as matl_grp_2,
        matl_grp_1 as matl_grp_1,
        eanupc as eanupc,
        mat_entrd as mat_entrd,
        batch as batch,
        stor_loc as stor_loc,
        createdon as created_on,
        serv_date as serv_date,
        cust_grp5 as cust_grp5,
        salesdeal as sls_deal,
        bill_cat as bill_cat,
        cust_grp1 as cust_grp1,
        cust_grp3 as cust_grp3,
        trans_date as trans_dt,
        cust_grp4 as cust_grp4,
        cust_grp2 as cust_grp2,
        stat_curr as stat_curr,
        ch_on as ch_on,
        comp_code as comp_cd,
        sales_dist as sls_dist,
        storno as stor_no,
        recordmode as record_mode,
        customer as customer,
        cust_sales as cust_sls,
        oi_ebeln as oi_ebeln,
        oi_ebelp as oi_ebelp,
        bic_zsd_pod as zsd_pod,
        current_timestamp()::timestamp_ntz(9) as crt_dttm,
        current_timestamp()::timestamp_ntz(9) as updt_dttm
    from source

)

select * from final
