--Overwriding default SQL header as we dont want to change timezone to Singapore
{{
    config(
        sql_header= ""
    )
}}

--Import CTE
with v_edw_rpt_anz_re as (
    select * from {{ source('pcfedw_integration', 'v_edw_rpt_anz_re') }}
),
--Logical CTE

--Final CTE
final as (
SELECT FISC_YR,
       CAST(FISC_PER AS numeric(18,0) ) AS FISC_PER,		--// INTEGER
       CLUSTER,
       MARKET,
       CHANNEL_NAME,
       DISTRIBUTOR_CODE,
       DISTRIBUTOR_NAME,
       SELL_OUT_CHANNEL,
       STORE_TYPE,
       PRIORITIZATION_SEGMENTATION,
       STORE_CATEGORY,
       STORE_CODE,
       STORE_NAME,
       STORE_GRADE,
       STORE_SIZE,
       REGION,
       ZONE_NAME,
       CITY,
       RTRLATITUDE,
       RTRLONGITUDE,
       CUSTOMER_SEGMENT_KEY,
       CUSTOMER_SEGMENT_DESCRIPTION,
       RETAIL_ENVIRONMENT,
       SAP_CUSTOMER_CHANNEL_KEY,
       SAP_CUSTOMER_CHANNEL_DESCRIPTION,
       SAP_CUSTOMER_SUB_CHANNEL_KEY,
       SAP_SUB_CHANNEL_DESCRIPTION,
       SAP_PARENT_CUSTOMER_KEY,
       SAP_PARENT_CUSTOMER_DESCRIPTION,
       SAP_BANNER_KEY,
       SAP_BANNER_DESCRIPTION,
       SAP_BANNER_FORMAT_KEY,
       SAP_BANNER_FORMAT_DESCRIPTION,
       CUSTOMER_NAME,
       CUSTOMER_CODE,
       PRODUCT_CODE,
       PRODUCT_NAME,
       PROD_HIER_L1,
       PROD_HIER_L2,
       PROD_HIER_L3,
       PROD_HIER_L4,
       PROD_HIER_L5,
       PROD_HIER_L6,
       PROD_HIER_L7,
       PROD_HIER_L8,
       PROD_HIER_L9,
       MAPPED_SKU_CD,
       SAP_PROD_SGMT_CD,
       SAP_PROD_SGMT_DESC,
       SAP_BASE_PROD_DESC,
       SAP_MEGA_BRND_DESC,
       SAP_BRND_DESC,
       SAP_VRNT_DESC,
       SAP_PUT_UP_DESC,
       SAP_GRP_FRNCHSE_CD,
       SAP_GRP_FRNCHSE_DESC,
       SAP_FRNCHSE_CD,
       SAP_FRNCHSE_DESC,
       SAP_PROD_FRNCHSE_CD,
       SAP_PROD_FRNCHSE_DESC,
       SAP_PROD_MJR_CD,
       SAP_PROD_MJR_DESC,
       SAP_PROD_MNR_CD,
       SAP_PROD_MNR_DESC,
       SAP_PROD_HIER_CD,
       SAP_PROD_HIER_DESC,
       PKA_FRANCHISE_DESC,
       PKA_BRAND_DESC,
       PKA_SUB_BRAND_DESC,
       PKA_VARIANT_DESC,
       PKA_SUB_VARIANT_DESC,
       GLOBAL_PRODUCT_FRANCHISE,
       GLOBAL_PRODUCT_BRAND,
       GLOBAL_PRODUCT_SUB_BRAND,
       GLOBAL_PRODUCT_VARIANT,
       GLOBAL_PRODUCT_SEGMENT,
       GLOBAL_PRODUCT_SUBSEGMENT,
       GLOBAL_PRODUCT_CATEGORY,
       GLOBAL_PRODUCT_SUBCATEGORY,
       GLOBAL_PUT_UP_DESCRIPTION,
       EAN,
       SKU_CODE,
       SKU_DESCRIPTION,
       PKA_PRODUCT_KEY,
       PKA_PRODUCT_KEY_DESCRIPTION,
       SALES_VALUE,
       SALES_QTY,
       AVG_SALES_QTY,
       LM_SALES,
       LM_SALES_QTY,
       LM_AVG_SALES_QTY,
       P3M_SALES,
       P3M_QTY,
       P3M_AVG_QTY,
       P6M_SALES,
       P6M_QTY,
       P6M_AVG_QTY,
       P12M_SALES,
       P12M_QTY,
       P12M_AVG_QTY,
       F3M_SALES,
       F3M_QTY,
       F3M_AVG_QTY,
       LM_SALES_FLAG,
       P3M_SALES_FLAG,
       P6M_SALES_FLAG,
       P12M_SALES_FLAG,
       MDP_FLAG,
       TARGET_COMPLAINCE,
       LIST_PRICE,
       SIZE_OF_PRICE_LM,
       SIZE_OF_PRICE_P3M,
       SIZE_OF_PRICE_P6M,
       SIZE_OF_PRICE_P12M,
       LM_SALES_FLAG_COUNT,
       P3M_SALES_FLAG_COUNT,
       P6M_SALES_FLAG_COUNT,
       P12M_SALES_FLAG_COUNT,
       MDP_FLAG_COUNT,
       DATA_SRC,
       SALES_VALUE_LIST_PRICE,
       LM_SALES_LP,
       P3M_SALES_LP,
       P6M_SALES_LP,
       P12M_SALES_LP,
       SIZE_OF_PRICE_LM_LP,
       SIZE_OF_PRICE_P3M_LP,
       SIZE_OF_PRICE_P6M_LP,
       SIZE_OF_PRICE_P12M_LP,
       --SOLDTO_CODE,
SYSDATE()		--// SYSDATE
FROM v_edw_rpt_anz_re
WHERE market in ('Australia','New Zealand') 
AND   FISC_PER >= (SELECT REPLACE(SUBSTRING(add_months (TO_DATE(MAX(fisc_per)::varchar,'YYYYMM'),-1),1,7),'-','')::INTEGER
                   FROM v_edw_rpt_anz_re)
AND   FISC_PER <= (SELECT MAX(fisc_per) FROM v_edw_rpt_anz_re)

)


--Final select
select * from final 