with cnpc_edw_rpt_retail_excellence as (
    select * from {{ ref('chnedw_integration__edw_cnpc_rpt_retail_excellence') }}
),

cnpc_edw_rpt_retail_excellence_details as 
(
select fisc_yr,
       fisc_per,
       "cluster",
	   market,
       channel_name,
       distributor_code,
       distributor_name,
       sell_out_channel,
       store_type,
       prioritization_segmentation,
       store_category,
       store_code,
       store_name,
       store_grade,
       store_size,
       region,  
       zone_name,
       city,
       rtrlatitude,
       rtrlongitude,
       customer_segment_key,
       customer_segment_description,
       retail_environment,
       sap_customer_channel_key,
       sap_customer_channel_description,
       sap_customer_sub_channel_key,
       sap_sub_channel_description,
       sap_parent_customer_key,
       sap_parent_customer_description,
       sap_banner_key,
       sap_banner_description,
       sap_banner_format_key,
       sap_banner_format_description,
       customer_name,
       customer_code,
       product_code,
       product_name,
       prod_hier_l1,
       prod_hier_l2,
       prod_hier_l3,
       prod_hier_l4,
       prod_hier_l5,
       prod_hier_l6,
       prod_hier_l7,
       prod_hier_l8,
       prod_hier_l9,
	   mapped_sku_cd,
       sap_prod_sgmt_cd,
       sap_prod_sgmt_desc,
       sap_base_prod_desc,
       sap_mega_brnd_desc,
       sap_brnd_desc,
       sap_vrnt_desc,
       sap_put_up_desc,    
	   sap_grp_frnchse_cd,
	   sap_grp_frnchse_desc,
	   sap_frnchse_cd,
	   sap_frnchse_desc,
	   sap_prod_frnchse_cd,
	   sap_prod_frnchse_desc,
	   sap_prod_mjr_cd,
	   sap_prod_mjr_desc,
	   sap_prod_mnr_cd,
	   sap_prod_mnr_desc,
	   sap_prod_hier_cd,
	   sap_prod_hier_desc,	   
	   pka_franchise_desc, 
	   pka_brand_desc, 
	   pka_sub_brand_desc, 
	   pka_variant_desc, 
	   pka_sub_variant_desc,	   
       global_product_franchise,
       global_product_brand,
       global_product_sub_brand,
       global_product_variant,
       global_product_segment,
       global_product_subsegment,
       global_product_category,
       global_product_subcategory,
       global_put_up_description,
       ean,
       --sku_code,
       --sku_description,
       pka_product_key,
       pka_product_key_description,
       sales_value,
       sales_qty,
       avg_sales_qty,
       lm_sales,
       lm_sales_qty,
       lm_avg_sales_qty,
       p3m_sales,
       p3m_qty,
       p3m_avg_qty,
       p6m_sales,
       p6m_qty,
       p6m_avg_qty,
       p12m_sales,
       p12m_qty,
       p12m_avg_qty,
       f3m_sales,
       f3m_qty,
       f3m_avg_qty,
       lm_sales_flag,
       p3m_sales_flag,
       p6m_sales_flag,
       p12m_sales_flag,
       mdp_flag,
	   target_complaince,
	   list_price,																
	   size_of_price_lm,
	   size_of_price_p3m,
	   size_of_price_p6m,
	   size_of_price_p12m,
       lm_sales_flag_count,
	   p3m_sales_flag_count,
	   p6m_sales_flag_count,
	   p12m_sales_flag_count,
       mdp_flag_count,
		data_src,
sales_value_list_price,	
		 lm_sales_lp,
		 p3m_sales_lp,
		 p6m_sales_lp,			
		 p12m_sales_lp,			  
		size_of_price_lm_lp,
	   size_of_price_p3m_lp,
	   size_of_price_p6m_lp,
	   size_of_price_p12m_lp,
	   soldto_code,
	   sysdate() as crt_dttm	
      	      from cnpc_edw_rpt_retail_excellence
    WHERE FISC_PER >= (SELECT REPLACE(SUBSTRING(add_months (TO_DATE(TO_CHAR(MAX(FISC_PER)),'YYYYMM'),-1),1,7),'-','')::INTEGER
                    FROM cnpc_edw_rpt_retail_excellence)		
    AND   FISC_PER <= (SELECT MAX(FISC_PER) FROM cnpc_edw_rpt_retail_excellence)
	and data_src is not null 
),

final as
(
    select
    fisc_yr::VARCHAR(11) AS fisc_yr,
    fisc_per::numeric(18,0) AS fisc_per,
    "cluster"::VARCHAR(100) as "cluster",
    market::VARCHAR(20) AS market,
    channel_name::VARCHAR(500) AS channel_name,
    distributor_code::VARCHAR(500) AS distributor_code,
    distributor_name::VARCHAR(500) AS distributor_name,
    sell_out_channel::VARCHAR(255) AS sell_out_channel,
    store_type::VARCHAR(500) AS store_type,
    prioritization_segmentation::VARCHAR(100) AS prioritization_segmentation,
    store_category::VARCHAR(203) AS store_category,
    store_code::VARCHAR(500) AS store_code,
    store_name::VARCHAR(500) AS store_name,
    store_grade::VARCHAR(100) AS store_grade,
    store_size::VARCHAR(100) AS store_size,
    region::VARCHAR(255) AS region,
    zone_name::VARCHAR(510) AS zone_name,
    city::VARCHAR(255) AS city,
    rtrlatitude::VARCHAR(100) AS rtrlatitude,
    rtrlongitude::VARCHAR(100) AS rtrlongitude,
    customer_segment_key::VARCHAR(12) AS customer_segment_key,
    customer_segment_description::VARCHAR(200) AS customer_segment_description,
    retail_environment::VARCHAR(500) AS retail_environment,
    sap_customer_channel_key::VARCHAR(12) AS sap_customer_channel_key,
    sap_customer_channel_description::VARCHAR(75) AS sap_customer_channel_description,
    sap_customer_sub_channel_key::VARCHAR(12) AS sap_customer_sub_channel_key,
    sap_sub_channel_description::VARCHAR(75) AS sap_sub_channel_description,
    sap_parent_customer_key::VARCHAR(12) AS sap_parent_customer_key,
    sap_parent_customer_description::VARCHAR(75) AS sap_parent_customer_description,
    sap_banner_key::VARCHAR(12) AS sap_banner_key,
    sap_banner_description::VARCHAR(75) AS sap_banner_description,
    sap_banner_format_key::VARCHAR(12) AS sap_banner_format_key,
    sap_banner_format_description::VARCHAR(75) AS sap_banner_format_description,
    customer_name::VARCHAR(200) AS customer_name,
    customer_code::VARCHAR(20) AS customer_code,
    product_code::VARCHAR(500) AS product_code,
    product_name::VARCHAR(500) AS product_name,
    prod_hier_l1::VARCHAR(50) AS prod_hier_l1,
    prod_hier_l2::VARCHAR(200) AS prod_hier_l2,
    prod_hier_l3::VARCHAR(255) AS prod_hier_l3,
    prod_hier_l4::VARCHAR(255) AS prod_hier_l4,
    prod_hier_l5::VARCHAR(255) AS prod_hier_l5,
    prod_hier_l6::VARCHAR(255) AS prod_hier_l6,
    prod_hier_l7::VARCHAR(200) AS prod_hier_l7,
    prod_hier_l8::VARCHAR(200) AS prod_hier_l8,
    prod_hier_l9::VARCHAR(250) AS prod_hier_l9,
    mapped_sku_cd::VARCHAR(50) AS mapped_sku_cd,
    sap_prod_sgmt_cd::VARCHAR(18) AS sap_prod_sgmt_cd,
    sap_prod_sgmt_desc::VARCHAR(100) AS sap_prod_sgmt_desc,
    sap_base_prod_desc::VARCHAR(100) AS sap_base_prod_desc,
    sap_mega_brnd_desc::VARCHAR(100) AS sap_mega_brnd_desc,
    sap_brnd_desc::VARCHAR(100) AS sap_brnd_desc,
    sap_vrnt_desc::VARCHAR(100) AS sap_vrnt_desc,
    sap_put_up_desc::VARCHAR(100) AS sap_put_up_desc,
    sap_grp_frnchse_cd::VARCHAR(18) AS sap_grp_frnchse_cd,
    sap_grp_frnchse_desc::VARCHAR(100) AS sap_grp_frnchse_desc,
    sap_frnchse_cd::VARCHAR(18) AS sap_frnchse_cd,
    sap_frnchse_desc::VARCHAR(100) AS sap_frnchse_desc,
    sap_prod_frnchse_cd::VARCHAR(18) AS sap_prod_frnchse_cd,
    sap_prod_frnchse_desc::VARCHAR(100) AS sap_prod_frnchse_desc,
    sap_prod_mjr_cd::VARCHAR(18) AS sap_prod_mjr_cd,
    sap_prod_mjr_desc::VARCHAR(100) AS sap_prod_mjr_desc,
    sap_prod_mnr_cd::VARCHAR(18) AS sap_prod_mnr_cd,
    sap_prod_mnr_desc::VARCHAR(100) AS sap_prod_mnr_desc,
    sap_prod_hier_cd::VARCHAR(18) AS sap_prod_hier_cd,
    sap_prod_hier_desc::VARCHAR(100) AS sap_prod_hier_desc,
    pka_franchise_desc::VARCHAR(30) AS pka_franchise_desc,
    pka_brand_desc::VARCHAR(30) AS pka_brand_desc,
    pka_sub_brand_desc::VARCHAR(30) AS pka_sub_brand_desc,
    pka_variant_desc::VARCHAR(30) AS pka_variant_desc,
    pka_sub_variant_desc::VARCHAR(30) AS pka_sub_variant_desc,
    global_product_franchise::VARCHAR(30) AS global_product_franchise,
    global_product_brand::VARCHAR(30) AS global_product_brand,
    global_product_sub_brand::VARCHAR(100) AS global_product_sub_brand,
    global_product_variant::VARCHAR(100) AS global_product_variant,
    global_product_segment::VARCHAR(100) AS global_product_segment,
    global_product_subsegment::VARCHAR(100) AS global_product_subsegment,
    global_product_category::VARCHAR(100) AS global_product_category,
    global_product_subcategory::VARCHAR(100) AS global_product_subcategory,
    global_put_up_description::VARCHAR(100) AS global_put_up_description,
    ean::VARCHAR(500) AS ean,
    mapped_sku_cd::VARCHAR(200) AS sku_code,
    null ::VARCHAR(500) AS sku_description,
    pka_product_key::VARCHAR(68) AS pka_product_key,
    pka_product_key_description::VARCHAR(255) AS pka_product_key_description,
    sales_value::NUMERIC(38,6) AS sales_value,
    sales_qty::NUMERIC(38,6) AS sales_qty,
    avg_sales_qty::NUMERIC(38,6) AS avg_sales_qty,
    lm_sales::NUMERIC(38,6) AS lm_sales,
    lm_sales_qty::NUMERIC(38,6) AS lm_sales_qty,
    lm_avg_sales_qty::NUMERIC(38,6) AS lm_avg_sales_qty,
    p3m_sales::NUMERIC(38,6) AS p3m_sales,
    p3m_qty::NUMERIC(38,6) AS p3m_qty,
    p3m_avg_qty::NUMERIC(38,6) AS p3m_avg_qty,
    p6m_sales::NUMERIC(38,6) AS p6m_sales,
    p6m_qty::NUMERIC(38,6) AS p6m_qty,
    p6m_avg_qty::NUMERIC(38,6) AS p6m_avg_qty,
    p12m_sales::NUMERIC(38,6) AS p12m_sales,
    p12m_qty::NUMERIC(38,6) AS p12m_qty,
    p12m_avg_qty::NUMERIC(38,6) AS p12m_avg_qty,
    f3m_sales::NUMERIC(38,6) AS f3m_sales,
    f3m_qty::NUMERIC(38,6) AS f3m_qty,
    f3m_avg_qty::NUMERIC(38,6) AS f3m_avg_qty,
    lm_sales_flag::VARCHAR(1) AS lm_sales_flag,
    p3m_sales_flag::VARCHAR(1) AS p3m_sales_flag,
    p6m_sales_flag::VARCHAR(1) AS p6m_sales_flag,
    p12m_sales_flag::VARCHAR(1) AS p12m_sales_flag,
    mdp_flag::VARCHAR(1) AS mdp_flag,
    target_complaince::numeric(38,6) AS target_complaince,
    list_price::NUMERIC(20,4) AS list_price,
    size_of_price_lm::NUMERIC(38,14) AS size_of_price_lm,
    size_of_price_p3m::NUMERIC(38,14) AS size_of_price_p3m,
    size_of_price_p6m::NUMERIC(38,14) AS size_of_price_p6m,
    size_of_price_p12m::NUMERIC(38,14) AS size_of_price_p12m,
    lm_sales_flag_count::numeric(38,0) AS lm_sales_flag_count,
    p3m_sales_flag_count::numeric(38,0) AS p3m_sales_flag_count,
    p6m_sales_flag_count::numeric(38,0) AS p6m_sales_flag_count,
    p12m_sales_flag_count::numeric(38,0) AS p12m_sales_flag_count,
    mdp_flag_count::numeric(38,0) AS mdp_flag_count,
    data_src::VARCHAR(14) AS data_src,
    sales_value_list_price::NUMERIC(38,6) AS sales_value_list_price,
    lm_sales_lp::NUMERIC(38,6) AS lm_sales_lp,
    p3m_sales_lp::NUMERIC(38,6) AS p3m_sales_lp,
    p6m_sales_lp::NUMERIC(38,6) AS p6m_sales_lp,
    p12m_sales_lp::NUMERIC(38,6) AS p12m_sales_lp,
    size_of_price_lm_lp::NUMERIC(38,14) AS size_of_price_lm_lp,
    size_of_price_p3m_lp::NUMERIC(38,14) AS size_of_price_p3m_lp,
    size_of_price_p6m_lp::NUMERIC(38,14) AS size_of_price_p6m_lp,
    size_of_price_p12m_lp::NUMERIC(38,14) AS size_of_price_p12m_lp,
    soldto_code::VARCHAR(20) AS soldto_code,
    crt_dttm::TIMESTAMP WITHOUT TIME ZONE AS crt_dttm
	from 
cnpc_edw_rpt_retail_excellence_details 
)

select * from final
