with source as 
(

   select * from {{ source('phlsdl_raw','sdl_mds_ph_hce_product_master_adftemp')}} 
),
transformed as 
(
    select 
    ID::NUMBER(10,0) AS ID,
MUID::VARCHAR(40) AS MUID,
VERSIONNAME::VARCHAR(100) AS VERSIONNAME,
VERSIONNUMBER::NUMBER(10,0) AS VERSIONNUMBER,
VERSION_ID::NUMBER(10,0) AS VERSION_ID,
VERSIONFLAG::VARCHAR(100) AS VERSIONFLAG,
NAME::VARCHAR(500) AS NAME,
CODE::VARCHAR(500) AS CODE,
CHANGETRACKINGMASK::NUMBER(10,0) AS CHANGETRACKINGMASK,
GROUP_VARIANT_CODE::VARCHAR(500) AS GROUP_VARIANT_CODE,
GROUP_VARIANT_NAME::VARCHAR(500) AS GROUP_VARIANT_NAME,
GROUP_VARIANT_ID::NUMBER(10,0) AS GROUP_VARIANT_ID,
TEAM_CODE::VARCHAR(500) AS TEAM_CODE,
TEAM_NAME::VARCHAR(500) AS TEAM_NAME,
TEAM_ID::NUMBER(10,0) AS TEAM_ID,
SAP_ITEM_CODE::VARCHAR(200) AS SAP_ITEM_CODE,
ENTERDATETIME::TIMESTAMP_NTZ(9) AS ENTERDATETIME,
ENTERUSERNAME::VARCHAR(200) AS ENTERUSERNAME,
ENTERVERSIONNUMBER::NUMBER(10,0) AS ENTERVERSIONNUMBER,
LASTCHGDATETIME::TIMESTAMP_NTZ(9) AS LASTCHGDATETIME,
LASTCHGUSERNAME::VARCHAR(200) AS LASTCHGUSERNAME,
LASTCHGVERSIONNUMBER::NUMBER(10,0) AS LASTCHGVERSIONNUMBER,
VALIDATIONSTATUS::VARCHAR(500) AS VALIDATIONSTATUS,
current_timestamp ::timestamp_ntz(9) as crtd_dttm 
    from source
)
select * from transformed
