with source as 
(
    select * from  {{source ('phlsdl_raw','sdl_mds_ph_hcp_store_master')}}
),
transformed as
(
    select 
      ID::NUMBER(10,0) AS ID,
MUID::VARCHAR(40) AS MUID,
VERSIONNAME::VARCHAR(100) AS VERSIONNAME,
VERSIONNUMBER::NUMBER(10,0) AS VERSIONNUMBER,
VERSION_ID::NUMBER(10,0) AS VERSION_ID,
VERSIONFLAG::VARCHAR(100) AS VERSIONFLAG,
NAME::VARCHAR(500) AS NAME,
CODE::VARCHAR(500) AS CODE,
CHANGETRACKINGMASK::NUMBER(10,0) AS CHANGETRACKINGMASK,
CUSTOMER_CODE::VARCHAR(500) AS CUSTOMER_CODE,
CUSTOMER_NAME::VARCHAR(500) AS CUSTOMER_NAME,
CUSTOMER_ID::NUMBER(10,0) AS CUSTOMER_ID,
STORE_CODE::VARCHAR(300) AS STORE_CODE,
GROUP_VARIANT_CODE::VARCHAR(500) AS GROUP_VARIANT_CODE,
GROUP_VARIANT_NAME::VARCHAR(500) AS GROUP_VARIANT_NAME,
GROUP_VARIANT_ID::NUMBER(10,0) AS GROUP_VARIANT_ID,
TERRITORY_CODE_CODE::VARCHAR(500) AS TERRITORY_CODE_CODE,
TERRITORY_CODE_NAME::VARCHAR(500) AS TERRITORY_CODE_NAME,
TERRITORY_CODE_ID::NUMBER(10,0) AS TERRITORY_CODE_ID,
SALES_ALLOCATED::NUMBER(38,4) AS SALES_ALLOCATED,
DISTRICT_CODE::VARCHAR(500) AS DISTRICT_CODE,
DISTRICT_NAME::VARCHAR(500) AS DISTRICT_NAME,
DISTRICT_ID::NUMBER(10,0) AS DISTRICT_ID,
ENTERDATETIME::TIMESTAMP_NTZ(9) AS ENTERDATETIME,
ENTERUSERNAME::VARCHAR(200) AS ENTERUSERNAME,
ENTERVERSIONNUMBER::NUMBER(10,0) AS ENTERVERSIONNUMBER,
LASTCHGDATETIME::TIMESTAMP_NTZ(9) AS LASTCHGDATETIME,
LASTCHGUSERNAME::VARCHAR(200) AS LASTCHGUSERNAME,
LASTCHGVERSIONNUMBER::NUMBER(10,0) AS LASTCHGVERSIONNUMBER,
VALIDATIONSTATUS::VARCHAR(500) AS VALIDATIONSTATUS,
current_timestamp()::timestamp_ntz(9) as crtd_dttm
from source
)
select * from transformed
