version: 2

models:
  - name: ntawks_integration__wks_edw_ims_invnt
    config:
      alias: wks_edw_ims_invnt
      tags: ["","transformation"]
  - name: ntawks_integration__wks_hk_allmonths_base
    config:
      alias: wks_hk_allmonths_base
      tags: ["","transformation"]
  - name: ntawks_integration__wks_hk_base_detail
    config:
      alias: wks_hk_base_detail
      tags: ["","transformation"]
  - name: ntawks_integration__hk_propagate_to
    config:
      alias: hk_propagate_to
      tags: ["","transformation"]
  - name: ntawks_integration__hk_propagate_from_to
    config:
      alias: hk_propagate_from_to
      tags: ["","transformation"]
  - name: ntawks_integration__wks_hk_siso_propagate_to_details
    config:
      alias: wks_hk_siso_propagate_to_details
      tags: ["","transformation"]
  - name: ntawks_integration__wks_HK_siso_propagate_to_existing_dtls
    config:
      alias: wks_HK_siso_propagate_to_existing_dtls
      tags: ["","transformation"]
  - name: ntawks_integration__wks_hk_siso_propagate_final
    config:
      alias: wks_hk_siso_propagate_final
      tags: ["","transformation"]
  - name: ntawks_integration__wks_hk_inventory_healthy_unhealthy_analysis
    config:
      alias: wks_hk_inventory_healthy_unhealthy_analysis
      tags: ["","transformation"]
  

  
  

  
 