-- edw_pacific_pharmacy_weekly_dist_analysis
-- alter table edw_pacific_pharmacy_dstrbtn_analysis rename to edw_pacific_pharmacy_weekly_dist_analysis;

-- commit;

with 
edw_time_dim as (
select * from {{ source('pcfedw_integration', 'edw_time_dim') }}
),
wks_au_pharma_dstrbtn_summary as (
select * from {{ ref('pcfwks_integration__wks_au_pharma_dstrbtn_summary') }}
),
edw_perenso_prod_dim as (
select * from {{ ref('pcfedw_integration__edw_perenso_prod_dim') }}
),
edw_perenso_account_dim as (
select * from {{ ref('pcfedw_integration__edw_perenso_account_dim') }}
),
edw_ps_msl_items as (
select * from {{ ref('pcfedw_integration__edw_ps_msl_items') }}
),
transformed as (
select wapds.delvry_dt,
       etd.time_id,
       etd.jj_year,
       etd.jj_qrtr,
       etd.jj_mnth,
       etd.jj_wk,
       --etd.jj_mnth_wk,
       etd.jj_mnth_id,
       etd.jj_mnth_tot,
       etd.jj_mnth_day,
       etd.jj_mnth_shrt,
       etd.jj_mnth_long,
       etd.cal_year,
       etd.cal_qrtr,
       etd.cal_mnth,
       --etd.cal_wk,
       --etd.cal_mnth_wk,
       etd.cal_mnth_id,
       etd.cal_mnth_nm,
       wapds.prod_key,
	     eppd.prod_desc,
       eppd.prod_id as prod_sapbw_code,
       eppd.prod_ean,
       eppd.prod_jj_franchise,
       eppd.prod_jj_category,
       eppd.prod_jj_brand,
       eppd.prod_sap_franchise,
       eppd.prod_sap_profit_centre,
       eppd.prod_sap_product_major,
       eppd.prod_grocery_franchise,
       eppd.prod_grocery_category,
       eppd.prod_grocery_brand,
       case 
             when (eppd.prod_active_nz_pharma != 'not assigned' 
                  or eppd.prod_active_au_grocery != 'not assigned' 
                  or eppd.prod_active_metcash != 'not assigned' 
                  or eppd.prod_active_nz_grocery != 'not assigned' 
                  or eppd.prod_active_au_pharma != 'not assigned')
             then 1
             else 0
       end prod_active_status,
       eppd.prod_pbs,
       eppd.prod_ims_brand,
       eppd.prod_nz_code,
       eppd.prod_metcash_code,
	     eppd.prod_old_id,
       eppd.prod_old_ean,
       eppd.prod_tax,
       eppd.prod_bwp_aud,
       eppd.prod_bwp_nzd,
	     wapds.acct_key as acct_key,
	     epad.acct_display_name,
       epad.acct_type_desc,
       epad.acct_street_1,
       epad.acct_street_2,
       epad.acct_street_3,
       epad.acct_suburb,
       epad.acct_postcode,
       epad.acct_phone_number,
       epad.acct_fax_number,
       epad.acct_email,
       epad.acct_country,
       epad.acct_region,
       epad.acct_state,
       epad.acct_banner_country,
       epad.acct_banner_division,
       epad.acct_banner_type,
       epad.acct_banner,
       epad.acct_type,
       epad.acct_sub_type,
       epad.acct_grade,
       epad.acct_nz_pharma_country,
       epad.acct_nz_pharma_state,
       epad.acct_nz_pharma_territory,
       epad.acct_nz_groc_country,
       epad.acct_nz_groc_state,
       epad.acct_nz_groc_territory,
       epad.acct_ssr_country,
       epad.acct_ssr_state,
       epad.acct_ssr_team_leader,
       epad.acct_ssr_territory,
       epad.acct_ssr_sub_territory,
       epad.acct_ind_groc_country,
       epad.acct_ind_groc_state,
       epad.acct_ind_groc_territory,
       epad.acct_ind_groc_sub_territory,
       epad.acct_au_pharma_country,
       epad.acct_au_pharma_state,
       epad.acct_au_pharma_territory,
       epad.acct_au_pharma_ssr_country,
       epad.acct_au_pharma_ssr_state,
       epad.acct_au_pharma_ssr_territory,
       case 
              when upper(epad.acct_ind_groc_state) != 'NOT ASSIGNED' then epad.acct_ind_groc_state
              when upper(epad.acct_au_pharma_state) != 'NOT ASSIGNED' then epad.acct_au_pharma_state
			  when upper(epad.acct_nz_pharma_state) != 'NOT ASSIGNED' then epad.acct_nz_pharma_state
              else 'NOT ASSIGNED'
       end  acct_tsm,
       case 
              when upper(epad.acct_ind_groc_territory) != 'NOT ASSIGNED' then epad.acct_ind_groc_territory
              when upper(epad.acct_au_pharma_territory) != 'NOT ASSIGNED' then epad.acct_au_pharma_territory
			  when upper(epad.acct_nz_pharma_territory) != 'NOT ASSIGNED' then epad.acct_nz_pharma_territory
              else 'NOT ASSIGNED'
       end  acct_terriroty,
	     epad.acct_store_code as acct_store_code,
	     epad.acct_fax_opt_out,
       epad.acct_email_opt_out,
       epad.acct_contact_method,
	     wapds.curnt_mnth_nis,
       wapds.curnt_mnth_qty,
       wapds.curnt_mnth_avg_lp,
       wapds.lst_mnth_nis,
       wapds.lst_mnth_qty,
       wapds.lst_mnth_avg_lp,
       wapds.lst3_mnth_nis,
       wapds.lst3_mnth_qty,
       wapds.lst3_mnth_avg_lp,
       wapds.lst6_mnth_nis,
       wapds.lst6_mnth_qty,
       wapds.lst6_mnth_avg_lp,
       wapds.lst12_mnth_nis,
       wapds.lst12_mnth_qty,
       wapds.lst12_mnth_avg_lp,
       wapds.curnt_mnth_dstrbtn_flag,
       wapds.lst_mnth_dstrbtn_flag,
       wapds.lst3_mnth_dstrbtn_flag,
       wapds.lst6_mnth_dstrbtn_flag,
       wapds.lst12_mnth_dstrbtn_flag,
       wapds.curnt_mnth_dstrbtn_trgt,
       wapds.lst_mnth_dstrbtn_trgt,
       wapds.lst3_mnth_dstrbtn_trgt,
       wapds.lst6_mnth_dstrbtn_trgt,
       wapds.lst12_mnth_dstrbtn_trgt,
	     epmi.msl_rank as pharmacy_msl_rank,
       epmi.msl_flag as pharmacy_msl_flag,
       current_timestamp() as load_date            
from edw_time_dim etd,
     wks_au_pharma_dstrbtn_summary wapds,
     edw_perenso_prod_dim eppd,
     edw_perenso_account_dim epad,
	 edw_ps_msl_items epmi
	 /*  (select *
      from vw_jjbr_curr_exch_dim
      where to_ccy = 'aud') jjbr,
     (select *
      from vw_bwar_curr_exch_dim
      where to_ccy = 'usd') bwar*/
where wapds.delvry_dt::date = etd.cal_date::date
and   wapds.prod_key = eppd.prod_key(+)
and   wapds.acct_key = epad.acct_id(+)
and   ltrim(eppd.prod_ean,0) = ltrim(epmi.ean(+),0)
and  upper(epmi.retail_environment (+)) = 'AU INDY PHARMACY'
and  epmi.latest_record(+)='Y'
),
final as (
    select
    delvry_dt::timestamp_ntz(9) as delvry_dt,
    time_id::number(18,0) as time_id,
    jj_year::number(18,0) as jj_year,
    jj_qrtr::number(18,0) as jj_qrtr,
    jj_mnth::number(18,0) as jj_mnth,
    jj_wk::number(18,0) as jj_wk,
    jj_mnth_id::number(18,0) as jj_mnth_id,
    jj_mnth_tot::number(18,0) as jj_mnth_tot,
    jj_mnth_day::number(18,0) as jj_mnth_day,
    jj_mnth_shrt::varchar(3) as jj_mnth_shrt,
    jj_mnth_long::varchar(10) as jj_mnth_long,
    cal_year::number(18,0) as cal_year,
    cal_qrtr::number(18,0) as cal_qrtr,
    cal_mnth::number(18,0) as cal_mnth,
    cal_mnth_id::number(18,0) as cal_mnth_id,
    cal_mnth_nm::varchar(10) as cal_mnth_nm,
    prod_key::varchar(21) as prod_key,
    prod_desc::varchar(100) as prod_desc,
    prod_sapbw_code::varchar(50) as prod_sapbw_code,
    prod_ean::varchar(50) as prod_ean,
    prod_jj_franchise::varchar(100) as prod_jj_franchise,
    prod_jj_category::varchar(100) as prod_jj_category,
    prod_jj_brand::varchar(100) as prod_jj_brand,
    prod_sap_franchise::varchar(100) as prod_sap_franchise,
    prod_sap_profit_centre::varchar(100) as prod_sap_profit_centre,
    prod_sap_product_major::varchar(100) as prod_sap_product_major,
    prod_grocery_franchise::varchar(100) as prod_grocery_franchise,
    prod_grocery_category::varchar(100) as prod_grocery_category,
    prod_grocery_brand::varchar(100) as prod_grocery_brand,
    prod_active_status::number(18,0) as prod_active_status,
    prod_pbs::varchar(100) as prod_pbs,
    prod_ims_brand::varchar(100) as prod_ims_brand,
    prod_nz_code::varchar(100) as prod_nz_code,
    prod_metcash_code::varchar(100) as prod_metcash_code,
    prod_old_id::varchar(50) as prod_old_id,
    prod_old_ean::varchar(50) as prod_old_ean,
    prod_tax::varchar(50) as prod_tax,
    prod_bwp_aud::varchar(50) as prod_bwp_aud,
    prod_bwp_nzd::varchar(50) as prod_bwp_nzd,
    acct_key::varchar(21) as acct_key,
    acct_display_name::varchar(256) as acct_display_name,
    acct_type_desc::varchar(50) as acct_type_desc,
    acct_street_1::varchar(256) as acct_street_1,
    acct_street_2::varchar(256) as acct_street_2,
    acct_street_3::varchar(256) as acct_street_3,
    acct_suburb::varchar(25) as acct_suburb,
    acct_postcode::varchar(25) as acct_postcode,
    acct_phone_number::varchar(50) as acct_phone_number,
    acct_fax_number::varchar(50) as acct_fax_number,
    acct_email::varchar(256) as acct_email,
    acct_country::varchar(256) as acct_country,
    acct_region::varchar(256) as acct_region,
    acct_state::varchar(256) as acct_state,
    acct_banner_country::varchar(256) as acct_banner_country,
    acct_banner_division::varchar(256) as acct_banner_division,
    acct_banner_type::varchar(256) as acct_banner_type,
    acct_banner::varchar(256) as acct_banner,
    acct_type::varchar(256) as acct_type,
    acct_sub_type::varchar(256) as acct_sub_type,
    acct_grade::varchar(256) as acct_grade,
    acct_nz_pharma_country::varchar(256) as acct_nz_pharma_country,
    acct_nz_pharma_state::varchar(256) as acct_nz_pharma_state,
    acct_nz_pharma_territory::varchar(256) as acct_nz_pharma_territory,
    acct_nz_groc_country::varchar(256) as acct_nz_groc_country,
    acct_nz_groc_state::varchar(256) as acct_nz_groc_state,
    acct_nz_groc_territory::varchar(256) as acct_nz_groc_territory,
    acct_ssr_country::varchar(256) as acct_ssr_country,
    acct_ssr_state::varchar(256) as acct_ssr_state,
    acct_ssr_team_leader::varchar(256) as acct_ssr_team_leader,
    acct_ssr_territory::varchar(256) as acct_ssr_territory,
    acct_ssr_sub_territory::varchar(256) as acct_ssr_sub_territory,
    acct_ind_groc_country::varchar(256) as acct_ind_groc_country,
    acct_ind_groc_state::varchar(256) as acct_ind_groc_state,
    acct_ind_groc_territory::varchar(256) as acct_ind_groc_territory,
    acct_ind_groc_sub_territory::varchar(256) as acct_ind_groc_sub_territory,
    acct_au_pharma_country::varchar(256) as acct_au_pharma_country,
    acct_au_pharma_state::varchar(256) as acct_au_pharma_state,
    acct_au_pharma_territory::varchar(256) as acct_au_pharma_territory,
    acct_au_pharma_ssr_country::varchar(256) as acct_au_pharma_ssr_country,
    acct_au_pharma_ssr_state::varchar(256) as acct_au_pharma_ssr_state,
    acct_au_pharma_ssr_territory::varchar(256) as acct_au_pharma_ssr_territory,
    acct_tsm::varchar(256) as acct_tsm,
    acct_terriroty::varchar(256) as acct_terriroty,
    acct_store_code::varchar(256) as acct_store_code,
    acct_fax_opt_out::varchar(256) as acct_fax_opt_out,
    acct_email_opt_out::varchar(256) as acct_email_opt_out,
    acct_contact_method::varchar(256) as acct_contact_method,
    curnt_mnth_nis::float as curnt_mnth_nis,
    curnt_mnth_qty::float as curnt_mnth_qty,
    curnt_mnth_avg_lp::number(38,6) as curnt_mnth_avg_lp,
    lst_mnth_nis::float as lst_mnth_nis,
    lst_mnth_qty::float as lst_mnth_qty,
    lst_mnth_avg_lp::number(38,6) as lst_mnth_avg_lp,
    lst3_mnth_nis::float as lst3_mnth_nis,
    lst3_mnth_qty::float as lst3_mnth_qty,
    lst3_mnth_avg_lp::number(38,6) as lst3_mnth_avg_lp,
    lst6_mnth_nis::float as lst6_mnth_nis,
    lst6_mnth_qty::float as lst6_mnth_qty,
    lst6_mnth_avg_lp::number(38,6) as lst6_mnth_avg_lp,
    lst12_mnth_nis::float as lst12_mnth_nis,
    lst12_mnth_qty::float as lst12_mnth_qty,
    lst12_mnth_avg_lp::number(38,6) as lst12_mnth_avg_lp,
    curnt_mnth_dstrbtn_flag::number(18,0) as curnt_mnth_dstrbtn_flag,
    lst_mnth_dstrbtn_flag::number(18,0) as lst_mnth_dstrbtn_flag,
    lst3_mnth_dstrbtn_flag::number(18,0) as lst3_mnth_dstrbtn_flag,
    lst6_mnth_dstrbtn_flag::number(18,0) as lst6_mnth_dstrbtn_flag,
    lst12_mnth_dstrbtn_flag::number(18,0) as lst12_mnth_dstrbtn_flag,
    curnt_mnth_dstrbtn_trgt::number(18,0) as curnt_mnth_dstrbtn_trgt,
    lst_mnth_dstrbtn_trgt::number(18,0) as lst_mnth_dstrbtn_trgt,
    lst3_mnth_dstrbtn_trgt::number(18,0) as lst3_mnth_dstrbtn_trgt,
    lst6_mnth_dstrbtn_trgt::number(18,0) as lst6_mnth_dstrbtn_trgt,
    lst12_mnth_dstrbtn_trgt::number(18,0) as lst12_mnth_dstrbtn_trgt,
    pharmacy_msl_rank::varchar(5) as pharmacy_msl_rank,
    pharmacy_msl_flag::varchar(5)pharmacy_msl_flag,
    load_date::timestamp_ntz(9) as load_date
    from transformed
),
select * from final