--import cte
with wks_my_base_re_raw as (
    select * from {{ ref('myswks_integration__wks_my_base_re_raw') }}
),
wks_my_regional_sellout_mapped_sku_cd as (
    select * from {{ ref('myswks_integration__wks_my_regional_sellout_mapped_sku_cd') }}
),

MY_BASE_RE  as (
SELECT CNTRY_CD,
       MD5(nvl (SOLDTO_CODE,'stc') ||nvl (DISTRIBUTOR_CODE,'dc') ||nvl (DISTRIBUTOR_NAME,'dn') ||nvl (STORE_CODE,'sc') ||nvl (EAN,'ean') ||nvl(sku_code,'sku')||nvl(MSL_PRODUCT_DESC,'mpd')||nvl (STORE_NAME,'sn') ||nvl (CHANNEL_NAME,'cn') ||nvl (SAP_PARENT_CUSTOMER_KEY,'spck') ||nvl (SAP_PARENT_CUSTOMER_DESCRIPTION,'spscd') ||nvl (SAP_CUSTOMER_CHANNEL_KEY,'scck') ||nvl (SAP_CUSTOMER_CHANNEL_DESCRIPTION,'sccd') ||nvl (SAP_CUSTOMER_SUB_CHANNEL_KEY,'scsck') ||nvl (SAP_SUB_CHANNEL_DESCRIPTION,'sscd') ||nvl (CUSTOMER_SEGMENT_KEY,'csk') ||nvl (CUSTOMER_SEGMENT_DESCRIPTION,'csd') ||nvl (SAP_GO_TO_MDL_KEY,'sgmk') ||nvl (SAP_GO_TO_MDL_DESCRIPTION,'sgmd') ||nvl (SAP_BANNER_KEY,'sbk') ||nvl (SAP_BANNER_DESCRIPTION,'sbd') ||nvl (SAP_BANNER_FORMAT_KEY,'sbfk') ||nvl (SAP_BANNER_FORMAT_DESCRIPTION,'sbfd') ||nvl (RETAIL_ENVIRONMENT,'re') ||nvl (GLOBAL_PRODUCT_FRANCHISE,'gpf') ||nvl (GLOBAL_PRODUCT_BRAND,'gpb') ||nvl (GLOBAL_PRODUCT_SUB_BRAND,'gpsb') ||nvl (GLOBAL_PRODUCT_VARIANT,'gpv') ||nvl (GLOBAL_PRODUCT_SEGMENT,'gps') ||nvl (GLOBAL_PRODUCT_SUBSEGMENT,'gpss') ||nvl (GLOBAL_PRODUCT_CATEGORY,'gpc') ||nvl (GLOBAL_PRODUCT_SUBCATEGORY,'gpsc') ||nvl (GLOBAL_PUT_UP_DESCRIPTION,'gpud') ||nvl (PKA_PRODUCT_KEY,'pk') ||nvl (PKA_PRODUCT_KEY_DESCRIPTION,'pkd')||nvl(store_type,'st')||nvl(Region,'rg')||nvl(zone_or_area,'ar')||nvl(store_grade,'sg')) AS SELLOUT_DIM_KEY,
       CNTRY_NM,
       DATA_SRC,
       SOLDTO_CODE,
       DISTRIBUTOR_CODE,
       DISTRIBUTOR_NAME|| '#' ||ltrim(DISTRIBUTOR_CODE,'0') AS DISTRIBUTOR_NAME,
       STORE_CODE,
	   store_grade,
       EAN,
       store_name||'#'||ltrim(store_code,'0') as STORE_NAME,
       RETAIL_ENVIRONMENT,
	   store_type,
	   sku_code,
	   msl_product_desc,
	   Region,zone_or_area,
       CHANNEL_NAME,
       SAP_PARENT_CUSTOMER_KEY,
       SAP_PARENT_CUSTOMER_DESCRIPTION,
       SAP_CUSTOMER_CHANNEL_KEY,
       SAP_CUSTOMER_CHANNEL_DESCRIPTION,
       SAP_CUSTOMER_SUB_CHANNEL_KEY,
       SAP_SUB_CHANNEL_DESCRIPTION,
       SAP_GO_TO_MDL_KEY,
       SAP_GO_TO_MDL_DESCRIPTION,
       SAP_BANNER_KEY,
       SAP_BANNER_DESCRIPTION,
       SAP_BANNER_FORMAT_KEY,
       SAP_BANNER_FORMAT_DESCRIPTION,
       CUSTOMER_SEGMENT_KEY,
       CUSTOMER_SEGMENT_DESCRIPTION,
       GLOBAL_PRODUCT_FRANCHISE,
       GLOBAL_PRODUCT_BRAND,
       GLOBAL_PRODUCT_SUB_BRAND,
       GLOBAL_PRODUCT_VARIANT,
       GLOBAL_PRODUCT_SEGMENT,
       GLOBAL_PRODUCT_SUBSEGMENT,
       GLOBAL_PRODUCT_CATEGORY,
       GLOBAL_PRODUCT_SUBCATEGORY,
       GLOBAL_PUT_UP_DESCRIPTION,
       PKA_PRODUCT_KEY,
       PKA_PRODUCT_KEY_DESCRIPTION,
       YEAR,
       MNTH_ID,
       SUM(sales_value_list_price) AS sales_value_list_price,
       SUM(SO_SLS_QTY) AS SO_SLS_QTY,
       SUM(SO_SLS_VALUE) AS SO_SLS_VALUE,
      TRUNC(AVG(SO_SLS_QTY) :: DECIMAL(10,2)) AS SO_AVG_QTY		--TRUNC(AVG(SELLOUT_SALES_QUANTITY) :: DECIMAL(38,6)) AS SO_AVG_QTY,
FROM (SELECT country_code AS CNTRY_CD,
             country_name AS CNTRY_NM,
             data_source AS DATA_SRC,
			 soldto_code,
			 
			LTRIM(DISTRIBUTOR_CODE,'0') AS DISTRIBUTOR_CODE,
             MAX(DISTRIBUTOR_NAME) OVER (PARTITION BY LTRIM(DISTRIBUTOR_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS DISTRIBUTOR_NAME,
             ltrim(STORE_CODE,0) as store_code,
              MAIN.EAN,		
              max(store_name) over ( PARTITION BY ltrim(STORE_CODE,0) ORDER BY cal_date desc,length(store_name) DESC  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS store_name ,
			  PD.SKU_CODE as SKU_Code,		
              PD.MSL_PRODUCT_DESC as msl_product_desc,		
			 case when data_source = 'SELL-OUT' then 'GT'
			      when data_source = 'POS' then 'MT' end AS RETAIL_ENVIRONMENT,
			 case when data_source = 'SELL-OUT' then store_grade
			      when data_source = 'POS' then store_type end AS store_type,
			 Region,zone_or_area,
             upper(case when data_source = 'SELL-OUT' then store_type
			      when data_source = 'POS' then store_grade end) AS CHANNEL_NAME,
			 store_grade,
             SAP_PARENT_CUSTOMER_KEY,
             SAP_PARENT_CUSTOMER_DESCRIPTION,
             SAP_CUSTOMER_CHANNEL_KEY,
             SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             SAP_CUSTOMER_SUB_CHANNEL_KEY,
             SAP_SUB_CHANNEL_DESCRIPTION,
             SAP_GO_TO_MDL_KEY,
             SAP_GO_TO_MDL_DESCRIPTION,
             SAP_BANNER_KEY,
             SAP_BANNER_DESCRIPTION,
             SAP_BANNER_FORMAT_KEY,
             SAP_BANNER_FORMAT_DESCRIPTION,
             CUSTOMER_SEGMENT_KEY,
             CUSTOMER_SEGMENT_DESCRIPTION,
GLOBAL_PRODUCT_FRANCHISE,
GLOBAL_PRODUCT_BRAND,
GLOBAL_PRODUCT_SUB_BRAND,
GLOBAL_PRODUCT_VARIANT,
GLOBAL_PRODUCT_SEGMENT,
GLOBAL_PRODUCT_SUBSEGMENT,
GLOBAL_PRODUCT_CATEGORY,
GLOBAL_PRODUCT_SUBCATEGORY ,
GLOBAL_PUT_UP_DESCRIPTION ,
PKA_PRODUCT_KEY ,
PKA_PRODUCT_KEY_DESCRIPTION,
             YEAR,
             MNTH_ID,
             sellout_value_list_price AS sales_value_list_price,
             SELLOUT_SALES_QUANTITY AS SO_SLS_QTY,
             SELLOUT_SALES_VALUE AS SO_SLS_VALUE
      from  wks_my_base_re_raw MAIN		
	      	   LEFT JOIN wks_my_regional_sellout_mapped_sku_cd PD		
            ON UPPER(MAIN.EAN)=PD.EAN) SELLOUT		
GROUP BY DISTRIBUTOR_CODE,
         DISTRIBUTOR_NAME,
         STORE_CODE,
         EAN,
         SOLDTO_CODE,
         YEAR,
         MNTH_ID,
         CNTRY_CD,
         CNTRY_NM,
         DATA_SRC,
         STORE_NAME,
         RETAIL_ENVIRONMENT,
		 store_type,
		 store_grade,
		 sku_code,
		 msl_product_desc,
	     Region,zone_or_area,
         CHANNEL_NAME,
         SAP_PARENT_CUSTOMER_KEY,
         SAP_PARENT_CUSTOMER_DESCRIPTION,
         SAP_CUSTOMER_CHANNEL_KEY,
         SAP_CUSTOMER_CHANNEL_DESCRIPTION,
         SAP_CUSTOMER_SUB_CHANNEL_KEY,
         SAP_SUB_CHANNEL_DESCRIPTION,
         SAP_GO_TO_MDL_KEY,
         SAP_GO_TO_MDL_DESCRIPTION,
         SAP_BANNER_KEY,
         SAP_BANNER_DESCRIPTION,
         SAP_BANNER_FORMAT_KEY,
         SAP_BANNER_FORMAT_DESCRIPTION,
         CUSTOMER_SEGMENT_KEY,
         CUSTOMER_SEGMENT_DESCRIPTION,
         GLOBAL_PRODUCT_FRANCHISE,
         GLOBAL_PRODUCT_BRAND,
         GLOBAL_PRODUCT_SUB_BRAND,
         GLOBAL_PRODUCT_VARIANT,
         GLOBAL_PRODUCT_SEGMENT,
         GLOBAL_PRODUCT_SUBSEGMENT,
         GLOBAL_PRODUCT_CATEGORY,
         GLOBAL_PRODUCT_SUBCATEGORY,
         GLOBAL_PUT_UP_DESCRIPTION,
         PKA_PRODUCT_KEY,
         PKA_PRODUCT_KEY_DESCRIPTION
)

--final select
select * from MY_BASE_RE