version: 2

models:
  - name: idnedw_integration__edw_reg_inventory_health_analysis_propagation
    config:
      alias: edw_reg_inventory_health_analysis_propagation
      tags: ["j_ap_id_reg_data_refresh","transformation"]
