with source as
(
    select * from {{ source('thasdl_raw', 'SDL_ECOM_AMS') }}
),
final as
(
SELECT
	ORDER_TIME::VARCHAR(50) as ORDER_TIME,
	ORDER_ID::VARCHAR(100) as ORDER_ID,
	ORDER_COMPLETED_TIME::VARCHAR(50) as ORDER_COMPLETED_TIME,
	VERIFIED_STATUS::VARCHAR(50) as VERIFIED_STATUS,
	CONVERSION_COMPLETED_TIME::VARCHAR(50) as CONVERSION_COMPLETED_TIME,
	BRAND_COMMISSION::NUMBER(20,4) as BRAND_COMMISSION,
	ITEM_ID::VARCHAR(50) as ITEM_ID,
	ITEM_NAME::VARCHAR(500) as ITEM_NAME,
	MODEL_ID::VARCHAR(50) as MODEL_ID,
	PRICE::NUMBER(20,4) as PRICE,
	PROMOTION_ID::VARCHAR(100) as PROMOTION_ID,
	QTY::NUMBER(38,0) as QTY,
	PURCHASE_VALUE::NUMBER(20,4) as PURCHASE_VALUE,
	L1_GLOBAL_CATEGORY::VARCHAR(100) as L1_GLOBAL_CATEGORY,
	L2_GLOBAL_CATEGORY::VARCHAR(255) as L2_GLOBAL_CATEGORY,
	L3_GLOBAL_CATEGORY::VARCHAR(255) as L3_GLOBAL_CATEGORY,
	ATTRI_COMMI_ID::VARCHAR(100) as ATTRI_COMMI_ID,
	CHANNEL::VARCHAR(100) as CHANNEL,
	COMMI_RATE::VARCHAR(100) as COMMI_RATE,
	EXPENSE::VARCHAR(100) as EXPENSE,
	DEDUCTION_STATUS::VARCHAR(100) as DEDUCTION_STATUS,
	DEDUCTION_METHOD::VARCHAR(100) as DEDUCTION_METHOD,
	DEDUCTION_TIME::VARCHAR(100) as DEDUCTION_TIME,
	SHOPE_NAME::VARCHAR(50) as SHOPE_NAME,
	FILENAME::VARCHAR(255) as filename,
	CRTD_DTTM :: TIMESTAMP_NTZ(9) as crtd_dttm,
	current_timestamp()::timestamp_ntz(9) as updt_dttm
from source
)
select * from final;