{{
    config(
        materialized= "incremental",
        incremental_strategy= "append",
        pre_hook = "{% if is_incremental() %}
                delete from {{this}}
                where (mc_cycle_plan_product_id) in (select mc_cycle_plan_product_id
                from {{ source('hcposesdl_raw', 'sdl_hcp_osea_mc_cycle_plan_product') }} stg_mc_cycle_plan_product
                where stg_mc_cycle_plan_product.mc_cycle_plan_product_id = mc_cycle_plan_product_id);
                {% endif %}"
    )
}}
with sdl_hcp_osea_mc_cycle_plan_product
as
(
select * from {{ source('hcposesdl_raw', 'sdl_hcp_osea_mc_cycle_plan_product') }}
)
,
transformed as
(
select 
MC_CYCLE_PLAN_PRODUCT_ID,
 (CASE WHEN UPPER(IS_DELETED) = 'TRUE' THEN 1 WHEN UPPER(IS_DELETED) IS NULL THEN 0 WHEN UPPER(IS_DELETED) = ' ' THEN 0 ELSE 0 END) AS IS_DELETED,
CYCLE_PLAN_PRODUCT_NAME,
RECORD_TYPE_ID,
CREATED_DATE,
CREATED_BY_ID,
LAST_MODIFIED_DATE,
LAST_MODIFIED_BY_ID,
SYSTEM_MODSTAMP,
MAY_EDIT,
CASE WHEN UPPER(IS_LOCKED) = 'TRUE' THEN 1 WHEN UPPER(IS_LOCKED) = 'FALSE' THEN 0 ELSE 0 END AS IS_LOCKED,	          
CYCLE_PLAN_CHANNEL,
CHANNEL,
CYCLE_PRODUCT,
EXTERNAL_ID,
LAST_CALCULATED,
PRODUCT_ACTIVITY_GOAL,
PRODUCT_ACTIVITY_MAX,
PRODUCT_ACTIVITY_REFMAINING,
PRODUCT_ACTIVITY_ACTUAL,
PRODUCT_ATTAINMENT,
PRODUCT_INTERACTIONS_ACTUALS,
PRODUCT_INTERACTIONS_EARNED,
PRODUCT_INTERACTIONS_GOAL,
PRODUCT,
VEEVA_EXTERNAL_ID,
DETAIL_PRIORITY,
PRODUCT_STATUS,
TEAM_PRODUCT_ACTIVITY_GOAL,
TEAM_PRODUCT_ACTIVITY_MAX,
TEAM_PRODUCT_ACTIVITY_REMAINING,
TEAM_PRODUCT_ACTIVITY_ACTUAL,
TEAM_PRODUCT_ATTAINMENT,
TEAM_PRODUCT_INTERACTIONS_ACTUAL,
TEAM_PRODUCT_INTERACTIONS_EARNED,
TEAM_PRODUCT_INTERACTIONS_GOAL,
TEAM_PRODUCT_STATUS,
ACTIVITY_GOAL_EDIT,
CYCLE_PLAN,
DETAIL_GROUP,
TEAM_ACTIVITY_GOAL_EDIT,
PRODUCT_LAST_ACTIVITY_DATE,
PRODUCT_LAST_ACTIVITY_DATETIME,
TEAM_PRODUCT_LAST_ACTIVITY_DATE,
TEAM_PRODUCT_LAST_ACTIVITY_DATETIME,
PRODUCT_LAST_ACTIVITY_DATE_1,
TEAM_PRODUCT_LAST_ACTIVITY_DATE_1,
MASTER_ALIGN_ID,
COUNTRY_CODE,
LEGACY_ID,
JJ_PRODUCT_ID18,
CLASSIFICATION,
ADOPTION_LEADER,
current_timestamp() as INSERTED_DATE,
       NULL as UPDATED_DATE 
from sdl_hcp_osea_mc_cycle_plan_product
)
,
final as
(select 
	MC_CYCLE_PLAN_PRODUCT_ID::VARCHAR(18) AS MC_CYCLE_PLAN_PRODUCT_ID,
IS_DELETED::NUMBER(38,0) AS IS_DELETED,
CYCLE_PLAN_PRODUCT_NAME::VARCHAR(255) AS CYCLE_PLAN_PRODUCT_NAME,
RECORD_TYPE_ID::VARCHAR(18) AS RECORD_TYPE_ID,
CREATED_DATE::TIMESTAMP_NTZ(9) AS CREATED_DATE,
CREATED_BY_ID::VARCHAR(18) AS CREATED_BY_ID,
LAST_MODIFIED_DATE::TIMESTAMP_NTZ(9) AS LAST_MODIFIED_DATE,
LAST_MODIFIED_BY_ID::VARCHAR(18) AS LAST_MODIFIED_BY_ID,
SYSTEM_MODSTAMP::TIMESTAMP_NTZ(9) AS SYSTEM_MODSTAMP,
MAY_EDIT::VARCHAR(10) AS MAY_EDIT,
IS_LOCKED::NUMBER(38,0) AS IS_LOCKED,
CYCLE_PLAN_CHANNEL::VARCHAR(50) AS CYCLE_PLAN_CHANNEL,
CHANNEL::VARCHAR(1300) AS CHANNEL,
CYCLE_PRODUCT::VARCHAR(100) AS CYCLE_PRODUCT,
EXTERNAL_ID::VARCHAR(100) AS EXTERNAL_ID,
LAST_CALCULATED::TIMESTAMP_NTZ(9) AS LAST_CALCULATED,
PRODUCT_ACTIVITY_GOAL::NUMBER(9,0) AS PRODUCT_ACTIVITY_GOAL,
PRODUCT_ACTIVITY_MAX::NUMBER(9,0) AS PRODUCT_ACTIVITY_MAX,
PRODUCT_ACTIVITY_REFMAINING::NUMBER(9,0) AS PRODUCT_ACTIVITY_REFMAINING,
PRODUCT_ACTIVITY_ACTUAL::NUMBER(9,0) AS PRODUCT_ACTIVITY_ACTUAL,
PRODUCT_ATTAINMENT::NUMBER(18,3) AS PRODUCT_ATTAINMENT,
PRODUCT_INTERACTIONS_ACTUALS::NUMBER(18,1) AS PRODUCT_INTERACTIONS_ACTUALS,
PRODUCT_INTERACTIONS_EARNED::NUMBER(18,1) AS PRODUCT_INTERACTIONS_EARNED,
PRODUCT_INTERACTIONS_GOAL::NUMBER(18,1) AS PRODUCT_INTERACTIONS_GOAL,
PRODUCT::VARCHAR(1300) AS PRODUCT,
VEEVA_EXTERNAL_ID::VARCHAR(100) AS VEEVA_EXTERNAL_ID,
DETAIL_PRIORITY::NUMBER(20) AS DETAIL_PRIORITY,
PRODUCT_STATUS::VARCHAR(40) AS PRODUCT_STATUS,
TEAM_PRODUCT_ACTIVITY_GOAL::NUMBER(18,1) AS TEAM_PRODUCT_ACTIVITY_GOAL,
TEAM_PRODUCT_ACTIVITY_MAX::NUMBER(18,1) AS TEAM_PRODUCT_ACTIVITY_MAX,
TEAM_PRODUCT_ACTIVITY_REMAINING::NUMBER(18,1) AS TEAM_PRODUCT_ACTIVITY_REMAINING,
TEAM_PRODUCT_ACTIVITY_ACTUAL::NUMBER(18,1) AS TEAM_PRODUCT_ACTIVITY_ACTUAL,
TEAM_PRODUCT_ATTAINMENT::NUMBER(18,3) AS TEAM_PRODUCT_ATTAINMENT,
TEAM_PRODUCT_INTERACTIONS_ACTUAL::NUMBER(18,1) AS TEAM_PRODUCT_INTERACTIONS_ACTUAL,
TEAM_PRODUCT_INTERACTIONS_EARNED::NUMBER(18,1) AS TEAM_PRODUCT_INTERACTIONS_EARNED,
TEAM_PRODUCT_INTERACTIONS_GOAL::NUMBER(18,1) AS TEAM_PRODUCT_INTERACTIONS_GOAL,
TEAM_PRODUCT_STATUS::VARCHAR(40) AS TEAM_PRODUCT_STATUS,
ACTIVITY_GOAL_EDIT::NUMBER(9,0) AS ACTIVITY_GOAL_EDIT,
CYCLE_PLAN::VARCHAR(1300) AS CYCLE_PLAN,
DETAIL_GROUP::VARCHAR(1300) AS DETAIL_GROUP,
TEAM_ACTIVITY_GOAL_EDIT::NUMBER(18,1) AS TEAM_ACTIVITY_GOAL_EDIT,
PRODUCT_LAST_ACTIVITY_DATE::DATE AS PRODUCT_LAST_ACTIVITY_DATE,
PRODUCT_LAST_ACTIVITY_DATETIME::TIMESTAMP_NTZ(9) AS PRODUCT_LAST_ACTIVITY_DATETIME,
TEAM_PRODUCT_LAST_ACTIVITY_DATE::DATE AS TEAM_PRODUCT_LAST_ACTIVITY_DATE,
TEAM_PRODUCT_LAST_ACTIVITY_DATETIME::TIMESTAMP_NTZ(9) AS TEAM_PRODUCT_LAST_ACTIVITY_DATETIME,
PRODUCT_LAST_ACTIVITY_DATE_1::DATE AS PRODUCT_LAST_ACTIVITY_DATE_1,
TEAM_PRODUCT_LAST_ACTIVITY_DATE_1::DATE AS TEAM_PRODUCT_LAST_ACTIVITY_DATE_1,
MASTER_ALIGN_ID::VARCHAR(20) AS MASTER_ALIGN_ID,
COUNTRY_CODE::VARCHAR(2) AS COUNTRY_CODE,
LEGACY_ID::VARCHAR(255) AS LEGACY_ID,
JJ_PRODUCT_ID18::VARCHAR(1300) AS JJ_PRODUCT_ID18,
CLASSIFICATION::VARCHAR(100) AS CLASSIFICATION,
ADOPTION_LEADER::VARCHAR(100) AS ADOPTION_LEADER,
	inserted_date::timestamp_ntz(9) as inserted_date,
	updated_date::timestamp_ntz(9) as updated_date
	from transformed
)

select * from final 
