sources:
  - name: jpnsdl_raw
    database: "{{ env_var('DBT_ENV_LOAD_DB') }}"
    schema: jpnsdl_raw
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: edi_invt_dt
        tags: ["","ingestion"]