--Import CTE
with v_edw_rpt_anz_re as (
    select * from {{ source('pcfedw_integration', 'v_edw_rpt_anz_re') }}
),
--Logical CTE

--Final CTE
edw_rpt_anz_re as (
SELECT FISC_YR,
       CAST(FISC_PER AS numeric(18,0) ) AS FISC_PER,		--// INTEGER
       CLUSTER,
       MARKET,
       CHANNEL_NAME,
       DISTRIBUTOR_CODE,
       DISTRIBUTOR_NAME,
       SELL_OUT_CHANNEL,
       STORE_TYPE,
       PRIORITIZATION_SEGMENTATION,
       STORE_CATEGORY,
       STORE_CODE,
       STORE_NAME,
       STORE_GRADE,
       STORE_SIZE,
       REGION,
       ZONE_NAME,
       CITY,
       RTRLATITUDE,
       RTRLONGITUDE,
       CUSTOMER_SEGMENT_KEY,
       CUSTOMER_SEGMENT_DESCRIPTION,
       RETAIL_ENVIRONMENT,
       SAP_CUSTOMER_CHANNEL_KEY,
       SAP_CUSTOMER_CHANNEL_DESCRIPTION,
       SAP_CUSTOMER_SUB_CHANNEL_KEY,
       SAP_SUB_CHANNEL_DESCRIPTION,
       SAP_PARENT_CUSTOMER_KEY,
       SAP_PARENT_CUSTOMER_DESCRIPTION,
       SAP_BANNER_KEY,
       SAP_BANNER_DESCRIPTION,
       SAP_BANNER_FORMAT_KEY,
       SAP_BANNER_FORMAT_DESCRIPTION,
       CUSTOMER_NAME,
       CUSTOMER_CODE,
       PRODUCT_CODE,
       PRODUCT_NAME,
       PROD_HIER_L1,
       PROD_HIER_L2,
       PROD_HIER_L3,
       PROD_HIER_L4,
       PROD_HIER_L5,
       PROD_HIER_L6,
       PROD_HIER_L7,
       PROD_HIER_L8,
       PROD_HIER_L9,
       MAPPED_SKU_CD,
       SAP_PROD_SGMT_CD,
       SAP_PROD_SGMT_DESC,
       SAP_BASE_PROD_DESC,
       SAP_MEGA_BRND_DESC,
       SAP_BRND_DESC,
       SAP_VRNT_DESC,
       SAP_PUT_UP_DESC,
       SAP_GRP_FRNCHSE_CD,
       SAP_GRP_FRNCHSE_DESC,
       SAP_FRNCHSE_CD,
       SAP_FRNCHSE_DESC,
       SAP_PROD_FRNCHSE_CD,
       SAP_PROD_FRNCHSE_DESC,
       SAP_PROD_MJR_CD,
       SAP_PROD_MJR_DESC,
       SAP_PROD_MNR_CD,
       SAP_PROD_MNR_DESC,
       SAP_PROD_HIER_CD,
       SAP_PROD_HIER_DESC,
       PKA_FRANCHISE_DESC,
       PKA_BRAND_DESC,
       PKA_SUB_BRAND_DESC,
       PKA_VARIANT_DESC,
       PKA_SUB_VARIANT_DESC,
       GLOBAL_PRODUCT_FRANCHISE,
       GLOBAL_PRODUCT_BRAND,
       GLOBAL_PRODUCT_SUB_BRAND,
       GLOBAL_PRODUCT_VARIANT,
       GLOBAL_PRODUCT_SEGMENT,
       GLOBAL_PRODUCT_SUBSEGMENT,
       GLOBAL_PRODUCT_CATEGORY,
       GLOBAL_PRODUCT_SUBCATEGORY,
       GLOBAL_PUT_UP_DESCRIPTION,
       EAN,
       SKU_CODE,
       SKU_DESCRIPTION,
       PKA_PRODUCT_KEY,
       PKA_PRODUCT_KEY_DESCRIPTION,
       SALES_VALUE,
       SALES_QTY,
       AVG_SALES_QTY,
       LM_SALES,
       LM_SALES_QTY,
       LM_AVG_SALES_QTY,
       P3M_SALES,
       P3M_QTY,
       P3M_AVG_QTY,
       P6M_SALES,
       P6M_QTY,
       P6M_AVG_QTY,
       P12M_SALES,
       P12M_QTY,
       P12M_AVG_QTY,
       F3M_SALES,
       F3M_QTY,
       F3M_AVG_QTY,
       LM_SALES_FLAG,
       P3M_SALES_FLAG,
       P6M_SALES_FLAG,
       P12M_SALES_FLAG,
       MDP_FLAG,
       TARGET_COMPLAINCE,
       LIST_PRICE,
       SIZE_OF_PRICE_LM,
       SIZE_OF_PRICE_P3M,
       SIZE_OF_PRICE_P6M,
       SIZE_OF_PRICE_P12M,
       LM_SALES_FLAG_COUNT,
       P3M_SALES_FLAG_COUNT,
       P6M_SALES_FLAG_COUNT,
       P12M_SALES_FLAG_COUNT,
       MDP_FLAG_COUNT,
       DATA_SRC,
       SALES_VALUE_LIST_PRICE,
       LM_SALES_LP,
       P3M_SALES_LP,
       P6M_SALES_LP,
       P12M_SALES_LP,
       SIZE_OF_PRICE_LM_LP,
       SIZE_OF_PRICE_P3M_LP,
       SIZE_OF_PRICE_P6M_LP,
       SIZE_OF_PRICE_P12M_LP,
       null as SOLDTO_CODE,
       SYSDATE() as crt_dttm		--// SYSDATE
FROM v_edw_rpt_anz_re
WHERE market in ('Australia','New Zealand') 
AND   FISC_PER >= (SELECT REPLACE(SUBSTRING(add_months (TO_DATE(MAX(fisc_per)::varchar,'YYYYMM'),-1),1,7),'-','')::INTEGER
                   FROM v_edw_rpt_anz_re)
AND   FISC_PER <= (SELECT MAX(fisc_per) FROM v_edw_rpt_anz_re)

),
final as(
    select
fisc_yr::VARCHAR(11) AS fisc_yr,
fisc_per::numeric(18,0) AS fisc_per,
cluster::VARCHAR(100) as cluster,
market::VARCHAR(20) AS market,
channel_name::VARCHAR(500) AS channel_name,
distributor_code::VARCHAR(500) AS distributor_code,
distributor_name::VARCHAR(500) AS distributor_name,
sell_out_channel::VARCHAR(255) AS sell_out_channel,
store_type::VARCHAR(500) AS store_type,
prioritization_segmentation::VARCHAR(100) AS prioritization_segmentation,
store_category::VARCHAR(203) AS store_category,
store_code::VARCHAR(500) AS store_code,
store_name::VARCHAR(500) AS store_name,
store_grade::VARCHAR(100) AS store_grade,
store_size::VARCHAR(100) AS store_size,
region::VARCHAR(255) AS region,
zone_name::VARCHAR(510) AS zone_name,
city::VARCHAR(255) AS city,
rtrlatitude::VARCHAR(100) AS rtrlatitude,
rtrlongitude::VARCHAR(100) AS rtrlongitude,
customer_segment_key::VARCHAR(12) AS customer_segment_key,
customer_segment_description::VARCHAR(200) AS customer_segment_description,
retail_environment::VARCHAR(500) AS retail_environment,
sap_customer_channel_key::VARCHAR(12) AS sap_customer_channel_key,
sap_customer_channel_description::VARCHAR(75) AS sap_customer_channel_description,
sap_customer_sub_channel_key::VARCHAR(12) AS sap_customer_sub_channel_key,
sap_sub_channel_description::VARCHAR(75) AS sap_sub_channel_description,
sap_parent_customer_key::VARCHAR(12) AS sap_parent_customer_key,
sap_parent_customer_description::VARCHAR(75) AS sap_parent_customer_description,
sap_banner_key::VARCHAR(12) AS sap_banner_key,
sap_banner_description::VARCHAR(75) AS sap_banner_description,
sap_banner_format_key::VARCHAR(12) AS sap_banner_format_key,
sap_banner_format_description::VARCHAR(75) AS sap_banner_format_description,
customer_name::VARCHAR(200) AS customer_name,
customer_code::VARCHAR(20) AS customer_code,
product_code::VARCHAR(500) AS product_code,
product_name::VARCHAR(500) AS product_name,
prod_hier_l1::VARCHAR(50) AS prod_hier_l1,
prod_hier_l2::VARCHAR(200) AS prod_hier_l2,
prod_hier_l3::VARCHAR(255) AS prod_hier_l3,
prod_hier_l4::VARCHAR(255) AS prod_hier_l4,
prod_hier_l5::VARCHAR(255) AS prod_hier_l5,
prod_hier_l6::VARCHAR(255) AS prod_hier_l6,
prod_hier_l7::VARCHAR(200) AS prod_hier_l7,
prod_hier_l8::VARCHAR(200) AS prod_hier_l8,
prod_hier_l9::VARCHAR(250) AS prod_hier_l9,
mapped_sku_cd::VARCHAR(50) AS mapped_sku_cd,
sap_prod_sgmt_cd::VARCHAR(18) AS sap_prod_sgmt_cd,
sap_prod_sgmt_desc::VARCHAR(100) AS sap_prod_sgmt_desc,
sap_base_prod_desc::VARCHAR(100) AS sap_base_prod_desc,
sap_mega_brnd_desc::VARCHAR(100) AS sap_mega_brnd_desc,
sap_brnd_desc::VARCHAR(100) AS sap_brnd_desc,
sap_vrnt_desc::VARCHAR(100) AS sap_vrnt_desc,
sap_put_up_desc::VARCHAR(100) AS sap_put_up_desc,
sap_grp_frnchse_cd::VARCHAR(18) AS sap_grp_frnchse_cd,
sap_grp_frnchse_desc::VARCHAR(100) AS sap_grp_frnchse_desc,
sap_frnchse_cd::VARCHAR(18) AS sap_frnchse_cd,
sap_frnchse_desc::VARCHAR(100) AS sap_frnchse_desc,
sap_prod_frnchse_cd::VARCHAR(18) AS sap_prod_frnchse_cd,
sap_prod_frnchse_desc::VARCHAR(100) AS sap_prod_frnchse_desc,
sap_prod_mjr_cd::VARCHAR(18) AS sap_prod_mjr_cd,
sap_prod_mjr_desc::VARCHAR(100) AS sap_prod_mjr_desc,
sap_prod_mnr_cd::VARCHAR(18) AS sap_prod_mnr_cd,
sap_prod_mnr_desc::VARCHAR(100) AS sap_prod_mnr_desc,
sap_prod_hier_cd::VARCHAR(18) AS sap_prod_hier_cd,
sap_prod_hier_desc::VARCHAR(100) AS sap_prod_hier_desc,
pka_franchise_desc::VARCHAR(30) AS pka_franchise_desc,
pka_brand_desc::VARCHAR(30) AS pka_brand_desc,
pka_sub_brand_desc::VARCHAR(30) AS pka_sub_brand_desc,
pka_variant_desc::VARCHAR(30) AS pka_variant_desc,
pka_sub_variant_desc::VARCHAR(30) AS pka_sub_variant_desc,
global_product_franchise::VARCHAR(30) AS global_product_franchise,
global_product_brand::VARCHAR(30) AS global_product_brand,
global_product_sub_brand::VARCHAR(100) AS global_product_sub_brand,
global_product_variant::VARCHAR(100) AS global_product_variant,
global_product_segment::VARCHAR(100) AS global_product_segment,
global_product_subsegment::VARCHAR(100) AS global_product_subsegment,
global_product_category::VARCHAR(100) AS global_product_category,
global_product_subcategory::VARCHAR(100) AS global_product_subcategory,
global_put_up_description::VARCHAR(100) AS global_put_up_description,
ean::VARCHAR(500) AS ean,
sku_code::VARCHAR(200) AS sku_code,
sku_description::VARCHAR(500) AS sku_description,
pka_product_key::VARCHAR(68) AS pka_product_key,
pka_product_key_description::VARCHAR(255) AS pka_product_key_description,
sales_value::NUMERIC(38,6) AS sales_value,
sales_qty::NUMERIC(38,6) AS sales_qty,
avg_sales_qty::NUMERIC(38,6) AS avg_sales_qty,
lm_sales::NUMERIC(38,6) AS lm_sales,
lm_sales_qty::NUMERIC(38,6) AS lm_sales_qty,
lm_avg_sales_qty::NUMERIC(38,6) AS lm_avg_sales_qty,
p3m_sales::NUMERIC(38,6) AS p3m_sales,
p3m_qty::NUMERIC(38,6) AS p3m_qty,
p3m_avg_qty::NUMERIC(38,6) AS p3m_avg_qty,
p6m_sales::NUMERIC(38,6) AS p6m_sales,
p6m_qty::NUMERIC(38,6) AS p6m_qty,
p6m_avg_qty::NUMERIC(38,6) AS p6m_avg_qty,
p12m_sales::NUMERIC(38,6) AS p12m_sales,
p12m_qty::NUMERIC(38,6) AS p12m_qty,
p12m_avg_qty::NUMERIC(38,6) AS p12m_avg_qty,
f3m_sales::NUMERIC(38,6) AS f3m_sales,
f3m_qty::NUMERIC(38,6) AS f3m_qty,
f3m_avg_qty::NUMERIC(38,6) AS f3m_avg_qty,
lm_sales_flag::VARCHAR(1) AS lm_sales_flag,
p3m_sales_flag::VARCHAR(1) AS p3m_sales_flag,
p6m_sales_flag::VARCHAR(1) AS p6m_sales_flag,
p12m_sales_flag::VARCHAR(1) AS p12m_sales_flag,
mdp_flag::VARCHAR(1) AS mdp_flag,
target_complaince::numeric(38,6) AS target_complaince,
list_price::NUMERIC(20,4) AS list_price,
size_of_price_lm::NUMERIC(38,14) AS size_of_price_lm,
size_of_price_p3m::NUMERIC(38,14) AS size_of_price_p3m,
size_of_price_p6m::NUMERIC(38,14) AS size_of_price_p6m,
size_of_price_p12m::NUMERIC(38,14) AS size_of_price_p12m,
lm_sales_flag_count::numeric(38,0) AS lm_sales_flag_count,
p3m_sales_flag_count::numeric(38,0) AS p3m_sales_flag_count,
p6m_sales_flag_count::numeric(38,0) AS p6m_sales_flag_count,
p12m_sales_flag_count::numeric(38,0) AS p12m_sales_flag_count,
mdp_flag_count::numeric(38,0) AS mdp_flag_count,
data_src::VARCHAR(14) AS data_src,
sales_value_list_price::NUMERIC(38,6) AS sales_value_list_price,
lm_sales_lp::NUMERIC(38,6) AS lm_sales_lp,
p3m_sales_lp::NUMERIC(38,6) AS p3m_sales_lp,
p6m_sales_lp::NUMERIC(38,6) AS p6m_sales_lp,
p12m_sales_lp::NUMERIC(38,6) AS p12m_sales_lp,
size_of_price_lm_lp::NUMERIC(38,14) AS size_of_price_lm_lp,
size_of_price_p3m_lp::NUMERIC(38,14) AS size_of_price_p3m_lp,
size_of_price_p6m_lp::NUMERIC(38,14) AS size_of_price_p6m_lp,
size_of_price_p12m_lp::NUMERIC(38,14) AS size_of_price_p12m_lp,
soldto_code::VARCHAR(20) AS soldto_code,
crt_dttm::TIMESTAMP WITHOUT TIME ZONE AS crt_dttm
from edw_rpt_anz_re
)
--Final select
select * from final 