with wks_pilot_sku_recom_tbl2 as 
(
    select * from {{ ref('indwks_integration__wks_pilot_sku_recom_tbl2') }}
),
wks_pilot_ly_actual_sales as
(
    select * from {{ ref('indwks_integration__wks_pilot_ly_actual_sales') }}
),
final as 
(
    SELECT mth_mm,
       qtr,
       fisc_yr,
       month,
       cust_cd,
       customer_name,
       rtruniquecode,
       retailer_cd,
       mother_sku_cd,
       trunc(oos_flag) as oos_flag,
       trunc(ms_flag) as ms_flag,
       trunc(cs_flag) as cs_flag,
       soq,
       region_name,
       zone_name,
       territory_name,
       class_desc,
       class_desc_a_sa_flag,
       channel_name,
       business_channel,
       status_desc,
       actv_flg,
       retailer_name,
       retailer_category_name,
       csrtrcode,
       nup_target,
       nup_actual_ly,
       nup_actual_cy,
       achievement_nr,
       hit_ms_flag,
       hit_cs_flag,
       franchise_name,
       brand_name,
       product_category_name,
       variant_name,
       mothersku_name,
       salesman_code,
       salesman_name,
       unique_sales_code,
       route_code,
       route_name,
       reco_flag,
       sales_flag,
       convert_timezone('UTC',current_timestamp()) as crt_dttm,
       convert_timezone('UTC',current_timestamp()) as updt_dttm
    FROM wks_pilot_sku_recom_tbl2
)
select mth_mm::number(18,0) as mth_mm,
qtr::number(18,0) as qtr,
fisc_yr::number(18,0) as fisc_yr,
month::varchar(3) as month,
cust_cd::varchar(50) as cust_cd,
customer_name::varchar(150) as customer_name,
rtruniquecode::varchar(100) as rtruniquecode,
retailer_cd::varchar(100) as retailer_cd,
mother_sku_cd::varchar(50) as mother_sku_cd,
oos_flag::number(38,0) as oos_flag,
ms_flag::number(38,0) as ms_flag,
cs_flag::number(38,0) as cs_flag,
soq::number(38,0) as soq,
region_name::varchar(50) as region_name,
zone_name::varchar(50) as zone_name,
territory_name::varchar(50) as territory_name,
class_desc::varchar(50) as class_desc,
class_desc_a_sa_flag::number(18,0) as class_desc_a_sa_flag,
channel_name::varchar(150) as channel_name,
business_channel::varchar(50) as business_channel,
status_desc::varchar(10) as status_desc,
actv_flg::varchar(1) as actv_flg,
retailer_name::varchar(150) as retailer_name,
retailer_category_name::varchar(50) as retailer_category_name,
csrtrcode::varchar(50) as csrtrcode,
nup_target::number(18,0) as nup_target,
nup_actual_ly::number(38,0) as nup_actual_ly,
nup_actual_cy::number(38,0) as nup_actual_cy,
achievement_nr::number(38,6) as achievement_nr,
hit_ms_flag::number(18,0) as hit_ms_flag,
hit_cs_flag::number(18,0) as hit_cs_flag,
franchise_name::varchar(50) as franchise_name,
brand_name::varchar(50) as brand_name,
product_category_name::varchar(150) as product_category_name,
variant_name::varchar(150) as variant_name,
mothersku_name::varchar(150) as mothersku_name,
salesman_code::varchar(50) as salesman_code,
salesman_name::varchar(50) as salesman_name,
unique_sales_code::varchar(50) as unique_sales_code,
route_code::varchar(100) as route_code,
route_name::varchar(50) as route_name,
reco_flag::varchar(50) as reco_flag,
sales_flag::varchar(50) as sales_flag,
crt_dttm::timestamp_ntz(9) as crt_dttm,
updt_dttm::timestamp_ntz(9) as updt_dttm
from final