with edw_vw_th_inventory_analysis as (
   select * from  {{ ref('thaedw_integration__edw_vw_th_inventory_analysis') }}
),

final as (
select
    data_type::varchar(9) as data_type,
    order_date::varchar(52) as order_date,
    year::number(18,0) as year,
    year_quarter::varchar(14) as year_quarter,
    month_year::varchar(23) as month_year,
    month_number::number(18,0) as month_number,
    year_week_number::varchar(21) as year_week_number,
    month_week_number::varchar(21) as month_week_number,
    country_code::varchar(2) as country_code,
    country_name::varchar(11) as country_name,
    distributor_id::varchar(20) as distributor_id,
    whcode::varchar(50) as whcode,
    whgroup::varchar(12) as whgroup,
    sku_code::varchar(50) as sku_code,
    sku_description::varchar(100) as sku_description,
    franchise::varchar(30) as franchise,
    brand::varchar(30) as brand,
    variant::varchar(100) as variant,
    segment::varchar(50) as segment,
    put_up_description::varchar(100) as put_up_description,
    prod_sub_brand::varchar(100) as prod_sub_brand,
    prod_subsegment::varchar(100) as prod_subsegment,
    prod_category::varchar(50) as prod_category,
    prod_subcategory::varchar(50) as prod_subcategory,
    sap_cust_id::varchar(10) as sap_cust_id,
    sap_cust_nm::varchar(100) as sap_cust_nm,
    sap_sls_org::varchar(4) as sap_sls_org,
    sap_cmp_id::varchar(6) as sap_cmp_id,
    sap_cntry_cd::varchar(3) as sap_cntry_cd,
    sap_cntry_nm::varchar(40) as sap_cntry_nm,
    sap_addr::varchar(150) as sap_addr,
    sap_region::varchar(150) as sap_region,
    sap_state_cd::varchar(150) as sap_state_cd,
    sap_city::varchar(150) as sap_city,
    sap_post_cd::varchar(150) as sap_post_cd,
    sap_chnl_cd::varchar(2) as sap_chnl_cd,
    sap_chnl_desc::varchar(20) as sap_chnl_desc,
    sap_sls_office_cd::varchar(4) as sap_sls_office_cd,
    sap_sls_office_desc::varchar(40) as sap_sls_office_desc,
    sap_sls_grp_cd::varchar(3) as sap_sls_grp_cd,
    sap_sls_grp_desc::varchar(40) as sap_sls_grp_desc,
    sap_prnt_cust_key::varchar(12) as sap_prnt_cust_key,
    sap_prnt_cust_desc::varchar(50) as sap_prnt_cust_desc,
    sap_cust_chnl_key::varchar(12) as sap_cust_chnl_key,
    sap_cust_chnl_desc::varchar(50) as sap_cust_chnl_desc,
    sap_cust_sub_chnl_key::varchar(12) as sap_cust_sub_chnl_key,
    sap_sub_chnl_desc::varchar(50) as sap_sub_chnl_desc,
    sap_go_to_mdl_key::varchar(12) as sap_go_to_mdl_key,
    sap_go_to_mdl_desc::varchar(50) as sap_go_to_mdl_desc,
    sap_bnr_key::varchar(12) as sap_bnr_key,
    sap_bnr_desc::varchar(50) as sap_bnr_desc,
    sap_bnr_frmt_key::varchar(12) as sap_bnr_frmt_key,
    sap_bnr_frmt_desc::varchar(50) as sap_bnr_frmt_desc,
    retail_env::varchar(50) as retail_env,
    sales_quantity::number(38,6) as sales_quantity,
    return_quantity::number(38,6) as return_quantity,
    gross_trade_sales::float as gross_trade_sales,
    inventory_quantity::float as inventory_quantity,
    amount_before_discount::float as amount_before_discount,
    inventory::float as inventory,
    si_gross_trade_sales_value::number(38,5) as si_gross_trade_sales_value,
    si_tp_value::number(38,5) as si_tp_value,
    si_net_trade_sales_value::number(38,5) as si_net_trade_sales_value
from edw_vw_th_inventory_analysis
)

select * from final