with itg_hcp360_veeva_medical_event as
(
    select * from {{ source('hcpitg_integration', 'itg_hcp360_veeva_medical_event') }}
),
final as
(
    select
    medical_event_key,
    NVL(medical_event_source_id,'Not Applicable') as medical_event_source_id,
    ownerid as owner_id,
    isdeleted as is_deleted,
    name,
    recordtypeid as record_type_id,
    createddate as created_date,
    createdbyid as created_by_id,
    last_modified_date,
    lastmodifiedbyid as last_modified_by_id,
    islocked as is_locked,
    primary_product,
    description,
    start_date,
    location,
    end_date,
    secondary_product,
    website,
    active,
    event_type,
    jj_core_estimated_total_cost as core_estimated_total_cost,
    jj_core_speaker as core_speaker_source_id,
    mobile_id,
    jj_core_status as core_status,
    country_code,
    jj_simp_hcc_business as business,
    jj_simp_hcc_isapproved as isapproved,
    jj_simp_hcc_modifiedby as modifiedby,
    jj_simp_hcc_modifiedon as modifiedon,
    jj_simp_hcc_process_reference as process_reference,
    jj_simp_hcc_process_stage as process_stage,
    jj_simp_hcc_process_url as process_url,
    jj_simp_hcc_process as process_source_id,
    end_time,
    null as start_time,
    jj_advisory as advisory,
    jj_approval_status as approval_status,
    jj_participant as participant,
    jj_moderator as moderator,
    jj_primary_product as primary_product_source_id,
    jj_secondary_product as secondary_product_source_id,
    jj_speaker as speaker_source_id,
    jj_tw_back_to_draft as tw_back_to_draft,
    jj_tw_event_contributor as tw_event_contributor,
    jj_tw_event_initiated_by as tw_event_initiated_by,
    jj_tw_current_user_can_delete as tw_current_user_can_delete,
    convert_timezone('UTC',current_timestamp())::timestamp_ntz as crt_dttm,
    convert_timezone('UTC',current_timestamp())::timestamp_ntz as updt_dttm
    from itg_hcp360_veeva_medical_event

    UNION ALL

    SELECT 'Not Applicable','Not Applicable','Not Applicable',0,'Not Applicable','Not Applicable',
    convert_timezone('UTC',current_timestamp())::timestamp_ntz,'Not Applicable',convert_timezone('UTC',current_timestamp())::timestamp_ntz,'Not Applicable',0,'Not Applicable','Not Applicable',convert_timezone('UTC',current_timestamp())::timestamp_ntz,
    'Not Applicable',convert_timezone('UTC',current_timestamp())::timestamp_ntz,'Not Applicable','Not Applicable',0,'Not Applicable',0,
    'Not Applicable','Not Applicable','Not Applicable','zz','Not Applicable',0,'Not Applicable',
    convert_timezone('UTC',current_timestamp())::timestamp_ntz,'Not Applicable','Not Applicable','Not Applicable','Not Applicable',convert_timezone('UTC',current_timestamp())::timestamp_ntz,
    convert_timezone('UTC',current_timestamp())::timestamp_ntz,'Not Applicable','Not Applicable','Not Applicable','Not Applicable','Not Applicable',
    'Not Applicable','Not Applicable',0,'Not Applicable','Not Applicable',    0,convert_timezone('UTC',current_timestamp())::timestamp_ntz,convert_timezone('UTC',current_timestamp())::timestamp_ntz

)
select medical_event_key::varchar(32) as medical_event_key,
    medical_event_source_id::varchar(18) as medical_event_source_id,
    owner_id::varchar(18) as owner_id,
    is_deleted::varchar(25) as is_deleted,
    name::varchar(80) as name,
    record_type_id::varchar(18) as record_type_id,
    created_date::timestamp_ntz(9) as created_date,
    created_by_id::varchar(18) as created_by_id,
    last_modified_date::timestamp_ntz(9) as last_modified_date,
    last_modified_by_id::varchar(18) as last_modified_by_id,
    is_locked::varchar(25) as is_locked,
    primary_product::varchar(256) as primary_product,
    description::varchar(32000) as description,
    start_date::date as start_date,
    location::varchar(40) as location,
    end_date::date as end_date,
    secondary_product::varchar(256) as secondary_product,
    website::varchar(255) as website,
    active::varchar(25) as active,
    event_type::varchar(256) as event_type,
    core_estimated_total_cost::number(18,2) as core_estimated_total_cost,
    core_speaker_source_id::varchar(18) as core_speaker_source_id,
    mobile_id::varchar(100) as mobile_id,
    core_status::varchar(256) as core_status,
    country_code::varchar(2) as country_code,
    business::varchar(500) as business,
    isapproved::varchar(25) as isapproved,
    modifiedby::varchar(1300) as modifiedby,
    modifiedon::timestamp_ntz(9) as modifiedon,
    process_reference::varchar(1300) as process_reference,
    process_stage::varchar(1300) as process_stage,
    process_url::varchar(1300) as process_url,
    process_source_id::varchar(18) as process_source_id,
    end_time::timestamp_ntz(9) as end_time,
    start_time::timestamp_ntz(9) as start_time,
    advisory::varchar(256) as advisory,
    approval_status::varchar(256) as approval_status,
    participant::varchar(256) as participant,
    moderator::varchar(256) as moderator,
    primary_product_source_id::varchar(18) as primary_product_source_id,
    secondary_product_source_id::varchar(18) as secondary_product_source_id,
    speaker_source_id::varchar(4099) as speaker_source_id,
    tw_back_to_draft::varchar(25) as tw_back_to_draft,
    tw_event_contributor::varchar(18) as tw_event_contributor,
    tw_event_initiated_by::varchar(256) as tw_event_initiated_by,
    tw_current_user_can_delete::varchar(25) as tw_current_user_can_delete,
    crt_dttm::timestamp_ntz(9) as crt_dttm,
    updt_dttm::timestamp_ntz(9) as updt_dttm
 from final