with
edw_hcp360_kpi_rpt_tbl1 as 
(
    select 
        country,
        source_system,
        channel,
        activity_type,
        hcp_master_id,
        employee_id,
        brand,
        brand_category,
        speciality,
        core_noncore,
        classification,
        territory,
        zone,
        hcp_created_date,
        activity_date,
        call_source_id,
        product_indication_name,
        no_of_prescription_units,
        first_prescription_date,
        planned_call_cnt,
        call_duration,
        prescription_id,
        noofprescritions,
        noofprescribers,
        email_name,
        is_unique,
        email_delivered_flag,
        crt_dttm,
        updt_dttm,
        null as target_value,
        null as target_kpi,
        null as report_brand_reference,
        diagnosis,
        region_hq,
        email_activity_type,
        hcp_id,
        transaction_flag,
        null as iqvia_brand,
        null as iqvia_pack_description,
        null as iqvia_product_description,
        null as iqvia_pack_volume,
        null as iqvia_input_brand,
        null as mat_noofprescritions,
        null as mat_noofprescribers,
        field_rep_active,
        null as mat_totalprescritions_by_brand,
        null as mat_totalprescribers_by_brand,
        null as mat_totalprescritions_jnj_brand,
        null as totalprescritions_by_brand,
        null as totalprescribers_by_brand,
        null as totalprescritions_jnj_brand,
        call_type,
        null as email_subject,
        null as totalprescritions_by_speciality,
        null as totalprescribers_by_speciality,
        null as totalprescritions_jnj_speciality,
        null as totalprescritions_by_indication,
        null as totalprescribers_by_indication,
        null as totalprescritions_jnj_indication,
        null as year_month,
        null as devicecategory,
        null as channelgrouping,
        null as visitor_country,
        null as new_visitors,
        null as repeat_visitors,
        null as all_visitor,
        null as unique_pageviews,
        null as total_downloads,
        null as pages,
        null as page_sessions,
        null as total_page_views,
        null as total_bounces,
        null as total_session_duration,
        null as sessions,
        territory_id,
        region,
        null as sales_unit,
        null as sales_value,
        null as totalsales_unit_by_brand,
        null as totalsales_value_by_brand,
        null as totalsales_unit_by_jnj_brand,
        null as totalsales_value_by_jnj_brand,
        null as medical_event_id,
        null as event_name,
        null as event_type,
        null as event_role,
        null as attendee_status,
        null as event_location,
        null as survey_question,
        null as survey_response,
        null as attendee_name,
        null as key_message,
        null as sales_channel,
        null as sales_area,
        null as sales_rep_count,
        null as survey_name,
        sample_id,
        null as customer_code,
        null as customer_name,
        null as retailer_code,
        null as retailer_name,
        null as retailer_category_cd,
        null as retailer_category_name,
        null as num_buying_retailer,
        is_active,
        null as event_status,
        category,
        null as udc_avbabybodydocq42019,
        null as udc_babyprofesionalcac2019,
        null as variant_name
    from {{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl1') }}
),
edw_hcp360_kpi_rpt_tbl2 as 
(
    select 
        country,
        source_system,
        channel,
        activity_type,
        hcp_master_id,
        employee_id,
        brand,
        brand_category,
        speciality,
        core_noncore,
        classification,
        territory,
        zone,
        hcp_created_date,
        activity_date,
        call_source_id,
        product_indication_name,
        no_of_prescription_units,
        first_prescription_date,
        planned_call_cnt,
        call_duration,
        prescription_id,
        noofprescritions,
        noofprescribers,
        email_name,
        is_unique,
        email_delivered_flag,
        crt_dttm,
        updt_dttm,
        null as target_value,
        null as target_kpi,
        null as report_brand_reference,
        diagnosis,
        region_hq,
        email_activity_type,
        hcp_id,
        transaction_flag,
        null as iqvia_brand,
        null as iqvia_pack_description,
        null as iqvia_product_description,
        null as iqvia_pack_volume,
        null as iqvia_input_brand,
        null as mat_noofprescritions,
        null as mat_noofprescribers,
        null as field_rep_active,
        null as mat_totalprescritions_by_brand,
        null as mat_totalprescribers_by_brand,
        null as mat_totalprescritions_jnj_brand,
        null as totalprescritions_by_brand,
        null as totalprescribers_by_brand,
        null as totalprescritions_jnj_brand,
        null as call_type,
        null as email_subject,
        null as totalprescritions_by_speciality,
        null as totalprescribers_by_speciality,
        null as totalprescritions_jnj_speciality,
        null as totalprescritions_by_indication,
        null as totalprescribers_by_indication,
        null as totalprescritions_jnj_indication,
        null as year_month,
        null as devicecategory,
        null as channelgrouping,
        null as visitor_country,
        null as new_visitors,
        null as repeat_visitors,
        null as all_visitor,
        null as unique_pageviews,
        null as total_downloads,
        null as pages,
        null as page_sessions,
        null as total_page_views,
        null as total_bounces,
        null as total_session_duration,
        null as sessions,
        null as territory_id,
        region,
        null as sales_unit,
        null as sales_value,
        null as totalsales_unit_by_brand,
        null as totalsales_value_by_brand,
        null as totalsales_unit_by_jnj_brand,
        null as totalsales_value_by_jnj_brand,
        null as medical_event_id,
        null as event_name,
        null as event_type,
        null as event_role,
        null as attendee_status,
        null as event_location,
        null as survey_question,
        null as survey_response,
        null as attendee_name,
        key_message,
        null as sales_channel,
        null as sales_area,
        null as sales_rep_count,
        null as survey_name,
        null as sample_id,
        null as customer_code,
        null as customer_name,
        null as retailer_code,
        null as retailer_name,
        null as retailer_category_cd,
        null as retailer_category_name,
        null as num_buying_retailer,
        null as is_active,
        null as event_status,
        null as category,
        null as udc_avbabybodydocq42019,
        null as udc_babyprofesionalcac2019,
        null as variant_name
from {{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl2') }}
),
edw_hcp360_kpi_rpt_tbl3 as 
(
    select 
        country,
        source_system,
        channel,
        activity_type,
        hcp_master_key as hcp_master_id,
        employee_id,
        brand,
        brand_category,
        speciality,
        core_noncore,
        classification,
        territory,
        zone,
        hcp_created_date,
        activity_date,
        call_source_id,
        product_indication_name,
        null as no_of_prescription_units,
        null as first_prescription_date,
        null as planned_call_cnt,
        null as call_duration,
        null as prescription_id,
        null as noofprescritions,
        null as noofprescribers,
        null as email_name,
        null as is_unique,
        null as email_delivered_flag,
        crt_dttm,
        updt_dttm,
        null as target_value,
        null as target_kpi,
        null as report_brand_reference,
        null as diagnosis,
        region_hq,
        null as email_activity_type,
        hcp_id,
        transaction_flag,
        null as iqvia_brand,
        null as iqvia_pack_description,
        null as iqvia_product_description,
        null as iqvia_pack_volume,
        null as iqvia_input_brand,
        null as mat_noofprescritions,
        null as mat_noofprescribers,
        null as field_rep_active,
        null as mat_totalprescritions_by_brand,
        null as mat_totalprescribers_by_brand,
        null as mat_totalprescritions_jnj_brand,
        null as totalprescritions_by_brand,
        null as totalprescribers_by_brand,
        null as totalprescritions_jnj_brand,
        null as call_type,
        null as email_subject,
        null as totalprescritions_by_speciality,
        null as totalprescribers_by_speciality,
        null as totalprescritions_jnj_speciality,
        null as totalprescritions_by_indication,
        null as totalprescribers_by_indication,
        null as totalprescritions_jnj_indication,
        null as year_month,
        null as devicecategory,
        null as channelgrouping,
        null as visitor_country,
        null as new_visitors,
        null as repeat_visitors,
        null as all_visitor,
        null as unique_pageviews,
        null as total_downloads,
        null as pages,
        null as page_sessions,
        null as total_page_views,
        null as total_bounces,
        null as total_session_duration,
        null as sessions,
        null as territory_id,
        region,
        null as sales_unit,
        null as sales_value,
        null as totalsales_unit_by_brand,
        null as totalsales_value_by_brand,
        null as totalsales_unit_by_jnj_brand,
        null as totalsales_value_by_jnj_brand,
        medical_event_id,
        event_name,
        event_type,
        event_role,
        attendee_status,
        event_location,
        survey_question,
        survey_response,
        attendee_name,
        null as key_message,
        null as sales_channel,
        null as sales_area,
        null as sales_rep_count,
        survey_name,
        null as sample_id,
        null as customer_code,
        null as customer_name,
        null as retailer_code,
        null as retailer_name,
        null as retailer_category_cd,
        null as retailer_category_name,
        null as num_buying_retailer,
        null as is_active,
        event_status,
        null as category,
        null as udc_avbabybodydocq42019,
        null as udc_babyprofesionalcac2019,
        null as variant_name
from 
{{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl3') }}

),
edw_hcp360_kpi_rpt_tbl4 as 
(
    select 
        country,
        source_system,
        channel,
        activity_type,
        hcp_master_id,
        employee_id,
        brand,
        brand_category,
        speciality,
        core_noncore,
        classification,
        territory,
        zone,
        hcp_created_date,
        activity_date,
        call_source_id,
        product_indication_name,
        no_of_prescription_units,
        first_prescription_date,
        planned_call_cnt,
        call_duration,
        prescription_id,
        noofprescritions,
        noofprescribers,
        email_name,
        is_unique,
        email_delivered_flag,
        crt_dttm,
        updt_dttm,
        null as target_value,
        null as target_kpi,
        null as report_brand_reference,
        diagnosis,
        region_hq,
        email_activity_type,
        hcp_id,
        null as transaction_flag,
        null as iqvia_brand,
        null as iqvia_pack_description,
        null as iqvia_product_description,
        null as iqvia_pack_volume,
        null as iqvia_input_brand,
        null as mat_noofprescritions,
        null as mat_noofprescribers,
        null as field_rep_active,
        null as mat_totalprescritions_by_brand,
        null as mat_totalprescribers_by_brand,
        null as mat_totalprescritions_jnj_brand,
        null as totalprescritions_by_brand,
        null as totalprescribers_by_brand,
        null as totalprescritions_jnj_brand,
        null as call_type,
        email_subject,
        null as totalprescritions_by_speciality,
        null as totalprescribers_by_speciality,
        null as totalprescritions_jnj_speciality,
        null as totalprescritions_by_indication,
        null as totalprescribers_by_indication,
        null as totalprescritions_jnj_indication,
        null as year_month,
        null as devicecategory,
        null as channelgrouping,
        null as visitor_country,
        null as new_visitors,
        null as repeat_visitors,
        null as all_visitor,
        null as unique_pageviews,
        null as total_downloads,
        null as pages,
        null as page_sessions,
        null as total_page_views,
        null as total_bounces,
        null as total_session_duration,
        null as sessions,
        null as territory_id,
        region,
        null as sales_unit,
        null as sales_value,
        null as totalsales_unit_by_brand,
        null as totalsales_value_by_brand,
        null as totalsales_unit_by_jnj_brand,
        null as totalsales_value_by_jnj_brand,
        null as medical_event_id,
        null as event_name,
        null as event_type,
        null as event_role,
        null as attendee_status,
        null as event_location,
        null as survey_question,
        null as survey_response,
        null as attendee_name,
        null as key_message,
        null as sales_channel,
        null as sales_area,
        null as sales_rep_count,
        null as survey_name,
        null as sample_id,
        null as customer_code,
        null as customer_name,
        null as retailer_code,
        null as retailer_name,
        null as retailer_category_cd,
        null as retailer_category_name,
        null as num_buying_retailer,
        null as is_active,
        null as event_status,
        null as category,
        null as udc_avbabybodydocq42019,
        null as udc_babyprofesionalcac2019,
        null as variant_name
from {{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl4') }}
),
edw_hcp360_kpi_rpt_tbl4_target as 
(
    select
    
        country,
        source_system,
        channel,
        activity_type    ,
        null as hcp_master_id,
        null as employee_id,
        null as brand,
        null as brand_category,
        null as speciality,
        null as core_noncore,
        null as classification,
        null as territory,
        null as zone,
        null as hcp_created_date,
        activity_date,
        null as call_source_id,
        null as product_indication_name,
        null as no_of_prescription_units,
        null as first_prescription_date,
        null as planned_call_cnt,
        null as call_duration,
        null as prescription_id,
        null as noofprescritions,
        null as noofprescribers,
        null as email_name,
        null as is_unique,
        null as email_delivered_flag,
        null as crt_dttm,
        null as updt_dttm,
        target_value,
        target_kpi,
        null as report_brand_reference,
        null as diagnosis,
        null as region_hq,
        null as email_activity_type,
        null as hcp_id,
        null as transaction_flag,
        null as iqvia_brand,
        null as iqvia_pack_description,
        null as iqvia_product_description,
        null as iqvia_pack_volume,
        null as iqvia_input_brand,
        null as mat_noofprescritions,
        null as mat_noofprescribers,
        null as field_rep_active,
        null as mat_totalprescritions_by_brand,
        null as mat_totalprescribers_by_brand,
        null as mat_totalprescritions_jnj_brand,
        null as totalprescritions_by_brand,
        null as totalprescribers_by_brand,
        null as totalprescritions_jnj_brand,
        null as call_type,
        null as email_subject,
        null as totalprescritions_by_speciality,
        null as totalprescribers_by_speciality,
        null as totalprescritions_jnj_speciality,
        null as totalprescritions_by_indication,
        null as totalprescribers_by_indication,
        null as totalprescritions_jnj_indication,
        null as year_month,
        null as devicecategory,
        null as channelgrouping,
        null as visitor_country,
        null as new_visitors,
        null as repeat_visitors,
        null as all_visitor,
        null as unique_pageviews,
        null as total_downloads,
        null as pages,
        null as page_sessions,
        null as total_page_views,
        null as total_bounces,
        null as total_session_duration,
        null as sessions,
        null as territory_id,
        null as region,
        null as sales_unit,
        null as sales_value,
        null as totalsales_unit_by_brand,
        null as totalsales_value_by_brand,
        null as totalsales_unit_by_jnj_brand,
        null as totalsales_value_by_jnj_brand,
        null as medical_event_id,
        null as event_name,
        null as event_type,
        null as event_role,
        null as attendee_status,
        null as event_location,
        null as survey_question,
        null as survey_response,
        null as attendee_name,
        null as key_message,
        null as sales_channel,
        null as sales_area,
        null as sales_rep_count,
        null as survey_name,
        null as sample_id,
        null as customer_code,
        null as customer_name,
        null as retailer_code,
        null as retailer_name,
        null as retailer_category_cd,
        null as retailer_category_name,
        null as num_buying_retailer,
        null as is_active,
        null as event_status,
        null as category,
        null as udc_avbabybodydocq42019,
        null as udc_babyprofesionalcac2019,
        null as variant_name
    from {{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl4_target') }}
),
edw_hcp360_kpi_rpt_tbl5 as 
(
    select 
    country,
    source_system,
    channel,
    activity_type,
    hcp_master_id,
    employee_id,
    brand,
    brand_category,
    speciality,
    core_noncore,
    classification,
    territory,
    zone,
    hcp_created_date,
    activity_date,
    call_source_id,
    product_indication_name,
    no_of_prescription_units,
    first_prescription_date,
    planned_call_cnt,
    call_duration,
    prescription_id,
    noofprescritions,
    noofprescribers,
    email_name,
    is_unique,
    email_delivered_flag,
    crt_dttm::timestamp_ntz,
    updt_dttm::timestamp_ntz,
    null as target_value,
    null as target_kpi,
    report_brand_reference,
    diagnosis,
    null as region_hq,
    email_activity_type,
    hcp_id,
    null as transaction_flag,
    iqvia_brand,
    iqvia_pack_description,
    iqvia_product_description,
    iqvia_pack_volume,
    iqvia_input_brand,
    mat_noofprescritions,
    mat_noofprescribers,
    null as field_rep_active,
    mat_totalprescritions_by_brand,
    mat_totalprescribers_by_brand,
    mat_totalprescritions_jnj_brand,
    totalprescritions_by_brand,
    totalprescribers_by_brand,
    totalprescritions_jnj_brand,
    call_type,
    email_subject,
    totalprescritions_by_speciality,
    totalprescribers_by_speciality,
    totalprescritions_jnj_speciality,
    totalprescritions_by_indication,
    totalprescribers_by_indication,
    totalprescritions_jnj_indication,
    null as year_month,
    null as devicecategory,
    null as channelgrouping,
    null as visitor_country,
    null as new_visitors,
    null as repeat_visitors,
    null as all_visitor,
    null as unique_pageviews,
    null as total_downloads,
    null as pages,
    null as page_sessions,
    null as total_page_views,
    null as total_bounces,
    null as total_session_duration,
    null as sessions,
    null as territory_id,
    region,
    sales_unit,
    sales_value,
    totalsales_unit_by_brand,
    totalsales_value_by_brand,
    totalsales_unit_by_jnj_brand,
    totalsales_value_by_jnj_brand,
    null as medical_event_id,
    null as event_name,
    null as event_type,
    null as event_role,
    null as attendee_status,
    null as event_location,
    null as survey_question,
    null as survey_response,
    null as attendee_name,
    null as key_message,
    null as sales_channel,
    null as sales_area,
    null as sales_rep_count,
    null as survey_name,
    null as sample_id,
    null as customer_code,
    null as customer_name,
    null as retailer_code,
    null as retailer_name,
    null as retailer_category_cd,
    null as retailer_category_name,
    null as num_buying_retailer,
    null as is_active,
    null as event_status,
    null as category,
    null as udc_avbabybodydocq42019,
    null as udc_babyprofesionalcac2019,
    null as variant_name
from {{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl5') }}
),
edw_hcp360_kpi_rpt_tbl6 as 
(
    select
        country,
        source_system,
        channel,
        activity_type,
        hcp_master_id,
        employee_id,
        brand,
        brand_category,
        speciality,
        core_noncore,
        classification,
        territory,
        zone,
        hcp_created_date,
        activity_date,
        call_source_id,
        product_indication_name,
        no_of_prescription_units,
        first_prescription_date,
        planned_call_cnt,
        call_duration,
        prescription_id,
        noofprescritions,
        noofprescribers,
        email_name,
        is_unique,
        email_delivered_flag,
        crt_dttm,
        updt_dttm,
        target_value,
        target_kpi,
        report_brand_reference,
        diagnosis,
        region_hq,
        email_activity_type,
        hcp_id,
        transaction_flag,
        iqvia_brand,
        iqvia_pack_description,
        iqvia_product_description,
        iqvia_pack_volume,
        iqvia_input_brand,
        mat_noofprescritions,
        mat_noofprescribers,
        field_rep_active,
        mat_totalprescritions_by_brand,
        mat_totalprescribers_by_brand,
        mat_totalprescritions_jnj_brand,
        totalprescritions_by_brand,
        totalprescribers_by_brand,
        totalprescritions_jnj_brand,
        call_type,
        email_subject,
        totalprescritions_by_speciality,
        totalprescribers_by_speciality,
        totalprescritions_jnj_speciality,
        totalprescritions_by_indication,
        totalprescribers_by_indication,
        totalprescritions_jnj_indication,
        year_month,
        devicecategory,
        channelgrouping,
        visitor_country,
        new_visitors,
        repeat_visitors,
        all_visitor,
        unique_pageviews,
        total_downloads,
        pages,
        page_sessions,
        total_page_views ,
        total_bounces,
        total_session_duration,
        sessions,
        null as territory_id,
        region,
        null as sales_unit,
        null as sales_value,
        null as totalsales_unit_by_brand,
        null as totalsales_value_by_brand,
        null as totalsales_unit_by_jnj_brand,
        null as totalsales_value_by_jnj_brand,
        null as medical_event_id,
        null as event_name,
        null as event_type,
        null as event_role,
        null as attendee_status,
        null as event_location,
        null as survey_question,
        null as survey_response,
        null as attendee_name,
        null as key_message,
        null as sales_channel,
        null as sales_area,
        null as sales_rep_count,
        null as survey_name,
        null as sample_id,
        null as customer_code,
        null as customer_name,
        null as retailer_code,
        null as retailer_name,
        null as retailer_category_cd,
        null as retailer_category_name,
        null as num_buying_retailer,
        null as is_active,
        null as event_status,
        null as category,
        null as udc_avbabybodydocq42019,
        null as udc_babyprofesionalcac2019,
        null as variant_name
from {{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl6') }}
),
edw_hcp360_kpi_rpt_tbl7 as 
(
    select 
        country,
        source_system,
        channel,
        activity_type,
        hcp_master_id,
        employee_id,
        brand,
        brand_category,
        speciality,
        core_noncore,
        classification,
        territory,
        zone,
        hcp_created_date,
        activity_date,
        call_source_id,
        product_indication_name,
        no_of_prescription_units,
        first_prescription_date,
        planned_call_cnt,
        call_duration,
        prescription_id,
        noofprescritions,
        noofprescribers,
        email_name,
        is_unique,
        email_delivered_flag,
        crt_dttm,
        updt_dttm,
        target_value,
        target_kpi,
        report_brand_reference,
        diagnosis,
        region_hq,
        email_activity_type,
        hcp_id,
        transaction_flag,
        iqvia_brand,
        iqvia_pack_description,
        iqvia_product_description,
        iqvia_pack_volume,
        iqvia_input_brand,
        mat_noofprescritions,
        mat_noofprescribers,
        field_rep_active,
        mat_totalprescritions_by_brand,
        mat_totalprescribers_by_brand,
        mat_totalprescritions_jnj_brand,
        totalprescritions_by_brand,
        totalprescribers_by_brand,
        totalprescritions_jnj_brand,
        call_type,
        email_subject,
        totalprescritions_by_speciality,
        totalprescribers_by_speciality,
        totalprescritions_jnj_speciality,
        totalprescritions_by_indication,
        totalprescribers_by_indication,
        totalprescritions_jnj_indication,
        year_month,
        devicecategory,
        channelgrouping,
        visitor_country,
        new_visitors,
        repeat_visitors,
        all_visitor,
        unique_pageviews,
        total_downloads,
        pages,
        page_sessions,
        total_page_views,
        total_bounces,
        total_session_duration,
        sessions,
        territory_id,
        region,
        sales_unit,
        sales_value,
        totalsales_unit_by_brand,
        totalsales_value_by_brand,
        totalsales_unit_by_jnj_brand,
        totalsales_value_by_jnj_brand,
        medical_event_id,
        event_name,
        event_type,
        event_role,
        attendee_status,
        event_location,
        survey_question,
        survey_response,
        attendee_name,
        key_message,
        sales_channel,
        sales_area,
        sales_rep_count,
        null as survey_name,
        null as sample_id,
        null as customer_code,
        null as customer_name,
        null as retailer_code,
        null as retailer_name,
        null as retailer_category_cd,
        null as retailer_category_name,
        null as num_buying_retailer,
        null as is_active,
        null as event_status,
        null as category,
        udc_avbabybodydocq42019,
        udc_babyprofesionalcac2019,
        variant_name,
    from {{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl7') }}
),
edw_hcp360_kpi_rpt_tbl7_sales as 
(
    select 
        country,
        source_system,
        null as channel,
        activity_type,
        null as hcp_master_id,
        null as employee_id,
        brand,
        null as brand_category,
        null as speciality,
        null as core_noncore,
        null as classification,
        null as territory,
        zone,
        null as hcp_created_date,
        null as activity_date,
        null as call_source_id,
        null as product_indication_name,
        null as no_of_prescription_units,
        null as first_prescription_date,
        null as planned_call_cnt,
        null as call_duration,
        null as prescription_id,
        null as noofprescritions,
        null as noofprescribers,
        null as email_name,
        null as is_unique,
        null as email_delivered_flag,
        crt_dttm,
        updt_dttm,
        null as target_value,
        null as target_kpi,
        null as report_brand_reference,
        null as diagnosis,
        null as region_hq,
        null as email_activity_type,
        null as hcp_id,
        null as transaction_flag,
        null as iqvia_brand,
        null as iqvia_pack_description,
        null as iqvia_product_description,
        null as iqvia_pack_volume,
        null as iqvia_input_brand,
        null as mat_noofprescritions,
        null as mat_noofprescribers,
        null as field_rep_active,
        null as mat_totalprescritions_by_brand,
        null as mat_totalprescribers_by_brand,
        null as mat_totalprescritions_jnj_brand,
        null as totalprescritions_by_brand,
        null as totalprescribers_by_brand,
        null as totalprescritions_jnj_brand,
        null as call_type,
        null as email_subject,
        null as totalprescritions_by_speciality,
        null as totalprescribers_by_speciality,
        null as totalprescritions_jnj_speciality,
        null as totalprescritions_by_indication,
        null as totalprescribers_by_indication,
        null as totalprescritions_jnj_indication,
        year_month,
        null as devicecategory,
        null as channelgrouping,
        null as visitor_country,
        null as new_visitors,
        null as repeat_visitors,
        null as all_visitor,
        null as unique_pageviews,
        null as total_downloads,
        null as pages,
        null as page_sessions,
        null as total_page_views,
        null as total_bounces,
        null as total_session_duration,
        null as sessions,
        null as territory_id,
        region,
        null as sales_unit,
        sales_value,
        null as totalsales_unit_by_brand,
        null as totalsales_value_by_brand,
        null as totalsales_unit_by_jnj_brand,
        null as totalsales_value_by_jnj_brand,
        null as medical_event_id,
        null as event_name,
        null as event_type,
        null as event_role,
        null as attendee_status,
        null as event_location,
        null as survey_question,
        null as survey_response,
        null as attendee_name,
        null as key_message,
        null as sales_channel,
        sales_area,
        null as sales_rep_count,
        null as survey_name,
        null as sample_id,
        customer_code,
        customer_name,
        retailer_code,
        retailer_name,
        retailer_category_cd,
        retailer_category_name,
        num_buying_retailer,
        null as is_active,
        null as event_status,
        null as category,
        null as udc_avbabybodydocq42019,
        null as udc_babyprofesionalcac2019,
        null as variant_name
    from {{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl7_sales') }}
),
edw_hcp360_kpi_rpt_tbl8 as 
(
    select 
        country,
        source_system,
        null as channel,
        activity_type,
        null as hcp_master_id,
        null as employee_id,
        brand,
        null as brand_category,
        null as speciality,
        null as core_noncore,
        null as classification,
        null as territory,
        zone,
        null as hcp_created_date,
        null as activity_date,
        null as call_source_id,
        null as product_indication_name,
        null as no_of_prescription_units,
        null as first_prescription_date,
        null as planned_call_cnt,
        null as call_duration,
        null as prescription_id,
        null as noofprescritions,
        null as noofprescribers,
        null as email_name,
        null as is_unique,
        null as email_delivered_flag,
        crt_dttm,
        updt_dttm,
        null as target_value,
        null as target_kpi,
        null as report_brand_reference,
        null as diagnosis,
        null as region_hq,
        null as email_activity_type,
        null as hcp_id,
        null as transaction_flag,
        null as iqvia_brand,
        null as iqvia_pack_description,
        null as iqvia_product_description,
        null as iqvia_pack_volume,
        null as iqvia_input_brand,
        null as mat_noofprescritions,
        null as mat_noofprescribers,
        null as field_rep_active,
        null as mat_totalprescritions_by_brand,
        null as mat_totalprescribers_by_brand,
        null as mat_totalprescritions_jnj_brand,
        null as totalprescritions_by_brand,
        null as totalprescribers_by_brand,
        null as totalprescritions_jnj_brand,
        null as call_type,
        null as email_subject,
        null as totalprescritions_by_speciality,
        null as totalprescribers_by_speciality,
        null as totalprescritions_jnj_speciality,
        null as totalprescritions_by_indication,
        null as totalprescribers_by_indication,
        null as totalprescritions_jnj_indication,
        year_month,
        null as devicecategory,
        null as channelgrouping,
        null as visitor_country,
        null as new_visitors,
        null as repeat_visitors,
        null as all_visitor,
        null as unique_pageviews,
        null as total_downloads,
        null as pages,
        null as page_sessions,
        null as total_page_views,
        null as total_bounces,
        null as total_session_duration,
        null as sessions,
        null as territory_id,
        region,
        null as sales_unit,
        sales_value,
        null as totalsales_unit_by_brand,
        null as totalsales_value_by_brand,
        null as totalsales_unit_by_jnj_brand,
        null as totalsales_value_by_jnj_brand,
        null as medical_event_id,
        null as event_name,
        null as event_type,
        null as event_role,
        null as attendee_status,
        null as event_location,
        null as survey_question,
        null as survey_response,
        null as attendee_name,
        null as key_message,
        sales_channel,
        sales_area,
        sales_rep_count,
        null as survey_name,
        null as sample_id,
        null as customer_code,
        null as customer_name,
        null as retailer_code,
        null as retailer_name,
        null as retailer_category_cd,
        null as retailer_category_name,
        null as num_buying_retailer,
        null as is_active,
        null as event_status,
        null as category,
        null as udc_avbabybodydocq42019,
        null as udc_babyprofesionalcac2019,
        null as variant_name
    from {{ ref('hcpedw_integration__edw_hcp360_kpi_rpt_tbl8') }}
),
trans as 
(
    select * from edw_hcp360_kpi_rpt_tbl1 
    union all
    select * from edw_hcp360_kpi_rpt_tbl2 
    union all
    select * from edw_hcp360_kpi_rpt_tbl3
    union all
    select * from edw_hcp360_kpi_rpt_tbl4
    union all
    select * from edw_hcp360_kpi_rpt_tbl4_target
    union all
    select * from edw_hcp360_kpi_rpt_tbl5
    union all
    select * from edw_hcp360_kpi_rpt_tbl6
    union all
    select * from edw_hcp360_kpi_rpt_tbl7
    union all
    select * from edw_hcp360_kpi_rpt_tbl7_sales
    union all
    select * from edw_hcp360_kpi_rpt_tbl8
),
final as 
(
    select 
	country::varchar(20) as country,
	source_system::varchar(20) as source_system,
	channel::varchar(20) as channel,
	activity_type::varchar(50) as activity_type,
	hcp_master_id::varchar(50) as hcp_master_id,
	employee_id::varchar(20) as employee_id,
	brand::varchar(20) as brand,
	brand_category::varchar(20) as brand_category,
	speciality::varchar(30) as speciality,
	core_noncore::varchar(20) as core_noncore,
	classification::varchar(50) as classification,
	territory::varchar(50) as territory,
	zone::varchar(50) as zone,
	hcp_created_date::date as hcp_created_date,
	activity_date::date as activity_date,
	call_source_id::varchar(18) as call_source_id,
	product_indication_name::varchar(100) as product_indication_name,
	no_of_prescription_units::number(15,2) as no_of_prescription_units,
	first_prescription_date::date as first_prescription_date,
	planned_call_cnt::number(3,0) as planned_call_cnt,
	call_duration::number(18,1) as call_duration,
	prescription_id::varchar(50) as prescription_id,
	noofprescritions::number(18,5) as noofprescritions,
	noofprescribers::number(18,5) as noofprescribers,
	email_name::varchar(100) as email_name,
	is_unique::varchar(1) as is_unique,
	email_delivered_flag::varchar(1) as email_delivered_flag,
	crt_dttm::timestamp_ntz(9) as crt_dttm,
	updt_dttm::timestamp_ntz(9) as updt_dttm,
	target_value::number(10,2) as target_value,
	target_kpi::varchar(50) as target_kpi,
	report_brand_reference::varchar(50) as report_brand_reference,
	diagnosis::varchar(100) as diagnosis,
	region_hq::varchar(50) as region_hq,
	email_activity_type::varchar(20) as email_activity_type,
	hcp_id::varchar(50) as hcp_id,
	transaction_flag::varchar(1) as transaction_flag,
	iqvia_brand::varchar(20) as iqvia_brand,
	iqvia_pack_description::varchar(100) as iqvia_pack_description,
	iqvia_product_description::varchar(50) as iqvia_product_description,
	iqvia_pack_volume::varchar(20) as iqvia_pack_volume,
	iqvia_input_brand::varchar(50) as iqvia_input_brand,
	mat_noofprescritions::number(18,5) as mat_noofprescritions,
	mat_noofprescribers::number(18,5) as mat_noofprescribers,
	field_rep_active::varchar(1) as field_rep_active,
	mat_totalprescritions_by_brand::number(18,5) as mat_totalprescritions_by_brand,
	mat_totalprescribers_by_brand::number(18,5) as mat_totalprescribers_by_brand,
	mat_totalprescritions_jnj_brand::number(18,5) as mat_totalprescritions_jnj_brand,
	totalprescritions_by_brand::number(18,5) as totalprescritions_by_brand,
	totalprescribers_by_brand::number(18,5) as totalprescribers_by_brand,
	totalprescritions_jnj_brand::number(18,5) as totalprescritions_jnj_brand,
	call_type::varchar(50) as call_type,
	email_subject::varchar(200) as email_subject,
	totalprescritions_by_speciality::number(18,5) as totalprescritions_by_speciality,
	totalprescribers_by_speciality::number(18,5) as totalprescribers_by_speciality,
	totalprescritions_jnj_speciality::number(18,5) as totalprescritions_jnj_speciality,
	totalprescritions_by_indication::number(18,5) as totalprescritions_by_indication,
	totalprescribers_by_indication::number(18,5) as totalprescribers_by_indication,
	totalprescritions_jnj_indication::number(18,5) as totalprescritions_jnj_indication,
	trunc(year_month)::varchar(25) as year_month,
	devicecategory::varchar(50) as devicecategory,
	channelgrouping::varchar(50) as channelgrouping,
	visitor_country::varchar(100) as visitor_country,
	new_visitors::number(18,5) as new_visitors,
	repeat_visitors::number(18,5) as repeat_visitors,
	all_visitor::number(18,5) as all_visitor,
	unique_pageviews::number(18,5) as unique_pageviews,
	total_downloads::number(18,5) as total_downloads,
	pages::number(18,5) as pages,
	page_sessions::number(18,5) as page_sessions,
	total_page_views::number(18,5) as total_page_views,
	total_bounces::number(18,5) as total_bounces,
	total_session_duration::number(18,5) as total_session_duration,
	sessions::number(18,5) as sessions,
	territory_id::varchar(20) as territory_id,
	region::varchar(100) as region,
	sales_unit::number(18,5) as sales_unit,
	sales_value::number(18,5) as sales_value,
	totalsales_unit_by_brand::number(18,5) as totalsales_unit_by_brand,
	totalsales_value_by_brand::number(18,5) as totalsales_value_by_brand,
	totalsales_unit_by_jnj_brand::number(18,5) as totalsales_unit_by_jnj_brand,
	totalsales_value_by_jnj_brand::number(18,5) as totalsales_value_by_jnj_brand,
	medical_event_id::varchar(18) as medical_event_id,
	event_name::varchar(80) as event_name,
	event_type::varchar(256) as event_type,
	event_role::varchar(256) as event_role,
	attendee_status::varchar(256) as attendee_status,
	event_location::varchar(40) as event_location,
	survey_question::varchar(1000) as survey_question,
	survey_response::varchar(6000) as survey_response,
	attendee_name::varchar(256) as attendee_name,
	key_message::varchar(250) as key_message,
	sales_channel::varchar(100) as sales_channel,
	sales_area::varchar(100) as sales_area,
	sales_rep_count::number(18,0) as sales_rep_count,
	survey_name::varchar(500) as survey_name,
	sample_id::varchar(20) as sample_id,
	customer_code::varchar(50) as customer_code,
	customer_name::varchar(150) as customer_name,
	retailer_code::varchar(100) as retailer_code,
	retailer_name::varchar(150) as retailer_name,
	retailer_category_cd::varchar(25) as retailer_category_cd,
	retailer_category_name::varchar(50) as retailer_category_name,
	num_buying_retailer::varchar(500) as num_buying_retailer,
	is_active::varchar(1) as is_active,
	event_status::varchar(100) as event_status,
	category::varchar(50) as category,
	udc_avbabybodydocq42019::varchar(150) as udc_avbabybodydocq42019,
	udc_babyprofesionalcac2019::varchar(150) as udc_babyprofesionalcac2019,
	variant_name::varchar(150) as variant_name
from trans
)
select * from final