with source as (
    select * from {{ ref ('pcfedw_integration__v_rpt_promo_analysis') }}
),
final as (
    select
        cmp_id as "cmp_id",
        country as "country",
        cust_no as "cust_no",
        promo_number as "promo_number",
        px_jj_year as "px_jj_year",
        px_jj_mnth as "px_jj_mnth",
        matl_id as "matl_id",
        sku_name as "sku_name",
        hierarchy_longname as "hierarchy_longname",
        promo_name as "promo_name",
        promo_start_date as "promo_start_date",
        promo_stop_date as "promo_stop_date",
        local_ccy as "local_ccy",
        cust_nm as "cust_nm",
        channel_desc as "channel_desc",
        sales_office_desc as "sales_office_desc",
        sales_grp_desc as "sales_grp_desc",
        matl_desc as "matl_desc",
        mega_brnd_desc as "mega_brnd_desc",
        brnd_desc as "brnd_desc",
        variant_desc as "variant_desc",
        fran_desc as "fran_desc",
        grp_fran_desc as "grp_fran_desc",
        prod_fran_desc as "prod_fran_desc",
        prod_hier_desc as "prod_hier_desc",
        prod_major_desc as "prod_major_desc",
        prod_minor_desc as "prod_minor_desc",
        px_base_qty as "px_base_qty",
        px_base_gts as "px_base_gts",
        px_promo_qty as "px_promo_qty",
        px_promo_gts as "px_promo_gts",
        px_total_qty as "px_total_qty",
        px_total_gts as "px_total_gts",
        px_base_cogs as "px_base_cogs",
        px_promo_cogs as "px_promo_cogs",
        px_total_cogs as "px_total_cogs",
        px_base_terms as "px_base_terms",
        px_promo_terms as "px_promo_terms",
        px_total_terms as "px_total_terms",
        case_qty as "case_qty",
        total_plan_spend as "total_plan_spend",
        total_paid as "total_paid",
        committed_spend as "committed_spend",
        finance_cogs as "finance_cogs"
    from source
)
select * from final