with source as (
    select * from {{ ref ('pcfedw_integration__vw_iri_scan_sales_analysis') }}
),
final as (
    select
        time_id as "time_id",
        jj_year as "jj_year",
        jj_qrtr as "jj_qrtr",
        jj_mnth as "jj_mnth",
        jj_wk as "jj_wk",
        jj_mnth_wk as "jj_mnth_wk",
        jj_mnth_id as "jj_mnth_id",
        jj_mnth_tot as "jj_mnth_tot",
        jj_mnth_day as "jj_mnth_day",
        jj_mnth_shrt as "jj_mnth_shrt",
        jj_mnth_long as "jj_mnth_long",
        cal_year as "cal_year",
        cal_qrtr as "cal_qrtr",
        cal_mnth as "cal_mnth",
        cal_wk as "cal_wk",
        cal_mnth_wk as "cal_mnth_wk",
        cal_mnth_id as "cal_mnth_id",
        cal_mnth_nm as "cal_mnth_nm",
        wk_end_dt as "wk_end_dt",
        representative_cust_cd as "representative_cust_cd",
        representative_cust_nm as "representative_cust_nm",
        channel_cd as "channel_cd",
        channel_desc as "channel_desc",
        country as "country",
        sales_grp_cd as "sales_grp_cd",
        sales_grp_nm as "sales_grp_nm",
        iri_market as "iri_market",
        ac_nielsencode as "ac_nielsencode",
        ac_longname as "ac_longname",
        iri_ean as "iri_ean",
        iri_prod_desc as "iri_prod_desc",
        matl_id as "matl_id",
        matl_desc as "matl_desc",
        master_code as "master_code",
        parent_matl_id as "parent_matl_id",
        parent_matl_desc as "parent_matl_desc",
        brnd_cd as "brnd_cd",
        brnd_desc as "brnd_desc",
        fran_cd as "fran_cd",
        fran_desc as "fran_desc",
        grp_fran_cd as "grp_fran_cd",
        grp_fran_desc as "grp_fran_desc",
        prod_fran_cd as "prod_fran_cd",
        prod_fran_desc as "prod_fran_desc",
        prod_mjr_cd as "prod_mjr_cd",
        prod_mjr_desc as "prod_mjr_desc",
        prod_mnr_cd as "prod_mnr_cd",
        prod_mnr_desc as "prod_mnr_desc",
        scan_units as "scan_units",
        scan_sales as "scan_sales",
        numeric_distribution as "numeric_distribution" ,
        weighted_distribution as "weighted_distribution",
        store_count_where_scanned as "store_count_where_scanned",
        pka_productkey as "pka_productkey",
        pka_productdesc as "pka_productdesc",
        lst_sku as "lst_sku",
        gph_region as "gph_region",
        gph_reg_frnchse as "gph_reg_frnchse",
        gph_reg_frnchse_grp as "gph_reg_frnchse_grp",
        gph_prod_frnchse as "gph_prod_frnchse",
        gph_prod_brnd as "gph_prod_brnd",
        gph_prod_sub_brnd as "gph_prod_sub_brnd",
        gph_prod_vrnt as "gph_prod_vrnt",
        gph_prod_needstate as "gph_prod_needstate",
        gph_prod_ctgry as "gph_prod_ctgry",
        gph_prod_subctgry as "gph_prod_subctgry",
        gph_prod_sgmnt as "gph_prod_sgmnt",
        gph_prod_subsgmnt as "gph_prod_subsgmnt",
        gph_prod_put_up_cd as "gph_prod_put_up_cd",
        gph_prod_put_up_desc as "gph_prod_put_up_desc"
    from source
)
select * from final