with source as (
    select * from {{ ref ('pcfedw_integration__vw_demand_forecast_analysis') }}
),
final as (
    select
        pac_source_type as "pac_source_type",
        pac_subsource_type as "pac_subsource_type",
        jj_period as "jj_period",
        jj_week_no as "jj_week_no",
        jj_wk as "jj_wk",
        jj_mnth as "jj_mnth",
        jj_mnth_shrt as "jj_mnth_shrt",
        jj_mnth_long as "jj_mnth_long",
        jj_qrtr as "jj_qrtr",
        jj_year as "jj_year",
        jj_mnth_tot as "jj_mnth_tot",
        week_date as "week_date",
        matl_no as "matl_no",
        matl_desc as "matl_desc",
        master_code as "master_code",
        parent_id as "parent_id",
        parent_matl_desc as "parent_matl_desc",
        mega_brnd_cd as "mega_brnd_cd",
        mega_brnd_desc as "mega_brnd_desc",
        brnd_cd as "brnd_cd",
        brnd_desc as "brnd_desc",
        base_prod_cd as "base_prod_cd",
        base_prod_desc as "base_prod_desc",
        variant_cd as "variant_cd",
        variant_desc as "variant_desc",
        fran_cd as "fran_cd",
        fran_desc as "fran_desc",
        grp_fran_cd as "grp_fran_cd",
        grp_fran_desc as "grp_fran_desc",
        matl_type_cd as "matl_type_cd",
        matl_type_desc as "matl_type_desc",
        prod_fran_cd as "prod_fran_cd",
        prod_fran_desc as "prod_fran_desc",
        prod_hier_cd as "prod_hier_cd",
        prod_hier_desc as "prod_hier_desc",
        prod_mjr_cd as "prod_mjr_cd",
        prod_mjr_desc as "prod_mjr_desc",
        prod_mnr_cd as "prod_mnr_cd",
        prod_mnr_desc as "prod_mnr_desc",
        mercia_plan as "mercia_plan",
        putup_cd as "putup_cd",
        putup_desc as "putup_desc",
        bar_cd as "bar_cd",
        cust_no as "cust_no",
        cmp_id as "cmp_id",
        ctry_key as "ctry_key",
        country as "country",
        state_cd as "state_cd",
        post_cd as "post_cd",
        cust_suburb as "cust_suburb",
        cust_nm as "cust_nm",
        fcst_chnl as "fcst_chnl",
        fcst_chnl_desc as "fcst_chnl_desc",
        sales_office_cd as "sales_office_cd",
        sales_office_desc as "sales_office_desc",
        sales_grp_cd as "sales_grp_cd",
        sales_grp_desc as "sales_grp_desc",
        curr_cd as "curr_cd",
        actual_sales_qty as "actual_sales_qty",
        apo_tot_frcst as "apo_tot_frcst",
        apo_base_frcst as "apo_base_frcst",
        apo_promo_frcst as "apo_promo_frcst",
        px_tot_frcst as "px_tot_frcst",
        px_base_frcst as "px_base_frcst",
        px_promo_frcst as "px_promo_frcst",
        projected_apo_tot_frcst as "projected_apo_tot_frcst",
        projected_px_tot_frcst as "projected_px_tot_frcst"
    from source
)
select * from final
