with source as (
    select * from {{ ref ('pcfedw_integration__edw_pharmacy_ecommerce_analysis') }}
),
final as (
	select 
        week_end_dt as "week_end_dt",
        jj_year as "jj_year",
        jj_qrtr as "jj_qrtr",
        jj_mnth as "jj_mnth",
        jj_wk as "jj_wk",
        jj_mnth_id as "jj_mnth_id",
        jj_mnth_tot as "jj_mnth_tot",
        jj_mnth_day as "jj_mnth_day",
        jj_mnth_shrt as "jj_mnth_shrt",
        jj_mnth_long as "jj_mnth_long",
        cal_year as "cal_year",
        cal_qrtr as "cal_qrtr",
        cal_mnth as "cal_mnth",
        cal_mnth_id as "cal_mnth_id",
        cal_mnth_nm as "cal_mnth_nm",
        prod_key as "prod_key",
        product_probe_id as "product_probe_id",
        prod_desc as "prod_desc",
        prod_sapbw_code as "prod_sapbw_code",
        prod_ean as "prod_ean",
        prod_jj_franchise as "prod_jj_franchise",
        prod_jj_category as "prod_jj_category",
        iqvia_prod_category as "iqvia_prod_category",
        prod_jj_brand as "prod_jj_brand",
        prod_sap_franchise as "prod_sap_franchise",
        prod_sap_profit_centre as "prod_sap_profit_centre",
        prod_sap_product_major as "prod_sap_product_major",
        prod_grocery_franchise as "prod_grocery_franchise",
        prod_grocery_category as "prod_grocery_category",
        prod_grocery_brand as "prod_grocery_brand",
        prod_pbs as "prod_pbs",
        prod_ims_brand as "prod_ims_brand",
        prod_nz_code as "prod_nz_code",
        gcph_franchise as "gcph_franchise",
        gcph_brand as "gcph_brand",
        gcph_subbrand as "gcph_subbrand",
        gcph_variant as "gcph_variant",
        gcph_needstate as "gcph_needstate",
        gcph_category as "gcph_category",
        gcph_subcategory as "gcph_subcategory",
        gcph_segment as "gcph_segment",
        gcph_subsegment as "gcph_subsegment",
        cust_group as "cust_group",
        ecomm_cust as "ecomm_cust",
        owner as "owner",
        manufacturer as "manufacturer",
        unit_online as "unit_online",
        aud_sales_online as "aud_sales_online",
        exch_rate_to_usd as "exch_rate_to_usd",
        usd_sales_online as "usd_sales_online"
    from source
)
select * from final
