with source as (
    select * from {{ ref ('pcfedw_integration__edw_promax_analysis_snapshot') }}
),
final as (
    select
        snapshot_date as "snapshot_date",
        snapshot_month as "snapshot_month",
        snapshot_year as "snapshot_year",
        ac_code as "ac_code",
        ac_longname as "ac_longname",
        activity_longname as "activity_longname",
        channel_desc as "channel_desc",
        closed_switch as "closed_switch",
        confirmed_switch as "confirmed_switch",
        country as "country",
        curr_cd as "curr_cd",
        cust_no as "cust_no",
        cust_del_flag as "cust_del_flag",
        cust_nm as "cust_nm",
        fran_desc as "fran_desc",
        gltt_rowid as "gltt_rowid",
        grp_fran_desc as "grp_fran_desc",
        jj_mnth_day as "jj_mnth_day",
        jj_mnth_shrt as "jj_mnth_shrt",
        jj_mnth_long as "jj_mnth_long",
        jj_mnth as "jj_mnth",
        jj_mnth_id as "jj_mnth_id",
        jj_qrtr as "jj_qrtr",
        jj_wk as "jj_wk",
        jj_year as "jj_year",
        local_ccy as "local_ccy",
        matl_desc as "matl_desc",
        matl_id as "matl_id",
        mega_brnd_desc as "mega_brnd_desc",
        prod_fran_desc as "prod_fran_desc",
        prod_mjr_desc as "prod_mjr_desc",
        prod_mnr_desc as "prod_mnr_desc",
        promax_bucket as "promax_bucket",
        p_buystartdatedef as "p_buystartdatedef",
        p_buystopdatedef as "p_buystopdatedef",
        p_deleted as "p_deleted",
        promotionforecastweek as "promotionforecastweek",
        p_promonumber as "p_promonumber",
        promotionrowid as "promotionrowid",
        p_startdate as "p_startdate",
        p_stopdate as "p_stopdate",
        sales_grp_desc as "sales_grp_desc",
        sales_office_desc as "sales_office_desc",
        sap_accnt_nm as "sap_accnt_nm",
        sap_account as "sap_account",
        transaction_longname as "transaction_longname",
        updt_dt as "updt_dt",
        buyperiod_length as "buyperiod_length",
        case_deal as "case_deal",
        case_quantity as "case_quantity",
        committed_spend as "committed_spend",
        aud_rate as "aud_rate",
        open_total as "open_total",
        paid_total as "paid_total",
        planspend_total as "planspend_total",
        promo_length as "promo_length"
    from source
)
select * from final
