with source as (
    select * from {{ ref ('pcfedw_integration__edw_gts_visibility') }}
),
final as (
	select 
        subsource_type as "subsource_type",
        country as "country",
        snapshot_date as "snapshot_date",
        snapshot_date_jnj_month as "snapshot_date_jnj_month",
        jj_mnth_id as "jj_mnth_id",
        jj_mnth as "jj_mnth",
        jj_mnth_nm as "jj_mnth_nm",
        jj_year as "jj_year",
        jj_qrtr as "jj_qrtr",
        cust_num as "cust_num",
        matl_num as "matl_num",
        sls_doc as "sls_doc",
        rqst_delv_dt as "rqst_delv_dt",
        rqst_delv_dt_jnj_month as "rqst_delv_dt_jnj_month",
        bill_num as "bill_num",
        bill_dt as "bill_dt",
        bill_dt_yyyy_mm as "bill_dt_yyyy_mm",
        created_on as "created_on",
        grp_fran_desc as "grp_fran_desc",
        prod_fran_desc as "prod_fran_desc",
        prod_mjr_desc as "prod_mjr_desc",
        prod_mnr_desc as "prod_mnr_desc",
        matl_desc as "matl_desc",
        brnd_desc as "brnd_desc",
        gcph_franchise as "gcph_franchise",
        gcph_brand as "gcph_brand",
        gcph_subbrand as "gcph_subbrand",
        gcph_variant as "gcph_variant",
        gcph_needstate as "gcph_needstate",
        gcph_category as "gcph_category",
        gcph_subcategory as "gcph_subcategory",
        gcph_segment as "gcph_segment",
        gcph_subsegment as "gcph_subsegment",
        master_code as "master_code",
        channel_desc as "channel_desc",
        sales_office_desc as "sales_office_desc",
        cust_nm as "cust_nm",
        sales_grp_desc as "sales_grp_desc",
        local_ccy as "local_ccy",
        to_ccy as "to_ccy",
        exch_rate as "exch_rate",
        open_orders_val as "open_orders_val",
        gts_landing_val as "gts_landing_val"
    from source
)
select * from final
