with vw_pharm_sellout_analysis as (
    select * from {{ ref('pcfedw_integration__vw_pharm_sellout_analysis') }}

),
final as (
select 
pac_source_type::varchar(7) as pac_source_type,
pac_subsource_type::varchar(12) as pac_subsource_type,
cal_date::date as cal_date,
jj_wk::number(18,0) as jj_wk,
jj_mnth::number(18,0) as jj_mnth,
jj_mnth_shrt::varchar(3) as jj_mnth_shrt,
jj_mnth_long::varchar(10) as jj_mnth_long,
jj_qrtr::number(18,0) as jj_qrtr,
jj_year::number(18,0) as jj_year,
cal_mnth_id::number(18,0) as cal_mnth_id,
jj_mnth_id::number(18,0) as jj_mnth_id,
cal_mnth::number(18,0) as cal_mnth,
cal_qrtr::number(18,0) as cal_qrtr,
cal_year::number(18,0) as cal_year,
jj_mnth_tot::number(18,0) as jj_mnth_tot,
jj_mnth_day::number(18,0) as jj_mnth_day,
cal_mnth_nm::varchar(10) as cal_mnth_nm,
store_probe_id::varchar(10) as store_probe_id,
store_id::number(10,0) as store_id,
store::varchar(256) as store,
suburb::varchar(255) as suburb,
postcode::varchar(255) as postcode,
store_country::varchar(256) as store_country,
store_region::varchar(256) as store_region,
store_state::varchar(256) as store_state,
store_channel::varchar(256) as store_channel,
store_type::varchar(256) as store_type,
store_banner::varchar(256) as store_banner,
store_grade::varchar(256) as store_grade,
ssr_team_leader::varchar(256) as ssr_team_leader,
ssr_territory::varchar(256) as ssr_territory,
ssr_region::varchar(256) as ssr_region,
aus_pharm_territory::varchar(256) as aus_pharm_territory,
aus_pharm_region::varchar(256) as aus_pharm_region,
aus_pharm_strategy::varchar(12) as aus_pharm_strategy,
aus_pharm_responsibility::varchar(12) as aus_pharm_responsibility,
primary_rep_team::varchar(61) as primary_rep_team,
primary_rep_region::varchar(317) as primary_rep_region,
primary_rep::varchar(267) as primary_rep,
product_probe_id::varchar(10) as product_probe_id,
product_id::number(10,0) as product_id,
product::varchar(100) as product,
units_in_inner::varchar(1) as units_in_inner,
sap_code::varchar(50) as sap_code,
ean::varchar(50) as ean,
symbion_code::varchar(1) as symbion_code,
api_code::varchar(1) as api_code,
sigma_code::varchar(1) as sigma_code,
pharmacy_franchise::varchar(100) as pharmacy_franchise,
pharmacy_category::varchar(100) as pharmacy_category,
pharmacy_brand::varchar(100) as pharmacy_brand,
sap_franchise::varchar(100) as sap_franchise,
sap_profit_centre::varchar(100) as sap_profit_centre,
sap_profit_major::varchar(100) as sap_profit_major,
pbs::varchar(100) as pbs,
active_aus_pharm::varchar(100) as active_aus_pharm,
matl_id::varchar(40) as matl_id,
matl_desc::varchar(100) as matl_desc,
mega_brnd_desc::varchar(100) as mega_brnd_desc,
brnd_desc::varchar(100) as brnd_desc,
fran_desc::varchar(100) as fran_desc,
grp_fran_desc::varchar(100) as grp_fran_desc,
prod_fran_desc::varchar(100) as prod_fran_desc,
prod_mjr_desc::varchar(100) as prod_mjr_desc,
putup_desc::varchar(100) as putup_desc,
bar_cd::varchar(40) as bar_cd,
time_period::varchar(8) as time_period,
units::number(18,0) as units,
amount::number(18,6) as amount,
derived_price::number(12,6) as derived_price,
order_id::number(10,0) as order_id,
order_status::varchar(255) as order_status,
turnin_units::number(10,0) as turnin_units,
inners::varchar(1) as inners,
turnin_nis::number(21,2) as turnin_nis,
discount_per::varchar(1) as discount_per,
"discount$":: varchar(1) as discount,
line_item_status::varchar(255) as line_item_status,
order_date::date as order_date,
sent_date::date as sent_date,
distributor_country::varchar(1) as distributor_country,
distributor::varchar(255) as distributor,
distributor_dc::varchar(255) as distributor_dc,
distributor_account_number::varchar(1) as distributor_account_number,
order_type::varchar(255) as order_type,
pharm_msl_flag::varchar(5) as pharm_msl_flag,
pharm_msl_rank::varchar(5) as pharm_msl_rank
from vw_pharm_sellout_analysis
)
select * from final