with EDW_RPT_SALES_DETAILS as (
	select * from {{ ref('indedw_integration__edw_rpt_sales_details') }}
),
ITG_MDS_IN_SSS_SCORE as (
	select * from {{ ref('inditg_integration__itg_mds_in_sss_score') }}
),
ITG_SSS_SCORECARD_DATA as (
	select * from {{ ref('inditg_integration__itg_sss_scorecard_data') }}
),
EDW_SSS_KPI_DATA_FINAL as (
	select * from {{ ref('indedw_integration__edw_sss_kpi_data_final') }}
),
MSL_FRANCHISE_ACHIEVEMENT_SCORE_CALC as (
	select * from {{ ref('indwks_integration__msl_franchise_achievement_score_calc') }}
),
ITG_MDS_IN_SSS_WEIGHTS as (
	select * from {{ ref('inditg_integration__itg_mds_in_sss_weights') }}
),
sales as(
	SELECT DISTINCT B.CAL_YR,
			B.QTR,
			RETAILER_CODE,
			RETAILER_NAME,
			RTRUNIQUECODE,
			REGION_NAME AS "REGION",
			ZONE_NAME AS "ZONE",
			TERRITORY_NAME AS "TERRITORY",
			CHANNEL_NAME AS "CHANNEL",
			RETAILER_CATEGORY_NAME AS "RETAIL_ENVIRONMENT",
			CUSTOMER_CODE AS "DISTRIBUTOR_CODE",
			CUSTOMER_NAME AS "DISTRIBUTOR_NAME",
			SALESMAN_CODE AS "SALESMAN_CODE",
			SALESMAN_NAME AS "SALESMAN_NAME",
			ROW_NUMBER() OVER (
				PARTITION BY B.CAL_YR,
				B.QTR,
				B.RETAILER_CODE ORDER BY invoice_date DESC
				) AS RN
		FROM EDW_RPT_SALES_DETAILS B
		WHERE UPPER(B.CHANNEL_NAME) = 'SELF SERVICE STORE'
),
SALES_RET as(
	SELECT DISTINCT B.RTRUNIQUECODE,
		B.RETAILER_CODE,
		B.RETAILER_NAME,
		ROW_NUMBER() OVER (
			PARTITION BY B.RETAILER_CODE ORDER BY invoice_date DESC
			) AS RN
	FROM EDW_RPT_SALES_DETAILS B
	WHERE UPPER(B.CHANNEL_NAME) = 'SELF SERVICE STORE'
),
MAX_SCO as(
	SELECT STORE_CLASS,
			KPI,
			NVL(BRAND, 'BRAND NOT APPLICABLE') AS BRAND,
			MAX(VALUE) AS MAX_POTENTIAL_BRAND_SCORE
		FROM ITG_MDS_IN_SSS_SCORE
		WHERE UPPER(KPI) = 'MSL COMPLIANCE'
		GROUP BY STORE_CLASS,
			KPI,
			NVL(BRAND, 'BRAND NOT APPLICABLE')
),
sss as(
	SELECT PROGRAM_TYPE,
		JNJ_ID,
		MAX(OUTLET_NAME) AS "LATEST_OUTLET_NAME"
	FROM ITG_SSS_SCORECARD_DATA
	GROUP BY 1,
		2
),
union1 as(
	SELECT 'INDIA' AS "COUNTRY",
		NVL(UPPER(SALES.REGION), UPPER(SSS.REGION)) AS REGION,
		NVL(UPPER(SALES.ZONE), UPPER(SSS.ZONE)) AS ZONE,
		NVL(UPPER(SALES.TERRITORY), UPPER(SSS.TERRITORY)) AS TERRITORY,
		NVL(UPPER(SALES.CHANNEL), 'STORE NOT LISTED AS SSS') AS CHANNEL,
		NVL(UPPER(SALES.RETAIL_ENVIRONMENT), 'STORE NOT LISTED AS SSS') AS RETAIL_ENVIRONMENT,
		NVL(UPPER(SALES.SALESMAN_NAME), 'STORE NOT LISTED AS SSS') AS SALESMAN_NAME,
		NVL(UPPER(SALES.SALESMAN_CODE), 'STORE NOT LISTED AS SSS') AS SALESMAN_CODE,
		NVL(UPPER(SALES.DISTRIBUTOR_CODE), 'STORE NOT LISTED AS SSS') AS DISTRIBUTOR_CODE,
		NVL(UPPER(SALES.DISTRIBUTOR_NAME), 'STORE NOT LISTED AS SSS') AS DISTRIBUTOR_NAME,
		SSS.JNJ_ID AS STORE_CODE,
		NVL((SALES_RET.RTRUNIQUECODE || '-' || UPPER(SALES_RET.RETAILER_NAME)), UPPER(SSS.outlet_name)) AS STORE_NAME,
		SSS.PROGRAM_TYPE,
		NVL(UPPER(SSS.BRAND), 'BRAND NOT APPLICABLE') AS FRANCHISE,
		UPPER(SSS.KPI) AS KPI,
		SSS.QUARTER,
		SSS.YEAR,
		SSS.SOURCE_ACTUAL::VARCHAR(50) AS SOURCE_ACTUAL_VALUE,
		SSS.SOURCE_TARGET::VARCHAR(50) AS SOURCE_TARGET_VALUE,
		CAST(SSS.ACTUAL AS NUMERIC(30, 24)) AS ACTUAL_VALUE,
		CAST(SSS.TARGET AS NUMERIC(30, 24)) AS TARGET_VALUE,
		(SSS.COMPLIANCE * 100) AS COMPLIANCE,
		SSS.WEIGHT,
		SSS.SCORE_VALUE AS KPI_SCORE,
		--,(SSS.COMPLIANCE * SSS.WEIGHT * 100) AS KPI_WEIGHTED_SCORE,
		NULL AS KPI_ACHIEVEMENT,
		SSS.MAX_POTENTIAL_BRAND_SCORE,
		NULL AS ACHIEVEMENT_NR,
		'INDIA' AS PROD_HIER_L1,
		NULL AS PROD_HIER_L2,
		SSS.BRAND AS PROD_HIER_L3,
		NULL AS PROD_HIER_L4,
		NULL AS PROD_HIER_L5,
		NULL AS PROD_HIER_L6,
		NULL AS PROD_HIER_L7,
		NULL AS PROD_HIER_L8,
		NULL AS PROD_HIER_L9,
		NULL::VARCHAR(5) AS ACTUAL_VALUE_MSL_L9,
		NULL::VARCHAR(5) AS TARGET_VALUE_MSL_L9,
		NVL(SALES_RET.RTRUNIQUECODE, 'STORE NOT LISTED AS SSS') AS RTRUNIQUECODE,
		current_timestamp()::timestamp_ntz(9) AS CRT_DTT,
		current_timestamp()::timestamp_ntz(9) AS UPDT_DTTM
	FROM EDW_SSS_KPI_DATA_FINAL SSS
	LEFT OUTER JOIN SALES ON SSS.JNJ_ID = SALES.RETAILER_CODE
		AND RIGHT(SSS.QUARTER, 1) = SALES.QTR
		AND SSS.YEAR = SALES.CAL_YR
		AND SALES.RN = 1
	--to select the outlet name from sales at retailer level
	LEFT OUTER JOIN SALES_RET ON SSS.JNJ_ID = SALES_RET.RETAILER_CODE
		AND SALES_RET.RN = 1
),
union2 as(
SELECT UPPER(CALC.COUNTRY) as COUNTRY,
	UPPER(CALC.REGION_NAME) AS REGION,
	UPPER(CALC.ZONE_NAME) AS ZONE,
	UPPER(CALC.TERRITORY_NAME) AS TERRITORY,
	UPPER(CALC.CHANNEL_NAME) AS CHANNEL,
	UPPER(CALC.RETAIL_ENVIRONMENT) AS RETAIL_ENVIRONMENT,
	CALC.SALESMAN_NAME as SALESMAN_NAME,
	CALC.SALESMAN_CODE as SALESMAN_CODE,
	CALC.DISTRIBUTOR_CODE as DISTRIBUTOR_CODE,
	CALC.DISTRIBUTOR_NAME as DISTRIBUTOR_NAME,
	CALC.STORE_CODE as STORE_CODE,
	UPPER(CALC.STORE_NAME) AS STORE_NAME,
	CALC.PROGRAM_TYPE as PROGRAM_TYPE,
	NVL(UPPER(CALC.PROD_HIER_L3), 'BRAND NOT APPLICABLE') AS FRANCHISE,
	'MSL' AS KPI,
	'Q' || CALC.QTR AS QUARTER,
	CALC.CAL_YR AS YEAR,
	CALC.ACTUAL_L3::VARCHAR(50) AS SOURCE_ACTUAL_VALUE,
	CALC.TARGET_L3::VARCHAR(50) AS SOURCE_TARGET_VALUE,
	CALC.ACTUAL_L3::NUMERIC(30, 24) AS ACTUAL_VALUE,
	CALC.TARGET_L3::NUMERIC(30, 24) AS TARGET_VALUE,
	CALC.FRANCHISE_MSL_ACHIEVEMENT * 100 AS COMPLIANCE,
	WEI.WEIGHT as WEIGHT,
	CALC.FRANCHISE_SCORE AS KPI_SCORE,
	CALC.FRANCHISE_MSL_ACHIEVEMENT AS KPI_ACHIEVEMENT,
	MAX_SCO.MAX_POTENTIAL_BRAND_SCORE,
	NULL AS ACHIEVEMENT_NR,
	'INDIA' AS "PROD_HIER_L1",
	NULL AS "PROD_HIER_L2",
	CALC.PROD_HIER_L3 as PROD_HIER_L3,
	CALC.PROD_HIER_L4 as PROD_HIER_L4,
	CALC.PROD_HIER_L5 as PROD_HIER_L5,
	CALC.PROD_HIER_L6 as PROD_HIER_L6,
	CALC.PROD_HIER_L7 as PROD_HIER_L7,
	CALC.PROD_HIER_L8 as PROD_HIER_L8,
	CALC.PROD_HIER_L9 as PROD_HIER_L9,
	CALC.ACTUAL::VARCHAR(5) AS ACTUAL_VALUE_MSL_L9,
	CALC.TARGET::VARCHAR(5) AS TARGET_VALUE_MSL_L9,
	CALC.RTRUNIQUECODE,
	current_timestamp()::timestamp_ntz(9) AS CRT_DTT,
	current_timestamp()::timestamp_ntz(9) AS UPDT_DTTM
FROM MSL_FRANCHISE_ACHIEVEMENT_SCORE_CALC CALC,
	 MAX_SCO,
	ITG_MDS_IN_SSS_WEIGHTS WEI
WHERE UPPER(CALC.program_type) = UPPER(MAX_SCO.STORE_CLASS)
	AND UPPER(calc.PROD_HIER_L3) = UPPER(MAX_SCO.BRAND)
	AND UPPER(MAX_SCO.KPI) = 'MSL COMPLIANCE'
	AND UPPER(CALC.PROGRAM_TYPE) = UPPER(WEI.STORE_CLASS)
	AND UPPER(wei.KPI) = 'MSL COMPLIANCE'
),
union3 as(
SELECT 'INDIA' AS "COUNTRY",
	UPPER(SALES.REGION_NAME) AS REGION,
	UPPER(SALES.ZONE_NAME) AS ZONE,
	UPPER(SALES.TERRITORY_NAME) AS TERRITORY,
	UPPER(SALES.CHANNEL_NAME) AS CHANNEL,
	UPPER(SALES.RETAILER_CATEGORY_NAME) AS RETAIL_ENVIRONMENT,
	UPPER(SALES.SALESMAN_NAME) AS SALESMAN_NAME,
	UPPER(SALES.SALESMAN_CODE) AS SALESMAN_CODE,
	UPPER(SALES.CUSTOMER_CODE) AS DISTRIBUTOR_CODE,
	UPPER(SALES.CUSTOMER_NAME) AS DISTRIBUTOR_NAME, 
	UPPER(SALES.RETAILER_CODE) AS STORE_CODE,
	NVL((SALES_RET.RTRUNIQUECODE || '-' || UPPER(SALES_RET.RETAILER_NAME)), UPPER(SSS.LATEST_OUTLET_NAME)) AS STORE_NAME,
	UPPER(SSS.PROGRAM_TYPE) AS PROGRAM_TYPE,
	NVL(CASE 
			WHEN UPPER(SALES.FRANCHISE_NAME) = 'SANPRO'
				THEN 'STAYFREE'
			WHEN UPPER(SALES.FRANCHISE_NAME) = 'OTC'
				THEN 'LISTERINE'
			WHEN UPPER(SALES.FRANCHISE_NAME) = 'BEAUTY CARE'
				THEN 'C&C'
			WHEN UPPER(SALES.FRANCHISE_NAME) = 'BABY CARE'
				THEN 'JOHNSON BABY'
			END, 'BRAND NOT APPLICABLE') AS FRANCHISE,
	'SALES VALUE' AS KPI,
	'Q' || SALES.QTR AS QUARTER,
	SALES.CAL_YR AS YEAR,
	'0'::VARCHAR(50) AS SOURCE_ACTUAL_VALUE,
	'0'::VARCHAR(50) AS SOURCE_TARGET_VALUE,
	0::NUMERIC(30, 24) AS ACTUAL_VALUE,
	0::NUMERIC(30, 24) AS TARGET_VALUE,
	0 AS "COMPLIANCE",
	0 AS WEIGHT,
	0 AS KPI_SCORE,
	0 AS KPI_ACHIEVEMENT,
	0 AS MAX_POTENTIAL_BRAND_SCORE,
	SUM(SALES.ACHIEVEMENT_NR) AS ACHIEVEMENT_NR,
	NULL AS PROD_HIER_L1,
	NULL AS PROD_HIER_L2,
	CASE 
		WHEN UPPER(SALES.FRANCHISE_NAME) = 'SANPRO'
			THEN 'STAYFREE'
		WHEN UPPER(SALES.FRANCHISE_NAME) = 'OTC'
			THEN 'LISTERINE'
		WHEN UPPER(SALES.FRANCHISE_NAME) = 'BEAUTY CARE'
			THEN 'C&C'
		WHEN UPPER(SALES.FRANCHISE_NAME) = 'BABY CARE'
			THEN 'JOHNSON BABY'
		END AS PROD_HIER_L3,
	UPPER(SALES.BRAND_NAME) AS PROD_HIER_L4,
	NULL AS PROD_HIER_L5,
	NULL AS PROD_HIER_L6,
	NULL AS PROD_HIER_L7,
	NULL AS PROD_HIER_L8,
	NULL AS PROD_HIER_L9,
	NULL::VARCHAR(5) AS ACTUAL_VALUE_MSL_L9,
	NULL::VARCHAR(5) AS TARGET_VALUE_MSL_L9,
	SALES_RET.RTRUNIQUECODE,
	current_timestamp()::timestamp_ntz(9) AS CRT_DTT,
	current_timestamp()::timestamp_ntz(9) AS UPDT_DTTM
FROM SSS
INNER JOIN EDW_RPT_SALES_DETAILS SALES ON SSS.JNJ_ID = SALES.RETAILER_CODE
	-- AND RIGHT(SSS.QUARTER,1) = SALES.QTR 
	--  AND SSS.YEAR = SALES.CAL_YR
	AND UPPER(SALES.CHANNEL_NAME) = 'SELF SERVICE STORE'
--to select the outlet name from sales at retailer level
LEFT OUTER JOIN SALES_RET ON UPPER(SSS.JNJ_ID) = UPPER(SALES_RET.RETAILER_CODE)
	AND SALES_RET.RN = 1
GROUP BY COUNTRY,
	REGION_NAME,
	ZONE_NAME,
	SALES.TERRITORY_NAME,
	SALES.CHANNEL_NAME,
	SALES.RETAILER_CATEGORY_NAME,
	SALES.SALESMAN_NAME,
	SALES.SALESMAN_CODE,
	SALES.CUSTOMER_CODE,
	SALES.CUSTOMER_NAME,
	SALES.RETAILER_CODE,
	STORE_NAME,
	PROGRAM_TYPE,
	FRANCHISE,
	KPI,
	QUARTER,
	SALES.CAL_YR,
	PROD_HIER_L3,
	PROD_HIER_L4,
	SALES_RET.RTRUNIQUECODE
),
transformed as(
	select * from union1
	union all
	select * from union2
    union all
	select * from union3
)
select * from transformed