with WKS_RPT_SSS_SCORECARD as (
    select * from DEV_DNA_CORE.INDWKS_INTEGRATION.WKS_RPT_SSS_SCORECARD
),

ITG_MDS_IN_SSS_PS_PROMOTER_STORE_MAP as (
    select *
    from DEV_DNA_CORE.INDITG_INTEGRATION.ITG_MDS_IN_SSS_PS_PROMOTER_STORE_MAP
),

CTE as (

    select 1
    from ITG_MDS_IN_SSS_PS_PROMOTER_STORE_MAP as MAP, WKS_RPT_SSS_SCORECARD
    where MAP.RTRUNIQUECODE = WKS_RPT_SSS_SCORECARD.RTRUNIQUECODE

),

TRANSFORMED as (
    select
        COUNTRY,
        REGION,
        ZONE,
        TERRITORY,
        CHANNEL,
        RETAIL_ENVIRONMENT,
        SALESMAN_NAME,
        SALESMAN_CODE,
        DISTRIBUTOR_CODE,
        DISTRIBUTOR_NAME,
        STORE_CODE,
        STORE_NAME,
        PROGRAM_TYPE,
        FRANCHISE,
        KPI,
        QUARTER,
        YEAR,
        ACTUAL_VALUE,
        TARGET_VALUE,
        COMPLIANCE,
        WEIGHT,
        KPI_SCORE,
        KPI_ACHIEVEMENT,
        MAX_POTENTIAL_BRAND_SCORE,
        ACHIEVEMENT_NR,
        ACTUAL_VALUE_MSL_L9,
        TARGET_VALUE_MSL_L9,
        RTRUNIQUECODE,
        CRT_DTT,
        UPDT_DTTM,
        ROW_NUMBER() over (
            order by CRT_DTT
        ) as TABLE_RN,
        COALESCE(PROD_HIER_L1, 'NOT AVAILABLE PROD_HIER_L1') as PROD_HIER_L1,
        COALESCE(PROD_HIER_L2, 'NOT AVAILABLE PROD_HIER_L2') as PROD_HIER_L2,
        COALESCE(PROD_HIER_L3, 'NOT AVAILABLE PROD_HIER_L3') as PROD_HIER_L3,
        COALESCE(PROD_HIER_L4, 'NOT AVAILABLE PROD_HIER_L4') as PROD_HIER_L4,
        COALESCE(PROD_HIER_L5, 'NOT AVAILABLE PROD_HIER_L5') as PROD_HIER_L5,
        COALESCE(PROD_HIER_L6, 'NOT AVAILABLE PROD_HIER_L6') as PROD_HIER_L6,
        COALESCE(PROD_HIER_L7, 'NOT AVAILABLE PROD_HIER_L7') as PROD_HIER_L7,
        COALESCE(PROD_HIER_L8, 'NOT AVAILABLE PROD_HIER_L8') as PROD_HIER_L8,
        COALESCE(PROD_HIER_L9, 'NOT AVAILABLE PROD_HIER_L9') as PROD_HIER_L9,
        case
            when CTE = 1
                then 'Y'
            else 'N'
        end as PROMOTOR_STORE
    from WKS_RPT_SSS_SCORECARD SSS
)

select * from TRANSFORMED
