with WKS_RPT_SSS_SCORECARD as (
    select * from DEV_DNA_CORE.INDWKS_INTEGRATION.WKS_RPT_SSS_SCORECARD
),
ITG_MDS_IN_SSS_PS_PROMOTER_STORE_MAP as (
    select * from DEV_DNA_CORE.INDITG_INTEGRATION.ITG_MDS_IN_SSS_PS_PROMOTER_STORE_MAP
),
cte as(
        select MAP.RTRUNIQUECODE
            from ITG_MDS_IN_SSS_PS_PROMOTER_STORE_MAP as MAP
),
TRANSFORMED as (
    select
    ROW_NUMBER() OVER (
		ORDER BY CRT_DTT
		) TABLE_RN,
	COUNTRY,
	REGION,
	ZONE,
	TERRITORY,
	CHANNEL,
	RETAIL_ENVIRONMENT,
	SALESMAN_NAME,
	SALESMAN_CODE,
	DISTRIBUTOR_CODE,
	DISTRIBUTOR_NAME,
	STORE_CODE,
	STORE_NAME,
	PROGRAM_TYPE,
	FRANCHISE,
	KPI,
	QUARTER,
	YEAR,
	ACTUAL_VALUE,
	TARGET_VALUE,
	COMPLIANCE,
	WEIGHT,
	KPI_SCORE,
	KPI_ACHIEVEMENT,
	MAX_POTENTIAL_BRAND_SCORE,
	ACHIEVEMENT_NR,
	NVL(PROD_HIER_L1, 'NOT AVAILABLE PROD_HIER_L1') AS PROD_HIER_L1,
	NVL(PROD_HIER_L2, 'NOT AVAILABLE PROD_HIER_L2') AS PROD_HIER_L2,
	NVL(PROD_HIER_L3, 'NOT AVAILABLE PROD_HIER_L3') AS PROD_HIER_L3,
	NVL(PROD_HIER_L4, 'NOT AVAILABLE PROD_HIER_L4') AS PROD_HIER_L4,
	NVL(PROD_HIER_L5, 'NOT AVAILABLE PROD_HIER_L5') AS PROD_HIER_L5,
	NVL(PROD_HIER_L6, 'NOT AVAILABLE PROD_HIER_L6') AS PROD_HIER_L6,
	NVL(PROD_HIER_L7, 'NOT AVAILABLE PROD_HIER_L7') AS PROD_HIER_L7,
	NVL(PROD_HIER_L8, 'NOT AVAILABLE PROD_HIER_L8') AS PROD_HIER_L8,
	NVL(PROD_HIER_L9, 'NOT AVAILABLE PROD_HIER_L9') AS PROD_HIER_L9,
	ACTUAL_VALUE_MSL_L9,
	TARGET_VALUE_MSL_L9,
	sss.RTRUNIQUECODE,
	 case 
        when cte.RTRUNIQUECODE is not null
            then 'Y'
        else 'N'
    end::varchar(1) as PROMOTOR_STORE,
	CRT_DTT,
	UPDT_DTTM 
    from WKS_RPT_SSS_SCORECARD SSS
    left join cte on cte.RTRUNIQUECODE = SSS.RTRUNIQUECODE
)
select * from TRANSFORMED