
with 
itg_account_hcp as (
select * from {{ ref('hcposeitg_integration__itg_account_hcp') }}
),
itg_recordtype as (
select * from {{ ref('hcposeitg_integration__itg_recordtype') }}
),
itg_account_hco as (
select * from {{ ref('hcposeitg_integration__itg_account_hco') }}
),
itg_lookup_eng_data as (
select * from {{ source('hcposeitg_integration', 'itg_lookup_eng_data') }}
),
HCP_POS_ENG AS(
SELECT COUNTRY_CODE, KEY_VALUE, TARGET_VALUE
                    FROM itg_lookup_eng_data
                    WHERE  UPPER(TABLE_NAME) ='DIM_HCP'
                    AND UPPER(COLUMN_NAME) = 'POSITION'
                    AND UPPER(TARGET_COLUMN_NAME) = 'POSITION_NAME_ENGLISH')
,
SPEC1_ENG AS(SELECT COUNTRY_CODE, KEY_VALUE, TARGET_VALUE
                    FROM itg_lookup_eng_data
                    WHERE  UPPER(TABLE_NAME) ='DIM_HCP'
                    AND UPPER(COLUMN_NAME) = 'SPECIALTY_1'
                    AND UPPER(TARGET_COLUMN_NAME) = 'SPECIALITY_1_TYPE_ENGLISH')   
,                    
 HCP_TYPE_ENG AS(SELECT COUNTRY_CODE, KEY_VALUE, TARGET_VALUE
                    FROM itg_lookup_eng_data
                    WHERE  UPPER(TABLE_NAME) ='DIM_HCP'
                    AND UPPER(COLUMN_NAME) = 'HCP_TYPE'
                    AND UPPER(TARGET_COLUMN_NAME) = 'HCP_TYPE_ENGLISH') ,
cte1 as (
SELECT DISTINCT 
    itg_hcp.hcp_key as hcp_key,
    itg_hcp.country_code as country_code,
    itg_hcp.account_source_id as hcp_source_id,
    itg_hcp.last_modified_date as modify_dt,
    itg_hcp.last_modified_by_id as modify_id,
    nvl(itg_hcp.external_id,'Not Applicable') as hcp_business_id,
    itg_hcp.professional_type as hcp_type,
    nvl(hcp_type_eng.target_value,itg_hcp.professional_type) as hcp_type_english,
    itg_hcp.inactive as inactive_flag,
    (case when upper(itg_hcp.inactive) = 1 then sysdate() when upper(itg_hcp.inactive) is null then null when upper(itg_hcp.inactive) = ' ' then null else null end) as inactive_date,
    'Not Applicable' as inactive_reason,
    itg_hcp.hcp_name as hcp_name,
    itg_hcp.hcp_english_name as hcp_english_name,
    itg_hcp.hcp_name as hcp_display_name,
    itg_hcp.gender as gender,
    itg_hcp.birth_day as birth_day,
    itg_hcp.specialty_1 as speciality_1_type,
    nvl(spec1_eng.target_value,itg_hcp.specialty_1) as speciality_1_type_english,
    itg_hcp.position as position_name,
    nvl(hcp_pos_eng.target_value,itg_hcp.position) as position_name_english,
    itg_hcp.territory_name as territory_name,
    itg_hcp.is_kol as kol_flag,
    'Not Applicable' as license_cd,
    itg_hcp.direct_line as direct_line_number,
    itg_hcp.direct_fax as direct_fax_number,
    itg_hcp.person_email as email_id,
    itg_hcp.mobile_nbr as mobile_nbr,
    itg_hcp.do_not_call_ind as do_not_call_flag,
    itg_hcp.email_opt_out_ind as email_opt_out_flag,
    itg_hco.hco_key as parent_hco_key,
    itg_hco.hco_name as parent_hco_name,
    itg_rec.record_type_name as record_type_name,
    nvl(itg_hcp.external_id,'Not Applicable') as hcp_external_id,
    itg_hcp.remarks as remarks,
    itg_hcp.is_deleted as deleted_flag,
    itg_hcp.preferred_name as preferred_name,
    itg_hcp.professional_type as professional_type,
    itg_hcp.go_classification as go_classification,
    itg_hcp.hcc_account_approved as hcc_account_approved_flag,
    itg_hcp.salutation as salutation,
    itg_hcp.is_excluded_from_realign as exclude_from_territory_assignment_rules_flag,
    itg_hcp.sfe_approved as sfe_approved_flag,
    itg_hcp.physician_prescribing_behavior as physician_prescribing_behavior,
    itg_hcp.physician_behavioral_style as physician_behavioral_style,
    itg_hcp.is_external_id_number::INTEGER as is_external_id_number,
    itg_hcp.customer_value_segmentation as customer_value_segmentation,
    itg_hcp.ability_to_influence_peers as ability_to_influence_peers,
    itg_hcp.practice_size as practice_size,
    itg_hcp.patient_type as patient_type,
    itg_hcp.patient_medical_condition as patient_medical_condition,
    itg_hcp.md_customer_segmentation as md_customer_segmentation,
    itg_hcp.years_of_experience as years_of_experience,
    itg_hcp.md_innovation as md_innovation,
    itg_hcp.md_number_of_procedures as md_number_of_procedures,
    itg_hcp.md_types_of_procedure as md_types_of_procedure,
    itg_hcp.md_total_hip_replacement as md_total_hip_replacement,
    itg_hcp.md_total_knee_replacement as md_total_knee_replacement,
    itg_hcp.md_spine as md_spine,
    itg_hcp.md_trauma as md_trauma,
    itg_hcp.md_collorectal as md_collorectal,
    itg_hcp.md_hepatobiliary as md_hepatobiliary,
    itg_hcp.md_cholecystectomy as md_cholecystectomy,
    itg_hcp.md_total_hysterectomy as md_total_hysterectomy,
    itg_hcp.md_myomectomy as md_myomectomy,
    itg_hcp.md_c_section as md_c_section,
    itg_hcp.md_normal_delivery as md_normal_delivery,
    itg_hcp.md_cabg as md_cabg,
    itg_hcp.md_valve_repair as md_valve_repair,
    itg_hcp.md_abdominal as md_abdominal,
    itg_hcp.md_breast_reconstruction as md_breast_reconstruction,
    itg_hcp.md_oral_cranial_maxilofacial as md_oral_cranial_maxilofacial,
    sysdate() as inserted_date,
    sysdate() as updated_date,
    itg_hcp.primary_ta as primary_ta,
    itg_hcp.secondary_ta as secondary_ta
FROM itg_account_hcp ITG_HCP
  JOIN itg_recordtype ITG_REC ON ITG_HCP.RECORD_TYPE_SOURCE_ID = ITG_REC.RECORD_TYPE_SOURCE_ID
       AND ITG_HCP.COUNTRY_CODE = ITG_REC.COUNTRY_CODE 
    LEFT OUTER JOIN itg_account_hco ITG_HCO ON ITG_HCO.ACCOUNT_SOURCE_ID = ITG_HCP.PRIMARY_PARENT_SOURCE_ID 
    AND  ITG_HCO.COUNTRY_CODE = ITG_HCP.COUNTRY_CODE
   LEFT OUTER JOIN HCP_POS_ENG
     ON ITG_HCP.POSITION      = HCP_POS_ENG.KEY_VALUE
     AND ITG_HCP.COUNTRY_CODE = HCP_POS_ENG.COUNTRY_CODE
  LEFT OUTER JOIN SPEC1_ENG
     ON ITG_HCP.SPECIALTY_1  = SPEC1_ENG.KEY_VALUE
    AND ITG_HCP.COUNTRY_CODE = SPEC1_ENG.COUNTRY_CODE
  LEFT OUTER JOIN HCP_TYPE_ENG
    ON ITG_HCP.HCP_TYPE    = HCP_TYPE_ENG.KEY_VALUE
   AND ITG_HCP.COUNTRY_CODE = HCP_TYPE_ENG.COUNTRY_CODE),
   
cte2 as (
SELECT 'Not Applicable',
       'ZZ',
       'NA',
      sysdate(),
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       0,
       sysdate(),
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       sysdate(),
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       0,
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       0,
       0,
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       0,
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       0,
       'Not Applicable',
       0,
       0,
       0,
       'Not Applicable',
       0,
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       'Not Applicable',
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       0,
       sysdate(),
       sysdate(),
	   'Not Applicable',
	   'Not Applicable'
),
transformed as (
select * from cte1
union all
select * from cte2),
final as (
select
hcp_key::varchar(32) as hcp_key,
country_code::varchar(8) as country_code,
hcp_source_id::varchar(18) as hcp_source_id,
modify_dt::timestamp_ntz(9) as modify_dt,
modify_id::varchar(18) as modify_id,
hcp_business_id::varchar(30) as hcp_business_id,
hcp_type::varchar(255) as hcp_type,
hcp_type_english::varchar(255) as hcp_type_english,
inactive_flag::number(38,0) as inactive_flag,
inactive_date::date as inactive_date,
inactive_reason::varchar(255) as inactive_reason,
hcp_name::varchar(255) as hcp_name,
hcp_english_name::varchar(800) as hcp_english_name,
hcp_display_name::varchar(255) as hcp_display_name,
gender::varchar(255) as gender,
birth_day::date as birth_day,
speciality_1_type::varchar(255) as speciality_1_type,
speciality_1_type_english::varchar(255) as speciality_1_type_english,
position_name::varchar(255) as position_name,
position_name_english::varchar(255) as position_name_english,
territory_name::varchar(255) as territory_name,
kol_flag::number(38,0) as kol_flag,
license_cd::varchar(255) as license_cd,
direct_line_number::varchar(40) as direct_line_number,
direct_fax_number::varchar(40) as direct_fax_number,
email_id::varchar(255) as email_id,
mobile_nbr::varchar(40) as mobile_nbr,
do_not_call_flag::number(38,0) as do_not_call_flag,
email_opt_out_flag::number(38,0) as email_opt_out_flag,
parent_hco_key::varchar(32) as parent_hco_key,
parent_hco_name::varchar(1300) as parent_hco_name,
record_type_name::varchar(255) as record_type_name,
hcp_external_id::varchar(120) as hcp_external_id,
remarks::varchar(255) as remarks,
deleted_flag::number(38,0) as deleted_flag,
preferred_name::varchar(255) as preferred_name,
professional_type::varchar(255) as professional_type,
go_classification::varchar(255) as go_classification,
hcc_account_approved_flag::number(38,0) as hcc_account_approved_flag,
salutation::varchar(120) as salutation,
exclude_from_territory_assignment_rules_flag::number(38,0) as exclude_from_territory_assignment_rules_flag,
sfe_approved_flag::number(38,0) as sfe_approved_flag,
physician_prescribing_behavior::varchar(255) as physician_prescribing_behavior,
physician_behavioral_style::varchar(255) as physician_behavioral_style,
is_external_id_number::varchar(255) as is_external_id_number,
customer_value_segmentation::varchar(255) as customer_value_segmentation,
ability_to_influence_peers::varchar(255) as ability_to_influence_peers,
practice_size::varchar(255) as practice_size,
patient_type::varchar(255) as patient_type,
patient_medical_condition::varchar(255) as patient_medical_condition,
md_customer_segmentation::varchar(255) as md_customer_segmentation,
years_of_experience::varchar(255) as years_of_experience,
md_innovation::varchar(255) as md_innovation,
md_number_of_procedures::varchar(255) as md_number_of_procedures,
md_types_of_procedure::varchar(255) as md_types_of_procedure,
md_total_hip_replacement::number(18,0) as md_total_hip_replacement,
md_total_knee_replacement::number(18,0) as md_total_knee_replacement,
md_spine::number(18,0) as md_spine,
md_trauma::number(18,0) as md_trauma,
md_collorectal::number(18,0) as md_collorectal,
md_hepatobiliary::number(18,0) as md_hepatobiliary,
md_cholecystectomy::number(18,0) as md_cholecystectomy,
md_total_hysterectomy::number(18,0) as md_total_hysterectomy,
md_myomectomy::number(18,0) as md_myomectomy,
md_c_section::number(18,0) as md_c_section,
md_normal_delivery::number(18,0) as md_normal_delivery,
md_cabg::number(18,0) as md_cabg,
md_valve_repair::number(18,0) as md_valve_repair,
md_abdominal::number(18,0) as md_abdominal,
md_breast_reconstruction::number(18,0) as md_breast_reconstruction,
md_oral_cranial_maxilofacial::number(18,0) as md_oral_cranial_maxilofacial,
inserted_date::timestamp_ntz(9) as inserted_date,
updated_date::timestamp_ntz(9) as updated_date,
primary_ta::varchar(255) as primary_ta,
secondary_ta::varchar(255) as secondary_ta
from transformed
)
select * from final