{{
    config(
        materialized="incremental",
        incremental_strategy="merge",
        unique_key=["prft_ctr","cust_channel","cust_hdqtr_cd","ctry_cd","yr"],
        merge_exclude_columns=["crt_dttm"]
)}}
with source as (
    select * from {{ ref('ntaitg_integration__itg_trd_promo_actl') }}
),
final as (
    select
        prft_ctr::varchar(100) as prft_ctr,
        prft_ctr_desc::varchar(200) as prft_ctr_desc,
        cust_channel::varchar(100) as cust_channel,
        cust_hdqtr_cd::varchar(200) as cust_hdqtr_cd,
        ctry_cd::varchar(20) as ctry_cd,
        crncy_cd::varchar(3) as crncy_cd,
        yr::varchar(4) as yr,
        jan_und_prcs::number(16,2) as jan_und_prcs,
        jan_aprv_no_pmt::number(16,2) as jan_aprv_no_pmt,
        jan_pmt::number(16,2) as jan_pmt,
        jan_actl_trd_promo::number(16,2) as jan_actl_trd_promo,
        feb_und_prcs::number(16,2) as feb_und_prcs,
        feb_aprv_no_pmt::number(16,2) as feb_aprv_no_pmt,
        feb_pmt::number(16,2) as feb_pmt,
        feb_actl_trd_promo::number(16,2) as feb_actl_trd_promo,
        mar_und_prcs::number(16,2) as mar_und_prcs,
        mar_aprv_no_pmt::number(16,2) as mar_aprv_no_pmt,
        mar_pmt::number(16,2) as mar_pmt,
        mar_actl_trd_promo::number(16,2) as mar_actl_trd_promo,
        apr_und_prcs::number(16,2) as apr_und_prcs,
        apr_aprv_no_pmt::number(16,2) as apr_aprv_no_pmt,
        apr_pmt::number(16,2) as apr_pmt,
        apr_actl_trd_promo::number(16,2) as apr_actl_trd_promo,
        may_und_prcs::number(16,2) as may_und_prcs,
        may_aprv_no_pmt::number(16,2) as may_aprv_no_pmt,
        may_pmt::number(16,2) as may_pmt,
        may_actl_trd_promo::number(16,2) as may_actl_trd_promo,
        jun_und_prcs::number(16,2) as jun_und_prcs,
        jun_aprv_no_pmt::number(16,2) as jun_aprv_no_pmt,
        jun_pmt::number(16,2) as jun_pmt,
        jun_actl_trd_promo::number(16,2) as jun_actl_trd_promo,
        jul_und_prcs::number(16,2) as jul_und_prcs,
        jul_aprv_no_pmt::number(16,2) as jul_aprv_no_pmt,
        jul_pmt::number(16,2) as jul_pmt,
        jul_actl_trd_promo::number(16,2) as jul_actl_trd_promo,
        aug_und_prcs::number(16,2) as aug_und_prcs,
        aug_aprv_no_pmt::number(16,2) as aug_aprv_no_pmt,
        aug_pmt::number(16,2) as aug_pmt,
        aug_actl_trd_promo::number(16,2) as aug_actl_trd_promo,
        sep_und_prcs::number(16,2) as sep_und_prcs,
        sep_aprv_no_pmt::number(16,2) as sep_aprv_no_pmt,
        sep_pmt::number(16,2) as sep_pmt,
        sep_actl_trd_promo::number(16,2) as sep_actl_trd_promo,
        oct_und_prcs::number(16,2) as oct_und_prcs,
        oct_aprv_no_pmt::number(16,2) as oct_aprv_no_pmt,
        oct_pmt::number(16,2) as oct_pmt,
        oct_actl_trd_promo::number(16,2) as oct_actl_trd_promo,
        nov_und_prcs::number(16,2) as nov_und_prcs,
        nov_aprv_no_pmt::number(16,2) as nov_aprv_no_pmt,
        nov_pmt::number(16,2) as nov_pmt,
        nov_actl_trd_promo::number(16,2) as nov_actl_trd_promo,
        dec_und_prcs::number(16,2) as dec_und_prcs,
        dec_aprv_no_pmt::number(16,2) as dec_aprv_no_pmt,
        dec_pmt::number(16,2) as dec_pmt,
        dec_actl_trd_promo::number(16,2) as dec_actl_trd_promo,
        crt_dttm::timestamp_ntz(9) as crt_dttm,
        updt_dttm::timestamp_ntz(9) as updt_dttm
    from source
)
select * from final