version: 2

models:
  - name: ntaitg_integration__itg_kr_otc_inventory
    config: 
      alias: itg_kr_otc_inventory
      tags: ["j_kr_otc_inv_etl_framework","ingestion"]
  - name: ntaitg_integration__sdl_kr_raw_otc_inventory
    config: 
      alias: sdl_kr_raw_otc_inventory
      tags: ["j_kr_otc_inv_etl_framework","ingestion"]