version: 2

sources:
  - name: ntasdl_raw
    database: "{{ env_var('DBT_ENV_LOAD_DB') }}"
    schema: snapntasdl_raw
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: sdl_kr_otc_inventory
        tags: ["j_kr_otc_inv_etl_framework ","ingestion"]