version: 2

sources:
  - name: ntasdl_raw
    database: "{{ env_var('DBT_ENV_LOAD_DB') }}"
    schema: snapntasdl_raw
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
    - name: sdl_kr_otc_inventory
      tags: ["j_kr_otc_inv_etl_framework ","ingestion"]
      tests:
      - test_null:
          select_columns: ["mnth_id","matl_num","brand","product_name","distributor_cd"]
          not_null_columns: ["matl_num","distributor_cd"]
          name: TRATBL_sdl_kr_otc_inventory__null_test
          config:
            store_failures: true
            schema: ntawks_integration
      - test_duplicate:
          select_columns: ["mnth_id","matl_num","brand","product_name","distributor_cd"]
          group_by_columns: ["mnth_id","matl_num","brand","product_name","unit_price","distributor_cd","inv_qty","inv_amt","filename"]
          name: TRATBL_sdl_kr_otc_inventory__duplicate_test
          config:
            store_failures: true
            schema: ntawks_integration