version: 2

sources:
  - name: ntasdl_raw
    database: "{{ env_var('DBT_ENV_LOAD_DB') }}"
    schema: ntasdl_raw
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
      - name: sdl_tw_as_watsons_inventory
        tags: ["ph_bp_target","ingestion"]
        tests:
            - test_null:
                select_columns: ["item_cd","item_desc"]
                not_null_columns: ["item_cd"]
                name: TRATBL_sdl_tw_as_watsons_inventory__null_test
                config:
                  store_failures: true
                  schema: ntawks_integration
            - test_duplicate:
                select_columns: ["item_cd","item_desc"]
                group_by_columns: ["item_cd"]
                name: TRATBL_sdl_tw_as_watsons_inventory__duplicate_test
                config:
                  store_failures: true
                  schema: ntawks_integration
            - test_lookup:
                select_columns: ["item_cd","item_desc"]
                column: " nvl(trim(item_cd),'#')"
                lookup_column: "cust_prod_cd"
                lookup_table: "DEV_DNA_CORE.SNAPNTAITG_INTEGRATION.ITG_POS_CUST_PROD_CD_EAN_MAP"
                name: TRATBL_sdl_tw_as_watsons_inventory__lookup_test
                config:
                  store_failures: true
                  schema: ntawks_integration 
      - name: sdl_tw_sfmc_complaint_data
        tags: ["tw_sfmc","ingestion"]
        tests:
        - test_null:
            select_columns: ["job_id","batch_id","subscriber_id","subscriber_key","email_id","file_name"]
            not_null_columns: ["job_id","batch_id","subscriber_id","subscriber_key","email_id","file_name"]
            name: TRATBL_sdl_tw_sfmc_complaint_data__null_test
            config:
              store_failures: true
              schema: myswks_integration
        - test_duplicate:
                select_columns:  ["job_id","batch_id","subscriber_id","subscriber_key","email_id","file_name"]
                group_by_columns: ["job_id","batch_id","subscriber_id","subscriber_key","email_id","file_name"]
                name: TRATBL_sdl_tw_sfmc_complaint_data__duplicate_test
                config:
                  store_failures: true
                  schema: myswks_integration
      - name: sdl_tw_sfmc_unsubscribe_data
        tags: ["tw_sfmc","ingestion"]
        tests:
        - test_null:
            select_columns: ["job_id","batch_id","subscriber_id","subscriber_key","email_id","file_name"]
            not_null_columns: ["job_id","batch_id","subscriber_id","subscriber_key","email_id","file_name"]
            name: TRATBL_sdl_tw_sfmc_unsubscribe_data__null_test
            config:
              store_failures: true
              schema: myswks_integration
        - test_duplicate:
                select_columns: ["job_id","batch_id","subscriber_id","subscriber_key","email_id","event_date","file_name"]
                group_by_columns: ["job_id","batch_id","subscriber_id","subscriber_key","email_id","event_date","file_name"]
                name: TRATBL_sdl_tw_sfmc_unsubscribe_data__duplicate_test
                config:
                  store_failures: true
                  schema: myswks_integration