with sdl_prox_report_bi_payment as
(
    select * from {{source('aspsdl_raw', 'sdl_prox_report_bi_payment')}}
),
final as
(
    select
    rowid::number(38,0) as rowid,
	budgetyear::number(38,0) as budgetyear,
	paymentno::varchar(50) as paymentno,
	paymentstatus::varchar(255) as paymentstatus,
	accountgroupcode::varchar(50) as accountgroupcode,
	accountgroupname::varchar(1000) as accountgroupname,
	paytocode::varchar(50) as paytocode,
	paytoname::varchar(1000) as paytoname,
	expensesubcategory::varchar(255) as expensesubcategory,
	paymenttitle::varchar(4000) as paymenttitle,
	reverseno::varchar(50) as reverseno,
	oldreverseno::varchar(50) as oldreverseno,
	invoicenumber::varchar(200) as invoicenumber,
	invoicetype::varchar(255) as invoicetype,
	sapdocnumber::varchar(50) as sapdocnumber,
	sapdocdate::timestamp_ntz(9) as sapdocdate,
	paymentmethod::varchar(255) as paymentmethod,
	paymentamountwithouttax::number(18,2) as paymentamountwithouttax,
	invoiceamountwithouttax::number(18,2) as invoiceamountwithouttax,
	vatcode::varchar(50) as vatcode,
	vatamount::number(18,2) as vatamount,
	whtcode::varchar(50) as whtcode,
	whtamount::number(18,2) as whtamount,
	amountpayable::number(18,2) as amountpayable,
	supportingdocuments::varchar(4000) as supportingdocuments,
	currentapprovaluser::varchar(4000) as currentapprovaluser,
	rejectreason::varchar(4000) as rejectreason,
	contractno::varchar(50) as contractno,
	contractnotemp::varchar(50) as contractnotemp,
	themecode::varchar(50) as themecode,
	themename::varchar(1000) as themename,
	expenserevenuerecognitionstartdate::timestamp_ntz(9) as expenserevenuerecognitionstartdate,
	expenserevenuerecognitionenddate::timestamp_ntz(9) as expenserevenuerecognitionenddate,
	expensepromoexecutionstartdate::timestamp_ntz(9) as expensepromoexecutionstartdate,
	expensepromoexecutionenddate::timestamp_ntz(9) as expensepromoexecutionenddate,
	paymentstartdate::timestamp_ntz(9) as paymentstartdate,
	paymentenddate::timestamp_ntz(9) as paymentenddate,
	autoallocate::varchar(50) as autoallocate,
	parked::varchar(50) as parked,
	payfromaccrual::varchar(50) as payfromaccrual,
	accrualglaccount::varchar(50) as accrualglaccount,
	glaccount::varchar(50) as glaccount,
	expensetypename::varchar(1000) as expensetypename,
	profitcenter::varchar(1000) as profitcenter,
	materialcode::varchar(50) as materialcode,
	materialname::varchar(1000) as materialname,
	contractoriginalamount::number(18,2) as contractoriginalamount,
	contractavailabletopay::number(18,2) as contractavailabletopay,
	plannedbalance::number(18,2) as plannedbalance,
	saprebateno::varchar(50) as saprebateno,
	rebatesettlementno::varchar(50) as rebatesettlementno,
	sapcmno::varchar(50) as sapcmno,
	sapcmdate::timestamp_ntz(9) as sapcmdate,
	contractstatus::varchar(255) as contractstatus,
	contractdetailstatus::varchar(50) as contractdetailstatus,
	createuser::varchar(255) as createuser,
	createtime::timestamp_ntz(9) as createtime,
	applicant::varchar(255) as applicant,
	applicantdate::timestamp_ntz(9) as applicantdate,
	approvedate::timestamp_ntz(9) as approvedate,
	postingdate::timestamp_ntz(9) as postingdate,
	postingperiod::varchar(50) as postingperiod,
	fillingid::varchar(1000) as fillingid,
	budgetowner::varchar(1000) as budgetowner,
	channel::varchar(50) as channel,
	rtmchannel::varchar(255) as rtmchannel,
	endtoendleadtime::number(38,0) as endtoendleadtime,
	salesinputleadtime::number(38,0) as salesinputleadtime,
	salesapprovalleadtime::number(38,0) as salesapprovalleadtime,
	mrc::varchar(50) as mrc,
	printatddate::timestamp_ntz(9) as printatddate,
	invoicenovat::varchar(50) as invoicenovat,
	invoicenowht::varchar(50) as invoicenowht,
	businesstaxcode::varchar(50) as businesstaxcode,
	businesstaxamount::number(18,2) as businesstaxamount,
	businesstax::varchar(50) as businesstax,
	applicationid::varchar(50) as applicationid,
	expenseid::varchar(50) as expenseid,
	contracttitle::varchar(1000) as contracttitle,
	filename::varchar(100) as filename,
	run_id::varchar(50) as run_id,
	crt_dttm::timestamp_ntz(9) as crt_dttm
    from sdl_prox_report_bi_payment
)
select * from final