with wks_mngmnt_rpt_tdp as 
(
    select * from indwks_integration.wks_mngmnt_rpt_tdp
),
wks_mngmnt_sales_hit_nr as 
(
    select * from indwks_integration.wks_mngmnt_sales_hit_nr
),
pf_weekly_os_perc_actual_logic_sm as
(
    select * from indwks_integration.pf_weekly_os_perc_actual_logic_sm
    --{{ ref('indwks_integration__pf_weekly_os_perc_actual_logic_sm') }}
),
wks_sku_recom_spike_msl_mthly_analytics as 
(
    select * from indwks_integration.wks_sku_recom_spike_msl_mthly_analytics
),
wks_mngmnt_rpt_nup_l3m_with_os as 
(
    select * from indwks_integration.wks_mngmnt_rpt_nup_l3m_with_os
),
final as
(
    SELECT 'SKU_RECOM_TDP' as dataset,
        mth_mm,
        region_name,
        zone_name,
        territory_name,
        null as cust_cd,
        null as salesman_code,
        null as salesman_name,
        null as unique_sales_code,
        channel_name,
        class_desc,
        retailer_channel_level_3,
        franchise_name,
        brand_name,
        product_category_name,
        variant_name,
        mothersku_name,
        total_stores,
        total_recos,
        total_hits,
        null as total_os,
        null as total_os_perc,
        null as store_tag,
        null as os_week0,
        null as os_week1,
        null as os_week2,
        null as os_week3,
        null as os_week4,
        null as os_week5,
        null as os_perc_week0,
        null as os_perc_week1,
        null as os_perc_week2,
        null as os_perc_week3,
        null as os_perc_week4,
        null as os_perc_week5,
        null as achievement_nr_all_msku,
        null as achievement_nr_msl_msku,
        convert_timezone('UTC',current_timestamp()) as crt_dttm,
        convert_timezone('UTC',current_timestamp()) as updt_dttm,
        null as week,
        null as retailer_cd,
        null as quantity,
        null as ret_msku,
        null as ms_flag,
        null as os_flag
    FROM wks_mngmnt_rpt_tdp

    UNION ALL

    SELECT 'SKU_RECOM_ACHNR' as dataset,
        mth_mm,
        region_name,
        zone_name,
        territory_name,
        null as cust_cd,
        null as salesman_code,
        null as salesman_name,
        null as unique_sales_code,
        channel_name,
        class_desc,
        retailer_channel_level_3,
        franchise_name,
        brand_name,
        product_category_name,
        variant_name,
        null as mothersku_name,
        null as total_stores,
        null as total_recos,
        null as total_hits,
        null as total_os,
        null as total_os_perc,
        null as store_tag,
        null as os_week0,
        null as os_week1,
        null as os_week2,
        null as os_week3,
        null as os_week4,
        null as os_week5,
        null as os_perc_week0,
        null as os_perc_week1,
        null as os_perc_week2,
        null as os_perc_week3,
        null as os_perc_week4,
        null as os_perc_week5,
        achievement_nr_all_msku,
        achievement_nr_msl_msku,
        convert_timezone('UTC',current_timestamp()) as crt_dttm,
        convert_timezone('UTC',current_timestamp()) as updt_dttm,
        null as week,
        null as retailer_cd,
        null as quantity,
        null as ret_msku,
        null as ms_flag,
        null as os_flag
    FROM wks_mngmnt_sales_hit_nr

    UNION ALL

    SELECT 'SKU_RECOM_WEEKLY_OS' as dataset,
        mnth_id::integer as mth_mm,
        region_name,
        zone_name,
        territory_name,
        cust_cd,
        salesman_code,
        salesman_name,
        unique_sales_code,
        channel_name,
        class_desc,
        retailer_channel_level_3,
        null as franchise_name,
        null as brand_name,
        null as product_category_name,
        null as variant_name,
        null as mothersku_name,
        total_stores,
        null as total_recos,
        null as total_hits,
        os_week5 as total_os,
        os_perc_week5 as total_os_perc,
        null as store_tag,
        os_week0,
        os_week1,
        os_week2,
        os_week3,
        os_week4,
        os_week5,
        os_perc_week0,
        os_perc_week1,
        os_perc_week2,
        os_perc_week3,
        os_perc_week4,
        os_perc_week5,
        null as achievement_nr_all_msku,
        null as achievement_nr_msl_msku,
        convert_timezone('UTC',current_timestamp()) as crt_dttm,
        convert_timezone('UTC',current_timestamp()) as updt_dttm,
        null as week,
        null as retailer_cd,
        null as quantity,
        null as ret_msku,
        null as ms_flag,
        null as os_flag
    FROM pf_weekly_os_perc_actual_logic_sm

    UNION ALL

    SELECT 'SKU_RECOM_MONTHLY_OS' as dataset,
        mth_mm,
        null as region_name,
        null as zone_name,
        null as territory_name,
        null as cust_cd,
        null as salesman_code,
        null as salesman_name,
        null as unique_sales_code,
        null as channel_name,
        null as class_desc,
        null as retailer_channel_level_3,
        null as franchise_name,
        null as brand_name,
        null as product_category_name,
        null as variant_name,
        null as mothersku_name,
        count_of_retailers as total_stores,
        recos as total_recos,
        hits as total_hits,
        no_of_orange_stores as total_os,
        orange_store_perc as total_os_perc,
        store_tag,
        null as os_week0,
        null as os_week1,
        null as os_week2,
        null as os_week3,
        null as os_week4,
        null as os_week5,
        null as os_perc_week0,
        null as os_perc_week1,
        null as os_perc_week2,
        null as os_perc_week3,
        null as os_perc_week4,
        null as os_perc_week5,
        null as achievement_nr_all_msku,
        null as achievement_nr_msl_msku,
        convert_timezone('UTC',current_timestamp()) as crt_dttm,
        convert_timezone('UTC',current_timestamp()) as updt_dttm,
        null as week,
        null as retailer_cd,
        null as quantity,
        null as ret_msku,
        null as ms_flag,
        null as os_flag
    FROM wks_sku_recom_spike_msl_mthly_analytics

    UNION ALL

    SELECT 'SKU_RECOM_UNIQUEPACK_MTHLY_L3M' as dataset,
        mth_mm,
        region_name,
        zone_name,
        territory_name,
        customer_code as cust_cd,
        null as salesman_code,
        null as salesman_name,
        null as unique_sales_code,
        channel_name,
        null as class_desc,
        null as retailer_channel_level_3,
        franchise_name,
        brand_name,
        product_category_name,
        variant_name,
        mothersku_name,
        null as total_stores,
        null as total_recos,
        null as total_hits,
        null as total_os,
        null as total_os_perc,
        null as store_tag,
        null as os_week0,
        null as os_week1,
        null as os_week2,
        null as os_week3,
        null as os_week4,
        null as os_week5,
        null as os_perc_week0,
        null as os_perc_week1,
        null as os_perc_week2,
        null as os_perc_week3,
        null as os_perc_week4,
        null as os_perc_week5,
        achievement_nr as achievement_nr_all_msku,
        null as achievement_nr_msl_msku,
        convert_timezone('UTC',current_timestamp()) as crt_dttm,
        convert_timezone('UTC',current_timestamp()) as updt_dttm,
        null as week,
        retailer_code as retailer_cd,
        null as quantity,
        ret_msku,
        ms_flag,
        os_flag
    FROM wks_mngmnt_rpt_nup_l3m_with_os
)
select dataset::varchar(50) as dataset,
        mth_mm::number(18,0) as mth_mm,
        region_name::varchar(200) as region_name,
        zone_name::varchar(200) as zone_name,
        territory_name::varchar(200) as territory_name,
        cust_cd::varchar(50) as cust_cd,
        salesman_code::varchar(50) as salesman_code,
        salesman_name::varchar(200) as salesman_name,
        unique_sales_code::varchar(50) as unique_sales_code,
        channel_name::varchar(50) as channel_name,
        class_desc::varchar(50) as class_desc,
        retailer_channel_level_3::varchar(200) as retailer_channel_level_3,
        franchise_name::varchar(255) as franchise_name,
        brand_name::varchar(255) as brand_name,
        product_category_name::varchar(255) as product_category_name,
        variant_name::varchar(255) as variant_name,
        mothersku_name::varchar(255) as mothersku_name,
        total_stores::number(18,0) as total_stores,
        total_recos::number(18,0) as total_recos,
        total_hits::number(18,0) as total_hits,
        total_os::number(18,0) as total_os,
        total_os_perc::number(6,2) as total_os_perc,
        store_tag::varchar(200) as store_tag,
        os_week0::number(18,0) as os_week0,
        os_week1::number(18,0) as os_week1,
        os_week2::number(18,0) as os_week2,
        os_week3::number(18,0) as os_week3,
        os_week4::number(18,0) as os_week4,
        os_week5::number(18,0) as os_week5,
        os_perc_week0::number(6,2) as os_perc_week0,
        os_perc_week1::number(6,2) as os_perc_week1,
        os_perc_week2::number(6,2) as os_perc_week2,
        os_perc_week3::number(6,2) as os_perc_week3,
        os_perc_week4::number(6,2) as os_perc_week4,
        os_perc_week5::number(6,2) as os_perc_week5,
        achievement_nr_all_msku::number(38,4) as achievement_nr_all_msku,
        achievement_nr_msl_msku::number(38,4) as achievement_nr_msl_msku,
        crt_dttm::timestamp_ntz(9) as crt_dttm,
        updt_dttm::timestamp_ntz(9) as updt_dttm,
        week::number(18,0) as week,
        retailer_cd::varchar(100) as retailer_cd,
        quantity::number(38,0) as quantity,
        ret_msku::varchar(255) as ret_msku,
        ms_flag::varchar(1) as ms_flag,
        os_flag::varchar(10) as os_flag
 from final