with source as(
    select * from {{ source('jpnsdl_raw', 'sdl_mds_jp_mt_so_rtlr_chg') }}   
),

result as(
    select
        ID::NUMBER(18,0) as ID,
	    MUID::VARCHAR(36) as MUID,
	    VERSIONNAME::VARCHAR(100) as VERSIONNAME,
	    VERSIONNUMBER::NUMBER(18,0) as VERSIONNUMBER,
	    VERSION_ID::NUMBER(18,0) as VERSION_ID,
	    VERSIONFLAG::VARCHAR(100) as VERSIONFLAG,
	    NAME::VARCHAR(500) as NAME,
	    CODE::VARCHAR(500) as CODE,
	    CHANGETRACKINGMASK::NUMBER(18,0) as CHANGETRACKINGMASK,
	    BGN_SNDR_CD::VARCHAR(200) as BGN_SNDR_CD,
	    RTLR_CD::VARCHAR(200) as RTLR_CD,
	    RTLR_NAME::VARCHAR(200) as RTLR_NAME,
	    STR_CD::VARCHAR(200) as STR_CD,
	    ERROR_TYPE::NUMBER(28,0) as ERROR_TYPE,
	    ENTERDATETIME::TIMESTAMP_NTZ(9) as ENTERDATETIME,
	    ENTERUSERNAME::VARCHAR(200) as ENTERUSERNAME,
	    ENTERVERSIONNUMBER::NUMBER(18,0) as ENTERVERSIONNUMBER,
	    LASTCHGDATETIME::TIMESTAMP_NTZ(9) as LASTCHGDATETIME,
	    LASTCHGUSERNAME::VARCHAR(200) as LASTCHGUSERNAME,
	    LASTCHGVERSIONNUMBER::NUMBER(18,0) as LASTCHGVERSIONNUMBER,
	    VALIDATIONSTATUS::VARCHAR(500) as VALIDATIONSTATUS,
        current_timestamp::timestamp_ntz(9) as create_date
    from source
)

select * from result