{{
    config(
        materialized= "incremental",
        incremental_strategy= "append",
        pre_hook = "{% if is_incremental() %}
                delete from {{this}} where diorderhistid in (select diorderhistid from {{ source('jpdclsdl_raw', 'c_tbeckesaihistory') }}) AND c_dikesaiid in (select c_dikesaiid from {{ source('jpdclsdl_raw', 'c_tbeckesaihistory') }});
                    {% endif %}"
    )
}}

with source as(
    select * from {{ source('jpdclsdl_raw', 'c_tbeckesaihistory') }}
),
final as(
    select 
        diorderhistid::number(38,0) as diorderhistid,
        c_dikesaiid::number(38,0) as c_dikesaiid,
        diorderid::number(38,0) as diorderid,
        diecusrid::number(38,0) as diecusrid,
        dishukkasts::varchar(6) as dishukkasts,
        disokoid::number(38,0) as disokoid,
        dsuriagedt::timestamp_ntz(9) as dsuriagedt,
        dinyukinsts::varchar(1) as dinyukinsts,
        dicardnyukinsts::varchar(1) as dicardnyukinsts,
        dsnyukindt::timestamp_ntz(9) as dsnyukindt,
        direnkeists::varchar(1) as direnkeists,
        dicancel::varchar(1) as dicancel,
        c_dsexchangeflg::varchar(1) as c_dsexchangeflg,
        c_dshoryutypekbn::varchar(1) as c_dshoryutypekbn,
        dihoryu::varchar(1) as dihoryu,
        c_dsshorttodokedate::timestamp_ntz(9) as c_dsshorttodokedate,
        c_dsshortdeliverytime::varchar(3) as c_dsshortdeliverytime,
        c_dstodokedate::timestamp_ntz(9) as c_dstodokedate,
        c_dsdeliverytime::varchar(3) as c_dsdeliverytime,
        dstodokesei::varchar(30) as dstodokesei,
        dstodokemei::varchar(30) as dstodokemei,
        dstodokeseikana::varchar(30) as dstodokeseikana,
        dstodokemeikana::varchar(30) as dstodokemeikana,
        dstodokezip::varchar(15) as dstodokezip,
        c_dstodokeprefcd::varchar(3) as c_dstodokeprefcd,
        dstodokepref::varchar(15) as dstodokepref,
        dstodokecity::varchar(108) as dstodokecity,
        dstodokeaddr::varchar(90) as dstodokeaddr,
        dstodoketatemono::varchar(90) as dstodoketatemono,
        dstodokeaddrkana::varchar(3072) as dstodokeaddrkana,
        dstodoketel::varchar(24) as dstodoketel,
        dstodokefax::varchar(24) as dstodokefax,
        dibillincluded::varchar(1) as dibillincluded,
        dihaisokeitai::number(38,0) as dihaisokeitai,
        c_dstodaydeliveryflg::varchar(1) as c_dstodaydeliveryflg,
        c_dsshukkadate::timestamp_ntz(9) as c_dsshukkadate,
        dskessaihoho::varchar(3) as dskessaihoho,
        c_dicardid::number(38,0) as c_dicardid,
        dspaymentclass::varchar(3) as dspaymentclass,
        c_dsdividetimes::number(38,0) as c_dsdividetimes,
        c_dsgmoorderid::varchar(40) as c_dsgmoorderid,
        dicardtradeid::varchar(384) as dicardtradeid,
        dicardtradepass::varchar(384) as dicardtradepass,
        dicardsts::varchar(3) as dicardsts,
        dicardcancel::varchar(1) as dicardcancel,
        diauthprc::number(38,0) as diauthprc,
        dsauthdt::timestamp_ntz(9) as dsauthdt,
        dscarddt::timestamp_ntz(9) as dscarddt,
        dicardcancelprc::number(38,0) as dicardcancelprc,
        c_dsacceptno::varchar(21) as c_dsacceptno,
        c_dinptransactionid::number(38,0) as c_dinptransactionid,
        c_dioldnptransactionid1::number(38,0) as c_dioldnptransactionid1,
        c_dioldnptransactionid2::number(38,0) as c_dioldnptransactionid2,
        c_dspaymentflg::varchar(1) as c_dspaymentflg,
        ditotalprc::number(38,0) as ditotalprc,
        c_didiscountprc::number(38,0) as c_didiscountprc,
        c_didiscountall::number(38,0) as c_didiscountall,
        diordertax::number(38,0) as diordertax,
        dihaisoprc::number(38,0) as dihaisoprc,
        c_dicollectprc::number(38,0) as c_dicollectprc,
        c_ditoujitsuhaisoprc::number(38,0) as c_ditoujitsuhaisoprc,
        diseikyuprc::number(38,0) as diseikyuprc,
        c_diregdiscticketprc::number(38,0) as c_diregdiscticketprc,
        dinyukinprc::number(38,0) as dinyukinprc,
        diseikyuremain::number(38,0) as diseikyuremain,
        dihenkinzumiprc::number(38,0) as dihenkinzumiprc,
        c_dsdiffprckbn::varchar(1) as c_dsdiffprckbn,
        diusepoint::number(38,0) as diusepoint,
        c_diexchangepoint::number(38,0) as c_diexchangepoint,
        c_diorderavailablepoint::number(38,0) as c_diorderavailablepoint,
        c_dikakutokuyoteipoint::number(38,0) as c_dikakutokuyoteipoint,
        c_dsnoshinshomemo::varchar(3000) as c_dsnoshinshomemo,
        c_dsnohinshoautomemo::varchar(3000) as c_dsnohinshoautomemo,
        c_dsokurijomemo::varchar(3000) as c_dsokurijomemo,
        c_dsnmemoerrflg::varchar(1) as c_dsnmemoerrflg,
        c_dsomemoerrflg::varchar(1) as c_dsomemoerrflg,
        divouchercode::varchar(768) as divouchercode,
        c_dscctraceurl::varchar(768) as c_dscctraceurl,
        c_dsusrtanmatsukbn::varchar(1) as c_dsusrtanmatsukbn,
        c_dsusrtraceurl::varchar(768) as c_dsusrtraceurl,
        c_dspickingclasskbn::varchar(3) as c_dspickingclasskbn,
        c_dspointdate1::varchar(21) as c_dspointdate1,
        c_dspointdate2::varchar(21) as c_dspointdate2,
        c_dspointdate3::varchar(21) as c_dspointdate3,
        c_dipoint1::number(38,0) as c_dipoint1,
        c_dipoint2::number(38,0) as c_dipoint2,
        c_dipoint3::number(38,0) as c_dipoint3,
        c_dsregularnum::number(38,0) as c_dsregularnum,
        c_dsreizoreitokubun::varchar(1) as c_dsreizoreitokubun,
        c_dsrikusokubun::varchar(1) as c_dsrikusokubun,
        c_dspostshipflg::varchar(1) as c_dspostshipflg,
        c_dsreservepostshipflg::varchar(1) as c_dsreservepostshipflg,
        c_dsnonshipmailflg::varchar(1) as c_dsnonshipmailflg,
        c_dsreserveflg::varchar(1) as c_dsreserveflg,
        c_dsfreekbn::varchar(1) as c_dsfreekbn,
        c_dsnptorokusts::varchar(3) as c_dsnptorokusts,
        c_dsnpsyuseists::varchar(3) as c_dsnpsyuseists,
        c_dsnpcancelsts::varchar(3) as c_dsnpcancelsts,
        c_dsnpshukkasts::varchar(3) as c_dsnpshukkasts,
        c_dsnpsaitorokusts::varchar(3) as c_dsnpsaitorokusts,
        c_dsrakutenuriagests::varchar(3) as c_dsrakutenuriagests,
        c_dsnpprintdatagetflg::varchar(1) as c_dsnpprintdatagetflg,
        dsprep::timestamp_ntz(9) as dsprep,
        dsren::timestamp_ntz(9) as dsren,
        dselim::timestamp_ntz(9) as dselim,
        diprepusr::number(38,0) as diprepusr,
        direnusr::number(38,0) as direnusr,
        dielimusr::number(38,0) as dielimusr,
        dielimflg::varchar(1) as dielimflg,
        c_dishukkashijicondid::number(38,0) as c_dishukkashijicondid,
        c_diadjustprc::number(38,0) as c_diadjustprc,
        c_dicardtypekbn::varchar(1) as c_dicardtypekbn,
        c_dihenkinprcinputdiff::number(38,0) as c_dihenkinprcinputdiff,
        c_dihenkinprcinputdifftotal::number(38,0) as c_dihenkinprcinputdifftotal,
        c_dsrakutengmoorderid::varchar(40) as c_dsrakutengmoorderid,
        c_dirakutencardtradeid::varchar(384) as c_dirakutencardtradeid,
        c_dirakutencardtradepass::varchar(384) as c_dirakutencardtradepass,
        c_dsrakutensyuseists::varchar(3) as c_dsrakutensyuseists,
        c_dsrakutencancelsts::varchar(3) as c_dsrakutencancelsts,
        ditodokeid::number(38,0) as ditodokeid,
        c_dsgmoshoptransactionid::varchar(75) as c_dsgmoshoptransactionid,
        c_dsgmotransactionid::varchar(16) as c_dsgmotransactionid,
        c_dsgmoauthprckbn::varchar(3) as c_dsgmoauthprckbn,
        c_dsgmotransactionsts::varchar(3) as c_dsgmotransactionsts,
        source_file_date::varchar(10) as source_file_date,
		current_timestamp()::timestamp_ntz(9) as inserted_date,
		inserted_by::varchar(100) as inserted_by,
		current_timestamp()::timestamp_ntz(9) as updated_date,
		updated_by::varchar(100) as updated_by
    from source
)
select * from final