{{
    config
    (
        materialized='incremental',
        incremental_strategy= 'append',
        pre_hook = "{% if is_incremental() %}
                    DELETE FROM {{this}} WHERE DIORDERID IN (SELECT DIORDERID FROM {{ source('jpdclsdl_raw', 'tbecorder') }});
                    {% endif %}",
        post_hook = "
                    UPDATE {{this}} SET C_DSUKETSUKETELCOMPANYCD = 'TNP', updated_date = GETDATE(), updated_by = 'ETL_Batch' WHERE C_DSUKETSUKETELCOMPANYCD = 'DCL' AND C_DSTEMPOCODE IS NOT NULL;
                    UPDATE {{this}} SET C_DSUKETSUKETELCOMPANYCD = 'WEB', updated_date = GETDATE(), updated_by = 'ETL_Batch' WHERE C_DSUKETSUKETELCOMPANYCD = 'DCL' AND dirouteid = '5';
                    UPDATE {{this}} SET C_DSUKETSUKETELCOMPANYCD = 'FAX', updated_date = GETDATE(), updated_by = 'ETL_Batch' WHERE C_DSUKETSUKETELCOMPANYCD = 'DCL' AND dirouteid = '3';
                    UPDATE {{this}} SET C_DSUKETSUKETELCOMPANYCD = 'MAL', updated_date = GETDATE(), updated_by = 'ETL_Batch' WHERE C_DSUKETSUKETELCOMPANYCD = 'DCL' AND dirouteid = '4';
                    UPDATE {{this}} SET C_DSUKETSUKETELCOMPANYCD = 'SHN', updated_date = GETDATE(), updated_by = 'ETL_Batch' WHERE C_DSUKETSUKETELCOMPANYCD = 'DCL' AND dirouteid = '6';
                    "
    )
}}

with source as
(
    select * from {{ source('jpdclsdl_raw', 'tbecorder') }}
),

final as
(
    select 
		diorderid::number(38,0) as diorderid,
		diordercode::varchar(18) as diordercode,
		diecusrid::number(38,0) as diecusrid,
		dssei::varchar(30) as dssei,
		dsmei::varchar(30) as dsmei,
		dsseikana::varchar(30) as dsseikana,
		dsmeikana::varchar(30) as dsmeikana,
		c_dimembtype::varchar(3) as c_dimembtype,
		ditodokeid::number(38,0) as ditodokeid,
		dstodokesei::varchar(30) as dstodokesei,
		dstodokemei::varchar(30) as dstodokemei,
		dstodokeseikana::varchar(30) as dstodokeseikana,
		dstodokemeikana::varchar(30) as dstodokemeikana,
		dstodokezip::varchar(15) as dstodokezip,
		c_dstodokeprefcd::varchar(3) as c_dstodokeprefcd,
		dstodokepref::varchar(15) as dstodokepref,
		dstodokecity::varchar(108) as dstodokecity,
		dstodokeaddr::varchar(90) as dstodokeaddr,
		dstodoketatemono::varchar(90) as dstodoketatemono,
		dstodokeaddrkana::varchar(3072) as dstodokeaddrkana,
		dstodoketel::varchar(24) as dstodoketel,
		dstodokefax::varchar(24) as dstodokefax,
		dipromid::number(38,0) as dipromid,
		dirouteid::number(38,0) as dirouteid,
		dsorderdt::timestamp_ntz(9) as dsorderdt,
		c_dskeiyaktodokedate::timestamp_ntz(9) as c_dskeiyaktodokedate,
		ditotalprc::number(38,0) as ditotalprc,
		dihaisoprc::number(38,0) as dihaisoprc,
		ditaxrate::number(38,0) as ditaxrate,
		c_dsreserveflg::varchar(1) as c_dsreserveflg,
		diusepoint::number(38,0) as diusepoint,
		c_diintroducepointflg::varchar(1) as c_diintroducepointflg,
		c_diintroduceid::number(38,0) as c_diintroduceid,
		dipoint::number(38,0) as dipoint,
		dimonthlypoint::number(38,0) as dimonthlypoint,
		diavailablepoint::number(38,0) as diavailablepoint,
		dihoryu::varchar(1) as dihoryu,
		c_dshoryuriyumemo::varchar(1500) as c_dshoryuriyumemo,
		dicancel::varchar(1) as dicancel,
		dishukkasts::varchar(6) as dishukkasts,
		dsuriagedt::timestamp_ntz(9) as dsuriagedt,
		dsordermemo::varchar(768) as dsordermemo,
		c_dikakutokuyoteipoint::number(38,0) as c_dikakutokuyoteipoint,
		c_dsorderkbn::varchar(1) as c_dsorderkbn,
		c_dsdosokbn::varchar(3) as c_dsdosokbn,
		c_diallhenpinflg::varchar(1) as c_diallhenpinflg,
		c_dshaisoshikibetsukbn::varchar(1) as c_dshaisoshikibetsukbn,
		diordertax::number(38,0) as diordertax,
		c_didiscountprc::number(38,0) as c_didiscountprc,
		c_didiscountall::number(38,0) as c_didiscountall,
		diseikyuprc::number(38,0) as diseikyuprc,
		dinyukinprc::number(38,0) as dinyukinprc,
		diseikyuremain::number(38,0) as diseikyuremain,
		dihenkinzumiprc::number(38,0) as dihenkinzumiprc,
		dihaisokeitai::number(38,0) as dihaisokeitai,
		c_dstorikomiid::varchar(15) as c_dstorikomiid,
		c_dsorderimportdate::timestamp_ntz(9) as c_dsorderimportdate,
		c_diuketsukeusrid::number(38,0) as c_diuketsukeusrid,
		c_dsuketsuketelcompanycd::varchar(4) as c_dsuketsuketelcompanycd,
		c_dsuketsukeusrname::varchar(48) as c_dsuketsukeusrname,
		c_diinputusrid::number(38,0) as c_diinputusrid,
		c_dsinputusrname::varchar(48) as c_dsinputusrname,
		c_dsinputtelcompanycd::varchar(4) as c_dsinputtelcompanycd,
		c_dilastupdusrid::number(38,0) as c_dilastupdusrid,
		c_dslastupdusrname::varchar(48) as c_dslastupdusrname,
		c_dslastupdtelcompanycd::varchar(4) as c_dslastupdtelcompanycd,
		c_dipendingstsid::number(38,0) as c_dipendingstsid,
		c_dspendingcorrdate::timestamp_ntz(9) as c_dspendingcorrdate,
		c_dsdeliveryfreeflg::varchar(1) as c_dsdeliveryfreeflg,
		c_dscollectfreeflg::varchar(1) as c_dscollectfreeflg,
		c_dicollectprc::number(38,0) as c_dicollectprc,
		c_ditoujitsuhaisoprc::number(38,0) as c_ditoujitsuhaisoprc,
		c_diclassid::number(38,0) as c_diclassid,
		c_dsusrsts::varchar(3) as c_dsusrsts,
		c_dspointitemincludeflg::varchar(1) as c_dspointitemincludeflg,
		c_diranktargetprc::number(38,0) as c_diranktargetprc,
		c_diranktotalprc::number(38,0) as c_diranktotalprc,
		c_dipaymentprc::number(38,0) as c_dipaymentprc,
		c_diordernum::number(38,0) as c_diordernum,
		c_diordersamplenum::number(38,0) as c_diordersamplenum,
		c_dsorderreferdate::timestamp_ntz(9) as c_dsorderreferdate,
		c_diregdiscticketprc::number(38,0) as c_diregdiscticketprc,
		c_dsregularautocreateflg::varchar(1) as c_dsregularautocreateflg,
		c_diexchangepoint::number(38,0) as c_diexchangepoint,
		c_dspointtargetprc::number(38,0) as c_dspointtargetprc,
		c_dsrewriteno::varchar(12) as c_dsrewriteno,
		c_dspotsalesno::varchar(25) as c_dspotsalesno,
		c_dstempocode::varchar(7) as c_dstempocode,
		c_dstemponame::varchar(192) as c_dstemponame,
		c_dstenposalesno::varchar(16) as c_dstenposalesno,
		c_dsorigpotsalesno::varchar(25) as c_dsorigpotsalesno,
		c_dsupdateflg::varchar(1) as c_dsupdateflg,
		c_dsfreekbn::varchar(1) as c_dsfreekbn,
		c_dsdeliverydemandflg::varchar(1) as c_dsdeliverydemandflg,
		c_dstoujitsuhaisofreeflg::varchar(1) as c_dstoujitsuhaisofreeflg,
		dibillincluded::varchar(1) as dibillincluded,
		dspackageflg::varchar(1) as dspackageflg,
		c_dssamplelogicd::varchar(3) as c_dssamplelogicd,
		dsprep::timestamp_ntz(9) as dsprep,
		dsren::timestamp_ntz(9) as dsren,
		dselim::timestamp_ntz(9) as dselim,
		diprepusr::number(38,0) as diprepusr,
		direnusr::number(38,0) as direnusr,
		dielimusr::number(38,0) as dielimusr,
		dielimflg::varchar(1) as dielimflg,
		c_diyoyakuhenpinflg::varchar(1) as c_diyoyakuhenpinflg,
		c_dsordercompmailsendkbn::varchar(1) as c_dsordercompmailsendkbn,
		c_diadjustprc::number(38,0) as c_diadjustprc,
		c_dihenkinprcinputdiff::number(38,0) as c_dihenkinprcinputdiff,
		c_dihenkinprcinputdifftotal::number(38,0) as c_dihenkinprcinputdifftotal,
		c_diadjustpoint::number(38,0) as c_diadjustpoint,
		null::varchar(10) as source_file_date,
		inserted_date::timestamp_ntz(9) as inserted_date,
		null::varchar(10) as inserted_by,
		updated_date::timestamp_ntz(9) as updated_date,
		null::varchar(100) as updated_by
    from source
)

select * from final