{{
    config(
        materialized= "incremental",
        incremental_strategy= "append",
        pre_hook = "{% if is_incremental() %}
            delete from {{this}} where c_dsregularoperatehistid in (select c_dsregularoperatehistid from {{ source('jpdclsdl_raw', 'c_tbecregularoperatehist') }});
                    {% endif %}"
    )
}}

with source as(
    select * from {{ source('jpdclsdl_raw', 'c_tbecregularoperatehist') }}
),
final as(
    select 
        c_dsregularoperatehistid::number(10,0) as c_dsregularoperatehistid,
        c_dsregularoperatedate::timestamp_ntz(9) as c_dsregularoperatedate,
        c_dschgtargetkbn::varchar(2) as c_dschgtargetkbn,
        c_dshaneikikankbn::varchar(2) as c_dshaneikikankbn,
        c_dshaneiunitkbn::varchar(2) as c_dshaneiunitkbn,
        c_dsregularmemo::varchar(2000) as c_dsregularmemo,
        c_diinputusrid::number(10,0) as c_diinputusrid,
        c_dsinputusrname::varchar(240) as c_dsinputusrname,
        c_dsinputtelcompanycd::varchar(3) as c_dsinputtelcompanycd,
        c_dsregularmeisaiid::number(10,0) as c_dsregularmeisaiid,
        c_dsdeleveryym::varchar(6) as c_dsdeleveryym,
        c_dstodokedate::timestamp_ntz(9) as c_dstodokedate,
        c_diregularcontractid::number(10,0) as c_diregularcontractid,
        c_diusrid::number(10,0) as c_diusrid,
        c_diregularcontractdate::timestamp_ntz(9) as c_diregularcontractdate,
        dirouteid::number(2,0) as dirouteid,
        diid::number(10,0) as diid,
        dsitemid::varchar(30) as dsitemid,
        c_dipromid::number(10,0) as c_dipromid,
        c_diregularcourseid::number(10,0) as c_diregularcourseid,
        ditodokeid::number(10,0) as ditodokeid,
        dstodokesei::varchar(50) as dstodokesei,
        dstodokemei::varchar(50) as dstodokemei,
        dstodokeseikana::varchar(50) as dstodokeseikana,
        dstodokemeikana::varchar(50) as dstodokemeikana,
        dstodokezip::varchar(10) as dstodokezip,
        c_dstodokeprefcd::varchar(2) as c_dstodokeprefcd,
        dstodokepref::varchar(100) as dstodokepref,
        dstodokecity::varchar(560) as dstodokecity,
        dstodokeaddr::varchar(200) as dstodokeaddr,
        dstodoketatemono::varchar(200) as dstodoketatemono,
        dstodokeaddrkana::varchar(2048) as dstodokeaddrkana,
        dstodoketel::varchar(16) as dstodoketel,
        dstodokefax::varchar(16) as dstodokefax,
        c_dsdosokbn::varchar(2) as c_dsdosokbn,
        dskessaihoho::varchar(2) as dskessaihoho,
        c_dicardid::number(10,0) as c_dicardid,
        dspaymentclass::varchar(2) as dspaymentclass,
        dihaisokeitai::number(10,0) as dihaisokeitai,
        c_dsyupacketkahiflg::varchar(1) as c_dsyupacketkahiflg,
        c_dsdeliveryrulekbn::varchar(2) as c_dsdeliveryrulekbn,
        c_dsdeliveryruledatekbn::varchar(2) as c_dsdeliveryruledatekbn,
        c_dsdeliveryruleweekkbn::varchar(2) as c_dsdeliveryruleweekkbn,
        c_dsdeliveryruledowkbn::varchar(2) as c_dsdeliveryruledowkbn,
        c_dsdeliverytime::varchar(2) as c_dsdeliverytime,
        c_dsnoshinshomemo::varchar(2000) as c_dsnoshinshomemo,
        c_dsokurijomemo::varchar(2000) as c_dsokurijomemo,
        c_dicancelflg::varchar(1) as c_dicancelflg,
        c_dsordercreatekbn::varchar(2) as c_dsordercreatekbn,
        c_dscontractchangekbn::varchar(2) as c_dscontractchangekbn,
        c_dsschedulechg05kbn::varchar(2) as c_dsschedulechg05kbn,
        c_dscategoryfreeflg::varchar(1) as c_dscategoryfreeflg,
        c_dsschedulechg02kbn::varchar(2) as c_dsschedulechg02kbn,
        c_dsschedulechg04kbn::varchar(2) as c_dsschedulechg04kbn,
        c_dsschedulechg08kbn::varchar(2) as c_dsschedulechg08kbn,
        c_dsschedulechg06kbn::varchar(2) as c_dsschedulechg06kbn,
        c_dsschedulechg07kbn::varchar(2) as c_dsschedulechg07kbn,
        c_dsschedulechg09kbn::varchar(2) as c_dsschedulechg09kbn,
        c_dsschedulechg01kbn::varchar(2) as c_dsschedulechg01kbn,
        c_dsschedulechg03kbn::varchar(2) as c_dsschedulechg03kbn,
        c_dsteikifirstflg::varchar(1) as c_dsteikifirstflg,
        c_diregularresult::number(6,0) as c_diregularresult,
        c_dsregularresultflg::varchar(1) as c_dsregularresultflg,
        c_dsschedulehaneiflg::varchar(1) as c_dsschedulehaneiflg,
        c_dsnextcreateflg::varchar(1) as c_dsnextcreateflg,
        c_dsnextdeliverydate::timestamp_ntz(9) as c_dsnextdeliverydate,
        dsprep::timestamp_ntz(9) as dsprep,
        dsren::timestamp_ntz(9) as dsren,
        dselim::timestamp_ntz(9) as dselim,
        diprepusr::number(10,0) as diprepusr,
        direnusr::number(10,0) as direnusr,
        dielimusr::number(10,0) as dielimusr,
        dielimflg::varchar(1) as dielimflg,
        NULL::varchar(10) as source_file_date,
        current_timestamp()::timestamp_ntz(9) as inserted_date,
        NULL::varchar(10) as inserted_by,
        current_timestamp()::timestamp_ntz(9) as updated_date,
        NULL::varchar(100) as updated_by
    from source
)
select * from final