with WKS_ANZ_RPT_RE as (
    select * from {{ ref('pcfwks_integration__wks_anz_rpt_re') }}
),
--final cte
anz_rpt_re_gcph  as (SELECT jj_year,
       jj_mnth_id,
       "CLUSTER",
       MARKET,
       data_src,
       CHANNEL_NAME,
       soldto_code,
       DISTRIBUTOR_CODE,
       DISTRIBUTOR_NAME,
       SELL_OUT_CHANNEL,
       STORE_TYPE,
       PRIORITIZATION_SEGMENTATION,
       STORE_CATEGORY,
       STORE_CODE,
       STORE_NAME,
       STORE_GRADE,
       STORE_SIZE,
       REGION,
       ZONE_NAME,
       CITY,
       RTRLATITUDE,
       RTRLONGITUDE,
       CUSTOMER_SEGMENT_KEY,
       CUSTOMER_SEGMENT_DESCRIPTION,
       RETAIL_ENVIRONMENT,
       SAP_CUSTOMER_CHANNEL_KEY,
       SAP_CUSTOMER_CHANNEL_DESCRIPTION,
       SAP_CUSTOMER_SUB_CHANNEL_KEY,
       SAP_SUB_CHANNEL_DESCRIPTION,
       SAP_PARENT_CUSTOMER_KEY,
       SAP_PARENT_CUSTOMER_DESCRIPTION,
       SAP_BANNER_KEY,
       SAP_BANNER_DESCRIPTION,
       SAP_BANNER_FORMAT_KEY,
       SAP_BANNER_FORMAT_DESCRIPTION,
       CUSTOMER_NAME,
       LTRIM(CUSTOMER_CODE,'0') AS CUSTOMER_CODE,
       PRODUCT_CODE,
       PRODUCT_NAME,
       PROD_HIER_L1,
       PROD_HIER_L2,
       PROD_HIER_L3,
       PROD_HIER_L4,
       PROD_HIER_L5,
       PROD_HIER_L6,
       PROD_HIER_L7,
       PROD_HIER_L8,
       PROD_HIER_L9,
       MAPPED_SKU_CD,
       SAP_PROD_SGMT_CD,
       SAP_PROD_SGMT_DESC,
       --SAP_BASE_PROD_CD,
       SAP_BASE_PROD_DESC,
       --SAP_MEGA_BRND_CD,
       SAP_MEGA_BRND_DESC,
       --SAP_BRND_CD,
       SAP_BRND_DESC,
       --SAP_VRNT_CD,
       SAP_VRNT_DESC,
       --SAP_PUT_UP_CD,
       SAP_PUT_UP_DESC,
       SAP_GRP_FRNCHSE_CD,
       SAP_GRP_FRNCHSE_DESC,
       SAP_FRNCHSE_CD,
       SAP_FRNCHSE_DESC,
       SAP_PROD_FRNCHSE_CD,
       SAP_PROD_FRNCHSE_DESC,
       SAP_PROD_MJR_CD,
       SAP_PROD_MJR_DESC,
       SAP_PROD_MNR_CD,
       SAP_PROD_MNR_DESC,
       SAP_PROD_HIER_CD,
       SAP_PROD_HIER_DESC,
       --PKA_FRANCHISE_CD,
       PKA_FRANCHISE_DESC,
       --PKA_BRAND_CD,
       PKA_BRAND_DESC,
       --PKA_SUB_BRAND_CD,
       PKA_SUB_BRAND_DESC,
       --PKA_VARIANT_CD,
       PKA_VARIANT_DESC,
       --PKA_SUB_VARIANT_CD,
       PKA_SUB_VARIANT_DESC,
       GLOBAL_PRODUCT_FRANCHISE,
       GLOBAL_PRODUCT_BRAND,
       GLOBAL_PRODUCT_SUB_BRAND,
       GLOBAL_PRODUCT_VARIANT,
       GLOBAL_PRODUCT_SEGMENT,
       GLOBAL_PRODUCT_SUBSEGMENT,
       GLOBAL_PRODUCT_CATEGORY,
       GLOBAL_PRODUCT_SUBCATEGORY,
       GLOBAL_PUT_UP_DESCRIPTION,
       --EAN,
       --SKU_CODE,
       --SKU_DESCRIPTION,
       --GREENLIGHT_SKU_FLAG,
       CASE
         WHEN PKA_PRODUCT_KEY IN ('N/A','NA') THEN 'NA'
         ELSE PKA_PRODUCT_KEY
       END AS PKA_PRODUCT_KEY,
       CASE
         WHEN PKA_PRODUCT_KEY_DESCRIPTION IN ('N/A','NA') THEN 'NA'
         ELSE PKA_PRODUCT_KEY_DESCRIPTION
       END AS PKA_PRODUCT_KEY_DESCRIPTION,
       SALES_VALUE,
       SALES_QTY,
       AVG_SALES_QTY,
       SALES_VALUE_LIST_PRICE,
       LM_SALES,
       LM_SALES_QTY,
       LM_AVG_SALES_QTY,
       LM_SALES_LP,
       P3M_SALES,
       P3M_QTY,
       P3M_AVG_QTY,
       P3M_SALES_LP,
       P6M_SALES,
       P6M_QTY,
       P6M_AVG_QTY,
       P6M_SALES_LP,
       P12M_SALES,
       P12M_QTY,
       P12M_AVG_QTY,
       P12M_SALES_LP,
       F3M_SALES,
       F3M_QTY,
       F3M_AVG_QTY,
       LM_SALES_FLAG,
       P3M_SALES_FLAG,
       P6M_SALES_FLAG,
       P12M_SALES_FLAG,
       MDP_FLAG,
       TARGET_COMPLAINCE,
       LIST_PRICE,
       TOTAL_SALES_LM,
       TOTAL_SALES_P3M,
       TOTAL_SALES_P6M,
       TOTAL_SALES_P12M,
       TOTAL_SALES_BY_STORE_LM,
       TOTAL_SALES_BY_STORE_P3M,
       TOTAL_SALES_BY_STORE_P6M,
       TOTAL_SALES_BY_STORE_P12M,
       TOTAL_SALES_BY_SKU_LM,
       TOTAL_SALES_BY_SKU_P3M,
       TOTAL_SALES_BY_SKU_P6M,
       TOTAL_SALES_BY_SKU_P12M,
	   TOTAL_SALES_LM_LP,
       TOTAL_SALES_P3M_LP,
       TOTAL_SALES_P6M_LP,
       TOTAL_SALES_P12M_LP,
       TOTAL_SALES_BY_STORE_LM_LP,
       TOTAL_SALES_BY_STORE_P3M_LP,
       TOTAL_SALES_BY_STORE_P6M_LP,
       TOTAL_SALES_BY_STORE_P12M_LP,
       TOTAL_SALES_BY_SKU_LM_LP,
       TOTAL_SALES_BY_SKU_P3M_LP,
       TOTAL_SALES_BY_SKU_P6M_LP,
       TOTAL_SALES_BY_SKU_P12M_LP,
       (TOTAL_SALES_BY_STORE_LM / NULLIF(TOTAL_SALES_LM,0)) AS STORE_CONTRIBUTION_LM,
       (TOTAL_SALES_BY_SKU_LM / NULLIF(TOTAL_SALES_LM,0)) AS SKU_CONTRIBUTION_LM,
       (STORE_CONTRIBUTION_LM*SKU_CONTRIBUTION_LM*TOTAL_SALES_LM) AS SIZE_OF_PRICE_LM,
       (TOTAL_SALES_BY_STORE_P3M / NULLIF(TOTAL_SALES_P3M,0)) AS STORE_CONTRIBUTION_P3M,
       (TOTAL_SALES_BY_SKU_P3M / NULLIF(TOTAL_SALES_P3M,0)) AS SKU_CONTRIBUTION_P3M,
       (STORE_CONTRIBUTION_P3M*SKU_CONTRIBUTION_P3M*TOTAL_SALES_P3M) AS SIZE_OF_PRICE_P3M,
       (TOTAL_SALES_BY_STORE_P6M / NULLIF(TOTAL_SALES_P6M,0)) AS STORE_CONTRIBUTION_P6M,
       (TOTAL_SALES_BY_SKU_P6M / NULLIF(TOTAL_SALES_P6M,0)) AS SKU_CONTRIBUTION_P6M,
       (STORE_CONTRIBUTION_P6M*SKU_CONTRIBUTION_P6M*TOTAL_SALES_P6M) AS SIZE_OF_PRICE_P6M,
       (TOTAL_SALES_BY_STORE_P12M / NULLIF(TOTAL_SALES_P12M,0)) AS STORE_CONTRIBUTION_P12M,
       (TOTAL_SALES_BY_SKU_P12M / NULLIF(TOTAL_SALES_P12M,0)) AS SKU_CONTRIBUTION_P12M,
       (STORE_CONTRIBUTION_P12M*SKU_CONTRIBUTION_P12M*TOTAL_SALES_P12M) AS SIZE_OF_PRICE_P12M,
       (TOTAL_SALES_BY_STORE_LM_LP / NULLIF(TOTAL_SALES_LM_LP,0)) AS STORE_CONTRIBUTION_LM_LP,
       (TOTAL_SALES_BY_SKU_LM_LP / NULLIF(TOTAL_SALES_LM_LP,0)) AS SKU_CONTRIBUTION_LM_LP,
       (STORE_CONTRIBUTION_LM_LP*SKU_CONTRIBUTION_LM_LP*TOTAL_SALES_LM_LP) AS SIZE_OF_PRICE_LM_LP,
       (TOTAL_SALES_BY_STORE_P3M_LP / NULLIF(TOTAL_SALES_P3M_LP,0)) AS STORE_CONTRIBUTION_P3M_LP,
       (TOTAL_SALES_BY_SKU_P3M_LP / NULLIF(TOTAL_SALES_P3M_LP,0)) AS SKU_CONTRIBUTION_P3M_LP,
       (STORE_CONTRIBUTION_P3M_LP*SKU_CONTRIBUTION_P3M_LP*TOTAL_SALES_P3M_LP) AS SIZE_OF_PRICE_P3M_LP,
       (TOTAL_SALES_BY_STORE_P6M_LP / NULLIF(TOTAL_SALES_P6M_LP,0)) AS STORE_CONTRIBUTION_P6M_LP,
       (TOTAL_SALES_BY_SKU_P6M_LP / NULLIF(TOTAL_SALES_P6M_LP,0)) AS SKU_CONTRIBUTION_P6M_LP,
       (STORE_CONTRIBUTION_P6M_LP*SKU_CONTRIBUTION_P6M_LP*TOTAL_SALES_P6M_LP) AS SIZE_OF_PRICE_P6M_LP,
       (TOTAL_SALES_BY_STORE_P12M_LP / NULLIF(TOTAL_SALES_P12M_LP,0)) AS STORE_CONTRIBUTION_P12M_LP,
       (TOTAL_SALES_BY_SKU_P12M_LP / NULLIF(TOTAL_SALES_P12M_LP,0)) AS SKU_CONTRIBUTION_P12M_LP,
       (STORE_CONTRIBUTION_P12M_LP*SKU_CONTRIBUTION_P12M_LP*TOTAL_SALES_P12M_LP) AS SIZE_OF_PRICE_P12M_LP,
       MD5(soldto_code||DISTRIBUTOR_NAME||SELL_OUT_CHANNEL||RETAIL_ENVIRONMENT||nvl (CUSTOMER_SEGMENT_DESCRIPTION,'csd') || nvl (SAP_CUSTOMER_CHANNEL_DESCRIPTION,'sccd') ||nvl (SAP_SUB_CHANNEL_DESCRIPTION,'sscd') ||nvl (SAP_PARENT_CUSTOMER_DESCRIPTION,'spscd') || nvl (SAP_BANNER_DESCRIPTION,'sbd') || nvl (SAP_BANNER_FORMAT_DESCRIPTION,'sbfd')) AS CUSTOMER_AGG_DIM_KEY,
       MD5(nvl (SAP_BASE_PROD_DESC,'sbpd') || nvl (SAP_MEGA_BRND_DESC,'smbd') ||nvl (SAP_BRND_DESC,'sb') || nvl (SAP_FRNCHSE_DESC,'sfd') || nvl (SAP_PROD_MJR_DESC,'spmd') ||nvl (SAP_PROD_MNR_DESC,'spm') || nvl (PKA_FRANCHISE_DESC,'pfd') || nvl (PKA_BRAND_DESC,'pbd') ||nvl (PKA_SUB_BRAND_DESC,'pbsd') || nvl (GLOBAL_PRODUCT_FRANCHISE,'gpf') || nvl (GLOBAL_PRODUCT_BRAND,'gpb') ||nvl (GLOBAL_PRODUCT_SUB_BRAND,'gpsb') ||nvl (GLOBAL_PRODUCT_SEGMENT,'gps') || nvl (GLOBAL_PRODUCT_SUBSEGMENT,'gpss') ||nvl (GLOBAL_PRODUCT_CATEGORY,'gpc') ||nvl (GLOBAL_PRODUCT_SUBCATEGORY,'gpsc') ||nvl (GLOBAL_PUT_UP_DESCRIPTION,'gputup')) AS PRODUCT_AGG_DIM_KEY
FROM (SELECT MAIN.jj_year,
             MAIN.jj_mnth_id,
             MAIN.CLUSTER,
             MAIN.MARKET AS MARKET,
             main.data_src,
             MAIN.CHANNEL_NAME AS CHANNEL_NAME,
             --MAIN.CHANNEL_NAME,
             MAIN.soldto_code,
             MAIN.DISTRIBUTOR_CODE,
             MAIN.DISTRIBUTOR_NAME,
             MAIN.SELL_OUT_CHANNEL,
             MAIN.STORE_TYPE AS STORE_TYPE,
             MAIN.PRIORITIZATION_SEGMENTATION,
             MAIN.STORE_CATEGORY,
             MAIN.STORE_CODE,
             MAIN.STORE_NAME,
             MAIN.STORE_GRADE,
             MAIN.STORE_SIZE,
             MAIN.REGION,
             MAIN.ZONE_NAME,
             MAIN.CITY,
             MAIN.RTRLATITUDE,
             MAIN.RTRLONGITUDE,
             TRIM(NVL (NULLIF(MAIN.CUSTOMER_SEGMENT_KEY,''),'NA')) AS CUSTOMER_SEGMENT_KEY,
             TRIM(NVL (NULLIF(MAIN.CUSTOMER_SEGMENT_DESCRIPTION,''),'NA')) AS CUSTOMER_SEGMENT_DESCRIPTION,
             main.sell_out_RE AS RETAIL_ENVIRONMENT,
             --TRIM(NVL (NULLIF(CUSTOMER.RETAIL_ENV,''),'NA')) AS RETAIL_ENVIRONMENT,
             TRIM(NVL (NULLIF(MAIN.SAP_CUSTOMER_CHANNEL_KEY,''),'NA')) AS SAP_CUSTOMER_CHANNEL_KEY,
             UPPER(TRIM(NVL (NULLIF(MAIN.SAP_CUSTOMER_CHANNEL_DESCRIPTION,''),'NA'))) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             TRIM(NVL (NULLIF(MAIN.SAP_CUSTOMER_SUB_CHANNEL_KEY,''),'NA')) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,
             UPPER(TRIM(NVL (NULLIF(MAIN.SAP_SUB_CHANNEL_DESCRIPTION,''),'NA'))) AS SAP_SUB_CHANNEL_DESCRIPTION,
             TRIM(NVL (NULLIF(MAIN.SAP_PARENT_CUSTOMER_KEY,''),'NA')) AS SAP_PARENT_CUSTOMER_KEY,
             UPPER(TRIM(NVL (NULLIF(MAIN.SAP_PARENT_CUSTOMER_DESCRIPTION,''),'NA'))) AS SAP_PARENT_CUSTOMER_DESCRIPTION,
             TRIM(NVL (NULLIF(MAIN.SAP_BANNER_KEY,''),'NA')) AS SAP_BANNER_KEY,
             UPPER(TRIM(NVL (NULLIF(MAIN.SAP_BANNER_DESCRIPTION,''),'NA'))) AS SAP_BANNER_DESCRIPTION,
             TRIM(NVL (NULLIF(MAIN.SAP_BANNER_FORMAT_KEY,''),'NA')) AS SAP_BANNER_FORMAT_KEY,
             UPPER(TRIM(NVL (NULLIF(MAIN.SAP_BANNER_FORMAT_DESCRIPTION,''),'NA'))) AS SAP_BANNER_FORMAT_DESCRIPTION,
             TRIM(NVL (NULLIF(MAIN.CUSTOMER_NAME,''),'NA')) AS CUSTOMER_NAME,
             TRIM(NVL (NULLIF(MAIN.CUSTOMER_CODE,''),'NA')) AS CUSTOMER_CODE,
             MAIN.PRODUCT_CODE AS PRODUCT_CODE,
             MAIN.PRODUCT_NAME AS PRODUCT_NAME,
             MAIN.PROD_HIER_L1,
             MAIN.PROD_HIER_L2,
             MAIN.PROD_HIER_L3,
             MAIN.PROD_HIER_L4,
             MAIN.PROD_HIER_L5,
             MAIN.PROD_HIER_L6,
             MAIN.PROD_HIER_L7,
             MAIN.PROD_HIER_L8,
             MAIN.PROD_HIER_L9,
             MAIN.MAPPED_SKU_CD,
             MAIN.SAP_PROD_SGMT_CD,
             MAIN.SAP_PROD_SGMT_DESC,
             --PRODUCT.SAP_BASE_PROD_CD,
             MAIN.SAP_BASE_PROD_DESC,
             --PRODUCT.SAP_MEGA_BRND_CD,
             MAIN.SAP_MEGA_BRND_DESC,
             --PRODUCT.SAP_BRND_CD,
             MAIN.SAP_BRND_DESC,
             --PRODUCT.SAP_VRNT_CD,
             MAIN.SAP_VRNT_DESC,
             --PRODUCT.SAP_PUT_UP_CD,
             MAIN.SAP_PUT_UP_DESC,
             MAIN.SAP_GRP_FRNCHSE_CD,
             MAIN.SAP_GRP_FRNCHSE_DESC,
             MAIN.SAP_FRNCHSE_CD,
             MAIN.SAP_FRNCHSE_DESC,
             MAIN.SAP_PROD_FRNCHSE_CD,
             MAIN.SAP_PROD_FRNCHSE_DESC,
             MAIN.SAP_PROD_MJR_CD,
             MAIN.SAP_PROD_MJR_DESC,
             MAIN.SAP_PROD_MNR_CD,
             MAIN.SAP_PROD_MNR_DESC,
             MAIN.SAP_PROD_HIER_CD,
             MAIN.SAP_PROD_HIER_DESC,
             TRIM(NVL (NULLIF(MAIN.GLOBAL_PRODUCT_FRANCHISE,''),'NA')) AS GLOBAL_PRODUCT_FRANCHISE,
             TRIM(NVL (NULLIF(MAIN.GLOBAL_PRODUCT_BRAND,''),'NA')) AS GLOBAL_PRODUCT_BRAND,
             TRIM(NVL (NULLIF(MAIN.GLOBAL_PRODUCT_SUB_BRAND,''),'NA')) AS GLOBAL_PRODUCT_SUB_BRAND,
             TRIM(NVL (NULLIF(MAIN.GLOBAL_PRODUCT_VARIANT,''),'NA')) AS GLOBAL_PRODUCT_VARIANT,
             TRIM(NVL (NULLIF(MAIN.GLOBAL_PRODUCT_SEGMENT,''),'NA')) AS GLOBAL_PRODUCT_SEGMENT,
             TRIM(NVL (NULLIF(MAIN.GLOBAL_PRODUCT_SUBSEGMENT,''),'NA')) AS GLOBAL_PRODUCT_SUBSEGMENT,
             TRIM(NVL (NULLIF(MAIN.GLOBAL_PRODUCT_CATEGORY,''),'NA')) AS GLOBAL_PRODUCT_CATEGORY,
             TRIM(NVL (NULLIF(MAIN.GLOBAL_PRODUCT_SUBCATEGORY,''),'NA')) AS GLOBAL_PRODUCT_SUBCATEGORY,
             TRIM(NVL (NULLIF(MAIN.GLOBAL_PUT_UP_DESCRIPTION,''),'NA')) AS GLOBAL_PUT_UP_DESCRIPTION,
             --TRIM(NVL (NULLIF(PRODUCT.EAN_NUM,''),'NA')) AS EAN,
             --MAIN.PRODUCT_CODE AS SKU_CODE,
             -- LTRIM(PRODUCT.SAP_MATL_NUM,0) AS SKU_CODE,
             --MAIN.PRODUCT_CODE AS SKU_DESCRIPTION,
             --UPPER(PRODUCT.SAP_MAT_DESC) AS SKU_DESCRIPTION,
             --TRIM(NVL (NULLIF(PRODUCT.GREENLIGHT_SKU_FLAG,''),'NA')) AS GREENLIGHT_SKU_FLAG,
             TRIM(NVL (NULLIF(MAIN.PKA_PRODUCT_KEY,''),'NA')) AS PKA_PRODUCT_KEY,
             TRIM(NVL (NULLIF(MAIN.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA')) AS PKA_PRODUCT_KEY_DESCRIPTION,
             --PRODUCT.PKA_FRANCHISE_CD,
             MAIN.PKA_FRANCHISE_DESC,
             --PRODUCT.PKA_BRAND_CD,
             MAIN.PKA_BRAND_DESC,
             --PRODUCT.PKA_SUB_BRAND_CD,
             MAIN.PKA_SUB_BRAND_DESC,
             --PRODUCT.PKA_VARIANT_CD,
             MAIN.PKA_VARIANT_DESC,
             --PRODUCT.PKA_SUB_VARIANT_CD,
             MAIN.PKA_SUB_VARIANT_DESC,
             MAIN.SALES_VALUE AS SALES_VALUE,
             MAIN.SALES_QTY AS SALES_QTY,
             MAIN.AVG_SALES_QTY AS AVG_SALES_QTY,
             MAIN.SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,
             MAIN.LM_SALES AS LM_SALES,
             MAIN.LM_SALES_QTY AS LM_SALES_QTY,
             MAIN.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,
             MAIN.LM_SALES_LP AS LM_SALES_LP,
             MAIN.P3M_SALES AS P3M_SALES,
             MAIN.P3M_QTY AS P3M_QTY,
             MAIN.P3M_AVG_QTY AS P3M_AVG_QTY,
             MAIN.P3M_SALES_LP AS P3M_SALES_LP,
             MAIN.F3M_SALES AS F3M_SALES,
             MAIN.F3M_QTY AS F3M_QTY,
             MAIN.F3M_AVG_QTY AS F3M_AVG_QTY,
             MAIN.P6M_SALES AS P6M_SALES,
             MAIN.P6M_QTY AS P6M_QTY,
             MAIN.P6M_AVG_QTY AS P6M_AVG_QTY,
             MAIN.P6M_SALES_LP AS P6M_SALES_LP,
             MAIN.P12M_SALES AS P12M_SALES,
             MAIN.P12M_QTY AS P12M_QTY,
             MAIN.P12M_AVG_QTY AS P12M_AVG_QTY,
             MAIN.P12M_SALES_LP AS P12M_SALES_LP,
             MAIN.LM_SALES_FLAG,
             MAIN.P3M_SALES_FLAG,
             MAIN.P6M_SALES_FLAG,
             MAIN.P12M_SALES_FLAG,
             MAIN.MDP_FLAG,
             100 AS TARGET_COMPLAINCE,
             MAIN.LIST_PRICE,
             SUM(MAIN.LM_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_LM,
             SUM(MAIN.P3M_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_P3M,
             SUM(MAIN.P6M_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_P6M,
             SUM(MAIN.P12M_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_P12M,
             SUM(MAIN.LM_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND,STORE_CODE) AS TOTAL_SALES_BY_STORE_LM,
             SUM(MAIN.P3M_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND,STORE_CODE) AS TOTAL_SALES_BY_STORE_P3M,
             SUM(MAIN.P6M_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND,STORE_CODE) AS TOTAL_SALES_BY_STORE_P6M,
             SUM(MAIN.P12M_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND,STORE_CODE) AS TOTAL_SALES_BY_STORE_P12M,
             SUM(MAIN.LM_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND,PRODUCT_CODE) AS TOTAL_SALES_BY_SKU_LM,
             SUM(MAIN.P3M_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND,PRODUCT_CODE) AS TOTAL_SALES_BY_SKU_P3M,
             SUM(MAIN.P6M_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND,PRODUCT_CODE) AS TOTAL_SALES_BY_SKU_P6M,
             SUM(MAIN.P12M_SALES) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND,PRODUCT_CODE) AS TOTAL_SALES_BY_SKU_P12M,
             SUM(MAIN.LM_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_LM_LP,
             SUM(MAIN.P3M_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_P3M_LP,
             SUM(MAIN.P6M_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_P6M_LP,
             SUM(MAIN.P12M_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_P12M_LP,
             SUM(MAIN.LM_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_BY_STORE_LM_LP,
             SUM(MAIN.P3M_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_BY_STORE_P3M_LP,
             SUM(MAIN.P6M_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_BY_STORE_P6M_LP,
             SUM(MAIN.P12M_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_BY_STORE_P12M_LP,
             SUM(MAIN.LM_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_BY_SKU_LM_LP,
             SUM(MAIN.P3M_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_BY_SKU_P3M_LP,
             SUM(MAIN.P6M_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_BY_SKU_P6M_LP,
             SUM(MAIN.P12M_SALES_LP) OVER (PARTITION BY jj_mnth_id,DISTRIBUTOR_NAME,GLOBAL_PRODUCT_BRAND) AS TOTAL_SALES_BY_SKU_P12M_LP
      FROM WKS_ANZ_RPT_RE MAIN
        )),
final as 
(
select 
jj_year::VARCHAR(16) AS jj_year,
jj_mnth_id::VARCHAR(22) AS jj_mnth_id,
cluster::VARCHAR(100) AS cluster,
market::VARCHAR(50) AS market,
data_src::VARCHAR(8) AS data_src,
channel_name::VARCHAR(150) AS channel_name,
soldto_code::VARCHAR(255) AS soldto_code,
distributor_code::VARCHAR(32) AS distributor_code,
distributor_name::VARCHAR(255) AS distributor_name,
sell_out_channel::VARCHAR(150) AS sell_out_channel,
store_type::VARCHAR(255) AS store_type,
prioritization_segmentation::VARCHAR(1) AS prioritization_segmentation,
store_category::VARCHAR(1) AS store_category,
store_code::VARCHAR(100) AS store_code,
store_name::VARCHAR(601) AS store_name,
store_grade::VARCHAR(20) AS store_grade,
store_size::VARCHAR(2) AS store_size,
region::VARCHAR(150) AS region,
zone_name::VARCHAR(150) AS zone_name,
city::VARCHAR(2) AS city,
rtrlatitude::VARCHAR(1) AS rtrlatitude,
rtrlongitude::VARCHAR(1) AS rtrlongitude,
customer_segment_key::VARCHAR(12) AS customer_segment_key,
customer_segment_description::VARCHAR(50) AS customer_segment_description,
retail_environment::VARCHAR(225) AS retail_environment,
sap_customer_channel_key::VARCHAR(12) AS sap_customer_channel_key,
sap_customer_channel_description::VARCHAR(112) AS sap_customer_channel_description,
sap_customer_sub_channel_key::VARCHAR(12) AS sap_customer_sub_channel_key,
sap_sub_channel_description::VARCHAR(112) AS sap_sub_channel_description,
sap_parent_customer_key::VARCHAR(12) AS sap_parent_customer_key,
sap_parent_customer_description::VARCHAR(112) AS sap_parent_customer_description,
sap_banner_key::VARCHAR(12) AS sap_banner_key,
sap_banner_description::VARCHAR(112) AS sap_banner_description,
sap_banner_format_key::VARCHAR(12) AS sap_banner_format_key,
sap_banner_format_description::VARCHAR(112) AS sap_banner_format_description,
customer_name::VARCHAR(100) AS customer_name,
customer_code::VARCHAR(10) AS customer_code,
product_code::VARCHAR(150) AS product_code,
product_name::VARCHAR(300) AS product_name,
prod_hier_l1::VARCHAR(1) AS prod_hier_l1,
prod_hier_l2::VARCHAR(1) AS prod_hier_l2,
prod_hier_l3::VARCHAR(384) AS prod_hier_l3,
prod_hier_l4::VARCHAR(384) AS prod_hier_l4,
prod_hier_l5::VARCHAR(384) AS prod_hier_l5,
prod_hier_l6::VARCHAR(1) AS prod_hier_l6,
prod_hier_l7::VARCHAR(1) AS prod_hier_l7,
prod_hier_l8::VARCHAR(1) AS prod_hier_l8,
prod_hier_l9::VARCHAR(2307) AS prod_hier_l9,
mapped_sku_cd::VARCHAR(40) AS mapped_sku_cd,
sap_prod_sgmt_cd::VARCHAR(18) AS sap_prod_sgmt_cd,
sap_prod_sgmt_desc::VARCHAR(100) AS sap_prod_sgmt_desc,
sap_base_prod_desc::VARCHAR(100) AS sap_base_prod_desc,
sap_mega_brnd_desc::VARCHAR(100) AS sap_mega_brnd_desc,
sap_brnd_desc::VARCHAR(100) AS sap_brnd_desc,
sap_vrnt_desc::VARCHAR(100) AS sap_vrnt_desc,
sap_put_up_desc::VARCHAR(100) AS sap_put_up_desc,
sap_grp_frnchse_cd::VARCHAR(18) AS sap_grp_frnchse_cd,
sap_grp_frnchse_desc::VARCHAR(100) AS sap_grp_frnchse_desc,
sap_frnchse_cd::VARCHAR(18) AS sap_frnchse_cd,
sap_frnchse_desc::VARCHAR(100) AS sap_frnchse_desc,
sap_prod_frnchse_cd::VARCHAR(18) AS sap_prod_frnchse_cd,
sap_prod_frnchse_desc::VARCHAR(100) AS sap_prod_frnchse_desc,
sap_prod_mjr_cd::VARCHAR(18) AS sap_prod_mjr_cd,
sap_prod_mjr_desc::VARCHAR(100) AS sap_prod_mjr_desc,
sap_prod_mnr_cd::VARCHAR(18) AS sap_prod_mnr_cd,
sap_prod_mnr_desc::VARCHAR(100) AS sap_prod_mnr_desc,
sap_prod_hier_cd::VARCHAR(18) AS sap_prod_hier_cd,
sap_prod_hier_desc::VARCHAR(100) AS sap_prod_hier_desc,
pka_franchise_desc::VARCHAR(30) AS pka_franchise_desc,
pka_brand_desc::VARCHAR(30) AS pka_brand_desc,
pka_sub_brand_desc::VARCHAR(30) AS pka_sub_brand_desc,
pka_variant_desc::VARCHAR(30) AS pka_variant_desc,
pka_sub_variant_desc::VARCHAR(30) AS pka_sub_variant_desc,
global_product_franchise::VARCHAR(30) AS global_product_franchise,
global_product_brand::VARCHAR(30) AS global_product_brand,
global_product_sub_brand::VARCHAR(100) AS global_product_sub_brand,
global_product_variant::VARCHAR(100) AS global_product_variant,
global_product_segment::VARCHAR(50) AS global_product_segment,
global_product_subsegment::VARCHAR(100) AS global_product_subsegment,
global_product_category::VARCHAR(50) AS global_product_category,
global_product_subcategory::VARCHAR(50) AS global_product_subcategory,
global_put_up_description::VARCHAR(100) AS global_put_up_description,
pka_product_key::VARCHAR(68) AS pka_product_key,
pka_product_key_description::VARCHAR(255) AS pka_product_key_description,
sales_value::NUMERIC(38,6) AS sales_value,
sales_qty::NUMERIC(38,6) AS sales_qty,
avg_sales_qty::NUMERIC(10,2) AS avg_sales_qty,
sales_value_list_price::NUMERIC(38,12) AS sales_value_list_price,
lm_sales::NUMERIC(38,6) AS lm_sales,
lm_sales_qty::NUMERIC(38,6) AS lm_sales_qty,
lm_avg_sales_qty::NUMERIC(10,2) AS lm_avg_sales_qty,
lm_sales_lp::NUMERIC(38,12) AS lm_sales_lp,
p3m_sales::NUMERIC(38,6) AS p3m_sales,
p3m_qty::NUMERIC(38,6) AS p3m_qty,
p3m_avg_qty::NUMERIC(38,6) AS p3m_avg_qty,
p3m_sales_lp::NUMERIC(38,12) AS p3m_sales_lp,
p6m_sales::NUMERIC(38,6) AS p6m_sales,
p6m_qty::NUMERIC(38,6) AS p6m_qty,
p6m_avg_qty::NUMERIC(38,6) AS p6m_avg_qty,
p6m_sales_lp::NUMERIC(38,12) AS p6m_sales_lp,
p12m_sales::NUMERIC(38,6) AS p12m_sales,
p12m_qty::NUMERIC(38,6) AS p12m_qty,
p12m_avg_qty::NUMERIC(38,6) AS p12m_avg_qty,
p12m_sales_lp::NUMERIC(38,12) AS p12m_sales_lp,
f3m_sales::NUMERIC(38,6) AS f3m_sales,
f3m_qty::NUMERIC(38,6) AS f3m_qty,
f3m_avg_qty::NUMERIC(38,6) AS f3m_avg_qty,
lm_sales_flag::VARCHAR(1) AS lm_sales_flag,
p3m_sales_flag::VARCHAR(1) AS p3m_sales_flag,
p6m_sales_flag::VARCHAR(1) AS p6m_sales_flag,
p12m_sales_flag::VARCHAR(1) AS p12m_sales_flag,
mdp_flag::VARCHAR(1) AS mdp_flag,
target_complaince::numeric(18,0) AS target_complaince,
list_price::NUMERIC(38,6) AS list_price,
total_sales_lm::NUMERIC(38,6) AS total_sales_lm,
total_sales_p3m::NUMERIC(38,6) AS total_sales_p3m,
total_sales_p6m::NUMERIC(38,6) AS total_sales_p6m,
total_sales_p12m::NUMERIC(38,6) AS total_sales_p12m,
total_sales_by_store_lm::NUMERIC(38,6) AS total_sales_by_store_lm,
total_sales_by_store_p3m::NUMERIC(38,6) AS total_sales_by_store_p3m,
total_sales_by_store_p6m::NUMERIC(38,6) AS total_sales_by_store_p6m,
total_sales_by_store_p12m::NUMERIC(38,6) AS total_sales_by_store_p12m,
total_sales_by_sku_lm::NUMERIC(38,6) AS total_sales_by_sku_lm,
total_sales_by_sku_p3m::NUMERIC(38,6) AS total_sales_by_sku_p3m,
total_sales_by_sku_p6m::NUMERIC(38,6) AS total_sales_by_sku_p6m,
total_sales_by_sku_p12m::NUMERIC(38,6) AS total_sales_by_sku_p12m,
total_sales_lm_lp::NUMERIC(38,12) AS total_sales_lm_lp,
total_sales_p3m_lp::NUMERIC(38,12) AS total_sales_p3m_lp,
total_sales_p6m_lp::NUMERIC(38,12) AS total_sales_p6m_lp,
total_sales_p12m_lp::NUMERIC(38,12) AS total_sales_p12m_lp,
total_sales_by_store_lm_lp::NUMERIC(38,12) AS total_sales_by_store_lm_lp,
total_sales_by_store_p3m_lp::NUMERIC(38,12) AS total_sales_by_store_p3m_lp,
total_sales_by_store_p6m_lp::NUMERIC(38,12) AS total_sales_by_store_p6m_lp,
total_sales_by_store_p12m_lp::NUMERIC(38,12) AS total_sales_by_store_p12m_lp,
total_sales_by_sku_lm_lp::NUMERIC(38,12) AS total_sales_by_sku_lm_lp,
total_sales_by_sku_p3m_lp::NUMERIC(38,12) AS total_sales_by_sku_p3m_lp,
total_sales_by_sku_p6m_lp::NUMERIC(38,12) AS total_sales_by_sku_p6m_lp,
total_sales_by_sku_p12m_lp::NUMERIC(38,12) AS total_sales_by_sku_p12m_lp,
store_contribution_lm::NUMERIC(38,4) AS store_contribution_lm,
sku_contribution_lm::NUMERIC(38,4) AS sku_contribution_lm,
size_of_price_lm::NUMERIC(38,14) AS size_of_price_lm,
store_contribution_p3m::NUMERIC(38,4) AS store_contribution_p3m,
sku_contribution_p3m::NUMERIC(38,4) AS sku_contribution_p3m,
size_of_price_p3m::NUMERIC(38,14) AS size_of_price_p3m,
store_contribution_p6m::NUMERIC(38,4) AS store_contribution_p6m,
sku_contribution_p6m::NUMERIC(38,4) AS sku_contribution_p6m,
size_of_price_p6m::NUMERIC(38,14) AS size_of_price_p6m,
store_contribution_p12m::NUMERIC(38,4) AS store_contribution_p12m,
sku_contribution_p12m::NUMERIC(38,4) AS sku_contribution_p12m,
size_of_price_p12m::NUMERIC(38,14) AS size_of_price_p12m,
store_contribution_lm_lp::NUMERIC(38,4) AS store_contribution_lm_lp,
sku_contribution_lm_lp::NUMERIC(38,4) AS sku_contribution_lm_lp,
size_of_price_lm_lp::NUMERIC(38,20) AS size_of_price_lm_lp,
store_contribution_p3m_lp::NUMERIC(38,4) AS store_contribution_p3m_lp,
sku_contribution_p3m_lp::NUMERIC(38,4) AS sku_contribution_p3m_lp,
size_of_price_p3m_lp::NUMERIC(38,20) AS size_of_price_p3m_lp,
store_contribution_p6m_lp::NUMERIC(38,4) AS store_contribution_p6m_lp,
sku_contribution_p6m_lp::NUMERIC(38,4) AS sku_contribution_p6m_lp,
size_of_price_p6m_lp::NUMERIC(38,20) AS size_of_price_p6m_lp,
store_contribution_p12m_lp::NUMERIC(38,4) AS store_contribution_p12m_lp,
sku_contribution_p12m_lp::NUMERIC(38,4) AS sku_contribution_p12m_lp,
size_of_price_p12m_lp::NUMERIC(38,20) AS size_of_price_p12m_lp,
customer_agg_dim_key::VARCHAR(32) AS customer_agg_dim_key,
product_agg_dim_key::VARCHAR(32) AS product_agg_dim_key
    from anz_rpt_re_gcph
)
--final select
select * from final