--import cte
with edw_rpt_regional_sellout_offtake as (
    select * from {{ source('aspedw_integration', 'edw_rpt_regional_sellout_offtake') }}
),
edw_vw_cal_retail_excellence_dim as (
    select * from {{ ref('aspedw_integration__v_edw_vw_cal_Retail_excellence_dim') }}
),
--final cte
anz_sellout_base_retail_excellence as 
(
SELECT CNTRY_CD,
       MD5(nvl (SOLDTO_CODE,'stc') ||nvl (DISTRIBUTOR_CODE,'dc') ||nvl (DISTRIBUTOR_NAME,'dn') ||nvl (STORE_CODE,'sc') ||nvl (EAN,'ean') ||nvl (STORE_NAME,'sn') ||nvl (CHANNEL_NAME,'cn') ||nvl (SAP_PARENT_CUSTOMER_KEY,'spck') ||nvl (SAP_PARENT_CUSTOMER_DESCRIPTION,'spscd') ||nvl (SAP_CUSTOMER_CHANNEL_KEY,'scck') ||nvl (SAP_CUSTOMER_CHANNEL_DESCRIPTION,'sccd') ||nvl (SAP_CUSTOMER_SUB_CHANNEL_KEY,'scsck') ||nvl (SAP_SUB_CHANNEL_DESCRIPTION,'sscd') ||nvl (CUSTOMER_SEGMENT_KEY,'csk') ||nvl (CUSTOMER_SEGMENT_DESCRIPTION,'csd') ||nvl (SAP_GO_TO_MDL_KEY,'sgmk') ||nvl (SAP_GO_TO_MDL_DESCRIPTION,'sgmd') ||nvl (SAP_BANNER_KEY,'sbk') ||nvl (SAP_BANNER_DESCRIPTION,'sbd') ||nvl (SAP_BANNER_FORMAT_KEY,'sbfk') ||nvl (SAP_BANNER_FORMAT_DESCRIPTION,'sbfd') ||nvl (RETAIL_ENVIRONMENT,'re') ||nvl (GLOBAL_PRODUCT_FRANCHISE,'gpf') ||nvl (GLOBAL_PRODUCT_BRAND,'gpb') ||nvl (GLOBAL_PRODUCT_SUB_BRAND,'gpsb') ||nvl (GLOBAL_PRODUCT_VARIANT,'gpv') ||nvl (GLOBAL_PRODUCT_SEGMENT,'gps') ||nvl (GLOBAL_PRODUCT_SUBSEGMENT,'gpss') ||nvl (GLOBAL_PRODUCT_CATEGORY,'gpc') ||nvl (GLOBAL_PRODUCT_SUBCATEGORY,'gpsc') ||nvl (GLOBAL_PUT_UP_DESCRIPTION,'gpud') ||nvl (PKA_PRODUCT_KEY,'pk') ||nvl (PKA_PRODUCT_KEY_DESCRIPTION,'pkd')||nvl(store_type,'st')||nvl(Region,'rg')||nvl(zone_or_area,'ar')||nvl(store_grade,'sg')) AS SELLOUT_DIM_KEY,
       CNTRY_NM,
       DATA_SRC,
       SOLDTO_CODE,
       DISTRIBUTOR_CODE,
       DISTRIBUTOR_NAME,
       STORE_CODE,
	   store_grade,list_price,msl_product_desc,sku_code,
       EAN,
       store_name||'#'||ltrim(store_code,'0') as STORE_NAME,
       RETAIL_ENVIRONMENT,
	   store_type,
	   Region,zone_or_area,
       CHANNEL_NAME,
       SAP_PARENT_CUSTOMER_KEY,
       SAP_PARENT_CUSTOMER_DESCRIPTION,
       SAP_CUSTOMER_CHANNEL_KEY,
       SAP_CUSTOMER_CHANNEL_DESCRIPTION,
       SAP_CUSTOMER_SUB_CHANNEL_KEY,
       SAP_SUB_CHANNEL_DESCRIPTION,
       SAP_GO_TO_MDL_KEY,
       SAP_GO_TO_MDL_DESCRIPTION,
       SAP_BANNER_KEY,
       SAP_BANNER_DESCRIPTION,
       SAP_BANNER_FORMAT_KEY,
       SAP_BANNER_FORMAT_DESCRIPTION,
       CUSTOMER_SEGMENT_KEY,
       CUSTOMER_SEGMENT_DESCRIPTION,
       GLOBAL_PRODUCT_FRANCHISE,
       GLOBAL_PRODUCT_BRAND,
       GLOBAL_PRODUCT_SUB_BRAND,
       GLOBAL_PRODUCT_VARIANT,
       GLOBAL_PRODUCT_SEGMENT,
       GLOBAL_PRODUCT_SUBSEGMENT,
       GLOBAL_PRODUCT_CATEGORY,
       GLOBAL_PRODUCT_SUBCATEGORY,
       GLOBAL_PUT_UP_DESCRIPTION,
       PKA_PRODUCT_KEY,
       PKA_PRODUCT_KEY_DESCRIPTION,
       YEAR,
       MNTH_ID,
       SUM(sales_value_list_price) AS sales_value_list_price,
       SUM(SO_SLS_QTY) AS SO_SLS_QTY,
       SUM(SO_SLS_VALUE) AS SO_SLS_VALUE,
       CAST(AVG(SO_SLS_QTY) AS DECIMAL(10,2)) AS SO_AVG_QTY,
       SYSDATE() as crt_dttm
FROM (SELECT country_code AS CNTRY_CD,
             country_name AS CNTRY_NM,
             data_source AS DATA_SRC,
             --DISTRIBUTOR_CODE,
             DISTRIBUTOR_NAME,
             --SOLDTO_CODE,
			 max(soldto_code) over ( PARTITION BY distributor_name ORDER BY length(soldto_code) desc,cal_date DESC  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS soldto_code,
			
       md5(distributor_name) as DISTRIBUTOR_CODE,
             ltrim(STORE_CODE,0) as store_code,
             ltrim(msl_product_code,0) as EAN,
              max(store_name) over ( PARTITION BY ltrim(STORE_CODE,0) ORDER BY cal_date desc,length(store_name) DESC  ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS store_name ,
			  max(list_price) over ( PARTITION BY ltrim(ean,0) ORDER BY length(sku_code) DESC,cal_date desc,sku_code desc ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS list_price ,
			max(msl_product_desc) over ( PARTITION BY ltrim(ean,0) ORDER BY length(sku_code) DESC,cal_date desc,sku_code desc ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS msl_product_desc ,
			max(sku_code) over ( PARTITION BY ltrim(ean,0) ORDER BY length(sku_code) DESC,cal_date desc,sku_code desc ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING ) AS sku_code,
             upper(retail_env) AS RETAIL_ENVIRONMENT,
			 store_type,
			 store_grade,
			 Region,zone_or_area,
             channel AS CHANNEL_NAME,
             SAP_PARENT_CUSTOMER_KEY,
             SAP_PARENT_CUSTOMER_DESCRIPTION,
             SAP_CUSTOMER_CHANNEL_KEY,
             SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             SAP_CUSTOMER_SUB_CHANNEL_KEY,
             SAP_SUB_CHANNEL_DESCRIPTION,
             SAP_GO_TO_MDL_KEY,
             SAP_GO_TO_MDL_DESCRIPTION,
             SAP_BANNER_KEY,
             SAP_BANNER_DESCRIPTION,
             SAP_BANNER_FORMAT_KEY,
             SAP_BANNER_FORMAT_DESCRIPTION,
             CUSTOMER_SEGMENT_KEY,
             CUSTOMER_SEGMENT_DESCRIPTION,
             GLOBAL_PRODUCT_FRANCHISE,
             GLOBAL_PRODUCT_BRAND,
             GLOBAL_PRODUCT_SUB_BRAND,
             GLOBAL_PRODUCT_VARIANT,
             GLOBAL_PRODUCT_SEGMENT,
             GLOBAL_PRODUCT_SUBSEGMENT,
             GLOBAL_PRODUCT_CATEGORY,
             GLOBAL_PRODUCT_SUBCATEGORY,
             GLOBAL_PUT_UP_DESCRIPTION,
             PKA_PRODUCT_KEY,
             PKA_PRODUCT_KEY_DESCRIPTION,
             YEAR,
             MNTH_ID,
             sellout_value_list_price AS sales_value_list_price,
             SELLOUT_SALES_QUANTITY AS SO_SLS_QTY,
             SELLOUT_SALES_VALUE AS SO_SLS_VALUE
      from  EDW_RPT_REGIONAL_SELLOUT_OFFTAKE	
	  WHERE COUNTRY_CODE in  ('AU','NZ') and data_source='SELL-OUT'  
	  AND   MNTH_ID >= (SELECT last_28mnths
                  FROM edw_vw_cal_retail_excellence_dim)::NUMERIC
      AND   MNTH_ID <= (SELECT last_2mnths FROM edw_vw_cal_retail_excellence_dim)::NUMERIC
	  ) MAIN
GROUP BY DISTRIBUTOR_CODE,
         DISTRIBUTOR_NAME,
         STORE_CODE,
         EAN,
         SOLDTO_CODE,
         YEAR,
         MNTH_ID,
         CNTRY_CD,
         CNTRY_NM,
         DATA_SRC,
         STORE_NAME,
         RETAIL_ENVIRONMENT,
		 store_type,
		 store_grade,list_price,msl_product_desc,sku_code,
	     Region,zone_or_area,
         CHANNEL_NAME,
         SAP_PARENT_CUSTOMER_KEY,
         SAP_PARENT_CUSTOMER_DESCRIPTION,
         SAP_CUSTOMER_CHANNEL_KEY,
         SAP_CUSTOMER_CHANNEL_DESCRIPTION,
         SAP_CUSTOMER_SUB_CHANNEL_KEY,
         SAP_SUB_CHANNEL_DESCRIPTION,
         SAP_GO_TO_MDL_KEY,
         SAP_GO_TO_MDL_DESCRIPTION,
         SAP_BANNER_KEY,
         SAP_BANNER_DESCRIPTION,
         SAP_BANNER_FORMAT_KEY,
         SAP_BANNER_FORMAT_DESCRIPTION,
         CUSTOMER_SEGMENT_KEY,
         CUSTOMER_SEGMENT_DESCRIPTION,
         GLOBAL_PRODUCT_FRANCHISE,
         GLOBAL_PRODUCT_BRAND,
         GLOBAL_PRODUCT_SUB_BRAND,
         GLOBAL_PRODUCT_VARIANT,
         GLOBAL_PRODUCT_SEGMENT,
         GLOBAL_PRODUCT_SUBSEGMENT,
         GLOBAL_PRODUCT_CATEGORY,
         GLOBAL_PRODUCT_SUBCATEGORY,
         GLOBAL_PUT_UP_DESCRIPTION,
         PKA_PRODUCT_KEY,
         PKA_PRODUCT_KEY_DESCRIPTION
),
final as
(
select 
cntry_cd::varchar(2) as cntry_cd,
sellout_dim_key::varchar(32) as sellout_dim_key,
cntry_nm::varchar(50) as cntry_nm,
data_src::varchar(14) as data_src,
soldto_code::varchar(255) as soldto_code,
distributor_code::varchar(32) as distributor_code,
distributor_name::varchar(255) as distributor_name,
store_code::varchar(100) as store_code,
store_grade::varchar(150) as store_grade,
list_price::numeric(38,6) as list_price,
msl_product_desc::varchar(300) as msl_product_desc,
sku_code::varchar(40) as sku_code,
ean::varchar(150) as ean,
store_name::varchar(601) as store_name,
retail_environment::varchar(225) as retail_environment,
store_type::varchar(255) as store_type,
region::varchar(150) as region,
zone_or_area::varchar(150) as zone_or_area,
channel_name::varchar(150) as channel_name,
sap_parent_customer_key::varchar(12) as sap_parent_customer_key,
sap_parent_customer_description::varchar(75) as sap_parent_customer_description,
sap_customer_channel_key::varchar(12) as sap_customer_channel_key,
sap_customer_channel_description::varchar(75) as sap_customer_channel_description,
sap_customer_sub_channel_key::varchar(12) as sap_customer_sub_channel_key,
sap_sub_channel_description::varchar(75) as sap_sub_channel_description,
sap_go_to_mdl_key::varchar(12) as sap_go_to_mdl_key,
sap_go_to_mdl_description::varchar(75) as sap_go_to_mdl_description,
sap_banner_key::varchar(12) as sap_banner_key,
sap_banner_description::varchar(75) as sap_banner_description,
sap_banner_format_key::varchar(12) as sap_banner_format_key,
sap_banner_format_description::varchar(75) as sap_banner_format_description,
customer_segment_key::varchar(12) as customer_segment_key,
customer_segment_description::varchar(50) as customer_segment_description,
global_product_franchise::varchar(30) as global_product_franchise,
global_product_brand::varchar(30) as global_product_brand,
global_product_sub_brand::varchar(100) as global_product_sub_brand,
global_product_variant::varchar(100) as global_product_variant,
global_product_segment::varchar(50) as global_product_segment,
global_product_subsegment::varchar(100) as global_product_subsegment,
global_product_category::varchar(50) as global_product_category,
global_product_subcategory::varchar(50) as global_product_subcategory,
global_put_up_description::varchar(100) as global_put_up_description,
pka_product_key::varchar(68) as pka_product_key,
pka_product_key_description::varchar(255) as pka_product_key_description,
year::numeric(18,0)as year,
mnth_id::varchar(23) as mnth_id,
sales_value_list_price::numeric(38,12) as sales_value_list_price,
so_sls_qty::numeric(38,6) as so_sls_qty,
so_sls_value::numeric(38,6) as so_sls_value,
so_avg_qty::numeric(10,2) as so_avg_qty,
crt_dttm::timestamp without time zone as crt_dttm
from anz_sellout_base_retail_excellence
)
--final select
select * from final

