with source as
(
    select * from {{ ref('inditg_integration__itg_billing_conditions') }}
),
final as
(
    select * from source
)
select bill_num::varchar(10) as bill_num,
    bill_item::number(18,0) as bill_item,
    bic_zstepnum::number(18,0) as bic_zstepnum,
    kncounter::number(18,0) as kncounter,
    doc_number::varchar(10) as doc_number,
    s_ord_item::number(18,0) as s_ord_item,
    knart::varchar(4) as knart,
    ch_on::number(18,0) as ch_on,
    comp_code::varchar(4) as comp_code,
    sales_dist::varchar(6) as sales_dist,
    bill_type::varchar(4) as bill_type,
    bill_date::date as bill_date,
    bill_cat::varchar(1) as bill_cat,
    loc_currcy::varchar(8) as loc_currcy,
    cust_group::varchar(2) as cust_group,
    sold_to::varchar(10) as sold_to,
    payer::varchar(10) as payer,
    exrate_acc::number(37,17) as exrate_acc,
    stat_curr::varchar(5) as stat_curr,
    doc_categ::varchar(2) as doc_categ,
    salesorg::varchar(4) as salesorg,
    distr_chan::varchar(2) as distr_chan,
    doc_currcy::varchar(5) as doc_currcy,
    createdon::number(18,0) as createdon,
    co_area::varchar(4) as co_area,
    costcenter::varchar(10) as costcenter,
    trans_date::number(18,0) as trans_date,
    exchg_rate::number(37,6) as exchg_rate,
    cust_grp1::varchar(3) as cust_grp1,
    cust_grp2::varchar(3) as cust_grp2,
    cust_grp3::varchar(3) as cust_grp3,
    cust_grp4::varchar(3) as cust_grp4,
    cust_grp5::varchar(3) as cust_grp5,
    matl_group::varchar(9) as matl_group,
    material::varchar(18) as material,
    mat_entrd::varchar(18) as mat_entrd,
    matl_grp_1::varchar(3) as matl_grp_1,
    matl_grp_2::varchar(3) as matl_grp_2,
    matl_grp_3::varchar(3) as matl_grp_3,
    matl_grp_4::varchar(3) as matl_grp_4,
    matl_grp_5::varchar(3) as matl_grp_5,
    billtoprty::varchar(10) as billtoprty,
    ship_to::varchar(10) as ship_to,
    itm_type::varchar(1) as itm_type,
    prod_hier::varchar(18) as prod_hier,
    prov_group::varchar(2) as prov_group,
    price_date::number(18,0) as price_date,
    item_categ::varchar(4) as item_categ,
    div_head::varchar(2) as div_head,
    division::varchar(2) as division,
    stat_date::number(18,0) as stat_date,
    refer_doc::varchar(10) as refer_doc,
    refer_itm::number(37,17) as refer_itm,
    sales_off::varchar(4) as sales_off,
    sales_grp::varchar(3) as sales_grp,
    wbs_elemt::varchar(24) as wbs_elemt,
    calday::number(18,0) as calday,
    calmonth::number(18,0) as calmonth,
    calweek::number(18,0) as calweek,
    fiscper::number(18,0) as fiscper,
    fiscvarnt::varchar(2) as fiscvarnt,
    knclass::varchar(4) as knclass,
    knorigin::varchar(4) as knorigin,
    kntyp::varchar(4) as kntyp,
    knval::number(37,17) as knval,
    kprice::number(37,17) as kprice,
    kinak::varchar(1) as kinak,
    kstat::varchar(1) as kstat,
    storno::varchar(1) as storno,
    rt_promo::varchar(10) as rt_promo,
    rebate_grp::varchar(2) as rebate_grp,
    bwapplnm::varchar(30) as bwapplnm,
    processkey::number(18,0) as processkey,
    eanupc::varchar(18) as eanupc,
    createdby::varchar(12) as createdby,
    serv_date::number(18,0) as serv_date,
    inv_qty::varchar(50) as inv_qty,
    forwagent::varchar(10) as forwagent,
    salesemply::number(18,0) as salesemply,
    sales_unit::varchar(3) as sales_unit,
    kappl::varchar(2) as kappl,
    acrn_id::varchar(2) as acrn_id,
    recordmode::varchar(1) as recordmode,
    crt_dttm::timestamp_ntz(9) as crt_dttm,
    updt_dttm::timestamp_ntz(9) as updt_dttm
from final