--import cte
with edw_rpt_regional_sellout_offtake as (
    select * from {{ source('aspedw_integration', 'edw_rpt_regional_sellout_offtake') }}
),
edw_vw_cal_retail_excellence_dim as (
    select * from {{ source('aspedw_integration', 'edw_vw_cal_retail_excellence_dim') }}
),
singapore_regional_sellout_mapped_sku_cd as (
    select * from {{ ref('sgpwks_integration__wks_singapore_regional_sellout_mapped_sku_cd') }}
),

--final cte
singapore_base_retail_excellence as 
(
SELECT COUNTRY_CODE AS CNTRY_CD,
       COUNTRY_NAME AS CNTRY_NM,
       DATA_SOURCE,
       MD5(NVL (SOLDTO_CODE,'stc') ||NVL (DISTRIBUTOR_CODE,'dc') ||NVL (DISTRIBUTOR_NAME,'dn') ||NVL (STORE_CODE,'sc') || NVL (STORE_NAME,'sn')
       || NVL (MSL_PRODUCT_CODE,'SKU') || NVL (SAP_PARENT_CUSTOMER_KEY,'spck') || NVL (SAP_PARENT_CUSTOMER_DESCRIPTION,'spscd')
       || NVL (SAP_CUSTOMER_CHANNEL_KEY,'scck') ||NVL (SAP_CUSTOMER_CHANNEL_DESCRIPTION,'sccd') || NVL (SAP_CUSTOMER_SUB_CHANNEL_KEY,'scsck')
       || NVL (SAP_SUB_CHANNEL_DESCRIPTION,'sscd') ||NVL (CUSTOMER_SEGMENT_KEY,'csk') || NVL (CUSTOMER_SEGMENT_DESCRIPTION,'csd')
       || NVL (SAP_GO_TO_MDL_KEY,'sgmk') ||NVL (SAP_GO_TO_MDL_DESCRIPTION,'sgmd') || NVL (SAP_BANNER_KEY,'sbk') ||NVL (SAP_BANNER_DESCRIPTION,'sbd')
       || NVL (SAP_BANNER_FORMAT_KEY,'sbfk') || NVL (SAP_BANNER_FORMAT_DESCRIPTION,'sbfd') ||NVL (RETAIL_ENVIRONMENT,'re')
       || NVL (GLOBAL_PRODUCT_FRANCHISE,'gpf') || NVL (GLOBAL_PRODUCT_BRAND,'gpb') ||NVL (GLOBAL_PRODUCT_SUB_BRAND,'gpsb')
       || NVL (GLOBAL_PRODUCT_VARIANT,'gpv') || NVL (GLOBAL_PRODUCT_SEGMENT,'gps') ||NVL (GLOBAL_PRODUCT_SUBSEGMENT,'gpss')
       || NVL (GLOBAL_PRODUCT_CATEGORY,'gpc') || NVL (GLOBAL_PRODUCT_SUBCATEGORY,'gpsc') ||NVL (GLOBAL_PUT_UP_DESCRIPTION,'gpud')
       || NVL (MAPPED_SKU_CD,'msc') || NVL (SKU_DESCRIPTION,'skud') || NVL (PKA_PRODUCT_KEY,'pk') ||NVL (PKA_PRODUCT_KEY_DESCRIPTION,'pkd')
       ||NVL (store_type,'st') ||NVL (Region,'rg') || NVL (zone_or_area,'ar')) AS SELLOUT_DIM_KEY,
       YEAR,
       MNTH_ID,
       LTRIM(SOLDTO_CODE,'0') AS SOLDTO_CODE,
       DISTRIBUTOR_CODE,
       DISTRIBUTOR_NAME|| '#' ||ltrim(DISTRIBUTOR_CODE,'0') AS DISTRIBUTOR_NAME,
       STORE_CODE,
       STORE_NAME|| '#' ||ltrim(STORE_CODE,'0') AS STORE_NAME,
       MSL_PRODUCT_CODE AS MASTER_CODE,
       MSCD.SKU_DESCRIPTION AS CUSTOMER_PRODUCT_DESC,		--//        MSCD.SKU_DESCRIPTION AS CUSTOMER_PRODUCT_DESC,
       STORE_TYPE,
       SAP_PARENT_CUSTOMER_KEY,
       SAP_PARENT_CUSTOMER_DESCRIPTION,
       SAP_CUSTOMER_CHANNEL_KEY,
       SAP_CUSTOMER_CHANNEL_DESCRIPTION,
       SAP_CUSTOMER_SUB_CHANNEL_KEY,
       SAP_SUB_CHANNEL_DESCRIPTION,
       SAP_GO_TO_MDL_KEY,
       SAP_GO_TO_MDL_DESCRIPTION,
       SAP_BANNER_KEY,
       SAP_BANNER_DESCRIPTION,
       SAP_BANNER_FORMAT_KEY,
       SAP_BANNER_FORMAT_DESCRIPTION,
       RETAIL_ENVIRONMENT,
       REGION,
       ZONE_OR_AREA,
       CUSTOMER_SEGMENT_KEY,
       CUSTOMER_SEGMENT_DESCRIPTION,
       GLOBAL_PRODUCT_FRANCHISE,
       GLOBAL_PRODUCT_BRAND,
       GLOBAL_PRODUCT_SUB_BRAND,
       GLOBAL_PRODUCT_VARIANT,
       GLOBAL_PRODUCT_SEGMENT,
       GLOBAL_PRODUCT_SUBSEGMENT,
       GLOBAL_PRODUCT_CATEGORY,
       GLOBAL_PRODUCT_SUBCATEGORY,
       GLOBAL_PUT_UP_DESCRIPTION,
       MSCD.MAPPED_SKU_CD AS MAPPED_SKU_CD,		--//        MSCD.MAPPED_SKU_CD AS MAPPED_SKU_CD,
       PKA_PRODUCT_KEY,
       PKA_PRODUCT_KEY_DESCRIPTION,
       SUM(SELLOUT_SALES_QUANTITY):: DECIMAL(38,6) AS SO_SLS_QTY,
       SUM(SELLOUT_SALES_VALUE) :: NUMERIC(38,6) AS SO_SLS_VALUE,
       TRUNC(AVG(SELLOUT_SALES_QUANTITY) :: DECIMAL(38,6)) AS SO_AVG_QTY,		--// AVG
       SUM(SALES_VALUE_LIST_PRICE) AS SALES_VALUE_LIST_PRICE,
SYSDATE()	as crt_dttm	--// SYSDATE
FROM (SELECT COUNTRY_CODE,
             COUNTRY_NAME,
             DATA_SOURCE,
             YEAR,
             MNTH_ID,
             MAX(SOLDTO_CODE) OVER (PARTITION BY LTRIM(DISTRIBUTOR_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS SOLDTO_CODE,
             LTRIM(DISTRIBUTOR_CODE,'0') AS DISTRIBUTOR_CODE,
             MAX(DISTRIBUTOR_NAME) OVER (PARTITION BY LTRIM(DISTRIBUTOR_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS DISTRIBUTOR_NAME,
             LTRIM(STORE_CODE,'0') AS STORE_CODE,
             MAX(STORE_NAME) OVER (PARTITION BY LTRIM(STORE_CODE,'0') ORDER BY cal_date DESC ROWS BETWEEN UNBOUNDED PRECEDING AND UNBOUNDED FOLLOWING) AS STORE_NAME,
             LTRIM(MSL_PRODUCT_CODE,'0') AS MSL_PRODUCT_CODE,
             STORE_TYPE,
             SAP_PARENT_CUSTOMER_KEY,
             SAP_PARENT_CUSTOMER_DESCRIPTION,
             SAP_CUSTOMER_CHANNEL_KEY,
             SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             SAP_CUSTOMER_SUB_CHANNEL_KEY,
             SAP_SUB_CHANNEL_DESCRIPTION,
             SAP_GO_TO_MDL_KEY,
             SAP_GO_TO_MDL_DESCRIPTION,
             SAP_BANNER_KEY,
             SAP_BANNER_DESCRIPTION,
             SAP_BANNER_FORMAT_KEY,
             SAP_BANNER_FORMAT_DESCRIPTION,
             RETAIL_ENV AS RETAIL_ENVIRONMENT,
             REGION,
             ZONE_OR_AREA,
             CUSTOMER_SEGMENT_KEY,
             CUSTOMER_SEGMENT_DESCRIPTION,
             GLOBAL_PRODUCT_FRANCHISE,
             GLOBAL_PRODUCT_BRAND,
             GLOBAL_PRODUCT_SUB_BRAND,
             GLOBAL_PRODUCT_VARIANT,
             GLOBAL_PRODUCT_SEGMENT,
             GLOBAL_PRODUCT_SUBSEGMENT,
             GLOBAL_PRODUCT_CATEGORY,
             GLOBAL_PRODUCT_SUBCATEGORY,
             GLOBAL_PUT_UP_DESCRIPTION,
             PKA_PRODUCT_KEY,
             PKA_PRODUCT_KEY_DESCRIPTION,
             SELLOUT_SALES_QUANTITY,
             SELLOUT_SALES_VALUE,
             SELLOUT_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE
      FROM edw_rpt_regional_sellout_offtake		--//       FROM RG_EDW.EDW_RPT_REGIONAL_SELLOUT_OFFTAKE
      WHERE COUNTRY_CODE = 'SG'
      AND   DATA_SOURCE = 'POS'
	  ) MAIN
  LEFT JOIN singapore_regional_sellout_mapped_sku_cd MSCD ON LTRIM (MAIN.MSL_PRODUCT_CODE,'0') = LTRIM (MSCD.MASTER_CODE,'0')		--//   LEFT JOIN OS_WKS.WKS_SINGAPORE_REGIONAL_SELLOUT_MAPPED_SKU_CD MSCD ON LTRIM (MAIN.MSL_PRODUCT_CODE,'0') = LTRIM (MSCD.MASTER_CODE,'0')
GROUP BY COUNTRY_CODE,
         COUNTRY_NAME,
         DATA_SOURCE,
         YEAR,
         MNTH_ID,
         SOLDTO_CODE,
         DISTRIBUTOR_CODE,
         DISTRIBUTOR_NAME,
         STORE_CODE,
         STORE_NAME,
         MSL_PRODUCT_CODE,
         CUSTOMER_PRODUCT_DESC,
         STORE_TYPE,
         SAP_PARENT_CUSTOMER_KEY,
         SAP_PARENT_CUSTOMER_DESCRIPTION,
         SAP_CUSTOMER_CHANNEL_KEY,
         SAP_CUSTOMER_CHANNEL_DESCRIPTION,
         SAP_CUSTOMER_SUB_CHANNEL_KEY,
         SAP_SUB_CHANNEL_DESCRIPTION,
         SAP_GO_TO_MDL_KEY,
         SAP_GO_TO_MDL_DESCRIPTION,
         SAP_BANNER_KEY,
         SAP_BANNER_DESCRIPTION,
         SAP_BANNER_FORMAT_KEY,
         SAP_BANNER_FORMAT_DESCRIPTION,
         RETAIL_ENVIRONMENT,
         REGION,
         ZONE_OR_AREA,
         CUSTOMER_SEGMENT_KEY,
         CUSTOMER_SEGMENT_DESCRIPTION,
         GLOBAL_PRODUCT_FRANCHISE,
         GLOBAL_PRODUCT_BRAND,
         GLOBAL_PRODUCT_SUB_BRAND,
         GLOBAL_PRODUCT_VARIANT,
         GLOBAL_PRODUCT_SEGMENT,
         GLOBAL_PRODUCT_SUBSEGMENT,
         GLOBAL_PRODUCT_CATEGORY,
         GLOBAL_PRODUCT_SUBCATEGORY,
         GLOBAL_PUT_UP_DESCRIPTION,
         MAPPED_SKU_CD,
         PKA_PRODUCT_KEY,
         PKA_PRODUCT_KEY_DESCRIPTION

),
final as
(
select 
cntry_cd::varchar(2) AS cntry_cd,	
cntry_nm::varchar(50) AS cntry_nm,	
data_source::varchar(14) AS data_source,	
sellout_dim_key::varchar(32) AS sellout_dim_key,	
year::numeric(18,0) AS year,	
mnth_id::varchar(23) AS mnth_id,	
soldto_code::varchar(255) AS soldto_code,	
distributor_code::varchar(100) AS distributor_code,	
distributor_name::varchar(356) AS distributor_name,	
store_code::varchar(100) AS store_code,	
store_name::varchar(601) AS store_name,	
master_code::varchar(150) AS master_code,	
customer_product_desc::varchar(150) AS customer_product_desc,	
store_type::varchar(255) AS store_type,	
sap_parent_customer_key::varchar(12) AS sap_parent_customer_key,	
sap_parent_customer_description::varchar(75) AS sap_parent_customer_description,	
sap_customer_channel_key::varchar(12) AS sap_customer_channel_key,	
sap_customer_channel_description::varchar(75) AS sap_customer_channel_description,	
sap_customer_sub_channel_key::varchar(12) AS sap_customer_sub_channel_key,	
sap_sub_channel_description::varchar(75) AS sap_sub_channel_description,	
sap_go_to_mdl_key::varchar(12) AS sap_go_to_mdl_key,	
sap_go_to_mdl_description::varchar(75) AS sap_go_to_mdl_description,	
sap_banner_key::varchar(12) AS sap_banner_key,	
sap_banner_description::varchar(75) AS sap_banner_description,	
sap_banner_format_key::varchar(12) AS sap_banner_format_key,	
sap_banner_format_description::varchar(75) AS sap_banner_format_description,	
retail_environment::varchar(150) AS retail_environment,	
region::varchar(150) AS region,	
zone_or_area::varchar(150) AS zone_or_area,	
customer_segment_key::varchar(12) AS customer_segment_key,	
customer_segment_description::varchar(50) AS customer_segment_description,	
global_product_franchise::varchar(30) AS global_product_franchise,	
global_product_brand::varchar(30) AS global_product_brand,	
global_product_sub_brand::varchar(100) AS global_product_sub_brand,	
global_product_variant::varchar(100) AS global_product_variant,	
global_product_segment::varchar(50) AS global_product_segment,	
global_product_subsegment::varchar(100) AS global_product_subsegment,	
global_product_category::varchar(50) AS global_product_category,	
global_product_subcategory::varchar(50) AS global_product_subcategory,	
global_put_up_description::varchar(100) AS global_put_up_description,	
mapped_sku_cd::varchar(40) AS mapped_sku_cd,	
pka_product_key::varchar(68) AS pka_product_key,	
pka_product_key_description::varchar(255) AS pka_product_key_description,	
so_sls_qty::numeric(38,6) AS so_sls_qty,	
so_sls_value::numeric(38,6) AS so_sls_value,	
so_avg_qty::numeric(38,6) AS so_avg_qty,	
sales_value_list_price::numeric(38,12) AS sales_value_list_price,	
crt_dttm::timestamp without time zone AS crt_dttm
from singapore_base_retail_excellence
)
--final select
select * from final

