with vw_rpt_th_gt_scorecard as(
 select * from {{ ref('thaedw_integration__vw_rpt_th_gt_scorecard') }}
)

SELECT identifier,
       cntry_cd,
       crncy_cd,
       cntry_nm,
       year_month,
       year,
       month,
       distributor_id,
       store_type,
       sales_area,
       sell_out_actual,
       gross_sell_out_actual,
       net_sell_out_actual,
       sell_out_target,
       msl_actual_count,
       msl_target_count,
       planned_call_count,
       visited_call_count,
       effective_call_count,
       sales_order_count,
       on_time_count,
       in_time_count,
       otif_count,
       coverage_stores_count,
       reactivate_stores_count,
       inactive_stores_count,
       active_stores_count,
       route_com_all,
	   effective_call_all,
       planned_store ,
       effective_store_in_plan,
       effective_store_all,
	   total_skus,
   	   total_stores
FROM vw_rpt_th_gt_scorecard
