with source as (
    select * from {{ source('myssdl_raw','sdl_mds_my_product_master') }}
),
final as
(
    select
        code::varchar(40) as item_cd,
        name::varchar(200) as item_desc,
        material_description::varchar(200) as item_desc2,
        material_type::varchar(10) as item_type,
        selling_status_code::varchar(40) as status,
        comm_status::varchar(40) as comm_status,
        pipo::varchar(40) as pipo_flag,
        franchise::varchar(100) as frnchse_desc,
        brand::varchar(100) as brnd_desc,
        variant::varchar(100) as vrnt_desc,
        put_up::varchar(40) as putup_desc,
        pack_size::varchar(40) as pack_size,
        platform::varchar(40) as platfrm,
        "normal/promo"::varchar(40) as promo_reg_ind,
        sap_valuation_class::varchar(40) as sap_val_class,
        product_barcode::varchar(40) as item_bar_cd,
        to_date(launch_date)::date as launch_dt,
        list_price::number(20,4) as list_prce,
        carton_price::number(20,4) as carton_prce,
        dz_price::number(20,4) as dz_prce,
        rsp::number(20,4) as rsp,
        rsp_w_gst::number(20,4) as rsp_with_gst,
        "trade_margin_%"::number(20,4) as trd_mrgin,
        "qty-shipper_(pc)"::number(20,4) as shipper_qty_pc,
        abc::varchar(40) as abc,
        remarks::varchar(255) as remrks,
        profit_center::varchar(40) as prft_cntr,
        "shelf_life_(years)"::number(20,4) as shelf_life,
        list_price_w_gst::number(20,4) as list_prce_with_gst,
        npi::varchar(10) as npi_ind,
        substring(to_date(npi_start_period, 'yyyymm'), 1, 4) + substring(to_date(npi_start_period, 'yyyymm'), 6, 2)::varchar(10) as npi_strt_period,
        hero_sku::varchar(10) as hero_ind,
        null::varchar(20) as cdl_dttm,
        current_timestamp()::timestamp_ntz(9) as crtd_dttm,
        current_timestamp()::timestamp_ntz(9) as updt_dttm,
        selling_status_name::varchar(500) as selling_status_name,
        selling_status_id::number(18,0) as selling_status_id,
        stronghold::varchar(200) as stronghold,
        category::varchar(200) as category,
        predecessor_material_code::varchar(200) as predecessor_material_code,
        predecessor_material_desc::varchar(200) as predecessor_material_desc,
        project_name::varchar(200) as project_name,
        supplier::varchar(200) as supplier,
        primary_source::varchar(200) as primary_source,
        material_code_desc::varchar(200) as material_code_desc,
        "product_dimension-l_(mm)"::number(31,2) as "product_dimension-l_(mm)",
        "product_dimension-w_(mm)"::number(31,2) as "product_dimension-w_(mm)",
        "product_dimension-h_(mm)"::number(31,3) as "product_dimension-h_(mm)",
        "product_dimension-m3"::number(31,2) as "product_dimension-m3",
        "shipper_dimension-l_(mm)"::number(31,2) as "shipper_dimension-l_(mm)",
        "shipper_dimension-w_(mm)"::number(31,2) as "shipper_dimension-w_(mm)",
        "shipper_dimension-h_(mm)"::number(31,2) as "shipper_dimension-h_(mm)",
        "shipper_dimension-m3"::number(31,2) as "shipper_dimension-m3",
        product_weight::number(31,0) as product_weight,
        bundle_barcode::varchar(200) as bundle_barcode,
        shipper_barcode::varchar(200) as shipper_barcode,
        "qty-inner_shipper_(pc)"::number(31,0) as "qty-inner_shipper_(pc)",
        "qty-shrink_wrap_(pc)"::number(31,0) as "qty-shrink_wrap_(pc)",
        "qty-shipper/layer"::number(31,0) as "qty-shipper/layer",
        "qty-layer/pallet"::number(31,0) as "qty-layer/pallet",
        "qty-shipper/pallet"::number(31,0) as "qty-shipper/pallet",
        "qty-dz/pallet"::number(31,0) as "qty-dz/pallet",
        "apo-master_code"::varchar(200) as "apo-master_code",
        "apo-product_classification"::varchar(200) as "apo-product_classification",
        "apo-dp_product_type"::varchar(200) as "apo-dp_product_type",
        "apo-copy_history"::varchar(200) as "apo-copy_history",
        "apo-forecast_ind"::varchar(200) as "apo-forecast_ind",
        "apo-npi_indicator"::varchar(200) as "apo-npi_indicator",
        "bnd-zcpe"::number(31,2) as "bnd-zcpe",
        "bn-list_price"::number(31,2) as "bn-list_price",
        "bnd-list_price"::number(31,2) as "bnd-list_price",
        "bn-duty"::number(31,2) as "bn-duty",
        "bnd-rcp"::number(31,2) as "bnd-rcp",
        "bnd-rcp(duty)"::number(31,2) as "bnd-rcp(duty)",
        "bn-trade_margin"::number(31,2) as "bn-trade_margin",
        compliance_asset_id::varchar(200) as compliance_asset_id,
        attachments::number(31,0) as attachments,
    from source
)
select * from final