with edw_vw_sfmc_analysis as (
    select * from snapntaedw_integration.edw_vw_sfmc_analysis
),
edw_calendar_dim as (
    select * from snapaspedw_integration.edw_calendar_dim
),
itg_query_parameters as (
    select * from snapaspitg_integration.itg_query_parameters
),
union_1 as 
(   
    SELECT 
        data_src,
        country_code,
        country_name,
        created_date,
        invoicec_created_date,
        invoice_completed_date,
        last_logon_time,
        purchase_date,
        redeemed_date,
        redeemption_completed_date,
        first_name,
        last_name,
        consumer_name,
        mobile_number,
        subscriber_key,
        mobile_country_code,
        address_country,
        address_region,
        address_1,
        address_2,
        line_id,
        address,
        birth_month,
        birth_year,
        consumer_age,
        consumer_age_group,
        email,
        gender,
        channel_name,
        brand,
        product_name,
        product_category,
        tier,
        remaining_points,
        customer_redeemed_points,
        total_points,
        invoive_number,
        invoice_qty,
        invoice_type,
        invoice_seller_name,
        invoice_points,
        invoice_status,
        child_name,
        child_birth_month,
        child_birth_year,
        child_gender,
        child_number,
        child_age,
        child_group,
        child_flag,
        redeemed_order_number,
        redeemed_prod_name,
        redemption_status,
        redeemed_points,
        redeemed_qty,
        activity_date,
        local_activity_date,
        sent_activity_date,
        email_name,
        email_subject,
        sent_email_name,
        sent_email_subject,
        email_delivered_flag,
        is_unique,
        url,
        link_name,
        link_content,
        bounce_reason,
        bounce_type,
        bounce_description,
        data_refresh_time,
        active_flag,
        inv_cnt
    FROM edw_vw_sfmc_analysis
    where country_code = 'TW'
),

--To add the data for invoice points based on product category (to solve the rollup sum issue for missed product categories in tableau dashboard)
union_2 as
(    
    select 
        data_src,
        country_code,
        country_name,
        created_date,
        invoicec_created_date,
        invoice_completed_date,
        last_logon_time,
        purchase_date,
        redeemed_date,
        redeemption_completed_date,
        first_name,
        last_name,
        consumer_name,
        mobile_number,
        subscriber_key,
        mobile_country_code,
        address_country,
        address_region,
        address_1,
        address_2,
        line_id,
        address,
        birth_month,
        birth_year,
        consumer_age,
        consumer_age_group,
        email,
        gender,
        channel_name,
        brand,
        product_name,
        product_category,
        tier,
        remaining_points,
        customer_redeemed_points,
        total_points,
        invoive_number,
        invoice_qty,
        invoice_type,
        invoice_seller_name,
        invoice_points,
        invoice_status,
        child_name,
        child_birth_month,
        child_birth_year,
        child_gender,
        child_number,
        child_age,
        child_group,
        child_flag,
        redeemed_order_number,
        redeemed_prod_name,
        redemption_status,
        redeemed_points,
        redeemed_qty,
        activity_date,
        local_activity_date,
        sent_activity_date,
        email_name,
        email_subject,
        sent_email_name,
        sent_email_subject,
        email_delivered_flag,
        is_unique,
        url,
        link_name,
        link_content,
        bounce_reason,
        bounce_type,
        bounce_description,
        data_refresh_time,
        active_flag,
        inv_cnt
    from 
        (
            select 
                'INV_CNT' as data_src,
                base.country_code as country_code,
                base.country_name as country_name,
                to_date((base.cal_mo_1||'01'),'yyyymmdd') as created_date,
                null::date as invoicec_created_date,
                null::date as invoice_completed_date,
                null::date as last_logon_time,
                null::date as purchase_date,
                null::date as redeemed_date,
                null::date as redeemption_completed_date,
                null as first_name,
                null as last_name,
                null as consumer_name,
                null as mobile_number,
                null as subscriber_key,
                null as mobile_country_code,
                null as address_country,
                null as address_region,
                null as address_1,
                null as address_2,
                null as line_id,
                null as address,
                null as birth_month,
                null as birth_year,
                null as consumer_age,
                null as consumer_age_group,
                null as email,
                null as gender,
                base.channel_name as channel_name,
                base.brand as brand,
                null as product_name,
                base.product_category as product_category,
                null as tier,
                null as remaining_points,
                null as customer_redeemed_points,
                null::integer as total_points,
                null as invoive_number,
                null as invoice_qty,
                null as invoice_type,
                null as invoice_seller_name,
                null::integer as invoice_points,
                base.invoice_status as invoice_status,
                null as child_name,
                null as child_birth_month,
                null as child_birth_year,
                null as child_gender,
                null as child_number,
                null as child_age,
                null as child_group,
                null as child_flag,
                null as redeemed_order_number,
                null as redeemed_prod_name,
                null as redemption_status,
                null as redeemed_points,
                null as redeemed_qty,
                null::date as activity_date,
                null::date as local_activity_date,
                null::date as sent_activity_date,
                null as email_name,
                null as email_subject,
                null as sent_email_name,
                null as sent_email_subject,
                null as email_delivered_flag,
                null as is_unique,
                null as url,
                null as link_name,
                null as link_content,
                null as bounce_reason,
                null as bounce_type,
                null as bounce_description,
                null::date as data_refresh_time,
                null as active_flag,
                cnt.inv_cnt as inv_cnt
            from 
                (
                    select distinct country_code,
                        country_name,
                        channel_name,
                        brand,
                        product_category,
                        invoice_status,
                        cal_mo_1
                    from union_1,
                    (
                        select distinct cal_mo_1
                        from edw_calendar_dim
                        where cal_yr >= 
                        (
                            select parameter_value from itg_query_parameters
                            where country_code = 'TW' and parameter_name = 'TW_SFMC'
                        ) --to_char(current_timestamp  , 'yyyy')-(select parameter_value from rg_itg.itg_query_parameters where country_code='TW' and parameter_name='TW_SFMC')
                            and cal_day <= current_timestamp
                    )
                    where data_src = 'INVOICE'
                ) base
                LEFT JOIN 
                (
                    select country_code,
                        country_name,
                        channel_name,
                        brand,
                        product_category,
                        invoice_status,
                        to_char(invoicec_created_date, 'yyyymm') inv_ym,
                        count(distinct invoive_number) inv_cnt
                    from 
                        (
                            select country_code,
                                country_name,
                                channel_name,
                                brand,
                                product_category,
                                invoice_status,
                                min(invoicec_created_date) as invoicec_created_date,
                                invoive_number
                            from union_1
                            where data_src = 'INVOICE'
                                and invoice_status = 'Approved'
                                and invoice_points > 0
                            group by country_code,
                                country_name,
                                channel_name,
                                brand,
                                product_category,
                                invoice_status,
                                invoive_number
                        )
                    group by country_code,
                        country_name,
                        channel_name,
                        brand,
                        product_category,
                        invoice_status,
                        to_char(invoicec_created_date, 'yyyymm')
                ) cnt ON base.country_code = cnt.country_code
                and base.country_name = cnt.country_name
                and nvl(base.channel_name, 'NA') = nvl(cnt.channel_name, 'NA')
                and base.brand = cnt.brand
                and base.product_category = cnt.product_category
                and base.invoice_status = cnt.invoice_status
                and base.cal_mo_1 = cnt.inv_ym
            where base.product_category is not null
        )
),
final as 
(
    select 
        data_src::varchar(11) as data_src,
        country_code::varchar(10) as country_code,
        country_name::varchar(10) as country_name,
        created_date::date as created_date,
        invoicec_created_date::date as invoicec_created_date,
        invoice_completed_date::date as invoice_completed_date,
        last_logon_time::date as last_logon_time,
        purchase_date::date as purchase_date,
        redeemed_date::date as redeemed_date,
        redeemption_completed_date::date as redeemption_completed_date,
        first_name::varchar(200) as first_name,
        last_name::varchar(200) as last_name,
        consumer_name::varchar(401) as consumer_name,
        mobile_number::varchar(30) as mobile_number,
        subscriber_key::varchar(100) as subscriber_key,
        mobile_country_code::varchar(10) as mobile_country_code,
        address_country::varchar(100) as address_country,
        address_region::varchar(100) as address_region,
        address_1::varchar(255) as address_1,
        address_2::varchar(255) as address_2,
        line_id::varchar(50) as line_id,
        address::varchar(488) as address,
        birth_month::varchar(10) as birth_month,
        birth_year::varchar(10) as birth_year,
        consumer_age::varchar(40) as consumer_age,
        consumer_age_group::varchar(9) as consumer_age_group,
        email::varchar(100) as email,
        gender::varchar(100) as gender,
        channel_name::varchar(200) as channel_name,
        brand::varchar(200) as brand,
        product_name::varchar(200) as product_name,
        product_category::varchar(200) as product_category,
        tier::varchar(100) as tier,
        remaining_points::number(10,4) as remaining_points,
        customer_redeemed_points::number(10,4) as customer_redeemed_points,
        total_points::number(10,4) as total_points,
        invoive_number::varchar(50) as invoive_number,
        invoice_qty::number(20,4) as invoice_qty,
        invoice_type::varchar(200) as invoice_type,
        invoice_seller_name::varchar(255) as invoice_seller_name,
        invoice_points::number(18,0) as invoice_points,
        invoice_status::varchar(50) as invoice_status,
        child_name::varchar(50) as child_name,
        child_birth_month::varchar(10) as child_birth_month,
        child_birth_year::varchar(10) as child_birth_year,
        child_gender::varchar(100) as child_gender,
        child_number::varchar(30) as child_number,
        child_age::varchar(40) as child_age,
        child_group::varchar(19) as child_group,
        child_flag::varchar(12) as child_flag,
        redeemed_order_number::varchar(50) as redeemed_order_number,
        redeemed_prod_name::varchar(255) as redeemed_prod_name,
        redemption_status::varchar(100) as redemption_status,
        redeemed_points::number(20,4) as redeemed_points,
        redeemed_qty::number(20,4) as redeemed_qty,
        activity_date::timestamp_ntz(9) as activity_date,
        local_activity_date::timestamp_ntz(9) as local_activity_date,
        sent_activity_date::timestamp_ntz(9) as sent_activity_date,
        email_name::varchar(100) as email_name,
        email_subject::varchar(200) as email_subject,
        sent_email_name::varchar(100) as sent_email_name,
        sent_email_subject::varchar(200) as sent_email_subject,
        email_delivered_flag::varchar(10) as email_delivered_flag,
        is_unique::varchar(10) as is_unique,
        url::varchar(1000) as url,
        link_name::varchar(200) as link_name,
        link_content::varchar(1000) as link_content,
        bounce_reason::varchar(30) as bounce_reason,
        bounce_type::varchar(30) as bounce_type,
        bounce_description::varchar(1000) as bounce_description,
        data_refresh_time::timestamp_ntz(9) as data_refresh_time,
        active_flag::varchar(10) as active_flag,
        inv_cnt::number(18,0) as inv_cnt
    from
    (
        select * from union_1
        union all
        select * from union_2
    )
)
select * from final