--import cte

with wks_cnpc_rpt_retail_excellence_sop as 
(
    select * from {{ ref('chnwks_integration__wks_china_personal_care_rpt_retail_excellence_sop' )}}
),
wks_cnpc_re_target_compliance as 
(
    select * from {{ ref('chnwks_integration__wks_china_personal_care_re_target_compliance' )}}
),

--final cte

edw_cnpc_rpt_retail_excellence as 
(
select
 dm.fisc_yr,
       dm.fisc_per,
       dm."cluster",
       dm.market,
       dm.data_src,
       dm.sell_out_channel as channel_name,
	   dm.soldto_code,
       dm.distributor_code,
       dm.distributor_name,
       dm.sell_out_channel,
       dm.store_type,
       null as prioritization_segmentation,
       null as store_category,
       dm.store_code,
       dm.store_name,
       null as store_grade,
       null as store_size,
       dm.region,
       dm.zone_name,
       null as city,
       null as rtrlatitude,
       null as rtrlongitude,
       dm.customer_segment_key,
       dm.customer_segment_description,
       dm.sell_out_re as retail_environment,
       dm.sap_parent_customer_key,
       dm.sap_parent_customer_description,
       dm.sap_customer_channel_key,
       dm.sap_customer_channel_description,
       dm.sap_customer_sub_channel_key,
       dm.sap_sub_channel_description,
       --dm.sap_go_to_mdl_key,
       -- dm.sap_go_to_mdl_description,
       dm.sap_banner_key,
       dm.sap_banner_description,
       dm.sap_banner_format_key,
       dm.sap_banner_format_description,
       null as customer_name,
       null as customer_code,
       dm.product_code,
       dm.product_name,
       prod_hier_l1,
       null as prod_hier_l2,
       null as prod_hier_l3,
       dm.prod_hier_l4,
       dm.prod_hier_l5,
       dm.prod_hier_l6,
       null as prod_hier_l7,
       null as prod_hier_l8,
       dm.prod_hier_l9,
       dm.mapped_sku_cd,
       -- dm.sap_matl_num,
       -- dm.sap_mat_desc,
       dm.sap_prod_sgmt_cd,
       dm.sap_prod_sgmt_desc,
       --null as sap_base_prod_cd,
       dm.sap_base_prod_desc,
       --null as sap_mega_brnd_cd,
       dm.sap_mega_brnd_desc,
       --null as sap_brnd_cd,
       dm.sap_brnd_desc,
       --null as sap_vrnt_cd,
       dm.sap_vrnt_desc,
       --null as sap_put_up_cd,
       dm.sap_put_up_desc,
       dm.sap_grp_frnchse_cd,
       dm.sap_grp_frnchse_desc,
       dm.sap_frnchse_cd,
       dm.sap_frnchse_desc,
       dm.sap_prod_frnchse_cd,
       dm.sap_prod_frnchse_desc,
       dm.sap_prod_mjr_cd,
       dm.sap_prod_mjr_desc,
       dm.sap_prod_mnr_cd,
       dm.sap_prod_mnr_desc,
       dm.sap_prod_hier_cd,
       dm.sap_prod_hier_desc,
       --null as pka_franchise_cd, 
       dm.pka_franchise_desc,
       -- null as pka_brand_cd, 
       dm.pka_brand_desc,
       --null as pka_sub_brand_cd, 
       dm.pka_sub_brand_desc,
       --null as pka_variant_cd, 
       dm.pka_variant_desc,
       -- null as pka_sub_variant_cd, 
       dm.pka_sub_variant_desc,
       --gph_region,
       --gph_reg_frnchse,
       -- gph_reg_frnchse_grp,
       dm.global_product_franchise,
       dm.global_product_brand,
       dm.global_product_sub_brand,
       dm.global_product_variant,
       --gph_prod_needstate,
       dm.global_product_category,
       dm.global_product_subcategory,
       dm.global_product_segment,
       dm.global_product_subsegment,
       --gph_prod_put_up_cd,
       dm.global_put_up_description,
       ---gph_prod_size,
       ---gph_prod_size_uom,
      dm.ean as ean,
      -- dm.sap_matl_num as sku_code,
       --dm.sap_mat_desc as sku_description,
       -- null as greenlight_sku_flag,
       dm.pka_product_key,
       dm.pka_product_key_description,
       dm.sales_value,
       dm.sales_qty,
       dm.avg_sales_qty,
       dm.sales_value_list_price,
       dm.lm_sales,
       dm.lm_sales_qty,
       dm.lm_avg_sales_qty,
       dm.lm_sales_lp,
       dm.p3m_sales,
       dm.p3m_qty,
       dm.p3m_avg_qty,
       dm.p3m_sales_lp,
       dm.p6m_sales,
       dm.p6m_qty,
       dm.p6m_avg_qty,
       dm.p6m_sales_lp,
       dm.p12m_sales,
       dm.p12m_qty,
       dm.p12m_avg_qty,
       dm.p12m_sales_lp,
       dm.f3m_sales,
       dm.f3m_qty,
       dm.f3m_avg_qty,
       dm.lm_sales_flag,
       dm.p3m_sales_flag,
       dm.p6m_sales_flag,
       dm.p12m_sales_flag,
       dm.mdp_flag,
               --TARGET_COMPLAINCE,
        CASE 
            WHEN (MDP_FLAG = 'Y' AND UPPER(dm.global_product_brand) = UPPER(TRGT_CMP.global_product_brand)) THEN TRGT_CMP.TARGET_COMPLIANCE
            ELSE 100
            END AS TARGET_COMPLAINCE,
       dm.list_price,
       dm.total_sales_lm,
       dm.total_sales_p3m,
       dm.total_sales_p6m,
       dm.total_sales_p12m,
       dm.total_sales_by_store_lm,
       dm.total_sales_by_store_p3m,
       dm.total_sales_by_store_p6m,
       dm.total_sales_by_store_p12m,
       dm.total_sales_by_sku_lm,
       dm.total_sales_by_sku_p3m,
       dm.total_sales_by_sku_p6m,
       dm.total_sales_by_sku_p12m,
       dm.total_sales_lm_lp,
       dm.total_sales_p3m_lp,
       dm.total_sales_p6m_lp,
       dm.total_sales_p12m_lp,
       dm.total_sales_by_store_lm_lp,
       dm.total_sales_by_store_p3m_lp,
       dm.total_sales_by_store_p6m_lp,
       dm.total_sales_by_store_p12m_lp,
       dm.total_sales_by_sku_lm_lp,
       dm.total_sales_by_sku_p3m_lp,
       dm.total_sales_by_sku_p6m_lp,
       dm.total_sales_by_sku_p12m_lp,
       dm.store_contribution_lm,
       dm.sku_contribution_lm,
       dm.size_of_price_lm,
       dm.store_contribution_p3m,
       dm.sku_contribution_p3m,
       dm.size_of_price_p3m,
       dm.store_contribution_p6m,
       dm.sku_contribution_p6m,
       dm.size_of_price_p6m,
       dm.store_contribution_p12m,
       dm.sku_contribution_p12m,
       dm.size_of_price_p12m,
       dm.store_contribution_lm_lp,
       dm.sku_contribution_lm_lp,
       dm.size_of_price_lm_lp,
       dm.store_contribution_p3m_lp,
       dm.sku_contribution_p3m_lp,
       dm.size_of_price_p3m_lp,
       dm.store_contribution_p6m_lp,
       dm.sku_contribution_p6m_lp,
       dm.size_of_price_p6m_lp,
       dm.store_contribution_p12m_lp,
       dm.sku_contribution_p12m_lp,
       dm.size_of_price_p12m_lp,
       count(dm.lm_sales_flag) over (partition by dm.customer_agg_dim_key,dm.product_agg_dim_key,dm.lm_sales_flag,dm.mdp_flag) as lm_sales_flag_count,
       count(dm.p3m_sales_flag) over (partition by dm.customer_agg_dim_key,dm.product_agg_dim_key,dm.p3m_sales_flag,dm.mdp_flag) as p3m_sales_flag_count,
       count(dm.p6m_sales_flag) over (partition by dm.customer_agg_dim_key,dm.product_agg_dim_key,dm.p6m_sales_flag,dm.mdp_flag) as p6m_sales_flag_count,
       count(dm.p12m_sales_flag) over (partition by dm.customer_agg_dim_key,dm.product_agg_dim_key,dm.p12m_sales_flag,dm.mdp_flag) as p12m_sales_flag_count,
       count(dm.mdp_flag) over (partition by dm.customer_agg_dim_key,dm.product_agg_dim_key,dm.mdp_flag) as mdp_flag_count,
       sysdate() as created_date
from wks_cnpc_rpt_retail_excellence_sop dm
LEFT JOIN wks_cnpc_re_target_compliance TRGT_CMP on (dm.fisc_per=TRGT_CMP.fisc_per and UPPER(dm.global_product_brand)=UPPER(TRGT_CMP.global_product_brand))),

FINAL AS 
(
select 
fisc_yr	::	numeric(18,0)	as	fisc_yr	,
fisc_per	::	numeric(18,0)	as	fisc_per	,
"cluster"	::	varchar(100)	as	"cluster"	,
market	::	varchar(30)	as	market	,
data_src	::	varchar(14)	as	data_src	,
channel_name	::	varchar(11)	as	channel_name	,
soldto_code	::	varchar(255)	as	soldto_code	,
distributor_code	::	varchar(100)	as	distributor_code	,
distributor_name	::	varchar(356)	as	distributor_name	,
sell_out_channel	::	varchar(11)	as	sell_out_channel	,
store_type	::	varchar(382)	as	store_type	,
prioritization_segmentation	::	varchar(1)	as	prioritization_segmentation	,
store_category	::	varchar(1)	as	store_category	,
store_code	::	varchar(100)	as	store_code	,
store_name	::	varchar(601)	as	store_name	,
store_grade	::	varchar(1)	as	store_grade	,
store_size	::	varchar(1)	as	store_size	,
region	::	varchar(150)	as	region	,
zone_name	::	varchar(150)	as	zone_name	,
city	::	varchar(1)	as	city	,
rtrlatitude	::	varchar(1)	as	rtrlatitude	,
rtrlongitude	::	varchar(1)	as	rtrlongitude	,
customer_segment_key	::	varchar(12)	as	customer_segment_key	,
customer_segment_description	::	varchar(50)	as	customer_segment_description	,
retail_environment	::	varchar(382)	as	retail_environment	,
sap_parent_customer_key	::	varchar(12)	as	sap_parent_customer_key	,
sap_parent_customer_description	::	varchar(75)	as	sap_parent_customer_description	,
sap_customer_channel_key	::	varchar(12)	as	sap_customer_channel_key	,
sap_customer_channel_description	::	varchar(75)	as	sap_customer_channel_description	,
sap_customer_sub_channel_key	::	varchar(12)	as	sap_customer_sub_channel_key	,
sap_sub_channel_description	::	varchar(75)	as	sap_sub_channel_description	,
sap_banner_key	::	varchar(12)	as	sap_banner_key	,
sap_banner_description	::	varchar(75)	as	sap_banner_description	,
sap_banner_format_key	::	varchar(12)	as	sap_banner_format_key	,
sap_banner_format_description	::	varchar(75)	as	sap_banner_format_description	,
customer_name	::	varchar(1)	as	customer_name	,
customer_code	::	varchar(1)	as	customer_code	,
product_code	::	varchar(200)	as	product_code	,
product_name	::	varchar(300)	as	product_name	,
prod_hier_l1	::	varchar(19)	as	prod_hier_l1	,
prod_hier_l2	::	varchar(1)	as	prod_hier_l2	,
prod_hier_l3	::	varchar(1)	as	prod_hier_l3	,
prod_hier_l4	::	varchar(30)	as	prod_hier_l4	,
prod_hier_l5	::	varchar(300)	as	prod_hier_l5	,
prod_hier_l6	::	varchar(200)	as	prod_hier_l6	,
prod_hier_l7	::	varchar(1)	as	prod_hier_l7	,
prod_hier_l8	::	varchar(1)	as	prod_hier_l8	,
prod_hier_l9	::	varchar(100)	as	prod_hier_l9	,
mapped_sku_cd	::	varchar(40)	as	mapped_sku_cd	,
sap_prod_sgmt_cd	::	varchar(18)	as	sap_prod_sgmt_cd	,
sap_prod_sgmt_desc	::	varchar(100)	as	sap_prod_sgmt_desc	,
sap_base_prod_desc	::	varchar(100)	as	sap_base_prod_desc	,
sap_mega_brnd_desc	::	varchar(100)	as	sap_mega_brnd_desc	,
sap_brnd_desc	::	varchar(100)	as	sap_brnd_desc	,
sap_vrnt_desc	::	varchar(100)	as	sap_vrnt_desc	,
sap_put_up_desc	::	varchar(100)	as	sap_put_up_desc	,
sap_grp_frnchse_cd	::	varchar(18)	as	sap_grp_frnchse_cd	,
sap_grp_frnchse_desc	::	varchar(100)	as	sap_grp_frnchse_desc	,
sap_frnchse_cd	::	varchar(18)	as	sap_frnchse_cd	,
sap_frnchse_desc	::	varchar(100)	as	sap_frnchse_desc	,
sap_prod_frnchse_cd	::	varchar(18)	as	sap_prod_frnchse_cd	,
sap_prod_frnchse_desc	::	varchar(100)	as	sap_prod_frnchse_desc	,
sap_prod_mjr_cd	::	varchar(18)	as	sap_prod_mjr_cd	,
sap_prod_mjr_desc	::	varchar(100)	as	sap_prod_mjr_desc	,
sap_prod_mnr_cd	::	varchar(18)	as	sap_prod_mnr_cd	,
sap_prod_mnr_desc	::	varchar(100)	as	sap_prod_mnr_desc	,
sap_prod_hier_cd	::	varchar(18)	as	sap_prod_hier_cd	,
sap_prod_hier_desc	::	varchar(100)	as	sap_prod_hier_desc	,
pka_franchise_desc	::	varchar(30)	as	pka_franchise_desc	,
pka_brand_desc	::	varchar(30)	as	pka_brand_desc	,
pka_sub_brand_desc	::	varchar(30)	as	pka_sub_brand_desc	,
pka_variant_desc	::	varchar(30)	as	pka_variant_desc	,
pka_sub_variant_desc	::	varchar(30)	as	pka_sub_variant_desc	,
global_product_franchise	::	varchar(30)	as	global_product_franchise	,
global_product_brand	::	varchar(30)	as	global_product_brand	,
global_product_sub_brand	::	varchar(100)	as	global_product_sub_brand	,
global_product_variant	::	varchar(100)	as	global_product_variant	,
global_product_category	::	varchar(50)	as	global_product_category	,
global_product_subcategory	::	varchar(50)	as	global_product_subcategory	,
global_product_segment	::	varchar(50)	as	global_product_segment	,
global_product_subsegment	::	varchar(100)	as	global_product_subsegment	,
global_put_up_description	::	varchar(100)	as	global_put_up_description	,
ean	::	varchar(50)	as	ean	,
pka_product_key	::	varchar(68)	as	pka_product_key	,
pka_product_key_description	::	varchar(382)	as	pka_product_key_description	,
sales_value	::	numeric(38,6)	as	sales_value	,
sales_qty	::	numeric(38,6)	as	sales_qty	,
avg_sales_qty	::	numeric(38,6)	as	avg_sales_qty	,
sales_value_list_price	::	numeric(38,12)	as	sales_value_list_price	,
lm_sales	::	numeric(38,6)	as	lm_sales	,
lm_sales_qty	::	numeric(38,6)	as	lm_sales_qty	,
lm_avg_sales_qty	::	numeric(38,6)	as	lm_avg_sales_qty	,
lm_sales_lp	::	numeric(38,12)	as	lm_sales_lp	,
p3m_sales	::	numeric(38,6)	as	p3m_sales	,
p3m_qty	::	numeric(38,6)	as	p3m_qty	,
p3m_avg_qty	::	numeric(38,6)	as	p3m_avg_qty	,
p3m_sales_lp	::	numeric(38,12)	as	p3m_sales_lp	,
p6m_sales	::	numeric(38,6)	as	p6m_sales	,
p6m_qty	::	numeric(38,6)	as	p6m_qty	,
p6m_avg_qty	::	numeric(38,6)	as	p6m_avg_qty	,
p6m_sales_lp	::	numeric(38,12)	as	p6m_sales_lp	,
p12m_sales	::	numeric(38,6)	as	p12m_sales	,
p12m_qty	::	numeric(38,6)	as	p12m_qty	,
p12m_avg_qty	::	numeric(38,6)	as	p12m_avg_qty	,
p12m_sales_lp	::	numeric(38,12)	as	p12m_sales_lp	,
f3m_sales	::	numeric(38,6)	as	f3m_sales	,
f3m_qty	::	numeric(38,6)	as	f3m_qty	,
f3m_avg_qty	::	numeric(38,6)	as	f3m_avg_qty	,
lm_sales_flag	::	varchar(1)	as	lm_sales_flag	,
p3m_sales_flag	::	varchar(1)	as	p3m_sales_flag	,
p6m_sales_flag	::	varchar(1)	as	p6m_sales_flag	,
p12m_sales_flag	::	varchar(1)	as	p12m_sales_flag	,
mdp_flag	::	varchar(1)	as	mdp_flag	,
target_complaince	::	integer	as	target_complaince	,
list_price	::	numeric(20,4)	as	list_price	,
total_sales_lm	::	numeric(38,6)	as	total_sales_lm	,
total_sales_p3m	::	numeric(38,6)	as	total_sales_p3m	,
total_sales_p6m	::	numeric(38,6)	as	total_sales_p6m	,
total_sales_p12m	::	numeric(38,6)	as	total_sales_p12m	,
total_sales_by_store_lm	::	numeric(38,6)	as	total_sales_by_store_lm	,
total_sales_by_store_p3m	::	numeric(38,6)	as	total_sales_by_store_p3m	,
total_sales_by_store_p6m	::	numeric(38,6)	as	total_sales_by_store_p6m	,
total_sales_by_store_p12m	::	numeric(38,6)	as	total_sales_by_store_p12m	,
total_sales_by_sku_lm	::	numeric(38,6)	as	total_sales_by_sku_lm	,
total_sales_by_sku_p3m	::	numeric(38,6)	as	total_sales_by_sku_p3m	,
total_sales_by_sku_p6m	::	numeric(38,6)	as	total_sales_by_sku_p6m	,
total_sales_by_sku_p12m	::	numeric(38,6)	as	total_sales_by_sku_p12m	,
total_sales_lm_lp	::	numeric(38,12)	as	total_sales_lm_lp	,
total_sales_p3m_lp	::	numeric(38,12)	as	total_sales_p3m_lp	,
total_sales_p6m_lp	::	numeric(38,12)	as	total_sales_p6m_lp	,
total_sales_p12m_lp	::	numeric(38,12)	as	total_sales_p12m_lp	,
total_sales_by_store_lm_lp	::	numeric(38,12)	as	total_sales_by_store_lm_lp	,
total_sales_by_store_p3m_lp	::	numeric(38,12)	as	total_sales_by_store_p3m_lp	,
total_sales_by_store_p6m_lp	::	numeric(38,12)	as	total_sales_by_store_p6m_lp	,
total_sales_by_store_p12m_lp	::	numeric(38,12)	as	total_sales_by_store_p12m_lp	,
total_sales_by_sku_lm_lp	::	numeric(38,12)	as	total_sales_by_sku_lm_lp	,
total_sales_by_sku_p3m_lp	::	numeric(38,12)	as	total_sales_by_sku_p3m_lp	,
total_sales_by_sku_p6m_lp	::	numeric(38,12)	as	total_sales_by_sku_p6m_lp	,
total_sales_by_sku_p12m_lp	::	numeric(38,12)	as	total_sales_by_sku_p12m_lp	,
store_contribution_lm	::	numeric(38,4)	as	store_contribution_lm	,
sku_contribution_lm	::	numeric(38,4)	as	sku_contribution_lm	,
size_of_price_lm	::	numeric(38,14)	as	size_of_price_lm	,
store_contribution_p3m	::	numeric(38,4)	as	store_contribution_p3m	,
sku_contribution_p3m	::	numeric(38,4)	as	sku_contribution_p3m	,
size_of_price_p3m	::	numeric(38,14)	as	size_of_price_p3m	,
store_contribution_p6m	::	numeric(38,4)	as	store_contribution_p6m	,
sku_contribution_p6m	::	numeric(38,4)	as	sku_contribution_p6m	,
size_of_price_p6m	::	numeric(38,14)	as	size_of_price_p6m	,
store_contribution_p12m	::	numeric(38,4)	as	store_contribution_p12m	,
sku_contribution_p12m	::	numeric(38,4)	as	sku_contribution_p12m	,
size_of_price_p12m	::	numeric(38,14)	as	size_of_price_p12m	,
store_contribution_lm_lp	::	numeric(38,4)	as	store_contribution_lm_lp	,
sku_contribution_lm_lp	::	numeric(38,4)	as	sku_contribution_lm_lp	,
size_of_price_lm_lp	::	numeric(38,20)	as	size_of_price_lm_lp	,
store_contribution_p3m_lp	::	numeric(38,4)	as	store_contribution_p3m_lp	,
sku_contribution_p3m_lp	::	numeric(38,4)	as	sku_contribution_p3m_lp	,
size_of_price_p3m_lp	::	numeric(38,20)	as	size_of_price_p3m_lp	,
store_contribution_p6m_lp	::	numeric(38,4)	as	store_contribution_p6m_lp	,
sku_contribution_p6m_lp	::	numeric(38,4)	as	sku_contribution_p6m_lp	,
size_of_price_p6m_lp	::	numeric(38,20)	as	size_of_price_p6m_lp	,
store_contribution_p12m_lp	::	numeric(38,4)	as	store_contribution_p12m_lp	,
sku_contribution_p12m_lp	::	numeric(38,4)	as	sku_contribution_p12m_lp	,
size_of_price_p12m_lp	::	numeric(38,20)	as	size_of_price_p12m_lp	,
lm_sales_flag_count	::	numeric(38,20)	as	lm_sales_flag_count	,
p3m_sales_flag_count	::	numeric(38,0)	as	p3m_sales_flag_count	,
p6m_sales_flag_count	::	numeric(38,0)	as	p6m_sales_flag_count	,
p12m_sales_flag_count	::	numeric(38,0)	as	p12m_sales_flag_count	,
mdp_flag_count	::	numeric(38,0)	as	mdp_flag_count	,
created_date ::	timestamp	as	created_date	
from edw_cnpc_rpt_retail_excellence
)

select * from final