with source as (
    select * from snaposeedw_integration.v_rpt_th_perfect_store
),
final as (
    select
        dataset::varchar(14) as dataset,
        customerid::varchar(255) as customerid,
        salespersonid::varchar(255) as salespersonid,
        mustcarryitem::varchar(4) as mustcarryitem,
        answerscore::varchar(1) as answerscore,
        presence::varchar(5) as presence,
        outofstock::varchar(4) as outofstock,
        kpi::varchar(255) as kpi,
        scheduleddate::date as scheduleddate,
        vst_status::varchar(9) as vst_status,
        fisc_yr::varchar(13) as fisc_yr,
        fisc_per::varchar(255) as fisc_per,
        firstname::varchar(513) as firstname,
        lastname::varchar(1) as lastname,
        customername::varchar(771) as customername,
        country::varchar(8) as country,
        state::varchar(255) as state,
        storereference::varchar(255) as storereference,
        storetype::varchar(300) as storetype,
        channel::varchar(300) as channel,
        salesgroup::varchar(113) as salesgroup,
        eannumber::varchar(255) as eannumber,
        prod_hier_l1::varchar(30) as prod_hier_l1,
        prod_hier_l2::varchar(50) as prod_hier_l2,
        prod_hier_l3::varchar(255) as prod_hier_l3,
        prod_hier_l4::varchar(30) as prod_hier_l4,
        prod_hier_l5::varchar(50) as prod_hier_l5,
        prod_hier_l6::varchar(100) as prod_hier_l6,
        prod_hier_l7::varchar(100) as prod_hier_l7,
        prod_hier_l8::varchar(100) as prod_hier_l8,
        prod_hier_l9::varchar(513) as prod_hier_l9,
        kpi_chnl_wt::float as kpi_chnl_wt,
        "y/n_flag" varchar(3) as "y/n_flag",
        posm_execution_flag::varchar(1) as posm_execution_flag,
        priority_store_flag::varchar(1) as priority_store_flag,
        questiontext::varchar(500) as questiontext,
        ques_desc::varchar(11) as ques_desc,
        value::varchar(255) as value,
        mkt_share::number(32,4) as mkt_share,
        rej_reason::varchar(255) as rej_reason,
        photo_url::varchar(1) as photo_url,
        category::varchar(255) as category,
        brand::varchar(255) as brand
    from source
)
select * from final