with edw_hcp360_veeva_wrk_fact_call_only as
(
    select country_code as country_key,
       hcp_key,
       hco_key,
       employee_key,
       organization_key,
       cast(cal_date_id as integer) as call_date_key,
       call_date_time,
       last_modified_date as call_entry_datetime,
       mobile_last_modified_date_time as call_mobile_last_modified_date_time,
       utc_call_date_time,
       utc_call_entry_time,
       call_status_type,
       call_channel_typ as call_channel_type,
       call_type,
       call_duration,
       cast(call_clm as integer) as call_clm_flag,
       case when is_parent_call_base = 1 then is_parent_call_base else null end as parent_call_flag,
       attendee_type,
       call_comments,
       next_call_notes,
       pre_call_notes,       
       last_activity_date,
       sample_card,
       account_plan,
       mobile_id,
       cast(significant_event as integer) as significant_event,
       location,
       signature_date,
       signature,
       territory,
	   attendees,
       detailed_products,
	   parent_call_source_id,
       user_name,
       cast(is_sampled_call as integer) as is_sampled_call,
       presentations,
       product_priority_1,
       product_priority_2,
       product_priority_3,
       product_priority_4,
       product_priority_5,
       attendee_list,
       sea_call_type,
       interaction_mode,
       cast(hcp_kol_initiated as integer) as hcp_kol_initiated,
       msl_interaction_type,
       calculated_field_2,
       calculated_hours_3,
       cast(call_planned as integer) as call_planned,
       call_submission_day,
	   null as case_coverage,
       day_of_week,
	   record_type_name as call_record_type_name,
	   call_name,
       parent_call_name,
       cast(submitted_by_mobile as integer) as submitted_by_mobile,
       call_source_id,
	   product_indication_key,
	   call_detail_priority,
       call_detail_type,
       call_detail_source_id,
       call_detail_name,
	   lastmodifieddate as call_modify_dt,
       last_modified_by_id as call_modify_id,
       call_detail_modify_date as call_detail_modify_dt,
       call_detail_modify_id as call_detail_modify_id,
       crt_dttm,
       updt_dttm
       from {{ ref('hcpedw_integration__edw_hcp360_veeva_wrk_fact_call_only') }}
),
edw_hcp360_veeva_wrk_fact_group_detail as
(
    select country_code as country_key,
       hcp_key,
       hco_key,
       employee_key,
       organization_key,
       cast(cal_date_id as integer) as call_date_key,
       call_date_time,
       last_modified_date as call_entry_datetime,
       mobile_last_modified_date_time as call_mobile_last_modified_date_time,
       utc_call_date_time,
       utc_call_entry_time,
       call_status_type,
       call_channel_typ as call_channel_type,
       call_type,
       call_duration,
       cast(call_clm as integer) as call_clm_flag,
       case when is_parent_call_base = 1 then is_parent_call_base else null end as parent_call_flag,
       attendee_type,
       call_comments,
       next_call_notes,
       pre_call_notes,       
       last_activity_date,
       sample_card,
       account_plan,
       mobile_id,
       cast(significant_event as integer) as significant_event,
       location,
       signature_date,
       signature,
       territory,
	   attendees,
       detailed_products,
	   parent_call_source_id,
       user_name,
       cast(is_sampled_call as integer) as is_sampled_call,
       presentations,
       product_priority_1,
       product_priority_2,
       product_priority_3,
       product_priority_4,
       product_priority_5,
       attendee_list,
       sea_call_type,
       interaction_mode,
       cast(hcp_kol_initiated as integer) as hcp_kol_initiated,
       msl_interaction_type,
       calculated_field_2,
       calculated_hours_3,
       cast(call_planned as integer) as call_planned,
       call_submission_day,
	   null as case_coverage,
       day_of_week,
	   record_type_name as call_record_type_name,
	   call_name,
       parent_call_name,
       cast(submitted_by_mobile as integer) as submitted_by_mobile,
       call_source_id,
	   product_indication_key,
	   call_detail_priority,
       call_detail_type,
       call_detail_source_id,
       call_detail_name,
	   lastmodifieddate as call_modify_dt,
       last_modified_by_id as call_modify_id,
       call_detail_modify_date as call_detail_modify_dt,
       call_detail_modify_id as call_detail_modify_id,
       crt_dttm,
       updt_dttm
       from {{ ref('hcpedw_integration__edw_hcp360_veeva_wrk_fact_group_detail') }}
),
edw_hcp360_veeva_wrk_fact_detail_only as
(
    select country_code as country_key,
       hcp_key,
       hco_key,
       employee_key,
       organization_key,
       cast(cal_date_id as integer) as call_date_key,
       call_date_time,
       last_modified_date as call_entry_datetime,
       mobile_last_modified_date_time as call_mobile_last_modified_date_time,
       utc_call_date_time,
       utc_call_entry_time,
       call_status_type,
       call_channel_typ as call_channel_type,
       call_type,
       call_duration,
       cast(call_clm as integer) as call_clm_flag,
       case when is_parent_call_base = 1 then is_parent_call_base else null end as parent_call_flag,
       attendee_type,
       call_comments,
       next_call_notes,
       pre_call_notes,       
       last_activity_date,
       sample_card,
       account_plan,
       mobile_id,
       cast(significant_event as integer) as significant_event,
       location,
       signature_date,
       signature,
       territory,
	   attendees,
       detailed_products,
	   parent_call_source_id,
       user_name,
       cast(is_sampled_call as integer) as is_sampled_call,
       presentations,
       product_priority_1,
       product_priority_2,
       product_priority_3,
       product_priority_4,
       product_priority_5,
       attendee_list,
       sea_call_type,
       interaction_mode,
       cast(hcp_kol_initiated as integer) as hcp_kol_initiated,
       msl_interaction_type,
       calculated_field_2,
       calculated_hours_3,
       cast(call_planned as integer) as call_planned,
       call_submission_day,
	   null as case_coverage,
       day_of_week,
	   record_type_name as call_record_type_name,
	   call_name,
       parent_call_name,
       cast(submitted_by_mobile as integer) as submitted_by_mobile,
       call_source_id,
	   product_indication_key,
	   call_detail_priority,
       call_detail_type,
       call_detail_source_id,
       call_detail_name,
	   lastmodifieddate as call_modify_dt,
       last_modified_by_id as call_modify_id,
       call_detail_modify_date as call_detail_modify_dt,
       call_detail_modify_id as call_detail_modify_id,
       crt_dttm,
       updt_dttm
       from {{ ref('hcpedw_integration__edw_hcp360_veeva_wrk_fact_detail_only') }}
),
edw_hcp360_veeva_sample_only as
(
    select country_code as country_key,
       hcp_key,
       hco_key,
       employee_key,
       organization_key,
       cast(cal_date_id as integer) as call_date_key,
       call_date_time,
       last_modified_date as call_entry_datetime,
       mobile_last_modified_date_time as call_mobile_last_modified_date_time,
       utc_call_date_time,
       utc_call_entry_time,
       call_status_type,
       call_channel_typ as call_channel_type,
       call_type,
       call_duration,
       cast(call_clm as integer) as call_clm_flag,
       case when is_parent_call_base = 1 then is_parent_call_base else null end as parent_call_flag,
       attendee_type,
       call_comments,
       next_call_notes,
       pre_call_notes,       
       last_activity_date,
       sample_card,
       account_plan,
       mobile_id,
       cast(significant_event as integer) as significant_event,
       location,
       signature_date,
       signature,
       territory,
	   attendees,
       detailed_products,
	   parent_call_source_id,
       user_name,
       cast(is_sampled_call as integer) as is_sampled_call,
       presentations,
       product_priority_1,
       product_priority_2,
       product_priority_3,
       product_priority_4,
       product_priority_5,
       attendee_list,
       sea_call_type,
       interaction_mode,
       cast(hcp_kol_initiated as integer) as hcp_kol_initiated,
       msl_interaction_type,
       calculated_field_2,
       calculated_hours_3,
       cast(call_planned as integer) as call_planned,
       call_submission_day,
	   null as case_coverage,
       day_of_week,
	   record_type_name as call_record_type_name,
	   call_name,
       parent_call_name,
       cast(submitted_by_mobile as integer) as submitted_by_mobile,
       call_source_id,
	   product_indication_key,
	   call_detail_priority,
       call_detail_type,
       call_detail_source_id,
       call_detail_name,
	   lastmodifieddate as call_modify_dt,
       last_modified_by_id as call_modify_id,
       call_detail_modify_date as call_detail_modify_dt,
       call_detail_modify_id as call_detail_modify_id,
       crt_dttm,
       updt_dttm
       from {{ ref('hcpedw_integration__edw_hcp360_veeva_sample_only') }}
),
edw_hcp360_veeva_detail_with_sample as
(
    select country_code as country_key,
       hcp_key,
       hco_key,
       employee_key,
       organization_key,
       cast(cal_date_id as integer) as call_date_key,
       call_date_time,
       last_modified_date as call_entry_datetime,
       mobile_last_modified_date_time as call_mobile_last_modified_date_time,
       utc_call_date_time,
       utc_call_entry_time,
       call_status_type,
       call_channel_typ as call_channel_type,
       call_type,
       call_duration,
       cast(call_clm as integer) as call_clm_flag,
       case when is_parent_call_base = 1 then is_parent_call_base else null end as parent_call_flag,
       attendee_type,
       call_comments,
       next_call_notes,
       pre_call_notes,       
       last_activity_date,
       sample_card,
       account_plan,
       mobile_id,
       cast(significant_event as integer) as significant_event,
       location,
       signature_date,
       signature,
       territory,
	   attendees,
       detailed_products,
	   parent_call_source_id,
       user_name,
       cast(is_sampled_call as integer) as is_sampled_call,
       presentations,
       product_priority_1,
       product_priority_2,
       product_priority_3,
       product_priority_4,
       product_priority_5,
       attendee_list,
       sea_call_type,
       interaction_mode,
       cast(hcp_kol_initiated as integer) as hcp_kol_initiated,
       msl_interaction_type,
       calculated_field_2,
       calculated_hours_3,
       cast(call_planned as integer) as call_planned,
       call_submission_day,
	   null as case_coverage,
       day_of_week,
	   record_type_name as call_record_type_name,
	   call_name,
       parent_call_name,
       cast(submitted_by_mobile as integer) as submitted_by_mobile,
       call_source_id,
	   product_indication_key,
	   call_detail_priority,
       call_detail_type,
       call_detail_source_id,
       call_detail_name,
	   lastmodifieddate as call_modify_dt,
       last_modified_by_id as call_modify_id,
       call_detail_modify_date as call_detail_modify_dt,
       call_detail_modify_id as call_detail_modify_id,
       crt_dttm,
       updt_dttm
       from {{ ref('hcpedw_integration__edw_hcp360_veeva_detail_with_sample') }}
),
edw_hcp360_veeva_group_detail_with_sample as
(
    select country_code as country_key,
       hcp_key,
       hco_key,
       employee_key,
       organization_key,
       cast(cal_date_id as integer) as call_date_key,
       call_date_time,
       last_modified_date as call_entry_datetime,
       mobile_last_modified_date_time as call_mobile_last_modified_date_time,
       utc_call_date_time,
       utc_call_entry_time,
       call_status_type,
       call_channel_typ as call_channel_type,
       call_type,
       call_duration,
       cast(call_clm as integer) as call_clm_flag,
       case when is_parent_call_base = 1 then is_parent_call_base else null end as parent_call_flag,
       attendee_type,
       call_comments,
       next_call_notes,
       pre_call_notes,       
       last_activity_date,
       sample_card,
       account_plan,
       mobile_id,
       cast(significant_event as integer) as significant_event,
       location,
       signature_date,
       signature,
       territory,
	   attendees,
       detailed_products,
	   parent_call_source_id,
       user_name,
       cast(is_sampled_call as integer) as is_sampled_call,
       presentations,
       product_priority_1,
       product_priority_2,
       product_priority_3,
       product_priority_4,
       product_priority_5,
       attendee_list,
       sea_call_type,
       interaction_mode,
       cast(hcp_kol_initiated as integer) as hcp_kol_initiated,
       msl_interaction_type,
       calculated_field_2,
       calculated_hours_3,
       cast(call_planned as integer) as call_planned,
       call_submission_day,
	   null as case_coverage,
       day_of_week,
	   record_type_name as call_record_type_name,
	   call_name,
       parent_call_name,
       cast(submitted_by_mobile as integer) as submitted_by_mobile,
       call_source_id,
	   product_indication_key,
	   call_detail_priority,
       call_detail_type,
       call_detail_source_id,
       call_detail_name,
	   lastmodifieddate as call_modify_dt,
       last_modified_by_id as call_modify_id,
       call_detail_modify_date as call_detail_modify_dt,
       call_detail_modify_id as call_detail_modify_id,
       crt_dttm,
       updt_dttm
       from {{ ref('hcpedw_integration__edw_hcp360_veeva_group_detail_with_sample') }}
),
final as
(
    select * from edw_hcp360_veeva_wrk_fact_call_only
    UNION ALL
    select * from edw_hcp360_veeva_wrk_fact_group_detail
    UNION ALL
    select * from edw_hcp360_veeva_wrk_fact_detail_only
    UNION ALL
    select * from edw_hcp360_veeva_sample_only
    UNION ALL
    select * from edw_hcp360_veeva_detail_with_sample
    UNION ALL
    select * from edw_hcp360_veeva_group_detail_with_sample
)
select country_key::varchar(18) as country_key,
    hcp_key::varchar(132) as hcp_key,
    hco_key::varchar(132) as hco_key,
    employee_key::varchar(132) as employee_key,
    organization_key::varchar(132) as organization_key,
    call_date_key::number(18,0) as call_date_key,
    call_date_time::timestamp_ntz(9) as call_date_time,
    call_entry_datetime::timestamp_ntz(9) as call_entry_datetime,
    call_mobile_last_modified_date_time::timestamp_ntz(9) as call_mobile_last_modified_date_time,
    utc_call_date_time::timestamp_ntz(9) as utc_call_date_time,
    utc_call_entry_time::timestamp_ntz(9) as utc_call_entry_time,
    call_status_type::varchar(1255) as call_status_type,
    call_channel_type::varchar(15) as call_channel_type,
    call_type::varchar(1255) as call_type,
    call_duration::number(18,0) as call_duration,
    call_clm_flag::number(18,0) as call_clm_flag,
    parent_call_flag::number(18,0) as parent_call_flag,
    attendee_type::varchar(1255) as attendee_type,
    call_comments::varchar(32000) as call_comments,
    next_call_notes::varchar(32000) as next_call_notes,
    pre_call_notes::varchar(32000) as pre_call_notes,
    last_activity_date::timestamp_ntz(9) as last_activity_date,
    sample_card::varchar(115) as sample_card,
    account_plan::varchar(118) as account_plan,
    mobile_id::varchar(1103) as mobile_id,
    significant_event::number(18,0) as significant_event,
    location::varchar(1128) as location,
    signature_date::timestamp_ntz(9) as signature_date,
    signature::varchar(32330) as signature,
    territory::varchar(1103) as territory,
    attendees::number(3,0) as attendees,
    detailed_products::varchar(1255) as detailed_products,
    parent_call_source_id::varchar(118) as parent_call_source_id,
    user_name::varchar(118) as user_name,
    is_sampled_call::number(18,0) as is_sampled_call,
    presentations::varchar(1530) as presentations,
    product_priority_1::varchar(118) as product_priority_1,
    product_priority_2::varchar(118) as product_priority_2,
    product_priority_3::varchar(118) as product_priority_3,
    product_priority_4::varchar(118) as product_priority_4,
    product_priority_5::varchar(118) as product_priority_5,
    attendee_list::varchar(32768) as attendee_list,
    sea_call_type::varchar(11300) as sea_call_type,
    interaction_mode::varchar(1255) as interaction_mode,
    hcp_kol_initiated::number(18,0) as hcp_kol_initiated,
    msl_interaction_type::varchar(1255) as msl_interaction_type,
    calculated_field_2::number(18,2) as calculated_field_2,
    calculated_hours_3::number(18,2) as calculated_hours_3,
    call_planned::number(18,0) as call_planned,
    call_submission_day::number(18,1) as call_submission_day,
    case_coverage::number(18,2) as case_coverage,
    day_of_week::varchar(11300) as day_of_week,
    call_record_type_name::varchar(180) as call_record_type_name,
    call_name::varchar(180) as call_name,
    parent_call_name::varchar(180) as parent_call_name,
    submitted_by_mobile::number(18,0) as submitted_by_mobile,
    call_source_id::varchar(118) as call_source_id,
    product_indication_key::varchar(132) as product_indication_key,
    call_detail_priority::number(2,0) as call_detail_priority,
    call_detail_type::varchar(1255) as call_detail_type,
    call_detail_source_id::varchar(118) as call_detail_source_id,
    call_detail_name::varchar(183) as call_detail_name,
    call_modify_dt::timestamp_ntz(9) as call_modify_dt,
    call_modify_id::varchar(118) as call_modify_id,
    call_detail_modify_dt::timestamp_ntz(9) as call_detail_modify_dt,
    call_detail_modify_id::varchar(118) as call_detail_modify_id,
    crt_dttm::timestamp_ntz(9) as crt_dttm,
    updt_dttm::timestamp_ntz(9) as updt_dttm
 from final