version: 2

sources:
  - name: thasdl_raw
    database: "{{ env_var('DBT_ENV_LOAD_DB') }}"
    schema: thasdl_raw
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
  
    - name: sdl_mds_th_htc_inventory
      tags: ["th_non_tesco",""]
      tests:
          - test_null:
              not_null_columns: ["company","date","whcode","productcode"]
              name: TRATBL_sdl_mds_th_htc_inventory__null_test
              config:
                store_failures: true
                schema: thawks_integration
    