version: 2

sources:
  - name: thasdl_raw
    database: "{{ env_var('DBT_ENV_LOAD_DB') }}"
    schema: thasdl_raw
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
  
    - name: sdl_mds_th_htc_inventory
      tags: ["th_non_tesco"]
      tests:
          - test_null:
              not_null_columns: ["company","date","whcode","productcode"]
              select_columns: ["company","date","whcode","productcode"]
              name: TRATBL_sdl_mds_th_htc_inventory__null_test
              config:
                store_failures: true
                schema: thawks_integration

    - name: sdl_th_dms_inventory_fact
      tags: ["th_mbox_inventory"]
      tests: 
          - test_date_format:
                      date_column: ["expirydate"]
                      select_columns: ["expirydate"]
                      name: TRATBL_sdl_th_dms_inventory_fact__test_date_format
                      config:
                        store_failures: true
                        schema: thawks_integration
    
    - name: sdl_cbd_gt_inventory_report_fact
      tests:
                - test_null:
                      not_null_columns: ["date","product_code","product_name","filename"]
                      select_columns: ["date","product_code","product_name","filename"]
                      name: TRATBL_sdl_cbd_gt_inventory_report_fact__null_test
                      config:
                        store_failures: true
                        schema: thawks_integration
                - test_duplicate:
                    group_by_columns: ["date","product_code","product_name","filename"]
                    select_columns: ["date","product_code","product_name","filename"]
                    need_counts: "no"
                    name: TRATBL_sdl_cbd_gt_inventory_report_fact__duplicate_test
                    config:
                      store_failures: true
                      schema: thawks_integration
      tags: ["cambodia_file_ingestion"]

    
    