version: 2

sources:
  - name: thasdl_raw
    database: "{{ env_var('DBT_ENV_LOAD_DB') }}"
    schema: thasdl_raw
    quoting:
      database: false
      schema: false
      identifier: false
    tables:
  
    - name: sdl_mds_th_htc_inventory
      tags: ["th_non_tesco","ingestion"]
      tests:
          - test_null:
              not_null_columns: ["company","date","whcode","productcode"]
              select_columns: ["company","date","whcode","productcode"]
              name: TRATBL_sdl_mds_th_htc_inventory__null_test
              config:
                store_failures: true
                schema: thawks_integration

    - name: sdl_th_dms_inventory_fact
      tags: ["th_mbox_files","ingestion"]
      tests: 
          - test_date_format:
                      date_column: ["expirydate"]
                      select_columns: ["expirydate"]
                      name: TRATBL_sdl_th_dms_inventory_fact__test_date_format
                      config:
                        store_failures: true
                        schema: thawks_integration
    - name: sdl_la_gt_inventory_fact
      tags: ["laos_file_ingestion","ingestion"]
      tests:
          - test_format:
              select_columns: ["filename","recdate","expirydate"]
              failure_reason: "'Data Format issue for recdate'"
              where_clause: " not regexp_like(recdate,'[1-2][0-9][0-9][0-9]/[0-1][0-9]/[0-3][0-9]')"          
              name: TRATBL_sdl_la_gt_inventory_fact__test_format_recdate
              config:
                store_failures: true
                schema: thawks_integration
          - test_format:
              select_columns: ["filename","recdate","expirydate"]
              failure_reason: "'Data Format issue for expirydate'"
              where_clause: " not regexp_like(expirydate,'[1-2][0-9][0-9][0-9][0-1][0-9][0-3][0-9]')"          
              name: TRATBL_sdl_la_gt_inventory_fact__test_format_expirydate
              config:
                store_failures: true
                schema: thawks_integration