version: 2

models:
  - name: thaitg_integration__itg_th_htc_inventory
    config:
      alias: itg_th_htc_inventory
      tags: ["th_non_tesco"]

  - name: thaitg_integration__itg_th_dms_inventory_fact
    config: 
      alias: itg_th_dms_inventory_fact
      tags: ["th_mbox_files"]

  - name: thaitg_integration__sdl_raw_th_dms_inventory_fact
    config: 
      alias: sdl_raw_th_dms_inventory_fact
      tags: ["th_mbox_files"]
  - name: thaitg_integration__sdl_raw_la_gt_inventory_fact
    config: 
      alias: sdl_raw_la_gt_inventory_fact
      tags: ["laos_file_ingestion"]
  - name: thaitg_integration__itg_la_gt_inventory_fact
    config: 
      alias: itg_la_gt_inventory_fact
      tags: ["laos_file_ingestion"]