with source as(
    select * from {{ ref('jpnedw_integration__item_m') }}
),
transformed as(
    SELECT create_dt as "create_dt"
        ,create_user as "create_user"
        ,update_dt as "update_dt"
        ,update_user as "update_user"
        ,reg_dt as "reg_dt"
        ,item_cd as "item_cd"
        ,item_nm as "item_nm"
        ,iten_nm_kn as "iten_nm_kn"
        ,iten_nm_knj as "iten_nm_knj"
        ,jan_cd as "jan_cd"
        ,itf_cd as "itf_cd"
        ,pc as "pc"
        ,unt_prc as "unt_prc"
        ,sub_frnch as "sub_frnch"
        ,jan_cd_so as "jan_cd_so"
        ,itf_cd_so as "itf_cd_so"
        ,updateflg as "updateflg"
        ,base_prod as "base_prod"
        ,variant as "variant"
        ,put_up as "put_up"
        ,mega_brnd as "mega_brnd"
        ,brnd as "brnd"
        ,dlt_flg as "dlt_flg"
        ,base_uom as "base_uom"
        ,item_cd_jd as "item_cd_jd"
        ,sap_cstm_type as "sap_cstm_type"
        ,mega_brnd_chkflg as "mega_brnd_chkflg"
        ,planet_l3_flg as "planet_l3_flg"
        ,rel_dt as "rel_dt"
        ,discon_dt as "discon_dt"
        ,new_prod_type as "new_prod_type"
        ,prom_goods_flg as "prom_goods_flg"
        ,parent_item_cd as "parent_item_cd"
        ,imp_item_flg as "imp_item_flg"
        ,succeeding_item_cd as "succeeding_item_cd"
        ,ldw_flg01 as "ldw_flg01"
        ,ldw_flg02 as "ldw_flg02"
        ,ldw_flg03 as "ldw_flg03"
    FROM source
)
select * from transformed