{{
    config(
        sql_header='use warehouse DEV_DNA_CORE_app2_wh;'
    )
}}

with dm_integration_dly as (
  select * from snapjpnedw_integration.dm_integration_dly
),
edi_chn_m as (
  select * from snapjpnedw_integration.edi_chn_m
),
mt_sgmt as (
  select * from snapjpnedw_integration.mt_sgmt
),
edi_chn_m as (
  select * from snapjpnedw_integration.edi_chn_m
),
mt_sgmt as (
  select * from snapjpnedw_integration.mt_sgmt
),
edi_cstm_m as (
  select * from snapjpnedw_integration.edi_cstm_m
),
edi_cstm_m as (
  select * from snapjpnedw_integration.edi_cstm_m
),
edi_store_m as (
  select * from snapjpnedw_integration.edi_store_m
),
mt_prf as (
  select * from snapjpnedw_integration.mt_prf
),
mt_account_key as (
  select * from snapjpnedw_integration.mt_account_key
),
mt_cld as (
  select * from snapjpnedw_integration.mt_cld
),
mt_jan_detail as (
  select * from DEV_DNA_CORE.JPNEDW_INTEGRATION.MT_JAN_DETAIL
),
vw_jan_change as (
  select * from snapjpnedw_integration.vw_jan_change
),
edi_item_m as (
  select * from snapjpnedw_integration.edi_item_m
),
vw_m_item_frnch_cdd as (
  select * from snapjpnedw_integration.vw_m_item_frnch_cdd
),
mt_chn_mjp_emp_chg as (
  select * from snapjpnedw_integration.mt_chn_mjp_emp_chg
),
mt_emp as (
  select * from snapjpnedw_integration.mt_emp
),
mt_chn_mjp_emp_chg as (
  select * from snapjpnedw_integration.mt_chn_mjp_emp_chg
),
mt_emp as (
  select * from snapjpnedw_integration.mt_emp
),
mt_chn_mjp_emp_chg as (
  select * from snapjpnedw_integration.mt_chn_mjp_emp_chg
),
mt_emp as (
  select * from snapjpnedw_integration.mt_emp
),
mt_cld as (
  select * from snapjpnedw_integration.mt_cld
),
mt_tp_status_mapping as (
  select * from jpnedw_integration.mt_tp_status_mapping
),
mt_chn_mjp_emp_chg as (
  select * from snapjpnedw_integration.mt_chn_mjp_emp_chg
),
mt_emp as (
  select * from snapjpnedw_integration.mt_emp
),
sdl_mds_jp_product_ca_ratio as (
  select * from DEV_DNA_LOAD.JPNSDL_RAW.SDL_MDS_JP_PRODUCT_CA_RATIO
),
sdl_mds_jp_jan_description as (
  select * from DEV_DNA_CORE.JPNEDW_ACCESS.SDL_MDS_JP_JAN_DESCRIPTION
),
transformed as(
SELECT "mt_account_key".accounting_code as "accounting_code",
  CAST("edi_chn_m1".acnt_prsn_cd as TEXT) AS "acnt_prsn_cd (edi_chn_m1)",
  CAST("edi_cstm_m".acnt_prsn_cd as TEXT) AS "acnt_prsn_cd (edi_cstm_m)",
  CAST("edi_cstm_m1".acnt_prsn_cd as TEXT) AS "acnt_prsn_cd (edi_cstm_m1)",
  CAST("edi_cstm_m2".acnt_prsn_cd as TEXT) AS "acnt_prsn_cd (edi_cstm_m2)",
  CAST("edi_chn_m".acnt_prsn_cd as TEXT) AS "acnt_prsn_cd",
  CAST("edi_chn_m1".adrs as TEXT) AS "adrs (edi_chn_m1)",
  CAST("edi_cstm_m".adrs as TEXT) AS "adrs (edi_cstm_m)",
  CAST("edi_cstm_m1".adrs as TEXT) AS "adrs (edi_cstm_m1)",
  CAST("edi_cstm_m2".adrs as TEXT) AS "adrs (edi_cstm_m2)",
  CAST("edi_chn_m".adrs as TEXT) AS "adrs",
  CAST("edi_cstm_m1".adrs_kn as TEXT) AS "adrs_kn (edi_cstm_m1)",
  CAST("edi_cstm_m2".adrs_kn as TEXT) AS "adrs_kn (edi_cstm_m2)",
  CAST("edi_store_m".adrs_kn as TEXT) AS "adrs_kn (edi_store_m)",
  CAST("edi_cstm_m".adrs_kn as TEXT) AS "adrs_kn",
  CAST("edi_cstm_m1".adrs_knj as TEXT) AS "adrs_knj (edi_cstm_m1)",
  CAST("edi_cstm_m2".adrs_knj as TEXT) AS "adrs_knj (edi_cstm_m2)",
  CAST("edi_store_m".adrs_knj1 as TEXT) AS "adrs_knj1",
  CAST("edi_store_m".adrs_knj2 as TEXT) AS "adrs_knj2",
  CAST("edi_cstm_m".adrs_knj as TEXT) AS "adrs_knj",
  CAST("edi_store_m".agrm_str as TEXT) AS "agrm_str",
  CAST("edi_store_m".all_str_ass as TEXT) AS "all_str_ass",
  CAST("edi_chn_m1".an_typ as TEXT) AS "an_typ (edi_chn_m1)",
  CAST("edi_chn_m".an_typ as TEXT) AS "an_typ",
  "mt_tp_status_mapping".approve_status_cd as "approve_status_cd",
  CAST("edi_item_m1".base_prod as TEXT) AS "base_prod (edi_item_m1)",
  CAST("edi_item_m".base_prod as TEXT) AS "base_prod",
  CAST("edi_item_m1".base_uom as TEXT) AS "base_uom (edi_item_m1)",
  CAST("edi_item_m".base_uom as TEXT) AS "base_uom",
  CAST("edi_cstm_m1".bl_cls_dt as TEXT) AS "bl_cls_dt (edi_cstm_m1)",
  CAST("edi_cstm_m2".bl_cls_dt as TEXT) AS "bl_cls_dt (edi_cstm_m2)",
  CAST("edi_cstm_m".bl_cls_dt as TEXT) AS "bl_cls_dt",
  CAST("edi_item_m1".brnd as TEXT) AS "brnd (edi_item_m1)",
  CAST("edi_item_m".brnd as TEXT) AS "brnd",
  CAST("edi_cstm_m1".buy_from_cd as TEXT) AS "buy_from_cd (edi_cstm_m1)",
  CAST("edi_cstm_m2".buy_from_cd as TEXT) AS "buy_from_cd (edi_cstm_m2)",
  CAST("edi_cstm_m".buy_from_cd as TEXT) AS "buy_from_cd",
  "sdl_mds_jp_jan_description"."changetrackingmask" as "changetrackingmask (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".changetrackingmask as "changetrackingmask",
  CAST("edi_chn_m1".chn_cd as TEXT) AS "chn_cd (edi_chn_m1)",
  CAST("edi_store_m".chn_cd as TEXT) AS "chn_cd (edi_store_m)",
  CAST("mt_chn_mjp_emp_chg".chn_cd as TEXT) AS "chn_cd (mt_chn_mjp_emp_chg)",
  CAST("mt_chn_mjp_emp_chg1".chn_cd as TEXT) AS "chn_cd (mt_chn_mjp_emp_chg1)",
  CAST("mt_chn_mjp_emp_chg2".chn_cd as TEXT) AS "chn_cd (mt_chn_mjp_emp_chg2)",
  CAST("mt_chn_mjp_emp_chg3".chn_cd as TEXT) AS "chn_cd (mt_chn_mjp_emp_chg3)",
  CAST("edi_chn_m".chn_cd as TEXT) AS "chn_cd",
  CAST("edi_store_m".chn_cd_oth as TEXT) AS "chn_cd_oth",
  CAST("edi_chn_m1".chn_offc_cd as TEXT) AS "chn_offc_cd (edi_chn_m1)",
  CAST("edi_store_m".chn_offc_cd as TEXT) AS "chn_offc_cd (edi_store_m)",
  CAST("edi_chn_m".chn_offc_cd as TEXT) AS "chn_offc_cd",
  CAST("edi_chn_m1".cmmn_nm as TEXT) AS "cmmn_nm (edi_chn_m1)",
  CAST("edi_chn_m".cmmn_nm as TEXT) AS "cmmn_nm",
  CAST("edi_store_m".cmmn_nm_kn as TEXT) AS "cmmn_nm_kn",
  CAST("edi_store_m".cmmn_nm_knj as TEXT) AS "cmmn_nm_knj",
  CAST("edi_cstm_m1".cmnt1 as TEXT) AS "cmnt1 (edi_cstm_m1)",
  CAST("edi_cstm_m2".cmnt1 as TEXT) AS "cmnt1 (edi_cstm_m2)",
  CAST("edi_cstm_m".cmnt1 as TEXT) AS "cmnt1",
  CAST("sdl_mds_jp_jan_description"."code" as TEXT) AS "code (sdl_mds_jp_jan_description)",
  CAST("sdl_mds_jp_product_ca_ratio".code as TEXT) AS "code",
  "edi_chn_m1".create_dt as "create_dt (edi_chn_m1)",
  "edi_cstm_m".create_dt as "create_dt (edi_cstm_m)",
  "edi_cstm_m1".create_dt as "create_dt (edi_cstm_m1)",
  "edi_cstm_m2".create_dt as "create_dt (edi_cstm_m2)",
  "edi_item_m".create_dt as "create_dt (edi_item_m)",
  "edi_item_m1".create_dt as "create_dt (edi_item_m1)",
  "edi_store_m".create_dt as "create_dt (edi_store_m)",
  "edi_chn_m".create_dt as "create_dt",
  CAST("edi_chn_m1".create_user as TEXT) AS "create_user (edi_chn_m1)",
  CAST("edi_cstm_m".create_user as TEXT) AS "create_user (edi_cstm_m)",
  CAST("edi_cstm_m1".create_user as TEXT) AS "create_user (edi_cstm_m1)",
  CAST("edi_cstm_m2".create_user as TEXT) AS "create_user (edi_cstm_m2)",
  CAST("edi_item_m".create_user as TEXT) AS "create_user (edi_item_m)",
  CAST("edi_item_m1".create_user as TEXT) AS "create_user (edi_item_m1)",
  CAST("edi_store_m".create_user as TEXT) AS "create_user (edi_store_m)",
  CAST("edi_chn_m".create_user as TEXT) AS "create_user",
  "mt_emp1".cstctr_cd as "cstctr_cd (mt_emp1)",
  "mt_emp2".cstctr_cd as "cstctr_cd (mt_emp2)",
  "mt_emp3".cstctr_cd as "cstctr_cd (mt_emp3)",
  "mt_emp".cstctr_cd as "cstctr_cd",
  CAST("edi_cstm_m1".cstm_cd as TEXT) AS "cstm_cd (edi_cstm_m1)",
  CAST("edi_cstm_m2".cstm_cd as TEXT) AS "cstm_cd (edi_cstm_m2)",
  CAST("edi_cstm_m".cstm_cd as TEXT) AS "cstm_cd",
  CAST("edi_cstm_m1".cstm_nm as TEXT) AS "cstm_nm (edi_cstm_m1)",
  CAST("edi_cstm_m2".cstm_nm as TEXT) AS "cstm_nm (edi_cstm_m2)",
  CAST("edi_cstm_m".cstm_nm as TEXT) AS "cstm_nm",
  CAST("edi_cstm_m1".cstm_nm_kn as TEXT) AS "cstm_nm_kn (edi_cstm_m1)",
  CAST("edi_cstm_m2".cstm_nm_kn as TEXT) AS "cstm_nm_kn (edi_cstm_m2)",
  CAST("edi_cstm_m".cstm_nm_kn as TEXT) AS "cstm_nm_kn",
  CAST("edi_cstm_m1".cstm_nm_knj as TEXT) AS "cstm_nm_knj (edi_cstm_m1)",
  CAST("edi_cstm_m2".cstm_nm_knj as TEXT) AS "cstm_nm_knj (edi_cstm_m2)",
  CAST("x_e382abe382b9e382bfe383a0 sql e382afe382a8e383aa_".cstm_nm_knj as TEXT) AS "cstm_nm_knj (x_e382abe382b9e382bfe383a0 sql e382afe382a8e383aa_",
  CAST("x_e382abe382b9e382bfe383a0 sql e382afe382a8e383az1".cstm_nm_knj as TEXT) AS "cstm_nm_knj (x_e382abe382b9e382bfe383a0 sql e382afe382a8e383az1",
  CAST("edi_cstm_m".cstm_nm_knj as TEXT) AS "cstm_nm_knj",
  CAST("edi_cstm_m1".cstm_typ as TEXT) AS "cstm_typ (edi_cstm_m1)",
  CAST("edi_cstm_m2".cstm_typ as TEXT) AS "cstm_typ (edi_cstm_m2)",
  CAST("edi_cstm_m".cstm_typ as TEXT) AS "cstm_typ",
  "mt_account_key".csw_category_1 as "csw_category_1",
  "mt_account_key".csw_sort_key as "csw_sort_key",
  CAST("edi_cstm_m1".cust_tfi_num as TEXT) AS "cust_tfi_num (edi_cstm_m1)",
  CAST("edi_cstm_m2".cust_tfi_num as TEXT) AS "cust_tfi_num (edi_cstm_m2)",
  CAST("edi_cstm_m".cust_tfi_num as TEXT) AS "cust_tfi_num",
  "mt_cld1".day as "day (mt_cld1)",
  "mt_cld".day as "day",
  "mt_cld1".day_of_week as "day_of_week (mt_cld1)",
  "mt_cld".day_of_week as "day_of_week",
  "sdl_mds_jp_product_ca_ratio".default_ca_ratio as "default_ca_ratio",
  "mt_jan_detail".delete_flag as "delete_flag (mt_jan_detail)",
  "mt_tp_status_mapping".delete_flag as "delete_flag (mt_tp_status_mapping)",
  "mt_account_key".delete_flag as "delete_flag",
  "mt_tp_status_mapping".direct_flg as "direct_flg",
  "edi_item_m1".discon_dt as "discon_dt (edi_item_m1)",
  "edi_item_m".discon_dt as "discon_dt",
  CAST("mt_chn_mjp_emp_chg1".division as TEXT) AS "division (mt_chn_mjp_emp_chg1)",
  CAST("mt_chn_mjp_emp_chg2".division as TEXT) AS "division (mt_chn_mjp_emp_chg2)",
  CAST("mt_chn_mjp_emp_chg3".division as TEXT) AS "division (mt_chn_mjp_emp_chg3)",
  CAST("mt_chn_mjp_emp_chg".division as TEXT) AS "division",
  CAST("mt_chn_mjp_emp_chg1".division_group as TEXT) AS "division_group (mt_chn_mjp_emp_chg1)",
  CAST("mt_chn_mjp_emp_chg2".division_group as TEXT) AS "division_group (mt_chn_mjp_emp_chg2)",
  CAST("mt_chn_mjp_emp_chg3".division_group as TEXT) AS "division_group (mt_chn_mjp_emp_chg3)",
  CAST("mt_chn_mjp_emp_chg".division_group as TEXT) AS "division_group",
  CAST("edi_item_m1".dlt_flg as TEXT) AS "dlt_flg (edi_item_m1)",
  CAST("edi_item_m".dlt_flg as TEXT) AS "dlt_flg",
  CAST("mt_chn_mjp_emp_chg1".emp_cd as TEXT) AS "emp_cd (mt_chn_mjp_emp_chg1)",
  CAST("mt_chn_mjp_emp_chg2".emp_cd as TEXT) AS "emp_cd (mt_chn_mjp_emp_chg2)",
  CAST("mt_chn_mjp_emp_chg3".emp_cd as TEXT) AS "emp_cd (mt_chn_mjp_emp_chg3)",
  "mt_emp".emp_cd as "emp_cd (mt_emp)",
  "mt_emp1".emp_cd as "emp_cd (mt_emp1)",
  "mt_emp2".emp_cd as "emp_cd (mt_emp2)",
  "mt_emp3".emp_cd as "emp_cd (mt_emp3)",
  CAST("mt_chn_mjp_emp_chg".emp_cd as TEXT) AS "emp_cd",
  CAST("edi_store_m".emp_cd_kk as TEXT) AS "emp_cd_kk",
  CAST("edi_store_m".emp_cd_roc as TEXT) AS "emp_cd_roc",
  "mt_emp1".emp_nm as "emp_nm (mt_emp1)",
  "mt_emp2".emp_nm as "emp_nm (mt_emp2)",
  "mt_emp3".emp_nm as "emp_nm (mt_emp3)",
  "mt_emp".emp_nm as "emp_nm",
  "mt_emp1".emp_nm_knj as "emp_nm_knj (mt_emp1)",
  "mt_emp2".emp_nm_knj as "emp_nm_knj (mt_emp2)",
  "mt_emp3".emp_nm_knj as "emp_nm_knj (mt_emp3)",
  "mt_emp".emp_nm_knj as "emp_nm_knj",
  "mt_emp1".emp_typ as "emp_typ (mt_emp1)",
  "mt_emp2".emp_typ as "emp_typ (mt_emp2)",
  "mt_emp3".emp_typ as "emp_typ (mt_emp3)",
  "mt_emp".emp_typ as "emp_typ",
  "sdl_mds_jp_jan_description"."enterdatetime" as "enterdatetime (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".enterdatetime as "enterdatetime",
  "sdl_mds_jp_jan_description"."enterusername" as "enterusername (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".enterusername as "enterusername",
  "sdl_mds_jp_jan_description"."enterversionnumber" as "enterversionnumber (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".enterversionnumber as "enterversionnumber",
  CAST("edi_cstm_m1".fax_nun as TEXT) AS "fax_nun (edi_cstm_m1)",
  CAST("edi_cstm_m2".fax_nun as TEXT) AS "fax_nun (edi_cstm_m2)",
  CAST("edi_cstm_m".fax_nun as TEXT) AS "fax_nun",
  CAST("mt_chn_mjp_emp_chg1".fc_cd as TEXT) AS "fc_cd (mt_chn_mjp_emp_chg1)",
  CAST("mt_chn_mjp_emp_chg2".fc_cd as TEXT) AS "fc_cd (mt_chn_mjp_emp_chg2)",
  CAST("mt_chn_mjp_emp_chg3".fc_cd as TEXT) AS "fc_cd (mt_chn_mjp_emp_chg3)",
  CAST("mt_chn_mjp_emp_chg".fc_cd as TEXT) AS "fc_cd",
  "mt_account_key".feild_condition as "feild_condition",
  CAST("edi_chn_m1".frnc as TEXT) AS "frnc (edi_chn_m1)",
  CAST("edi_chn_m".frnc as TEXT) AS "frnc",
  "vw_m_item_frnch_cdd".frnch_cd as "frnch_cd",
  "vw_m_item_frnch_cdd".frnch_group_cd as "frnch_group_cd",
  "vw_m_item_frnch_cdd".frnch_group_nm as "frnch_group_nm",
  "vw_m_item_frnch_cdd".frnch_group_srt as "frnch_group_srt",
  "vw_m_item_frnch_cdd".frnch_nm as "frnch_nm",
  "vw_m_item_frnch_cdd".frnch_srt as "frnch_srt",
  "mt_cld1".half as "half (mt_cld1)",
  "mt_cld".half as "half",
  "mt_cld1".half_15 as "half_15 (mt_cld1)",
  "mt_cld".half_15 as "half_15",
  "mt_cld1".half_15_nm as "half_15_nm (mt_cld1)",
  "mt_cld".half_15_nm as "half_15_nm",
  "mt_cld1".half_20 as "half_20 (mt_cld1)",
  "mt_cld".half_20 as "half_20",
  "mt_cld1".half_20_nm as "half_20_nm (mt_cld1)",
  "mt_cld".half_20_nm as "half_20_nm",
  "mt_cld1".half_445 as "half_445 (mt_cld1)",
  "mt_cld".half_445 as "half_445",
  "mt_cld1".half_445_nm as "half_445_nm (mt_cld1)",
  "mt_cld".half_445_nm as "half_445_nm",
  "mt_cld1".half_nm as "half_nm (mt_cld1)",
  "mt_cld".half_nm as "half_nm",
  "sdl_mds_jp_jan_description"."id" as "id (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".id as "id",
  CAST("edi_item_m1".imp_item_flg as TEXT) AS "imp_item_flg (edi_item_m1)",
  CAST("edi_item_m".imp_item_flg as TEXT) AS "imp_item_flg",
  CAST("edi_item_m".item_cd as TEXT) AS "item_cd (edi_item_m)",
  CAST("edi_item_m1".item_cd as TEXT) AS "item_cd (edi_item_m1)",
  "sdl_mds_jp_product_ca_ratio".item_cd as "item_cd (sdl_mds_jp_product_ca_ratio)",
  "vw_m_item_frnch_cdd".item_cd as "item_cd (vw_m_item_frnch_cdd)",
  CAST("vw_jan_change".item_cd as TEXT) AS "item_cd",
  CAST("edi_item_m1".item_cd_jd as TEXT) AS "item_cd_jd (edi_item_m1)",
  CAST("edi_item_m".item_cd_jd as TEXT) AS "item_cd_jd",
  CAST("edi_item_m1".item_nm as TEXT) AS "item_nm (edi_item_m1)",
  CAST("edi_item_m".item_nm as TEXT) AS "item_nm",
  CAST("edi_item_m1".iten_nm_kn as TEXT) AS "iten_nm_kn (edi_item_m1)",
  CAST("edi_item_m".iten_nm_kn as TEXT) AS "iten_nm_kn",
  CAST("edi_item_m1".iten_nm_knj as TEXT) AS "iten_nm_knj (edi_item_m1)",
  CAST("sdl_mds_jp_jan_description"."iten_nm_knj" as TEXT) AS "iten_nm_knj (sdl_mds_jp_jan_description)",
  CAST("edi_item_m".iten_nm_knj as TEXT) AS "iten_nm_knj",
  CAST("edi_item_m1".itf_cd as TEXT) AS "itf_cd (edi_item_m1)",
  CAST("edi_item_m".itf_cd as TEXT) AS "itf_cd",
  CAST("edi_item_m1".itf_cd_so as TEXT) AS "itf_cd_so (edi_item_m1)",
  CAST("edi_item_m".itf_cd_so as TEXT) AS "itf_cd_so",
  CAST("edi_item_m".jan_cd as TEXT) AS "jan_cd (edi_item_m)",
  CAST("edi_item_m1".jan_cd as TEXT) AS "jan_cd (edi_item_m1)",
  CAST("vw_jan_change".jan_cd as TEXT) AS "jan_cd (vw_jan_change)",
  "mt_jan_detail".jan_cd as "jan_cd",
  CAST("edi_item_m1".jan_cd_so as TEXT) AS "jan_cd_so (edi_item_m1)",
  CAST("edi_item_m".jan_cd_so as TEXT) AS "jan_cd_so",
  "dm_integration_dly".jcp_account as "jcp_account",
  "dm_integration_dly".jcp_amt as "jcp_amt",
  "dm_integration_dly".jcp_analysis_type as "jcp_analysis_type",
  "dm_integration_dly".jcp_chn_cd as "jcp_chn_cd",
  "dm_integration_dly".jcp_chn_offc_cd as "jcp_chn_offc_cd",
  "dm_integration_dly".jcp_create_date as "jcp_create_date",
  "dm_integration_dly".jcp_cstm_cd as "jcp_cstm_cd",
  "mt_tp_status_mapping".jcp_data_category as "jcp_data_category (mt_tp_status_mapping)",
  "dm_integration_dly".jcp_data_category as "jcp_data_category",
  "dm_integration_dly".jcp_data_source as "jcp_data_source",
  "dm_integration_dly".jcp_date as "jcp_date",
  "dm_integration_dly".jcp_jan_cd as "jcp_jan_cd",
  "dm_integration_dly".jcp_load_date as "jcp_load_date",
  "dm_integration_dly".jcp_new_item_type as "jcp_new_item_type",
  "dm_integration_dly".jcp_plan_item_type as "jcp_plan_item_type",
  "dm_integration_dly".jcp_plan_type as "jcp_plan_type",
  "dm_integration_dly".jcp_qty as "jcp_qty",
  "dm_integration_dly".jcp_str_cd as "jcp_str_cd",
  "dm_integration_dly".jcp_unit_prc as "jcp_unit_prc",
  CAST("edi_cstm_m1".jis_city_cd as TEXT) AS "jis_city_cd (edi_cstm_m1)",
  CAST("edi_cstm_m2".jis_city_cd as TEXT) AS "jis_city_cd (edi_cstm_m2)",
  CAST("edi_store_m".jis_city_cd as TEXT) AS "jis_city_cd (edi_store_m)",
  CAST("edi_cstm_m".jis_city_cd as TEXT) AS "jis_city_cd",
  CAST("edi_store_m".jis_prfct_c as TEXT) AS "jis_prfct_c",
  CAST("edi_cstm_m1".jis_prfct_cd as TEXT) AS "jis_prfct_cd (edi_cstm_m1)",
  CAST("edi_cstm_m2".jis_prfct_cd as TEXT) AS "jis_prfct_cd (edi_cstm_m2)",
  CAST("edi_cstm_m".jis_prfct_cd as TEXT) AS "jis_prfct_cd",
  CAST("edi_cstm_m1".jrsd_dpt_cd as TEXT) AS "jrsd_dpt_cd (edi_cstm_m1)",
  CAST("edi_cstm_m2".jrsd_dpt_cd as TEXT) AS "jrsd_dpt_cd (edi_cstm_m2)",
  CAST("edi_cstm_m".jrsd_dpt_cd as TEXT) AS "jrsd_dpt_cd",
  "mt_account_key"."key_figure_#" as "key_figure_#",
  "mt_account_key".key_figure_nm as "key_figure_nm",
  "mt_account_key".key_figure_nm_dsp as "key_figure_nm_dsp",
  "mt_account_key".key_figure_nm_knj as "key_figure_nm_knj",
  "sdl_mds_jp_jan_description"."lastchgdatetime" as "lastchgdatetime (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".lastchgdatetime as "lastchgdatetime",
  "sdl_mds_jp_jan_description"."lastchgusername" as "lastchgusername (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".lastchgusername as "lastchgusername",
  "sdl_mds_jp_jan_description"."lastchgversionnumber" as "lastchgversionnumber (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".lastchgversionnumber as "lastchgversionnumber",
  CAST("edi_item_m1".ldw_flg01 as TEXT) AS "ldw_flg01 (edi_item_m1)",
  CAST("edi_item_m".ldw_flg01 as TEXT) AS "ldw_flg01",
  CAST("edi_item_m1".ldw_flg02 as TEXT) AS "ldw_flg02 (edi_item_m1)",
  CAST("edi_item_m".ldw_flg02 as TEXT) AS "ldw_flg02",
  CAST("edi_item_m1".ldw_flg03 as TEXT) AS "ldw_flg03 (edi_item_m1)",
  CAST("edi_item_m".ldw_flg03 as TEXT) AS "ldw_flg03",
  CAST("edi_chn_m1".lgl_nm as TEXT) AS "lgl_nm (edi_chn_m1)",
  CAST("edi_chn_m".lgl_nm as TEXT) AS "lgl_nm",
  CAST("edi_store_m".lgl_nm_kn as TEXT) AS "lgl_nm_kn",
  CAST("edi_store_m".lgl_nm_knj1 as TEXT) AS "lgl_nm_knj1",
  CAST("edi_store_m".lgl_nm_knj2 as TEXT) AS "lgl_nm_knj2",
  "mt_tp_status_mapping".mapping_status_cd1 as "mapping_status_cd1",
  "mt_tp_status_mapping".mapping_status_cd2 as "mapping_status_cd2",
  "mt_tp_status_mapping".mapping_status_cd3 as "mapping_status_cd3",
  "mt_tp_status_mapping".mapping_status_cd4 as "mapping_status_cd4",
  "mt_tp_status_mapping".mapping_status_cd5 as "mapping_status_cd5",
  "mt_tp_status_mapping".mapping_status_nm1 as "mapping_status_nm1",
  "mt_tp_status_mapping".mapping_status_nm2 as "mapping_status_nm2",
  "mt_tp_status_mapping".mapping_status_nm3 as "mapping_status_nm3",
  "mt_tp_status_mapping".mapping_status_nm4 as "mapping_status_nm4",
  "mt_tp_status_mapping".mapping_status_nm5 as "mapping_status_nm5",
  CAST("edi_item_m1".mega_brnd as TEXT) AS "mega_brnd (edi_item_m1)",
  CAST("edi_item_m".mega_brnd as TEXT) AS "mega_brnd",
  CAST("edi_item_m1".mega_brnd_chkflg as TEXT) AS "mega_brnd_chkflg (edi_item_m1)",
  CAST("edi_item_m".mega_brnd_chkflg as TEXT) AS "mega_brnd_chkflg",
  "vw_m_item_frnch_cdd".min_prod_cd as "min_prod_cd",
  "vw_m_item_frnch_cdd".min_prod_nm as "min_prod_nm",
  "vw_m_item_frnch_cdd".min_prod_srt as "min_prod_srt",
  "vw_m_item_frnch_cdd".mjr_prod_cd2 as "mjr_prod_cd2",
  "vw_m_item_frnch_cdd".mjr_prod_cd as "mjr_prod_cd",
  "vw_m_item_frnch_cdd".mjr_prod_nm2 as "mjr_prod_nm2",
  "vw_m_item_frnch_cdd".mjr_prod_nm as "mjr_prod_nm",
  "vw_m_item_frnch_cdd".mjr_prod_srt2 as "mjr_prod_srt2",
  "vw_m_item_frnch_cdd".mjr_prod_srt as "mjr_prod_srt",
  "mt_cld1".month as "month (mt_cld1)",
  "mt_cld".month as "month",
  "mt_cld1".month_15 as "month_15 (mt_cld1)",
  "mt_cld".month_15 as "month_15",
  "mt_cld1".month_15_nm as "month_15_nm (mt_cld1)",
  "mt_cld".month_15_nm as "month_15_nm",
  "mt_cld1".month_20 as "month_20 (mt_cld1)",
  "mt_cld".month_20 as "month_20",
  "mt_cld1".month_20_nm as "month_20_nm (mt_cld1)",
  "mt_cld".month_20_nm as "month_20_nm",
  "mt_cld1".month_445 as "month_445 (mt_cld1)",
  "mt_cld".month_445 as "month_445",
  "mt_cld1".month_445_nm as "month_445_nm (mt_cld1)",
  "mt_cld".month_445_nm as "month_445_nm",
  "mt_cld1".month_nm as "month_nm (mt_cld1)",
  "mt_cld".month_nm as "month_nm",
  "sdl_mds_jp_jan_description"."muid" as "muid (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".muid as "muid",
  "mt_cld1".mweek_15ms as "mweek_15ms (mt_cld1)",
  "mt_cld".mweek_15ms as "mweek_15ms",
  "mt_cld1".mweek_15ms_iso as "mweek_15ms_iso (mt_cld1)",
  "mt_cld".mweek_15ms_iso as "mweek_15ms_iso",
  "mt_cld1".mweek_15ss as "mweek_15ss (mt_cld1)",
  "mt_cld".mweek_15ss as "mweek_15ss",
  "mt_cld1".mweek_15ss_iso as "mweek_15ss_iso (mt_cld1)",
  "mt_cld".mweek_15ss_iso as "mweek_15ss_iso",
  "mt_cld1".mweek_20 as "mweek_20 (mt_cld1)",
  "mt_cld".mweek_20 as "mweek_20",
  "mt_cld1".mweek_20_iso as "mweek_20_iso (mt_cld1)",
  "mt_cld".mweek_20_iso as "mweek_20_iso",
  "mt_cld1".mweek_445 as "mweek_445 (mt_cld1)",
  "mt_cld".mweek_445 as "mweek_445",
  "mt_cld1".mweek_445_iso as "mweek_445_iso (mt_cld1)",
  "mt_cld".mweek_445_iso as "mweek_445_iso",
  CAST("sdl_mds_jp_jan_description"."name" as TEXT) AS "name (sdl_mds_jp_jan_description)",
  CAST("sdl_mds_jp_product_ca_ratio".name as TEXT) AS "name",
  "sdl_mds_jp_product_ca_ratio".new_ca_ratio as "new_ca_ratio",
  CAST("edi_item_m1".new_prod_type as TEXT) AS "new_prod_type (edi_item_m1)",
  CAST("edi_item_m".new_prod_type as TEXT) AS "new_prod_type",
  "mt_cld1".opr_flg as "opr_flg (mt_cld1)",
  "mt_cld".opr_flg as "opr_flg",
  "mt_emp1".org_cd as "org_cd (mt_emp1)",
  "mt_emp2".org_cd as "org_cd (mt_emp2)",
  "mt_emp3".org_cd as "org_cd (mt_emp3)",
  "mt_emp".org_cd as "org_cd",
  CAST("edi_item_m1".parent_item_cd as TEXT) AS "parent_item_cd (edi_item_m1)",
  CAST("edi_item_m".parent_item_cd as TEXT) AS "parent_item_cd",
  CAST("edi_item_m1".pc as TEXT) AS "pc (edi_item_m1)",
  CAST("edi_item_m".pc as TEXT) AS "pc",
  CAST("edi_store_m".pj_ass as TEXT) AS "pj_ass",
  CAST("edi_chn_m1".pj_typ as TEXT) AS "pj_typ (edi_chn_m1)",
  CAST("edi_chn_m".pj_typ as TEXT) AS "pj_typ",
  CAST("edi_item_m1".planet_l3_flg as TEXT) AS "planet_l3_flg (edi_item_m1)",
  CAST("edi_item_m".planet_l3_flg as TEXT) AS "planet_l3_flg",
  "dm_integration_dly".plnt as "plnt",
  CAST("edi_cstm_m1".plnt_cd as TEXT) AS "plnt_cd (edi_cstm_m1)",
  CAST("edi_cstm_m2".plnt_cd as TEXT) AS "plnt_cd (edi_cstm_m2)",
  CAST("x_e382abe382b9e382bfe383a0 sql e382afe382a8e383aa_".plnt_cd as TEXT) AS "plnt_cd (x_e382abe382b9e382bfe383a0 sql e382afe382a8e383aa_)",
  CAST("x_e382abe382b9e382bfe383a0 sql e382afe382a8e383az1".plnt_cd as TEXT) AS "plnt_cd (x_e382abe382b9e382bfe383a0 sql e382afe382a8e383az1)",
  CAST("edi_cstm_m".plnt_cd as TEXT) AS "plnt_cd",
  "dm_integration_dly".pn_account_sub_cd as "pn_account_sub_cd",
  "dm_integration_dly".pn_cddfc as "pn_cddfc",
  "dm_integration_dly".pn_cddmp as "pn_cddmp",
  CAST("dm_integration_dly".pn_item_group as TEXT) AS "pn_item_group",
  CAST("dm_integration_dly".pn_plan_type as TEXT) AS "pn_plan_type",
  CAST("dm_integration_dly".pn_promotion_nm as TEXT) AS "pn_promotion_nm",
  "mt_prf".prf_cd as "prf_cd",
  "mt_prf".prf_nm_knj as "prf_nm_knj",
  CAST("mt_jan_detail".product_name as TEXT) AS "product_name",
  CAST("edi_item_m1".prom_goods_flg as TEXT) AS "prom_goods_flg (edi_item_m1)",
  CAST("edi_item_m".prom_goods_flg as TEXT) AS "prom_goods_flg",
  "mt_tp_status_mapping".promo_status_cd as "promo_status_cd",
  CAST("edi_cstm_m1".pst_cd as TEXT) AS "pst_cd (edi_cstm_m1)",
  CAST("edi_cstm_m2".pst_cd as TEXT) AS "pst_cd (edi_cstm_m2)",
  CAST("edi_cstm_m".pst_cd as TEXT) AS "pst_cd",
  CAST("edi_store_m".pst_co as TEXT) AS "pst_co",
  CAST("edi_item_m1".put_up as TEXT) AS "put_up (edi_item_m1)",
  CAST("edi_item_m".put_up as TEXT) AS "put_up",
  "mt_cld1".quarter as "quarter (mt_cld1)",
  "mt_cld".quarter as "quarter",
  "mt_cld1".quarter_15 as "quarter_15 (mt_cld1)",
  "mt_cld".quarter_15 as "quarter_15",
  "mt_cld1".quarter_15_nm as "quarter_15_nm (mt_cld1)",
  "mt_cld".quarter_15_nm as "quarter_15_nm",
  "mt_cld1".quarter_20 as "quarter_20 (mt_cld1)",
  "mt_cld".quarter_20 as "quarter_20",
  "mt_cld1".quarter_20_nm as "quarter_20_nm (mt_cld1)",
  "mt_cld".quarter_20_nm as "quarter_20_nm",
  "mt_cld1".quarter_445 as "quarter_445 (mt_cld1)",
  "mt_cld".quarter_445 as "quarter_445",
  "mt_cld1".quarter_445_nm as "quarter_445_nm (mt_cld1)",
  "mt_cld".quarter_445_nm as "quarter_445_nm",
  "mt_cld1".quarter_nm as "quarter_nm (mt_cld1)",
  "mt_cld".quarter_nm as "quarter_nm",
  CAST("edi_chn_m1".rank as TEXT) AS "rank (edi_chn_m1)",
  CAST("edi_chn_m".rank as TEXT) AS "rank",
  CAST("edi_cstm_m1".rebate_rep_cd as TEXT) AS "rebate_rep_cd (edi_cstm_m1)",
  CAST("edi_cstm_m2".rebate_rep_cd as TEXT) AS "rebate_rep_cd (edi_cstm_m2)",
  CAST("edi_cstm_m".rebate_rep_cd as TEXT) AS "rebate_rep_cd",
  "mt_account_key".reference_column as "reference_column",
  "mt_account_key".reference_field as "reference_field",
  "mt_account_key".reference_table as "reference_table",
  "edi_chn_m1".reg_dt as "reg_dt (edi_chn_m1)",
  "edi_cstm_m".reg_dt as "reg_dt (edi_cstm_m)",
  "edi_cstm_m1".reg_dt as "reg_dt (edi_cstm_m1)",
  "edi_cstm_m2".reg_dt as "reg_dt (edi_cstm_m2)",
  "edi_item_m".reg_dt as "reg_dt (edi_item_m)",
  "edi_item_m1".reg_dt as "reg_dt (edi_item_m1)",
  "edi_store_m".reg_dt as "reg_dt (edi_store_m)",
  "edi_chn_m".reg_dt as "reg_dt",
  "edi_item_m1".rel_dt as "rel_dt (edi_item_m1)",
  "edi_item_m".rel_dt as "rel_dt",
  "mt_tp_status_mapping".rslt_status_cd as "rslt_status_cd",
  CAST("sdl_mds_jp_product_ca_ratio".rtl_ho_cd_code as TEXT) AS "rtl_ho_cd_code",
  "sdl_mds_jp_product_ca_ratio".rtl_ho_cd_id as "rtl_ho_cd_id",
  CAST("sdl_mds_jp_product_ca_ratio".rtl_ho_cd_name as TEXT) AS "rtl_ho_cd_name",
  CAST("edi_chn_m1".sales_group as TEXT) AS "sales_group (edi_chn_m1)",
  CAST("edi_chn_m".sales_group as TEXT) AS "sales_group",
  "dm_integration_dly".sales_grp as "sales_grp",
  CAST("edi_item_m1".sap_cstm_type as TEXT) AS "sap_cstm_type (edi_item_m1)",
  CAST("edi_item_m".sap_cstm_type as TEXT) AS "sap_cstm_type",
  "edi_chn_m1".scnd_acnt_prsn as "scnd_acnt_prsn (edi_chn_m1)",
  "edi_chn_m".scnd_acnt_prsn as "scnd_acnt_prsn",
  CAST("edi_chn_m1".sgmt as TEXT) AS "sgmt (edi_chn_m1)",
  "mt_sgmt".sgmt as "sgmt (mt_sgmt)",
  "mt_sgmt1".sgmt as "sgmt (mt_sgmt1)",
  CAST("edi_chn_m".sgmt as TEXT) AS "sgmt",
  "mt_sgmt1".sgmt_nm as "sgmt_nm (mt_sgmt1)",
  "mt_sgmt".sgmt_nm as "sgmt_nm",
  "mt_sgmt1".sgmt_nm_rep as "sgmt_nm_rep (mt_sgmt1)",
  "mt_sgmt".sgmt_nm_rep as "sgmt_nm_rep",
  CAST("edi_cstm_m1".ship_dpt as TEXT) AS "ship_dpt (edi_cstm_m1)",
  CAST("edi_cstm_m2".ship_dpt as TEXT) AS "ship_dpt (edi_cstm_m2)",
  CAST("edi_cstm_m".ship_dpt as TEXT) AS "ship_dpt",
  "edi_cstm_m1".ship_ld_tm as "ship_ld_tm (edi_cstm_m1)",
  "edi_cstm_m2".ship_ld_tm as "ship_ld_tm (edi_cstm_m2)",
  "edi_cstm_m".ship_ld_tm as "ship_ld_tm",
  "dm_integration_dly".si_calday as "si_calday",
  "dm_integration_dly".si_fiscper as "si_fiscper",
  "dm_integration_dly".si_jcp_445_ymd_dt as "si_jcp_445_ymd_dt",
  "dm_integration_dly".si_jcp_create_dt as "si_jcp_create_dt",
  "dm_integration_dly".si_jcp_pan_flg as "si_jcp_pan_flg",
  "dm_integration_dly".si_jcp_update_dt as "si_jcp_update_dt",
  "dm_integration_dly".si_jcp_update_flg as "si_jcp_update_flg",
  "dm_integration_dly".si_material as "si_material",
  "mt_account_key".sign_of_number as "sign_of_number",
  "mt_emp1".slm_cd as "slm_cd (mt_emp1)",
  "mt_emp2".slm_cd as "slm_cd (mt_emp2)",
  "mt_emp3".slm_cd as "slm_cd (mt_emp3)",
  "mt_emp".slm_cd as "slm_cd",
  "mt_cld1".sls_flg as "sls_flg (mt_cld1)",
  "mt_cld".sls_flg as "sls_flg",
  "dm_integration_dly".so_chg_cd as "so_chg_cd",
  "dm_integration_dly".so_data_type as "so_data_type",
  "dm_integration_dly".so_dep_cd as "so_dep_cd",
  "dm_integration_dly".so_id as "so_id",
  "dm_integration_dly".so_item_cd_typ as "so_item_cd_typ",
  "dm_integration_dly".so_item_nm as "so_item_nm",
  "dm_integration_dly".so_item_nm_kanji as "so_item_nm_kanji",
  "dm_integration_dly".so_jcp_rec_seq as "so_jcp_rec_seq",
  "dm_integration_dly".so_net_prc as "so_net_prc",
  "dm_integration_dly".so_opt_fld as "so_opt_fld",
  "dm_integration_dly".so_person_in_charge as "so_person_in_charge",
  "dm_integration_dly".so_person_name as "so_person_name",
  "dm_integration_dly".so_price as "so_price",
  "dm_integration_dly".so_price_type as "so_price_type",
  "dm_integration_dly".so_qty_type as "so_qty_type",
  "dm_integration_dly".so_rcv_dt as "so_rcv_dt",
  "dm_integration_dly".so_rep_info as "so_rep_info",
  "dm_integration_dly".so_rep_name_kanji as "so_rep_name_kanji",
  "dm_integration_dly".so_rtl_address_cd as "so_rtl_address_cd",
  "dm_integration_dly".so_rtl_cd as "so_rtl_cd",
  "dm_integration_dly".so_rtl_ho_cd as "so_rtl_ho_cd",
  "dm_integration_dly".so_rtl_name as "so_rtl_name",
  "dm_integration_dly".so_rtl_name_kanji as "so_rtl_name_kanji",
  "dm_integration_dly".so_rtl_type as "so_rtl_type",
  "dm_integration_dly".so_sales_chan_type as "so_sales_chan_type",
  "dm_integration_dly".so_shp_num as "so_shp_num",
  "dm_integration_dly".so_shp_ws_cd as "so_shp_ws_cd",
  "dm_integration_dly".so_trade_cd as "so_trade_cd",
  "dm_integration_dly".so_trade_type as "so_trade_type",
  "dm_integration_dly".so_unt_prc as "so_unt_prc",
  "dm_integration_dly".so_ws_cd as "so_ws_cd",
  CAST("edi_store_m".str_cd as TEXT) AS "str_cd",
  CAST("edi_item_m1".sub_frnch as TEXT) AS "sub_frnch (edi_item_m1)",
  CAST("edi_item_m".sub_frnch as TEXT) AS "sub_frnch",
  CAST("edi_item_m1".succeeding_item_cd as TEXT) AS "succeeding_item_cd (edi_item_m1)",
  CAST("edi_item_m".succeeding_item_cd as TEXT) AS "succeeding_item_cd",
  CAST("edi_store_m".tel_no as TEXT) AS "tel_no",
  CAST("edi_cstm_m1".tel_num as TEXT) AS "tel_num (edi_cstm_m1)",
  CAST("edi_cstm_m2".tel_num as TEXT) AS "tel_num (edi_cstm_m2)",
  CAST("edi_cstm_m".tel_num as TEXT) AS "tel_num",
  "dm_integration_dly".tp_apl_appl_rel_flg as "tp_apl_appl_rel_flg",
  "dm_integration_dly".tp_apl_apply_begin_dt as "tp_apl_apply_begin_dt",
  "dm_integration_dly".tp_apl_apply_dt as "tp_apl_apply_dt",
  "dm_integration_dly".tp_apl_apply_emp_cd as "tp_apl_apply_emp_cd",
  "dm_integration_dly".tp_apl_apply_end_dt as "tp_apl_apply_end_dt",
  "dm_integration_dly".tp_apl_approve_dt as "tp_apl_approve_dt",
  "dm_integration_dly".tp_apl_approve_emp_cd as "tp_apl_approve_emp_cd",
  "dm_integration_dly".tp_apl_branch_cd as "tp_apl_branch_cd",
  CAST("dm_integration_dly".tp_apl_comment1 as TEXT) AS "tp_apl_comment1",
  "dm_integration_dly".tp_apl_create_dt as "tp_apl_create_dt",
  "dm_integration_dly".tp_apl_create_emp_cd as "tp_apl_create_emp_cd",
  "dm_integration_dly".tp_apl_direct_flg as "tp_apl_direct_flg",
  "dm_integration_dly".tp_apl_fiscal_year as "tp_apl_fiscal_year",
  "dm_integration_dly".tp_apl_fix_dt as "tp_apl_fix_dt",
  "dm_integration_dly".tp_apl_fix_emp_cd as "tp_apl_fix_emp_cd",
  "dm_integration_dly".tp_apl_midst_appl_flg as "tp_apl_midst_appl_flg",
  "dm_integration_dly".tp_apl_payee_typ_cd as "tp_apl_payee_typ_cd",
  "dm_integration_dly".tp_apl_target_chn_cd as "tp_apl_target_chn_cd",
  "dm_integration_dly".tp_apl_update_dt as "tp_apl_update_dt",
  "dm_integration_dly".tp_apl_update_emp_cd as "tp_apl_update_emp_cd",
  "dm_integration_dly".tp_apld_contract_no as "tp_apld_contract_no",
  "dm_integration_dly".tp_apld_cstm_head_office_cd as "tp_apld_cstm_head_office_cd",
  "dm_integration_dly".tp_apld_update_dt as "tp_apld_update_dt",
  "dm_integration_dly".tp_approve_status_cd as "tp_approve_status_cd",
  "dm_integration_dly".tp_bme_promo_cd as "tp_bme_promo_cd",
  "dm_integration_dly".tp_cstctr_cd as "tp_cstctr_cd",
  "dm_integration_dly".tp_cstm_cd as "tp_cstm_cd",
  "dm_integration_dly".tp_file_status_cd as "tp_file_status_cd",
  "dm_integration_dly".tp_promo_cd as "tp_promo_cd",
  "dm_integration_dly".tp_promo_nm as "tp_promo_nm",
  "dm_integration_dly".tp_promo_status_cd as "tp_promo_status_cd",
  "dm_integration_dly".tp_res_apply_dt as "tp_res_apply_dt",
  "dm_integration_dly".tp_res_apply_emp_cd as "tp_res_apply_emp_cd",
  "dm_integration_dly".tp_res_approve_dt as "tp_res_approve_dt",
  "dm_integration_dly".tp_res_approve_emp_cd as "tp_res_approve_emp_cd",
  "dm_integration_dly".tp_res_branch_cd as "tp_res_branch_cd",
  CAST("dm_integration_dly".tp_res_comment1 as TEXT) AS "tp_res_comment1",
  "dm_integration_dly".tp_res_create_dt as "tp_res_create_dt",
  "dm_integration_dly".tp_res_direct_flg as "tp_res_direct_flg",
  "dm_integration_dly".tp_res_fiscal_year as "tp_res_fiscal_year",
  "dm_integration_dly".tp_res_payee_cd as "tp_res_payee_cd",
  "dm_integration_dly".tp_res_payee_typ_cd as "tp_res_payee_typ_cd",
  "dm_integration_dly".tp_res_payment_dt as "tp_res_payment_dt",
  "dm_integration_dly".tp_res_payment_plan_dt as "tp_res_payment_plan_dt",
  "dm_integration_dly".tp_res_recognize_dt as "tp_res_recognize_dt",
  "dm_integration_dly".tp_res_recognize_emp_cd as "tp_res_recognize_emp_cd",
  "dm_integration_dly".tp_res_tax_flg as "tp_res_tax_flg",
  "dm_integration_dly".tp_res_trnsfr_dtl_cd as "tp_res_trnsfr_dtl_cd",
  "dm_integration_dly".tp_res_update_dt as "tp_res_update_dt",
  "dm_integration_dly".tp_resd_cancel_dt as "tp_resd_cancel_dt",
  CAST("dm_integration_dly".tp_resd_comment1 as TEXT) AS "tp_resd_comment1",
  "dm_integration_dly".tp_resd_contract_no as "tp_resd_contract_no",
  "dm_integration_dly".tp_resd_cstm_head_office_cd as "tp_resd_cstm_head_office_cd",
  "dm_integration_dly".tp_resd_direct_dtl_flg as "tp_resd_direct_dtl_flg",
  "dm_integration_dly".tp_resd_payee_typ_cd as "tp_resd_payee_typ_cd",
  "dm_integration_dly".tp_resd_reason_cd as "tp_resd_reason_cd",
  "dm_integration_dly".tp_resd_rslt_input_dt as "tp_resd_rslt_input_dt",
  "dm_integration_dly".tp_resd_servey_total_dt as "tp_resd_servey_total_dt",
  "dm_integration_dly".tp_resd_tax_amt as "tp_resd_tax_amt",
  "dm_integration_dly".tp_resd_tax_rate as "tp_resd_tax_rate",
  "dm_integration_dly".tp_resd_update_dt as "tp_resd_update_dt",
  "dm_integration_dly".tp_rslt_status_cd as "tp_rslt_status_cd",
  "dm_integration_dly".tp_sap_cancel_dt as "tp_sap_cancel_dt",
  "dm_integration_dly".tp_sap_cnt_dt as "tp_sap_cnt_dt",
  "dm_integration_dly".tp_tsp_acnt_cd as "tp_tsp_acnt_cd",
  "dm_integration_dly".tp_unit_cost as "tp_unit_cost",
  "dm_integration_dly".tp_val_fixed_appl_cnt as "tp_val_fixed_appl_cnt",
  "dm_integration_dly".tp_val_fixed_type as "tp_val_fixed_type",
  CAST("edi_cstm_m1".transport_fee_id as TEXT) AS "transport_fee_id (edi_cstm_m1)",
  CAST("edi_cstm_m2".transport_fee_id as TEXT) AS "transport_fee_id (edi_cstm_m2)",
  CAST("edi_cstm_m".transport_fee_id as TEXT) AS "transport_fee_id",
  CAST("edi_cstm_m1".transport_timing as TEXT) AS "transport_timing (edi_cstm_m1)",
  CAST("edi_cstm_m2".transport_timing as TEXT) AS "transport_timing (edi_cstm_m2)",
  CAST("edi_cstm_m".transport_timing as TEXT) AS "transport_timing",
  CAST("edi_cstm_m1".transporter_id as TEXT) AS "transporter_id (edi_cstm_m1)",
  CAST("edi_cstm_m2".transporter_id as TEXT) AS "transporter_id (edi_cstm_m2)",
  CAST("edi_cstm_m".transporter_id as TEXT) AS "transporter_id",
  CAST("edi_store_m".trd_cd as TEXT) AS "trd_cd",
  CAST("edi_store_m".trd_offc_cd as TEXT) AS "trd_offc_cd",
  CAST("edi_cstm_m1".trd_typ_cg_flg as TEXT) AS "trd_typ_cg_flg (edi_cstm_m1)",
  CAST("edi_cstm_m2".trd_typ_cg_flg as TEXT) AS "trd_typ_cg_flg (edi_cstm_m2)",
  CAST("edi_cstm_m".trd_typ_cg_flg as TEXT) AS "trd_typ_cg_flg",
  "edi_item_m1".unt_prc as "unt_prc (edi_item_m1)",
  "edi_item_m".unt_prc as "unt_prc",
  "edi_chn_m1".update_dt as "update_dt (edi_chn_m1)",
  "edi_cstm_m".update_dt as "update_dt (edi_cstm_m)",
  "edi_cstm_m1".update_dt as "update_dt (edi_cstm_m1)",
  "edi_cstm_m2".update_dt as "update_dt (edi_cstm_m2)",
  "edi_item_m".update_dt as "update_dt (edi_item_m)",
  "edi_item_m1".update_dt as "update_dt (edi_item_m1)",
  "edi_store_m".update_dt as "update_dt (edi_store_m)",
  "mt_account_key".update_dt as "update_dt (mt_account_key)",
  "mt_chn_mjp_emp_chg".update_dt as "update_dt (mt_chn_mjp_emp_chg)",
  "mt_chn_mjp_emp_chg1".update_dt as "update_dt (mt_chn_mjp_emp_chg1)",
  "mt_chn_mjp_emp_chg2".update_dt as "update_dt (mt_chn_mjp_emp_chg2)",
  "mt_chn_mjp_emp_chg3".update_dt as "update_dt (mt_chn_mjp_emp_chg3)",
  "mt_emp".update_dt as "update_dt (mt_emp)",
  "mt_emp1".update_dt as "update_dt (mt_emp1)",
  "mt_emp2".update_dt as "update_dt (mt_emp2)",
  "mt_emp3".update_dt as "update_dt (mt_emp3)",
  "mt_jan_detail".update_dt as "update_dt (mt_jan_detail)",
  "mt_prf".update_dt as "update_dt (mt_prf)",
  "mt_sgmt".update_dt as "update_dt (mt_sgmt)",
  "mt_sgmt1".update_dt as "update_dt (mt_sgmt1)",
  "mt_tp_status_mapping".update_dt as "update_dt (mt_tp_status_mapping)",
  "edi_chn_m".update_dt as "update_dt",
  CAST("edi_chn_m1".update_user as TEXT) AS "update_user (edi_chn_m1)",
  CAST("edi_cstm_m".update_user as TEXT) AS "update_user (edi_cstm_m)",
  CAST("edi_cstm_m1".update_user as TEXT) AS "update_user (edi_cstm_m1)",
  CAST("edi_cstm_m2".update_user as TEXT) AS "update_user (edi_cstm_m2)",
  CAST("edi_item_m".update_user as TEXT) AS "update_user (edi_item_m)",
  CAST("edi_item_m1".update_user as TEXT) AS "update_user (edi_item_m1)",
  CAST("edi_store_m".update_user as TEXT) AS "update_user (edi_store_m)",
  "mt_account_key".update_user as "update_user (mt_account_key)",
  "mt_chn_mjp_emp_chg".update_user as "update_user (mt_chn_mjp_emp_chg)",
  "mt_chn_mjp_emp_chg1".update_user as "update_user (mt_chn_mjp_emp_chg1)",
  "mt_chn_mjp_emp_chg2".update_user as "update_user (mt_chn_mjp_emp_chg2)",
  "mt_chn_mjp_emp_chg3".update_user as "update_user (mt_chn_mjp_emp_chg3)",
  "mt_emp".update_user as "update_user (mt_emp)",
  "mt_emp1".update_user as "update_user (mt_emp1)",
  "mt_emp2".update_user as "update_user (mt_emp2)",
  "mt_emp3".update_user as "update_user (mt_emp3)",
  "mt_jan_detail".update_user as "update_user (mt_jan_detail)",
  "mt_prf".update_user as "update_user (mt_prf)",
  "mt_sgmt".update_user as "update_user (mt_sgmt)",
  "mt_sgmt1".update_user as "update_user (mt_sgmt1)",
  "mt_tp_status_mapping".update_user as "update_user (mt_tp_status_mapping)",
  CAST("edi_chn_m".update_user as TEXT) AS "update_user",
  CAST("edi_cstm_m1".updateflg as TEXT) AS "updateflg (edi_cstm_m1)",
  CAST("edi_cstm_m2".updateflg as TEXT) AS "updateflg (edi_cstm_m2)",
  "edi_item_m".updateflg as "updateflg (edi_item_m)",
  "edi_item_m1".updateflg as "updateflg (edi_item_m1)",
  CAST("edi_cstm_m".updateflg as TEXT) AS "updateflg",
  CAST("sdl_mds_jp_jan_description"."validationstatus" as TEXT) AS "validationstatus (sdl_mds_jp_jan_description)",
  CAST("sdl_mds_jp_product_ca_ratio".validationstatus as TEXT) AS "validationstatus",
  CAST("edi_item_m1".variant as TEXT) AS "variant (edi_item_m1)",
  CAST("edi_item_m".variant as TEXT) AS "variant",
  "sdl_mds_jp_jan_description"."version_id" as "version_id (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".version_id as "version_id",
  "sdl_mds_jp_jan_description"."versionflag" as "versionflag (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".versionflag as "versionflag",
  "sdl_mds_jp_jan_description"."versionname" as "versionname (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".versionname as "versionname",
  "sdl_mds_jp_jan_description"."versionnumber" as "versionnumber (sdl_mds_jp_jan_description)",
  "sdl_mds_jp_product_ca_ratio".versionnumber as "versionnumber",
  "mt_cld1".week as "week (mt_cld1)",
  "mt_cld".week as "week",
  "mt_cld1".week_ms as "week_ms (mt_cld1)",
  "mt_cld".week_ms as "week_ms",
  "mt_cld1".week_ss as "week_ss (mt_cld1)",
  "mt_cld".week_ss as "week_ss",
  "mt_emp1".wwid as "wwid (mt_emp1)",
  "mt_emp2".wwid as "wwid (mt_emp2)",
  "mt_emp3".wwid as "wwid (mt_emp3)",
  "mt_emp".wwid as "wwid",
  "mt_cld1".year as "year (mt_cld1)",
  "mt_cld".year as "year",
  "mt_cld1".year_15 as "year_15 (mt_cld1)",
  "mt_cld".year_15 as "year_15",
  "mt_cld1".year_20 as "year_20 (mt_cld1)",
  "mt_cld".year_20 as "year_20",
  "mt_cld1".year_445 as "year_445 (mt_cld1)",
  "mt_cld".year_445 as "year_445",
  "mt_cld1".ymd_dt as "ymd_dt (mt_cld1)",
  "mt_cld".ymd_dt as "ymd_dt",
  "mt_cld1".ymonth_15 as "ymonth_15 (mt_cld1)",
  "mt_cld".ymonth_15 as "ymonth_15",
  "mt_cld1".ymonth_20 as "ymonth_20 (mt_cld1)",
  "mt_cld".ymonth_20 as "ymonth_20",
  "mt_cld1".ymonth_445 as "ymonth_445 (mt_cld1)",
  "mt_cld".ymonth_445 as "ymonth_445"
  FROM dm_integration_dly  "dm_integration_dly"
  LEFT JOIN edi_chn_m "edi_chn_m" ON ("dm_integration_dly".jcp_chn_offc_cd = CAST("edi_chn_m".chn_cd AS TEXT))
  LEFT JOIN mt_sgmt "mt_sgmt" ON ("edi_chn_m".sgmt = "mt_sgmt".sgmt)
  LEFT JOIN edi_chn_m "edi_chn_m1" ON ("dm_integration_dly".jcp_chn_cd = CAST("edi_chn_m1".chn_cd AS TEXT))
  LEFT JOIN mt_sgmt "mt_sgmt1" ON ("edi_chn_m1".sgmt = "mt_sgmt1".sgmt)
  LEFT JOIN edi_cstm_m "edi_cstm_m" ON ("dm_integration_dly".jcp_cstm_cd = CAST("edi_cstm_m".cstm_cd AS TEXT))
  LEFT JOIN edi_cstm_m "edi_cstm_m1" ON ("edi_cstm_m".rebate_rep_cd = CAST("edi_cstm_m1".cstm_cd AS TEXT))
  LEFT JOIN edi_store_m "edi_store_m" ON ("dm_integration_dly".jcp_str_cd = CAST("edi_store_m".str_cd AS TEXT))
  LEFT JOIN mt_prf "mt_prf" ON ("edi_store_m".jis_prfct_c = "mt_prf".prf_cd)
  INNER JOIN mt_account_key "mt_account_key" ON ("dm_integration_dly".jcp_account = "mt_account_key".accounting_code)
  INNER JOIN mt_cld "mt_cld" ON ("dm_integration_dly".jcp_date = "mt_cld".ymd_dt)
  LEFT JOIN mt_jan_detail "mt_jan_detail" ON ("dm_integration_dly".jcp_jan_cd = "mt_jan_detail".jan_cd)
  LEFT JOIN vw_jan_change "vw_jan_change" ON ("dm_integration_dly".jcp_jan_cd = CAST("vw_jan_change".jan_cd AS TEXT))
  LEFT JOIN edi_item_m "edi_item_m" ON ("vw_jan_change".item_cd = CAST("edi_item_m".item_cd AS TEXT))
  LEFT JOIN vw_m_item_frnch_cdd "vw_m_item_frnch_cdd" ON ("vw_jan_change".item_cd = "vw_m_item_frnch_cdd".item_cd)
  LEFT JOIN mt_chn_mjp_emp_chg "mt_chn_mjp_emp_chg2" ON (("dm_integration_dly".jcp_cstm_cd = CAST("mt_chn_mjp_emp_chg2".chn_cd AS TEXT)) AND ("vw_m_item_frnch_cdd".frnch_cd = CAST("mt_chn_mjp_emp_chg2".fc_cd AS TEXT)))
  LEFT JOIN mt_emp "mt_emp2" ON ("mt_chn_mjp_emp_chg2".emp_cd = "mt_emp2".emp_cd)
  LEFT JOIN mt_chn_mjp_emp_chg "mt_chn_mjp_emp_chg1" ON (("dm_integration_dly".jcp_chn_cd = CAST("mt_chn_mjp_emp_chg1".chn_cd AS TEXT)) AND ("vw_m_item_frnch_cdd".frnch_cd = CAST("mt_chn_mjp_emp_chg1".fc_cd AS TEXT)))
  LEFT JOIN mt_emp "mt_emp1" ON ("mt_chn_mjp_emp_chg1".emp_cd = "mt_emp1".emp_cd)
  LEFT JOIN mt_chn_mjp_emp_chg "mt_chn_mjp_emp_chg" ON (("dm_integration_dly".jcp_chn_offc_cd = CAST("mt_chn_mjp_emp_chg".chn_cd AS TEXT)) AND ("vw_m_item_frnch_cdd".frnch_cd = CAST("mt_chn_mjp_emp_chg".fc_cd AS TEXT)))
  LEFT JOIN mt_emp "mt_emp" ON ("mt_chn_mjp_emp_chg".emp_cd = "mt_emp".emp_cd)
  LEFT JOIN mt_cld "mt_cld1" ON ("dm_integration_dly".tp_sap_cnt_dt = "mt_cld1".ymd_dt)
  LEFT JOIN mt_tp_status_mapping "mt_tp_status_mapping" ON (("dm_integration_dly".tp_approve_status_cd = "mt_tp_status_mapping".approve_status_cd) AND ("dm_integration_dly".tp_promo_status_cd = "mt_tp_status_mapping".promo_status_cd) AND ("dm_integration_dly".tp_rslt_status_cd = "mt_tp_status_mapping".rslt_status_cd) AND ("dm_integration_dly".tp_apl_direct_flg = "mt_tp_status_mapping".direct_flg) AND ("dm_integration_dly".jcp_data_category = "mt_tp_status_mapping".jcp_data_category))
  LEFT JOIN mt_chn_mjp_emp_chg "mt_chn_mjp_emp_chg3" ON (("edi_cstm_m1".rebate_rep_cd = CAST("mt_chn_mjp_emp_chg3".chn_cd AS TEXT)) AND ("vw_m_item_frnch_cdd".frnch_cd = CAST("mt_chn_mjp_emp_chg3".fc_cd AS TEXT)))
  LEFT JOIN mt_emp "mt_emp3" ON ("mt_chn_mjp_emp_chg3".emp_cd = "mt_emp3".emp_cd)
  LEFT JOIN (
  select min(cstm_nm_knj) as cstm_nm_knj , plnt_cd as plnt_cd from edi_cstm_m group by plnt_cd
) "x_e382abe382b9e382bfe383a0 sql e382afe382a8e383aa_" ON ("dm_integration_dly".so_ws_cd = CAST("x_e382abe382b9e382bfe383a0 sql e382afe382a8e383aa_".plnt_cd AS TEXT))
  LEFT JOIN (
  select min(cstm_nm_knj) as cstm_nm_knj , plnt_cd as plnt_cd from edi_cstm_m group by plnt_cd
) "x_e382abe382b9e382bfe383a0 sql e382afe382a8e383az1" ON ("dm_integration_dly".so_shp_ws_cd = CAST("x_e382abe382b9e382bfe383a0 sql e382afe382a8e383az1".plnt_cd AS TEXT))
  LEFT JOIN edi_cstm_m "edi_cstm_m2" ON ("dm_integration_dly".jcp_cstm_cd= CAST("edi_cstm_m2".cstm_cd AS TEXT))
  LEFT JOIN sdl_mds_jp_product_ca_ratio "sdl_mds_jp_product_ca_ratio" ON (("edi_cstm_m2".rebate_rep_cd = CAST("sdl_mds_jp_product_ca_ratio".rtl_ho_cd_code AS TEXT)) AND ("dm_integration_dly".jcp_jan_cd = "sdl_mds_jp_product_ca_ratio".item_cd))
  LEFT JOIN edi_item_m "edi_item_m1" ON ("dm_integration_dly".jcp_jan_cd = CAST("edi_item_m1".jan_cd_so AS TEXT))
  LEFT JOIN sdl_mds_jp_jan_description "sdl_mds_jp_jan_description" ON ("dm_integration_dly".jcp_jan_cd = CAST("sdl_mds_jp_jan_description"."code" AS TEXT))
)
select * from transformed