{{
    config(
        materialized = 'incremental',
        incremental_strategy ='append',
        pre_hook = "
        {% if is_incremental() %}
            DELETE FROM {{ this }} WHERE ORGANIZATION_KEY = 'Not Applicable';
        {% endif %}
            ",

        post_hook = " 
                    UPDATE {{ this }} SET FLAG = 'HT', EFFECTIVE_TO_DATE = dateadd(day, -1, current_timestamp())
                    WHERE (TERRITORY_SOURCE_ID,COUNTRY_CODE) IN (SELECT WRK.TERRITORY_SOURCE_ID,WRK.COUNTRY_CODE FROM {{ this }} WRK WHERE EFFECTIVE_FROM_DATE = to_date(current_timestamp()))
                    AND to_date(EFFECTIVE_FROM_DATE) < (
                    SELECT max(to_date(AA.EFFECTIVE_FROM_DATE)) EFFECTIVE_FROM_DATE
                    FROM {{ this }} AA)
                    AND EFFECTIVE_TO_DATE = to_date('12/31/2099', 'mm/dd/yyyy');
                    
                    UPDATE {{ this }} SET EFFECTIVE_FROM_DATE = '1900-01-01 00:00:00'
                    WHERE EFFECTIVE_FROM_DATE <> '1900-01-01 00:00:00'
                    AND MY_ORGANIZATION_CODE IN (
                    SELECT MY_ORGANIZATION_CODE
                    FROM {{ this }}
                    WHERE MY_ORGANIZATION_CODE <> 'Not Applicable'
                    GROUP BY 1
                    HAVING COUNT(MY_ORGANIZATION_CODE) = 1);
                    "

    )
}}

with wrk_dim_organization as (
    select * from {{ ref('hcposeedw_integration__wrk_dim_organization') }}
),

NEW_REC as (
    SELECT TERRITORY_SOURCE_ID,
    COUNTRY_CODE,
    MY_ORGANIZATION_CODE,
    MY_ORGANIZATION_NAME,
    ORGANIZATION_L1_CODE,
    ORGANIZATION_L1_NAME,
    ORGANIZATION_L2_CODE,
    ORGANIZATION_L2_NAME,
    nullif(ORGANIZATION_L3_CODE, '') ORGANIZATION_L3_CODE,
    nullif(ORGANIZATION_L3_NAME, '') ORGANIZATION_L3_NAME,
    nullif(ORGANIZATION_L4_CODE, '') ORGANIZATION_L4_CODE,
    nullif(ORGANIZATION_L4_NAME, '') ORGANIZATION_L4_NAME,
    nullif(ORGANIZATION_L5_CODE, '') ORGANIZATION_L5_CODE,
    nullif(ORGANIZATION_L5_NAME, '') ORGANIZATION_L5_NAME,
    nullif(ORGANIZATION_L6_CODE, '') ORGANIZATION_L6_CODE,
    nullif(ORGANIZATION_L6_NAME, '') ORGANIZATION_L6_NAME,
    nullif(ORGANIZATION_L7_CODE, '') ORGANIZATION_L7_CODE,
    nullif(ORGANIZATION_L7_NAME, '') ORGANIZATION_L7_NAME,
    nullif(ORGANIZATION_L8_CODE, '') ORGANIZATION_L8_CODE,
    nullif(ORGANIZATION_L8_NAME, '') ORGANIZATION_L8_NAME,
    nullif(ORGANIZATION_L9_CODE, '') ORGANIZATION_L9_CODE,
    nullif(ORGANIZATION_L9_NAME, '') ORGANIZATION_L9_NAME
  FROM wrk_dim_organization 

  MINUS

  SELECT TERRITORY_SOURCE_ID,
    COUNTRY_CODE,
    MY_ORGANIZATION_CODE,
    MY_ORGANIZATION_NAME,
    ORGANIZATION_L1_CODE,
    ORGANIZATION_L1_NAME,
    ORGANIZATION_L2_CODE,
    ORGANIZATION_L2_NAME,
    nullif(ORGANIZATION_L3_CODE, '') ORGANIZATION_L3_CODE,
    nullif(ORGANIZATION_L3_NAME, '') ORGANIZATION_L3_NAME,
    nullif(ORGANIZATION_L4_CODE, '') ORGANIZATION_L4_CODE,
    nullif(ORGANIZATION_L4_NAME, '') ORGANIZATION_L4_NAME,
    nullif(ORGANIZATION_L5_CODE, '') ORGANIZATION_L5_CODE,
    nullif(ORGANIZATION_L5_NAME, '') ORGANIZATION_L5_NAME,
    nullif(ORGANIZATION_L6_CODE, '') ORGANIZATION_L6_CODE,
    nullif(ORGANIZATION_L6_NAME, '') ORGANIZATION_L6_NAME,
    nullif(ORGANIZATION_L7_CODE, '') ORGANIZATION_L7_CODE,
    nullif(ORGANIZATION_L7_NAME, '') ORGANIZATION_L7_NAME,
    nullif(ORGANIZATION_L8_CODE, '') ORGANIZATION_L8_CODE,
    nullif(ORGANIZATION_L8_NAME, '') ORGANIZATION_L8_NAME,
    nullif(ORGANIZATION_L9_CODE, '') ORGANIZATION_L9_CODE,
    nullif(ORGANIZATION_L9_NAME, '') ORGANIZATION_L9_NAME
  FROM {{ this }}
),

cte1 as (
SELECT MD5(NEW_REC.TERRITORY_SOURCE_ID || NEW_REC.COUNTRY_CODE || current_timestamp()) AS ORGANIZATION_KEY,
  NEW_REC.TERRITORY_SOURCE_ID,
  NEW_REC.COUNTRY_CODE,
  NEW_REC.MY_ORGANIZATION_CODE,
  NEW_REC.MY_ORGANIZATION_NAME,
  NEW_REC.ORGANIZATION_L1_CODE,
  NEW_REC.ORGANIZATION_L1_NAME,
  NEW_REC.ORGANIZATION_L2_CODE,
  NEW_REC.ORGANIZATION_L2_NAME,
  NEW_REC.ORGANIZATION_L3_CODE,
  NEW_REC.ORGANIZATION_L3_NAME,
  NEW_REC.ORGANIZATION_L4_CODE,
  NEW_REC.ORGANIZATION_L4_NAME,
  NEW_REC.ORGANIZATION_L5_CODE,
  NEW_REC.ORGANIZATION_L5_NAME,
  NEW_REC.ORGANIZATION_L6_CODE,
  NEW_REC.ORGANIZATION_L6_NAME,
  NEW_REC.ORGANIZATION_L7_CODE,
  NEW_REC.ORGANIZATION_L7_NAME,
  NEW_REC.ORGANIZATION_L8_CODE,
  NEW_REC.ORGANIZATION_L8_NAME,
  NEW_REC.ORGANIZATION_L9_CODE,
  NEW_REC.ORGANIZATION_L9_NAME,
  current_timestamp() INSERTED_DATE,
  current_timestamp() UPDATED_DATE,
  current_timestamp() EFFECTIVE_FROM_DATE,
  to_date('12/31/2099', 'mm/dd/yyyy') EFFECTIVE_TO_DATE,
  'NW' AS FLAG
FROM NEW_REC
),

cte2 as (
SELECT 'Not Applicable',
  'Not Applicable',
  'ZZ',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  'Not Applicable',
  current_timestamp() INSERTED_DATE,
  current_timestamp() UPDATED_DATE,
  current_timestamp() EFFECTIVE_FROM_DATE,
  current_timestamp() EFFECTIVE_TO_DATE,
  'Not Applicable'
  ),

result as (
    select * from cte1
    union all
    select * from cte2
),

final as (
    select
    ORGANIZATION_KEY::VARCHAR(32) as ORGANIZATION_KEY,
	TERRITORY_SOURCE_ID::VARCHAR(18) as TERRITORY_SOURCE_ID,
	COUNTRY_CODE::VARCHAR(8) as COUNTRY_CODE,
	MY_ORGANIZATION_CODE::VARCHAR(18) as MY_ORGANIZATION_CODE,
	MY_ORGANIZATION_NAME::VARCHAR(80) as MY_ORGANIZATION_NAME,
	ORGANIZATION_L1_CODE::VARCHAR(18) as ORGANIZATION_L1_CODE,
	ORGANIZATION_L1_NAME::VARCHAR(80) as ORGANIZATION_L1_NAME,
	ORGANIZATION_L2_CODE::VARCHAR(18) as ORGANIZATION_L2_CODE,
	ORGANIZATION_L2_NAME::VARCHAR(80) as ORGANIZATION_L2_NAME,
	ORGANIZATION_L3_CODE::VARCHAR(18) as ORGANIZATION_L3_CODE,
	ORGANIZATION_L3_NAME::VARCHAR(80) as ORGANIZATION_L3_NAME,
	ORGANIZATION_L4_CODE::VARCHAR(18) as ORGANIZATION_L4_CODE,
	ORGANIZATION_L4_NAME::VARCHAR(80) as ORGANIZATION_L4_NAME,
	ORGANIZATION_L5_CODE::VARCHAR(18) as ORGANIZATION_L5_CODE,
	ORGANIZATION_L5_NAME::VARCHAR(80) as ORGANIZATION_L5_NAME,
	ORGANIZATION_L6_CODE::VARCHAR(18) as ORGANIZATION_L6_CODE,
	ORGANIZATION_L6_NAME::VARCHAR(80) as ORGANIZATION_L6_NAME,
	ORGANIZATION_L7_CODE::VARCHAR(18) as ORGANIZATION_L7_CODE,
	ORGANIZATION_L7_NAME::VARCHAR(80) as ORGANIZATION_L7_NAME,
	ORGANIZATION_L8_CODE::VARCHAR(18) as ORGANIZATION_L8_CODE,
	ORGANIZATION_L8_NAME::VARCHAR(80) as ORGANIZATION_L8_NAME,
	ORGANIZATION_L9_CODE::VARCHAR(18) as ORGANIZATION_L9_CODE,
	ORGANIZATION_L9_NAME::VARCHAR(80) as ORGANIZATION_L9_NAME,
	EFFECTIVE_FROM_DATE::DATE as EFFECTIVE_FROM_DATE,
	EFFECTIVE_TO_DATE::DATE as EFFECTIVE_TO_DATE,
	FLAG::VARCHAR(18) as FLAG,
	current_timestamp()::TIMESTAMP_NTZ(9) as INSERTED_DATE,
	current_timestamp()::TIMESTAMP_NTZ(9) as UPDATED_DATE
    from result
)

select * from final