with itg_tblpf_secsalesm as 
(
    select * from {{ ref('inditg_integration__itg_tblpf_secsalesm') }}
),
trans as 
(

    SELECT 
       runmm as month,
       runyr as year,
       DistCode as customer_code,
       PrdCode as product_code,
       SUM(CASE WHEN src <> 'SR' AND mon = runmm AND yr = runyr THEN PrdQty ELSE 0 END) AS Sec_Prd_Qty,
       SUM(CASE WHEN src <> 'SR' AND mon = runmm AND yr = runyr THEN PtrValue ELSE 0 END) AS Sec_PTR_Value,
       SUM(CASE WHEN src <> 'SR' AND mon = runmm AND yr = runyr THEN PrdNrValue ELSE 0 END) AS Sec_Prd_NR_Value,
       SUM(CASE WHEN src <> 'SR' AND mon = runmm AND yr = runyr THEN LPvalue ELSE 0 END) AS Sec_LP_value,
       SUM(CASE WHEN src = 'SR' AND mon = runmm AND yr = runyr THEN PrdQty ELSE 0 END) AS Sec_Prd_Qty_Ret,
       SUM(CASE WHEN src = 'SR' AND mon = runmm AND yr = runyr THEN PtrValue ELSE 0 END) AS Sec_Ptr_Value_Ret,
       SUM(CASE WHEN src = 'SR' AND mon = runmm AND yr = runyr THEN PrdNrValue ELSE 0 END) AS Sec_Prd_NR_Value_Ret,
       SUM(CASE WHEN src = 'SR' AND mon = runmm AND yr = runyr THEN LPvalue ELSE 0 END) AS Sec_LP_value_Ret,
       SUM(CASE WHEN src <> 'SR' AND mon = runmm AND yr = runyr THEN TrInQty ELSE 0 END) AS Sec_Tr_In_Qty,
       SUM(CASE WHEN src <> 'SR' AND mon = runmm AND yr = runyr THEN trOutQty ELSE 0 END) AS Sec_Tr_Out_Qty,
       SUM(CASE WHEN src <> 'SR' AND mon = runmm AND yr = runyr THEN trInVal ELSE 0 END) AS Sec_Tr_In_Val,
       SUM(CASE WHEN src <> 'SR' AND mon = runmm AND yr = runyr THEN trOutVal ELSE 0 END) AS Sec_Tr_Out_Val,
       SUM(NonWaveOpenQty) AS Sec_Non_Wave_Open_Qty,
       SUM(CASE WHEN src <> 'SR' AND mon = runmm AND yr = runyr THEN prdGrossAmt ELSE 0 END) AS Sec_Gross_Amt,
       SUM(CASE WHEN src = 'SR' AND mon = runmm AND yr = runyr THEN prdGrossAmt ELSE 0 END) AS Sec_Gross_Amt_Ret,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN PrdQty ELSE 0 END) AS Sec_Late_Prd_Qty,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN PtrValue ELSE 0 END) AS Sec_Late_PTR_Value,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN PrdNrValue ELSE 0 END) AS Sec_Late_Prd_NR_Value,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN LPvalue ELSE 0 END) AS Sec_Late_LP_value,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN PrdQty ELSE 0 END) AS Sec_Late_Prd_Qty_Ret,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN PtrValue ELSE 0 END) AS Sec_Late_Ptr_Value_Ret,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN PrdNrValue ELSE 0 END) AS Sec_Late_Prd_NR_Value_Ret,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN LPvalue ELSE 0 END) AS Sec_Late_LP_value_Ret,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN trInQty ELSE 0 END) AS Sec_Late_Tr_In_Qty,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN trOutQty ELSE 0 END) AS Sec_Late_Tr_Out_Qty,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN trInVal ELSE 0 END) AS Sec_Late_Tr_In_Val,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN trOutVal ELSE 0 END) AS Sec_Late_Tr_Out_Val,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN NonWaveOpenQty ELSE 0 END) AS Sec_Late_Non_Wave_Open_Qty,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN prdGrossAmt ELSE 0 END) AS Sec_Late_Gross_Amt,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN prdGrossAmt ELSE 0 END) AS Sec_Late_Gross_Amt_Ret,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PrdQty_prev ELSE 0 END) AS dbrestore_Sec_Late_Prd_Qty_prev,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PtrValue_prev ELSE 0 END) AS dbrestore_Sec_Late_PTR_Value_prev,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PrdNrValue_prev ELSE 0 END) AS dbrestore_Sec_Late_Prd_NR_Value_prev,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PrdQty_prev ELSE 0 END) AS dbrestore_Sec_Late_Prd_Qty_Ret_prev,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PtrValue_prev ELSE 0 END) AS dbrestore_Sec_Late_Ptr_Value_Ret_prev,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PrdNrValue_prev ELSE 0 END) AS dbrestore_Sec_Late_Prd_NR_Value_Ret_prev,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_prdGrossAmt_prev ELSE 0 END) AS dbrestore_Sec_Late_Gross_Amt_prev,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_prdGrossAmt_prev ELSE 0 END) AS dbrestore_Sec_Late_Gross_Amt_Ret_prev,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PrdQty_current ELSE 0 END) AS dbrestore_Sec_Late_Prd_Qty_current,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PtrValue_current ELSE 0 END) AS dbrestore_Sec_Late_PTR_Value_current,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PrdNrValue_current ELSE 0 END) AS dbrestore_Sec_Late_Prd_NR_Value_current,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PrdQty_current ELSE 0 END) AS dbrestore_Sec_Late_Prd_Qty_Ret_current,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PtrValue_current ELSE 0 END) AS dbrestore_Sec_Late_Ptr_Value_Ret_current,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_PrdNrValue_current ELSE 0 END) AS dbrestore_Sec_Late_Prd_NR_Value_Ret_current,
       SUM(CASE WHEN src <> 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_prdGrossAmt_current ELSE 0 END) AS dbrestore_Sec_Late_Gross_Amt_current,
       SUM(CASE WHEN src = 'SR' AND CAST(yr||lpad (mon,2,'0') AS INTEGER) < CAST(runyr||lpad (runmm,2,'0') AS INTEGER) THEN dbrestore_prdGrossAmt_current ELSE 0 END) AS dbrestore_Sec_Late_Gross_Amt_Ret_current,
       current_timestamp() as crt_dttm,
       current_timestamp() as updt_dttm
FROM itg_tblpf_secsalesm
GROUP BY runmm,
         runyr,
         DistCode,
         PrdCode),
final as 
(
    select 
	month::number(18,0) as month,
	year::number(18,0) as year,
	customer_code::varchar(50) as customer_code,
	product_code::varchar(50) as product_code,
	sec_prd_qty::number(16,4) as sec_prd_qty,
	sec_ptr_value::number(16,4) as sec_ptr_value,
	sec_prd_nr_value::number(18,3) as sec_prd_nr_value,
	sec_lp_value::number(18,3) as sec_lp_value,
	sec_prd_qty_ret::number(16,4) as sec_prd_qty_ret,
	sec_ptr_value_ret::number(16,4) as sec_ptr_value_ret,
	sec_prd_nr_value_ret::number(18,3) as sec_prd_nr_value_ret,
	sec_lp_value_ret::number(18,3) as sec_lp_value_ret,
	sec_tr_in_qty::number(16,3) as sec_tr_in_qty,
	sec_tr_out_qty::number(16,3) as sec_tr_out_qty,
	sec_tr_in_val::number(16,3) as sec_tr_in_val,
	sec_tr_out_val::number(16,3) as sec_tr_out_val,
	sec_non_wave_open_qty::number(16,3) as sec_non_wave_open_qty,
	sec_gross_amt::number(16,4) as sec_gross_amt,
	sec_gross_amt_ret::number(16,4) as sec_gross_amt_ret,
	sec_late_prd_qty::number(16,4) as sec_late_prd_qty,
	sec_late_ptr_value::number(16,4) as sec_late_ptr_value,
	sec_late_prd_nr_value::number(18,3) as sec_late_prd_nr_value,
	sec_late_lp_value::number(18,3) as sec_late_lp_value,
	sec_late_prd_qty_ret::number(16,4) as sec_late_prd_qty_ret,
	sec_late_ptr_value_ret::number(16,4) as sec_late_ptr_value_ret,
	sec_late_prd_nr_value_ret::number(18,3) as sec_late_prd_nr_value_ret,
	sec_late_lp_value_ret::number(18,3) as sec_late_lp_value_ret,
	sec_late_tr_in_qty::number(16,3) as sec_late_tr_in_qty,
	sec_late_tr_out_qty::number(16,3) as sec_late_tr_out_qty,
	sec_late_tr_in_val::number(16,3) as sec_late_tr_in_val,
	sec_late_tr_out_val::number(16,3) as sec_late_tr_out_val,
	sec_late_non_wave_open_qty::number(16,3) as sec_late_non_wave_open_qty,
	sec_late_gross_amt::number(16,4) as sec_late_gross_amt,
	sec_late_gross_amt_ret::number(16,4) as sec_late_gross_amt_ret,
	dbrestore_sec_late_prd_qty_prev::number(16,4) as dbrestore_sec_late_prd_qty_prev,
	dbrestore_sec_late_ptr_value_prev::number(16,4) as dbrestore_sec_late_ptr_value_prev,
	dbrestore_sec_late_prd_nr_value_prev::number(18,3) as dbrestore_sec_late_prd_nr_value_prev,
	dbrestore_sec_late_prd_qty_ret_prev::number(16,4) as dbrestore_sec_late_prd_qty_ret_prev,
	dbrestore_sec_late_ptr_value_ret_prev::number(16,4) as dbrestore_sec_late_ptr_value_ret_prev,
	dbrestore_sec_late_prd_nr_value_ret_prev::number(18,3) as dbrestore_sec_late_prd_nr_value_ret_prev,
	dbrestore_sec_late_gross_amt_prev::number(16,4) as dbrestore_sec_late_gross_amt_prev,
	dbrestore_sec_late_gross_amt_ret_prev::number(16,4) as dbrestore_sec_late_gross_amt_ret_prev,
	dbrestore_sec_late_prd_qty_current::number(16,4) as dbrestore_sec_late_prd_qty_current,
	dbrestore_sec_late_ptr_value_current::number(16,4) as dbrestore_sec_late_ptr_value_current,
	dbrestore_sec_late_prd_nr_value_current::number(18,3) as dbrestore_sec_late_prd_nr_value_current,
	dbrestore_sec_late_prd_qty_ret_current::number(16,4) as dbrestore_sec_late_prd_qty_ret_current,
	dbrestore_sec_late_ptr_value_ret_current::number(16,4) as dbrestore_sec_late_ptr_value_ret_current,
	dbrestore_sec_late_prd_nr_value_ret_current::number(18,3) as dbrestore_sec_late_prd_nr_value_ret_current,
	dbrestore_sec_late_gross_amt_current::number(16,4) as dbrestore_sec_late_gross_amt_current,
	dbrestore_sec_late_gross_amt_ret_current::number(16,4) as dbrestore_sec_late_gross_amt_ret_current,
	crt_dttm::timestamp_ntz(9) as crt_dttm,
	updt_dttm::timestamp_ntz(9) as updt_dttm
    from trans
)
select * from final