--import cte     
with wks_my_rpt_re_gcph as (
    select * from {{ ref('myswks_integration__wks_my_rpt_re_gcph') }}
),
retail_excellence_msl_target_final as 
 (
    select * from {{ ref('myswks_integration__wks_retail_excellence_msl_target_final') }}
 ),

--final cte
edw_rpt_my_re  as (
SELECT jj_year AS FISC_YR,
       gcph.jj_mnth_id AS FISC_PER,
       "cluster",
       gcph.MARKET as market,
       data_src,
       CHANNEL_NAME,
       soldto_code,
       DISTRIBUTOR_CODE,
       DISTRIBUTOR_NAME,
       SELL_OUT_CHANNEL,
       STORE_TYPE,
       PRIORITIZATION_SEGMENTATION,
       STORE_CATEGORY,
       STORE_CODE,
       STORE_NAME,
       STORE_GRADE,
       STORE_SIZE,
       REGION,
       --STORE_ADDRESS,
       --POST_CODE,
       ZONE_NAME,
       CITY,
       RTRLATITUDE,
       RTRLONGITUDE,
       CUSTOMER_SEGMENT_KEY,
       CUSTOMER_SEGMENT_DESCRIPTION,
       RETAIL_ENVIRONMENT,
       SAP_CUSTOMER_CHANNEL_KEY,
       SAP_CUSTOMER_CHANNEL_DESCRIPTION,
       SAP_CUSTOMER_SUB_CHANNEL_KEY,
       SAP_SUB_CHANNEL_DESCRIPTION,
       SAP_PARENT_CUSTOMER_KEY,
       SAP_PARENT_CUSTOMER_DESCRIPTION,
       SAP_BANNER_KEY,
       SAP_BANNER_DESCRIPTION,
       SAP_BANNER_FORMAT_KEY,
       SAP_BANNER_FORMAT_DESCRIPTION,
       CUSTOMER_NAME,
       CUSTOMER_CODE,
       PRODUCT_CODE,
       PRODUCT_NAME,
       PROD_HIER_L1,
       PROD_HIER_L2,
       PROD_HIER_L3,
       PROD_HIER_L4,
       PROD_HIER_L5,
       PROD_HIER_L6,
       PROD_HIER_L7,
       PROD_HIER_L8,
       PROD_HIER_L9,
       MAPPED_SKU_CD,
       SAP_PROD_SGMT_CD,
       SAP_PROD_SGMT_DESC,
       --null as  SAP_BASE_PROD_CD,
       SAP_BASE_PROD_DESC,
       --null as SAP_MEGA_BRND_CD,
       SAP_MEGA_BRND_DESC,
       --null as SAP_BRND_CD,
       SAP_BRND_DESC,
       --null as SAP_VRNT_CD,
       SAP_VRNT_DESC,
       --null as SAP_PUT_UP_CD,
       SAP_PUT_UP_DESC,
       SAP_GRP_FRNCHSE_CD,
       SAP_GRP_FRNCHSE_DESC,
       SAP_FRNCHSE_CD,
       SAP_FRNCHSE_DESC,
       SAP_PROD_FRNCHSE_CD,
       SAP_PROD_FRNCHSE_DESC,
       SAP_PROD_MJR_CD,
       SAP_PROD_MJR_DESC,
       SAP_PROD_MNR_CD,
       SAP_PROD_MNR_DESC,
       SAP_PROD_HIER_CD,
       SAP_PROD_HIER_DESC,
       --null as PKA_FRANCHISE_CD, 
       PKA_FRANCHISE_DESC,
       -- null as PKA_BRAND_CD, 
       PKA_BRAND_DESC,
       --null as PKA_SUB_BRAND_CD, 
       PKA_SUB_BRAND_DESC,
       --null as PKA_VARIANT_CD, 
       PKA_VARIANT_DESC,
       --null as PKA_SUB_VARIANT_CD, 
       PKA_SUB_VARIANT_DESC,
       GLOBAL_PRODUCT_FRANCHISE,
       gcph.GLOBAL_PRODUCT_BRAND,
       GLOBAL_PRODUCT_SUB_BRAND,
       GLOBAL_PRODUCT_VARIANT,
       GLOBAL_PRODUCT_SEGMENT,
       GLOBAL_PRODUCT_SUBSEGMENT,
       GLOBAL_PRODUCT_CATEGORY,
       GLOBAL_PRODUCT_SUBCATEGORY,
       GLOBAL_PUT_UP_DESCRIPTION,
       product_code AS EAN,
       product_code AS SKU_CODE,
       product_name AS SKU_DESCRIPTION,
       --null as GREENLIGHT_SKU_FLAG,
       PKA_PRODUCT_KEY,
       PKA_PRODUCT_KEY_DESCRIPTION,
       SALES_VALUE,
       SALES_QTY,
       AVG_SALES_QTY,
       SALES_VALUE_LIST_PRICE,
       LM_SALES,
       LM_SALES_QTY,
       LM_AVG_SALES_QTY,
       LM_SALES_LP,
       P3M_SALES,
       P3M_QTY,
       P3M_AVG_QTY,
       P3M_SALES_LP,
       P6M_SALES,
       P6M_QTY,
       P6M_AVG_QTY,
       P6M_SALES_LP,
       P12M_SALES,
       P12M_QTY,
       P12M_AVG_QTY,
       P12M_SALES_LP,
       F3M_SALES,
       F3M_QTY,
       F3M_AVG_QTY,
       LM_SALES_FLAG,
       P3M_SALES_FLAG,
       P6M_SALES_FLAG,
       P12M_SALES_FLAG,
       MDP_FLAG,
       case when mdp_flag='Y' and gcph.global_product_brand=target.global_product_brand then target.TARGET_COMPLAINCE else 100 end as TARGET_COMPLAINCE,
       LIST_PRICE,
       TOTAL_SALES_LM,
       TOTAL_SALES_P3M,
       TOTAL_SALES_P6M,
       TOTAL_SALES_P12M,
       TOTAL_SALES_BY_STORE_LM,
       TOTAL_SALES_BY_STORE_P3M,
       TOTAL_SALES_BY_STORE_P6M,
       TOTAL_SALES_BY_STORE_P12M,
       TOTAL_SALES_BY_SKU_LM,
       TOTAL_SALES_BY_SKU_P3M,
       TOTAL_SALES_BY_SKU_P6M,
       TOTAL_SALES_BY_SKU_P12M,
       STORE_CONTRIBUTION_LM,
       SKU_CONTRIBUTION_LM,
       SIZE_OF_PRICE_LM,
       STORE_CONTRIBUTION_P3M,
       SKU_CONTRIBUTION_P3M,
       SIZE_OF_PRICE_P3M,
       STORE_CONTRIBUTION_P6M,
       SKU_CONTRIBUTION_P6M,
       SIZE_OF_PRICE_P6M,
       STORE_CONTRIBUTION_P12M,
       SKU_CONTRIBUTION_P12M,
       SIZE_OF_PRICE_P12M,
       TOTAL_SALES_LM_LP,
       TOTAL_SALES_P3M_LP,
       TOTAL_SALES_P6M_LP,
       TOTAL_SALES_P12M_LP,
       TOTAL_SALES_BY_STORE_LM_LP,
       TOTAL_SALES_BY_STORE_P3M_LP,
       TOTAL_SALES_BY_STORE_P6M_LP,
       TOTAL_SALES_BY_STORE_P12M_LP,
       TOTAL_SALES_BY_SKU_LM_LP,
       TOTAL_SALES_BY_SKU_P3M_LP,
       TOTAL_SALES_BY_SKU_P6M_LP,
       TOTAL_SALES_BY_SKU_P12M_LP,
       STORE_CONTRIBUTION_LM_LP,
       SKU_CONTRIBUTION_LM_LP,
       SIZE_OF_PRICE_LM_LP,
       STORE_CONTRIBUTION_P3M_LP,
       SKU_CONTRIBUTION_P3M_LP,
       SIZE_OF_PRICE_P3M_LP,
       STORE_CONTRIBUTION_P6M_LP,
       SKU_CONTRIBUTION_P6M_LP,
       SIZE_OF_PRICE_P6M_LP,
       STORE_CONTRIBUTION_P12M_LP,
       SKU_CONTRIBUTION_P12M_LP,
       SIZE_OF_PRICE_P12M_LP,
       COUNT(LM_SALES_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,LM_SALES_FLAG,MDP_FLAG) AS lM_SALES_FLAG_COUNT,
       COUNT(P3M_SALES_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,P3M_SALES_FLAG,MDP_FLAG) AS P3M_SALES_FLAG_COUNT,
       COUNT(P6M_SALES_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,P6M_SALES_FLAG,MDP_FLAG) AS P6M_SALES_FLAG_COUNT,
       COUNT(P12M_SALES_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,P12M_SALES_FLAG,MDP_FLAG) AS P12M_SALES_FLAG_COUNT,
       COUNT(MDP_FLAG) OVER (PARTITION BY CUSTOMER_AGG_DIM_KEY,PRODUCT_AGG_DIM_KEY,MDP_FLAG) AS MDP_FLAG_COUNT,
       SYSDATE() AS CRT_DTTM 
FROM WKS_MY_RPT_RE_GCPH gcph	
left join retail_excellence_msl_target_final  target on (gcph.jj_mnth_id=target.jj_mnth_id and gcph.global_product_brand=target.global_product_brand)
),
final as
(
    select 
fisc_yr::numeric(18,0) AS fisc_yr,
fisc_per::varchar(22) AS fisc_per,
"cluster"::varchar(100) AS "cluster",
market::varchar(50) AS market,
data_src::varchar(10) AS data_src,
channel_name::varchar(100) AS channel_name,
soldto_code::varchar(255) AS soldto_code,
distributor_code::varchar(150) AS distributor_code,
distributor_name::varchar(534) AS distributor_name,
sell_out_channel::varchar(100) AS sell_out_channel,
store_type::varchar(382) AS store_type,
prioritization_segmentation::varchar(13) AS prioritization_segmentation,
store_category::varchar(13) AS store_category,
store_code::varchar(150) AS store_code,
store_name::varchar(901) AS store_name,
store_grade::varchar(13) AS store_grade,
store_size::varchar(13) AS store_size,
region::varchar(150) AS region,
zone_name::varchar(150) AS zone_name,
city::varchar(11) AS city,
rtrlatitude::varchar(13) AS rtrlatitude,
rtrlongitude::varchar(13) AS rtrlongitude,
customer_segment_key::varchar(12) AS customer_segment_key,
customer_segment_description::varchar(50) AS customer_segment_description,
retail_environment::varchar(255) AS retail_environment,
sap_customer_channel_key::varchar(30) AS sap_customer_channel_key,
sap_customer_channel_description::varchar(75) AS sap_customer_channel_description,
sap_customer_sub_channel_key::varchar(12) AS sap_customer_sub_channel_key,
sap_sub_channel_description::varchar(75) AS sap_sub_channel_description,
sap_parent_customer_key::varchar(12) AS sap_parent_customer_key,
sap_parent_customer_description::varchar(75) AS sap_parent_customer_description,
sap_banner_key::varchar(12) AS sap_banner_key,
sap_banner_description::varchar(75) AS sap_banner_description,
sap_banner_format_key::varchar(12) AS sap_banner_format_key,
sap_banner_format_description::varchar(75) AS sap_banner_format_description,
customer_name::varchar(100) AS customer_name,
customer_code::varchar(10) AS customer_code,
product_code::varchar(150) AS product_code,
product_name::varchar(150) AS product_name,
prod_hier_l1::varchar(200) AS prod_hier_l1,
prod_hier_l2::varchar(200) AS prod_hier_l2,
prod_hier_l3::varchar(200) AS prod_hier_l3,
prod_hier_l4::varchar(200) AS prod_hier_l4,
prod_hier_l5::varchar(200) AS prod_hier_l5,
prod_hier_l6::varchar(200) AS prod_hier_l6,
prod_hier_l7::varchar(200) AS prod_hier_l7,
prod_hier_l8::varchar(200) AS prod_hier_l8,
prod_hier_l9::varchar(200) AS prod_hier_l9,
mapped_sku_cd::varchar(40) AS mapped_sku_cd,
sap_prod_sgmt_cd::varchar(18) AS sap_prod_sgmt_cd,
sap_prod_sgmt_desc::varchar(100) AS sap_prod_sgmt_desc,
sap_base_prod_desc::varchar(100) AS sap_base_prod_desc,
sap_mega_brnd_desc::varchar(100) AS sap_mega_brnd_desc,
sap_brnd_desc::varchar(100) AS sap_brnd_desc,
sap_vrnt_desc::varchar(100) AS sap_vrnt_desc,
sap_put_up_desc::varchar(100) AS sap_put_up_desc,
sap_grp_frnchse_cd::varchar(18) AS sap_grp_frnchse_cd,
sap_grp_frnchse_desc::varchar(100) AS sap_grp_frnchse_desc,
sap_frnchse_cd::varchar(18) AS sap_frnchse_cd,
sap_frnchse_desc::varchar(100) AS sap_frnchse_desc,
sap_prod_frnchse_cd::varchar(18) AS sap_prod_frnchse_cd,
sap_prod_frnchse_desc::varchar(100) AS sap_prod_frnchse_desc,
sap_prod_mjr_cd::varchar(18) AS sap_prod_mjr_cd,
sap_prod_mjr_desc::varchar(100) AS sap_prod_mjr_desc,
sap_prod_mnr_cd::varchar(18) AS sap_prod_mnr_cd,
sap_prod_mnr_desc::varchar(100) AS sap_prod_mnr_desc,
sap_prod_hier_cd::varchar(18) AS sap_prod_hier_cd,
sap_prod_hier_desc::varchar(100) AS sap_prod_hier_desc,
pka_franchise_desc::varchar(30) AS pka_franchise_desc,
pka_brand_desc::varchar(30) AS pka_brand_desc,
pka_sub_brand_desc::varchar(30) AS pka_sub_brand_desc,
pka_variant_desc::varchar(30) AS pka_variant_desc,
pka_sub_variant_desc::varchar(30) AS pka_sub_variant_desc,
global_product_franchise::varchar(30) AS global_product_franchise,
global_product_brand::varchar(30) AS global_product_brand,
global_product_sub_brand::varchar(100) AS global_product_sub_brand,
global_product_variant::varchar(100) AS global_product_variant,
global_product_segment::varchar(50) AS global_product_segment,
global_product_subsegment::varchar(100) AS global_product_subsegment,
global_product_category::varchar(50) AS global_product_category,
global_product_subcategory::varchar(50) AS global_product_subcategory,
global_put_up_description::varchar(100) AS global_put_up_description,
ean::varchar(40) AS ean,
sku_code::varchar(40) AS sku_code,
sku_description::varchar(200) AS sku_description,
pka_product_key::varchar(68) AS pka_product_key,
pka_product_key_description::varchar(255) AS pka_product_key_description,
sales_value::numeric(38,6) AS sales_value,
sales_qty::numeric(38,6) AS sales_qty,
avg_sales_qty::numeric(38,6) AS avg_sales_qty,
sales_value_list_price::numeric(38,12) AS sales_value_list_price,
lm_sales::numeric(38,6) AS lm_sales,
lm_sales_qty::numeric(38,6) AS lm_sales_qty,
lm_avg_sales_qty::numeric(38,6) AS lm_avg_sales_qty,
lm_sales_lp::numeric(38,12) AS lm_sales_lp,
p3m_sales::numeric(38,6) AS p3m_sales,
p3m_qty::numeric(38,6) AS p3m_qty,
p3m_avg_qty::numeric(38,6) AS p3m_avg_qty,
p3m_sales_lp::numeric(38,12) AS p3m_sales_lp,
p6m_sales::numeric(38,6) AS p6m_sales,
p6m_qty::numeric(38,6) AS p6m_qty,
p6m_avg_qty::numeric(38,6) AS p6m_avg_qty,
p6m_sales_lp::numeric(38,12) AS p6m_sales_lp,
p12m_sales::numeric(38,6) AS p12m_sales,
p12m_qty::numeric(38,6) AS p12m_qty,
p12m_avg_qty::numeric(38,6) AS p12m_avg_qty,
p12m_sales_lp::numeric(38,12) AS p12m_sales_lp,
f3m_sales::numeric(38,6) AS f3m_sales,
f3m_qty::numeric(38,6) AS f3m_qty,
f3m_avg_qty::numeric(38,6) AS f3m_avg_qty,
lm_sales_flag::varchar(1) AS lm_sales_flag,
p3m_sales_flag::varchar(1) AS p3m_sales_flag,
p6m_sales_flag::varchar(1) AS p6m_sales_flag,
p12m_sales_flag::varchar(1) AS p12m_sales_flag,
mdp_flag::varchar(1) AS mdp_flag,
target_complaince::integer AS target_complaince,
list_price::numeric(20,4) AS list_price,
total_sales_lm::numeric(38,6) AS total_sales_lm,
total_sales_p3m::numeric(38,6) AS total_sales_p3m,
total_sales_p6m::numeric(38,6) AS total_sales_p6m,
total_sales_p12m::numeric(38,6) AS total_sales_p12m,
total_sales_by_store_lm::numeric(38,6) AS total_sales_by_store_lm,
total_sales_by_store_p3m::numeric(38,6) AS total_sales_by_store_p3m,
total_sales_by_store_p6m::numeric(38,6) AS total_sales_by_store_p6m,
total_sales_by_store_p12m::numeric(38,6) AS total_sales_by_store_p12m,
total_sales_by_sku_lm::numeric(38,6) AS total_sales_by_sku_lm,
total_sales_by_sku_p3m::numeric(38,6) AS total_sales_by_sku_p3m,
total_sales_by_sku_p6m::numeric(38,6) AS total_sales_by_sku_p6m,
total_sales_by_sku_p12m::numeric(38,6) AS total_sales_by_sku_p12m,
total_sales_lm_lp::numeric(38,12) AS total_sales_lm_lp,
total_sales_p3m_lp::numeric(38,12) AS total_sales_p3m_lp,
total_sales_p6m_lp::numeric(38,12) AS total_sales_p6m_lp,
total_sales_p12m_lp::numeric(38,12) AS total_sales_p12m_lp,
total_sales_by_store_lm_lp::numeric(38,12) AS total_sales_by_store_lm_lp,
total_sales_by_store_p3m_lp::numeric(38,12) AS total_sales_by_store_p3m_lp,
total_sales_by_store_p6m_lp::numeric(38,12) AS total_sales_by_store_p6m_lp,
total_sales_by_store_p12m_lp::numeric(38,12) AS total_sales_by_store_p12m_lp,
total_sales_by_sku_lm_lp::numeric(38,12) AS total_sales_by_sku_lm_lp,
total_sales_by_sku_p3m_lp::numeric(38,12) AS total_sales_by_sku_p3m_lp,
total_sales_by_sku_p6m_lp::numeric(38,12) AS total_sales_by_sku_p6m_lp,
total_sales_by_sku_p12m_lp::numeric(38,12) AS total_sales_by_sku_p12m_lp,
store_contribution_lm::numeric(38,4) AS store_contribution_lm,
sku_contribution_lm::numeric(38,4) AS sku_contribution_lm,
size_of_price_lm::numeric(38,14) AS size_of_price_lm,
store_contribution_p3m::numeric(38,4) AS store_contribution_p3m,
sku_contribution_p3m::numeric(38,4) AS sku_contribution_p3m,
size_of_price_p3m::numeric(38,14) AS size_of_price_p3m,
store_contribution_p6m::numeric(38,4) AS store_contribution_p6m,
sku_contribution_p6m::numeric(38,4) AS sku_contribution_p6m,
size_of_price_p6m::numeric(38,14) AS size_of_price_p6m,
store_contribution_p12m::numeric(38,4) AS store_contribution_p12m,
sku_contribution_p12m::numeric(38,4) AS sku_contribution_p12m,
size_of_price_p12m::numeric(38,14) AS size_of_price_p12m,
store_contribution_lm_lp::numeric(38,4) AS store_contribution_lm_lp,
sku_contribution_lm_lp::numeric(38,4) AS sku_contribution_lm_lp,
size_of_price_lm_lp::numeric(38,20) AS size_of_price_lm_lp,
store_contribution_p3m_lp::numeric(38,4) AS store_contribution_p3m_lp,
sku_contribution_p3m_lp::numeric(38,4) AS sku_contribution_p3m_lp,
size_of_price_p3m_lp::numeric(38,20) AS size_of_price_p3m_lp,
store_contribution_p6m_lp::numeric(38,4) AS store_contribution_p6m_lp,
sku_contribution_p6m_lp::numeric(38,4) AS sku_contribution_p6m_lp,
size_of_price_p6m_lp::numeric(38,20) AS size_of_price_p6m_lp,
store_contribution_p12m_lp::numeric(38,4) AS store_contribution_p12m_lp,
sku_contribution_p12m_lp::numeric(38,4) AS sku_contribution_p12m_lp,
size_of_price_p12m_lp::numeric(38,20) AS size_of_price_p12m_lp,
lm_sales_flag_count::numeric(38,0) AS lm_sales_flag_count,
p3m_sales_flag_count::numeric(38,0) AS p3m_sales_flag_count,
p6m_sales_flag_count::numeric(38,0) AS p6m_sales_flag_count,
p12m_sales_flag_count::numeric(38,0) AS p12m_sales_flag_count,
mdp_flag_count::numeric(38,0) AS mdp_flag_count,
crt_dttm::timestamp without time zone AS crt_dttm
from edw_rpt_my_re
)
--final select
select * from final	