with itg_hcp360_veeva_user as
(
    select * from {{ source('hcpitg_integration', 'itg_hcp360_veeva_user') }}
),
itg_hcp360_veeva_userterritory as
(
    select * from {{ source('hcpitg_integration', 'itg_hcp360_veeva_userterritory') }}
),
itg_hcp360_veeva_territory as
(
    select * from {{ source('hcpitg_integration', 'itg_hcp360_veeva_territory') }}
),
final as
(
    SELECT DISTINCT ORG_HIER.TERRITORY_SOURCE_ID,
    COUNTRY_CODE,
    ORG_HIER.TERRITORY_SOURCE_ID AS MY_ORGANIZATION_CODE,
    ORG_HIER.TERRITORY_NAME AS MY_ORGANIZATION_NAME,
    ORG_HIER.LEVEL_1_TERRITORY_CODE as ORGANIZATION_L1_CODE,
    ORG_HIER.LEVEL_1_TERRITORY_NAME as ORGANIZATION_L1_NAME,        
    ORG_HIER.LEVEL_2_TERRITORY_CODE as ORGANIZATION_L2_CODE ,
    ORG_HIER.LEVEL_2_TERRITORY_NAME as ORGANIZATION_L2_NAME,
    ORG_HIER.LEVEL_3_TERRITORY_CODE as ORGANIZATION_L3_CODE ,
    ORG_HIER.LEVEL_3_TERRITORY_NAME as ORGANIZATION_L3_NAME,
    ORG_HIER.LEVEL_4_TERRITORY_CODE as ORGANIZATION_L4_CODE ,
    ORG_HIER.LEVEL_4_TERRITORY_NAME as ORGANIZATION_L4_NAME,
    ORG_HIER.LEVEL_5_TERRITORY_CODE as ORGANIZATION_L5_CODE ,
    ORG_HIER.LEVEL_5_TERRITORY_NAME as ORGANIZATION_L5_NAME,
    ORG_HIER.LEVEL_6_TERRITORY_CODE as ORGANIZATION_L6_CODE ,
    ORG_HIER.LEVEL_6_TERRITORY_NAME as ORGANIZATION_L6_NAME,
    ORG_HIER.LEVEL_7_TERRITORY_CODE as ORGANIZATION_L7_CODE ,
    ORG_HIER.LEVEL_7_TERRITORY_NAME as ORGANIZATION_L7_NAME,
    ORG_HIER.LEVEL_8_TERRITORY_CODE as ORGANIZATION_L8_CODE ,
    ORG_HIER.LEVEL_8_TERRITORY_NAME as ORGANIZATION_L8_NAME,
    ORG_HIER.LEVEL_9_TERRITORY_CODE as ORGANIZATION_L9_CODE ,
    ORG_HIER.LEVEL_9_TERRITORY_NAME as ORGANIZATION_L9_NAME,
    convert_timezone('UTC',current_timestamp()) as CRT_DTTM,
    convert_timezone('UTC',current_timestamp()) as UPDT_DTTM
    FROM 
    ( 
    -- LEAF NODE
        (WITH BASE_USER AS
        (SELECT USER_NAME,
            EMPLOYEE_NAME,
            COMPANY_NAME,
            DEPARTMENT,
            TERRITORY_NAME,
            T.TERRITORY_SOURCE_ID,
            PARENT_TERRITORY_SOURCE_ID,
            U.COUNTRY_CODE
        FROM ITG_HCP360_VEEVA_USER U,
            ITG_HCP360_VEEVA_USERTERRITORY UT,
            ITG_HCP360_VEEVA_TERRITORY T
        WHERE EMPLOYEE_SOURCE_ID = USER_TERRITORY_USER_SOURCE_ID
        AND   UT.TERRITORY_SOURCE_ID = T.TERRITORY_SOURCE_ID
        AND   UT.IS_ACTIVE = '1' AND U.COUNTRY_CODE ='IN' ),
        
        ITG_TERRITORY AS 
        (SELECT * FROM  ITG_HCP360_VEEVA_TERRITORY T WHERE territory_name not in ('ASEANHK','SIMP')),
        LEAF_NODE AS 
        (SELECT * FROM BASE_USER),
        LEVEL_4 AS 
        (SELECT *  FROM ITG_TERRITORY WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM BASE_USER)),          
        LEVEL_3 AS 
        (SELECT *  FROM ITG_TERRITORY WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM LEVEL_4)),
        LEVEL_2 AS 
        (SELECT *  FROM ITG_TERRITORY  WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM LEVEL_3)),
        LEVEL_1 AS 
        (SELECT *  FROM ITG_TERRITORY  WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM LEVEL_2))
        
        SELECT DISTINCT BASE_USER.USER_NAME,
            BASE_USER.EMPLOYEE_NAME,
            BASE_USER.COMPANY_NAME,
            BASE_USER.DEPARTMENT,
            BASE_USER.TERRITORY_NAME,
            BASE_USER.TERRITORY_SOURCE_ID, 
            BASE_USER.COUNTRY_CODE,
            '' AS LEVEL_9_TERRITORY_CODE,
            '' AS LEVEL_9_TERRITORY_NAME,
            '' AS  LEVEL_8_TERRITORY_CODE,
            '' AS  LEVEL_8_TERRITORY_NAME,
            '' AS  LEVEL_7_TERRITORY_CODE,
            '' AS  LEVEL_7_TERRITORY_NAME,
            '' AS  LEVEL_6_TERRITORY_CODE,
            '' AS  LEVEL_6_TERRITORY_NAME,
            LEAF_NODE.TERRITORY_SOURCE_ID AS  LEVEL_5_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME AS  LEVEL_5_TERRITORY_NAME,
            LEVEL_4.TERRITORY_SOURCE_ID LEVEL_4_TERRITORY_CODE,
            LEVEL_4.TERRITORY_NAME     LEVEL_4_TERRITORY_NAME,                 
            LEVEL_3.TERRITORY_SOURCE_ID LEVEL_3_TERRITORY_CODE,
            LEVEL_3.TERRITORY_NAME LEVEL_3_TERRITORY_NAME,
            LEVEL_2.TERRITORY_SOURCE_ID LEVEL_2_TERRITORY_CODE,
            LEVEL_2.TERRITORY_NAME LEVEL_2_TERRITORY_NAME,
            LEVEL_1.TERRITORY_SOURCE_ID LEVEL_1_TERRITORY_CODE,
            LEVEL_1.TERRITORY_NAME LEVEL_1_TERRITORY_NAME
        FROM BASE_USER,
            LEAF_NODE,
            LEVEL_4,
            LEVEL_3 ,
            LEVEL_2,
            LEVEL_1
        WHERE BASE_USER.TERRITORY_SOURCE_ID = LEAF_NODE.TERRITORY_SOURCE_ID
        AND   LEAF_NODE.PARENT_TERRITORY_SOURCE_ID = LEVEL_4.TERRITORY_SOURCE_ID
        AND   LEVEL_4.PARENT_TERRITORY_SOURCE_ID = LEVEL_3.TERRITORY_SOURCE_ID
        AND   LEVEL_3.PARENT_TERRITORY_SOURCE_ID = LEVEL_2.TERRITORY_SOURCE_ID
        AND   LEVEL_2.PARENT_TERRITORY_SOURCE_ID = LEVEL_1.TERRITORY_SOURCE_ID 
        )

        UNION ALL
        --LEVEL 4
    (WITH BASE_USER AS
        (SELECT USER_NAME,
            EMPLOYEE_NAME,
            COMPANY_NAME,
            DEPARTMENT,
            TERRITORY_NAME,
            T.TERRITORY_SOURCE_ID,
            PARENT_TERRITORY_SOURCE_ID,
            U.COUNTRY_CODE
        FROM ITG_HCP360_VEEVA_USER U,
            ITG_HCP360_VEEVA_USERTERRITORY UT,
            ITG_HCP360_VEEVA_TERRITORY T
        WHERE EMPLOYEE_SOURCE_ID = USER_TERRITORY_USER_SOURCE_ID
        AND   UT.TERRITORY_SOURCE_ID = T.TERRITORY_SOURCE_ID
        AND   UT.IS_ACTIVE = '1' AND U.COUNTRY_CODE ='IN' ),
        
        ITG_TERRITORY AS 
        (SELECT * FROM  ITG_HCP360_VEEVA_TERRITORY T WHERE territory_name not in ('ASEANHK','SIMP')),       
        LEAF_NODE AS 
        (SELECT * FROM BASE_USER),
        LEVEL_4 AS 
        (SELECT *  FROM ITG_TERRITORY WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM BASE_USER)),          
        LEVEL_3 AS 
        (SELECT *  FROM ITG_TERRITORY WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM LEVEL_4)),
        LEVEL_2 AS 
        (SELECT *  FROM ITG_TERRITORY  WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM LEVEL_3))
        
        SELECT DISTINCT BASE_USER.USER_NAME,
            BASE_USER.EMPLOYEE_NAME,
            BASE_USER.COMPANY_NAME,
            BASE_USER.DEPARTMENT,
            BASE_USER.TERRITORY_NAME,
            BASE_USER.TERRITORY_SOURCE_ID, 
            BASE_USER.COUNTRY_CODE,
            '' AS LEVEL_9_TERRITORY_CODE,
            '' AS LEVEL_9_TERRITORY_NAME,
            '' AS  LEVEL_8_TERRITORY_CODE,
            '' AS  LEVEL_8_TERRITORY_NAME,
            '' AS  LEVEL_7_TERRITORY_CODE,
            '' AS  LEVEL_7_TERRITORY_NAME,
            '' AS  LEVEL_6_TERRITORY_CODE,
            '' AS  LEVEL_6_TERRITORY_NAME,
            LEAF_NODE.TERRITORY_SOURCE_ID AS  LEVEL_5_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME AS  LEVEL_5_TERRITORY_NAME,
            LEAF_NODE.TERRITORY_SOURCE_ID AS LEVEL_4_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME AS     LEVEL_4_TERRITORY_NAME,                 
            LEVEL_4.TERRITORY_SOURCE_ID LEVEL_3_TERRITORY_CODE,
            LEVEL_4.TERRITORY_NAME LEVEL_3_TERRITORY_NAME,
            LEVEL_3.TERRITORY_SOURCE_ID LEVEL_2_TERRITORY_CODE,
            LEVEL_3.TERRITORY_NAME LEVEL_2_TERRITORY_NAME,
            LEVEL_2.TERRITORY_SOURCE_ID LEVEL_1_TERRITORY_CODE,
            LEVEL_2.TERRITORY_NAME LEVEL_1_TERRITORY_NAME
        FROM BASE_USER,
            LEAF_NODE,
            LEVEL_4,
            LEVEL_3 ,
            LEVEL_2
        WHERE BASE_USER.TERRITORY_SOURCE_ID = LEAF_NODE.TERRITORY_SOURCE_ID
        AND   LEAF_NODE.PARENT_TERRITORY_SOURCE_ID = LEVEL_4.TERRITORY_SOURCE_ID
        AND   LEVEL_4.PARENT_TERRITORY_SOURCE_ID = LEVEL_3.TERRITORY_SOURCE_ID
        AND   LEVEL_3.PARENT_TERRITORY_SOURCE_ID = LEVEL_2.TERRITORY_SOURCE_ID
        AND   UPPER(LEVEL_2.TERRITORY_NAME) = 'IN' 
        )

        UNION ALL          
        --- LEVEL 3
        (WITH BASE_USER AS
        (SELECT USER_NAME,
            EMPLOYEE_NAME,
            COMPANY_NAME,
            DEPARTMENT,
            TERRITORY_NAME,
            T.TERRITORY_SOURCE_ID,
            PARENT_TERRITORY_SOURCE_ID,
            U.COUNTRY_CODE
        FROM ITG_HCP360_VEEVA_USER U,
            ITG_HCP360_VEEVA_USERTERRITORY UT,
            ITG_HCP360_VEEVA_TERRITORY T
        WHERE EMPLOYEE_SOURCE_ID = USER_TERRITORY_USER_SOURCE_ID
        AND   UT.TERRITORY_SOURCE_ID = T.TERRITORY_SOURCE_ID
        AND   UT.IS_ACTIVE = '1' AND U.COUNTRY_CODE ='IN' ),
        
        ITG_TERRITORY AS 
        (SELECT * FROM  ITG_HCP360_VEEVA_TERRITORY T WHERE territory_name not in ('ASEANHK','SIMP')),
        LEAF_NODE AS 
        (SELECT * FROM BASE_USER),
        LEVEL_4 AS 
        (SELECT *  FROM ITG_TERRITORY WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM BASE_USER)),
        LEVEL_3 AS 
        (SELECT *  FROM ITG_TERRITORY  WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM LEVEL_4))
        
        SELECT DISTINCT BASE_USER.USER_NAME,
            BASE_USER.EMPLOYEE_NAME,
            BASE_USER.COMPANY_NAME,
            BASE_USER.DEPARTMENT,
            BASE_USER.TERRITORY_NAME,
            BASE_USER.TERRITORY_SOURCE_ID, 
            BASE_USER.COUNTRY_CODE,                 
            '' AS LEVEL_9_TERRITORY_CODE,
            '' AS LEVEL_9_TERRITORY_NAME,
            '' AS  LEVEL_8_TERRITORY_CODE,
            '' AS  LEVEL_8_TERRITORY_NAME,
            '' AS  LEVEL_7_TERRITORY_CODE,
            '' AS  LEVEL_7_TERRITORY_NAME,
            '' AS  LEVEL_6_TERRITORY_CODE,
            '' AS  LEVEL_6_TERRITORY_NAME,
            LEAF_NODE.TERRITORY_SOURCE_ID AS  LEVEL_5_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME AS  LEVEL_5_TERRITORY_NAME,
            LEAF_NODE.TERRITORY_SOURCE_ID LEVEL_4_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME LEVEL_4_TERRITORY_NAME,                 
            LEAF_NODE.TERRITORY_SOURCE_ID LEVEL_3_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME LEVEL_3_TERRITORY_NAME,
            LEVEL_4.TERRITORY_SOURCE_ID LEVEL_2_TERRITORY_CODE,
            LEVEL_4.TERRITORY_NAME LEVEL_2_TERRITORY_NAME,
            LEVEL_3.TERRITORY_SOURCE_ID LEVEL_1_TERRITORY_CODE,
            LEVEL_3.TERRITORY_NAME LEVEL_1_TERRITORY_NAME
        FROM BASE_USER,
            LEAF_NODE,
            LEVEL_4 ,
            LEVEL_3
        WHERE BASE_USER.TERRITORY_SOURCE_ID = LEAF_NODE.TERRITORY_SOURCE_ID
        AND   LEAF_NODE.PARENT_TERRITORY_SOURCE_ID = LEVEL_4.TERRITORY_SOURCE_ID
        AND   LEVEL_4.PARENT_TERRITORY_SOURCE_ID = LEVEL_3.TERRITORY_SOURCE_ID
        AND   UPPER(LEVEL_3.TERRITORY_NAME) = 'IN'
        )
        UNION ALL
        --- LEVEL 2 
        (WITH BASE_USER AS
        (SELECT USER_NAME,
            EMPLOYEE_NAME,
            COMPANY_NAME,
            DEPARTMENT,
            TERRITORY_NAME,
            T.TERRITORY_SOURCE_ID,
            PARENT_TERRITORY_SOURCE_ID,
            U.COUNTRY_CODE
        FROM ITG_HCP360_VEEVA_USER U,
            ITG_HCP360_VEEVA_USERTERRITORY UT,
            ITG_HCP360_VEEVA_TERRITORY T
        WHERE EMPLOYEE_SOURCE_ID = USER_TERRITORY_USER_SOURCE_ID
        AND   UT.TERRITORY_SOURCE_ID = T.TERRITORY_SOURCE_ID
        AND   UT.IS_ACTIVE = '1' AND U.COUNTRY_CODE ='VN' ),
        
        ITG_TERRITORY AS 
        (SELECT * FROM  ITG_HCP360_VEEVA_TERRITORY T WHERE territory_name not in ('ASEANHK','SIMP')),
        LEAF_NODE AS 
        (SELECT * FROM BASE_USER),
        LEVEL_4 AS 
        (SELECT *  FROM ITG_TERRITORY WHERE (TERRITORY_SOURCE_ID)  IN (SELECT PARENT_TERRITORY_SOURCE_ID  FROM BASE_USER))
        
        SELECT DISTINCT BASE_USER.USER_NAME,
            BASE_USER.EMPLOYEE_NAME,
            BASE_USER.COMPANY_NAME,
            BASE_USER.DEPARTMENT,
            BASE_USER.TERRITORY_NAME,
            BASE_USER.TERRITORY_SOURCE_ID, 
            BASE_USER.COUNTRY_CODE,                 
            '' AS LEVEL_9_TERRITORY_CODE,
            '' AS LEVEL_9_TERRITORY_NAME,
            '' AS  LEVEL_8_TERRITORY_CODE,
            '' AS  LEVEL_8_TERRITORY_NAME,
            '' AS  LEVEL_7_TERRITORY_CODE,
            '' AS  LEVEL_7_TERRITORY_NAME,
            '' AS  LEVEL_6_TERRITORY_CODE,
            '' AS  LEVEL_6_TERRITORY_NAME,
            LEAF_NODE.TERRITORY_SOURCE_ID AS  LEVEL_5_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME AS  LEVEL_5_TERRITORY_NAME,
            LEAF_NODE.TERRITORY_SOURCE_ID LEVEL_4_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME LEVEL_4_TERRITORY_NAME,                 
            LEAF_NODE.TERRITORY_SOURCE_ID LEVEL_3_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME LEVEL_3_TERRITORY_NAME,
            LEAF_NODE.TERRITORY_SOURCE_ID LEVEL_2_TERRITORY_CODE,
            LEAF_NODE.TERRITORY_NAME LEVEL_2_TERRITORY_NAME,
            LEVEL_4.TERRITORY_SOURCE_ID LEVEL_1_TERRITORY_CODE,
            LEVEL_4.TERRITORY_NAME LEVEL_1_TERRITORY_NAME
        FROM BASE_USER,
            LEAF_NODE,
            LEVEL_4 
        WHERE BASE_USER.TERRITORY_SOURCE_ID = LEAF_NODE.TERRITORY_SOURCE_ID
        AND   LEAF_NODE.PARENT_TERRITORY_SOURCE_ID = LEVEL_4.TERRITORY_SOURCE_ID
        AND   UPPER(LEVEL_4.TERRITORY_NAME) = 'IN'
        )        
    ) ORG_HIER  
)
select territory_source_id::varchar(18) as territory_source_id,
    country_code::varchar(8) as country_code,
    my_organization_code::varchar(18) as my_organization_code,
    my_organization_name::varchar(80) as my_organization_name,
    organization_l1_code::varchar(18) as organization_l1_code,
    organization_l1_name::varchar(80) as organization_l1_name,
    organization_l2_code::varchar(18) as organization_l2_code,
    organization_l2_name::varchar(80) as organization_l2_name,
    organization_l3_code::varchar(18) as organization_l3_code,
    organization_l3_name::varchar(80) as organization_l3_name,
    organization_l4_code::varchar(18) as organization_l4_code,
    organization_l4_name::varchar(80) as organization_l4_name,
    organization_l5_code::varchar(18) as organization_l5_code,
    organization_l5_name::varchar(80) as organization_l5_name,
    organization_l6_code::varchar(18) as organization_l6_code,
    organization_l6_name::varchar(80) as organization_l6_name,
    organization_l7_code::varchar(18) as organization_l7_code,
    organization_l7_name::varchar(80) as organization_l7_name,
    organization_l8_code::varchar(18) as organization_l8_code,
    organization_l8_name::varchar(80) as organization_l8_name,
    organization_l9_code::varchar(18) as organization_l9_code,
    organization_l9_name::varchar(80) as organization_l9_name,
    crt_dttm::timestamp_ntz(9) as crt_dttm,
    updt_dttm::timestamp_ntz(9) as updt_dttm
 from final