{% macro wks_indonesia_noo_analysis_update() %}
 Update {{this}}  set latest_chnl = upper(edcd.chnl), latest_outlet_type = upper(edcd.outlet_type), latest_chnl_grp = edcd.chnl_grp, latest_cust_grp2 = edcd.cust_grp2, latest_cust_grp = edcd.cust_grp, latest_cust_nm_map = edcd.cust_nm_map from {{this}} n1 inner join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = trim(upper(edcd.key_outlet)) where concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = trim(upper(edcd.key_outlet));
 Update {{this}}  set latest_outlet_type = upper(edcd.outlet_type) from {{this}} n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = concat(TRIM(UPPER(edcd.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(edcd.cust_id_map))) where n1.outlet_type is not null and n1.latest_outlet_type is null;
 Update {{this}}  set latest_chnl = upper(edcd.chnl) from {{this}}  n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = concat(TRIM(UPPER(edcd.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(edcd.cust_id_map))) where n1.chnl is not null and n1.latest_chnl is null;
 Update {{this}}  set latest_chnl_grp = edcd.chnl_grp from {{this}}  n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = concat(TRIM(UPPER(edcd.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(edcd.cust_id_map))) where n1.chnl_grp is not null and n1.latest_chnl_grp is null;
 Update {{this}}  set latest_cust_grp2 = edcd.cust_grp2 from {{this}}  n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = concat(TRIM(UPPER(edcd.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(edcd.cust_id_map))) where n1.tiering is not null and n1.latest_cust_grp2 is null;
 Update {{this}}  set latest_cust_grp = edcd.cust_grp from {{this}}  n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = concat(TRIM(UPPER(edcd.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(edcd.cust_id_map))) where n1.cust_grp is not null and n1.latest_cust_grp is null;
 Update {{this}}  set latest_cust_nm_map = edcd.cust_nm_map from {{this}}  n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = concat(TRIM(UPPER(edcd.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(edcd.cust_id_map))) where n1.cust_nm_map is not null and n1.latest_cust_nm_map is null;
 Update {{this}}  set latest_region = edd.region, latest_area = edd.area, latest_rbm = edd.rbm_nm, latest_area_pic = edd.bdm_nm from {{this}} as n1 inner join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_DIM AS EDD on TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)) = trim(upper(edd.jj_sap_dstrbtr_id)) where TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID))= TRIM(UPPER(edd.jj_sap_dstrbtr_id));
 Update {{this}}  set latest_region = edd.region from {{this}} as n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_DIM AS EDD on TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)) = trim(upper(edd.jj_sap_dstrbtr_id)) where n1.region is not null and n1.latest_region is null;
 Update {{this}}  set latest_area = edd.area from {{this}}  as n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_DIM AS EDD on TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)) = trim(upper(edd.jj_sap_dstrbtr_id)) where n1.area is not null and n1.latest_area is null;
 Update {{this}}  set latest_rbm = edd.rbm_nm from {{this}}  as n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_DIM AS EDD on TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)) = trim(upper(edd.jj_sap_dstrbtr_id)) where n1.rbm_nm is not null and n1.latest_rbm is null;
 Update {{this}}  set latest_area_pic = edd.bdm_nm from {{this}}  as n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_DIM AS EDD on TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)) = trim(upper(edd.jj_sap_dstrbtr_id)) where n1.bdm_nm is not null and n1.latest_area_pic is null;
Update {{this}}  set latest_jjid = edcd.jjid from {{this}} n1 inner join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = trim(upper(edcd.key_outlet)) where concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = trim(upper(edcd.key_outlet));
 Update {{this}}  set latest_jjid = upper(edcd.jjid) from {{this}} n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = concat(TRIM(UPPER(edcd.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(edcd.cust_id_map))) where n1.jjid is not null and n1.latest_jjid is null;
Update {{this}}  set latest_put_up = edp.VARIANT3 || ' ' || NVL(CAST(edp.PUT_UP AS VARCHAR),''), latest_franchise = edp.franchise, latest_brand = edp.brand from {{this}} as n1 inner join dev_dna_core.idnedw_integration.EDW_PRODUCT_DIM AS EDP on TRIM(UPPER(n1.JJ_SAP_PROD_ID)) = trim(upper(edp.jj_sap_prod_id)) where TRIM(UPPER(n1.JJ_SAP_PROD_ID))= TRIM(UPPER(edp.jj_sap_prod_id));
 Update {{this}}  set latest_put_up = edp.VARIANT3 || ' ' || NVL(CAST(edp.PUT_UP AS VARCHAR),'') from {{this}}  as n1 join dev_dna_core.idnedw_integration.EDW_PRODUCT_DIM AS EDP on TRIM(UPPER(n1.JJ_SAP_PROD_ID)) = trim(upper(edp.jj_sap_prod_id)) where n1.put_up is not null and n1.latest_put_up is null;
 Update {{this}}  set latest_franchise = edp.franchise from {{this}}  as n1 join dev_dna_core.idnedw_integration.EDW_PRODUCT_DIM AS EDP on TRIM(UPPER(n1.JJ_SAP_PROD_ID)) = trim(upper(edp.jj_sap_prod_id)) where n1.franchise is not null and n1.latest_franchise is null;
 Update {{this}}  set latest_brand = edp.brand from {{this}}  as n1 join dev_dna_core.idnedw_integration.EDW_PRODUCT_DIM AS EDP on TRIM(UPPER(n1.JJ_SAP_PROD_ID)) = trim(upper(edp.jj_sap_prod_id)) where n1.brand is not null and n1.latest_brand is null;
 update {{this}}  set latest_chnl_grp2 = edcd.chnl_grp2 from {{this}} n1 inner join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = trim(upper(edcd.key_outlet)) where concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = trim(upper(edcd.key_outlet));
 Update {{this}}  set latest_chnl_grp2 = edcd.chnl_grp2 from {{this}} n1 join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_CUSTOMER_DIM EDCD on concat(TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(n1.cust_id_map))) = concat(TRIM(UPPER(edcd.JJ_SAP_DSTRBTR_ID)),TRIM(UPPER(edcd.cust_id_map))) where n1.chnl_grp2 is not null and n1.latest_chnl_grp2 is null;
 update {{this}}  set Latest_Distributor_Group = edcd.dstrbtr_grp_nm from {{this}} n1 inner join dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_DIM  EDCD on TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)) = trim(upper(EDCD.jj_sap_dstrbtr_id));
 Update {{this}}  set Latest_Dstrbtr_grp_cd = edcd.dstrbtr_grp_cd from {{this}} n1 join  dev_dna_core.idnedw_integration.EDW_DISTRIBUTOR_DIM EDCD on TRIM(UPPER(n1.JJ_SAP_DSTRBTR_ID)) = trim(upper(EDCD.jj_sap_dstrbtr_id));

{% endmacro %}

