{{ config(
  materialized='incremental',
  transient=false,
  post_hook="call common_integration.SP_GET_HARMONIZED_BRAND('TRADITIONAL_ACTUAL_TV_SPEND','Y')"
) }}


select
ts.CLIENT as CLIENT ,  
ts.CL_CODE as CL_CODE ,  
ts.CL_GSTIN as CL_GSTIN ,  
ts.PRODUCT as PRODUCT ,  
ts.EST_NO as EST_NO ,  
cast(ts.EST_DT as date) as EST_DT ,  
floor(cast(ts.EST_AMOUNT as float),2) as EST_AMOUNT ,
floor(cast(ts.EST_RT10SC as float),2) as EST_RT10SC ,
ts.SUPP_NO as SUPP_NO ,  
ts.SUPP_DT as SUPP_DT ,  
ts.CAM_CODE as CAM_CODE ,  
ts.CAM_DES as CAM_DES ,  
ts.CAM_REM as CAM_REM ,  
ts.CHANNEL_CD as CHANNEL_CD ,  
ts.CHANNEL as CHANNEL ,  
ts.PROGRAM as PROGRAM ,  
ts.DAYS as DAYS ,  
cast(ts.SPOT_DATE as date) as SPOT_DATE ,  
ts.SPOT_DAY as SPOT_DAY ,  
cast(ts.ORI_DATE as date) as ORI_DATE ,  
ts.TELE_TIME as TELE_TIME ,  
cast(ts.DURATION as integer) as DURATION ,  
cast(ts.REV_DATE as date) as REV_DATE ,  
ts.STATUS as STATUS ,  
ts.RO_NUMBER as RO_NUMBER ,  
cast(ts.RO_DATE as date) as RO_DATE ,  
floor(cast(ts.RO_AMOUNT as float),2) as RO_AMOUNT,
floor(cast(ts.RO_RT_10SC as float),2) as RO_RT_10SC,
ts.CAN_NO as CAN_NO ,  
cast(ts.CAN_DATE  as date) as CAN_DATE ,  
ts.SAVEEST_NO as SAVEEST_NO ,  
ts.CURRENCY as CURRENCY ,  
ts.MONI_COMP as MONI_COMP ,  
ts.MONI_NO as MONI_NO ,  
cast(ts.MONI_DATE  as date) as MONI_DATE ,  
cast(ts.AD_SPOTORD as integer) as AD_SPOTORD ,  
cast(ts.TOT_SPOT as integer) as TOT_SPOT ,  
ts.AD_TIME as AD_TIME ,  
ts.AD_LANG as AD_LANG ,  
ts.OB_NUMBER as OB_NUMBER ,  
cast(ts.OB_DATE as date) as OB_DATE ,  
floor(cast(ts.OB_AMOUNT as float),2) as OB_AMOUNT,
floor(cast(ts.OB_RT_10SC as float),2) as OB_RT_10SC,
ts.VENDOR_CD as VENDOR_CD ,  
ts.IB_NUMBER as IB_NUMBER ,  
ts.IB_DATE as IB_DATE ,  
ts.ENTRC as ENTRC ,  
ts.AD_NO as AD_NO ,  
ts.CAPTION as CAPTION ,  
ts.ROTOCOMP as ROTOCOMP ,  
ts.VN_GSTIN as VN_GSTIN ,  
ts.PONO as PONO ,  
cast(ts.PO_DT as date) as PO_DT ,  
ts.SAPNO as SAPNO ,  
ts.FA_IB_NO as FA_IB_NO ,  
floor(cast(ts.AAC_AMT as float),2) as AAC_AMT,
floor(cast(ts.AAC_PER as float),2) as AAC_PER,
floor(cast(ts.SAC_PER as float),2) as SAC_PER,
floor(cast(ts.NET_RO as float),2) as NET_RO,
floor(cast(ts.NET_OB as float),2) as NET_OB,
floor(cast(ts.NET_IB as float),2) as NET_IB,
ts.RO_CLIENT  as RO_CLIENT ,  
ts.CAT1_CODE as CAT1_CODE ,  
ts.CAT2_CODE as CAT2_CODE ,  
ts.CAT1_NAME as CAT1_NAME ,  
ts.CAT2_NAME as CAT2_NAME ,  
floor(cast(ts.STD_RATE as float),2) as STD_RATE,
floor(cast(ts.STD_COST as float),2) as STD_COST,
floor(cast(ts.PLAN_RATE as float),2) as PLAN_RATE,
floor(cast(ts.PLAN_COST as float),2) as PLAN_COST,
ts.BILL_NO as BILL_NO ,  
cast(ts.SCHMONTH as integer) as SCHMONTH ,  
cast(ts.SCHYEAR as integer) as SCHYEAR ,  
ts.TAPE_NO as TAPE_NO  ,  
ts.ADTYPDESC as ADTYPDESC  ,  
ts.SUPBILL_NO as SUPBILL_NO   ,  
cast(ts.SUPBILL_DT as date) as SUPBILL_DT ,  
floor(cast(ts.SUPBILLAMT as float),2) as SUPBILLAMT,
floor(cast(ts.SUPBILLNET as float),2) as SUPBILLNET,
ts.OB_STATE as OB_STATE ,  
ts.OB_GST_ON as OB_GST_ON ,  
floor(cast(ts.AGNGSTBASE as float),2) as AGNGSTBASE,
floor(cast(ts.AGNCGSTPER as float),2) as AGNCGSTPER,
floor(cast(ts.AGNCOMCGST as float),2) as AGNCOMCGST,
floor(cast(ts.AGNSGSTPER as float),2) as AGNSGSTPER,
floor(cast(ts.AGNCOMSGST as float),2) as AGNCOMSGST,
floor(cast(ts.AGNIGSTPER as float),2) as AGNIGSTPER,
floor(cast(ts.AGNCOMIGST as float),2) as AGNCOMIGST,
ts.RECOVERTAX as RECOVERTAX ,  
floor(cast(ts.OB_GSTBASE as float),2) as OB_GSTBASE,
floor(cast(ts.OB_CGSTPER as float),2) as OB_CGSTPER,
floor(cast(ts.OB_CGSTAMT as float),2) as OB_CGSTAMT,
floor(cast(ts.OB_SGSTPER as float),2) as OB_SGSTPER,
floor(cast(ts.OB_SGSTAMT as float),2) as OB_SGSTAMT,
floor(cast(ts.OB_IGSTPER as float),2) as OB_IGSTPER,
floor(cast(ts.OB_IGSTAMT as float),2) as OB_IGSTAMT,
ts.IRN_NO as IRN_NO ,  
ts.ACK_NO as ACK_NO ,  
cast(ts.ACK_DT as date) as ACK_DT ,  
ts."GROUP" as "GROUP" ,  
ts.TEL_STN as TEL_STN ,  
ts.KEY as KEY ,  
ts.CL_TOTAL as CL_TOTAL ,  
ts.ROCL_CD as ROCL_CD ,  
ts.STVENTER as STVENTER ,  
cast(ts.EST_SPOT as integer) as EST_SPOT ,  
ts.MEDIAM as MEDIAM ,  
ts.PR_CODE as PR_CODE ,  
floor(cast(ts.OB_COST as float),2) as OB_COST_INR , 
floor(cast(cast(replace(ts.OB_COST,',','') as float)/ curr.rate as float),2) as OB_COST_USD,
ts.UIDKEY as UIDKEY ,  
ts.COMP_GRPCD as COMP_GRPCD ,  
ts.COMP_GRPNM as COMP_GRPNM ,  
ts.HOUSE_NAME as HOUSE_NAME ,  
ts.PROV_ON as PROV_ON,
'India' as GCGH_COUNTRY,
null as GCPH_BRAND,
null as BRAND_HARMONIZED_BY,
TO_TIMESTAMP(CURRENT_TIMESTAMP()) as crt_dttm,
try_TO_TIMESTAMP('') as updt_dttm

from {{ source(
      "TRADITIONAL_RAW",
      "T_TRANS_TV_SPENDS_INDIA_MONTHLY"
    )}}  ts
left join {{ source(
      "TRADITIONAL_RAW",
      "T_TRADITIONAL_CURRENCY_EXCHANGE_RATE"
    )}}  curr
on ts.OB_DATE=curr.date