{{ config(
  materialized='incremental',
  transient=false,
) }}


SELECT
	CLIENT
	, GCPH_BRAND
	, 'India' AS GCGH_COUNTRY
	, CAMPAIGN
	, OBJECTIVE
	, cast(YEAR as NUMBER(38,0)) as YEAR
	, QUARTER
	, MONTH
	, START_DATE
	, END_DATE
	, PUBLISHER
	, DOMAIN_SITE
	, CATEGORY_PUBLISHER_TYPE
	, SECTION
	, TARGETING
	, GEOGRAPHY
	, DEMO
	, AD_UNIT
	, NORMALIZED_AD_UNIT
	, AD_UNIT_TYPE
	, CREATIVE_SIZE
	, cast(NO_OF_DAYS as NUMBER(38,0)) as NO_OF_DAYS
	, PROGRAMMATIC
	, DSP
	, MEDIA_PROPERTY_TYPE
	, MEDIUM
	, DEAL_TYPE
	, cast(REACH as NUMBER(38,5)) as REACH
	, cast(DELIVERED_IMPRESSIONS as NUMBER(38,5)) as DELIVERED_IMPRESSIONS
	, cast(DELIVERED_TOTAL_VIEWS_VIDEO as NUMBER(38,5)) as DELIVERED_TOTAL_VIEWS_VIDEO
	, cast(VIDEO_FIRST_QUARTILE_VIEWS as NUMBER(38,5)) as VIDEO_FIRST_QUARTILE_VIEWS
	, cast(VIDEO_SECOND_QUARTILE_VIEWS as NUMBER(38,5)) as VIDEO_SECOND_QUARTILE_VIEWS
	, cast(VIDEO_THIRD_QUARTILE_VIEWS as NUMBER(38,5)) as VIDEO_THIRD_QUARTILE_VIEWS
	, cast(VIDEO_TOTAL_VIEWS as NUMBER(38,5)) as VIDEO_TOTAL_VIEWS
	, cast(DELIVERED_CLICKS as NUMBER(38,5)) as DELIVERED_CLICKS
	, cast(DELIVERED_LINK_CLICKS as NUMBER(38,5)) as DELIVERED_LINK_CLICKS
	, cast(DELIVERED_ENGAGEMENTS  as NUMBER(38,5)) as DELIVERED_ENGAGEMENTS
	, cast(DELIVERED_NET_RATE as NUMBER(38,5)) as DELIVERED_NET_RATE
	, cast(NET_COST as NUMBER(38,5)) as NET_COST
	, CURRENT_TIMESTAMP() AS LOAD_TS

    from {{ source('TRADITIONAL_RAW','T_TRANS_OTHER_PAID_MEDIA_LIDAR_MONTHLY_APAC') }}