{% macro build_ssmthsalhephedda() %}
    {% set query %}
        CREATE TABLE if not exists 
        {% if target.name=='prod' %}
                    jpdclitg_integration.ssmthsalhephedda
                {% else %}
                    {{schema}}.jpndclitg_integration__ssmthsalhephedda
                {% endif %}
         (
                KAISHA_CD VARCHAR(15) NOT NULL,
                SAL_NO VARCHAR(18) NOT NULL,
                SAL_JISK_IMP_SNSH_NO VARCHAR(30),
                SAL_SHUR_KBN VARCHAR(1),
                SAL_DEN_KBN VARCHAR(1),
                SHANIGI_KBN VARCHAR(1),
                KKNG_KBN VARCHAR(1),
                DEN_ADD_KBN VARCHAR(1),
                SKCH_TR_SITE_KBN VARCHAR(1),
                TORI_KBN VARCHAR(1),
                TORI_KENMEI VARCHAR(120),
                SM_CHANERU_CD VARCHAR(3),
                MUSYO_JUCH_KBN VARCHAR(1),
                MUSYO_TORI_RIYUU_CD VARCHAR(6),
                REND_MT_DEN_SHUBT VARCHAR(4),
                REND_MT_DEN_NO VARCHAR(18),
                HASS_MT_DEN_SHUBT VARCHAR(4),
                HASSEI_MT_DEN_NO VARCHAR(18),
                SHANAI_TORI_HACHU_NO VARCHAR(18),
                JUHACHU_TORI_PM_NO VARCHAR(18),
                SAL_KEIJ_DT NUMBER(18,0),
                SAL_TANTCD VARCHAR(22),
                SAL_BMN_NAIBU_NO VARCHAR(30),
                IN_TANTCD VARCHAR(22),
                TOKUISK_CD VARCHAR(22),
                SNPO_CHUMON_NO VARCHAR(30),
                TOKUISK_SNPO_TANT_NMS VARCHAR(33),
                TOKUISK_SNPO_TANT_TEL VARCHAR(30),
                TOKUISK_SNPO_TANT_FAX VARCHAR(30),
                SHHARSK_CD VARCHAR(22),
                SHHAR_KSSAI_JKEN_NAIBU_NO VARCHAR(30),
                SHHAR_KSSAI_JKEN_NMS VARCHAR(120),
                SHHAR_KSSAI_JKEN_NMR VARCHAR(30),
                SHHARSHIME_KBN VARCHAR(1),
                SHHARSHIME_NAYOSE_KOMK VARCHAR(30),
                SKYSK_CD VARCHAR(22),
                KAIS_KSSAI_JKEN_NAIBU_NO VARCHAR(30),
                KAIS_KSSAI_JKEN_NMS VARCHAR(120),
                KAIS_KSSAI_JKEN_NMR VARCHAR(30),
                SKYSHIME_KBN VARCHAR(1),
                SKYSHIME_NAYOSE_KOMK VARCHAR(30),
                SM_SKYSK_YUUBIN_NO VARCHAR(10),
                SM_SKYSK_ADDR1 VARCHAR(150),
                SM_SKYSK_ADDR2 VARCHAR(150),
                SM_SKYSK_TANT_NMS VARCHAR(33),
                SM_SKYSK_TEL VARCHAR(30),
                SM_SKYSK_FAX VARCHAR(30),
                SHUKASK_CD VARCHAR(22),
                SHUKASK_NMS1 VARCHAR(75),
                SHUKASK_NMS2 VARCHAR(75),
                SHUKASK_YUUBIN_NO VARCHAR(10),
                SHUKASK_ADDR1 VARCHAR(150),
                SHUKASK_ADDR2 VARCHAR(150),
                SHUKASK_TANT_NMS VARCHAR(33),
                SHUKASK_TEL VARCHAR(30),
                SHUKASK_FAX VARCHAR(30),
                JUYOUKA_CD VARCHAR(22),
                SKCH_TR_NAIBU_NO VARCHAR(30),
                SOKO_NAIBU_NO VARCHAR(30),
                PJ_CD VARCHAR(30),
                TATNE_TUKA_CD VARCHAR(4),
                TATNE_CH_RATE_UNT NUMBER(38,0),
                TATNE_CH_RATE NUMBER(8,4),
                KSAI_TUKA_CD VARCHAR(4),
                KSAI_CH_RATE_UNT NUMBER(38,0),
                KAJUU_HEIKIN_KSAI_CH_RATE NUMBER(8,4),
                SAL_SUM_KIN NUMBER(15,2),
                SHOUMI_SAL_SUM_KIN NUMBER(15,2),
                SAL_SHOHZEI_SUM_KIN NUMBER(15,2),
                DEN_NEBIKI_RITSU NUMBER(6,3),
                DEN_NEBIKI_KIN NUMBER(15,2),
                SHOUMI_DEN_NEBIKI_KIN NUMBER(15,2),
                DEN_NEBIKI_SZ_KIN NUMBER(15,2),
                DEN_NAF_SAL_KIN NUMBER(15,2),
                DEN_NF_SHM_SAL_KIN NUMBER(15,2),
                DEN_NAF_SAL_SZ_KIN NUMBER(15,2),
                SAL_SUM_KIN_KSAI NUMBER(15,2),
                SHOUMI_SAL_SUM_KIN_KSAI NUMBER(15,2),
                SAL_SZ_SUM_KIN_KSAI NUMBER(15,2),
                DEN_NB_KIN_KSAI NUMBER(15,2),
                SHOUMI_DEN_NB_KIN_KSAI NUMBER(15,2),
                DEN_NB_SZ_KIN_KSAI NUMBER(15,2),
                DEN_NAF_SAL_KIN_KSAI NUMBER(15,2),
                DEN_NF_SHM_SAL_KIN_KSAI NUMBER(15,2),
                DEN_NAF_SAL_SZ_KIN_KSAI NUMBER(15,2),
                SAL_SUM_KIN_KIH NUMBER(15,2),
                SHOUMI_SAL_SUM_KIN_KIH NUMBER(15,2),
                SAL_SZ_SUM_KIN_KIH NUMBER(15,2),
                DEN_NB_KIN_KIH NUMBER(15,2),
                SHOUMI_DEN_NB_KIN_KIH NUMBER(15,2),
                DEN_NB_SZ_KIN_KIH NUMBER(15,2),
                DEN_NAF_SAL_KIN_KIH NUMBER(15,2),
                DEN_NF_SHM_SAL_KIN_KIH NUMBER(15,2),
                DEN_NAF_SAL_SZ_KIN_KIH NUMBER(15,2),
                SAL_GENKA_SUM_KIN NUMBER(15,2),
                SHGK_SUM_KIN NUMBER(15,2),
                SAL_SOU_RIEKI_SUM_KIN NUMBER(15,2),
                SAL_SOU_RIEKI_RITSU NUMBER(6,3),
                HANKAN_HI_TOU_SUM_KIN NUMBER(15,2),
                EIGYOU_RIEKI_SUM_KIN NUMBER(15,2),
                EIGYOU_RIEKI_RITSU NUMBER(6,3),
                SHOKAI_SAL_DT NUMBER(18,0),
                UPD_MT_SAL_NO VARCHAR(18),
                UPD_SAL_NO VARCHAR(18),
                SOSAI_SAL_NO VARCHAR(18),
                SAL_TEKYO VARCHAR(160),
                SAL_BKO VARCHAR(768),
                SAL_MEMO VARCHAR(768),
                KAKAK_KT_KEY_CD VARCHAR(15),
                SHOKAI_SAL_NO VARCHAR(18),
                KSSAI_JKEN_MOD_FLG NUMBER(38,0),
                DEN_NAF_SAL_KIN_MOD_FLG NUMBER(38,0),
                SAL_BNKTSU_FLG NUMBER(38,0),
                YOSHIN_GENDO_KIN_OVER_FLG NUMBER(38,0),
                SKCH_TR_GNDGK_OVER_FLG NUMBER(38,0),
                MUSYO_TORI_FUKUMU_FLG NUMBER(38,0),
                TEIKI_SAL_FUKUMU_FLG NUMBER(38,0),
                MEU_SKY_FLG NUMBER(38,0),
                SM_SHNIN_SHNSI_JOKYO_KBN VARCHAR(1),
                SHOUNIN_SHINSEI_NO VARCHAR(30),
                ZENKAI_SHOUNIN_SHINSEI_NO VARCHAR(30),
                SM_SHNIN_SHNSI_JOKYO_KBN_DN VARCHAR(1),
                SHNIN_SHNSI_NO_DEN VARCHAR(30),
                RINGISHO_NO VARCHAR(30),
                SIWK_ADD_JOKYO_KBN VARCHAR(1),
                CAN_SIWK_ADD_JOKYO_KBN VARCHAR(1),
                SIWK_RENKEI_NAIBU_NO VARCHAR(30),
                JIDOU_SIWK_RUN_SEQ_NO NUMBER(38,0),
                AP_RENKEI_JOKYO_KBN VARCHAR(1),
                AR_RENKEI_JOKYO_KBN VARCHAR(1),
                AR_AP_RENKEI_SK_KBN VARCHAR(1),
                SAL_RIREKI_NO NUMBER(38,0),
                SKY_DEN_NAIBU_NO VARCHAR(30),
                SHHAR_DEN_NAIBU_NO VARCHAR(30),
                SM_SIWK_NAIBU_NO VARCHAR(30),
                PROCESSTYPE_CD VARCHAR(15),
                JYU_HACHU_KBN VARCHAR(1),
                SOUGK_JUNGK_KBN VARCHAR(1),
                KWSE_YOYAKU_KANRI_KBN VARCHAR(1),
                KWSE_YOYAKU_KAIKEI_SHR_KBN VARCHAR(1),
                TOKUISK_SHUS_JOHO_HYOJI_FLG NUMBER(38,0),
                SKYSK_SHUS_JOHO_HYOJI_FLG NUMBER(38,0),
                SHUKASK_SHUS_JOHO_HYOJI_FLG NUMBER(38,0),
                CAN_FLG NUMBER(38,0),
                CAN_DT NUMBER(18,0),
                CAN_KOUSISHA_CD VARCHAR(22),
                SM_DEN_ADD_DT NUMBER(18,0),
                DEN_UPD_DT NUMBER(18,0),
                DEN_KOUSISHA VARCHAR(22),
                TOUROKU_USER VARCHAR(22) NOT NULL,
                TOUROKU_DATE NUMBER(38,0) NOT NULL,
                KOUSHIN_USER VARCHAR(22) NOT NULL,
                KOUSHIN_DATE NUMBER(38,0) NOT NULL,
                SOURCE_FILE_DATE VARCHAR(10),
                INSERTED_DATE TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_TZ(9)),
                INSERTED_BY VARCHAR(100) DEFAULT 'ETL_Batch',
                UPDATED_DATE TIMESTAMP_NTZ(9) DEFAULT CAST('CURRENT_TIMESTAMP()' AS TIMESTAMP_TZ(9)),
                UPDATED_BY VARCHAR(100)
        );
                               
    {% endset %}

    {% do run_query(query) %}
    
{% endmacro %}