
{{ 
    config(materialized='table', 
    transient= true
    )
     
    }}
with wks_cnpc_rpt_retail_excellence
as (select * from {{ ref('chnwks_integration__wks_china_personal_care_rpt_retail_excellence') }}),

edw_list_price as(
    select * from {{ ref('aspedw_integration__edw_list_price') }}
),

wks_cnpc_rpt_retail_excellence_sop as 
(
    (select fisc_yr,
       fisc_per,
       "cluster",
       market,
       data_src,
	   soldto_code,
       distributor_code,
       distributor_name,
       coalesce(sell_out_channel,'Not Defined') as sell_out_channel,
       sell_out_re,
       store_type,
       store_code,
       store_name,
       region,
       zone_name,
       city,
       customer_segment_key,
       customer_segment_description,
       sap_parent_customer_key,
       sap_parent_customer_description,
       sap_customer_channel_key,
       sap_customer_channel_description,
       sap_customer_sub_channel_key,
       sap_sub_channel_description,
       sap_go_to_mdl_key,
       sap_go_to_mdl_description,
       sap_banner_key,
       sap_banner_description,
       sap_banner_format_key,
       sap_banner_format_description,
       product_code,
	   ean,
       product_name,
       prod_hier_l1,
       prod_hier_l4,
       prod_hier_l5,
       prod_hier_l6,
       prod_hier_l9,
       mapped_sku_cd,
       sap_sku_code,
       sap_sku_description,
       sap_prod_sgmt_cd,
       sap_prod_sgmt_desc,
       sap_base_prod_desc,
       sap_mega_brnd_desc,
       sap_brnd_desc,
       sap_vrnt_desc,
       sap_put_up_desc,
       sap_grp_frnchse_cd,
       sap_grp_frnchse_desc,
       sap_frnchse_cd,
       sap_frnchse_desc,
       sap_prod_frnchse_cd,
       sap_prod_frnchse_desc,
       sap_prod_mjr_cd,
       sap_prod_mjr_desc,
       sap_prod_mnr_cd,
       sap_prod_mnr_desc,
       sap_prod_hier_cd,
       sap_prod_hier_desc,
       global_product_franchise,
       global_product_brand,
       global_product_sub_brand,
       global_product_variant,
       global_product_segment,
       global_product_subsegment,
       global_product_category,
       global_product_subcategory,
       global_put_up_description,
       pka_franchise_desc,
       pka_brand_desc,
       pka_sub_brand_desc,
       pka_variant_desc,
       pka_sub_variant_desc,
       pka_product_key,
       pka_product_key_description,
       sales_value,
       sales_qty,
       avg_sales_qty,
       sales_value_list_price,
       lm_sales,
       lm_sales_qty,
       lm_avg_sales_qty,
       lm_sales_lp,
       p3m_sales,
       p3m_qty,
       p3m_avg_qty,
       p3m_sales_lp,
       p6m_sales,
       p6m_qty,
       p6m_avg_qty,
       p6m_sales_lp,
       p12m_sales,
       p12m_qty,
       p12m_avg_qty,
       p12m_sales_lp,
       f3m_sales,
       f3m_qty,
       f3m_avg_qty,
       lm_sales_flag,
       p3m_sales_flag,
       p6m_sales_flag,
       p12m_sales_flag,
       mdp_flag,
       target_compliance,
       list_price,
       total_sales_lm,
       total_sales_p3m,
       total_sales_p6m,
       total_sales_p12m,
       total_sales_by_store_lm,
       total_sales_by_store_p3m,
       total_sales_by_store_p6m,
       total_sales_by_store_p12m,
       total_sales_by_sku_lm,
       total_sales_by_sku_p3m,
       total_sales_by_sku_p6m,
       total_sales_by_sku_p12m,
       total_sales_lm_lp,
       total_sales_p3m_lp,
       total_sales_p6m_lp,
       total_sales_p12m_lp,
       total_sales_by_store_lm_lp,
       total_sales_by_store_p3m_lp,
       total_sales_by_store_p6m_lp,
       total_sales_by_store_p12m_lp,
       total_sales_by_sku_lm_lp,
       total_sales_by_sku_p3m_lp,
       total_sales_by_sku_p6m_lp,
       total_sales_by_sku_p12m_lp,
       (total_sales_by_store_lm / nullif(total_sales_lm,0)) as store_contribution_lm,
       (total_sales_by_sku_lm / nullif(total_sales_lm,0)) as sku_contribution_lm,
       (store_contribution_lm*sku_contribution_lm*total_sales_lm) as size_of_price_lm,
       (total_sales_by_store_p3m / nullif(total_sales_p3m,0)) as store_contribution_p3m,
       (total_sales_by_sku_p3m / nullif(total_sales_p3m,0)) as sku_contribution_p3m,
       (store_contribution_p3m*sku_contribution_p3m*total_sales_p3m) as size_of_price_p3m,
       (total_sales_by_store_p6m / nullif(total_sales_p6m,0)) as store_contribution_p6m,
       (total_sales_by_sku_p6m / nullif(total_sales_p6m,0)) as sku_contribution_p6m,
       (store_contribution_p6m*sku_contribution_p6m*total_sales_p6m) as size_of_price_p6m,
       (total_sales_by_store_p12m / nullif(total_sales_p12m,0)) as store_contribution_p12m,
       (total_sales_by_sku_p12m / nullif(total_sales_p12m,0)) as sku_contribution_p12m,
       (store_contribution_p12m*sku_contribution_p12m*total_sales_p12m) as size_of_price_p12m,
       (total_sales_by_store_lm_lp / nullif(total_sales_lm_lp,0)) as store_contribution_lm_lp,
       (total_sales_by_sku_lm_lp / nullif(total_sales_lm_lp,0)) as sku_contribution_lm_lp,
       (store_contribution_lm_lp*sku_contribution_lm_lp*total_sales_lm_lp) as size_of_price_lm_lp,
       (total_sales_by_store_p3m_lp / nullif(total_sales_p3m_lp,0)) as store_contribution_p3m_lp,
       (total_sales_by_sku_p3m_lp / nullif(total_sales_p3m_lp,0)) as sku_contribution_p3m_lp,
       (store_contribution_p3m_lp*sku_contribution_p3m_lp*total_sales_p3m_lp) as size_of_price_p3m_lp,
       (total_sales_by_store_p6m_lp / nullif(total_sales_p6m_lp,0)) as store_contribution_p6m_lp,
       (total_sales_by_sku_p6m_lp / nullif(total_sales_p6m_lp,0)) as sku_contribution_p6m_lp,
       (store_contribution_p6m_lp*sku_contribution_p6m_lp*total_sales_p6m_lp) as size_of_price_p6m_lp,
       (total_sales_by_store_p12m_lp / nullif(total_sales_p12m_lp,0)) as store_contribution_p12m_lp,
       (total_sales_by_sku_p12m_lp / nullif(total_sales_p12m_lp,0)) as sku_contribution_p12m_lp,
       (store_contribution_p12m_lp*sku_contribution_p12m_lp*total_sales_p12m_lp) as size_of_price_p12m_lp,
       md5(distributor_code||nvl (sell_out_channel,'soc') ||nvl (sell_out_re,'soe') ||nvl (customer_segment_description,'csd') || nvl (sap_customer_channel_description,'sccd') ||nvl (sap_sub_channel_description,'sscd') ||nvl (sap_parent_customer_description,'spscd') || nvl (sap_banner_description,'sbd') || nvl (sap_banner_format_description,'sbfd')) as customer_agg_dim_key,
       md5(nvl (sap_base_prod_desc,'sbpd') || nvl (sap_mega_brnd_desc,'smbd') ||nvl (sap_brnd_desc,'sb') || nvl (sap_frnchse_desc,'sfd') || nvl (sap_prod_mjr_desc,'spmd') ||nvl (sap_prod_mnr_desc,'spm') 
       ||nvl (global_product_franchise,'gpf') || nvl (global_product_brand,'gpb') ||nvl (global_product_sub_brand,'gpsb') ||nvl (global_product_segment,'gps') || nvl (global_product_subsegment,'gpss') ||nvl (global_product_category,'gpc') ||nvl (global_product_subcategory,'gpsc') ||nvl (global_product_variant,'gpv') ||nvl (global_put_up_description,'gppu') || nvl (pka_franchise_desc,'pkaf') ||nvl (pka_brand_desc,'pkab') ||nvl (pka_sub_brand_desc,'pkasb') ||nvl (pka_variant_desc,'pkav') ||nvl (pka_sub_variant_desc,'pkasv') ||nvl (pka_product_key,'pkapk') ||nvl (pka_product_key_description,'pkapkd')) as product_agg_dim_key,
       sysdate() as created_date
from (select main.fisc_yr,
             main.fisc_per,
             main."cluster",
             main.market as market,
             main.data_src,
             main.soldto_code,
             main.distributor_code,
             main.distributor_name,
             main.sell_out_channel,
             main.sell_out_re,
             main.store_type as store_type,
             main.store_code,
             main.store_name,
             main.region,
             main.zone_name,
             main.city,
             main.customer_segment_key,
             main.customer_segment_description,
             main.sap_parent_customer_key,
             main.sap_parent_customer_description,
             main.sap_customer_channel_key,
             main.sap_customer_channel_description,
             main.sap_customer_sub_channel_key,
             main.sap_sub_channel_description,
             main.sap_go_to_mdl_key,
              main.sap_go_to_mdl_description,
             main.sap_banner_key,
             main.sap_banner_description,
             main.sap_banner_format_key,
             main.sap_banner_format_description,
             main.product_code as product_code,
             main.product_name as product_name,
			 main.ean as ean,
             main.prod_hier_l1,
             main.prod_hier_l4,
             main.prod_hier_l5,
             main.prod_hier_l6,
             main.prod_hier_l9,
             main.mapped_sku_cd,
            main.sap_sku_code,
             main.sap_sku_description,
             main.sap_prod_sgmt_cd,
             main.sap_prod_sgmt_desc,
             main.sap_base_prod_desc,
            main.sap_mega_brnd_desc,
             main.sap_brnd_desc,
             main.sap_vrnt_desc,
             main.sap_put_up_desc,
             main.sap_grp_frnchse_cd,
             main.sap_grp_frnchse_desc,
             main.sap_frnchse_cd,
             main.sap_frnchse_desc,
             main.sap_prod_frnchse_cd,
             main.sap_prod_frnchse_desc,
             main.sap_prod_mjr_cd,
             main.sap_prod_mjr_desc,
             main.sap_prod_mnr_cd,
             main.sap_prod_mnr_desc,
             main.sap_prod_hier_cd,
             main.sap_prod_hier_desc,
             main.global_product_franchise,
              main.global_product_brand,
              main.global_product_sub_brand,
              main.global_product_variant,
              main.global_product_segment,
              main.global_product_subsegment,
             main.global_product_category,
             main.global_product_subcategory,
            main.global_put_up_description,
            main.pka_franchise_desc,
              main.pka_brand_desc,
              main.pka_sub_brand_desc,
              main.pka_variant_desc,
             main.pka_sub_variant_desc,
              main.pka_product_key,
             main.pka_product_key_description,
             main.sales_value as sales_value,
             main.sales_qty as sales_qty,
             main.avg_sales_qty as avg_sales_qty,
             main.sales_value_list_price as sales_value_list_price,
             main.lm_sales as lm_sales,
             main.lm_sales_qty as lm_sales_qty,
             main.lm_avg_sales_qty as lm_avg_sales_qty,
             main.lm_sales_lp as lm_sales_lp,
             main.p3m_sales as p3m_sales,
             main.p3m_qty as p3m_qty,
             main.p3m_avg_qty as p3m_avg_qty,
             main.p3m_sales_lp as p3m_sales_lp,
             main.f3m_sales as f3m_sales,
             main.f3m_qty as f3m_qty,
             main.f3m_avg_qty as f3m_avg_qty,
             main.p6m_sales as p6m_sales,
             main.p6m_qty as p6m_qty,
             main.p6m_avg_qty as p6m_avg_qty,
             main.p6m_sales_lp as p6m_sales_lp,
             main.p12m_sales as p12m_sales,
             main.p12m_qty as p12m_qty,
             main.p12m_avg_qty as p12m_avg_qty,
             main.p12m_sales_lp as p12m_sales_lp,
             main.lm_sales_flag,
             main.p3m_sales_flag,
             main.p6m_sales_flag,
             main.p12m_sales_flag,
             main.mdp_flag,
             1 as target_compliance,
             lp.list_price,
             sum(main.lm_sales) over (partition by fisc_per,distributor_code,global_product_brand) as total_sales_lm,
             sum(main.p3m_sales) over (partition by fisc_per,distributor_code,global_product_brand) as total_sales_p3m,
             sum(main.p6m_sales) over (partition by fisc_per,distributor_code,global_product_brand) as total_sales_p6m,
             sum(main.p12m_sales) over (partition by fisc_per,distributor_code,global_product_brand) as total_sales_p12m,
             sum(main.lm_sales) over (partition by fisc_per,distributor_code,global_product_brand,store_code) as total_sales_by_store_lm,
             sum(main.p3m_sales) over (partition by fisc_per,distributor_code,global_product_brand,store_code) as total_sales_by_store_p3m,
             sum(main.p6m_sales) over (partition by fisc_per,distributor_code,global_product_brand,store_code) as total_sales_by_store_p6m,
             sum(main.p12m_sales) over (partition by fisc_per,distributor_code,global_product_brand,store_code) as total_sales_by_store_p12m,
             sum(main.lm_sales) over (partition by fisc_per,distributor_code,global_product_brand,product_code) as total_sales_by_sku_lm,
             sum(main.p3m_sales) over (partition by fisc_per,distributor_code,global_product_brand,product_code) as total_sales_by_sku_p3m,
             sum(main.p6m_sales) over (partition by fisc_per,distributor_code,global_product_brand,product_code) as total_sales_by_sku_p6m,
             sum(main.p12m_sales) over (partition by fisc_per,distributor_code,global_product_brand,product_code) as total_sales_by_sku_p12m,
             sum(main.lm_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand) as total_sales_lm_lp,
             sum(main.p3m_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand) as total_sales_p3m_lp,
             sum(main.p6m_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand) as total_sales_p6m_lp,
             sum(main.p12m_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand) as total_sales_p12m_lp,
             sum(main.lm_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand,store_code) as total_sales_by_store_lm_lp,
             sum(main.p3m_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand,store_code) as total_sales_by_store_p3m_lp,
             sum(main.p6m_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand,store_code) as total_sales_by_store_p6m_lp,
             sum(main.p12m_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand,store_code) as total_sales_by_store_p12m_lp,
             sum(main.lm_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand,product_code) as total_sales_by_sku_lm_lp,
             sum(main.p3m_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand,product_code) as total_sales_by_sku_p3m_lp,
             sum(main.p6m_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand,product_code) as total_sales_by_sku_p6m_lp,
             sum(main.p12m_sales_lp) over (partition by fisc_per,distributor_code,global_product_brand,product_code) as total_sales_by_sku_p12m_lp
      from wks_cnpc_rpt_retail_excellence main
      left join (select ltrim(edw_list_price.material,'0') as material,
                          edw_list_price.amount as list_price,
						  row_number() over (partition by ltrim(edw_list_price.material,'0') order by to_date(edw_list_price.valid_to,'yyyymmdd') desc,to_date(edw_list_price.dt_from,'yyyymmdd') desc) as rn
                   from edw_list_price
                   where edw_list_price.sls_org in ('1000','1500','1600','1700')) lp
     
              on ltrim (main.mapped_sku_cd,'0') = lp.material
              and rn = 1))
),

wks_cnpc_rpt_retail_excellence_sop_final as
(
 select fisc_yr	::	numeric(18,0)	as	fisc_yr	,
fisc_per	::	numeric(18,0)	as	fisc_per	,
"cluster"	::	varchar(100)	as	"cluster"	,
market	::	varchar(30)	as	market	,
data_src	::	varchar(14)	as	data_src	,
soldto_code	::	varchar(255)	as	soldto_code	,
distributor_code	::	varchar(100)	as	distributor_code	,
distributor_name	::	varchar(356)	as	distributor_name	,
sell_out_channel	::	varchar(11)	as	sell_out_channel	,
sell_out_re	::	varchar(382)	as	sell_out_re	,
store_type	::	varchar(382)	as	store_type	,
store_code	::	varchar(100)	as	store_code	,
store_name	::	varchar(601)	as	store_name	,
region	::	varchar(150)	as	region	,
zone_name	::	varchar(150)	as	zone_name	,
city	::	varchar(150)	as	city	,
customer_segment_key	::	varchar(12)	as	customer_segment_key	,
customer_segment_description	::	varchar(50)	as	customer_segment_description	,
sap_parent_customer_key	::	varchar(12)	as	sap_parent_customer_key	,
sap_parent_customer_description	::	varchar(75)	as	sap_parent_customer_description	,
sap_customer_channel_key	::	varchar(12)	as	sap_customer_channel_key	,
sap_customer_channel_description	::	varchar(75)	as	sap_customer_channel_description	,
sap_customer_sub_channel_key	::	varchar(12)	as	sap_customer_sub_channel_key	,
sap_sub_channel_description	::	varchar(75)	as	sap_sub_channel_description	,
sap_go_to_mdl_key	::	varchar(12)	as	sap_go_to_mdl_key	,
sap_go_to_mdl_description	::	varchar(75)	as	sap_go_to_mdl_description	,
sap_banner_key	::	varchar(12)	as	sap_banner_key	,
sap_banner_description	::	varchar(75)	as	sap_banner_description	,
sap_banner_format_key	::	varchar(12)	as	sap_banner_format_key	,
sap_banner_format_description	::	varchar(75)	as	sap_banner_format_description	,
product_code	::	varchar(200)	as	product_code	,
ean	::	varchar(50)	as	ean	,
product_name	::	varchar(300)	as	product_name	,
prod_hier_l1	::	varchar(19)	as	prod_hier_l1	,
prod_hier_l4	::	varchar(30)	as	prod_hier_l4	,
prod_hier_l5	::	varchar(300)	as	prod_hier_l5	,
prod_hier_l6	::	varchar(200)	as	prod_hier_l6	,
prod_hier_l9	::	varchar(100)	as	prod_hier_l9	,
mapped_sku_cd	::	varchar(40)	as	mapped_sku_cd	,
sap_sku_code	::	varchar(40)	as	sap_sku_code	,
sap_sku_description	::	varchar(100)	as	sap_sku_description	,
sap_prod_sgmt_cd	::	varchar(18)	as	sap_prod_sgmt_cd	,
sap_prod_sgmt_desc	::	varchar(100)	as	sap_prod_sgmt_desc	,
sap_base_prod_desc	::	varchar(100)	as	sap_base_prod_desc	,
sap_mega_brnd_desc	::	varchar(100)	as	sap_mega_brnd_desc	,
sap_brnd_desc	::	varchar(100)	as	sap_brnd_desc	,
sap_vrnt_desc	::	varchar(100)	as	sap_vrnt_desc	,
sap_put_up_desc	::	varchar(100)	as	sap_put_up_desc	,
sap_grp_frnchse_cd	::	varchar(18)	as	sap_grp_frnchse_cd	,
sap_grp_frnchse_desc	::	varchar(100)	as	sap_grp_frnchse_desc	,
sap_frnchse_cd	::	varchar(18)	as	sap_frnchse_cd	,
sap_frnchse_desc	::	varchar(100)	as	sap_frnchse_desc	,
sap_prod_frnchse_cd	::	varchar(18)	as	sap_prod_frnchse_cd	,
sap_prod_frnchse_desc	::	varchar(100)	as	sap_prod_frnchse_desc	,
sap_prod_mjr_cd	::	varchar(18)	as	sap_prod_mjr_cd	,
sap_prod_mjr_desc	::	varchar(100)	as	sap_prod_mjr_desc	,
sap_prod_mnr_cd	::	varchar(18)	as	sap_prod_mnr_cd	,
sap_prod_mnr_desc	::	varchar(100)	as	sap_prod_mnr_desc	,
sap_prod_hier_cd	::	varchar(18)	as	sap_prod_hier_cd	,
sap_prod_hier_desc	::	varchar(100)	as	sap_prod_hier_desc	,
global_product_franchise	::	varchar(30)	as	global_product_franchise	,
global_product_brand	::	varchar(30)	as	global_product_brand	,
global_product_sub_brand	::	varchar(100)	as	global_product_sub_brand	,
global_product_variant	::	varchar(100)	as	global_product_variant	,
global_product_segment	::	varchar(50)	as	global_product_segment	,
global_product_subsegment	::	varchar(100)	as	global_product_subsegment	,
global_product_category	::	varchar(50)	as	global_product_category	,
global_product_subcategory	::	varchar(50)	as	global_product_subcategory	,
global_put_up_description	::	varchar(100)	as	global_put_up_description	,
pka_franchise_desc	::	varchar(30)	as	pka_franchise_desc	,
pka_brand_desc	::	varchar(30)	as	pka_brand_desc	,
pka_sub_brand_desc	::	varchar(30)	as	pka_sub_brand_desc	,
pka_variant_desc	::	varchar(30)	as	pka_variant_desc	,
pka_sub_variant_desc	::	varchar(30)	as	pka_sub_variant_desc	,
pka_product_key	::	varchar(68)	as	pka_product_key	,
pka_product_key_description	::	varchar(382)	as	pka_product_key_description	,
sales_value	::	numeric(38,6)	as	sales_value	,
sales_qty	::	numeric(38,6)	as	sales_qty	,
avg_sales_qty	::	numeric(38,6)	as	avg_sales_qty	,
sales_value_list_price	::	numeric(38,12)	as	sales_value_list_price	,
lm_sales	::	numeric(38,6)	as	lm_sales	,
lm_sales_qty	::	numeric(38,6)	as	lm_sales_qty	,
lm_avg_sales_qty	::	numeric(38,6)	as	lm_avg_sales_qty	,
lm_sales_lp	::	numeric(38,12)	as	lm_sales_lp	,
p3m_sales	::	numeric(38,6)	as	p3m_sales	,
p3m_qty	::	numeric(38,6)	as	p3m_qty	,
p3m_avg_qty	::	numeric(38,6)	as	p3m_avg_qty	,
p3m_sales_lp	::	numeric(38,12)	as	p3m_sales_lp	,
p6m_sales	::	numeric(38,6)	as	p6m_sales	,
p6m_qty	::	numeric(38,6)	as	p6m_qty	,
p6m_avg_qty	::	numeric(38,6)	as	p6m_avg_qty	,
p6m_sales_lp	::	numeric(38,12)	as	p6m_sales_lp	,
p12m_sales	::	numeric(38,6)	as	p12m_sales	,
p12m_qty	::	numeric(38,6)	as	p12m_qty	,
p12m_avg_qty	::	numeric(38,6)	as	p12m_avg_qty	,
p12m_sales_lp	::	numeric(38,12)	as	p12m_sales_lp	,
f3m_sales	::	numeric(38,6)	as	f3m_sales	,
f3m_qty	::	numeric(38,6)	as	f3m_qty	,
f3m_avg_qty	::	numeric(38,6)	as	f3m_avg_qty	,
lm_sales_flag	::	varchar(1)	as	lm_sales_flag	,
p3m_sales_flag	::	varchar(1)	as	p3m_sales_flag	,
p6m_sales_flag	::	varchar(1)	as	p6m_sales_flag	,
p12m_sales_flag	::	varchar(1)	as	p12m_sales_flag	,
mdp_flag	::	varchar(1)	as	mdp_flag	,
target_compliance	::	numeric(18,0)	as	target_compliance	,
list_price	::	numeric(20,4)	as	list_price	,
total_sales_lm	::	numeric(38,6)	as	total_sales_lm	,
total_sales_p3m	::	numeric(38,6)	as	total_sales_p3m	,
total_sales_p6m	::	numeric(38,6)	as	total_sales_p6m	,
total_sales_p12m	::	numeric(38,6)	as	total_sales_p12m	,
total_sales_by_store_lm	::	numeric(38,6)	as	total_sales_by_store_lm	,
total_sales_by_store_p3m	::	numeric(38,6)	as	total_sales_by_store_p3m	,
total_sales_by_store_p6m	::	numeric(38,6)	as	total_sales_by_store_p6m	,
total_sales_by_store_p12m	::	numeric(38,6)	as	total_sales_by_store_p12m	,
total_sales_by_sku_lm	::	numeric(38,6)	as	total_sales_by_sku_lm	,
total_sales_by_sku_p3m	::	numeric(38,6)	as	total_sales_by_sku_p3m	,
total_sales_by_sku_p6m	::	numeric(38,6)	as	total_sales_by_sku_p6m	,
total_sales_by_sku_p12m	::	numeric(38,6)	as	total_sales_by_sku_p12m	,
total_sales_lm_lp	::	numeric(38,12)	as	total_sales_lm_lp	,
total_sales_p3m_lp	::	numeric(38,12)	as	total_sales_p3m_lp	,
total_sales_p6m_lp	::	numeric(38,12)	as	total_sales_p6m_lp	,
total_sales_p12m_lp	::	numeric(38,12)	as	total_sales_p12m_lp	,
total_sales_by_store_lm_lp	::	numeric(38,12)	as	total_sales_by_store_lm_lp	,
total_sales_by_store_p3m_lp	::	numeric(38,12)	as	total_sales_by_store_p3m_lp	,
total_sales_by_store_p6m_lp	::	numeric(38,12)	as	total_sales_by_store_p6m_lp	,
total_sales_by_store_p12m_lp	::	numeric(38,12)	as	total_sales_by_store_p12m_lp	,
total_sales_by_sku_lm_lp	::	numeric(38,12)	as	total_sales_by_sku_lm_lp	,
total_sales_by_sku_p3m_lp	::	numeric(38,12)	as	total_sales_by_sku_p3m_lp	,
total_sales_by_sku_p6m_lp	::	numeric(38,12)	as	total_sales_by_sku_p6m_lp	,
total_sales_by_sku_p12m_lp	::	numeric(38,12)	as	total_sales_by_sku_p12m_lp	,
store_contribution_lm	::	numeric(38,4)	as	store_contribution_lm	,
sku_contribution_lm	::	numeric(38,4)	as	sku_contribution_lm	,
size_of_price_lm	::	numeric(38,14)	as	size_of_price_lm	,
store_contribution_p3m	::	numeric(38,4)	as	store_contribution_p3m	,
sku_contribution_p3m	::	numeric(38,4)	as	sku_contribution_p3m	,
size_of_price_p3m	::	numeric(38,14)	as	size_of_price_p3m	,
store_contribution_p6m	::	numeric(38,4)	as	store_contribution_p6m	,
sku_contribution_p6m	::	numeric(38,4)	as	sku_contribution_p6m	,
size_of_price_p6m	::	numeric(38,14)	as	size_of_price_p6m	,
store_contribution_p12m	::	numeric(38,4)	as	store_contribution_p12m	,
sku_contribution_p12m	::	numeric(38,4)	as	sku_contribution_p12m	,
size_of_price_p12m	::	numeric(38,14)	as	size_of_price_p12m	,
store_contribution_lm_lp	::	numeric(38,4)	as	store_contribution_lm_lp	,
sku_contribution_lm_lp	::	numeric(38,4)	as	sku_contribution_lm_lp	,
size_of_price_lm_lp	::	numeric(38,20)	as	size_of_price_lm_lp	,
store_contribution_p3m_lp	::	numeric(38,4)	as	store_contribution_p3m_lp	,
sku_contribution_p3m_lp	::	numeric(38,4)	as	sku_contribution_p3m_lp	,
size_of_price_p3m_lp	::	numeric(38,20)	as	size_of_price_p3m_lp	,
store_contribution_p6m_lp	::	numeric(38,4)	as	store_contribution_p6m_lp	,
sku_contribution_p6m_lp	::	numeric(38,4)	as	sku_contribution_p6m_lp	,
size_of_price_p6m_lp	::	numeric(38,20)	as	size_of_price_p6m_lp	,
store_contribution_p12m_lp	::	numeric(38,4)	as	store_contribution_p12m_lp	,
sku_contribution_p12m_lp	::	numeric(38,4)	as	sku_contribution_p12m_lp	,
size_of_price_p12m_lp	::	numeric(38,20)	as	size_of_price_p12m_lp	,
customer_agg_dim_key	::	varchar(32)	as	customer_agg_dim_key	,
product_agg_dim_key	::	varchar(32)	as	product_agg_dim_key	,
created_date ::	timestamp without time zone	as	created_date	
from wks_cnpc_rpt_retail_excellence_sop
)

select * from wks_cnpc_rpt_retail_excellence_sop_final