with itg_kr_re_msl_list as (
    select * from {{ ref('natwks_integration__wks_itg_kr_re_msl_list') }}
),
wks_korea_regional_sellout_actuals as (
    select * from {{ ref('nawks_integration__wks_korea_regional_sellout_actuals') }}
),

customer_heirarchy as (
    select * from {{ ref('aspedw_integration__edw_generic_customer_hierarchy') }}
),

product_heirarchy as (
    select * from {{ ref('aspedw_integration__edw_generic_product_hierarchy') }}
),

product_key_attribute as (
    select * from {{ ref('aspedw_integration__edw_generic_product_key_attributes') }}
),
edw_company_dim as (
    select * from {{ source('aspedw_integration','edw_company_dim') }}
),
itg_mds_sg_customer_hierarchy as (
    select * from {{ source('sgpitg_integration','itg_mds_sg_customer_hierarchy') }}
),
edw_vw_pop6_products as (
    select * from {{ source('ntaedw_integration','edw_vw_pop6_products') }}
),
v_rpt_pop6_perfectstore as (
    select * from {{ source('ntaedw_integration','v_rpt_pop6_perfectstore') }}
),

edw_list_price as (
    select * from {{ ref('aspedw_integration__edw_list_price') }}
),

edw_customer_sales_dim as (
    select * from {{ ref('aspedw_integration__edw_customer_sales_dim') }}
),

EDW_GCH_CUSTOMERHIERARCHY as(
    select * from {{ ref('aspedw_integration__edw_gch_customerhierarchy') }}
),
EDW_CUSTOMER_BASE_DIM as(
    select * from {{ ref('aspedw_integration__edw_customer_base_dim') }}
),

EDW_DSTRBTN_CHNL as(
    select * from {{ ref('aspedw_integration__edw_dstrbtn_chnl') }}
),

EDW_SALES_ORG_DIM as(
    select * from {{ ref('aspedw_integration__edw_sales_org_dim') }}
),

EDW_CODE_DESCRIPTIONS as(
    select * from {{ ref('aspedw_integration__edw_code_descriptions') }}
),

EDW_SUBCHNL_RETAIL_ENV_MAPPING as(
    select * from {{ source('aspedw_integration', 'edw_subchnl_retail_env_mapping') }}
),

EDW_CODE_DESCRIPTIONS_MANUAL as(
    select * from {{ source('aspedw_integration', 'edw_code_descriptions_manual') }}
),
kr_rpt_retail_excellence_mdp  as (
SELECT DISTINCT MDP.*,		--// SELECT DISTINCT MDP.*,
       COM.*,		--//        COM.*,
SYSDATE() as crtd_dttm		--// SYSDATE
FROM (
SELECT TARGET.FISC_YR :: numeric(18,0)  AS FISC_YR,		--// numeric(18,0) // SELECT CAST(TARGET.FISC_YR AS numeric(18,0) ) AS FISC_YR,		--// INTEGER  // SELECT CAST(TARGET.FISC_YR AS numeric(18,0) ) AS FISC_YR,		--// numeric(18,0) // SELECT CAST(TARGET.FISC_YR AS numeric(18,0) ) AS FISC_YR,
             TARGET.FISC_PER :: numeric(18,0) AS FISC_PER,		--// numeric(18,0) //              CAST(TARGET.FISC_PER AS numeric(18,0) ) AS FISC_PER,		--// INTEGER  //              CAST(TARGET.FISC_PER AS numeric(18,0) ) AS FISC_PER,		--// numeric(18,0) //              CAST(TARGET.FISC_PER AS numeric(18,0) ) AS FISC_PER,
			 COALESCE(ACTUAL.CNTRY_NM, 'Korea') AS MARKET,		--// 			 COALESCE(ACTUAL.CNTRY_NM, 'Korea') AS MARKET,		--// 			 COALESCE(ACTUAL.CNTRY_NM, 'Korea') AS MARKET,		--// 			 COALESCE(ACTUAL.CNTRY_NM, 'Korea') AS MARKET,
			 COALESCE(ACTUAL.DATA_SOURCE, TARGET.DATA_SOURCE) AS DATA_SRC,		--// 			 COALESCE(ACTUAL.DATA_SOURCE, TARGET.DATA_SOURCE) AS DATA_SRC,		--// 			 COALESCE(ACTUAL.DATA_SOURCE, TARGET.DATA_SOURCE) AS DATA_SRC,		--// 			 COALESCE(ACTUAL.DATA_SOURCE, TARGET.DATA_SOURCE) AS DATA_SRC,
             UPPER(COALESCE(ACTUAL.CHANNEL, TARGET.CHANNEL_DESC)) AS CHANNEL_NAME,		--//              UPPER(COALESCE(ACTUAL.CHANNEL, TARGET.CHANNEL_DESC)) AS CHANNEL_NAME,		--//              UPPER(COALESCE(ACTUAL.CHANNEL, TARGET.CHANNEL_DESC)) AS CHANNEL_NAME,		--//              UPPER(COALESCE(ACTUAL.CHANNEL, TARGET.CHANNEL_DESC)) AS CHANNEL_NAME,
             UPPER(COALESCE(ACTUAL.SOLD_TO_CODE, TARGET.SOLD_TO_CODE)) AS SOLD_TO_CODE,		--//              UPPER(COALESCE(ACTUAL.SOLD_TO_CODE, TARGET.SOLD_TO_CODE)) AS SOLD_TO_CODE,		--//              UPPER(COALESCE(ACTUAL.SOLD_TO_CODE, TARGET.SOLD_TO_CODE)) AS SOLD_TO_CODE,		--//              UPPER(COALESCE(ACTUAL.SOLD_TO_CODE, TARGET.SOLD_TO_CODE)) AS SOLD_TO_CODE,
             UPPER(COALESCE(ACTUAL.DISTRIBUTOR_CODE, TARGET.DISTRIBUTOR_CODE)) AS DISTRIBUTOR_CODE,		--//              UPPER(COALESCE(ACTUAL.DISTRIBUTOR_CODE, TARGET.DISTRIBUTOR_CODE)) AS DISTRIBUTOR_CODE,		--//              UPPER(COALESCE(ACTUAL.DISTRIBUTOR_CODE, TARGET.DISTRIBUTOR_CODE)) AS DISTRIBUTOR_CODE,		--//              UPPER(COALESCE(ACTUAL.DISTRIBUTOR_CODE, TARGET.DISTRIBUTOR_CODE)) AS DISTRIBUTOR_CODE,
			 UPPER(COALESCE(ACTUAL.DISTRIBUTOR_NAME, TARGET.DISTRIBUTOR_NAME)) AS DISTRIBUTOR_NAME,		--// 			 UPPER(COALESCE(ACTUAL.DISTRIBUTOR_NAME, TARGET.DISTRIBUTOR_NAME)) AS DISTRIBUTOR_NAME,		--// 			 UPPER(COALESCE(ACTUAL.DISTRIBUTOR_NAME, TARGET.DISTRIBUTOR_NAME)) AS DISTRIBUTOR_NAME,		--// 			 UPPER(COALESCE(ACTUAL.DISTRIBUTOR_NAME, TARGET.DISTRIBUTOR_NAME)) AS DISTRIBUTOR_NAME,
             UPPER(COALESCE(ACTUAL.CHANNEL, TARGET.CHANNEL_DESC)) AS SELL_OUT_CHANNEL,		--//              UPPER(COALESCE(ACTUAL.CHANNEL, TARGET.CHANNEL_DESC)) AS SELL_OUT_CHANNEL,		--//              UPPER(COALESCE(ACTUAL.CHANNEL, TARGET.CHANNEL_DESC)) AS SELL_OUT_CHANNEL,		--//              UPPER(COALESCE(ACTUAL.CHANNEL, TARGET.CHANNEL_DESC)) AS SELL_OUT_CHANNEL,
			 UPPER(COALESCE(ACTUAL.RETAIL_ENVIRONMENT, TARGET.RETAIL_ENVIRONMENT)) AS RETAIL_ENVIRONMENT,		--// 			 UPPER(COALESCE(ACTUAL.RETAIL_ENVIRONMENT, TARGET.RETAIL_ENVIRONMENT)) AS RETAIL_ENVIRONMENT,		--// 			 UPPER(COALESCE(ACTUAL.RETAIL_ENVIRONMENT, TARGET.RETAIL_ENVIRONMENT)) AS RETAIL_ENVIRONMENT,		--// 			 UPPER(COALESCE(ACTUAL.RETAIL_ENVIRONMENT, TARGET.RETAIL_ENVIRONMENT)) AS RETAIL_ENVIRONMENT,
             UPPER(COALESCE(ACTUAL.STORE_CODE, TARGET.STORE_CODE)) AS STORE_CODE,		--//              UPPER(COALESCE(ACTUAL.STORE_CODE, TARGET.STORE_CODE)) AS STORE_CODE,		--//              UPPER(COALESCE(ACTUAL.STORE_CODE, TARGET.STORE_CODE)) AS STORE_CODE,		--//              UPPER(COALESCE(ACTUAL.STORE_CODE, TARGET.STORE_CODE)) AS STORE_CODE,
             UPPER(COALESCE(ACTUAL.STORE_NAME, TARGET.STORE_NAME)) AS STORE_NAME,		--//              UPPER(COALESCE(ACTUAL.STORE_NAME, TARGET.STORE_NAME)) AS STORE_NAME,		--//              UPPER(COALESCE(ACTUAL.STORE_NAME, TARGET.STORE_NAME)) AS STORE_NAME,		--//              UPPER(COALESCE(ACTUAL.STORE_NAME, TARGET.STORE_NAME)) AS STORE_NAME,
             UPPER(COALESCE(ACTUAL.STORE_TYPE, 'NA')) AS STORE_TYPE,		--//              UPPER(COALESCE(ACTUAL.STORE_TYPE, 'NA')) AS STORE_TYPE,		--//              UPPER(COALESCE(ACTUAL.STORE_TYPE, 'NA')) AS STORE_TYPE,		--//              UPPER(COALESCE(ACTUAL.STORE_TYPE, 'NA')) AS STORE_TYPE,
             ACTUAL.STORE_GRADE AS STORE_GRADE,		--//              ACTUAL.STORE_GRADE AS STORE_GRADE,		--//              ACTUAL.STORE_GRADE AS STORE_GRADE,		--//              ACTUAL.STORE_GRADE AS STORE_GRADE,
             --RETAILER.CLASS_DESC AS STORE_SIZE,
			 ACTUAL.REGION AS REGION,		--// 			 ACTUAL.REGION AS REGION,		--// 			 ACTUAL.REGION AS REGION,		--// 			 ACTUAL.REGION AS REGION,
             --TARGET.STORE_ADDRESS,
             --TARGET.STORE_POSTCODE AS POST_CODE,
             ACTUAL.ZONE_OR_AREA AS ZONE_NAME,		--//              ACTUAL.ZONE_OR_AREA AS ZONE_NAME,		--//              ACTUAL.ZONE_OR_AREA AS ZONE_NAME,		--//              ACTUAL.ZONE_OR_AREA AS ZONE_NAME,
             --TARGET.CITY AS CITY,
             --RETAILER.RTRLATITUDE AS RTRLATITUDE,
             --RETAILER.RTRLONGITUDE AS RTRLONGITUDE,
			 /*TARGET.MASTER_CODE AS PRODUCT_CODE,		--// 			 /*TARGET.MASTER_CODE AS PRODUCT_CODE,		--// 			 /*TARGET.MASTER_CODE AS PRODUCT_CODE,		--// 			 /*TARGET.master_code AS PRODUCT_CODE,
             ACTUAL.MASTER_CODE_DESC AS PRODUCT_NAME,*/		--//              ACTUAL.MASTER_CODE_DESC AS PRODUCT_NAME,*/		--//              ACTUAL.MASTER_CODE_DESC AS PRODUCT_NAME,*/		--//              ACTUAL.MASTER_CODE_DESC AS PRODUCT_NAME,*/
			 UPPER(COALESCE(ACTUAL.EAN, TARGET.EAN)) AS PRODUCT_CODE,		--// 			 UPPER(COALESCE(ACTUAL.EAN, TARGET.EAN)) AS PRODUCT_CODE,		--// 			 UPPER(COALESCE(ACTUAL.EAN, TARGET.EAN)) AS PRODUCT_CODE,		--// 			 UPPER(COALESCE(ACTUAL.EAN, TARGET.EAN)) AS PRODUCT_CODE,
			 UPPER(COALESCE(ACTUAL.SKU_DESCRIPTION, TARGET.SKU_DESCRIPTION)) AS PRODUCT_NAME,		--// 			 UPPER(COALESCE(ACTUAL.SKU_DESCRIPTION, TARGET.SKU_DESCRIPTION)) AS PRODUCT_NAME,		--// 			 UPPER(COALESCE(ACTUAL.SKU_DESCRIPTION, TARGET.SKU_DESCRIPTION)) AS PRODUCT_NAME,		--// 			 UPPER(COALESCE(ACTUAL.SKU_DESCRIPTION, TARGET.SKU_DESCRIPTION)) AS PRODUCT_NAME,
			 --ACTUAL.SKU_DESCRIPTION AS PRODUCT_NAME,
             --TRIM(COALESCE(ACTUAL.EAN, TARGET.EAN)) AS EAN,
             POP.PROD_HIER_L1,		--//              POP.PROD_HIER_L1,		--//              POP.PROD_HIER_L1,		--//              POP.PROD_HIER_L1,
             POP.PROD_HIER_L2,		--//              POP.PROD_HIER_L2,		--//              POP.PROD_HIER_L2,		--//              POP.PROD_HIER_L2,
             POP.PROD_HIER_L3,		--//              POP.PROD_HIER_L3,		--//              POP.PROD_HIER_L3,		--//              POP.PROD_HIER_L3,
             POP.PROD_HIER_L4,		--//              POP.PROD_HIER_L4,		--//              POP.PROD_HIER_L4,		--//              POP.PROD_HIER_L4,
             POP.PROD_HIER_L5,		--//              POP.PROD_HIER_L5,		--//              POP.PROD_HIER_L5,		--//              POP.PROD_HIER_L5,
             POP.PROD_HIER_L6,		--//              POP.PROD_HIER_L6,		--//              POP.PROD_HIER_L6,		--//              POP.PROD_HIER_L6,
             POP.PROD_HIER_L7,		--//              POP.PROD_HIER_L7,		--//              POP.PROD_HIER_L7,		--//              POP.PROD_HIER_L7,
             POP.PROD_HIER_L8,		--//              POP.PROD_HIER_L8,		--//              POP.PROD_HIER_L8,		--//              POP.PROD_HIER_L8,
             POP.PROD_HIER_L9,		--//              POP.PROD_HIER_L9,		--//              POP.PROD_HIER_L9,		--//              POP.PROD_HIER_L9,
             UPPER(COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE)) AS MAPPED_SKU_CD,		--//              UPPER(COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE)) AS MAPPED_SKU_CD,		--//              UPPER(COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE)) AS MAPPED_SKU_CD,		--//              UPPER(COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE)) AS MAPPED_SKU_CD,
             COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,
             COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,
             --COALESCE(ACTUAL.STORE_TYPE) AS RETAIL_ENVIRONMENT,
             COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,
             COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,
             COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,
             COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,
             COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,
             COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,
             COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,
             COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,
             COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,
             TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,
             TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,
             COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,		--//              COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,		--//              COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,		--//              COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,
             --TRIM(NVL (NULLIF(PRODUCT.EAN,''),'NA')) AS EAN,
             --TRIM(NVL (NULLIF(PRODUCT.SAP_MATL_NUM,''),'NA')) AS SKU_CODE,
             --TRIM(NVL (NULLIF(PRODUCT.SAP_MAT_DESC,''),'NA')) AS SKU_DESCRIPTION,
             TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,
             TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,
             TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,
             TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,
             TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,
             --COALESCE(ACTUAL.PKA_PRODUCT_KEY,PRODUCT.PKA_PRODUCT_KEY) AS PKA_PRODUCT_KEY,
             --COALESCE(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION) AS PKA_PRODUCT_KEY_DESCRIPTION,
			 CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA'))		--// 			 CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA'))		--// 			 CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA'))		--// 			 CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA'))
			 WHEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productkey,''),'NA'))
			 WHEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productkey,''),'NA'))
			 ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY,''),'NA')) END AS PKA_PRODUCT_KEY,		--// 			 ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY,''),'NA')) END AS PKA_PRODUCT_KEY,		--// 			 ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY,''),'NA')) END AS PKA_PRODUCT_KEY,		--// 			 ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY,''),'NA')) END AS PKA_PRODUCT_KEY,
			 CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA'))		--// 			 CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA'))		--// 			 CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA'))		--// 			 CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA'))
			 WHEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productdesc,''),'NA'))
			 WHEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productdesc,''),'NA'))
			 ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA')) END AS PKA_PRODUCT_KEY_DESCRIPTION,		--// 			 ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA')) END AS PKA_PRODUCT_KEY_DESCRIPTION,		--// 			 ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA')) END AS PKA_PRODUCT_KEY_DESCRIPTION,		--// 			 ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA')) END AS PKA_PRODUCT_KEY_DESCRIPTION,
             ACTUAL.CM_SALES AS SALES_VALUE,		--//              ACTUAL.CM_SALES AS SALES_VALUE,		--//              ACTUAL.CM_SALES AS SALES_VALUE,		--//              ACTUAL.CM_SALES AS SALES_VALUE,
             ACTUAL.CM_SALES_QTY AS SALES_QTY,		--//              ACTUAL.CM_SALES_QTY AS SALES_QTY,		--//              ACTUAL.CM_SALES_QTY AS SALES_QTY,		--//              ACTUAL.CM_SALES_QTY AS SALES_QTY,
             ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,		--//              ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,		--//              ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,		--//              ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,
             ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,		--//              ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,		--//              ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,		--//              ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,
             ACTUAL.LM_SALES AS LM_SALES,		--//              ACTUAL.LM_SALES AS LM_SALES,		--//              ACTUAL.LM_SALES AS LM_SALES,		--//              ACTUAL.LM_SALES AS LM_SALES,
             ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,		--//              ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,		--//              ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,		--//              ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,
             ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,		--//              ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,		--//              ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,		--//              ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,
             ACTUAL.LM_SALES_LP AS LM_SALES_LP,		--//              ACTUAL.LM_SALES_LP AS LM_SALES_LP,		--//              ACTUAL.LM_SALES_LP AS LM_SALES_LP,		--//              ACTUAL.LM_SALES_LP AS LM_SALES_LP,
             ACTUAL.P3M_SALES AS P3M_SALES,		--//              ACTUAL.P3M_SALES AS P3M_SALES,		--//              ACTUAL.P3M_SALES AS P3M_SALES,		--//              ACTUAL.P3M_SALES AS P3M_SALES,
             ACTUAL.P3M_QTY AS P3M_QTY,		--//              ACTUAL.P3M_QTY AS P3M_QTY,		--//              ACTUAL.P3M_QTY AS P3M_QTY,		--//              ACTUAL.P3M_QTY AS P3M_QTY,
             ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,		--//              ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,		--//              ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,		--//              ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,
             ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,		--//              ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,		--//              ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,		--//              ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,
             ACTUAL.F3M_SALES AS F3M_SALES,		--//              ACTUAL.F3M_SALES AS F3M_SALES,		--//              ACTUAL.F3M_SALES AS F3M_SALES,		--//              ACTUAL.F3M_SALES AS F3M_SALES,
             ACTUAL.F3M_QTY AS F3M_QTY,		--//              ACTUAL.F3M_QTY AS F3M_QTY,		--//              ACTUAL.F3M_QTY AS F3M_QTY,		--//              ACTUAL.F3M_QTY AS F3M_QTY,
             ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,		--//              ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,		--//              ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,		--//              ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,
             ACTUAL.P6M_SALES AS P6M_SALES,		--//              ACTUAL.P6M_SALES AS P6M_SALES,		--//              ACTUAL.P6M_SALES AS P6M_SALES,		--//              ACTUAL.P6M_SALES AS P6M_SALES,
             ACTUAL.P6M_QTY AS P6M_QTY,		--//              ACTUAL.P6M_QTY AS P6M_QTY,		--//              ACTUAL.P6M_QTY AS P6M_QTY,		--//              ACTUAL.P6M_QTY AS P6M_QTY,
             ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,		--//              ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,		--//              ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,		--//              ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,
             ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,		--//              ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,		--//              ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,		--//              ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,
             ACTUAL.P12M_SALES AS P12M_SALES,		--//              ACTUAL.P12M_SALES AS P12M_SALES,		--//              ACTUAL.P12M_SALES AS P12M_SALES,		--//              ACTUAL.P12M_SALES AS P12M_SALES,
             ACTUAL.P12M_QTY AS P12M_QTY,		--//              ACTUAL.P12M_QTY AS P12M_QTY,		--//              ACTUAL.P12M_QTY AS P12M_QTY,		--//              ACTUAL.P12M_QTY AS P12M_QTY,
             ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,		--//              ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,		--//              ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,		--//              ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,
             ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,		--//              ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,		--//              ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,		--//              ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,
             COALESCE(ACTUAL.LM_SALES_FLAG,'N') AS LM_SALES_FLAG,		--//              COALESCE(ACTUAL.LM_SALES_FLAG,'N') AS LM_SALES_FLAG,		--//              COALESCE(ACTUAL.LM_SALES_FLAG,'N') AS LM_SALES_FLAG,		--//              COALESCE(ACTUAL.LM_SALES_FLAG,'N') AS LM_SALES_FLAG,
             COALESCE(ACTUAL.P3M_SALES_FLAG,'N') AS P3M_SALES_FLAG,		--//              COALESCE(ACTUAL.P3M_SALES_FLAG,'N') AS P3M_SALES_FLAG,		--//              COALESCE(ACTUAL.P3M_SALES_FLAG,'N') AS P3M_SALES_FLAG,		--//              COALESCE(ACTUAL.P3M_SALES_FLAG,'N') AS P3M_SALES_FLAG,
             COALESCE(ACTUAL.P6M_SALES_FLAG,'N') AS P6M_SALES_FLAG,		--//              COALESCE(ACTUAL.P6M_SALES_FLAG,'N') AS P6M_SALES_FLAG,		--//              COALESCE(ACTUAL.P6M_SALES_FLAG,'N') AS P6M_SALES_FLAG,		--//              COALESCE(ACTUAL.P6M_SALES_FLAG,'N') AS P6M_SALES_FLAG,
             COALESCE(ACTUAL.P12M_SALES_FLAG,'N') AS P12M_SALES_FLAG,		--//              COALESCE(ACTUAL.P12M_SALES_FLAG,'N') AS P12M_SALES_FLAG,		--//              COALESCE(ACTUAL.P12M_SALES_FLAG,'N') AS P12M_SALES_FLAG,		--//              COALESCE(ACTUAL.P12M_SALES_FLAG,'N') AS P12M_SALES_FLAG,
             'Y' AS MDP_FLAG,
             100 AS TARGET_COMPLAINCE
		FROM ITG_KR_RE_MSL_LIST TARGET
        LEFT JOIN (SELECT * FROM WKS_KOREA_REGIONAL_SELLOUT_ACTUALS) ACTUAL		--//         LEFT JOIN (SELECT * FROM NA_WKS.WKS_KOREA_REGIONAL_SELLOUT_ACTUALS) ACTUAL		--//         LEFT JOIN (SELECT * FROM WKS_KOREA_REGIONAL_SELLOUT_ACTUALS) ACTUAL		--//         LEFT JOIN (SELECT * FROM NA_WKS.WKS_KOREA_REGIONAL_SELLOUT_ACTUALS) ACTUAL
               ON TARGET.FISC_PER = ACTUAL.MNTH_ID		--//                ON TARGET.FISC_PER = ACTUAL.MNTH_ID		--//                ON TARGET.FISC_PER = ACTUAL.MNTH_ID		--//                ON TARGET.FISC_PER = ACTUAL.MNTH_ID
               AND UPPER(TARGET.STORE_CODE) = UPPER(ACTUAL.STORE_CODE)		--//                AND UPPER(TARGET.STORE_CODE) = UPPER(ACTUAL.STORE_CODE)		--//                AND UPPER(TARGET.STORE_CODE) = UPPER(ACTUAL.STORE_CODE)		--//                AND UPPER(TARGET.STORE_CODE) = UPPER(ACTUAL.STORE_CODE)
               AND UPPER(TARGET.DISTRIBUTOR_CODE) = UPPER(ACTUAL.DISTRIBUTOR_CODE)		--//                AND UPPER(TARGET.DISTRIBUTOR_CODE) = UPPER(ACTUAL.DISTRIBUTOR_CODE)		--//                AND UPPER(TARGET.DISTRIBUTOR_CODE) = UPPER(ACTUAL.DISTRIBUTOR_CODE)		--//                AND UPPER(TARGET.DISTRIBUTOR_CODE) = UPPER(ACTUAL.DISTRIBUTOR_CODE)
               AND UPPER(TARGET.SOLD_TO_CODE) = UPPER(ACTUAL.SOLD_TO_CODE)		--//                AND UPPER(TARGET.SOLD_TO_CODE) = UPPER(ACTUAL.SOLD_TO_CODE)		--//                AND UPPER(TARGET.SOLD_TO_CODE) = UPPER(ACTUAL.SOLD_TO_CODE)		--//                AND UPPER(TARGET.SOLD_TO_CODE) = UPPER(ACTUAL.SOLD_TO_CODE)
               AND UPPER(TARGET.RETAIL_ENVIRONMENT) = UPPER(ACTUAL.RETAIL_ENVIRONMENT)		--//                AND UPPER(TARGET.RETAIL_ENVIRONMENT) = UPPER(ACTUAL.RETAIL_ENVIRONMENT)		--//                AND UPPER(TARGET.RETAIL_ENVIRONMENT) = UPPER(ACTUAL.RETAIL_ENVIRONMENT)		--//                AND UPPER(TARGET.RETAIL_ENVIRONMENT) = UPPER(ACTUAL.RETAIL_ENVIRONMENT)
			   AND TRIM (TARGET.EAN) = TRIM (ACTUAL.EAN)		--// 			   AND TRIM (TARGET.EAN) = TRIM (ACTUAL.EAN)		--// 			   AND TRIM (TARGET.EAN) = TRIM (ACTUAL.EAN)		--// 			   AND TRIM (TARGET.EAN) = TRIM (ACTUAL.EAN)
        LEFT JOIN (SELECT DISTINCT eannumber,
							prod_hier_l1,
							prod_hier_l2,
							prod_hier_l3,
							prod_hier_l4,
							prod_hier_l5,
							prod_hier_l6,
							prod_hier_l7,
							prod_hier_l8,
							prod_hier_l9
				FROM v_rpt_pop6_perfectstore WHERE UPPER(v_rpt_pop6_perfectstore.country::TEXT) = 'KOREA'::CHARACTER VARYING::TEXT) POP
				   ON LTRIM ( COALESCE(ACTUAL.EAN::TEXT,TARGET.EAN::TEXT),'0'::CHARACTER VARYING::TEXT) = LTRIM (POP.EANNUMBER::TEXT,'0'::CHARACTER VARYING::TEXT)		--// 				   ON LTRIM ( COALESCE(ACTUAL.EAN::TEXT,TARGET.EAN::TEXT),'0'::CHARACTER VARYING::TEXT) = LTRIM (POP.EANNUMBER::TEXT,'0'::CHARACTER VARYING::TEXT)		--// 				   ON LTRIM ( COALESCE(ACTUAL.EAN::TEXT,TARGET.EAN::TEXT),'0'::CHARACTER VARYING::TEXT) = LTRIM (POP.EANNUMBER::TEXT,'0'::CHARACTER VARYING::TEXT)		--// 				   ON LTRIM ( COALESCE(ACTUAL.EAN::TEXT,TARGET.EAN::TEXT),'0'::CHARACTER VARYING::TEXT) = LTRIM (POP.EANNUMBER::TEXT,'0'::CHARACTER VARYING::TEXT)

				   ----------------customer hierarchy------------------------------
		LEFT JOIN (SELECT *
		FROM (SELECT DISTINCT ECBD.CUST_NUM AS SAP_CUST_ID,		--// 		FROM (SELECT DISTINCT ECBD.CUST_NUM AS SAP_CUST_ID,
					 ECBD.CUST_NM AS SAP_CUST_NM,		--// 					 ECBD.CUST_NM AS SAP_CUST_NM,
					 ECSD.SLS_ORG AS SAP_SLS_ORG,		--// 					 ECSD.SLS_ORG AS SAP_SLS_ORG,
					 ECD.COMPANY AS SAP_CMP_ID,		--// 					 ECD.COMPANY AS SAP_CMP_ID,
					 ECD.CTRY_KEY AS SAP_CNTRY_CD,		--// 					 ECD.CTRY_KEY AS SAP_CNTRY_CD,
					 ECD.CTRY_NM AS SAP_CNTRY_NM,		--// 					 ECD.CTRY_NM AS SAP_CNTRY_NM,
					 ECSD.PRNT_CUST_KEY AS SAP_PRNT_CUST_KEY,		--// 					 ECSD.PRNT_CUST_KEY AS SAP_PRNT_CUST_KEY,
					 CDDES_PCK.CODE_DESC AS SAP_PRNT_CUST_DESC,		--// 					 CDDES_PCK.CODE_DESC AS SAP_PRNT_CUST_DESC,
					 ECSD.CHNL_KEY AS SAP_CUST_CHNL_KEY,		--// 					 ECSD.CHNL_KEY AS SAP_CUST_CHNL_KEY,
					 CDDES_CHNL.CODE_DESC AS SAP_CUST_CHNL_DESC,		--// 					 CDDES_CHNL.CODE_DESC AS SAP_CUST_CHNL_DESC,
					 ECSD.SUB_CHNL_KEY AS SAP_CUST_SUB_CHNL_KEY,		--// 					 ECSD.SUB_CHNL_KEY AS SAP_CUST_SUB_CHNL_KEY,
					 CDDES_SUBCHNL.CODE_DESC AS SAP_SUB_CHNL_DESC,		--// 					 CDDES_SUBCHNL.CODE_DESC AS SAP_SUB_CHNL_DESC,
					 ECSD.GO_TO_MDL_KEY AS SAP_GO_TO_MDL_KEY,		--// 					 ECSD.GO_TO_MDL_KEY AS SAP_GO_TO_MDL_KEY,
					 CDDES_GTM.CODE_DESC AS SAP_GO_TO_MDL_DESC,		--// 					 CDDES_GTM.CODE_DESC AS SAP_GO_TO_MDL_DESC,
					 ECSD.BNR_KEY AS SAP_BNR_KEY,		--// 					 ECSD.BNR_KEY AS SAP_BNR_KEY,
					 CDDES_BNRKEY.CODE_DESC AS SAP_BNR_DESC,		--// 					 CDDES_BNRKEY.CODE_DESC AS SAP_BNR_DESC,
					 ECSD.BNR_FRMT_KEY AS SAP_BNR_FRMT_KEY,		--// 					 ECSD.BNR_FRMT_KEY AS SAP_BNR_FRMT_KEY,
					 CDDES_BNRFMT.CODE_DESC AS SAP_BNR_FRMT_DESC,		--// 					 CDDES_BNRFMT.CODE_DESC AS SAP_BNR_FRMT_DESC,
					 SUBCHNL_RETAIL_ENV.RETAIL_ENV,		--// 					 SUBCHNL_RETAIL_ENV.RETAIL_ENV,
					 --REGZONE.REGION_NAME AS REGION,
					 --REGZONE.ZONE_NAME AS ZONE_OR_AREA,
					 EGCH.GCGH_REGION AS GCH_REGION,		--// 					 EGCH.GCGH_REGION AS GCH_REGION,
					 EGCH.GCGH_CLUSTER AS GCH_CLUSTER,		--// 					 EGCH.GCGH_CLUSTER AS GCH_CLUSTER,
					 EGCH.GCGH_SUBCLUSTER AS GCH_SUBCLUSTER,		--// 					 EGCH.GCGH_SUBCLUSTER AS GCH_SUBCLUSTER,
					 EGCH.GCGH_MARKET AS GCH_MARKET,		--// 					 EGCH.GCGH_MARKET AS GCH_MARKET,
					 EGCH.GCCH_RETAIL_BANNER AS GCH_RETAIL_BANNER,		--// 					 EGCH.GCCH_RETAIL_BANNER AS GCH_RETAIL_BANNER,
					 ECSD.SEGMT_KEY AS CUST_SEGMT_KEY,		--// 					 ECSD.SEGMT_KEY AS CUST_SEGMT_KEY,
					 CODES_SEGMENT.CODE_DESC AS cust_segment_desc,		--// 					 CODES_SEGMENT.code_desc AS cust_segment_desc,
					 --ROW_NUMBER() OVER (PARTITION BY SAP_CUST_ID ORDER BY SAP_PRNT_CUST_KEY,cust_segmt_key ASC NULLS LAST) AS RANK
					 --ROW_NUMBER() OVER (PARTITION BY SAP_CUST_ID ORDER BY NULLIF(SAP_PRNT_CUST_KEY,''),NULLIF(SAP_BNR_KEY,''),NULLIF(SAP_BNR_FRMT_KEY,''),NULLIF(CUST_SEGMT_KEY,'') ASC NULLS LAST) AS RANK
					 ROW_NUMBER() OVER (PARTITION BY SAP_CUST_ID ORDER BY NULLIF(ECSD.PRNT_CUST_KEY,''),NULLIF(ECSD.BNR_KEY,''),NULLIF(ECSD.BNR_FRMT_KEY,''),NULLIF(ECSD.SEGMT_KEY,'') ASC NULLS LAST) AS RANK
			  FROM EDW_GCH_CUSTOMERHIERARCHY EGCH,		--// 			  FROM RG_EDW.EDW_GCH_CUSTOMERHIERARCHY EGCH,
				   EDW_CUSTOMER_SALES_DIM ECSD,		--// 				   RG_EDW.EDW_CUSTOMER_SALES_DIM ECSD,
				   EDW_CUSTOMER_BASE_DIM ECBD,		--// 				   RG_EDW.EDW_CUSTOMER_BASE_DIM ECBD,
				   EDW_COMPANY_DIM ECD,		--// 				   RG_EDW.EDW_COMPANY_DIM ECD,
				   EDW_DSTRBTN_CHNL EDC,		--// 				   RG_EDW.EDW_DSTRBTN_CHNL EDC,
				   EDW_SALES_ORG_DIM ESOD,		--// 				   RG_EDW.EDW_SALES_ORG_DIM ESOD,
				   EDW_CODE_DESCRIPTIONS CDDES_PCK,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_PCK,
				   EDW_CODE_DESCRIPTIONS CDDES_BNRKEY,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_BNRKEY,
				   EDW_CODE_DESCRIPTIONS CDDES_BNRFMT,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_BNRFMT,
				   EDW_CODE_DESCRIPTIONS CDDES_CHNL,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_CHNL,
				   EDW_CODE_DESCRIPTIONS CDDES_GTM,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_GTM,
				   EDW_CODE_DESCRIPTIONS CDDES_SUBCHNL,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_SUBCHNL,
				   EDW_SUBCHNL_RETAIL_ENV_MAPPING SUBCHNL_RETAIL_ENV,		--// 				   RG_EDW.EDW_SUBCHNL_RETAIL_ENV_MAPPING SUBCHNL_RETAIL_ENV,
				   EDW_CODE_DESCRIPTIONS_MANUAL CODES_SEGMENT,		--// 				   RG_EDW.edw_code_descriptions_manual CODES_SEGMENT,
			  (SELECT DISTINCT CUST_NUM,
					  REC_CRT_DT,
					  PRNT_CUST_KEY,
					  ROW_NUMBER() OVER (PARTITION BY CUST_NUM ORDER BY REC_CRT_DT DESC) RN
			   FROM EDW_CUSTOMER_SALES_DIM) A		--// 			   FROM ASPEDW_INTEGRATION.EDW_CUSTOMER_SALES_DIM) A
			  WHERE EGCH.CUSTOMER ( + ) = ECBD.CUST_NUM		--// 			  WHERE EGCH.CUSTOMER (+) = ECBD.CUST_NUM // 			  WHERE EGCH.CUSTOMER ( || ) = ECBD.CUST_NUM
			  AND   ECSD.CUST_NUM = ECBD.CUST_NUM		--// 			  AND   ECSD.CUST_NUM = ECBD.CUST_NUM
			  AND   A.CUST_NUM = ECSD.CUST_NUM		--// 			  AND   A.CUST_NUM = ECSD.CUST_NUM
			  AND   ECSD.DSTR_CHNL = EDC.DISTR_CHAN		--// 			  AND   ECSD.DSTR_CHNL = EDC.DISTR_CHAN
			  AND   ECSD.SLS_ORG = ESOD.SLS_ORG		--// 			  AND   ECSD.SLS_ORG = ESOD.SLS_ORG
			  AND   ESOD.SLS_ORG_CO_CD = ECD.CO_CD		--// 			  AND   ESOD.SLS_ORG_CO_CD = ECD.CO_CD
			  AND   A.RN = 1		--// 			  AND   A.RN = 1
			  AND   UPPER(TRIM(CDDES_PCK.CODE_TYPE ( + ))) = 'PARENT CUSTOMER KEY'		--// 			  AND   UPPER(TRIM(CDDES_PCK.CODE_TYPE (+))) = 'PARENT CUSTOMER KEY' // 			  AND   UPPER(TRIM(CDDES_PCK.CODE_TYPE ( || ))) = 'PARENT CUSTOMER KEY'
			  AND   CDDES_PCK.CODE ( + ) = ECSD.PRNT_CUST_KEY		--// 			  AND   CDDES_PCK.CODE (+) = ECSD.PRNT_CUST_KEY // 			  AND   CDDES_PCK.CODE ( || ) = ECSD.PRNT_CUST_KEY
			  AND   UPPER(TRIM(CDDES_BNRKEY.CODE_TYPE ( + ))) = 'BANNER KEY'		--// 			  AND   UPPER(TRIM(cddes_bnrkey.code_type (+))) = 'BANNER KEY' // 			  AND   UPPER(TRIM(cddes_bnrkey.code_type ( || ))) = 'BANNER KEY'
			  AND   CDDES_BNRKEY.CODE ( + ) = ECSD.BNR_KEY		--// 			  AND   CDDES_BNRKEY.CODE (+) = ECSD.BNR_KEY // 			  AND   CDDES_BNRKEY.CODE ( || ) = ECSD.BNR_KEY
			  AND   UPPER(TRIM(CDDES_BNRFMT.CODE_TYPE ( + ))) = 'BANNER FORMAT KEY'		--// 			  AND   UPPER(TRIM(cddes_bnrfmt.code_type (+))) = 'BANNER FORMAT KEY' // 			  AND   UPPER(TRIM(cddes_bnrfmt.code_type ( || ))) = 'BANNER FORMAT KEY'
			  AND   CDDES_BNRFMT.CODE ( + ) = ECSD.BNR_FRMT_KEY		--// 			  AND   CDDES_BNRFMT.CODE (+) = ECSD.BNR_FRMT_KEY // 			  AND   CDDES_BNRFMT.CODE ( || ) = ECSD.BNR_FRMT_KEY
			  AND   UPPER(TRIM(CDDES_CHNL.CODE_TYPE ( + ))) = 'CHANNEL KEY'		--// 			  AND   UPPER(TRIM(cddes_chnl.code_type (+))) = 'CHANNEL KEY' // 			  AND   UPPER(TRIM(cddes_chnl.code_type ( || ))) = 'CHANNEL KEY'
			  AND   CDDES_CHNL.CODE ( + ) = ECSD.CHNL_KEY		--// 			  AND   CDDES_CHNL.CODE (+) = ECSD.CHNL_KEY // 			  AND   CDDES_CHNL.CODE ( || ) = ECSD.CHNL_KEY
			  AND   UPPER(TRIM(CDDES_GTM.CODE_TYPE ( + ))) = 'GO TO MODEL KEY'		--// 			  AND   UPPER(TRIM(cddes_gtm.code_type (+))) = 'GO TO MODEL KEY' // 			  AND   UPPER(TRIM(cddes_gtm.code_type ( || ))) = 'GO TO MODEL KEY'
			  AND   CDDES_GTM.CODE ( + ) = ECSD.GO_TO_MDL_KEY		--// 			  AND   CDDES_GTM.CODE (+) = ECSD.GO_TO_MDL_KEY // 			  AND   CDDES_GTM.CODE ( || ) = ECSD.GO_TO_MDL_KEY
			  AND   UPPER(TRIM(CDDES_SUBCHNL.CODE_TYPE ( + ))) = 'SUB CHANNEL KEY'		--// 			  AND   UPPER(TRIM(cddes_subchnl.code_type (+))) = 'SUB CHANNEL KEY' // 			  AND   UPPER(TRIM(cddes_subchnl.code_type ( || ))) = 'SUB CHANNEL KEY'
			  AND   CDDES_SUBCHNL.CODE ( + ) = ECSD.SUB_CHNL_KEY		--// 			  AND   CDDES_SUBCHNL.CODE (+) = ECSD.SUB_CHNL_KEY // 			  AND   CDDES_SUBCHNL.CODE ( || ) = ECSD.SUB_CHNL_KEY
			  AND   UPPER(SUBCHNL_RETAIL_ENV.SUB_CHANNEL ( + )) = UPPER(CDDES_SUBCHNL.CODE_DESC)		--// 			  AND   UPPER(SUBCHNL_RETAIL_ENV.SUB_CHANNEL (+)) = UPPER(CDDES_SUBCHNL.CODE_DESC) // 			  AND   UPPER(SUBCHNL_RETAIL_ENV.SUB_CHANNEL ( || )) = UPPER(CDDES_SUBCHNL.CODE_DESC)
			  AND   CODES_SEGMENT.CODE_TYPE ( + ) = 'Customer Segmentation Key'		--// 			  AND   CODES_SEGMENT.code_type (+) = 'Customer Segmentation Key' // 			  AND   CODES_SEGMENT.code_type ( || ) = 'Customer Segmentation Key'
			  AND   CODES_SEGMENT.CODE ( + ) = ECSD.SEGMT_KEY)		--// 			  AND   CODES_SEGMENT.CODE (+) = ECSD.segmt_key) // 			  AND   CODES_SEGMENT.CODE ( || ) = ECSD.segmt_key)
		WHERE RANK = 1) CUSTOMER ON LTRIM(ACTUAL.SOLD_TO_CODE,'0') = LTRIM(CUSTOMER.SAP_CUST_ID ,'0')		--// 		WHERE RANK = 1) CUSTOMER ON LTRIM(ACTUAL.SOLD_TO_CODE,'0') = LTRIM(CUSTOMER.SAP_CUST_ID (+),'0')

      ----------------product hierarchy------------------------------
        LEFT JOIN (SELECT * FROM product_heirarchy

				   WHERE RANK = 1) PRODUCT ON LTRIM(COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LTRIM(PRODUCT.SAP_MATL_NUM,'0')		--// 				   WHERE RNK = 1) PRODUCT ON LTRIM(COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LTRIM(PRODUCT.sap_matl_num,'0')		--// 				   WHERE RANK = 1) PRODUCT ON LTRIM(COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LTRIM(PRODUCT.sap_matl_num,'0')		--// 				   WHERE rnk = 1) PRODUCT ON LTRIM(COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LTRIM(PRODUCT.sap_matl_num,'0')
				   LEFT JOIN (select * from product_key_attribute
                     WHERE CTRY_NM = 'KOREA') PROD_KEY1 ON LTRIM (COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LTRIM (PROD_KEY1.SKU,'0')		--//                      WHERE CTRY_NM = 'KOREA') PROD_KEY1 ON LTRIM (COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LTRIM (PROD_KEY1.SKU,'0')		--//                      WHERE CTRY_NM = 'KOREA') PROD_KEY1 ON LTRIM (COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LTRIM (PROD_KEY1.SKU,'0')		--//                      where CTRY_NM = 'Korea') PROD_KEY1 ON LTRIM (COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LTRIM (PROD_KEY1.SKU,'0')
					  LEFT JOIN (select * from product_key_attribute
                      WHERE  CTRY_NM = 'KOREA') PROD_KEY2 ON LTRIM ((COALESCE(ACTUAL.EAN, TARGET.EAN)),'0') = LTRIM (PROD_KEY2.EAN_UPC,'0')		--//                       AND A.CTRY_NM = 'KOREA') PROD_KEY2 ON LTRIM ((COALESCE(ACTUAL.EAN, TARGET.EAN)),'0') = LTRIM (PROD_KEY2.EAN_UPC,'0')		--//                       where  CTRY_NM = 'KOREA') PROD_KEY2 ON LTRIM ((COALESCE(ACTUAL.EAN, TARGET.EAN)),'0') = LTRIM (PROD_KEY2.EAN_UPC,'0')		--//                       AND A.CTRY_NM = 'Korea') PROD_KEY2 ON LTRIM ((COALESCE(ACTUAL.EAN, TARGET.EAN)),'0') = LTRIM (PROD_KEY2.EAN_UPC,'0')
        LEFT JOIN (SELECT LTRIM(EDW_LIST_PRICE.MATERIAL,'0') AS MATERIAL,		--//         LEFT JOIN (SELECT LTRIM(EDW_LIST_PRICE.MATERIAL,'0') AS MATERIAL,		--//         LEFT JOIN (SELECT LTRIM(EDW_LIST_PRICE.MATERIAL,'0') AS MATERIAL,		--//         LEFT JOIN (SELECT LTRIM(EDW_LIST_PRICE.MATERIAL,'0') AS MATERIAL,
                          EDW_LIST_PRICE.AMOUNT AS LIST_PRICE,		--//                           EDW_LIST_PRICE.AMOUNT AS LIST_PRICE,		--//                           EDW_LIST_PRICE.AMOUNT AS LIST_PRICE,		--//                           EDW_LIST_PRICE.AMOUNT AS LIST_PRICE,
                          ROW_NUMBER() OVER (PARTITION BY LTRIM(EDW_LIST_PRICE.MATERIAL,'0') ORDER BY TO_DATE(EDW_LIST_PRICE.VALID_TO,'YYYYMMDD') DESC,TO_DATE(EDW_LIST_PRICE.DT_FROM,'YYYYMMDD') DESC) AS RN
                   FROM edw_list_price
                   WHERE EDW_LIST_PRICE.SLS_ORG IN ('3200','320S')) LP		--//                    WHERE EDW_LIST_PRICE.SLS_ORG IN ('3200','320S')) LP		--//                    WHERE EDW_LIST_PRICE.SLS_ORG IN ('3200','320S')) LP		--//                    WHERE EDW_LIST_PRICE.SLS_ORG IN ('3200','320S')) LP
               ON LTRIM (COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LP.MATERIAL		--//                ON LTRIM (COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LP.MATERIAL		--//                ON LTRIM (COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LP.MATERIAL		--//                ON LTRIM (COALESCE(ACTUAL.SKU_CODE, TARGET.SKU_CODE),'0') = LP.MATERIAL
              AND RN = 1) MDP,
     (SELECT DISTINCT "cluster"
      FROM EDW_COMPANY_DIM
      WHERE CTRY_GROUP = 'Korea') COM
WHERE FISC_PER <= (SELECT MAX(MNTH_ID)
                   FROM WKS_KOREA_REGIONAL_SELLOUT_ACTUALS)
),
kr_rpt_retail_excellence_non_mdp as
(
SELECT DISTINCT NON_MDP.*,		--// SELECT DISTINCT NON_MDP.*,
                 COM.*,		--//                  COM.*,
SYSDATE() as crtd_dttm		--// SYSDATE
FROM (SELECT ACTUAL.YEAR :: numeric(18,0)  AS YEAR,		--// INTEGER // FROM (SELECT CAST(ACTUAL.YEAR AS numeric(18,0) ) AS YEAR,
             ACTUAL.MNTH_ID :: numeric(18,0)  AS MNTH_ID,		--// INTEGER //              CAST(ACTUAL.MNTH_ID AS numeric(18,0) ) AS MNTH_ID,
             ACTUAL.CNTRY_NM AS MARKET,		--//              ACTUAL.CNTRY_NM AS MARKET,
			 ACTUAL.DATA_SOURCE AS DATA_SRC,		--// 			 ACTUAL.DATA_SOURCE AS DATA_SRC,
             --STORE_DET.CHANNEL AS CHANNEL,
			 UPPER(ACTUAL.CHANNEL) AS CHANNEL_NAME,		--// 			 UPPER(ACTUAL.CHANNEL) AS CHANNEL_NAME,
             UPPER(ACTUAL.SOLD_TO_CODE) AS SOLD_TO_CODE,		--//              UPPER(ACTUAL.SOLD_TO_CODE) AS SOLD_TO_CODE,
             UPPER(ACTUAL.DISTRIBUTOR_CODE) AS DISTRIBUTOR_CODE,		--//              UPPER(ACTUAL.DISTRIBUTOR_CODE) AS DISTRIBUTOR_CODE,
			 UPPER(ACTUAL.DISTRIBUTOR_NAME) AS DISTRIBUTOR_NAME,		--// 			 UPPER(ACTUAL.DISTRIBUTOR_NAME) AS DISTRIBUTOR_NAME,
             UPPER(ACTUAL.CHANNEL) AS SELL_OUT_CHANNEL,		--//              UPPER(ACTUAL.CHANNEL) AS SELL_OUT_CHANNEL,
			 UPPER(COALESCE(ACTUAL.RETAIL_ENVIRONMENT, 'NA')) AS RETAIL_ENVIRONMENT,		--// 			 UPPER(COALESCE(ACTUAL.RETAIL_ENVIRONMENT, 'NA')) AS RETAIL_ENVIRONMENT,
             --RETAILER.CLASS_DESC AS PRIORITIZATION_SEGMENTATION,
             --'NA' AS STORE_CATEGORY,
             UPPER(ACTUAL.STORE_CODE) AS STORE_CODE,		--//              UPPER(ACTUAL.STORE_CODE) AS STORE_CODE,
			 UPPER(ACTUAL.STORE_NAME) AS STORE_NAME,		--// 			 UPPER(ACTUAL.STORE_NAME) AS STORE_NAME,
             UPPER(COALESCE(ACTUAL.STORE_TYPE, 'NA')) AS STORE_TYPE,		--//              UPPER(COALESCE(ACTUAL.STORE_TYPE, 'NA')) AS STORE_TYPE,
             ACTUAL.STORE_GRADE AS STORE_GRADE,		--//              ACTUAL.STORE_GRADE AS STORE_GRADE,
             --RETAILER.CLASS_DESC AS STORE_SIZE,
			 ACTUAL.REGION AS REGION,		--// 			 ACTUAL.REGION AS REGION,
             --STORE_DET.STORE_ADDRESS,
             --STORE_DET.STORE_POSTCODE AS POST_CODE,
             ACTUAL.ZONE_OR_AREA AS ZONE_NAME,		--//              ACTUAL.ZONE_OR_AREA AS ZONE_NAME,
             --STORE_DET.CITY AS CITY,
             --RETAILER.RTRLATITUDE AS RTRLATITUDE,
             --RETAILER.RTRLONGITUDE AS RTRLONGITUDE,
             UPPER(ACTUAL.EAN) AS PRODUCT_CODE,		--//              UPPER(ACTUAL.EAN) AS PRODUCT_CODE,
			 UPPER(ACTUAL.SKU_DESCRIPTION) AS PRODUCT_NAME,		--// 			 UPPER(ACTUAL.SKU_DESCRIPTION) AS PRODUCT_NAME,
			 --LTRIM(ACTUAL.EAN, '0') AS EAN,
             POP.PROD_HIER_L1,		--//              POP.PROD_HIER_L1,
             POP.PROD_HIER_L2,		--//              POP.PROD_HIER_L2,
             POP.PROD_HIER_L3,		--//              POP.PROD_HIER_L3,
             POP.PROD_HIER_L4,		--//              POP.PROD_HIER_L4,
             POP.PROD_HIER_L5,		--//              POP.PROD_HIER_L5,
             POP.PROD_HIER_L6,		--//              POP.PROD_HIER_L6,
             POP.PROD_HIER_L7,		--//              POP.PROD_HIER_L7,
             POP.PROD_HIER_L8,		--//              POP.PROD_HIER_L8,
             POP.PROD_HIER_L9,		--//              POP.PROD_HIER_L9,
             UPPER(ACTUAL.SKU_CODE) AS MAPPED_SKU_CD,		--//              UPPER(ACTUAL.SKU_CODE) AS MAPPED_SKU_CD,
			 COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,		--// 			 COALESCE(ACTUAL.CUSTOMER_SEGMENT_KEY,CUSTOMER.CUST_SEGMT_KEY) AS CUSTOMER_SEGMENT_KEY,
             COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,		--//              COALESCE(ACTUAL.CUSTOMER_SEGMENT_DESCRIPTION,CUSTOMER.CUST_SEGMENT_DESC) AS CUSTOMER_SEGMENT_DESCRIPTION,
             --COALESCE(ACTUAL.STORE_TYPE) AS RETAIL_ENVIRONMENT,
             COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_KEY,CUSTOMER.SAP_CUST_CHNL_KEY) AS SAP_CUSTOMER_CHANNEL_KEY,
             COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_CHANNEL_DESCRIPTION,CUSTOMER.SAP_CUST_CHNL_DESC) AS SAP_CUSTOMER_CHANNEL_DESCRIPTION,
             COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,		--//              COALESCE(ACTUAL.SAP_CUSTOMER_SUB_CHANNEL_KEY,CUSTOMER.SAP_CUST_SUB_CHNL_KEY) AS SAP_CUSTOMER_SUB_CHANNEL_KEY,
             COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_SUB_CHANNEL_DESCRIPTION,CUSTOMER.SAP_SUB_CHNL_DESC) AS SAP_SUB_CHANNEL_DESCRIPTION,
             COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_KEY,CUSTOMER.SAP_PRNT_CUST_KEY) AS SAP_PARENT_CUSTOMER_KEY,
             COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_PARENT_CUSTOMER_DESCRIPTION,CUSTOMER.SAP_PRNT_CUST_DESC) AS SAP_PARENT_CUSTOMER_DESCRIPTION,
             COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_KEY,CUSTOMER.SAP_BNR_KEY) AS SAP_BANNER_KEY,
             COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_DESCRIPTION,CUSTOMER.SAP_BNR_DESC) AS SAP_BANNER_DESCRIPTION,
             COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_KEY,CUSTOMER.SAP_BNR_FRMT_KEY) AS SAP_BANNER_FORMAT_KEY,
             COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,		--//              COALESCE(ACTUAL.SAP_BANNER_FORMAT_DESCRIPTION,CUSTOMER.SAP_BNR_FRMT_DESC) AS SAP_BANNER_FORMAT_DESCRIPTION,
             TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_NM,''),'NA')) AS CUSTOMER_NAME,
             TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,		--//              TRIM(NVL (NULLIF(CUSTOMER.SAP_CUST_ID,''),'NA')) AS CUSTOMER_CODE,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_CD,''),'NA')) AS SAP_PROD_SGMT_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_SGMT_DESC,''),'NA')) AS SAP_PROD_SGMT_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BASE_PROD_DESC,''),'NA')) AS SAP_BASE_PROD_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_MEGA_BRND_DESC,''),'NA')) AS SAP_MEGA_BRND_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_BRND_DESC,''),'NA')) AS SAP_BRND_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_VRNT_DESC,''),'NA')) AS SAP_VRNT_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PUT_UP_DESC,''),'NA')) AS SAP_PUT_UP_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_CD,''),'NA')) AS SAP_GRP_FRNCHSE_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_GRP_FRNCHSE_DESC,''),'NA')) AS SAP_GRP_FRNCHSE_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_CD,''),'NA')) AS SAP_FRNCHSE_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_FRNCHSE_DESC,''),'NA')) AS SAP_FRNCHSE_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_CD,''),'NA')) AS SAP_PROD_FRNCHSE_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_FRNCHSE_DESC,''),'NA')) AS SAP_PROD_FRNCHSE_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_CD,''),'NA')) AS SAP_PROD_MJR_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MJR_DESC,''),'NA')) AS SAP_PROD_MJR_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_CD,''),'NA')) AS SAP_PROD_MNR_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_MNR_DESC,''),'NA')) AS SAP_PROD_MNR_DESC,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_CD,''),'NA')) AS SAP_PROD_HIER_CD,
             TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.SAP_PROD_HIER_DESC,''),'NA')) AS SAP_PROD_HIER_DESC,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_FRANCHISE,PRODUCT.GPH_PROD_FRNCHSE) AS GLOBAL_PRODUCT_FRANCHISE,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_BRAND,PRODUCT.GPH_PROD_BRND) AS GLOBAL_PRODUCT_BRAND,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUB_BRAND,PRODUCT.GPH_PROD_SUB_BRND) AS GLOBAL_PRODUCT_SUB_BRAND,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_VARIANT,PRODUCT.GPH_PROD_VRNT) AS GLOBAL_PRODUCT_VARIANT,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SEGMENT,PRODUCT.GPH_PROD_NEEDSTATE) AS GLOBAL_PRODUCT_SEGMENT,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBSEGMENT,PRODUCT.GPH_PROD_SUBSGMNT) AS GLOBAL_PRODUCT_SUBSEGMENT,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_CATEGORY,PRODUCT.GPH_PROD_CTGRY) AS GLOBAL_PRODUCT_CATEGORY,
             COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,		--//              COALESCE(ACTUAL.GLOBAL_PRODUCT_SUBCATEGORY,PRODUCT.GPH_PROD_SUBCTGRY) AS GLOBAL_PRODUCT_SUBCATEGORY,
             COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,		--//              COALESCE(ACTUAL.GLOBAL_PUT_UP_DESCRIPTION,PRODUCT.GPH_PROD_PUT_UP_DESC) AS GLOBAL_PUT_UP_DESCRIPTION,
             --TRIM(NVL (NULLIF(PRODUCT.EAN,''),'NA')) AS EAN,
             --TRIM(NVL (NULLIF(PRODUCT.SAP_MATL_NUM,''),'NA')) AS SKU_CODE,
             --TRIM(NVL (NULLIF(PRODUCT.SAP_MAT_DESC,''),'NA')) AS SKU_DESCRIPTION,
             TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_FRANCHISE_DESC,''),'NA')) AS PKA_FRANCHISE_DESC,
             TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_BRAND_DESC,''),'NA')) AS PKA_BRAND_DESC,
             TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_BRAND_DESC,''),'NA')) AS PKA_SUB_BRAND_DESC,
             TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_VARIANT_DESC,''),'NA')) AS PKA_VARIANT_DESC,
             TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,		--//              TRIM(NVL (NULLIF(PRODUCT.PKA_SUB_VARIANT_DESC,''),'NA')) AS PKA_SUB_VARIANT_DESC,
             --COALESCE(ACTUAL.PKA_PRODUCT_KEY,PRODUCT.PKA_PRODUCT_KEY) AS PKA_PRODUCT_KEY,
             --COALESCE(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION) AS PKA_PRODUCT_KEY_DESCRIPTION,
			CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA'))		--// 			CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA'))
			WHEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productkey,''),'NA'))
			WHEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productkey,''),'NA'))
			ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY,''),'NA')) END AS PKA_PRODUCT_KEY,		--// 			ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY,''),'NA')) END AS PKA_PRODUCT_KEY,
			CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA'))		--// 			CASE WHEN  TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(ACTUAL.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA'))
			WHEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY1.pka_productdesc,''),'NA'))
			WHEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productkey,''),'NA')) NOT IN ('N/A','NA') THEN TRIM(NVL (NULLIF(PROD_KEY2.pka_productdesc,''),'NA'))
			ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA')) END AS PKA_PRODUCT_KEY_DESCRIPTION,		--// 			ELSE TRIM(NVL (NULLIF(PRODUCT.PKA_PRODUCT_KEY_DESCRIPTION,''),'NA')) END AS PKA_PRODUCT_KEY_DESCRIPTION,
             ACTUAL.CM_SALES AS SALES_VALUE,		--//              ACTUAL.CM_SALES AS SALES_VALUE,
             ACTUAL.CM_SALES_QTY AS SALES_QTY,		--//              ACTUAL.CM_SALES_QTY AS SALES_QTY,
             ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,		--//              ACTUAL.CM_AVG_SALES_QTY AS AVG_SALES_QTY,
			 ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,		--// 			 ACTUAL.CM_SALES_VALUE_LIST_PRICE AS SALES_VALUE_LIST_PRICE,
             ACTUAL.LM_SALES AS LM_SALES,		--//              ACTUAL.LM_SALES AS LM_SALES,
             ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,		--//              ACTUAL.LM_SALES_QTY AS LM_SALES_QTY,
             ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,		--//              ACTUAL.LM_AVG_SALES_QTY AS LM_AVG_SALES_QTY,
			 ACTUAL.LM_SALES_LP AS LM_SALES_LP,		--// 			 ACTUAL.LM_SALES_LP AS LM_SALES_LP,
             ACTUAL.P3M_SALES AS P3M_SALES,		--//              ACTUAL.P3M_SALES AS P3M_SALES,
             ACTUAL.P3M_QTY AS P3M_QTY,		--//              ACTUAL.P3M_QTY AS P3M_QTY,
             ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,		--//              ACTUAL.P3M_AVG_QTY AS P3M_AVG_QTY,
			 ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,		--// 			 ACTUAL.P3M_SALES_LP AS P3M_SALES_LP,
             ACTUAL.F3M_SALES AS F3M_SALES,		--//              ACTUAL.F3M_SALES AS F3M_SALES,
             ACTUAL.F3M_QTY AS F3M_QTY,		--//              ACTUAL.F3M_QTY AS F3M_QTY,
             ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,		--//              ACTUAL.F3M_AVG_QTY AS F3M_AVG_QTY,
             ACTUAL.P6M_SALES AS P6M_SALES,		--//              ACTUAL.P6M_SALES AS P6M_SALES,
             ACTUAL.P6M_QTY AS P6M_QTY,		--//              ACTUAL.P6M_QTY AS P6M_QTY,
             ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,		--//              ACTUAL.P6M_AVG_QTY AS P6M_AVG_QTY,
			 ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,		--// 			 ACTUAL.P6M_SALES_LP AS P6M_SALES_LP,
             ACTUAL.P12M_SALES AS P12M_SALES,		--//              ACTUAL.P12M_SALES AS P12M_SALES,
             ACTUAL.P12M_QTY AS P12M_QTY,		--//              ACTUAL.P12M_QTY AS P12M_QTY,
             ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,		--//              ACTUAL.P12M_AVG_QTY AS P12M_AVG_QTY,
			 ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,		--// 			 ACTUAL.P12M_SALES_LP AS P12M_SALES_LP,
             ACTUAL.LM_SALES_FLAG,		--//              ACTUAL.LM_SALES_FLAG,
             ACTUAL.P3M_SALES_FLAG,		--//              ACTUAL.P3M_SALES_FLAG,
             ACTUAL.P6M_SALES_FLAG,		--//              ACTUAL.P6M_SALES_FLAG,
             ACTUAL.P12M_SALES_FLAG,		--//              ACTUAL.P12M_SALES_FLAG,
             'N' AS MDP_FLAG,
             100 AS TARGET_COMPLAINCE
		FROM (SELECT *
            FROM WKS_KOREA_REGIONAL_SELLOUT_ACTUALS A
            WHERE NOT EXISTS (SELECT 1
                              FROM ITG_KR_RE_MSL_LIST T
                              WHERE A.MNTH_ID = T.FISC_PER		--//                               WHERE A.MNTH_ID = T.FISC_PER
                AND UPPER(A.STORE_CODE) = UPPER(T.STORE_CODE)		--//                 AND UPPER(A.STORE_CODE) = UPPER(T.STORE_CODE)
               AND UPPER(A.DISTRIBUTOR_CODE) = UPPER(T.DISTRIBUTOR_CODE)		--//                AND UPPER(A.DISTRIBUTOR_CODE) = UPPER(T.DISTRIBUTOR_CODE)
               AND UPPER(A.SOLD_TO_CODE) = UPPER(T.SOLD_TO_CODE)		--//                AND UPPER(A.SOLD_TO_CODE) = UPPER(T.SOLD_TO_CODE)
							  AND UPPER (A.RETAIL_ENVIRONMENT) = UPPER (T.RETAIL_ENVIRONMENT)		--// 							  AND UPPER (A.RETAIL_ENVIRONMENT) = UPPER (T.RETAIL_ENVIRONMENT)
							  AND TRIM (A.EAN) = TRIM (T.EAN))) ACTUAL		--// 							  AND TRIM (A.EAN) = TRIM (T.EAN))) ACTUAL
        LEFT JOIN (SELECT DISTINCT eannumber,
							prod_hier_l1,
							prod_hier_l2,
							prod_hier_l3,
							prod_hier_l4,
							prod_hier_l5,
							prod_hier_l6,
							prod_hier_l7,
							prod_hier_l8,
							prod_hier_l9
				FROM v_rpt_pop6_perfectstore WHERE UPPER(v_rpt_pop6_perfectstore.country::TEXT) = 'KOREA'::CHARACTER VARYING::TEXT) POP
				   ON LTRIM (ACTUAL.EAN::TEXT,'0'::CHARACTER VARYING::TEXT) = LTRIM (POP.EANNUMBER::TEXT,'0'::CHARACTER VARYING::TEXT)		--// 				   ON LTRIM (ACTUAL.EAN::TEXT,'0'::CHARACTER VARYING::TEXT) = LTRIM (POP.EANNUMBER::TEXT,'0'::CHARACTER VARYING::TEXT)

				   ----------------customer hierarchy------------------------------
		LEFT JOIN (SELECT *
		FROM (SELECT DISTINCT ECBD.CUST_NUM AS SAP_CUST_ID,		--// 		FROM (SELECT DISTINCT ECBD.CUST_NUM AS SAP_CUST_ID,
					 ECBD.CUST_NM AS SAP_CUST_NM,		--// 					 ECBD.CUST_NM AS SAP_CUST_NM,
					 ECSD.SLS_ORG AS SAP_SLS_ORG,		--// 					 ECSD.SLS_ORG AS SAP_SLS_ORG,
					 ECD.COMPANY AS SAP_CMP_ID,		--// 					 ECD.COMPANY AS SAP_CMP_ID,
					 ECD.CTRY_KEY AS SAP_CNTRY_CD,		--// 					 ECD.CTRY_KEY AS SAP_CNTRY_CD,
					 ECD.CTRY_NM AS SAP_CNTRY_NM,		--// 					 ECD.CTRY_NM AS SAP_CNTRY_NM,
					 ECSD.PRNT_CUST_KEY AS SAP_PRNT_CUST_KEY,		--// 					 ECSD.PRNT_CUST_KEY AS SAP_PRNT_CUST_KEY,
					 CDDES_PCK.CODE_DESC AS SAP_PRNT_CUST_DESC,		--// 					 CDDES_PCK.CODE_DESC AS SAP_PRNT_CUST_DESC,
					 ECSD.CHNL_KEY AS SAP_CUST_CHNL_KEY,		--// 					 ECSD.CHNL_KEY AS SAP_CUST_CHNL_KEY,
					 CDDES_CHNL.CODE_DESC AS SAP_CUST_CHNL_DESC,		--// 					 CDDES_CHNL.CODE_DESC AS SAP_CUST_CHNL_DESC,
					 ECSD.SUB_CHNL_KEY AS SAP_CUST_SUB_CHNL_KEY,		--// 					 ECSD.SUB_CHNL_KEY AS SAP_CUST_SUB_CHNL_KEY,
					 CDDES_SUBCHNL.CODE_DESC AS SAP_SUB_CHNL_DESC,		--// 					 CDDES_SUBCHNL.CODE_DESC AS SAP_SUB_CHNL_DESC,
					 ECSD.GO_TO_MDL_KEY AS SAP_GO_TO_MDL_KEY,		--// 					 ECSD.GO_TO_MDL_KEY AS SAP_GO_TO_MDL_KEY,
					 CDDES_GTM.CODE_DESC AS SAP_GO_TO_MDL_DESC,		--// 					 CDDES_GTM.CODE_DESC AS SAP_GO_TO_MDL_DESC,
					 ECSD.BNR_KEY AS SAP_BNR_KEY,		--// 					 ECSD.BNR_KEY AS SAP_BNR_KEY,
					 CDDES_BNRKEY.CODE_DESC AS SAP_BNR_DESC,		--// 					 CDDES_BNRKEY.CODE_DESC AS SAP_BNR_DESC,
					 ECSD.BNR_FRMT_KEY AS SAP_BNR_FRMT_KEY,		--// 					 ECSD.BNR_FRMT_KEY AS SAP_BNR_FRMT_KEY,
					 CDDES_BNRFMT.CODE_DESC AS SAP_BNR_FRMT_DESC,		--// 					 CDDES_BNRFMT.CODE_DESC AS SAP_BNR_FRMT_DESC,
					 SUBCHNL_RETAIL_ENV.RETAIL_ENV,		--// 					 SUBCHNL_RETAIL_ENV.RETAIL_ENV,
					 --REGZONE.REGION_NAME AS REGION,
					 --REGZONE.ZONE_NAME AS ZONE_OR_AREA,
					 EGCH.GCGH_REGION AS GCH_REGION,		--// 					 EGCH.GCGH_REGION AS GCH_REGION,
					 EGCH.GCGH_CLUSTER AS GCH_CLUSTER,		--// 					 EGCH.GCGH_CLUSTER AS GCH_CLUSTER,
					 EGCH.GCGH_SUBCLUSTER AS GCH_SUBCLUSTER,		--// 					 EGCH.GCGH_SUBCLUSTER AS GCH_SUBCLUSTER,
					 EGCH.GCGH_MARKET AS GCH_MARKET,		--// 					 EGCH.GCGH_MARKET AS GCH_MARKET,
					 EGCH.GCCH_RETAIL_BANNER AS GCH_RETAIL_BANNER,		--// 					 EGCH.GCCH_RETAIL_BANNER AS GCH_RETAIL_BANNER,
					 ECSD.SEGMT_KEY AS CUST_SEGMT_KEY,		--// 					 ECSD.SEGMT_KEY AS CUST_SEGMT_KEY,
					 CODES_SEGMENT.CODE_DESC AS cust_segment_desc,		--// 					 CODES_SEGMENT.code_desc AS cust_segment_desc,
					 --ROW_NUMBER() OVER (PARTITION BY SAP_CUST_ID ORDER BY SAP_PRNT_CUST_KEY,cust_segmt_key ASC NULLS LAST) AS RANK
					 --ROW_NUMBER() OVER (PARTITION BY SAP_CUST_ID ORDER BY NULLIF(SAP_PRNT_CUST_KEY,''),NULLIF(SAP_BNR_KEY,''),NULLIF(SAP_BNR_FRMT_KEY,''),NULLIF(CUST_SEGMT_KEY,'') ASC NULLS LAST) AS RANK
					 ROW_NUMBER() OVER (PARTITION BY SAP_CUST_ID ORDER BY NULLIF(ECSD.PRNT_CUST_KEY,''),NULLIF(ECSD.BNR_KEY,''),NULLIF(ECSD.BNR_FRMT_KEY,''),NULLIF(ECSD.SEGMT_KEY,'') ASC NULLS LAST) AS RANK
			  FROM EDW_GCH_CUSTOMERHIERARCHY EGCH,		--// 			  FROM RG_EDW.EDW_GCH_CUSTOMERHIERARCHY EGCH,
				   EDW_CUSTOMER_SALES_DIM ECSD,		--// 				   RG_EDW.EDW_CUSTOMER_SALES_DIM ECSD,
				   EDW_CUSTOMER_BASE_DIM ECBD,		--// 				   RG_EDW.EDW_CUSTOMER_BASE_DIM ECBD,
				   EDW_COMPANY_DIM ECD,		--// 				   RG_EDW.EDW_COMPANY_DIM ECD,
				   EDW_DSTRBTN_CHNL EDC,		--// 				   RG_EDW.EDW_DSTRBTN_CHNL EDC,
				   EDW_SALES_ORG_DIM ESOD,		--// 				   RG_EDW.EDW_SALES_ORG_DIM ESOD,
				   EDW_CODE_DESCRIPTIONS CDDES_PCK,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_PCK,
				   EDW_CODE_DESCRIPTIONS CDDES_BNRKEY,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_BNRKEY,
				   EDW_CODE_DESCRIPTIONS CDDES_BNRFMT,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_BNRFMT,
				   EDW_CODE_DESCRIPTIONS CDDES_CHNL,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_CHNL,
				   EDW_CODE_DESCRIPTIONS CDDES_GTM,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_GTM,
				   EDW_CODE_DESCRIPTIONS CDDES_SUBCHNL,		--// 				   RG_EDW.EDW_CODE_DESCRIPTIONS CDDES_SUBCHNL,
				   EDW_SUBCHNL_RETAIL_ENV_MAPPING SUBCHNL_RETAIL_ENV,		--// 				   RG_EDW.EDW_SUBCHNL_RETAIL_ENV_MAPPING SUBCHNL_RETAIL_ENV,
				   EDW_CODE_DESCRIPTIONS_MANUAL CODES_SEGMENT,		--// 				   RG_EDW.edw_code_descriptions_manual CODES_SEGMENT,
			  (SELECT DISTINCT CUST_NUM,
					  REC_CRT_DT,
					  PRNT_CUST_KEY,
					  ROW_NUMBER() OVER (PARTITION BY CUST_NUM ORDER BY REC_CRT_DT DESC) RN
			   FROM ASPEDW_INTEGRATION.EDW_CUSTOMER_SALES_DIM) A		--// 			   FROM ASPEDW_INTEGRATION.EDW_CUSTOMER_SALES_DIM) A
			  WHERE EGCH.CUSTOMER ( + ) = ECBD.CUST_NUM		--// 			  WHERE EGCH.CUSTOMER (+) = ECBD.CUST_NUM // 			  WHERE EGCH.CUSTOMER ( || ) = ECBD.CUST_NUM
			  AND   ECSD.CUST_NUM = ECBD.CUST_NUM		--// 			  AND   ECSD.CUST_NUM = ECBD.CUST_NUM
			  AND   A.CUST_NUM = ECSD.CUST_NUM		--// 			  AND   A.CUST_NUM = ECSD.CUST_NUM
			  AND   ECSD.DSTR_CHNL = EDC.DISTR_CHAN		--// 			  AND   ECSD.DSTR_CHNL = EDC.DISTR_CHAN
			  AND   ECSD.SLS_ORG = ESOD.SLS_ORG		--// 			  AND   ECSD.SLS_ORG = ESOD.SLS_ORG
			  AND   ESOD.SLS_ORG_CO_CD = ECD.CO_CD		--// 			  AND   ESOD.SLS_ORG_CO_CD = ECD.CO_CD
			  AND   A.RN = 1		--// 			  AND   A.RN = 1
			  AND   UPPER(TRIM(CDDES_PCK.CODE_TYPE ( + ))) = 'PARENT CUSTOMER KEY'		--// 			  AND   UPPER(TRIM(CDDES_PCK.CODE_TYPE (+))) = 'PARENT CUSTOMER KEY' // 			  AND   UPPER(TRIM(CDDES_PCK.CODE_TYPE ( || ))) = 'PARENT CUSTOMER KEY'
			  AND   CDDES_PCK.CODE ( + ) = ECSD.PRNT_CUST_KEY		--// 			  AND   CDDES_PCK.CODE (+) = ECSD.PRNT_CUST_KEY // 			  AND   CDDES_PCK.CODE ( || ) = ECSD.PRNT_CUST_KEY
			  AND   UPPER(TRIM(CDDES_BNRKEY.CODE_TYPE ( + ))) = 'BANNER KEY'		--// 			  AND   UPPER(TRIM(cddes_bnrkey.code_type (+))) = 'BANNER KEY' // 			  AND   UPPER(TRIM(cddes_bnrkey.code_type ( || ))) = 'BANNER KEY'
			  AND   CDDES_BNRKEY.CODE ( + ) = ECSD.BNR_KEY		--// 			  AND   CDDES_BNRKEY.CODE (+) = ECSD.BNR_KEY // 			  AND   CDDES_BNRKEY.CODE ( || ) = ECSD.BNR_KEY
			  AND   UPPER(TRIM(CDDES_BNRFMT.CODE_TYPE ( + ))) = 'BANNER FORMAT KEY'		--// 			  AND   UPPER(TRIM(cddes_bnrfmt.code_type (+))) = 'BANNER FORMAT KEY' // 			  AND   UPPER(TRIM(cddes_bnrfmt.code_type ( || ))) = 'BANNER FORMAT KEY'
			  AND   CDDES_BNRFMT.CODE ( + ) = ECSD.BNR_FRMT_KEY		--// 			  AND   CDDES_BNRFMT.CODE (+) = ECSD.BNR_FRMT_KEY // 			  AND   CDDES_BNRFMT.CODE ( || ) = ECSD.BNR_FRMT_KEY
			  AND   UPPER(TRIM(CDDES_CHNL.CODE_TYPE ( + ))) = 'CHANNEL KEY'		--// 			  AND   UPPER(TRIM(cddes_chnl.code_type (+))) = 'CHANNEL KEY' // 			  AND   UPPER(TRIM(cddes_chnl.code_type ( || ))) = 'CHANNEL KEY'
			  AND   CDDES_CHNL.CODE ( + ) = ECSD.CHNL_KEY		--// 			  AND   CDDES_CHNL.CODE (+) = ECSD.CHNL_KEY // 			  AND   CDDES_CHNL.CODE ( || ) = ECSD.CHNL_KEY
			  AND   UPPER(TRIM(CDDES_GTM.CODE_TYPE ( + ))) = 'GO TO MODEL KEY'		--// 			  AND   UPPER(TRIM(cddes_gtm.code_type (+))) = 'GO TO MODEL KEY' // 			  AND   UPPER(TRIM(cddes_gtm.code_type ( || ))) = 'GO TO MODEL KEY'
			  AND   CDDES_GTM.CODE ( + ) = ECSD.GO_TO_MDL_KEY		--// 			  AND   CDDES_GTM.CODE (+) = ECSD.GO_TO_MDL_KEY // 			  AND   CDDES_GTM.CODE ( || ) = ECSD.GO_TO_MDL_KEY
			  AND   UPPER(TRIM(CDDES_SUBCHNL.CODE_TYPE ( + ))) = 'SUB CHANNEL KEY'		--// 			  AND   UPPER(TRIM(cddes_subchnl.code_type (+))) = 'SUB CHANNEL KEY' // 			  AND   UPPER(TRIM(cddes_subchnl.code_type ( || ))) = 'SUB CHANNEL KEY'
			  AND   CDDES_SUBCHNL.CODE ( + ) = ECSD.SUB_CHNL_KEY		--// 			  AND   CDDES_SUBCHNL.CODE (+) = ECSD.SUB_CHNL_KEY // 			  AND   CDDES_SUBCHNL.CODE ( || ) = ECSD.SUB_CHNL_KEY
			  AND   UPPER(SUBCHNL_RETAIL_ENV.SUB_CHANNEL ( + )) = UPPER(CDDES_SUBCHNL.CODE_DESC)		--// 			  AND   UPPER(SUBCHNL_RETAIL_ENV.SUB_CHANNEL (+)) = UPPER(CDDES_SUBCHNL.CODE_DESC) // 			  AND   UPPER(SUBCHNL_RETAIL_ENV.SUB_CHANNEL ( || )) = UPPER(CDDES_SUBCHNL.CODE_DESC)
			  AND   CODES_SEGMENT.CODE_TYPE ( + ) = 'Customer Segmentation Key'		--// 			  AND   CODES_SEGMENT.code_type (+) = 'Customer Segmentation Key' // 			  AND   CODES_SEGMENT.code_type ( || ) = 'Customer Segmentation Key'
			  AND   CODES_SEGMENT.CODE ( + ) = ECSD.SEGMT_KEY)		--// 			  AND   CODES_SEGMENT.CODE (+) = ECSD.segmt_key) // 			  AND   CODES_SEGMENT.CODE ( || ) = ECSD.segmt_key)
		WHERE RANK = 1) CUSTOMER ON LTRIM(ACTUAL.SOLD_TO_CODE,'0') = LTRIM(CUSTOMER.SAP_CUST_ID,'0')		--// 		WHERE RANK = 1) CUSTOMER ON LTRIM(ACTUAL.SOLD_TO_CODE,'0') = LTRIM(CUSTOMER.SAP_CUST_ID (+),'0')

      ----------------product hierarchy------------------------------
        LEFT JOIN (SELECT * FROM product_heirarchy
				   WHERE RANK = 1) PRODUCT ON LTRIM(ACTUAL.SKU_CODE,'0') = LTRIM(PRODUCT.SAP_MATL_NUM,'0')		--// 				   WHERE RANK = 1) PRODUCT ON LTRIM(ACTUAL.SKU_CODE,'0') = LTRIM(PRODUCT.sap_matl_num,'0')
				   LEFT JOIN (SELECT * from product_key_attribute

                      where  CTRY_NM = 'Korea') PROD_KEY1 ON LTRIM (ACTUAL.SKU_CODE,'0') = LTRIM (PROD_KEY1.SKU,'0')		--//                       where  CTRY_NM = 'Korea') PROD_KEY1 ON LTRIM (ACTUAL.SKU_CODE,'0') = LTRIM (PROD_KEY1.SKU,'0')

					  LEFT JOIN (select * from product_key_attribute

                      where CTRY_NM = 'Korea') PROD_KEY2 ON LTRIM (ACTUAL.EAN,'0') = LTRIM (PROD_KEY2.EAN_UPC,'0')		--//                       where CTRY_NM = 'Korea') PROD_KEY2 ON LTRIM (ACTUAL.EAN,'0') = LTRIM (PROD_KEY2.EAN_UPC,'0')

        LEFT JOIN (SELECT LTRIM(EDW_LIST_PRICE.MATERIAL,'0') AS MATERIAL,		--//         LEFT JOIN (SELECT LTRIM(EDW_LIST_PRICE.MATERIAL,'0') AS MATERIAL,
                          EDW_LIST_PRICE.AMOUNT AS LIST_PRICE,		--//                           EDW_LIST_PRICE.AMOUNT AS LIST_PRICE,
                          ROW_NUMBER() OVER (PARTITION BY LTRIM(EDW_LIST_PRICE.MATERIAL,'0') ORDER BY TO_DATE(EDW_LIST_PRICE.VALID_TO,'YYYYMMDD') DESC,TO_DATE(EDW_LIST_PRICE.DT_FROM,'YYYYMMDD') DESC) AS RN
                   FROM EDW_LIST_PRICE
                   WHERE EDW_LIST_PRICE.SLS_ORG IN ('3200','320S')) LP		--//                    WHERE EDW_LIST_PRICE.SLS_ORG IN ('3200','320S')) LP
               ON LTRIM (ACTUAL.SKU_CODE,'0') = LP.MATERIAL		--//                ON LTRIM (ACTUAL.SKU_CODE,'0') = LP.MATERIAL
              AND RN = 1) NON_MDP,
     (SELECT DISTINCT "cluster"
      FROM EDW_COMPANY_DIM
      WHERE CTRY_GROUP = 'Korea') COM
),
kr_rpt_retail_excellence as
(
select * from kr_rpt_retail_excellence_mdp
union 
select * from kr_rpt_retail_excellence_non_mdp
),
final as 
(
select 
fisc_yr::numeric(18,0) AS fisc_yr,
fisc_per::numeric(18,0) AS fisc_per,
market::varchar(50) AS market,
data_src::varchar(14) AS data_src,
channel_name::varchar(337) AS channel_name,
sold_to_code::varchar(382) AS sold_to_code,
distributor_code::varchar(225) AS distributor_code,
distributor_name::varchar(801) AS distributor_name,
sell_out_channel::varchar(337) AS sell_out_channel,
retail_environment::varchar(225) AS retail_environment,
store_code::varchar(225) AS store_code,
store_name::varchar(1351) AS store_name,
store_type::varchar(573) AS store_type,
store_grade::varchar(150) AS store_grade,
region::varchar(150) AS region,
zone_name::varchar(150) AS zone_name,
product_code::varchar(225) AS product_code,
product_name::varchar(450) AS product_name,
prod_hier_l1::varchar(200) AS prod_hier_l1,
prod_hier_l2::varchar(200) AS prod_hier_l2,
prod_hier_l3::varchar(200) AS prod_hier_l3,
prod_hier_l4::varchar(200) AS prod_hier_l4,
prod_hier_l5::varchar(200) AS prod_hier_l5,
prod_hier_l6::varchar(200) AS prod_hier_l6,
prod_hier_l7::varchar(200) AS prod_hier_l7,
prod_hier_l8::varchar(200) AS prod_hier_l8,
prod_hier_l9::varchar(1) AS prod_hier_l9,
mapped_sku_cd::varchar(60) AS mapped_sku_cd,
customer_segment_key::varchar(12) AS customer_segment_key,
customer_segment_description::varchar(50) AS customer_segment_description,
sap_customer_channel_key::varchar(12) AS sap_customer_channel_key,
sap_customer_channel_description::varchar(75) AS sap_customer_channel_description,
sap_customer_sub_channel_key::varchar(12) AS sap_customer_sub_channel_key,
sap_sub_channel_description::varchar(75) AS sap_sub_channel_description,
sap_parent_customer_key::varchar(12) AS sap_parent_customer_key,
sap_parent_customer_description::varchar(75) AS sap_parent_customer_description,
sap_banner_key::varchar(12) AS sap_banner_key,
sap_banner_description::varchar(75) AS sap_banner_description,
sap_banner_format_key::varchar(12) AS sap_banner_format_key,
sap_banner_format_description::varchar(75) AS sap_banner_format_description,
customer_name::varchar(100) AS customer_name,
customer_code::varchar(10) AS customer_code,
sap_prod_sgmt_cd::varchar(18) AS sap_prod_sgmt_cd,
sap_prod_sgmt_desc::varchar(100) AS sap_prod_sgmt_desc,
sap_base_prod_desc::varchar(100) AS sap_base_prod_desc,
sap_mega_brnd_desc::varchar(100) AS sap_mega_brnd_desc,
sap_brnd_desc::varchar(100) AS sap_brnd_desc,
sap_vrnt_desc::varchar(100) AS sap_vrnt_desc,
sap_put_up_desc::varchar(100) AS sap_put_up_desc,
sap_grp_frnchse_cd::varchar(18) AS sap_grp_frnchse_cd,
sap_grp_frnchse_desc::varchar(100) AS sap_grp_frnchse_desc,
sap_frnchse_cd::varchar(18) AS sap_frnchse_cd,
sap_frnchse_desc::varchar(100) AS sap_frnchse_desc,
sap_prod_frnchse_cd::varchar(18) AS sap_prod_frnchse_cd,
sap_prod_frnchse_desc::varchar(100) AS sap_prod_frnchse_desc,
sap_prod_mjr_cd::varchar(18) AS sap_prod_mjr_cd,
sap_prod_mjr_desc::varchar(100) AS sap_prod_mjr_desc,
sap_prod_mnr_cd::varchar(18) AS sap_prod_mnr_cd,
sap_prod_mnr_desc::varchar(100) AS sap_prod_mnr_desc,
sap_prod_hier_cd::varchar(18) AS sap_prod_hier_cd,
sap_prod_hier_desc::varchar(100) AS sap_prod_hier_desc,
global_product_franchise::varchar(30) AS global_product_franchise,
global_product_brand::varchar(30) AS global_product_brand,
global_product_sub_brand::varchar(100) AS global_product_sub_brand,
global_product_variant::varchar(100) AS global_product_variant,
global_product_segment::varchar(50) AS global_product_segment,
global_product_subsegment::varchar(100) AS global_product_subsegment,
global_product_category::varchar(50) AS global_product_category,
global_product_subcategory::varchar(50) AS global_product_subcategory,
global_put_up_description::varchar(100) AS global_put_up_description,
pka_franchise_desc::varchar(30) AS pka_franchise_desc,
pka_brand_desc::varchar(30) AS pka_brand_desc,
pka_sub_brand_desc::varchar(30) AS pka_sub_brand_desc,
pka_variant_desc::varchar(30) AS pka_variant_desc,
pka_sub_variant_desc::varchar(30) AS pka_sub_variant_desc,
pka_product_key::varchar(68) AS pka_product_key,
pka_product_key_description::varchar(255) AS pka_product_key_description,
sales_value::numeric(38,6) AS sales_value,
sales_qty::numeric(38,6) AS sales_qty,
avg_sales_qty::numeric(38,6) AS avg_sales_qty,
sales_value_list_price::numeric(38,12) AS sales_value_list_price,
lm_sales::numeric(38,6) AS lm_sales,
lm_sales_qty::numeric(38,6) AS lm_sales_qty,
lm_avg_sales_qty::numeric(38,6) AS lm_avg_sales_qty,
lm_sales_lp::numeric(38,12) AS lm_sales_lp,
p3m_sales::numeric(38,6) AS p3m_sales,
p3m_qty::numeric(38,6) AS p3m_qty,
p3m_avg_qty::numeric(38,6) AS p3m_avg_qty,
p3m_sales_lp::numeric(38,12) AS p3m_sales_lp,
f3m_sales::numeric(38,6) AS f3m_sales,
f3m_qty::numeric(38,6) AS f3m_qty,
f3m_avg_qty::numeric(38,6) AS f3m_avg_qty,
p6m_sales::numeric(38,6) AS p6m_sales,
p6m_qty::numeric(38,6) AS p6m_qty,
p6m_avg_qty::numeric(38,6) AS p6m_avg_qty,
p6m_sales_lp::numeric(38,12) AS p6m_sales_lp,
p12m_sales::numeric(38,6) AS p12m_sales,
p12m_qty::numeric(38,6) AS p12m_qty,
p12m_avg_qty::numeric(38,6) AS p12m_avg_qty,
p12m_sales_lp::numeric(38,12) AS p12m_sales_lp,
lm_sales_flag::varchar(1) AS lm_sales_flag,
p3m_sales_flag::varchar(1) AS p3m_sales_flag,
p6m_sales_flag::varchar(1) AS p6m_sales_flag,
p12m_sales_flag::varchar(1) AS p12m_sales_flag,
mdp_flag::varchar(1) AS mdp_flag,
target_complaince::numeric(18,0) AS target_complaince,
"cluster"::varchar(100) AS cluster,
crtd_dttm::timestamp without time zone AS crtd_dttm,
from kr_rpt_retail_excellence
)
--Final select
select * from final