with source as 
(
    select * from  {{source ('phlsdl_raw','sdl_mds_ph_hcp_product_master')}}
),
transformed as
(
    select 
       ID :: NUMBER(10,0) as ID,
	MUID :: VARCHAR(40) as MUID,
	VERSIONNAME::VARCHAR(100) as VERSIONNAME,
	VERSIONNUMBER::NUMBER(10,0) as VERSIONNUMBER,
	VERSION_ID::NUMBER(10,0) as VERSION_ID,
	VERSIONFLAG::VARCHAR(100) as VERSIONFLAG,
	NAME::VARCHAR(500) as NAME,
	CODE::VARCHAR(500) as CODE,
	CHANGETRACKINGMASK::NUMBER(10,0) as CHANGETRACKINGMASK,
	TEAM_CODE::VARCHAR(500) as TEAM_CODE,
	TEAM_NAME::VARCHAR(500) as TEAM_NAME,
	TEAM_ID::NUMBER(10,0) as TEAM_ID,
	GROUP_VARIANT_CODE::VARCHAR(500) as GROUP_VARIANT_CODE,
	GROUP_VARIANT_NAME::VARCHAR(500) as GROUP_VARIANT_NAME,
	GROUP_VARIANT_ID::NUMBER(10,0) as GROUP_VARIANT_ID,
	ENTERDATETIME::TIMESTAMP_NTZ(9) as ENTERDATETIME,
	ENTERUSERNAME::VARCHAR(200) as ENTERUSERNAME,
	ENTERVERSIONNUMBER::NUMBER(10,0) as ENTERVERSIONNUMBER,
	LASTCHGDATETIME::TIMESTAMP_NTZ(9) as LASTCHGDATETIME,
	LASTCHGUSERNAME::VARCHAR(200) as LASTCHGUSERNAME,
	LASTCHGVERSIONNUMBER::NUMBER(10,0) as LASTCHGVERSIONNUMBE,
	VALIDATIONSTATUS::VARCHAR(500) as VALIDATIONSTATUS,
    current_timestamp()::timestamp_ntz(9) as crtd_dttm
    
    from source
)
select * from transformed
