with source as 
(
    select * from snapindwks_integration.wks_retailermaster_upd
),
final as 
(
    select 
    retailer_code::varchar(50) as retailer_code,
	start_date::timestamp_ntz(9) as start_date,
	end_date::timestamp_ntz(9) as end_date,
	customer_code::varchar(50) as customer_code,
	customer_name::varchar(150) as customer_name,
	retailer_name::varchar(150) as retailer_name,
	retailer_address1::varchar(250) as retailer_address1,
	retailer_address2::varchar(250) as retailer_address2,
	retailer_address3::varchar(250) as retailer_address3,
	region_code::number(38,0) as region_code,
	region_name::varchar(50) as region_name,
	zone_code::number(38,0) as zone_code,
	zone_name::varchar(50) as zone_name,
	zone_classification::varchar(50) as zone_classification,
	territory_code::number(38,0) as territory_code,
	territory_name::varchar(50) as territory_name,
	territory_classification::varchar(50) as territory_classification,
	state_code::number(38,0) as state_code,
	state_name::varchar(50) as state_name,
	town_name::varchar(50) as town_name,
	town_classification::varchar(50) as town_classification,
	class_code::varchar(50) as class_code,
	class_desc::varchar(50) as class_desc,
	outlet_type::varchar(50) as outlet_type,
	channel_code::varchar(50) as channel_code,
	channel_name::varchar(150) as channel_name,
	business_channel::varchar(50) as business_channel,
	loyalty_desc::varchar(50) as loyalty_desc,
	registration_date::number(18,0) as registration_date,
	status_cd::varchar(50) as status_cd,
	status_desc::varchar(10) as status_desc,
	csrtrcode::varchar(50) as csrtrcode,
	crt_dttm::timestamp_ntz(9) as crt_dttm,
	updt_dttm::timestamp_ntz(9) as updt_dttm,
	actv_flg::varchar(1) as actv_flg,
	retailer_category_cd::varchar(25) as retailer_category_cd,
	retailer_category_name::varchar(50) as retailer_category_name,
	rtrlatitude::varchar(40) as rtrlatitude,
	rtrlongitude::varchar(40) as rtrlongitude,
	rtruniquecode::varchar(100) as rtruniquecode,
	createddate::timestamp_ntz(9) as createddate,
	file_rec_dt::date as file_rec_dt,
	type_name::varchar(50) as type_name,
	town_code::varchar(50) as town_code,
    from source
)
select * from final