with KESAI_H_DATA_MART_SUB_N as(
    select * from {{ ref('jpndcledw_integration__kesai_h_data_mart_sub_n') }}
),
union1 as(
SELECT CN.SALENO,
	CN.JUCHKBN,
	CN.JUCHYM,
	CN.JUCHDATE,
	CN.JUCHQUARTER,
	CN.JUCHJIGYOKI,
	CN.KOKYANO,
	CN.TORIKEIKBN,
	CN.CANCELFLG,
	CN.HANROCODE,
	CN.SYOHANROBUNNAME,
	CN.CHUHANROBUNNAME,
	CN.DAIHANROBUNNAME,
	CN.MEDIACODE,
	CN.SORYO,
	CN.TAX,
	CN.SOGOKEI,
	CN.TENPOCODE,
	CN.SHUKAYM,
	CN.SHUKADATE,
	CN.SHUKAQUARTER,
	CN.SHUKAJIGYOKI,
	CN.ZIPCODE,
	CN.TODOFUKENCODE,
	CN.RIYOPOINT,
	CN.HAPPENPOINT,
	CN.KESSAIKBN,
	CN.CARDCORPCODE,
	CN.HENREASONCODE,
	CN.MOTOINSERTID,
	CN.MOTOINSERTDATE,
	CN.MOTOUPDATEDATE,
	CN.INSERTDATE,
	CN.INSERTTIME,
	CN.INSERTID,
	CN.UPDATEDATE,
	CN.UPDATETIME,
	CN.UPDATEID,
	CN.RANK,
	CN.DISPSALENO,
	CN.KESAIID,
	CN.ORDERCODE,
	CN.HENREASONNAME,
	CN.UKETSUKEUSRID,
	CN.UKETSUKETELCOMPANYCD,
	CN.SMKEIROID,
	CN.DIPROMID,
	CN.SALENO_TRM,
	CN.DICOLLECTPRC,
	CN.DITOUJITSUHAISOPRC,
	CN.DIDISCOUNTALL,
	CN.C_DIDISCOUNTPRC,
	CN.POINT_EXCHANGE,
	CN.LOGINCODE,
	CN.MAKER,
	CN.TODOFUKEN_CODE,
	CN.SHUKKASTS,
	CN.DIVOUCHERCODE,
	CN.DITAXRATE,
	CN.DISEIKYUREMAIN,
	CN.DINYUKINSTS,
	CN.DICARDNYUKINSTS,
	CN.DISOKOID,
	CN.DIHAISOKEITAI
FROM KESAI_H_DATA_MART_SUB_N CN
WHERE CN.MAKER = 1

),
union2 as( 

SELECT CN.SALENO,
	CN.JUCHKBN,
	CN.JUCHYM,
	CN.JUCHDATE,
	CN.JUCHQUARTER,
	CN.JUCHJIGYOKI,
	CN.KOKYANO,
	CN.TORIKEIKBN,
	CN.CANCELFLG,
	CN.HANROCODE,
	CN.SYOHANROBUNNAME,
	CN.CHUHANROBUNNAME,
	CN.DAIHANROBUNNAME,
	CN.MEDIACODE,
	NVL(CN.SORYO, 0) AS SORYO,
	NVL(CN.TAX, 0) AS TAX,
	NVL(CN.SOGOKEI, 0) AS SOGOKEI,
	CN.TENPOCODE,
	CN.SHUKAYM,
	CN.SHUKADATE,
	CN.SHUKAQUARTER,
	CN.SHUKAJIGYOKI,
	CN.ZIPCODE,
	CN.TODOFUKENCODE,
	NVL(CN.RIYOPOINT, 0) AS RIYOPOINT,
	CN.HAPPENPOINT,
	CN.KESSAIKBN,
	CN.CARDCORPCODE,
	CN.HENREASONCODE,
	CN.MOTOINSERTID,
	CN.MOTOINSERTDATE,
	CN.MOTOUPDATEDATE,
	CN.INSERTDATE,
	CN.INSERTTIME,
	CN.INSERTID,
	CN.UPDATEDATE,
	CN.UPDATETIME,
	CN.UPDATEID,
	CN.RANK,
	CN.DISPSALENO,
	CN.KESAIID,
	CN.ORDERCODE,
	CN.HENREASONNAME,
	CN.UKETSUKEUSRID,
	CN.UKETSUKETELCOMPANYCD,
	CN.SMKEIROID,
	CN.DIPROMID,
	CN.SALENO_TRM,
	NVL(CN.DICOLLECTPRC, 0) AS DICOLLECTPRC,
	NVL(CN.DITOUJITSUHAISOPRC, 0) AS DITOUJITSUHAISOPRC,
	NVL(CN.DIDISCOUNTALL, 0) AS DIDISCOUNTALL,
	NVL(C_DIDISCOUNTPRC, 0) AS C_DIDISCOUNTPRC,
	CN.POINT_EXCHANGE,
	CN.LOGINCODE,
	CN.MAKER,
	CN.TODOFUKEN_CODE,
	CN.SHUKKASTS,
	CN.DIVOUCHERCODE,
	CN.DITAXRATE,
	NVL(CN.DISEIKYUREMAIN, 0) AS DISEIKYUREMAIN,
	CN.DINYUKINSTS,
	CN.DICARDNYUKINSTS,
	CN.DISOKOID,
	CN.DIHAISOKEITAI
FROM KESAI_H_DATA_MART_SUB_N CN
WHERE CN.MAKER = 2

),
transformed as(
    select * from union1
    union all
    select * from union2
),
final as(
    select 
        saleno::varchar(63) as saleno,
        juchkbn::varchar(3) as juchkbn,
        juchym::varchar(18) as juchym,
        juchdate::number(18,0) as juchdate,
        juchquarter::varchar(3) as juchquarter,
        juchjigyoki::varchar(135) as juchjigyoki,
        kokyano::varchar(70) as kokyano,
        torikeikbn::varchar(3) as torikeikbn,
        cancelflg::varchar(8) as cancelflg,
        hanrocode::varchar(135) as hanrocode,
        syohanrobunname::varchar(135) as syohanrobunname,
        chuhanrobunname::varchar(135) as chuhanrobunname,
        daihanrobunname::varchar(135) as daihanrobunname,
        mediacode::varchar(8) as mediacode,
        soryo::number(18,0) as soryo,
        tax::number(18,0) as tax,
        sogokei::number(18,0) as sogokei,
        tenpocode::varchar(8) as tenpocode,
        shukaym::varchar(18) as shukaym,
        shukadate::number(18,0) as shukadate,
        shukaquarter::varchar(3) as shukaquarter,
        shukajigyoki::varchar(135) as shukajigyoki,
        zipcode::varchar(15) as zipcode,
        todofukencode::varchar(15) as todofukencode,
        riyopoint::number(18,0) as riyopoint,
        happenpoint::number(18,0) as happenpoint,
        kessaikbn::varchar(8) as kessaikbn,
        cardcorpcode::varchar(135) as cardcorpcode,
        henreasoncode::varchar(135) as henreasoncode,
        motoinsertid::varchar(135) as motoinsertid,
        motoinsertdate::number(18,0) as motoinsertdate,
        motoupdatedate::number(18,0) as motoupdatedate,
        insertdate::number(18,0) as insertdate,
        inserttime::number(18,0) as inserttime,
        insertid::varchar(9) as insertid,
        updatedate::number(18,0) as updatedate,
        updatetime::number(18,0) as updatetime,
        updateid::varchar(9) as updateid,
        rank::number(18,0) as rank,
        dispsaleno::varchar(62) as dispsaleno,
        kesaiid::varchar(62) as kesaiid,
        ordercode::varchar(18) as ordercode,
        henreasonname::varchar(48) as henreasonname,
        uketsukeusrid::number(18,0) as uketsukeusrid,
        uketsuketelcompanycd::varchar(8) as uketsuketelcompanycd,
        smkeiroid::number(18,0) as smkeiroid,
        dipromid::number(18,0) as dipromid,
        saleno_trm::varchar(63) as saleno_trm,
        dicollectprc::number(18,0) as dicollectprc,
        ditoujitsuhaisoprc::number(18,0) as ditoujitsuhaisoprc,
        didiscountall::number(18,0) as didiscountall,
        c_didiscountprc::number(18,0) as c_didiscountprc,
        point_exchange::number(18,0) as point_exchange,
        logincode::varchar(48) as logincode,
        maker::number(18,0) as maker,
        todofuken_code::varchar(135) as todofuken_code,
        shukkasts::varchar(6) as shukkasts,
        divouchercode::varchar(768) as divouchercode,
        ditaxrate::number(18,0) as ditaxrate,
        diseikyuremain::number(18,0) as diseikyuremain,
        dinyukinsts::varchar(8) as dinyukinsts,
        dicardnyukinsts::varchar(8) as dicardnyukinsts,
        disokoid::number(18,0) as disokoid,
        dihaisokeitai::number(18,0) as dihaisokeitai,
        current_timestamp()::timestamp_ntz(9) as inserted_date,
        null::varchar(100) as inserted_by ,
        current_timestamp()::timestamp_ntz(9) as updated_date,
        null::varchar(100) as updated_by
    from transformed
)
select * from final