{{
    config
    (
        sql_header="USE WAREHOUSE "+ env_var("DBT_ENV_CORE_DB_MEDIUM_WH")+ ";",
    )
}}
WITH 
ZCMMNSOSHITAIK AS
(
SELECT * FROM {{ source('jpdclitg_integration','zcmmnsoshitaik') }} 
),
C_TBECKESAI AS
(
SELECT * FROM {{ref('jpndclitg_integration__c_tbeckesai')}}
),
CIM03ITEM_ZAIKO AS
(
SELECT * FROM {{ref('jpndcledw_integration__cim03item_zaiko')}}
),
SSMTHSALHEDDA AS
(
SELECT * FROM {{ref('jpndclitg_integration__ssmthsalhedda')}}
),
SSMTBSALMEI AS
(
SELECT * FROM {{ source('jpdclitg_integration','ssmtbsalmei') }}
 
),
SSMTHDCLTHANJUCHHEDDA AS
(
SELECT * FROM {{ source('jpdclitg_integration','ssmthdclthanjuchhedda') }}
),
ZCMMNTORISK AS
(
SELECT * FROM {{ source('jpdclitg_integration','zcmmntorisk') }} 
),
HANYO_ATTR AS
(
SELECT * FROM {{ref('jpndcledw_integration__hanyo_attr')}}
),
CIT86OSALM_KKNG AS
(
SELECT * FROM  {{ source('jpdcledw_integration','cit86osalm_kkng') }}  
),
CIT85OSALH_KKNG AS
(
SELECT * FROM {{ source('jpdcledw_integration','cit85osalh_kkng') }} 
),
T1 AS
(
SELECT
	
	CIT86OSALM_KKNG.OURINO AS OURINO,
	CIT86OSALM_KKNG.GYONO AS GYONO,
	CIT86OSALM_KKNG.ITEMCODE AS ITEMCODE,
	CIT86OSALM_KKNG.ITEMCODE_HANBAI AS ITEMCODE_HANBAI,
	CASE 
		WHEN CIT86OSALM_KKNG.ITEMCODE LIKE '9%'
			AND ITEM.ITEMKBN = '08'
			THEN 0
		ELSE NVL(CIT86OSALM_KKNG.SURYO, 0)
		END AS SURYO,
	CIT86OSALM_KKNG.TANKA AS TANKA,
	CIT86OSALM_KKNG.HENSU AS HENSU,
	CIT86OSALM_KKNG.HENUSU AS HENUSU,
	CIT86OSALM_KKNG.KINGAKU AS KINGAKU,
	CIT86OSALM_KKNG.MEISAINUKIKINGAKU AS MEISAINUKIKINGAKU,
	CIT86OSALM_KKNG.MEISAITAX AS MEISAITAX,
	CIT86OSALM_KKNG.TANKA_TUKA AS TANKA_TUKA,
	CIT86OSALM_KKNG.KINGAKU_TUKA AS KINGAKU_TUKA,
	CIT86OSALM_KKNG.MEISAINUKIKINGAKU_TUKA AS MEISAINUKIKINGAKU_TUKA,
	CIT86OSALM_KKNG.MEISAITAX_TUKA AS MEISAITAX_TUKA,
	1 AS KAKOKBN,
	CIT85OSALH_KKNG.KKNG_KBN AS KKNG_KBN,
	CIT86OSALM_KKNG.OURINO AS DISPOURINO,
	0 AS SHIMEBI,
	CIT86OSALM_KKNG.MEISAINUKIKINGAKU AS ANBUNMEISAINUKIKINGAKU,
	1 AS MARKER,
	NULL AS ROWID1,
	NULL AS ROWID2,
	NULL AS ROWID3,
	NULL AS ROWID4,
	NULL AS ROWID5,
	NULL AS ROWID6,
	0 AS SHOHZEI_RITSU 
FROM CIT86OSALM_KKNG ,
	CIT85OSALH_KKNG ,
	CIM03ITEM_ZAIKO ITEM
WHERE CIT85OSALH_KKNG.JUCHKBN NOT IN ('90', '91', '92')
	AND CIT86OSALM_KKNG.OURINO = CIT85OSALH_KKNG.OURINO
	AND CIT86OSALM_KKNG.ITEMCODE = ITEM.ITEMCODE(+)
	AND ITEM.SYUTOKU_KBN(+) = 'PORT'
),
T2 AS
(
SELECT
	SSMTBSALMEI.sal_no AS OURINO,
	NVL(SSMTBSALMEI.sal_meirow_no, 0) AS GYONO,
	SSMTBSALMEI.hin_cd AS ITEMCODE,
	NULL AS ITEMCODE_HANBAI,
	CASE 
		WHEN SSMTBSALMEI.hin_cd LIKE '9%'
			AND ITEM.ITEMKBN = '08'
			THEN 0
		ELSE NVL(SSMTBSALMEI.sal_qut_sm, 0)
		END AS SURYO,
	NVL(SSMTBSALMEI.sal_prc, 0) AS TANKA,
	0 AS HENSU,
	0 AS HENUSU,
	NVL(SSMTBSALMEI.sal_kin, 0) AS KINGAKU,
	NVL(SSMTBSALMEI.shoumi_sal_kin, 0) AS MEISAINUKIKINGAKU,
	NVL(SSMTBSALMEI.sal_sz_kin, 0) AS MEISAITAX,
	NVL(SSMTBSALMEI.sal_prc_ksai, 0) AS TANKA_TUKA,
	NVL(SSMTBSALMEI.sal_kin_ksai, 0) AS KINGAKU_TUKA,
	NVL(SSMTBSALMEI.shoumi_sal_kin_ksai, 0) AS MEISAINUKIKINGAKU_TUKA,
	NVL(SSMTBSALMEI.sal_sz_kin_ksai, 0) AS MEISAITAX_TUKA,
	0 AS KAKOKBN,
	NVL(DECODE(ZCMMNTORISK.BUNR_VAL_CD3, '40', '2', '1'), '1') AS KKNG_KBN,
	SSMTBSALMEI.sal_no AS DISPOURINO,
	NVL(SSMTBSALMEI.sky_kisan_dt, 0) AS SHIMEBI,
	NVL(SSMTBSALMEI.DEN_NB_AB_AF_SAL_KIN, 0) AS ANBUNMEISAINUKIKINGAKU,
	2 AS MARKER,
	NULL AS ROWID1,
	NULL AS ROWID2,
	NULL AS ROWID3,
	NULL AS ROWID4,
	NULL AS ROWID5,
	NULL AS ROWID6,
	SSMTBSALMEI.SHOHZEI_RITSU AS SHOHZEI_RITSU

FROM SSMTHSALHEDDA ,
	SSMTBSALMEI ,
	SSMTHDCLTHANJUCHHEDDA ,
	ZCMMNTORISK ,
	HANYO_ATTR DAILY,
	HANYO_ATTR KAISYA,
	CIM03ITEM_ZAIKO ITEM

WHERE SUBSTRING(SSMTHSALHEDDA.touroku_date, 1, 8) >= DAILY.ATTR3
	AND DAILY.KBNMEI = 'DAILYFROM'
	AND SSMTHSALHEDDA.kaisha_cd = KAISYA.ATTR1
	AND KAISYA.KBNMEI = 'KAISYA'
	AND SSMTHSALHEDDA.rend_mt_den_shubt = '105' 
	AND SSMTHSALHEDDA.CAN_FLG = '0' 
	AND SSMTHSALHEDDA.kaisha_cd = SSMTHDCLTHANJUCHHEDDA.kaisha_cd(+) 
	AND SSMTHSALHEDDA.hassei_mt_den_no = SSMTHDCLTHANJUCHHEDDA.juch_no(+) 
	AND SSMTHDCLTHANJUCHHEDDA.juch_no IS NULL
	AND (
		SSMTHSALHEDDA.tokuisk_cd <> 'BI00000001'
		AND SSMTHSALHEDDA.tokuisk_cd <> 'BI00000002'
		AND SSMTHSALHEDDA.tokuisk_cd <> 'BI00000003'
		)
	AND SSMTHSALHEDDA.kaisha_cd = SSMTBSALMEI.kaisha_cd 
	AND SSMTHSALHEDDA.sal_no = SSMTBSALMEI.sal_no 
	AND SSMTHSALHEDDA.kaisha_cd = ZCMMNTORISK.kaisha_cd(+) 
	AND SSMTHSALHEDDA.tokuisk_cd = ZCMMNTORISK.torisk_cd(+) 
	AND SSMTBSALMEI.hin_cd = ITEM.ITEMCODE(+)
	AND ITEM.SYUTOKU_KBN(+) = 'PORT'
),
T3 AS
(
SELECT
	
	SSMTBSALMEI.sal_no AS OURINO,
	NVL(SSMTBSALMEI.sal_meirow_no, 0) AS GYONO,
	SSMTBSALMEI.hin_cd AS ITEMCODE,
	NULL AS ITEMCODE_HANBAI,
	CASE 
		WHEN SSMTBSALMEI.hin_cd LIKE '9%'
			AND ITEM.ITEMKBN = '08'
			THEN 0
		ELSE NVL(SSMTBSALMEI.sal_qut_sm, 0)
		END AS SURYO,
	NVL(SSMTBSALMEI.sal_prc, 0) AS TANKA,
	0 AS HENSU,
	0 AS HENUSU,
	NVL(SSMTBSALMEI.sal_kin, 0) AS KINGAKU,
	NVL(SSMTBSALMEI.shoumi_sal_kin, 0) AS MEISAINUKIKINGAKU,
	NVL(SSMTBSALMEI.sal_sz_kin, 0) AS MEISAITAX,
	NVL(SSMTBSALMEI.sal_prc_ksai, 0) AS TANKA_TUKA,
	NVL(SSMTBSALMEI.sal_kin_ksai, 0) AS KINGAKU_TUKA,
	NVL(SSMTBSALMEI.shoumi_sal_kin_ksai, 0) AS MEISAINUKIKINGAKU_TUKA,
	NVL(SSMTBSALMEI.sal_sz_kin_ksai, 0) AS MEISAITAX_TUKA,
	0 AS KAKOKBN,
	NVL(DECODE(ZCMMNTORISK.BUNR_VAL_CD3, '40', '2', '1'), '1') AS KKNG_KBN,
	SSMTBSALMEI.sal_no AS DISPOURINO,
	NVL(SSMTBSALMEI.sky_kisan_dt, 0) AS SHIMEBI,
	NVL(SSMTBSALMEI.DEN_NB_AB_AF_SAL_KIN, 0) AS ANBUNMEISAINUKIKINGAKU,
	3 AS MARKER,
	NULL AS ROWID1,
	NULL AS ROWID2,
	NULL AS ROWID3,
	NULL AS ROWID4,
	NULL AS ROWID5,
	NULL AS ROWID6,
	SSMTBSALMEI.SHOHZEI_RITSU AS SHOHZEI_RITSU
FROM SSMTHSALHEDDA ,
	SSMTBSALMEI ,
	C_TBECKESAI ,
	ZCMMNTORISK ,
	HANYO_ATTR DAILY,
	HANYO_ATTR KAISYA,
	CIM03ITEM_ZAIKO ITEM

WHERE SUBSTRING(SSMTHSALHEDDA.touroku_date, 1, 8) >= DAILY.ATTR3
	AND DAILY.KBNMEI = 'DAILYFROM'
	
	AND SSMTHSALHEDDA.kaisha_cd = KAISYA.ATTR1
	AND KAISYA.KBNMEI = 'KAISYA'
	AND SSMTHSALHEDDA.rend_mt_den_shubt IS NULL 
	AND SSMTHSALHEDDA.CAN_FLG = '0' 
	AND SSMTHSALHEDDA.SAL_JISK_IMP_SNSH_NO = CAST(C_TBECKESAI.C_DIKESAIID AS VARCHAR) 
	AND SSMTHSALHEDDA.kaisha_cd = SSMTBSALMEI.kaisha_cd 
	AND SSMTHSALHEDDA.sal_no = SSMTBSALMEI.sal_no 
	AND SSMTHSALHEDDA.kaisha_cd = ZCMMNTORISK.kaisha_cd(+) 
	AND SSMTHSALHEDDA.tokuisk_cd = ZCMMNTORISK.torisk_cd(+) 
	AND (
		SSMTHSALHEDDA.tokuisk_cd <> 'BI00000001'
		AND SSMTHSALHEDDA.tokuisk_cd <> 'BI00000002'
		AND SSMTHSALHEDDA.tokuisk_cd <> 'BI00000003'
		) 
	AND SSMTBSALMEI.hin_cd = ITEM.ITEMCODE(+)
	AND ITEM.SYUTOKU_KBN(+) = 'PORT'

),
T4 AS
(
SELECT
	
	SSMTBSALMEI.sal_no AS OURINO,
	NVL(SSMTBSALMEI.sal_meirow_no, 0) AS GYONO,
	SSMTBSALMEI.hin_cd AS ITEMCODE,
	NULL AS ITEMCODE_HANBAI,
	CASE 
		WHEN SSMTBSALMEI.hin_cd LIKE '9%'
			AND ITEM.ITEMKBN = '08'
			THEN 0
		ELSE NVL(SSMTBSALMEI.sal_qut_sm, 0)
		END AS SURYO,
	NVL(SSMTBSALMEI.sal_prc, 0) AS TANKA,
	0 AS HENSU,
	0 AS HENUSU,
	NVL(SSMTBSALMEI.sal_kin, 0) AS KINGAKU,
	NVL(SSMTBSALMEI.shoumi_sal_kin, 0) AS MEISAINUKIKINGAKU,
	NVL(SSMTBSALMEI.sal_sz_kin, 0) AS MEISAITAX,
	NVL(SSMTBSALMEI.sal_prc_ksai, 0) AS TANKA_TUKA,
	NVL(SSMTBSALMEI.sal_kin_ksai, 0) AS KINGAKU_TUKA,
	NVL(SSMTBSALMEI.shoumi_sal_kin_ksai, 0) AS MEISAINUKIKINGAKU_TUKA,
	NVL(SSMTBSALMEI.sal_sz_kin_ksai, 0) AS MEISAITAX_TUKA,
	0 AS KAKOKBN,
	NVL(DECODE(ZCMMNTORISK.BUNR_VAL_CD3, '40', '2', '1'), '1') AS KKNG_KBN,
	SSMTBSALMEI.sal_no AS DISPOURINO,
	NVL(SSMTBSALMEI.sky_kisan_dt, 0) AS SHIMEBI,
	NVL(SSMTBSALMEI.DEN_NB_AB_AF_SAL_KIN, 0) AS ANBUNMEISAINUKIKINGAKU,
	4 AS MARKER,
	NULL AS ROWID1,
	NULL AS ROWID2,
	NULL AS ROWID3,
	NULL AS ROWID4,
	NULL AS ROWID5,
	NULL AS ROWID6,
	SSMTBSALMEI.SHOHZEI_RITSU AS SHOHZEI_RITSU
FROM SSMTHSALHEDDA ,
	SSMTBSALMEI ,
	C_TBECKESAI ,
	ZCMMNTORISK ,
	HANYO_ATTR DAILY,
	HANYO_ATTR KAISYA,
	ZCMMNSOSHITAIK ,
	CIM03ITEM_ZAIKO ITEM

WHERE SUBSTRING(SSMTHSALHEDDA.touroku_date, 1, 8) >= DAILY.ATTR3
	AND DAILY.KBNMEI = 'DAILYFROM'
	AND SSMTHSALHEDDA.kaisha_cd = KAISYA.ATTR1
	AND KAISYA.KBNMEI = 'KAISYA'
	AND SSMTHSALHEDDA.rend_mt_den_shubt IS NULL 
	AND SSMTHSALHEDDA.SAL_SHUR_KBN = '2' 
	AND SSMTHSALHEDDA.CAN_FLG = '0' 
	
	AND SSMTHSALHEDDA.SAL_JISK_IMP_SNSH_NO = CAST(C_TBECKESAI.C_DIKESAIID(+) AS VARCHAR)
	AND CAST(C_TBECKESAI.C_DIKESAIID AS VARCHAR) IS NULL
	AND SSMTHSALHEDDA.kaisha_cd = SSMTBSALMEI.kaisha_cd 
	AND SSMTHSALHEDDA.sal_no = SSMTBSALMEI.sal_no 
	
	AND SSMTHSALHEDDA.kaisha_cd = ZCMMNTORISK.kaisha_cd(+) 
	AND SSMTHSALHEDDA.tokuisk_cd = ZCMMNTORISK.torisk_cd(+) 
	
	AND SSMTHSALHEDDA.SAL_JISK_IMP_SNSH_NO = CAST(C_TBECKESAI.C_DIKESAIID(+) AS VARCHAR)
	AND CAST(C_TBECKESAI.C_DIKESAIID AS VARCHAR) IS NULL
	AND (
		SSMTHSALHEDDA.tokuisk_cd <> 'BI00000001'
		AND SSMTHSALHEDDA.tokuisk_cd <> 'BI00000002'
		AND SSMTHSALHEDDA.tokuisk_cd <> 'BI00000003'
		) 
	AND SSMTHSALHEDDA.KAISHA_CD = ZCMMNSOSHITAIK.KAISHA_CD(+) 
	AND SSMTHSALHEDDA.SAL_BMN_NAIBU_NO = ZCMMNSOSHITAIK.BMN_NAIBUKANRI_NO(+) 

	AND NOT (
		SSMTHSALHEDDA.tokuisk_cd = 'FS00000001'
		AND ZCMMNSOSHITAIK.BMN_HYOUJI_CD NOT IN (
			SELECT ATTR1
			FROM HANYO_ATTR
			WHERE KBNMEI = 'FAMILYSALE'
				AND (
					ATTR3 = '卸FS'
					OR ATTR3 = '店舗FS'
					)
			)
		)
	AND SSMTBSALMEI.hin_cd = ITEM.ITEMCODE(+)
	AND ITEM.SYUTOKU_KBN(+) = 'PORT'
),
UNION_OF AS
(
    SELECT * FROM T1 
    UNION ALL 
    SELECT * FROM T2 
    UNION ALL 
    SELECT * FROM T3 
    UNION ALL 
    SELECT * FROM T4 
),
FINAL AS
(
    SELECT OURINO::VARCHAR(18) AS OURINO,
        GYONO::NUMBER(18,0) AS GYONO,
        ITEMCODE::VARCHAR(45) AS ITEMCODE,
        ITEMCODE_HANBAI::VARCHAR(45) AS ITEMCODE_HANBAI,
        SURYO::NUMBER(22,3) AS SURYO,
        TANKA::NUMBER(22,3) AS TANKA,
        HENSU::NUMBER(38,0) AS HENSU,
        HENUSU::NUMBER(38,0) AS HENUSU,
        KINGAKU::NUMBER(13,2) AS KINGAKU,
        MEISAINUKIKINGAKU::NUMBER(13,2) AS MEISAINUKIKINGAKU,
        MEISAITAX::NUMBER(21,2) AS MEISAITAX,
        TANKA_TUKA::NUMBER(22,3) AS TANKA_TUKA,
        KINGAKU_TUKA::NUMBER(13,2) AS KINGAKU_TUKA,
        MEISAINUKIKINGAKU_TUKA::NUMBER(13,2) AS MEISAINUKIKINGAKU_TUKA,
        MEISAITAX_TUKA::NUMBER(21,2) AS MEISAITAX_TUKA,
        KAKOKBN::NUMBER(18,0) AS KAKOKBN,
        KKNG_KBN::VARCHAR(1) AS KKNG_KBN,
        DISPOURINO::VARCHAR(18) AS DISPOURINO,
        SHIMEBI::NUMBER(18,0) AS SHIMEBI,
        ANBUNMEISAINUKIKINGAKU::NUMBER(13,2) AS ANBUNMEISAINUKIKINGAKU,
        MARKER::NUMBER(18,0) AS MARKER,
        ROWID1::VARCHAR(1) AS ROWID1,
        ROWID2::VARCHAR(1) AS ROWID2,
        ROWID3::VARCHAR(1) AS ROWID3,
        ROWID4::VARCHAR(1) AS ROWID4,
        ROWID5::VARCHAR(1) AS ROWID5,
        ROWID6::VARCHAR(1) AS ROWID6,
        SHOHZEI_RITSU::NUMBER(4,2) AS SHOHZEI_RITSU,
        CURRENT_TIMESTAMP()::TIMESTAMP_TZ(9) AS INSERTED_DATE,
        'ETL_Batch'::VARCHAR(100) AS INSERTED_BY,
        CURRENT_TIMESTAMP()::TIMESTAMP_TZ(9) AS UPDATED_DATE,
        NULL::VARCHAR(100) AS UPDATED_BY
    FROM UNION_OF
)
SELECT * FROM FINAL