WITH KR_054_ALLADM
AS (
    SELECT *
    FROM JPDCLEDW_INTEGRATION.KR_054_ALLADM
    ),
KR_054_SFUYO_MEISAI
AS (
    SELECT *
    FROM JPDCLEDW_INTEGRATION.KR_054_SFUYO_MEISAI
    ),
TBUSRPRAM
AS (
    SELECT *
    FROM JPDCLITG_INTEGRATION.TBUSRPRAM
    ),
FINAL
AS (
    SELECT ADM.DIECUSRID AS DIECUSRID,
        SUBSTRING(ADM.C_DSPOINTLIMITDATE, 1, 6) AS YOTEI_YM,
        SUBSTRING(ADM.C_DSPOINTLIMITDATE, 1, 4) AS YOTEI_YY,
        SUBSTRING(ADM.C_DSPOINTLIMITDATE, 5, 2) AS YOTEI_MM,
        WK.POINT_YM AS POINT_YM,
        WK.POINT_YY AS POINT_YY,
        WK.POINT_MM AS POINT_MM,
        ADM.DIREMNANTPOINT AS YPOINT,
        ADM.C_DIPOINTISSUEID AS YPOINT_ID
    FROM KR_054_ALLADM ADM
    INNER JOIN KR_054_SFUYO_MEISAI WK ON ADM.DIECUSRID = WK.DIECUSRID
        AND ADM.C_DIPOINTISSUEID = WK.POINT_ID
    WHERE 1 = 1
        AND ADM.DIELIMFLG = '0'
        AND ADM.DIVALIDFLG = '1'
        AND ADM.DIPOINTCODE = '1'
        AND ADM.DIREMNANTPOINT <> 0
        AND SUBSTRING(ADM.C_DSPOINTLIMITDATE, 1, 4) >= '2020'
        AND WK.DIECUSRID IN (
            SELECT USR.DIUSRID
            FROM TBUSRPRAM USR
            WHERE 1 = 1
                AND USR.DIELIMFLG = '0'
                AND USR.DISECESSIONFLG = '0'
                AND USR.DSDAT93 = '通常ユーザ'
            )
    )
SELECT *
FROM FINAL
