{{
    config(
        sql_header="USE WAREHOUSE "+ env_var("DBT_ENV_CORE_DB_MEDIUM_WH")+ ";",
    )
}}

with c_tbecordermeisaihistory as(
    select * from {{ ref('jpndclitg_integration__c_tbecordermeisaihistory') }}
),
c_tbeckesaihistory as(
    select * from {{ ref('jpndclitg_integration__c_tbeckesaihistory') }}
),
c_tbecorderhistory as(
    select * from {{ ref('jpndclitg_integration__c_tbecorderhistory') }}
),
tbecorder as(
    select * from {{ ref('jpndclitg_integration__tbecorder') }}
),
kesai_h_data_mart_sub_n_rirek as(
    select * from {{ ref('jpndcledw_integration__kesai_h_data_mart_sub_n_rirek') }}
),
c_tbecprivilegekesaihistory as(
    select * from {{ ref('jpndclitg_integration__c_tbecprivilegekesaihistory') }}
),
c_tbecprivilegemst as(
    select * from {{ ref('jpndclitg_integration__c_tbecprivilegemst') }}
),
kesaiid_dummy as(
    select * from {{ ref('jpndcledw_integration__kesaiid_dummy') }}
),
union1 as(
    SELECT 'U' || CAST((TBECORDERMEISAI.C_DIKESAIID) AS VARCHAR) AS SALENO,
	NVL(TBECORDERMEISAI.DIMEISAIID, 0) AS GYONO,
	CASE 
		WHEN TBECORDERMEISAI.C_DSPOINTITEMFLG = '0'
			THEN '商品'
		ELSE 'ポイント交換商品'
		END AS MEISAIKBN,
	TBECORDERMEISAI.DSITEMID AS ITEMCODE, --商品ID
	TBECORDERMEISAI.DSITEMNAME AS ITEMNAME, --商品名
	CAST((TBECORDERMEISAI.DIID) AS VARCHAR) AS DIID, --商品内部ID
	CAST((TBECORDERMEISAI.DISETID) AS VARCHAR) AS DISETID,--セット商品内部ID
	TBECORDERMEISAI.DIITEMNUM AS SURYO,
	--分解前
	DECODE(TBECORDERMEISAI.DIITEMNUM, 0, 0, (NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC, 0) - NVL(TBECORDERMEISAI.C_DIDISCOUNTMEISAI, 0)) / NVL(TBECORDERMEISAI.DIITEMNUM, 1)) AS TANKA, --割引後税込単価：(小計(税込）- 割引額) / 数量
	DECODE(TBECORDERMEISAI.C_DINOSHINSHOITEMPRC, 0, 0, NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC, 0) - NVL(TBECORDERMEISAI.C_DIDISCOUNTMEISAI, 0)) AS KINGAKU,
	CASE 
		--商品の場合
		WHEN TBECORDERMEISAI.C_DSPOINTITEMFLG = '0'
			THEN DECODE(TBECORDERMEISAI.C_DINOSHINSHOITEMPRC, 0, 0, CEIL(((NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC, 0) - NVL(TBECORDERMEISAI.C_DIDISCOUNTMEISAI, 0)) / ((100 + TBECORDER.DITAXRATE) / (1.0 * 100)))))
				--ポイント交換商品
		ELSE ((NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC, 0) - NVL(TBECORDERMEISAI.C_DIDISCOUNTMEISAI, 0)))
		END MEISAINUKIKINGAKU,
	DECODE(TBECORDERMEISAI.C_DINOSHINSHOITEMPRC, 0, 0, NVL(TBECORDERMEISAI.C_DIDISCOUNTRATE, 0)) AS WARIRITU,
	NVL(TBECORDERMEISAI.DITOTALPRC, 0) AS WARIMAEKOMITANKA --割引前税込単価：単価(税込)
	,
	CASE 
		--商品の場合
		WHEN TBECORDERMEISAI.C_DSPOINTITEMFLG = '0'
			THEN DECODE(TBECORDERMEISAI.C_DINOSHINSHOITEMPRC, 0, 0, NVL((TBECORDERMEISAI.C_DIITEMTOTALPRC - (TBECORDERMEISAI.DIITEMTAX * NVL(TBECORDERMEISAI.DIITEMNUM, 1))), 0))
				--ポイント交換商品
		ELSE NVL((TBECORDERMEISAI.DIUSUALPRC * TBECORDERMEISAI.DIITEMNUM), 0)
		END WARIMAENUKIKINGAKU,
	DECODE(TBECORDERMEISAI.C_DINOSHINSHOITEMPRC, 0, 0, NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC, 0)) AS WARIMAEKOMIKINGAKU
	--分解後
	,
	DECODE(TBECORDERMEISAI.DIITEMNUM, 0, 0, (NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC + TBECORDERMEISAI.C_DIADJUSTPRC, 0) - NVL(TBECORDERMEISAI.C_DIDISCOUNTMEISAI, 0)) / NVL(TBECORDERMEISAI.DIITEMNUM, 1)) AS BUN_TANKA --割引後税込単価：(小計(税込）- 割引額) / 数量
	,
	NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC + TBECORDERMEISAI.C_DIADJUSTPRC, 0) - NVL(TBECORDERMEISAI.C_DIDISCOUNTMEISAI, 0) AS BUN_KINGAKU,
	CASE 
		--商品の場合
		WHEN TBECORDERMEISAI.C_DSPOINTITEMFLG = '0'
			THEN CEIL(((NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC + TBECORDERMEISAI.C_DIADJUSTPRC, 0) - NVL(TBECORDERMEISAI.C_DIDISCOUNTMEISAI, 0)) / ((100 + TBECORDER.DITAXRATE) / (1.0 * 100))))
				--ポイント交換商品
		ELSE ((NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC + TBECORDERMEISAI.C_DIADJUSTPRC, 0) - NVL(TBECORDERMEISAI.C_DIDISCOUNTMEISAI, 0)))
		END BUN_MEISAINUKIKINGAKU,
	NVL(TBECORDERMEISAI.C_DIDISCOUNTRATE, 0) AS BUN_WARIRITU,
	NVL(TBECORDERMEISAI.DITOTALPRC + TBECORDERMEISAI.C_DIADJUSTPRC, 0) AS BUN_WARIMAEKOMITANKA --割引前税込単価：単価(税込)
	,
	CASE 
		--商品の場合
		WHEN TBECORDERMEISAI.C_DSPOINTITEMFLG = '0'
			THEN NVL((TBECORDERMEISAI.C_DIITEMTOTALPRC + TBECORDERMEISAI.C_DIADJUSTPRC - (TBECORDERMEISAI.DIITEMTAX * NVL(TBECORDERMEISAI.DIITEMNUM, 1))), 0)
				--ポイント交換商品
		ELSE NVL(((TBECORDERMEISAI.DIUSUALPRC + TBECORDERMEISAI.C_DIADJUSTPRC) * TBECORDERMEISAI.DIITEMNUM), 0)
		END BUN_WARIMAENUKIKINGAKU,
	NVL(TBECORDERMEISAI.C_DIITEMTOTALPRC + TBECORDERMEISAI.C_DIADJUSTPRC, 0) AS BUN_WARIMAEKOMIKINGAKU,
	CAST((TBECORDERMEISAI.C_DIKESAIID) AS VARCHAR) AS DISPSALENO
	--BGN MOD 20190325 takano ***課題0027***
	--     , TBECORDERMEISAI.C_DIKESAIID                 AS KESAIID
	,
	CAST((TBECORDERMEISAI.C_DIKESAIID) AS VARCHAR) AS KESAIID,
	--END MOD 20190325 takano ***課題0027***
	TBECORDER.DIORDERID AS DIORDERID, --受注内部ID
	TBECORDERMEISAI.C_DSPOINTITEMFLG AS C_DSPOINTITEMFLG, --ポイント交換商品フラグ
	TBECORDERMEISAI.C_DIITEMTYPE AS C_DIITEMTYPE, --商品区分
	TBECORDERMEISAI.C_DIADJUSTPRC AS C_DIADJUSTPRC, --調整金額
	TBECORDERMEISAI.DITOTALPRC AS DITOTALPRC, --税込み額
	TBECORDERMEISAI.DIITEMTAX AS DIITEMTAX, --消費税額
	TBECORDERMEISAI.C_DIITEMTOTALPRC AS C_DIITEMTOTALPRC, --販売小計(税込)
	TBECORDERMEISAI.C_DIDISCOUNTMEISAI AS C_DIDISCOUNTMEISAI, --割引金額
	TBECORDERMEISAI.DISETMEISAIID AS DISETMEISAIID, --親行取得用
	TBECORDERMEISAI.C_DSSETITEMKBN AS C_DSSETITEMKBN, --セット品区分
	1 AS MAKER --マーカー
	--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--DnA側でデータマートを作成するため廃止
	--, CAST((GREATEST(
	--         NVL(TBECORDERMEISAI.JOIN_REC_UPDDATE_SUB1,0)
	--       , CAST((NVL(CAST((NVL(C_TBECKESAI.DSREN,C_TBECKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(TBECORDER.DSREN,TBECORDER.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , NVL(RIREKI.JOIN_REC_UPDDATE,0)
	--   ))                                         AS JOIN_REC_UPDDATE  --結合レコード更新日時(JJ連携の差分抽出に使用)
	---END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--決済情報に存在する受注明細情報のみ
FROM (
	SELECT MEISAI.DIORDERHISTID,
		MEISAI.DIMEISAIID,
		MEISAI.DIORDERID,
		MEISAI.DISETID,
		MEISAI.DIID,
		MEISAI.DSITEMID,
		MEISAI.DSITEMNAME, --商品名
		MEISAI.DITOTALPRC,
		MEISAI.DIITEMTAX,
		MEISAI.DIITEMNUM,
		MEISAI.C_DIITEMTOTALPRC,
		MEISAI.C_DIDISCOUNTMEISAI,
		NVL(MEISAI.C_DIKESAIID, KESAI.C_DIKESAIID) AS C_DIKESAIID,
		MEISAI.C_DSPOINTITEMFLG,
		MEISAI.DICANCEL,
		MEISAI.C_DINOSHINSHOITEMPRC,
		MEISAI.C_DIDISCOUNTRATE,
		MEISAI.DIELIMFLG,
		MEISAI.C_DIADJUSTPRC, --調整金額
		MEISAI.C_DIITEMTYPE, --商品区分
		MEISAI.DISETMEISAIID, --親行取得用
		MEISAI.C_DSSETITEMKBN, --セット品区分
		MEISAI.DIUSUALPRC --ポイント交換商品
		--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
		--DnA側でデータマートを作成するため廃止
		--       , CAST((GREATEST(
		--                 CAST((NVL(CAST((NVL(MEISAI.DSREN,MEISAI.DSPREP),'YYYYMMDDHH24MISS'),0))
		--              ,  CAST((NVL(CAST((NVL(KESAI.DSREN,KESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
		--              ,  CAST((NVL(CAST((NVL(HEADER.DSREN,HEADER.DSPREP),'YYYYMMDDHH24MISS'),0))
		--          )) AS JOIN_REC_UPDDATE_SUB1
		--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	FROM C_TBECORDERMEISAIHISTORY MEISAI
	LEFT OUTER JOIN (
		SELECT DIORDERID,
			MIN(C_DIKESAIID) AS C_DIKESAIID
		--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
		--DnA側でデータマートを作成するため廃止
		--                         , MAX(DSPREP)      AS DSPREP
		--                         , MAX(DSREN)       AS DSREN
		--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
		FROM C_TBECKESAIHISTORY
		GROUP BY DIORDERID
		) KESAI ON MEISAI.DIORDERID = KESAI.DIORDERID
	LEFT OUTER JOIN TBECORDER HEADER ON HEADER.DIORDERID = MEISAI.DIORDERID
	JOIN KESAI_H_DATA_MART_SUB_N_RIREK RIREKI ON RIREKI.DIORDERHISTID = MEISAI.DIORDERHISTID --受注変更履歴.履歴ID = 受注明細情報履歴.履歴ID
		AND RIREKI.DIORDERID = MEISAI.DIORDERID --受注変更履歴.受注内部ID = 受注明細情報履歴.受注内部ID
	) TBECORDERMEISAI, --受注明細情報
	C_TBECKESAIHISTORY C_TBECKESAI, --決済情報
	C_TBECORDERHISTORY TBECORDER, --受注情報
	KESAI_H_DATA_MART_SUB_N_RIREK RIREKI --受注変更履歴
WHERE RIREKI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND RIREKI.DIORDERID = TBECORDER.DIORDERID --受注変更履歴.受注内部ID = 受注情報履歴.受注内部ID
	AND TBECORDERMEISAI.DIORDERID = TBECORDER.DIORDERID
	AND TBECORDERMEISAI.DIORDERHISTID = TBECORDER.DIORDERHISTID
	AND TBECORDERMEISAI.C_DIKESAIID = C_TBECKESAI.C_DIKESAIID --受注明細情報．決済ID = 決済情報．決済ID
	AND TBECORDERMEISAI.DIORDERHISTID = C_TBECKESAI.DIORDERHISTID --受注明細情報．決済ID = 決済情報．決済ID
	AND C_TBECKESAI.DICANCEL = '0' --決済情報.キャンセルフラグ = '0'(0:有効)
	--削除フラグ対応
	AND TBECORDER.DIELIMFLG = '0'
	AND C_TBECKESAI.DIELIMFLG = '0'
	AND TBECORDERMEISAI.DIELIMFLG = '0'
	AND TBECORDERMEISAI.DICANCEL = '0'
	AND (
		TBECORDERMEISAI.C_DIITEMTYPE <> '08'
		OR TBECORDERMEISAI.DISETID = TBECORDERMEISAI.DIID
		) --不要なダミーを除く
	--利用ポイント数(交換以外)
),
union2 as( 
SELECT 'U' || CAST((C_TBECKESAI.C_DIKESAIID) AS VARCHAR) AS SALENO,
	9000000001 AS GYONO,
	'利用ポイント数(交換以外)' AS MEISAIKBN,
	'X000000001' AS ITEMCODE,
	'利用ポイント数(交換以外)' AS ITEMNAME, --商品名
	'X000000001' AS DIID, --商品内部ID
	'X000000001' AS DISETID, --セット商品内部ID
	1 AS SURYO,
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS TANKA, --割引後税込単価：受注使用ポイント（交換以外）
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS KINGAKU ,--割引後明細税込金額：受注使用ポイント（交換以外）
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS MEISAINUKIKINGAKU, --割引後明細税抜金額：受注使用ポイント（交換以外）
	0 AS WARIRITU, --割引率：0(固定)
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS WARIMAEKOMITANKA ,--割引前税込単価：単価(税込)
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS WARIMAENUKIKINGAKU, --割引前明細税抜金額：販売価格（税抜）* 数量
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS WARIMAEKOMIKINGAKU ,--割引前明細税込金額：小計(税込）
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS BUN_TANKA, --割引後税込単価：受注使用ポイント（交換以外）
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS BUN_KINGAKU, --割引後明細税込金額：受注使用ポイント（交換以外）
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS BUN_MEISAINUKIKINGAKU, --割引後明細税抜金額：受注使用ポイント（交換以外）
	0 AS BUN_WARIRITU, --割引率：0(固定)
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS BUN_WARIMAEKOMITANKA ,--割引前税込単価：単価(税込)
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS BUN_WARIMAENUKIKINGAKU, --割引前明細税抜金額：販売価格（税抜）* 数量
	- NVL(C_TBECKESAI.DIUSEPOINT, 0) AS BUN_WARIMAEKOMIKINGAKU ,--割引前明細税込金額：小計(税込）
	CAST((C_TBECKESAI.C_DIKESAIID) AS VARCHAR) AS DISPSALENO,
	--BGN MOD 20190325 takano ***課題0027***
	--     , C_TBECKESAI.C_DIKESAIID                 AS KESAIID
	CAST((C_TBECKESAI.C_DIKESAIID) AS VARCHAR) AS KESAIID,
	--END MOD 20190325 takano ***課題0027***
	TBECORDER.DIORDERID AS DIORDERID, --受注内部ID
	'0' AS C_DSPOINTITEMFLG ,--ポイント交換商品フラグ
	'0' AS C_DIITEMTYPE, --商品区分
	0 AS C_DIADJUSTPRC, --調整金額
	0 AS DITOTALPRC ,--税込み額
	0 AS DIITEMTAX ,--消費税額
	0 AS C_DIITEMTOTALPRC ,--販売小計(税込)
	0 AS C_DIDISCOUNTMEISAI, --割引金額
	9000000001 AS DISETMEISAIID, --親行取得用
	'DUMMY' AS C_DSSETITEMKBN, --セット品区分
	2 AS MAKER --マーカー
	--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--DnA側でデータマートを作成するため廃止
	--, CAST((GREATEST(
	--         CAST((NVL(CAST((NVL(C_TBECKESAI.DSREN,C_TBECKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(TBECORDER.DSREN,TBECORDER.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , NVL(RIREKI.JOIN_REC_UPDDATE,0)
	--   ))                                     AS JOIN_REC_UPDDATE  --結合レコード更新日時(JJ連携の差分抽出に使用)
	--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
FROM C_TBECKESAIHISTORY C_TBECKESAI, --決済履歴情報
	C_TBECORDERHISTORY TBECORDER, --受注履歴情報
	KESAI_H_DATA_MART_SUB_N_RIREK RIREKI --受注変更履歴
WHERE C_TBECKESAI.DIORDERID = TBECORDER.DIORDERID --決済情報.受注内部ID = 受注情報.受注内部ID
	AND RIREKI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DICANCEL = '0' --決済情報.キャンセルフラグ = '0'(0:有効)
	AND C_TBECKESAI.DIUSEPOINT <> 0 --決済情報.受注使用ポイント（交換以外） = 0以外
	AND C_TBECKESAI.DIELIMFLG = '0' --決済情報.削除フラグ = '0'(0:有効)
	AND TBECORDER.DIELIMFLG = '0' --受注情報.削除フラグ = '0'(0:有効)
	--利用ポイント数(交換)

),
union3 as(
SELECT 'U' || CAST((C_TBECKESAI.C_DIKESAIID) AS VARCHAR) AS SALENO,
	9000000002 AS GYONO,
	'利用ポイント数(交換)' AS MEISAIKUBUN,
	'X000000002' AS ITEMCODE,
	'利用ポイント数(交換)' AS ITEMNAME, --商品名
	'X000000002' AS DIID, --商品内部ID
	'X000000002' AS DISETID, --セット商品内部ID
	1 AS SURYO,
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS TANKA, --割引後税込単価：受注使用ポイント（交換）
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS KINGAKU, --割引後明細税込金額：受注使用ポイント（交換）
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS MEISAINUKIKINGAKU, --割引後明細税抜金額：受注使用ポイント（交換）
	0 AS WARIRITU, --割引率：0(固定)
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS WARIMAEKOMITANKA, --割引前税込単価：受注使用ポイント（交換）
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS WARIMAENUKIKINGAKU, --割引前明細税抜金額：受注使用ポイント（交換）
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS WARIMAEKOMIKINGAKU, --割引前明細税込金額：受注使用ポイント（交換）
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS BUN_TANKA, --割引後税込単価：受注使用ポイント（交換）
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS BUN_KINGAKU, --割引後明細税込金額：受注使用ポイント（交換）
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS BUN_MEISAINUKIKINGAKU, --割引後明細税抜金額：受注使用ポイント（交換）
	0 AS BUN_WARIRITU, --割引率：0(固定)
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS BUN_WARIMAEKOMITANKA, --割引前税込単価：受注使用ポイント（交換）
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS BUN_WARIMAENUKIKINGAKU, --割引前明細税抜金額：受注使用ポイント（交換）
	- NVL(C_TBECKESAI.C_DIEXCHANGEPOINT, 0) AS BUN_WARIMAEKOMIKINGAKU, --割引前明細税込金額：受注使用ポイント（交換）
	CAST((C_TBECKESAI.C_DIKESAIID) AS VARCHAR) AS DISPSALENO,
	--BGN MOD 20190325 takano ***課題0027***
	--     , C_TBECKESAI.C_DIKESAIID                , AS KESAIID
	CAST((C_TBECKESAI.C_DIKESAIID) AS VARCHAR) AS KESAIID,
	--END MOD 20190325 takano **,*課題0027***
	TBECORDER.DIORDERID AS DIORDERID, --受注内部ID
	'0' AS C_DSPOINTITEMFLG, --ポイント交換商品フラグ
	'0' AS C_DIITEMTYPE, --商品区分
	0 AS C_DIADJUSTPRC, --調整金額
	0 AS DITOTALPRC, --税込み額
	0 AS DIITEMTAX, --消費税額
	0 AS C_DIITEMTOTALPRC, --販売小計(税込)
	0 AS C_DIDISCOUNTMEISAI --割引金額
	,
	9000000002 AS DISETMEISAIID, --親行取得用
	'DUMMY' AS C_DSSETITEMKBN, --セット品区分
	3 AS MAKER --マーカー
	--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--DnA側でデータマートを作成するため廃止
	--, CAST((GREATEST(
	--         CAST((NVL(CAST((NVL(C_TBECKESAI.DSREN,C_TBECKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(TBECORDER.DSREN,TBECORDER.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , NVL(RIREKI.JOIN_REC_UPDDATE,0)
	--   ))                                     AS JOIN_REC_UPDDATE  --結合レコード更新日時(JJ連携の差分抽出に使用)
	--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
FROM C_TBECKESAIHISTORY C_TBECKESAI, --決済履歴情報
	C_TBECORDERHISTORY TBECORDER, --受注履歴情報
	KESAI_H_DATA_MART_SUB_N_RIREK RIREKI --受注変更履歴
WHERE C_TBECKESAI.DIORDERID = TBECORDER.DIORDERID
	AND RIREKI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DICANCEL = '0' --決済情報.キャンセルフラグ = '0'(0:有効)
	AND C_TBECKESAI.C_DIEXCHANGEPOINT <> 0 --決済情報.受注使用ポイント（交換） = 0以外
	AND C_TBECKESAI.DIELIMFLG = '0' --決済情報.削除フラグ = '0'(0:有効)
	AND TBECORDER.DIELIMFLG = '0' --受注情報.削除フラグ = '0'(0:有効)
),
union4 as(
    
--3.特典
SELECT 'U' || CAST((C_TBECKESAI.C_DIKESAIID) AS VARCHAR) AS SALENO,
	--BGN-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	--   , CAST((C_TBECPRIVILEGEORDERREL.DIPRIVILEGEID || C_TBECPRIVILEGEORDERREL.DIORDERID) AS GYONO
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID || C_TBECPRIVILEGEKESAI.DIORDERID) AS NUMERIC) AS GYONO,
	--END-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	'特典' AS MEISAIKBN,
	--BGN-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	--   , CAST((C_TBECPRIVILEGEORDERREL.DIPRIVILEGEID)                                        AS ITEMCODE
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID) AS VARCHAR) AS ITEMCODE,
	--END-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	'特典' AS ITEMNAME, --商品名
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID) AS VARCHAR) AS DIID ,--商品内部ID
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID) AS VARCHAR) AS DISETID, --セット商品内部ID
	--BGN-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	--   , NVL(C_TBECPRIVILEGEORDERREL.C_DIPRIVILEGENUM,0)                                       AS SURYO
	--   , DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU,3,
	--      -NVL(C_TBECPRIVILEGEORDERREL.C_DIPRIVILEGEPRC,0)
	--     ,0)                                                                                   AS TANKA              --割引後税込単価：特典付与マスタ.特典種別=3 (3:値引)の場合、-特典適用額
	--   , DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU,3,
	--      -NVL(C_TBECPRIVILEGEORDERREL.C_DIPRIVILEGEPRC,0)
	--     ,0)                                                                                   AS KINGAKU            --割引後明細税込金額：特典付与マスタ.特典種別=3 (3:値引)の場合、特典適用額
	--   , DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU,3,
	--      -CEIL(NVL(C_TBECPRIVILEGEORDERREL.C_DIPRIVILEGEPRC,0) / ((100+TBECORDER.DITAXRATE)/100))
	--     ,0)                                                                                   AS MEISAINUKIKINGAKU  --割引後明細税抜金額：特典付与マスタ.特典種別=3 (3:値引)の場合、特典適用額 / ((100 + 税率) / 100 )
	NVL(C_TBECPRIVILEGEKESAI.C_DIPRIVILEGENUM, 0) AS SURYO,
	DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU, 3, - NVL(C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEPRC, 0) --特典付与マスタ.特典種別=3 (3:値引)の場合、-特典適用額
		, 0) AS TANKA, --割引後税込単価：特典適用額
	--BGN-MOD 20180622 KOBAYASHI ***保守の変更管理(318)対応を反映****
	--     , DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU,3,-NVL(C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEPRC,0)             --特典付与マスタ.特典種別=3 (3:値引)の場合、特典適用額
	--       ,0)                                                                                   AS KINGAKU            --割引後明細税込金額：特典適用額
	--     , DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU,3,-CEIL(NVL(C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEPRC,0) / ((100+TBECORDER.DITAXRATE)/100)) --特典付与マスタ.特典種別=3 (3:値引)の場合、特典適用額 / ((100 + 税率) / 100 )
	--       ,0)                                                                                   AS MEISAINUKIKINGAKU --割引後明細税抜金額：特典適用額 / ((100 + 税率) / 100 )
	DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU, 3, - NVL(C_TBECPRIVILEGEKESAI.C_DIPRIVILEGETOTALPRC, 0) --特典付与マスタ.特典種別=3 (3:値引)の場合、特典適用額合計
		, 0) AS KINGAKU ,--割引後明細税込金額：特典適用額合計
	DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU, 3, - CEIL(NVL(C_TBECPRIVILEGEKESAI.C_DIPRIVILEGETOTALPRC, 0) / ((100 + TBECORDER.DITAXRATE) / (1.0 * 100))) --特典付与マスタ.特典種別=3 (3:値引)の場合、特典適用額合計 / ((100 + 税率) / 100 )
		, 0) AS MEISAINUKIKINGAKU, --割引後明細税抜金額：特典適用額合計 / ((100 + 税率) / 100 )
	--END-MOD 20180622 KOBAYASHI ***保守の変更管理(318)対応を反映****
	--END-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	0 AS WARIRITU ,--割引率：0(固定)
	0 AS WARIMAEKOMITANKA, --割引前税込単価：0(固定)
	0 AS WARIMAENUKIKINGAKU, --割引前明細税抜金額：0(固定)
	0 AS WARIMAEKOMIKINGAKU, --割引前明細税込金額：0(固定)
	DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU, 3, - NVL(C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEPRC, 0) --特典付与マスタ.特典種別=3 (3:値引)の場合、-特典適用額
		, 0) AS BUN_TANKA, --割引後税込単価：特典適用額
	DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU, 3, - NVL(C_TBECPRIVILEGEKESAI.C_DIPRIVILEGETOTALPRC, 0) --特典付与マスタ.特典種別=3 (3:値引)の場合、特典適用額合計
		, 0) AS BUN_KINGAKU ,--割引後明細税込金額：特典適用額合計
	DECODE(C_TBECPRIVILEGEMST.C_DIPRIVILEGESHUBETSU, 3, - CEIL(NVL(C_TBECPRIVILEGEKESAI.C_DIPRIVILEGETOTALPRC, 0) / ((100 + TBECORDER.DITAXRATE) / (1.0 * 100))) --特典付与マスタ.特典種別=3 (3:値引)の場合、特典適用額合計 / ((100 + 税率) / 100 )
		, 0) AS BUN_MEISAINUKIKINGAKU, --割引後明細税抜金額：特典適用額合計 / ((100 + 税率) / 100 )
	0 AS BUN_WARIRITU ,--割引率：0(固定)
	0 AS BUN_WARIMAEKOMITANKA, --割引前税込単価：0(固定)
	0 AS BUN_WARIMAENUKIKINGAKU, --割引前明細税抜金額：0(固定)
	0 AS BUN_WARIMAEKOMIKINGAKU ,--割引前明細税込金額：0(固定)
	CAST((C_TBECKESAI.C_DIKESAIID) AS VARCHAR) AS DISPSALENO,
	--BGN MOD 20190325 takano ***課題0027***
	--     , C_TBECKESAI.C_DIKESAIID                                                               AS KESAIID
	CAST((C_TBECKESAI.C_DIKESAIID) AS VARCHAR) AS KESAIID,
	--END MOD 20190325 takano ***課題0027***
	TBECORDER.DIORDERID AS DIORDERID, --受注内部ID
	'0' AS C_DSPOINTITEMFLG, --ポイント交換商品フラグ
	'0' AS C_DIITEMTYPE ,--商品区分
	0 AS C_DIADJUSTPRC, --調整金額
	0 AS DITOTALPRC, --税込み額
	0 AS DIITEMTAX, --消費税額
	0 AS C_DIITEMTOTALPRC, --販売小計(税込)
	0 AS C_DIDISCOUNTMEISAI, --割引金額
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID || C_TBECPRIVILEGEKESAI.DIORDERID) AS NUMERIC) AS DISETMEISAIID, --親行取得用
	'DUMMY' AS C_DSSETITEMKBN, --セット品区分
	4 AS MAKER --マーカー
	--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--DnA側でデータマートを作成するため廃止
	--, CAST((GREATEST(
	--         CAST((NVL(CAST((NVL(C_TBECKESAI.DSREN,C_TBECKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(TBECORDER.DSREN,TBECORDER.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(C_TBECPRIVILEGEKESAI.DSREN,C_TBECPRIVILEGEKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(C_TBECPRIVILEGEMST.DSREN,C_TBECPRIVILEGEMST.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , NVL(RIREKI.JOIN_REC_UPDDATE,0)
	--   ))                                                                                   AS JOIN_REC_UPDDATE  --結合レコード更新日時(JJ連携の差分抽出に使用)
	--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
FROM C_TBECKESAIHISTORY C_TBECKESAI, --決済履歴情報
	C_TBECORDERHISTORY TBECORDER ,--受注履歴情報
	--BGN-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	--  , C_TBECPRIVILEGEORDERRELHISTORY C_TBECPRIVILEGEORDERREL --特典履歴－受注関連
	C_TBECPRIVILEGEKESAIHISTORY C_TBECPRIVILEGEKESAI, --特典履歴－決済関連
	--END-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	C_TBECPRIVILEGEMST C_TBECPRIVILEGEMST, --特典付与マスタ
	KESAI_H_DATA_MART_SUB_N_RIREK RIREKI --受注変更履歴
WHERE C_TBECKESAI.DIORDERID = TBECORDER.DIORDERID
	AND RIREKI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	--BGN-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	--AND   TBECORDER.DIORDERID = C_TBECPRIVILEGEORDERREL.DIORDERID
	--AND   TBECORDER.DIORDERHISTID = C_TBECPRIVILEGEORDERREL.DIORDERHISTID
	--AND   C_TBECPRIVILEGEORDERREL.DIPRIVILEGEID = C_TBECPRIVILEGEMST.C_DIPRIVILEGEID
	AND C_TBECKESAI.C_DIKESAIID = C_TBECPRIVILEGEKESAI.C_DIKESAIID
	AND TBECORDER.DIORDERHISTID = C_TBECPRIVILEGEKESAI.DIORDERHISTID
	AND C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID = C_TBECPRIVILEGEMST.C_DIPRIVILEGEID
	--END-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	AND C_TBECKESAI.DICANCEL = '0' --決済情報.キャンセルフラグ = '0'(0:有効)
	--BGN-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	--AND   C_TBECPRIVILEGEORDERREL.C_DINONDISPFLG = '0' --特典-受注関連.非表示フラグ
	AND C_TBECPRIVILEGEKESAI.C_DINONDISPFLG = '0' --特典-決済関連.非表示フラグ
	--END-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	AND C_TBECKESAI.DIELIMFLG = '0' --決済情報.削除フラグ = '0'(0:有効)
	AND TBECORDER.DIELIMFLG = '0' --受注情報.削除フラグ = '0'(0:有効)
	--BGN-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	--AND   C_TBECPRIVILEGEORDERREL.DIELIMFLG = '0'      --特典.削除フラグ = '0'(0:有効)
	AND C_TBECPRIVILEGEKESAI.DIELIMFLG = '0' --特典-決済関連.削除フラグ = '0'(0:有効)
	--END-MOD 20180622 KOBAYASHI ***保守の変更管理(317)対応を反映****
	AND C_TBECPRIVILEGEMST.DIELIMFLG = '0' --特典付与マスタ.削除フラグ = '0'(0:有効)
	AND C_DSTEKIYOJYOGAIFLG = '0' --特典－受注関連.適用除外フラグ = '0'(0:除外しない)
	--BGN ADD 20190325 takano ***課題0027***
	--ダミーレコード行作成
	--金額、数量、ポイントは全て0
),
union5 as(
    
SELECT CAST(('U' || DUM.C_DIKESAIID_AFTER) AS VARCHAR) AS SALENO,
	NVL(TBECORDERMEISAI.DIMEISAIID, 0) AS GYONO,
	CASE 
		WHEN TBECORDERMEISAI.C_DSPOINTITEMFLG = '0'
			THEN '商品'
		ELSE 'ポイント交換商品'
		END AS MEISAIKBN,
	TBECORDERMEISAI.DSITEMID AS ITEMCODE, --商品ID
	TBECORDERMEISAI.DSITEMNAME AS ITEMNAME, --商品名
	CAST((TBECORDERMEISAI.DIID) AS VARCHAR) AS DIID ,--商品内部ID
	CAST((TBECORDERMEISAI.DISETID) AS VARCHAR) AS DISETID ,--セット商品内部ID
	0 AS SURYO,
	--分解前
	0 AS TANKA, --割引後税込単価
	0 AS KINGAKU,
	0 AS MEISAINUKIKINGAKU,
	0 AS WARIRITU,
	0 AS WARIMAEKOMITANKA, --割引前税込単価
	0 AS WARIMAENUKIKINGAKU,
	0 AS WARIMAEKOMIKINGAKU,
	--分解後
	0 AS BUN_TANKA, --割引後税込単価
	0 AS BUN_KINGAKU,
	0 AS BUN_MEISAINUKIKINGAKU,
	0 AS BUN_WARIRITU,
	0 AS BUN_WARIMAEKOMITANKA, --割引前税込単価
	0 AS BUN_WARIMAENUKIKINGAKU,
	0 AS BUN_WARIMAEKOMIKINGAKU,
	DUM.C_DIKESAIID_AFTER AS DISPSALENO,
	DUM.C_DIKESAIID_AFTER AS KESAIID,
	TBECORDER.DIORDERID AS DIORDERID, --受注内部ID
	TBECORDERMEISAI.C_DSPOINTITEMFLG AS C_DSPOINTITEMFLG ,--ポイント交換商品フラグ
	TBECORDERMEISAI.C_DIITEMTYPE AS C_DIITEMTYPE, --商品区分
	0 AS C_DIADJUSTPRC, --調整金額
	0 AS DITOTALPRC, --税込み額
	0 AS DIITEMTAX ,--消費税額
	0 AS C_DIITEMTOTALPRC, --販売小計(税込)
	0 AS C_DIDISCOUNTMEISAI, --割引金額
	TBECORDERMEISAI.DISETMEISAIID AS DISETMEISAIID ,--親行取得用
	TBECORDERMEISAI.C_DSSETITEMKBN AS C_DSSETITEMKBN, --セット品区分
	1 AS MAKER --マーカー
	--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--DnA側でデータマートを作成するため廃止
	--, CAST((GREATEST(
	--         NVL(TBECORDERMEISAI.JOIN_REC_UPDDATE_SUB2,0)
	--       , CAST((NVL(CAST((NVL(C_TBECKESAI.DSREN,C_TBECKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(TBECORDER.DSREN,TBECORDER.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , NVL(RIREKI.JOIN_REC_UPDDATE,0)
	--       , NVL(DUM.JOIN_REC_UPDDATE,0)
	--   ))                                                                                   AS JOIN_REC_UPDDATE  --結合レコード更新日時(JJ連携の差分抽出に使用)
	--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--決済情報に存在する受注明細情報のみ
FROM (
	SELECT MEISAI.DIORDERHISTID,
		MEISAI.DIMEISAIID,
		MEISAI.DIORDERID,
		MEISAI.DISETID,
		MEISAI.DIID,
		MEISAI.DSITEMID,
		MEISAI.DSITEMNAME, --商品名
		MEISAI.DITOTALPRC,
		MEISAI.DIITEMTAX,
		MEISAI.DIITEMNUM,
		MEISAI.C_DIITEMTOTALPRC,
		MEISAI.C_DIDISCOUNTMEISAI,
		NVL(MEISAI.C_DIKESAIID, KESAI.C_DIKESAIID) AS C_DIKESAIID,
		MEISAI.C_DSPOINTITEMFLG,
		MEISAI.DICANCEL,
		MEISAI.C_DINOSHINSHOITEMPRC,
		MEISAI.C_DIDISCOUNTRATE,
		MEISAI.DIELIMFLG,
		MEISAI.C_DIADJUSTPRC, --調整金額
		MEISAI.C_DIITEMTYPE, --商品区分
		MEISAI.DISETMEISAIID, --親行取得用
		MEISAI.C_DSSETITEMKBN, --セット品区分
		MEISAI.DIUSUALPRC --ポイント交換商品
		--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
		--DnA側でデータマートを作成するため廃止
		--       , CAST((GREATEST(
		--                 CAST((NVL(CAST((NVL(MEISAI.DSREN,MEISAI.DSPREP),'YYYYMMDDHH24MISS'),0))
		--              ,  CAST((NVL(CAST((NVL(KESAI.DSREN,KESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
		--              ,  CAST((NVL(CAST((NVL(HEADER.DSREN,HEADER.DSPREP),'YYYYMMDDHH24MISS'),0))
		--          )) AS JOIN_REC_UPDDATE_SUB2
		--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	FROM C_TBECORDERMEISAIHISTORY MEISAI
	LEFT OUTER JOIN (
		SELECT DIORDERID,
			MIN(C_DIKESAIID) AS C_DIKESAIID
		--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
		--DnA側でデータマートを作成するため廃止
		--                         , MAX(DSPREP)      AS DSPREP
		--                         , MAX(DSREN)       AS DSREN
		--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
		FROM C_TBECKESAIHISTORY
		GROUP BY DIORDERID
		) KESAI ON MEISAI.DIORDERID = KESAI.DIORDERID
	LEFT OUTER JOIN TBECORDER HEADER ON HEADER.DIORDERID = MEISAI.DIORDERID
	JOIN KESAI_H_DATA_MART_SUB_N_RIREK RIREKI ON RIREKI.DIORDERHISTID = MEISAI.DIORDERHISTID --受注変更履歴.履歴ID = 受注明細情報履歴.履歴ID
		AND RIREKI.DIORDERID = MEISAI.DIORDERID --受注変更履歴.受注内部ID = 受注明細情報履歴.受注内部ID
	) TBECORDERMEISAI, --受注明細情報
	C_TBECKESAIHISTORY C_TBECKESAI, --決済情報
	C_TBECORDERHISTORY TBECORDER, --受注情報
	KESAI_H_DATA_MART_SUB_N_RIREK RIREKI, --受注変更履歴
	--BGN-UPD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	(
		SELECT DISTINCT C_DIKESAIID_BEFORE,
			C_DIKESAIID_AFTER
		FROM KESAIID_DUMMY
		) DUM
--DnA側でデータマートを作成するため廃止
--, (SELECT C_DIKESAIID_BEFORE
--         ,C_DIKESAIID_AFTER
--         ,MAX(JOIN_REC_UPDDATE) AS JOIN_REC_UPDDATE
--    FROM KESAIID_DUMMY
--    GROUP BY C_DIKESAIID_BEFORE, C_DIKESAIID_AFTER)DUM
--END-UPD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
WHERE RIREKI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND RIREKI.DIORDERID = TBECORDER.DIORDERID --受注変更履歴.受注内部ID = 受注情報履歴.受注内部ID
	AND TBECORDERMEISAI.DIORDERID = TBECORDER.DIORDERID
	AND TBECORDERMEISAI.DIORDERHISTID = TBECORDER.DIORDERHISTID
	AND TBECORDERMEISAI.C_DIKESAIID = C_TBECKESAI.C_DIKESAIID --受注明細情報．決済ID = 決済情報．決済ID
	AND TBECORDERMEISAI.DIORDERHISTID = C_TBECKESAI.DIORDERHISTID --受注明細情報．決済ID = 決済情報．決済ID
	AND C_TBECKESAI.DICANCEL = '0' --決済情報.キャンセルフラグ = '0'(0:有効)
	AND TBECORDER.DIELIMFLG = '0'
	AND C_TBECKESAI.DIELIMFLG = '0'
	AND TBECORDERMEISAI.DIELIMFLG = '0'
	AND TBECORDERMEISAI.DICANCEL = '0'
	AND (
		TBECORDERMEISAI.C_DIITEMTYPE <> '08'
		OR TBECORDERMEISAI.DISETID = TBECORDERMEISAI.DIID
		) --不要なダミーを除く
	AND DUM.C_DIKESAIID_BEFORE = C_TBECKESAI.C_DIKESAIID
--利用ポイント数(交換以外)

),
union6 as(
    
SELECT CAST(('U' || DUM.C_DIKESAIID_AFTER) AS VARCHAR) AS SALENO,
	9000000001 AS GYONO,
	'利用ポイント数(交換以外)' AS MEISAIKBN,
	'X000000001' AS ITEMCODE,
	'利用ポイント数(交換以外)' AS ITEMNAME, --商品名
	'X000000001' AS DIID, --商品内部ID
	'X000000001' AS DISETID, --セット商品内部ID
	0 AS SURYO,
	0 AS TANKA, --割引後税込単価
	0 AS KINGAKU, --割引後明細税込金額
	0 AS MEISAINUKIKINGAKU, --割引後明細税抜金額
	0 AS WARIRITU, --割引率
	0 AS WARIMAEKOMITANKA, --割引前税込単価
	0 AS WARIMAENUKIKINGAKU, --割引前明細税抜金額
	0 AS WARIMAEKOMIKINGAKU, --割引前明細税込金額
	0 AS BUN_TANKA, --割引後税込単価
	0 AS BUN_KINGAKU, --割引後明細税込金額
	0 AS BUN_MEISAINUKIKINGAKU, --割引後明細税抜金額
	0 AS BUN_WARIRITU, --割引率
	0 AS BUN_WARIMAEKOMITANKA, --割引前税込単価
	0 AS BUN_WARIMAENUKIKINGAKU, --割引前明細税抜金額
	0 AS BUN_WARIMAEKOMIKINGAKU, --割引前明細税込金額
	DUM.C_DIKESAIID_AFTER AS DISPSALENO,
	DUM.C_DIKESAIID_AFTER AS KESAIID,
	TBECORDER.DIORDERID AS DIORDERID, --受注内部ID
	'0' AS C_DSPOINTITEMFLG, --ポイント交換商品フラグ
	'0' AS C_DIITEMTYPE, --商品区分
	0 AS C_DIADJUSTPRC, --調整金額
	0 AS DITOTALPRC, --税込み額
	0 AS DIITEMTAX, --消費税額
	0 AS C_DIITEMTOTALPRC, --販売,小計(税込)
	0 AS C_DIDISCOUNTMEISAI, --割引金額
	9000000001 AS DISETMEISAIID, --親行取得用
	'DUMMY' AS C_DSSETITEMKBN, --セット品区分
	2 AS MAKER --マーカー
	--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--DnA側でデータマートを作成するため廃止
	--, CAST((GREATEST(
	--         CAST((NVL(CAST((NVL(C_TBECKESAI.DSREN,C_TBECKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(TBECORDER.DSREN,TBECORDER.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , NVL(RIREKI.JOIN_REC_UPDDATE,0)
	--       , NVL(DUM.JOIN_REC_UPDDATE,0)
	--   ))                                                                                   AS JOIN_REC_UPDDATE  --結合レコード更新日時(JJ連携の差分抽出に使用)
	--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
FROM C_TBECKESAIHISTORY C_TBECKESAI, --決済履歴情報
	C_TBECORDERHISTORY TBECORDER, --受注履歴情報
	KESAI_H_DATA_MART_SUB_N_RIREK RIREKI, --受注変更履歴
	--BGN-UPD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	(
		SELECT DISTINCT C_DIKESAIID_BEFORE,
			C_DIKESAIID_AFTER
		FROM KESAIID_DUMMY
		) DUM
--DnA側でデータマートを作成するため廃止
--, (SELECT C_DIKESAIID_BEFORE
--         ,C_DIKESAIID_AFTER
--         ,MAX(JOIN_REC_UPDDATE) AS JOIN_REC_UPDDATE
--    FROM KESAIID_DUMMY
--    GROUP BY C_DIKESAIID_BEFORE, C_DIKESAIID_AFTER)DUM
--END-UPD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
WHERE C_TBECKESAI.DIORDERID = TBECORDER.DIORDERID --決済情報.受注内部ID = 受注情報.受注内部ID
	AND RIREKI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DICANCEL = '0' --決済情報.キャンセルフラグ = '0'(0:有効)
	AND C_TBECKESAI.DIUSEPOINT <> 0 --決済情報.受注使用ポイント（交換以外） = 0以外
	AND C_TBECKESAI.DIELIMFLG = '0' --決済情報.削除フラグ = '0'(0:有効)
	AND TBECORDER.DIELIMFLG = '0' --受注情報.削除フラグ = '0'(0:有効)
	AND DUM.C_DIKESAIID_BEFORE = C_TBECKESAI.C_DIKESAIID
--利用ポイント数(交換)

),
union7 as(
    
SELECT CAST(('U' || DUM.C_DIKESAIID_AFTER) AS VARCHAR) AS SALENO,
	9000000002 AS GYONO,
	'利用ポイント数(交換)' AS MEISAIKUBUN,
	'X000000002' AS ITEMCODE,
	'利用ポイント数(交換)' AS ITEMNAME, --商品名
	'X000000002' AS DIID, --商品内部ID
	'X000000002' AS DISETID, --セット商品内部ID
	0 AS SURYO,
	0 AS TANKA, --割引後税込単価
	0 AS KINGAKU, --割引後明細税込金額
	0 AS MEISAINUKIKINGAKU, --割引後明細税抜金額
	0 AS WARIRITU, --割引率
	0 AS WARIMAEKOMITANKA, --割引前税込単価
	0 AS WARIMAENUKIKINGAKU, --割引前明細税抜金額
	0 AS WARIMAEKOMIKINGAKU, --割引前明細税込金額
	0 AS BUN_TANKA, --割引後税込単価
	0 AS BUN_KINGAKU, --割引後明細税込金額
	0 AS BUN_MEISAINUKIKINGAKU, --割引後明細税抜金額
	0 AS BUN_WARIRITU, --割引率
	0 AS BUN_WARIMAEKOMITANKA, --割引前税込単価
	0 AS BUN_WARIMAENUKIKINGAKU, --割引前明細税抜金額
	0 AS BUN_WARIMAEKOMIKINGAKU, --割引前明細税込金額
	DUM.C_DIKESAIID_AFTER AS DISPSALENO,
	DUM.C_DIKESAIID_AFTER AS KESAIID,
	TBECORDER.DIORDERID AS DIORDERID, --受注内部ID
	'0' AS C_DSPOINTITEMFLG, --ポイント交換商品フラグ
	'0' AS C_DIITEMTYPE, --商品区分
	0 AS C_DIADJUSTPRC, --調整金額
	0 AS DITOTALPRC, --税込み額
	0 AS DIITEMTAX, --消費税額
	0 AS C_DIITEMTOTALPRC, --販売小計(税込)
	0 AS C_DIDISCOUNTMEISAI, --割引金額
	9000000002 AS DISETMEISAIID, --親行取得用
	'DUMMY' AS C_DSSETITEMKBN, --セット品区分
	3 AS MAKER --マーカー
	--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--DnA側でデータマートを作成するため廃止
	--, CAST((GREATEST(
	--         CAST((NVL(CAST((NVL(C_TBECKESAI.DSREN,C_TBECKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(TBECORDER.DSREN,TBECORDER.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , NVL(RIREKI.JOIN_REC_UPDDATE,0)
	--       , NVL(DUM.JOIN_REC_UPDDATE,0)
	--   ))                                                                                   AS JOIN_REC_UPDDATE  --結合レコード更新日時(JJ連携の差分抽出に使用)
	--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
FROM C_TBECKESAIHISTORY C_TBECKESAI ,--決済履歴情報
	C_TBECORDERHISTORY TBECORDER, --受注履歴情報
	KESAI_H_DATA_MART_SUB_N_RIREK RIREKI, --受注変更履歴
	--BGN-UPD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	(
		SELECT DISTINCT C_DIKESAIID_BEFORE,
			C_DIKESAIID_AFTER
		FROM KESAIID_DUMMY
		) DUM
--DnA側でデータマートを作成するため廃止
--, (SELECT C_DIKESAIID_BEFORE
--         ,C_DIKESAIID_AFTER
--         ,MAX(JOIN_REC_UPDDATE) AS JOIN_REC_UPDDATE
--    FROM KESAIID_DUMMY
--    GROUP BY C_DIKESAIID_BEFORE, C_DIKESAIID_AFTER)DUM
--END-UPD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
WHERE C_TBECKESAI.DIORDERID = TBECORDER.DIORDERID
	AND RIREKI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DICANCEL = '0' --決済情報.キャンセルフラグ = '0'(0:有効)
	AND C_TBECKESAI.C_DIEXCHANGEPOINT <> 0 --決済情報.受注使用ポイント（交換） = 0以外
	AND C_TBECKESAI.DIELIMFLG = '0' --決済情報.削除フラグ = '0'(0:有効)
	AND TBECORDER.DIELIMFLG = '0' --受注情報.削除フラグ = '0'(0:有効)
	AND DUM.C_DIKESAIID_BEFORE = C_TBECKESAI.C_DIKESAIID


),
union8 as(
    
--特典
SELECT CAST(('U' || DUM.C_DIKESAIID_AFTER) AS VARCHAR) AS SALENO,
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID || C_TBECPRIVILEGEKESAI.DIORDERID) AS NUMERIC) AS GYONO,
	'特典' AS MEISAIKBN,
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID) AS VARCHAR) AS ITEMCODE,
	'特典' AS ITEMNAME, --商品名
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID) AS VARCHAR) AS DIID, --商品内部ID
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID) AS VARCHAR) AS DISETID, --セット商品内部ID
	0 AS SURYO,
	0 AS TANKA, --割引後税込単価
	0 AS KINGAKU, --割引後明細税込金額
	0 AS MEISAINUKIKINGAKU, --割引後明細税抜金額
	0 AS WARIRITU, --割引率
	0 AS WARIMAEKOMITANKA, --割引前税込単価
	0 AS WARIMAENUKIKINGAKU, --割引前明細税抜金額
	0 AS WARIMAEKOMIKINGAKU, --割引前明細税込金額
	0 AS BUN_TANKA, --割引後税込単価
	0 AS BUN_KINGAKU, --割引後明細税込金額
	0 AS BUN_MEISAINUKIKINGAKU, --割引後明細税抜金額
	0 AS BUN_WARIRITU, --割引率
	0 AS BUN_WARIMAEKOMITANKA, --割引前税込単価
	0 AS BUN_WARIMAENUKIKINGAKU, --割引前明細税抜金額
	0 AS BUN_WARIMAEKOMIKINGAKU, --割引前明細税込金額
	DUM.C_DIKESAIID_AFTER AS DISPSALENO,
	DUM.C_DIKESAIID_AFTER AS KESAIID,
	TBECORDER.DIORDERID AS DIORDERID, --受注内部ID
	'0' AS C_DSPOINTITEMFLG, --ポイント交換商品フラグ
	'0' AS C_DIITEMTYPE, --商品区分
	0 AS C_DIADJUSTPRC, --調整金額
	0 AS DITOTALPRC, --税込み額
	0 AS DIITEMTAX, --消費税額
	0 AS C_DIITEMTOTALPRC, --販売小計(税込)
	0 AS C_DIDISCOUNTMEISAI, --割引金額
	CAST((C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID || C_TBECPRIVILEGEKESAI.DIORDERID) AS NUMERIC) AS DISETMEISAIID, --親行取得用
	'DUMMY' AS C_DSSETITEMKBN, --セット品区分
	4 AS MAKER --マーカー
	--BGN-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	--DnA側でデータマートを作成するため廃止
	--, CAST((GREATEST(
	--         CAST((NVL(CAST((NVL(C_TBECKESAI.DSREN,C_TBECKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(TBECORDER.DSREN,TBECORDER.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(C_TBECPRIVILEGEKESAI.DSREN,C_TBECPRIVILEGEKESAI.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , CAST((NVL(CAST((NVL(C_TBECPRIVILEGEMST.DSREN,C_TBECPRIVILEGEMST.DSPREP),'YYYYMMDDHH24MISS'),0))
	--       , NVL(RIREKI.JOIN_REC_UPDDATE,0)
	--       , NVL(DUM.JOIN_REC_UPDDATE,0)
	--   ))                                                                                   AS JOIN_REC_UPDDATE  --結合レコード更新日時(JJ連携の差分抽出に使用)
	--END-ADD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
FROM C_TBECKESAIHISTORY C_TBECKESAI, --決済履歴情報
	C_TBECORDERHISTORY TBECORDER, --受注履歴情報
	C_TBECPRIVILEGEKESAIHISTORY C_TBECPRIVILEGEKESAI, --特典履歴－決済関連
	C_TBECPRIVILEGEMST C_TBECPRIVILEGEMST, --特典付与マスタ
	KESAI_H_DATA_MART_SUB_N_RIREK RIREKI, --受注変更履歴
	--BGN-UPD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
	
	(
		SELECT DISTINCT C_DIKESAIID_BEFORE,
			C_DIKESAIID_AFTER
		FROM KESAIID_DUMMY
		) DUM
--DnA側でデータマートを作成するため廃止
--, (SELECT C_DIKESAIID_BEFORE
--         ,C_DIKESAIID_AFTER
--         ,MAX(JOIN_REC_UPDDATE) AS JOIN_REC_UPDDATE
--    FROM KESAIID_DUMMY
--    GROUP BY C_DIKESAIID_BEFORE, C_DIKESAIID_AFTER)DUM
--END-UPD 20200108 D.YAMASHITA ***変更19855(JJ連携処理の追加におけるDWHデータの差分抽出実現化)****
WHERE C_TBECKESAI.DIORDERID = TBECORDER.DIORDERID
	AND RIREKI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.DIORDERHISTID = TBECORDER.DIORDERHISTID --受注変更履歴.履歴ID = 受注情報履歴.履歴ID
	AND C_TBECKESAI.C_DIKESAIID = C_TBECPRIVILEGEKESAI.C_DIKESAIID
	AND TBECORDER.DIORDERHISTID = C_TBECPRIVILEGEKESAI.DIORDERHISTID
	AND C_TBECPRIVILEGEKESAI.C_DIPRIVILEGEID = C_TBECPRIVILEGEMST.C_DIPRIVILEGEID
	AND C_TBECKESAI.DICANCEL = '0' --決済情報.キャンセルフラグ = '0'(0:有効)
	AND C_TBECPRIVILEGEKESAI.C_DINONDISPFLG = '0' --特典-決済関連.非表示フラグ
	AND C_TBECKESAI.DIELIMFLG = '0' --決済情報.削除フラグ = '0'(0:有効)
	AND TBECORDER.DIELIMFLG = '0' --受注情報.削除フラグ = '0'(0:有効)
	AND C_TBECPRIVILEGEKESAI.DIELIMFLG = '0' --特典-決済関連.削除フラグ = '0'(0:有効)
	AND C_TBECPRIVILEGEMST.DIELIMFLG = '0' --特典付与マスタ.削除フラグ = '0'(0:有効)
	AND C_DSTEKIYOJYOGAIFLG = '0' --特典－受注関連.適用除外フラグ = '0'(0:除外しない)
	AND DUM.C_DIKESAIID_BEFORE = C_TBECKESAI.C_DIKESAIID

),
transformed as(
    select * from union1
    union all
    select * from union2
    union all
    select * from union3
    union all
    select * from union4
    union all
    select * from union5
    union all
    select * from union6
    union all
    select * from union7
    union all
    select * from union8
    
),
final as(
    select 
        saleno::varchar(64) as saleno,
        gyono::number(18,0) as gyono,
        meisaikbn::varchar(36) as meisaikbn,
        itemcode::varchar(60) as itemcode,
        itemname::varchar(190) as itemname,
        diid::varchar(60) as diid,
        disetid::varchar(60) as disetid,
        suryo::number(18,0) as suryo,
        tanka::number(18,0) as tanka,
        kingaku::number(18,0) as kingaku,
        meisainukikingaku::number(18,0) as meisainukikingaku,
        wariritu::number(18,0) as wariritu,
        warimaekomitanka::number(18,0) as warimaekomitanka,
        warimaenukikingaku::number(18,0) as warimaenukikingaku,
        warimaekomikingaku::number(18,0) as warimaekomikingaku,
        bun_tanka::number(18,0) as bun_tanka,
        bun_kingaku::number(18,0) as bun_kingaku,
        bun_meisainukikingaku::number(18,0) as bun_meisainukikingaku,
        bun_wariritu::number(18,0) as bun_wariritu,
        bun_warimaekomitanka::number(18,0) as bun_warimaekomitanka,
        bun_warimaenukikingaku::number(18,0) as bun_warimaenukikingaku,
        bun_warimaekomikingaku::number(18,0) as bun_warimaekomikingaku,
        dispsaleno::varchar(64) as dispsaleno,
        kesaiid::varchar(64) as kesaiid,
        diorderid::number(10,0) as diorderid,
        c_dspointitemflg::varchar(3) as c_dspointitemflg,
        c_diitemtype::varchar(5) as c_diitemtype,
        c_diadjustprc::number(18,0) as c_diadjustprc,
        ditotalprc::number(18,0) as ditotalprc,
        diitemtax::number(18,0) as diitemtax,
        c_diitemtotalprc::number(18,0) as c_diitemtotalprc,
        c_didiscountmeisai::number(18,0) as c_didiscountmeisai,
        disetmeisaiid::number(18,0) as disetmeisaiid,
        c_dssetitemkbn::varchar(8) as c_dssetitemkbn,
        maker::number(18,0) as maker,
        current_timestamp()::timestamp_ntz(9) as inserted_date,
        null::varchar(100) as inserted_by ,
        current_timestamp()::timestamp_ntz(9) as updated_date,
        null::varchar(100) as updated_by
    from transformed
)
select * from final