with country_lkp as (
    select * from {{ source('mds_access','mds_lkp_country_hierarchy') }}
),

final as(
    select
    name::VARCHAR(500) as country,
    name::VARCHAR(500) as p1,
    lower(name)::VARCHAR(500) as p2,
    upper(name)::VARCHAR(1500) as p3,
    iso2_ctry_cd::VARCHAR(2) as p4,
    ('-' || name || '-')::VARCHAR(502) as p5,
    ('-' || currency || '-')::VARCHAR(7) as p6,
    (' ' || name)::VARCHAR(501) as p8,
    ('-' || iso2_ctry_cd || '-')::VARCHAR(4) as p9,
    ('_' || iso2_ctry_cd || '_')::VARCHAR(4) as p11,
    (iso2_ctry_cd || ' |')::VARCHAR(4) as p12,
    (iso3_ctry_cd)::VARCHAR(3) as p13,
    ('_' || name)::VARCHAR(501) as p14,
    ('- ' || iso2_ctry_cd)::VARCHAR(4) as p15,
    ('-' || iso2_ctry_cd)::VARCHAR(3) as p16,
    ('_' || iso2_ctry_cd)::VARCHAR(3) as p19,
    ('_ ' || iso2_ctry_cd)::VARCHAR(4) as p20,
    (iso2_ctry_cd || '_')::VARCHAR(3) as p21,
    ('|' || iso2_ctry_cd || '|')::VARCHAR(4) as p22,
    ('|' || iso2_ctry_cd || '-')::VARCHAR(4) as p23,
    (' ' || iso3_ctry_cd || ' ')::VARCHAR(5) as p24,
    (iso2_ctry_cd || '_')::VARCHAR(3) as p25,
    ('_ ' || iso2_ctry_cd)::VARCHAR(4) as p26,
    (' ' || iso2_ctry_cd || ' ')::VARCHAR(4) as p27,
    ('  ' || iso2_ctry_cd || '_')::VARCHAR(5) as p28,
    ('- ' || iso2_ctry_cd || ' ')::VARCHAR(5) as p29,
    (' ' || iso2_ctry_cd || '-')::VARCHAR(4) as p30,
    (iso2_ctry_cd || '-')::VARCHAR(3) as p31,
    (' ' || iso2_ctry_cd)::VARCHAR(3) as p33,
    (iso2_ctry_cd || ' |')::VARCHAR(4) as p34,
    ('~' || iso2_ctry_cd || '-')::VARCHAR(4) as p35,
    ('- ' || iso2_ctry_cd || ' -')::VARCHAR(6) as p36,
    (iso2_ctry_cd || '-')::VARCHAR(3) as p41,
    ('|' || name || '|')::VARCHAR(502) as p42,
    (iso2_ctry_cd || '|')::VARCHAR(3) as p43,
    (iso3_ctry_cd || '|')::VARCHAR(4) as p44,
    (iso2_ctry_cd || '|')::VARCHAR(3) as p45,
    (' ' || iso2_ctry_cd)::VARCHAR(3) as p46,
    lower(iso2_ctry_cd)::VARCHAR(2) as p49,
    (iso2_ctry_cd || ' ')::VARCHAR(3) as p50,
    (' ' || name || ' ')::VARCHAR(502) as p52,
    ('_' || iso2_ctry_cd || '|')::VARCHAR(4) as p53,
    (' ' || iso2_ctry_cd || '_')::VARCHAR(4) as p54,
    ('| ' || iso3_ctry_cd)::VARCHAR(5) as p55,
    (' ' || iso3_ctry_cd || ' |')::VARCHAR(6) as p56,
    ('_' || lower(iso2_ctry_cd) || '_')::VARCHAR(4) as p57,
    (' ' || iso2_ctry_cd || '|')::VARCHAR(4) as p58,
    (iso3_ctry_cd || '_')::VARCHAR(4) as p59,
    lower(name || ' ')::VARCHAR(501) as p64,
    ('_' || name || '_')::VARCHAR(502) as p65,
    lower('_' || name || '_')::VARCHAR(502) as p73,
    (' ' || iso2_ctry_cd || ' |')::VARCHAR(5) as p74,
    ('~' || iso2_ctry_cd || '-')::VARCHAR(4) as p75,
    ('-' || iso2_ctry_cd || '|')::VARCHAR(4) as p76,
    ('- ' || iso2_ctry_cd)::VARCHAR(4) as p77,
    (name || ' ')::VARCHAR(501) as p80,
    upper(name || ' ')::VARCHAR(1503) as p81,
    (currency)::VARCHAR(5) as p84,
    (')' || iso2_ctry_cd || '|')::VARCHAR(4) as p85,
    (iso2_ctry_cd || '_JnJ')::VARCHAR(6) as p86,
    gcgh_country::VARCHAR(250) as gcgh_country,
    gcgh_region::VARCHAR(50) as gcgh_region
    from country_lkp 
    where iso2_ctry_cd != ''
)

select * from final