with source as (
    select * from {{ ref('aspedw_integration__v_rpt_copa_ciw') }}
),
final as (
    select
        fisc_yr as "fisc_yr",
        fisc_yr_per as "fisc_yr_per",
        fisc_day as "fisc_day",
        ctry_nm as "ctry_nm",
        "cluster" as "cluster",
        obj_crncy_co_obj as "obj_crncy_co_obj",
        from_crncy as "from_crncy",
        acct_nm as "acct_nm",
        acct_num as "acct_num",
        ciw_desc as "ciw_desc",
        ciw_bucket as "ciw_bucket",
        csw_desc as "csw_desc",
        "b1 mega-brand",
        "b2 brand",
        "b3 base product",
        "b4 variant",
        "b5 put-up",
        cust_num as "cust_num",
        "parent customer",
        banner as "banner",
        "banner format",
        channel as "channel",
        "go to model",
        "sub channel",
        retail_env as "retail_env",
        gcph_franchise as "gcph_franchise",
        gcph_brand as "gcph_brand",
        gcph_subbrand as "gcph_subbrand",
        gcph_variant as "gcph_variant",
        put_up_description as "put_up_description",
        gcph_needstate as "gcph_needstate",
        gcph_category as "gcph_category",
        gcph_subcategory as "gcph_subcategory",
        gcph_segment as "gcph_segment",
        gcph_subsegment as "gcph_subsegment",
        gcch_total_enterprise as "gcch_total_enterprise",
        gcch_retail_banner as "gcch_retail_banner",
        gcch_primary_format as "gcch_primary_format",
        gcch_distributor_attribute as "gcch_distributor_attribute",
        acct_hier_shrt_desc as "acct_hier_shrt_desc",
        qty as "qty",
        amt_lcy as "amt_lcy",
        amt_usd as "amt_usd"
    from source
)
select * from final