with source as (
    select * from {{ ref('aspedw_integration__edw_rpt_ecomm_oneview') }}
),
final as
(

    Select data_type	as	"data_type",
dataset	as	"dataset",
data_level	as	"data_level",
kpi	as	"kpi",
period_type	as	"period_type",
fisc_year	as	"fisc_year",
cal_year	as	"cal_year",
fisc_month	as	"fisc_month",
cal_month	as	"cal_month",
fisc_day	as	"fisc_day",
cal_day	as	"cal_day",
fisc_yr_per	as	"fisc_yr_per",
cluster	as	"cluster",
market	as	"market",
sub_market	as	"sub_market",
channel	as	"channel",
sub_channel	as	"sub_channel",
retail_environment	as	"retail_environment",
go_to_model	as	"go_to_model",
profit_center	as	"profit_center",
company_code	as	"company_code",
sap_customer_code	as	"sap_customer_code",
sap_customer_name	as	"sap_customer_name",
banner	as	"banner",
banner_format	as	"banner_format",
platform_name	as	"platform_name",
retailer_name	as	"retailer_name",
retailer_name_english	as	"retailer_name_english",
manufacturer_name	as	"manufacturer_name",
jj_manufacturer_flag	as	"jj_manufacturer_flag",
prod_hier_l1	as	"prod_hier_l1",
prod_hier_l2	as	"prod_hier_l2",
prod_hier_l3	as	"prod_hier_l3",
prod_hier_l4	as	"prod_hier_l4",
prod_hier_l5	as	"prod_hier_l5",
prod_hier_l6	as	"prod_hier_l6",
prod_hier_l7	as	"prod_hier_l7",
prod_hier_l8	as	"prod_hier_l8",
prod_hier_l9	as	"prod_hier_l9",
product_minor_code	as	"product_minor_code",
product_minor_name	as	"product_minor_name",
material_number	as	"material_number",
ean	as	"ean",
retailer_sku_code	as	"retailer_sku_code",
product_key	as	"product_key",
product_key_description	as	"product_key_description",
target_value	as	"target_value",
actual_value	as	"actual_value",
value_usd	as	"value_usd",
value_lcy	as	"value_lcy",
salesweight	as	"salesweight",
from_crncy	as	"from_crncy",
to_crncy	as	"to_crncy",
account_number	as	"account_number",
account_name	as	"account_name",
account_description_l1	as	"account_description_l1",
account_description_l2	as	"account_description_l2",
account_description_l3	as	"account_description_l3",
additional_information	as	"additional_information",
ppm_role	as	"ppm_role",
totalnts_lcy_value	as	"totalnts_lcy_value",
totalnts_usd_value	as	"totalnts_usd_value"
from source
)

select * from final