with source as (
    select * from {{ ref('aspedw_integration__v_rpt_copa_sku') }}
),
final as (
    select
        fisc_yr as "fisc_yr",
        fisc_yr_per as "fisc_yr_per",
        fisc_day as "fisc_day",
        ctry_nm as "ctry_nm",
        "cluster",
        obj_crncy_co_obj as "obj_crncy_co_obj",
        "b1 mega-brand",
        "b2 brand",
        "b3 base product",
        "b4 variant",
        "b5 put-up",
        "prod h1 operating group",
        "prod h2 franchise group",
        "prod h3 franchise",
        "prod h4 product franchise",
        "prod h5 product major",
        "prod h6 product minor",
        pka_franchise_desc as "pka_franchise_desc",
        pka_brand_desc as "pka_brand_desc",
        pka_sub_brand_desc as "pka_sub_brand_desc",
        pka_variant_desc as "pka_variant_desc",
        pka_sub_variant_desc as "pka_sub_variant_desc",
        pka_flavor_desc as "pka_flavor_desc",
        pka_ingredient_desc as "pka_ingredient_desc",
        pka_application_desc as "pka_application_desc",
        pka_length_desc as "pka_length_desc",
        pka_shape_desc as "pka_shape_desc",
        pka_spf_desc as "pka_spf_desc",
        pka_cover_desc as "pka_cover_desc",
        pka_form_desc as "pka_form_desc",
        pka_size_desc as "pka_size_desc",
        pka_character_desc as "pka_character_desc",
        pka_package_desc as "pka_package_desc",
        pka_attribute_13_desc as "pka_attribute_13_desc",
        pka_attribute_14_desc as "pka_attribute_14_desc",
        pka_sku_identification_desc as "pka_sku_identification_desc",
        pka_one_time_relabeling_desc as "pka_one_time_relabeling_desc",
        pka_product_key as "pka_product_key",
        pka_product_key_description as "pka_product_key_description",
        pka_product_key_description_2 as "pka_product_key_description_2",
        pka_root_code as "pka_root_code",
        pka_root_code_desc_1 as "pka_root_code_desc_1",
        pka_root_code_desc_2 as "pka_root_code_desc_2",
        greenlight_sku_flag as "greenlight_sku_flag",
        "parent customer",
        banner as "banner",
        "banner format",
        channel as "channel",
        "go to model",
        "sub channel",
        retail_env as "retail_env",
        nts_usd as "nts_usd",
        nts_lcy as "nts_lcy",
        gts_usd as "gts_usd",
        gts_lcy as "gts_lcy",
        eq_usd as "eq_usd",
        eq_lcy as "eq_lcy",
        from_crncy as "from_crncy",
        to_crncy as "to_crncy",
        nts_qty as "nts_qty",
        gts_qty as "gts_qty",
        eq_qty as "eq_qty",
        "product code",
        "product name"
    from source
)
select * from final