with source as (
    select * from {{ ref('aspedw_integration__edw_material_sales_dim') }}
),
final as (
    select
    sls_org as "sls_org",
dstr_chnl as "dstr_chnl",
matl_num as "matl_num",
base_unit as "base_unit",
matl_grp_1 as "matl_grp_1",
prod_hierarchy as "prod_hierarchy",
commsn_grp as "commsn_grp",
vol_rebt_grp as "vol_rebt_grp",
pharma_cent_no as "pharma_cent_no",
del_fl as "del_fl",
matl_grp_2 as "matl_grp_2",
matl_grp_3 as "matl_grp_3",
matl_grp_4 as "matl_grp_4",
matl_grp_5 as "matl_grp_5",
matl_stats_grp as "matl_stats_grp",
asrtmnt_grade as "asrtmnt_grade",
afs_vas_matl_grp as "afs_vas_matl_grp",
afs_prc_in as "afs_prc_in",
predecessor as "predecessor",
sku_id as "sku_id",
prodt_alloc_det_proc as "prodt_alloc_det_proc",
num_pcs_in as "num_pcs_in",
ean_num as "ean_num",
old_matl_num as "old_matl_num",
delv_plnt as "delv_plnt",
cash_disc_ind as "cash_disc_ind",
prc_grp_matl as "prc_grp_matl",
acct_asgn_grp as "acct_asgn_grp",
itm_cat_grp as "itm_cat_grp",
min_ordr_qty as "min_ordr_qty",
min_delv_qty as "min_delv_qty",
delv_unit as "delv_unit",
delv_uom as "delv_uom",
sls_unit as "sls_unit",
launch_dt as "launch_dt",
npi_in as "npi_in",
lcl_matl_grp_1 as "lcl_matl_grp_1",
lcl_matl_grp_2 as "lcl_matl_grp_2",
lcl_matl_grp_3 as "lcl_matl_grp_3",
lcl_matl_grp_4 as "lcl_matl_grp_4",
lcl_matl_grp_5 as "lcl_matl_grp_5",
lcl_matl_grp_6 as "lcl_matl_grp_6",
npi_in_apo as "npi_in_apo",
copy_hist as "copy_hist",
prod_classftn as "prod_classftn",
fcst_indc_apo as "fcst_indc_apo",
prod_type_apo as "prod_type_apo",
mstr_cd as "mstr_cd",
med_desc as "med_desc",
crt_dttm as "crt_dttm",
updt_dttm as "updt_dttm"
from source
)
select * from final 