with edw_gch_customerhierarchy as(
    select * from {{ ref('aspedw_integration__edw_gch_customerhierarchy') }}
),
final as (
    Select tamr_id as "tamr_id",
    origin_source_name as "origin_source_name",
    origin_entity_id as "origin_entity_id",
    manualclassificationid as "manualclassificationid",
    manualclassificationpath as "manualclassificationpath",
    suggestedclassificationid as "suggestedclassificationid",
    suggestedclassificationpath as "suggestedclassificationpath",
    suggestedclassificationscore as "suggestedclassificationscore",
    finalclassificationpath as "finalclassificationpath",
    unique_id as "unique_id",
    region as "region",
    customer as "customer",
    country as "country",
    name as "name",
    city as "city",
    postal_code as "postal_code",
    state as "state",
    district as "district",
    search_term as "search_term",
    regional_customer as "regional_customer",
    regional_customer_code as "regional_customer_code",
    regional_banner as "regional_banner",
    regional_banner_code as "regional_banner_code",
    regional_channel as "regional_channel",
    regional_segmentation as "regional_segmentation",
    regional_class_of_trade as "regional_class_of_trade",
    emea_top_20_key_account as "emea_top_20_key_account",
    apac_global_customer as "apac_global_customer",
    apac_go_to_model as "apac_go_to_model",
    apac_sub_channel as "apac_sub_channel",
    apac_banner_in_format as "apac_banner_in_format",
    latam_regional_customer_group as "latam_regional_customer_group",
    gcgh_region as "gcgh_region",
    gcgh_cluster as "gcgh_cluster",
    gcgh_subcluster as "gcgh_subcluster",
    gcgh_market as "gcgh_market",
    gcch_total_enterprise as "gcch_total_enterprise",
    gcch_retail_banner as "gcch_retail_banner",
    dateofextract as "dateofextract",
    cdl_datetime as "cdl_datetime",
    cdl_source_file as "cdl_source_file",
    load_key as "load_key",
    crt_dttm as "crt_dttm",
    updt_dttm as "updt_dttm",
    primary_format as "primary_format",
    distributor_attribute as "distributor_attribute"
    From edw_gch_customerhierarchy
)

select * from final