{% macro build_wks_th_gt_sales_order_pre_load(filename) %}
    {% set tablename %}
    {% if target.name=='prod' %}
                    thawk_integration.wks_th_gt_sales_order_pre_load
                {% else %}
                    {{schema}}.thawks_integration__wks_th_gt_sales_order_pre_load
                {% endif %}	
    {% endset %}
    {% set query %}
    CREATE TABLE if not exists {{tablename}}		
    (
        hashkey varchar(500),
        cntry_cd varchar(5),
        crncy_cd varchar(5),
        saleunit varchar(10),
        orderid varchar(50),
        orderdate date,
        customer_id varchar(50),
        customer_name varchar(150),
        city varchar(50),
        region varchar(50),
        saledistrict varchar(50),
        saleoffice varchar(50),
        salegroup varchar(50),
        customertype varchar(50),
        storetype varchar(50),
        saletype varchar(50),
        salesemployee varchar(50),
        salename varchar(150),
        productid varchar(50),
        productname varchar(150),
        megabrand varchar(50),
        brand varchar(50),
        baseproduct varchar(50),
        variant varchar(50),
        putup varchar(50),
        priceref numeric(18,6),
        backlog numeric(18,6),
        qty numeric(18,6),
        subamt1 numeric(18,6),
        discount numeric(18,6),
        subamt2 numeric(18,6),
        discountbtline numeric(18,6),
        totalbeforevat numeric(18,6),
        total numeric(18,6),
        sales_order_line_no varchar(10),
        cancelled varchar(10),
        documentid varchar(50),
        return_reason varchar(150),
        promotioncode varchar(50),
        promotioncode1 varchar(50),
        promotioncode2 varchar(50),
        promotioncode3 varchar(50),
        promotioncode4 varchar(50),
        promotioncode5 varchar(50),
        promotion_code varchar(50),
        promotion_code2 varchar(50),
        promotion_code3 varchar(50),
        avgdiscount numeric(18,6),
        ordertype varchar(10),
        approverstatus varchar(10),
        pricelevel varchar(10),
        optional date,
        deliverydate date,
        ordertime varchar(50),
        shipto varchar(50),
        billto varchar(50),
        deliveryrouteid varchar(50),
        approved_date date,
        approved_time varchar(50),
        ref_15 varchar(255),
        paymenttype varchar(50),
        filename varchar(100),
        run_id varchar(50),
        crt_dttm timestamp without time zone  	
    );
    TRUNCATE TABLE {{tablename}};
    
    INSERT INTO {{tablename}}(
    hashkey,
    cntry_cd,
    crncy_cd,
    saleunit,
    orderid,
    orderdate,
    customer_id,
    customer_name,
    city,
    region,
    saledistrict,
    saleoffice,
    salegroup,
    customertype,
    storetype,
    saletype,
    salesemployee,
    salename,
    productid,
    productname,
    megabrand,
    brand,
    baseproduct,
    variant,
    putup,
    priceref,
    backlog,
    qty,
    subamt1,
    discount,
    subamt2,
    discountbtline,
    totalbeforevat,
    total,
    sales_order_line_no,
    cancelled,
    documentid,
    return_reason,
    promotioncode,
    promotioncode1,
    promotioncode2,
    promotioncode3,
    promotioncode4,
    promotioncode5,
    promotion_code,
    promotion_code2,
    promotion_code3,
    avgdiscount,
    ordertype,
    approverstatus,
    pricelevel,
    optional,
    deliverydate,
    ordertime,
    shipto,
    billto,
    deliveryrouteid,
    approved_date,
    approved_time,
    ref_15,
    paymenttype,
    filename,
    run_id,
    crt_dttm
    )

    SELECT 
        MD5(COALESCE(UPPER(saleunit),'N/A') ||coalesce (UPPER(orderid),'N/A') ||coalesce (orderdate,'9999-12-31') ||coalesce (UPPER(productid),'N/A') ||coalesce (UPPER(customer_id),'N/A') ||coalesce (sales_order_line_no,'N/A')) AS hashkey,
        cntry_cd,
        crncy_cd,
        saleunit,
        orderid,
        orderdate,
        customer_id,
        customer_name,
        city,
        region,
        saledistrict,
        saleoffice,
        salegroup,
        customertype,
        storetype,
        saletype,
        salesemployee,
        salename,
        productid,
        productname,
        megabrand,
        brand,
        baseproduct,
        variant,
        putup,
        priceref,
        backlog,
        qty,
        subamt1,
        discount,
        subamt2,
        discountbtline,
        totalbeforevat,
        total,
        sales_order_line_no,
        cancelled,
        documentid,
        return_reason,
        promotioncode,
        promotioncode1,
        promotioncode2,
        promotioncode3,
        promotioncode4,
        promotioncode5,
        promotion_code,
        promotion_code2,
        promotion_code3,
        avgdiscount,
        ordertype,
        approverstatus,
        pricelevel,
        optional,
        deliverydate,
        ordertime,
        shipto,
        billto,
        deliveryrouteid,
        approved_date,
        approved_time,
        ref_15,
        paymenttype,
        filename,
        run_id,
        crt_dttm
    FROM 
    {% if target.name=='prod' %}
            thaitg_integration.itg_th_gt_sales_order
        {% else %}
            {{schema}}.thaitg_integration__itg_th_gt_sales_order
        {% endif %}
    WHERE orderdate >= (SELECT MIN(orderdate) FROM {{ source('thasdl_raw', 'sdl_th_gt_sales_order') }} where filename = '{{filename}}'
    )
    AND   UPPER(saleunit) IN (SELECT DISTINCT UPPER(saleunit)
                            FROM {{ source('thasdl_raw', 'sdl_th_gt_sales_order') }} where filename = '{{filename}}'
                            );
    {% endset %}

    {% do run_query(query) %}
{% endmacro %}