with itg_vn_dms_forecast as (
select * from {{ ref('vnmitg_integration__itg_vn_dms_forecast') }}
),
edw_vw_os_time_dim as (
select * from {{ ref('sgpedw_integration__edw_vw_os_time_dim') }}
),
wks_vn_si_st_so_details as (
select * from {{ ref('vnmwks_integration__wks_vn_si_st_so_details') }}
),
itg_vn_dms_history_saleout as (
select * from {{ ref('vnmitg_integration_itg_vn_dms_history_saleout') }}
),
itg_vn_dms_distributor_dim_rnk as (
select *,row_number() over (partition by dstrbtr_id order by crtd_dttm desc) as rnk 
 from {{ ref('vnmitg_integration_itg_vn_dms_history_saleout') }} 
),
itg_vn_dms_distributor_dim as (
select * from itg_vn_dms_distributor_dim_rnk where rnk=1
),
itg_vn_distributor_sap_sold_to_mapping as (
select * from {{ ref('vnmitg_integration_itg_vn_distributor_sap_sold_to_mapping') }}
),
transformed as (select timedim."year" as jj_year,
       timedim.qrtr as jj_qrtr,
       timedim.mnth_id as jj_mnth_id,
       timedim.mnth_no as jj_mnth_no,
       null as jj_mnth_wk_no,
	   null as wks_in_qrtr,
       territory_dist,
       warehouse as distributor_id_report,
       null as dstrbtr_grp_cd,
       null as dstrbtr_type,
       null as sap_sold_to_code,
       null as sap_matl_num,
       null as sap_matl_name,
       null as dstrbtr_matl_num,
       null as dstrbtr_matl_name,
       case when channel = 'GT' THEN 'GENERAL TRADE' END as trade_type,
       null as bill_doc,
       null as bill_date,
       null as cust_cd,
       null as slsmn_cd,
       null as slsmn_nm,
       null as slsmn_status,
       null as so_sls_qty,
       null as so_ret_qty,
       null as so_grs_trd_sls,
       null as so_net_trd_sls,
       null as so_avg_wk_tgt,
       null as so_mnth_tgt,
       null as supervisor_code,
       null as supervisor_name,
       null as asm_id,
       null as asm_name,
       null as dstrb_region,
	   null as outlet_name,
       null as shop_type,
       null as Group_hierarchy, 
       null as Top_Door_Group,
	   null as  Top_Door_Target,
	   'N' as  Top_Door_Flag,
       null as si_sls_qty,
       null as si_ret_qty,
       null as si_gts_val,
       null as si_nts_val,
       null as  si_avg_wk_tgt,
       null as si_target,
       null as st_sls_qty,
       null as st_ret_qty,
       null as st_grs_trd_sls,
       null as st_net_trd_sls,
       null as st_avg_wk_tgt,
       null as st_target,
       null as visit_call_date,
       null as product_visit_call_date,
       null as PC_Target,
       null as PC_Target_by_week,
       null as CE_Target,
       null as CE_Target_by_week,
	     null as ub_weekly_target,
       forecast.franchise,
       forecast.brand,
       forecast.variant,
       null as product_group,
       null as group_jb,
	   null as groupmsl,
       cast (forecast.forecastso_mil as numeric(15,4))*1000000 as forecastso_mil
from itg_vn_dms_forecast forecast,
     (select edw_vw_os_time_dim."year",
             edw_vw_os_time_dim.qrtr,
             edw_vw_os_time_dim.mnth_id,
             edw_vw_os_time_dim.mnth_no,
             MIN(edw_vw_os_time_dim.cal_date) as cal_date
      from edw_vw_os_time_dim
      group by edw_vw_os_time_dim."year",
               edw_vw_os_time_dim.qrtr,
               edw_vw_os_time_dim.mnth_id,
               edw_vw_os_time_dim.mnth_no) timedim
where forecast.cycle = cast(timedim.mnth_id as numeric)
AND channel = 'GT'
UNION ALL
select wks_si_so_st.*, null as forecastso_mil
from
wks_vn_si_st_so_details wks_si_so_st
UNION ALL  -- History data
select timedim."year" as jj_year,
       timedim.qrtr as jj_qrtr,
       timedim.mnth_id as jj_mnth_id,
       timedim.mnth_no as jj_mnth_no,
       null as jj_mnth_wk_no,
	   null as wks_in_qrtr,
       hist_data.territory_dist,
       hist_data.mapped_spk  as distributor_id_report,
       null as dstrbtr_grp_cd,
       null as dstrbtr_type,
       hist_data.sap_sold_to_code,
       hist_data.productcodesap as sap_matl_num,
       hist_data.sku_name as sap_matl_name,
       hist_data.dmsproductid  as dstrbtr_matl_num,
       hist_data.sku_name as dstrbtr_matl_num,
       'GENERAL TRADE' as trade_type,
        null as bill_doc,
        timedim.cal_date as bill_date,
        null as cust_cd,
        null as slsmn_cd,
        null as slsmn_nm,
        null as slsmn_status,
        null as so_sls_qty,
        null as so_ret_qty,
        hist_data.sellout_afvat_afdisc as so_grs_trd_sls,
       -- (hist_data.sellout_afvat_afdisc - hist_data.sellout_afvat_afdisc*(nvl(hist_data.tax,0)/100)) as so_net_trd_sls,
       --(hist_data.sellout_afvat_afdisc/((100 + nvl(hist_data.tax,0)) / 100 )) as so_net_trd_sls,
	   /*Map so_net_trd_sls as sellout_afvat_afdisc*/
	   hist_data.sellout_afvat_afdisc as so_net_trd_sls,
        null as so_avg_wk_tgt,
        null as so_mnth_tgt,
        null as supervisor_code,
        null as supervisor_name,
        hist_data.asm_id,
        hist_data.asm_name,
        hist_data.region as dstrb_region,
	    null as  outlet_name,
		null as  shop_type,
        null as  Group_hierarchy, 
        null as  Top_Door_Group,
	    null as  Top_Door_Target,
		'N' as  Top_Door_Flag,
        null as si_sls_qty,
       null as si_ret_qty,
       null as si_gts_val,
       null as si_nts_val,
       null as  si_avg_wk_tgt,
       null as si_target,
       null as st_sls_qty,
       null as st_ret_qty,
       null as st_grs_trd_sls,
       null as st_net_trd_sls,
       null as st_avg_wk_tgt,
       null as st_target,
       null as visit_call_date,
       null as product_visit_call_date,
       null as PC_Target,
       null as PC_Target_by_week,
       null as CE_Target,
       null as CE_Target_by_week,
       null as ub_weekly_target,
       hist_data.franchise,
       hist_data.brand,
       hist_data.variant,
       hist_data.dmsproduct_group,
       hist_data.group_jb,
	   null as groupmsl,
       null as forecastso_mil
from
(select dist_dim.territory_dist,
       dist_dim.mapped_spk,
       dist_dim.sap_sold_to_code,
       dist_dim.sap_ship_to_code,
        null as region,
       hist_so.franchise,
       hist_so.brand,
       hist_so.variant,
       hist_so.dmsproduct_group,
       hist_so.dmsproductid,
       hist_so.productcodesap,
       hist_so.sku_name,
       hist_so.province,
       hist_so.group_jb,
       hist_so.user_id as asm_id,
       hist_so.rsm_name as asm_name,
       CYCLE,
       sellout_afvat_bfdisc,
       sellout_afvat_afdisc,
       tax
from itg_vn_dms_history_saleout hist_so
  LEFT JOIN (select DISTINCT territory_dist,
                    mapped_spk,
                    province,
                    mapp.sap_sold_to_code,
                    mapp.sap_ship_to_code
             from itg_vn_dms_distributor_dim dd,
                  itg_vn_distributor_sap_sold_to_mapping mapp
             where mapp.distributor_id = dd.mapped_spk) dist_dim ON dist_dim.province = hist_so.province) hist_data
left join
(select edw_vw_os_time_dim."year",
             edw_vw_os_time_dim.qrtr,
             edw_vw_os_time_dim.mnth_id,
             edw_vw_os_time_dim.mnth_no,
             MIN(edw_vw_os_time_dim.cal_date) as cal_date
      from edw_vw_os_time_dim
      group by edw_vw_os_time_dim."year",
               edw_vw_os_time_dim.qrtr,
               edw_vw_os_time_dim.mnth_id,
               edw_vw_os_time_dim.mnth_no)timedim 
on timedim.mnth_id = hist_data.cycle
),
final as (
    select 
    jj_year::number(18,0) as jj_year,
    jj_qrtr::varchar(14) as jj_qrtr,
    jj_mnth_id::varchar(23) as jj_mnth_id,
    jj_mnth_no::number(18,0) as jj_mnth_no,
    jj_mnth_wk_no::number(38,0) as jj_mnth_wk_no,
    wks_in_qrtr::number(38,0) as wks_in_qrtr,
    territory_dist::varchar(100) as territory_dist,
    distributor_id_report::varchar(100) as distributor_id_report,
    dstrbtr_grp_cd::varchar(100) as dstrbtr_grp_cd,
    dstrbtr_type::varchar(100) as dstrbtr_type,
    sap_sold_to_code::varchar(50) as sap_sold_to_code,
    sap_matl_num::varchar(50) as sap_matl_num,
    sap_matl_name::varchar(100) as sap_matl_name,
    dstrbtr_matl_num::varchar(100) as dstrbtr_matl_num,
    dstrbtr_matl_name::varchar(100) as dstrbtr_matl_name,
    trade_type::varchar(13) as trade_type,
    bill_doc::varchar(30) as bill_doc,
    bill_date::date as bill_date,
    cust_cd::varchar(100) as cust_cd,
    slsmn_cd::varchar(50) as slsmn_cd,
    slsmn_nm::varchar(100) as slsmn_nm,
    slsmn_status::varchar(1) as slsmn_status,
    so_sls_qty::number(22,4) as so_sls_qty,
    so_ret_qty::number(22,4) as so_ret_qty,
    so_grs_trd_sls::number(22,4) as so_grs_trd_sls,
    so_net_trd_sls::number(22,4) as so_net_trd_sls,
    so_avg_wk_tgt::number(28,6) as so_avg_wk_tgt,
    so_mnth_tgt::number(24,6) as so_mnth_tgt,
    supervisor_code::varchar(50) as supervisor_code,
    supervisor_name::varchar(100) as supervisor_name,
    asm_id::varchar(100) as asm_id,
    asm_name::varchar(200) as asm_name,
    dstrb_region::varchar(20) as dstrb_region,
    outlet_name::varchar(100) as outlet_name,
    shop_type::varchar(100) as shop_type,
    group_hierarchy::varchar(100) as group_hierarchy,
    top_door_group::varchar(100) as top_door_group,
    top_door_target::number(20,2) as top_door_target,
    top_door_flag::varchar(1) as top_door_flag,
    si_sls_qty::number(38,4) as si_sls_qty,
    si_ret_qty::number(38,4) as si_ret_qty,
    si_gts_val::number(38,4) as si_gts_val,
    si_nts_val::number(38,4) as si_nts_val,
    si_avg_wk_tgt::number(25,4) as si_avg_wk_tgt,
    si_target::number(22,4) as si_target,
    st_sls_qty::number(20,2) as st_sls_qty,
    st_ret_qty::number(20,2) as st_ret_qty,
    st_grs_trd_sls::number(22,4) as st_grs_trd_sls,
    st_net_trd_sls::number(22,4) as st_net_trd_sls,
    st_avg_wk_tgt::number(25,4) as st_avg_wk_tgt,
    st_target::number(22,4) as st_target,
    visit_call_date::date as visit_call_date,
    product_visit_call_date::date as product_visit_call_date,
    pc_target::number(22,4) as pc_target,
    pc_target_by_week::number(22,4) as pc_target_by_week,
    ce_target::number(22,4) as ce_target,
    ce_target_by_week::number(22,4) as ce_target_by_week,
    ub_weekly_target::number(38,24) as ub_weekly_target,
    franchise::varchar(100) as franchise,
    brand::varchar(100) as brand,
    variant::varchar(100) as variant,
    product_group::varchar(200) as product_group,
    group_jb::varchar(50) as group_jb,
    groupmsl::varchar(100) as groupmsl,
    forecastso_mil::number(23,4) as forecastso_mil
    from transformed
)
select * from final