{{
    config
    (
        materialized = 'incremental',
        incremental_strategy = 'append',
        pre_hook = "
                    
                    {% if var('cte_to_execute') == 'tp_integration_job' %}
                    UPDATE {{ ref('jpnedw_integration__mt_constant_range') }}
                    SET MAX_DATE = (
                            SELECT MAX(YMD_DT)
                            FROM {{ source('jpnedw_integration', 'mt_cld') }}
                            WHERE year_445 = (
                                    SELECT YEAR(current_timestamp()::timestamp_ntz(9))
                                    )
                            )
                    WHERE Identify_cd = 'TP';

                    UPDATE {{ ref('jpnedw_integration__mt_constant_range') }}
                    SET MIN_DATE = (
                            SELECT MIN(YMD_DT)
                            FROM {{ source('jpnedw_integration', 'mt_cld') }}
                            WHERE year::number = (
                                    SELECT YEAR(current_timestamp()::timestamp_ntz(9))
                                    ) - (
                                    SELECT DELETE_RANGE
                                    FROM {{ ref('jpnedw_integration__mt_constant_range') }} 
                                    WHERE IDENTIFY_CD = 'TP'
                                    ) + 1
                                AND day = 1
                            )
                    WHERE Identify_cd = 'TP';

                    DELETE
                    FROM {{this}} ab USING {{ ref('jpnedw_integration__mt_constant_range') }} mt
                    WHERE ab.JCP_DATA_SOURCE = 'TP'
                        AND ab.JCP_DATA_SOURCE = mt.IDENTIFY_CD
                        AND ab.JCP_DATE BETWEEN mt.MIN_DATE
                            AND mt.MAX_DATE;

                    {% elif var('cte_to_execute') == 'sellin_integration_job' %}

                    UPDATE {{ ref('jpnedw_integration__mt_constant_range') }}
                    SET MAX_DATE = (
                            SELECT MAX(YMD_DT)
                            FROM {{ source('jpnedw_integration', 'mt_cld') }}
                            WHERE year_445 = (
                                    SELECT YEAR(current_timestamp()::timestamp_ntz(9))
                                    )
                            )
                    WHERE Identify_cd = 'SI';

                    UPDATE {{ ref('jpnedw_integration__mt_constant_range') }}
                    SET MIN_DATE = (
                            SELECT MIN(YMD_DT)
                            FROM {{ source('jpnedw_integration', 'mt_cld') }}
                            WHERE year_445 = (
                                    SELECT YEAR(current_timestamp()::timestamp_ntz(9))
                                    )
                            )
                    WHERE Identify_cd = 'SI';

                    DELETE
                    FROM {{this}} ab USING {{ ref('jpnedw_integration__mt_constant_range') }} mt
                    WHERE ab.JCP_DATA_SOURCE = 'SI'
                        AND ab.JCP_DATA_SOURCE = mt.IDENTIFY_CD
                        AND ab.JCP_DATE BETWEEN mt.MIN_DATE
                            AND mt.MAX_DATE;

                    {% elif var('cte_to_execute') == 'sellout_integration_job' %}

                    UPDATE {{ ref('jpnedw_integration__mt_constant_range') }}
                    SET MAX_DATE = (
                            SELECT MAX(YMD_DT)
                            FROM {{ source('jpnedw_integration', 'mt_cld') }}
                            WHERE year_445 = (
                                    SELECT YEAR(current_timestamp()::timestamp_ntz(9))
                                    )
                            )
                    WHERE Identify_cd = 'SO';


                    UPDATE {{ ref('jpnedw_integration__mt_constant_range') }}
                    SET MIN_DATE = (
                            SELECT MAX(YMD_DT)
                            FROM {{ source('jpnedw_integration', 'mt_cld') }}
                            WHERE year_445::number = (
                                    SELECT YEAR(current_timestamp()::timestamp_ntz(9))
                                    ) - (
                                    SELECT DELETE_RANGE
                                    FROM {{ ref('jpnedw_integration__mt_constant_range') }} 
                                    WHERE IDENTIFY_CD = 'SO'
                                    )
                            )
                    WHERE Identify_cd = 'SO';

                    DELETE
                    FROM {{this}} ab USING {{ ref('jpnedw_integration__mt_constant_range') }} mt
                    WHERE ab.JCP_DATA_SOURCE = 'SO'
                        AND ab.JCP_DATA_SOURCE = mt.IDENTIFY_CD
                        AND ab.JCP_DATE BETWEEN mt.MIN_DATE
                            AND mt.MAX_DATE;

                    {% endif %}
                    "
    )
}}

WITH dw_so_sell_out_dly
AS (
	SELECT *
	FROM {{ ref('jpnedw_integration__dw_so_sell_out_dly') }}
	),
dw_si_sell_in_dly
AS (
	SELECT *
	FROM {{ ref('jpnedw_integration__dw_si_sell_in_dly') }}
	),
edi_item_m
AS (
	SELECT *
	FROM {{ ref('jpnedw_integration__edi_item_m') }}
	),
edi_store_m
AS (
	SELECT *
	FROM {{ ref('jpnedw_integration__edi_store_m') }}
	),
edi_chn_m
AS (
	SELECT *
	FROM {{ ref('jpnedw_integration__edi_chn_m') }}
	),
mt_constant_range1
AS (
	SELECT MAX_DATE,
		MIN_DATE
	FROM {{ ref('jpnedw_integration__mt_constant_range') }}
	WHERE IDENTIFY_CD = 'SO'
	),
mt_constant_range2
AS (
	SELECT MAX_DATE,
		MIN_DATE
	FROM {{ ref('jpnedw_integration__mt_constant_range') }}
	WHERE IDENTIFY_CD = 'TP'
	),
mt_constant_range3
AS (
	SELECT MAX_DATE,
		MIN_DATE
	FROM {{ ref('jpnedw_integration__mt_constant_range') }}
	WHERE IDENTIFY_CD = 'SO'
	),
mt_cld
AS (
	SELECT *
	FROM {{ source('jpnedw_integration', 'mt_cld') }}
	),
wk_tp_datamart_promo_amt
AS (
	SELECT *
	FROM {{ ref('jpnwks_integration__wk_tp_datamart_promo_amt') }}
	),
mt_constant
AS (
	SELECT *
	FROM {{ source('jpnedw_integration', 'mt_constant') }}
	),

{% if var("cte_to_execute") == 'io_integration_job' %}
tmp1
AS (
	SELECT 'SO' AS JCP_DATA_SOURCE,
		'Actual' AS JCP_PLAN_TYPE,
		'Sell-Out' AS JCP_ANALYSIS_TYPE,
		'Sell-Out' AS JCP_DATA_CATEGORY,
		T_IN.SHP_DATE AS JCP_DATE,
		T_IN.JCP_SHP_TO_CD AS JCP_CSTM_CD,
		T_IN.JCP_STR_CD AS JCP_STR_CD,
		T_STR_CHN.CHN_CD AS JCP_CHN_CD,
		T_STR_CHN.CHN_OFFC_CD AS JCP_CHN_OFFC_CD,
		T_IN.ITEM_CD AS JCP_JAN_CD,
		CASE 
			WHEN T_ITEM_M.PROM_GOODS_FLG IS NOT NULL
				THEN T_ITEM_M.PROM_GOODS_FLG
			ELSE 'N'
			END AS JCP_PLAN_ITEM_TYPE,
		CASE 
			WHEN 0 <= MONTHS_BETWEEN(T_IN.SHP_DATE, T_ITEM_M.REL_DT)
				AND MONTHS_BETWEEN(T_IN.SHP_DATE, T_ITEM_M.REL_DT) < 12
				THEN 'Y'
			ELSE 'N'
			END AS JCP_NEW_ITEM_TYPE,
		CASE 
			WHEN T_IN.TRADE_TYPE IN ('11', '12', '31', '32', '51', '52')
				THEN '402000'
			WHEN T_IN.TRADE_TYPE IN ('21', '22', '41', '42')
				THEN '402098'
			ELSE NULL
			END AS JCP_ACCOUNT,
		TO_TIMESTAMP(to_char(current_timestamp(), 'YYYY-MM-DD HH24:MI:SS')) AS JCP_CREATE_DATE,
		T_IN.JCP_CREATE_DATE AS JCP_LOAD_DATE,
		CASE 
			WHEN T_IN.QTY <> 0
				THEN T_IN.JCP_NET_PRICE / T_IN.QTY
			ELSE NULL
			END AS JCP_UNIT_PRC,
		T_IN.QTY AS JCP_QTY,
		T_IN.JCP_NET_PRICE AS JCP_AMT,
		T_IN.RCV_DT AS SO_RCV_DT,
		T_IN.WS_CD AS SO_WS_CD,
		T_IN.RTL_TYPE AS SO_RTL_TYPE,
		T_IN.RTL_CD AS SO_RTL_CD,
		T_IN.TRADE_TYPE AS SO_TRADE_TYPE,
		T_IN.SHP_NUM AS SO_SHP_NUM,
		T_IN.TRADE_CD AS SO_TRADE_CD,
		T_IN.DEP_CD AS SO_DEP_CD,
		T_IN.CHG_CD AS SO_CHG_CD,
		T_IN.PERSON_IN_CHARGE AS SO_PERSON_IN_CHARGE,
		T_IN.PERSON_NAME AS SO_PERSON_NAME,
		T_IN.RTL_NAME AS SO_RTL_NAME,
		T_IN.RTL_HO_CD AS SO_RTL_HO_CD,
		T_IN.RTL_ADDRESS_CD AS SO_RTL_ADDRESS_CD,
		T_IN.DATA_TYPE AS SO_DATA_TYPE,
		T_IN.OPT_FLD AS SO_OPT_FLD,
		T_IN.ITEM_NM AS SO_ITEM_NM,
		T_IN.ITEM_CD_TYP AS SO_ITEM_CD_TYP,
		T_IN.QTY_TYPE AS SO_QTY_TYPE,
		T_IN.PRICE AS SO_PRICE,
		T_IN.PRICE_TYPE AS SO_PRICE_TYPE,
		T_IN.SHP_WS_CD AS SO_SHP_WS_CD,
		T_IN.REP_NAME_KANJI AS SO_REP_NAME_KANJI,
		T_IN.REP_INFO AS SO_REP_INFO,
		T_IN.RTL_NAME_KANJI AS SO_RTL_NAME_KANJI,
		T_IN.ITEM_NM_KANJI AS SO_ITEM_NM_KANJI,
		T_IN.UNT_PRC AS SO_UNT_PRC,
		T_IN.NET_PRC AS SO_NET_PRC,
		T_IN.SALES_CHAN_TYPE AS SO_SALES_CHAN_TYPE
	FROM mt_constant_range1 mt,
		DW_SO_SELL_OUT_DLY T_IN
	LEFT OUTER JOIN (
		SELECT EDI_STORE_M.STR_CD,
			EDI_CHN_M.CHN_CD,
			EDI_CHN_M.CHN_OFFC_CD
		FROM EDI_STORE_M
		LEFT OUTER JOIN EDI_CHN_M ON EDI_STORE_M.CHN_CD = EDI_CHN_M.CHN_CD
		) T_STR_CHN ON T_IN.JCP_STR_CD = T_STR_CHN.STR_CD
	LEFT OUTER JOIN EDI_ITEM_M T_ITEM_M ON T_IN.ITEM_CD = T_ITEM_M.JAN_CD_SO
	WHERE SHP_DATE BETWEEN mt.min_date
			AND mt.max_date
		AND BGN_SNDR_CD LIKE 'PAN%'
	),
insert1
AS (
	SELECT JCP_DATA_SOURCE::VARCHAR(40) AS JCP_DATA_SOURCE,
		JCP_PLAN_TYPE::VARCHAR(20) AS JCP_PLAN_TYPE,
		JCP_ANALYSIS_TYPE::VARCHAR(40) AS JCP_ANALYSIS_TYPE,
		JCP_DATA_CATEGORY::VARCHAR(40) AS JCP_DATA_CATEGORY,
		JCP_DATE::TIMESTAMP_NTZ(9) AS JCP_DATE,
		JCP_CSTM_CD::VARCHAR(40) AS JCP_CSTM_CD,
		JCP_STR_CD::VARCHAR(40) AS JCP_STR_CD,
		JCP_CHN_CD::VARCHAR(40) AS JCP_CHN_CD,
		JCP_CHN_OFFC_CD::VARCHAR(40) AS JCP_CHN_OFFC_CD,
		JCP_JAN_CD::VARCHAR(40) AS JCP_JAN_CD,
		JCP_PLAN_ITEM_TYPE::VARCHAR(2) AS JCP_PLAN_ITEM_TYPE,
		JCP_NEW_ITEM_TYPE::VARCHAR(2) AS JCP_NEW_ITEM_TYPE,
		JCP_ACCOUNT::VARCHAR(40) AS JCP_ACCOUNT,
		JCP_CREATE_DATE::TIMESTAMP_NTZ(9) AS JCP_CREATE_DATE,
		JCP_LOAD_DATE::TIMESTAMP_NTZ(9) AS JCP_LOAD_DATE,
		JCP_UNIT_PRC::NUMBER(32, 10) AS JCP_UNIT_PRC,
		JCP_QTY::NUMBER(32, 10) AS JCP_QTY,
		JCP_AMT::NUMBER(32, 10) AS JCP_AMT,
		SO_RCV_DT::TIMESTAMP_NTZ(9) AS SO_RCV_DT,
		SO_WS_CD::VARCHAR(32) AS SO_WS_CD,
		SO_RTL_TYPE::VARCHAR(2) AS SO_RTL_TYPE,
		SO_RTL_CD::VARCHAR(32) AS SO_RTL_CD,
		SO_TRADE_TYPE::VARCHAR(4) AS SO_TRADE_TYPE,
		SO_SHP_NUM::VARCHAR(20) AS SO_SHP_NUM,
		SO_TRADE_CD::VARCHAR(14) AS SO_TRADE_CD,
		SO_DEP_CD::VARCHAR(6) AS SO_DEP_CD,
		SO_CHG_CD::VARCHAR(2) AS SO_CHG_CD,
		SO_PERSON_IN_CHARGE::VARCHAR(10) AS SO_PERSON_IN_CHARGE,
		SO_PERSON_NAME::VARCHAR(30) AS SO_PERSON_NAME,
		SO_RTL_NAME::VARCHAR(160) AS SO_RTL_NAME,
		SO_RTL_HO_CD::VARCHAR(64) AS SO_RTL_HO_CD,
		SO_RTL_ADDRESS_CD::VARCHAR(30) AS SO_RTL_ADDRESS_CD,
		SO_DATA_TYPE::VARCHAR(2) AS SO_DATA_TYPE,
		SO_OPT_FLD::VARCHAR(2) AS SO_OPT_FLD,
		SO_ITEM_NM::VARCHAR(160) AS SO_ITEM_NM,
		SO_ITEM_CD_TYP::VARCHAR(2) AS SO_ITEM_CD_TYP,
		SO_QTY_TYPE::VARCHAR(2) AS SO_QTY_TYPE,
		SO_PRICE::NUMBER(32, 10) AS SO_PRICE,
		SO_PRICE_TYPE::VARCHAR(2) AS SO_PRICE_TYPE,
		SO_SHP_WS_CD::VARCHAR(16) AS SO_SHP_WS_CD,
		SO_REP_NAME_KANJI::VARCHAR(60) AS SO_REP_NAME_KANJI,
		SO_REP_INFO::VARCHAR(28) AS SO_REP_INFO,
		SO_RTL_NAME_KANJI::VARCHAR(160) AS SO_RTL_NAME_KANJI,
		SO_ITEM_NM_KANJI::VARCHAR(160) AS SO_ITEM_NM_KANJI,
		SO_UNT_PRC::NUMBER(32, 10) AS SO_UNT_PRC,
		SO_NET_PRC::NUMBER(32, 10) AS SO_NET_PRC,
		SO_SALES_CHAN_TYPE::VARCHAR(2) AS SO_SALES_CHAN_TYPE,
		NULL::TIMESTAMP_NTZ(9) AS SI_CALDAY,
		NULL::VARCHAR(42) AS SI_FISCPER,
		NULL::VARCHAR(108) AS SI_MATERIAL,
		NULL::TIMESTAMP_NTZ(9) AS SI_JCP_CREATE_DT,
		NULL::VARCHAR(14) AS SI_JCP_PAN_FLG,
		NULL::TIMESTAMP_NTZ(9) AS SI_JCP_445_YMD_DT,
		NULL::VARCHAR(2) AS SI_JCP_UPDATE_FLG,
		NULL::TIMESTAMP_NTZ(9) AS SI_JCP_UPDATE_DT,
		NULL::VARCHAR(40) AS PN_CDDFC,
		NULL::VARCHAR(40) AS PN_CDDMP,
		NULL::VARCHAR(2) AS PN_ACCOUNT_SUB_CD,
		NULL::VARCHAR(400) AS PN_PLAN_TYPE,
		NULL::VARCHAR(400) AS PN_PROMOTION_NM,
		NULL::VARCHAR(400) AS PN_ITEM_GROUP,
		NULL::VARCHAR(20) AS TP_PROMO_CD,
		NULL::VARCHAR(160) AS TP_PROMO_NM,
		NULL::VARCHAR(20) AS TP_CSTM_CD,
		NULL::VARCHAR(2) AS TP_VAL_FIXED_TYPE,
		NULL::NUMBER(12, 0) AS TP_VAL_FIXED_APPL_CNT,
		NULL::TIMESTAMP_NTZ(9) AS TP_SAP_CNT_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_SAP_CANCEL_DT,
		NULL::VARCHAR(4) AS TP_PROMO_STATUS_CD,
		NULL::VARCHAR(4) AS TP_APPROVE_STATUS_CD,
		NULL::VARCHAR(4) AS TP_RSLT_STATUS_CD,
		NULL::VARCHAR(4) AS TP_FILE_STATUS_CD,
		NULL::VARCHAR(8) AS TP_CSTCTR_CD,
		NULL::VARCHAR(20) AS TP_TSP_ACNT_CD,
		NULL::VARCHAR(20) AS TP_BME_PROMO_CD,
		NULL::NUMBER(24, 0) AS TP_UNIT_COST,
		NULL::VARCHAR(16) AS TP_APL_CREATE_EMP_CD,
		NULL::VARCHAR(16) AS TP_APL_APPLY_EMP_CD,
		NULL::VARCHAR(16) AS TP_APL_APPROVE_EMP_CD,
		NULL::VARCHAR(10) AS TP_APL_TARGET_CHN_CD,
		NULL::VARCHAR(20) AS TP_APL_BRANCH_CD,
		NULL::VARCHAR(2) AS TP_APL_PAYEE_TYP_CD,
		NULL::VARCHAR(2) AS TP_APL_DIRECT_FLG,
		NULL::VARCHAR(2) AS TP_APL_MIDST_APPL_FLG,
		NULL::VARCHAR(8) AS TP_APL_FISCAL_YEAR,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_CREATE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPROVE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_BEGIN_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_END_DT,
		NULL::VARCHAR(1024) AS TP_APL_COMMENT1,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_UPDATE_DT,
		NULL::VARCHAR(16) AS TP_APL_FIX_EMP_CD,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_FIX_DT,
		NULL::VARCHAR(16) AS TP_APL_UPDATE_EMP_CD,
		NULL::VARCHAR(2) AS TP_APL_APPL_REL_FLG,
		NULL::VARCHAR(20) AS TP_APLD_CSTM_HEAD_OFFICE_CD,
		NULL::VARCHAR(40) AS TP_APLD_CONTRACT_NO,
		NULL::TIMESTAMP_NTZ(9) AS TP_APLD_UPDATE_DT,
		NULL::VARCHAR(16) AS TP_RES_APPLY_EMP_CD,
		NULL::VARCHAR(16) AS TP_RES_APPROVE_EMP_CD,
		NULL::VARCHAR(16) AS TP_RES_RECOGNIZE_EMP_CD,
		NULL::VARCHAR(20) AS TP_RES_PAYEE_CD,
		NULL::VARCHAR(20) AS TP_RES_BRANCH_CD,
		NULL::VARCHAR(2) AS TP_RES_PAYEE_TYP_CD,
		NULL::VARCHAR(2) AS TP_RES_DIRECT_FLG,
		NULL::VARCHAR(8) AS TP_RES_FISCAL_YEAR,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_CREATE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_APPLY_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_APPROVE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_RECOGNIZE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_PAYMENT_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_PAYMENT_PLAN_DT,
		NULL::VARCHAR(20) AS TP_RES_TRNSFR_DTL_CD,
		NULL::VARCHAR(1024) AS TP_RES_COMMENT1,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_UPDATE_DT,
		NULL::VARCHAR(2) AS TP_RES_TAX_FLG,
		NULL::VARCHAR(20) AS TP_RESD_CSTM_HEAD_OFFICE_CD,
		NULL::VARCHAR(2) AS TP_RESD_PAYEE_TYP_CD,
		NULL::VARCHAR(40) AS TP_RESD_CONTRACT_NO,
		NULL::VARCHAR(1024) AS TP_RESD_COMMENT1,
		NULL::VARCHAR(2) AS TP_RESD_DIRECT_DTL_FLG,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_SERVEY_TOTAL_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_RSLT_INPUT_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_CANCEL_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_UPDATE_DT,
		NULL::VARCHAR(4) AS TP_RESD_REASON_CD,
		NULL::NUMBER(8, 2) AS TP_RESD_TAX_RATE,
		NULL::NUMBER(20, 0) AS TP_RESD_TAX_AMT,
		NULL::VARCHAR(10) AS PLNT,
		NULL::VARCHAR(10) AS SALES_GRP,
		NULL::NUMBER(10, 0) AS SO_ID,
		NULL::NUMBER(10, 0) AS SO_JCP_REC_SEQ
	FROM tmp1
	)
select * from insert1

{% elif var('cte_to_execute') == 'tp_integration_job' %}
tmp2
AS (
	SELECT 'TP' AS JCP_DATA_SOURCE,
		'Actual' AS JCP_PLAN_TYPE,
		MRT.act_flg AS JCP_ANALYSIS_TYPE,
		MRT.act_flg AS JCP_DATA_CATEGORY,
		MRT.APPLY_DT AS JCP_DATE,
		MRT.payee_cd AS JCP_CSTM_CD,
		NULL AS JCP_STR_CD,
		MRT.chn_cd AS JCP_CHN_CD,
		CHN.CHN_OFFC_CD AS JCP_CHN_OFFC_CD,
		MRT.jan_cd AS JCP_JAN_CD,
		NULL AS JCP_PLAN_ITEM_TYPE,
		NULL AS JCP_NEW_ITEM_TYPE,
		MRT.acnt_cd AS JCP_ACCOUNT,
		TO_CHAR(TO_TIMESTAMP(current_timestamp())) AS JCP_CREATE_DATE,
		TO_DATE(current_timestamp()) AS JCP_LOAD_DATE,
		NULL AS JCP_UNIT_PRC,
		NULL AS JCP_QTY,
		MRT.total AS JCP_AMT,
		MRT.promo_cd AS TP_PROMO_CD,
		NULL AS TP_PROMO_NM,
		MRT.payee_cd AS TP_CSTM_CD,
		NULL AS TP_VAL_FIXED_TYPE,
		NULL AS TP_VAL_FIXED_APPL_CNT,
		NULL AS TP_SAP_CNT_DT,
		NULL AS TP_SAP_CANCEL_DT,
		MRT.promo_status_cd AS TP_PROMO_STATUS_CD,
		NULL AS TP_APPROVE_STATUS_CD,
		NULL AS TP_RSLT_STATUS_CD,
		NULL AS TP_FILE_STATUS_CD,
		MRT.cstctr_cd AS TP_CSTCTR_CD,
		MRT.tsp_acnt_cd AS TP_TSP_ACNT_CD,
		NULL AS TP_BME_PROMO_CD,
		NULL AS TP_UNIT_COST,
		NULL AS TP_APL_CREATE_EMP_CD,
		NULL AS TP_APL_APPLY_EMP_CD,
		NULL AS TP_APL_APPROVE_EMP_CD,
		NULL AS TP_APL_TARGET_CHN_CD,
		NULL AS TP_APL_BRANCH_CD,
		NULL AS TP_APL_PAYEE_TYP_CD,
		MRT.promo_direct_flg AS TP_APL_DIRECT_FLG,
		NULL AS TP_APL_MIDST_APPL_FLG,
		NULL AS TP_APL_FISCAL_YEAR,
		NULL AS TP_APL_CREATE_DT,
		NULL AS TP_APL_APPLY_DT,
		NULL AS TP_APL_APPROVE_DT,
		to_date(MRT.apply_begin_dt) AS TP_APL_APPLY_BEGIN_DT,
		to_date(MRT.apply_end_dt) AS TP_APL_APPLY_END_DT,
		NULL AS TP_APL_COMMENT1,
		NULL AS TP_APL_UPDATE_DT,
		NULL AS TP_APL_FIX_EMP_CD,
		NULL AS TP_APL_FIX_DT,
		NULL AS TP_APL_UPDATE_EMP_CD,
		NULL AS TP_APL_APPL_REL_FLG,
		NULL AS TP_APLD_CSTM_HEAD_OFFICE_CD,
		NULL AS TP_APLD_CONTRACT_NO,
		NULL AS TP_APLD_UPDATE_DT,
		NULL AS TP_RES_APPLY_EMP_CD,
		NULL AS TP_RES_APPROVE_EMP_CD,
		NULL AS TP_RES_RECOGNIZE_EMP_CD,
		NULL AS TP_RES_PAYEE_CD,
		NULL AS TP_RES_BRANCH_CD,
		NULL AS TP_RES_PAYEE_TYP_CD,
		NULL AS TP_RES_DIRECT_FLG,
		NULL AS TP_RES_FISCAL_YEAR,
		NULL AS TP_RES_CREATE_DT,
		NULL AS TP_RES_APPLY_DT,
		NULL AS TP_RES_APPROVE_DT,
		NULL AS TP_RES_RECOGNIZE_DT,
		NULL AS TP_RES_PAYMENT_DT,
		NULL AS TP_RES_PAYMENT_PLAN_DT,
		NULL AS TP_RES_TRNSFR_DTL_CD,
		NULL AS TP_RES_COMMENT1,
		NULL AS TP_RES_UPDATE_DT,
		NULL AS TP_RES_TAX_FLG,
		NULL AS TP_RESD_CSTM_HEAD_OFFICE_CD,
		NULL AS TP_RESD_PAYEE_TYP_CD,
		NULL AS TP_RESD_CONTRACT_NO,
		NULL AS TP_RESD_COMMENT1,
		NULL AS TP_RESD_DIRECT_DTL_FLG,
		NULL AS TP_RESD_SERVEY_TOTAL_DT,
		NULL AS TP_RESD_RSLT_INPUT_DT,
		NULL AS TP_RESD_CANCEL_DT,
		NULL AS TP_RESD_UPDATE_DT,
		NULL AS TP_RESD_REASON_CD,
		NULL AS TP_RESD_TAX_RATE,
		NULL AS TP_RESD_TAX_AMT
	FROM mt_constant_range2 mt,
		(
			SELECT DISTINCT AMT.promo_cd,
				AMT.jan_cd,
				AMT.tsp_acnt_cd,
				AMT.acnt_cd,
				AMT.cstctr_cd,
				AMT.payee_cd,
				AMT.act_flg,
				AMT.amt,
				AMT.promo_status_cd,
				AMT.STATUS,
				AMT.chn_cd,
				AMT.apply_begin_dt,
				AMT.apply_end_dt,
				AMT.promo_direct_flg,
				CLD.YMD_DT APPLY_DT,
				cast(apply_end_dt::DATE - apply_begin_dt::DATE AS INT) + 1 AS monthly,
				round(amt / monthly, 2) AS total
			FROM wk_tp_datamart_promo_amt AMT,
				MT_CLD CLD
			WHERE CLD.YMD_DT BETWEEN to_date(APPLY_BEGIN_DT)
					AND to_date(APPLY_end_DT)
			) MRT
	LEFT OUTER JOIN EDI_CHN_M CHN ON MRT.CHN_CD = CHN.CHN_CD
	WHERE MRT.APPLY_BEGIN_DT BETWEEN mt.min_date
			AND mt.max_date
	),
insert2
AS (
	SELECT JCP_DATA_SOURCE::VARCHAR(40) AS JCP_DATA_SOURCE,
		JCP_PLAN_TYPE::VARCHAR(20) AS JCP_PLAN_TYPE,
		JCP_ANALYSIS_TYPE::VARCHAR(40) AS JCP_ANALYSIS_TYPE,
		JCP_DATA_CATEGORY::VARCHAR(40) AS JCP_DATA_CATEGORY,
		JCP_DATE::TIMESTAMP_NTZ(9) AS JCP_DATE,
		JCP_CSTM_CD::VARCHAR(40) AS JCP_CSTM_CD,
		JCP_STR_CD::VARCHAR(40) AS JCP_STR_CD,
		JCP_CHN_CD::VARCHAR(40) AS JCP_CHN_CD,
		JCP_CHN_OFFC_CD::VARCHAR(40) AS JCP_CHN_OFFC_CD,
		JCP_JAN_CD::VARCHAR(40) AS JCP_JAN_CD,
		JCP_PLAN_ITEM_TYPE::VARCHAR(2) AS JCP_PLAN_ITEM_TYPE,
		JCP_NEW_ITEM_TYPE::VARCHAR(2) AS JCP_NEW_ITEM_TYPE,
		JCP_ACCOUNT::VARCHAR(40) AS JCP_ACCOUNT,
		JCP_CREATE_DATE::TIMESTAMP_NTZ(9) AS JCP_CREATE_DATE,
		JCP_LOAD_DATE::TIMESTAMP_NTZ(9) AS JCP_LOAD_DATE,
		JCP_UNIT_PRC::NUMBER(32, 10) AS JCP_UNIT_PRC,
		JCP_QTY::NUMBER(32, 10) AS JCP_QTY,
		JCP_AMT::NUMBER(32, 10) AS JCP_AMT,
		NULL::TIMESTAMP_NTZ(9) AS SO_RCV_DT,
		NULL::VARCHAR(32) AS SO_WS_CD,
		NULL::VARCHAR(2) AS SO_RTL_TYPE,
		NULL::VARCHAR(32) AS SO_RTL_CD,
		NULL::VARCHAR(4) AS SO_TRADE_TYPE,
		NULL::VARCHAR(20) AS SO_SHP_NUM,
		NULL::VARCHAR(14) AS SO_TRADE_CD,
		NULL::VARCHAR(6) AS SO_DEP_CD,
		NULL::VARCHAR(2) AS SO_CHG_CD,
		NULL::VARCHAR(10) AS SO_PERSON_IN_CHARGE,
		NULL::VARCHAR(30) AS SO_PERSON_NAME,
		NULL::VARCHAR(160) AS SO_RTL_NAME,
		NULL::VARCHAR(64) AS SO_RTL_HO_CD,
		NULL::VARCHAR(30) AS SO_RTL_ADDRESS_CD,
		NULL::VARCHAR(2) AS SO_DATA_TYPE,
		NULL::VARCHAR(2) AS SO_OPT_FLD,
		NULL::VARCHAR(160) AS SO_ITEM_NM,
		NULL::VARCHAR(2) AS SO_ITEM_CD_TYP,
		NULL::VARCHAR(2) AS SO_QTY_TYPE,
		NULL::NUMBER(32, 10) AS SO_PRICE,
		NULL::VARCHAR(2) AS SO_PRICE_TYPE,
		NULL::VARCHAR(16) AS SO_SHP_WS_CD,
		NULL::VARCHAR(60) AS SO_REP_NAME_KANJI,
		NULL::VARCHAR(28) AS SO_REP_INFO,
		NULL::VARCHAR(160) AS SO_RTL_NAME_KANJI,
		NULL::VARCHAR(160) AS SO_ITEM_NM_KANJI,
		NULL::NUMBER(32, 10) AS SO_UNT_PRC,
		NULL::NUMBER(32, 10) AS SO_NET_PRC,
		NULL::VARCHAR(2) AS SO_SALES_CHAN_TYPE,
		NULL::TIMESTAMP_NTZ(9) AS SI_CALDAY,
		NULL::VARCHAR(42) AS SI_FISCPER,
		NULL::VARCHAR(108) AS SI_MATERIAL,
		NULL::TIMESTAMP_NTZ(9) AS SI_JCP_CREATE_DT,
		NULL::VARCHAR(14) AS SI_JCP_PAN_FLG,
		NULL::TIMESTAMP_NTZ(9) AS SI_JCP_445_YMD_DT,
		NULL::VARCHAR(2) AS SI_JCP_UPDATE_FLG,
		NULL::TIMESTAMP_NTZ(9) AS SI_JCP_UPDATE_DT,
		NULL::VARCHAR(40) AS PN_CDDFC,
		NULL::VARCHAR(40) AS PN_CDDMP,
		NULL::VARCHAR(2) AS PN_ACCOUNT_SUB_CD,
		NULL::VARCHAR(400) AS PN_PLAN_TYPE,
		NULL::VARCHAR(400) AS PN_PROMOTION_NM,
		NULL::VARCHAR(400) AS PN_ITEM_GROUP,
		TP_PROMO_CD::VARCHAR(20) AS TP_PROMO_CD,
		TP_PROMO_NM::VARCHAR(160) AS TP_PROMO_NM,
		TP_CSTM_CD::VARCHAR(20) AS TP_CSTM_CD,
		TP_VAL_FIXED_TYPE::VARCHAR(2) AS TP_VAL_FIXED_TYPE,
		TP_VAL_FIXED_APPL_CNT::NUMBER(12, 0) AS TP_VAL_FIXED_APPL_CNT,
		TP_SAP_CNT_DT::TIMESTAMP_NTZ(9) AS TP_SAP_CNT_DT,
		TP_SAP_CANCEL_DT::TIMESTAMP_NTZ(9) AS TP_SAP_CANCEL_DT,
		TP_PROMO_STATUS_CD::VARCHAR(4) AS TP_PROMO_STATUS_CD,
		TP_APPROVE_STATUS_CD::VARCHAR(4) AS TP_APPROVE_STATUS_CD,
		TP_RSLT_STATUS_CD::VARCHAR(4) AS TP_RSLT_STATUS_CD,
		TP_FILE_STATUS_CD::VARCHAR(4) AS TP_FILE_STATUS_CD,
		TP_CSTCTR_CD::VARCHAR(8) AS TP_CSTCTR_CD,
		TP_TSP_ACNT_CD::VARCHAR(20) AS TP_TSP_ACNT_CD,
		TP_BME_PROMO_CD::VARCHAR(20) AS TP_BME_PROMO_CD,
		TP_UNIT_COST::NUMBER(24, 0) AS TP_UNIT_COST,
		TP_APL_CREATE_EMP_CD::VARCHAR(16) AS TP_APL_CREATE_EMP_CD,
		TP_APL_APPLY_EMP_CD::VARCHAR(16) AS TP_APL_APPLY_EMP_CD,
		TP_APL_APPROVE_EMP_CD::VARCHAR(16) AS TP_APL_APPROVE_EMP_CD,
		TP_APL_TARGET_CHN_CD::VARCHAR(10) AS TP_APL_TARGET_CHN_CD,
		TP_APL_BRANCH_CD::VARCHAR(20) AS TP_APL_BRANCH_CD,
		TP_APL_PAYEE_TYP_CD::VARCHAR(2) AS TP_APL_PAYEE_TYP_CD,
		TP_APL_DIRECT_FLG::VARCHAR(2) AS TP_APL_DIRECT_FLG,
		TP_APL_MIDST_APPL_FLG::VARCHAR(2) AS TP_APL_MIDST_APPL_FLG,
		TP_APL_FISCAL_YEAR::VARCHAR(8) AS TP_APL_FISCAL_YEAR,
		TP_APL_CREATE_DT::TIMESTAMP_NTZ(9) AS TP_APL_CREATE_DT,
		TP_APL_APPLY_DT::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_DT,
		TP_APL_APPROVE_DT::TIMESTAMP_NTZ(9) AS TP_APL_APPROVE_DT,
		TP_APL_APPLY_BEGIN_DT::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_BEGIN_DT,
		TP_APL_APPLY_END_DT::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_END_DT,
		TP_APL_COMMENT1::VARCHAR(1024) AS TP_APL_COMMENT1,
		TP_APL_UPDATE_DT::TIMESTAMP_NTZ(9) AS TP_APL_UPDATE_DT,
		TP_APL_FIX_EMP_CD::VARCHAR(16) AS TP_APL_FIX_EMP_CD,
		TP_APL_FIX_DT::TIMESTAMP_NTZ(9) AS TP_APL_FIX_DT,
		TP_APL_UPDATE_EMP_CD::VARCHAR(16) AS TP_APL_UPDATE_EMP_CD,
		TP_APL_APPL_REL_FLG::VARCHAR(2) AS TP_APL_APPL_REL_FLG,
		TP_APLD_CSTM_HEAD_OFFICE_CD::VARCHAR(20) AS TP_APLD_CSTM_HEAD_OFFICE_CD,
		TP_APLD_CONTRACT_NO::VARCHAR(40) AS TP_APLD_CONTRACT_NO,
		TP_APLD_UPDATE_DT::TIMESTAMP_NTZ(9) AS TP_APLD_UPDATE_DT,
		TP_RES_APPLY_EMP_CD::VARCHAR(16) AS TP_RES_APPLY_EMP_CD,
		TP_RES_APPROVE_EMP_CD::VARCHAR(16) AS TP_RES_APPROVE_EMP_CD,
		TP_RES_RECOGNIZE_EMP_CD::VARCHAR(16) AS TP_RES_RECOGNIZE_EMP_CD,
		TP_RES_PAYEE_CD::VARCHAR(20) AS TP_RES_PAYEE_CD,
		TP_RES_BRANCH_CD::VARCHAR(20) AS TP_RES_BRANCH_CD,
		TP_RES_PAYEE_TYP_CD::VARCHAR(2) AS TP_RES_PAYEE_TYP_CD,
		TP_RES_DIRECT_FLG::VARCHAR(2) AS TP_RES_DIRECT_FLG,
		TP_RES_FISCAL_YEAR::VARCHAR(8) AS TP_RES_FISCAL_YEAR,
		TP_RES_CREATE_DT::TIMESTAMP_NTZ(9) AS TP_RES_CREATE_DT,
		TP_RES_APPLY_DT::TIMESTAMP_NTZ(9) AS TP_RES_APPLY_DT,
		TP_RES_APPROVE_DT::TIMESTAMP_NTZ(9) AS TP_RES_APPROVE_DT,
		TP_RES_RECOGNIZE_DT::TIMESTAMP_NTZ(9) AS TP_RES_RECOGNIZE_DT,
		TP_RES_PAYMENT_DT::TIMESTAMP_NTZ(9) AS TP_RES_PAYMENT_DT,
		TP_RES_PAYMENT_PLAN_DT::TIMESTAMP_NTZ(9) AS TP_RES_PAYMENT_PLAN_DT,
		TP_RES_TRNSFR_DTL_CD::VARCHAR(20) AS TP_RES_TRNSFR_DTL_CD,
		TP_RES_COMMENT1::VARCHAR(1024) AS TP_RES_COMMENT1,
		TP_RES_UPDATE_DT::TIMESTAMP_NTZ(9) AS TP_RES_UPDATE_DT,
		TP_RES_TAX_FLG::VARCHAR(2) AS TP_RES_TAX_FLG,
		TP_RESD_CSTM_HEAD_OFFICE_CD::VARCHAR(20) AS TP_RESD_CSTM_HEAD_OFFICE_CD,
		TP_RESD_PAYEE_TYP_CD::VARCHAR(2) AS TP_RESD_PAYEE_TYP_CD,
		TP_RESD_CONTRACT_NO::VARCHAR(40) AS TP_RESD_CONTRACT_NO,
		TP_RESD_COMMENT1::VARCHAR(1024) AS TP_RESD_COMMENT1,
		TP_RESD_DIRECT_DTL_FLG::VARCHAR(2) AS TP_RESD_DIRECT_DTL_FLG,
		TP_RESD_SERVEY_TOTAL_DT::TIMESTAMP_NTZ(9) AS TP_RESD_SERVEY_TOTAL_DT,
		TP_RESD_RSLT_INPUT_DT::TIMESTAMP_NTZ(9) AS TP_RESD_RSLT_INPUT_DT,
		TP_RESD_CANCEL_DT::TIMESTAMP_NTZ(9) AS TP_RESD_CANCEL_DT,
		TP_RESD_UPDATE_DT::TIMESTAMP_NTZ(9) AS TP_RESD_UPDATE_DT,
		TP_RESD_REASON_CD::VARCHAR(4) AS TP_RESD_REASON_CD,
		TP_RESD_TAX_RATE::NUMBER(8, 2) AS TP_RESD_TAX_RATE,
		TP_RESD_TAX_AMT::NUMBER(20, 0) AS TP_RESD_TAX_AMT,
		NULL::VARCHAR(10) AS PLNT,
		NULL::VARCHAR(10) AS SALES_GRP,
		NULL::NUMBER(10, 0) AS SO_ID,
		NULL::NUMBER(10, 0) AS SO_JCP_REC_SEQ
	FROM tmp2
	)

select * from insert2

{% elif var("cte_to_execute") == 'sellin_integration_job' %}
tmp3
AS (
	SELECT 'SI' AS JCP_DATA_SOURCE,
		'Actual' AS JCP_PLAN_TYPE,
		'Sell-In' AS JCP_ANALYSIS_TYPE,
		'Sell-In' AS JCP_DATA_CATEGORY,
		CASE 
			WHEN T_IN.CALDAY < T_IN.JCP_445_YMD_DT
				THEN T_IN.JCP_445_YMD_DT
			ELSE T_IN.CALDAY
			END AS JCP_DATE,
		T_IN.CUSTOMER AS JCP_CSTM_CD,
		NULL AS JCP_STR_CD,
		NULL AS JCP_CHN_OFFC_CD,
		T_ITEM_M.JAN_CD AS JCP_JAN_CD,
		CASE 
			WHEN T_ITEM_M.PROM_GOODS_FLG IS NOT NULL
				THEN T_ITEM_M.PROM_GOODS_FLG
			ELSE 'N'
			END AS JCP_PLAN_ITEM_TYPE,
		CASE 
			WHEN T_IN.CALDAY < T_IN.JCP_445_YMD_DT
				THEN CASE 
						WHEN 0 <= MONTHS_BETWEEN(T_IN.JCP_445_YMD_DT, T_ITEM_M.REL_DT)
							AND MONTHS_BETWEEN(T_IN.JCP_445_YMD_DT, T_ITEM_M.REL_DT) < 12
							THEN 'Y'
						ELSE 'N'
						END
			ELSE CASE 
					WHEN 0 <= MONTHS_BETWEEN(T_IN.CALDAY, T_ITEM_M.REL_DT)
						AND MONTHS_BETWEEN(T_IN.CALDAY, T_ITEM_M.REL_DT) < 12
						THEN 'Y'
					ELSE 'N'
					END
			END AS JCP_NEW_ITEM_TYPE,
		T_IN.ACCOUNT AS JCP_ACCOUNT,
		to_timestamp(TO_CHAR(current_timestamp(), 'YYYY-MM-DD HH24:MI:SS')) AS JCP_CREATE_DATE,
		T_IN.JCP_CREATE_DT AS JCP_LOAD_DATE,
		ABS(T_IN.JCP_UNT_PRC) AS JCP_UNIT_PRC,
		(T_IN.JCP_QTY * (- 1)) AS JCP_QTY,
		(T_IN.AMOCCC * (- 1)) AS JCP_AMT,
		T_IN.CALDAY AS SI_CALDAY,
		T_IN.FISCPER AS SI_FISCPER,
		T_IN.MATERIAL AS SI_MATERIAL,
		T_IN.JCP_CREATE_DT AS SI_JCP_CREATE_DT,
		T_IN.JCP_PAN_FLG AS SI_JCP_PAN_FLG,
		T_IN.JCP_445_YMD_DT AS SI_JCP_445_YMD_DT,
		T_IN.JCP_UPDATE_FLG AS SI_JCP_UPDATE_FLG,
		T_IN.JCP_UPDATE_DT AS SI_JCP_UPDATE_DT,
		T_IN.plnt AS plnt,
		T_IN.SALES_GRP AS SALES_GRP
	FROM DW_SI_SELL_IN_DLY T_IN
	LEFT OUTER JOIN EDI_ITEM_M T_ITEM_M ON T_IN.MATERIAL = T_ITEM_M.ITEM_CD
	WHERE T_IN.JCP_PAN_FLG = (
			SELECT IDENTIFY_VALUE
			FROM MT_CONSTANT
			WHERE IDENTIFY_CD = 'JCP_PAN_FLG'
			)
	),
insert3
AS (
	SELECT JCP_DATA_SOURCE::VARCHAR(40) AS JCP_DATA_SOURCE,
		JCP_PLAN_TYPE::VARCHAR(20) AS JCP_PLAN_TYPE,
		JCP_ANALYSIS_TYPE::VARCHAR(40) AS JCP_ANALYSIS_TYPE,
		JCP_DATA_CATEGORY::VARCHAR(40) AS JCP_DATA_CATEGORY,
		JCP_DATE::TIMESTAMP_NTZ(9) AS JCP_DATE,
		JCP_CSTM_CD::VARCHAR(40) AS JCP_CSTM_CD,
		JCP_STR_CD::VARCHAR(40) AS JCP_STR_CD,
		NULL::VARCHAR(40) AS JCP_CHN_CD,
		JCP_CHN_OFFC_CD::VARCHAR(40) AS JCP_CHN_OFFC_CD,
		JCP_JAN_CD::VARCHAR(40) AS JCP_JAN_CD,
		JCP_PLAN_ITEM_TYPE::VARCHAR(2) AS JCP_PLAN_ITEM_TYPE,
		JCP_NEW_ITEM_TYPE::VARCHAR(2) AS JCP_NEW_ITEM_TYPE,
		JCP_ACCOUNT::VARCHAR(40) AS JCP_ACCOUNT,
		JCP_CREATE_DATE::TIMESTAMP_NTZ(9) AS JCP_CREATE_DATE,
		JCP_LOAD_DATE::TIMESTAMP_NTZ(9) AS JCP_LOAD_DATE,
		JCP_UNIT_PRC::NUMBER(32, 10) AS JCP_UNIT_PRC,
		JCP_QTY::NUMBER(32, 10) AS JCP_QTY,
		JCP_AMT::NUMBER(32, 10) AS JCP_AMT,
		NULL::TIMESTAMP_NTZ(9) AS SO_RCV_DT,
		NULL::VARCHAR(32) AS SO_WS_CD,
		NULL::VARCHAR(2) AS SO_RTL_TYPE,
		NULL::VARCHAR(32) AS SO_RTL_CD,
		NULL::VARCHAR(4) AS SO_TRADE_TYPE,
		NULL::VARCHAR(20) AS SO_SHP_NUM,
		NULL::VARCHAR(14) AS SO_TRADE_CD,
		NULL::VARCHAR(6) AS SO_DEP_CD,
		NULL::VARCHAR(2) AS SO_CHG_CD,
		NULL::VARCHAR(10) AS SO_PERSON_IN_CHARGE,
		NULL::VARCHAR(30) AS SO_PERSON_NAME,
		NULL::VARCHAR(160) AS SO_RTL_NAME,
		NULL::VARCHAR(64) AS SO_RTL_HO_CD,
		NULL::VARCHAR(30) AS SO_RTL_ADDRESS_CD,
		NULL::VARCHAR(2) AS SO_DATA_TYPE,
		NULL::VARCHAR(2) AS SO_OPT_FLD,
		NULL::VARCHAR(160) AS SO_ITEM_NM,
		NULL::VARCHAR(2) AS SO_ITEM_CD_TYP,
		NULL::VARCHAR(2) AS SO_QTY_TYPE,
		NULL::NUMBER(32, 10) AS SO_PRICE,
		NULL::VARCHAR(2) AS SO_PRICE_TYPE,
		NULL::VARCHAR(16) AS SO_SHP_WS_CD,
		NULL::VARCHAR(60) AS SO_REP_NAME_KANJI,
		NULL::VARCHAR(28) AS SO_REP_INFO,
		NULL::VARCHAR(160) AS SO_RTL_NAME_KANJI,
		NULL::VARCHAR(160) AS SO_ITEM_NM_KANJI,
		NULL::NUMBER(32, 10) AS SO_UNT_PRC,
		NULL::NUMBER(32, 10) AS SO_NET_PRC,
		NULL::VARCHAR(2) AS SO_SALES_CHAN_TYPE,
		SI_CALDAY::TIMESTAMP_NTZ(9) AS SI_CALDAY,
		SI_FISCPER::VARCHAR(42) AS SI_FISCPER,
		SI_MATERIAL::VARCHAR(108) AS SI_MATERIAL,
		SI_JCP_CREATE_DT::TIMESTAMP_NTZ(9) AS SI_JCP_CREATE_DT,
		SI_JCP_PAN_FLG::VARCHAR(14) AS SI_JCP_PAN_FLG,
		SI_JCP_445_YMD_DT::TIMESTAMP_NTZ(9) AS SI_JCP_445_YMD_DT,
		SI_JCP_UPDATE_FLG::VARCHAR(2) AS SI_JCP_UPDATE_FLG,
		SI_JCP_UPDATE_DT::TIMESTAMP_NTZ(9) AS SI_JCP_UPDATE_DT,
		NULL::VARCHAR(40) AS PN_CDDFC,
		NULL::VARCHAR(40) AS PN_CDDMP,
		NULL::VARCHAR(2) AS PN_ACCOUNT_SUB_CD,
		NULL::VARCHAR(400) AS PN_PLAN_TYPE,
		NULL::VARCHAR(400) AS PN_PROMOTION_NM,
		NULL::VARCHAR(400) AS PN_ITEM_GROUP,
		NULL::VARCHAR(20) AS TP_PROMO_CD,
		NULL::VARCHAR(160) AS TP_PROMO_NM,
		NULL::VARCHAR(20) AS TP_CSTM_CD,
		NULL::VARCHAR(2) AS TP_VAL_FIXED_TYPE,
		NULL::NUMBER(12, 0) AS TP_VAL_FIXED_APPL_CNT,
		NULL::TIMESTAMP_NTZ(9) AS TP_SAP_CNT_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_SAP_CANCEL_DT,
		NULL::VARCHAR(4) AS TP_PROMO_STATUS_CD,
		NULL::VARCHAR(4) AS TP_APPROVE_STATUS_CD,
		NULL::VARCHAR(4) AS TP_RSLT_STATUS_CD,
		NULL::VARCHAR(4) AS TP_FILE_STATUS_CD,
		NULL::VARCHAR(8) AS TP_CSTCTR_CD,
		NULL::VARCHAR(20) AS TP_TSP_ACNT_CD,
		NULL::VARCHAR(20) AS TP_BME_PROMO_CD,
		NULL::NUMBER(24, 0) AS TP_UNIT_COST,
		NULL::VARCHAR(16) AS TP_APL_CREATE_EMP_CD,
		NULL::VARCHAR(16) AS TP_APL_APPLY_EMP_CD,
		NULL::VARCHAR(16) AS TP_APL_APPROVE_EMP_CD,
		NULL::VARCHAR(10) AS TP_APL_TARGET_CHN_CD,
		NULL::VARCHAR(20) AS TP_APL_BRANCH_CD,
		NULL::VARCHAR(2) AS TP_APL_PAYEE_TYP_CD,
		NULL::VARCHAR(2) AS TP_APL_DIRECT_FLG,
		NULL::VARCHAR(2) AS TP_APL_MIDST_APPL_FLG,
		NULL::VARCHAR(8) AS TP_APL_FISCAL_YEAR,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_CREATE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPROVE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_BEGIN_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_END_DT,
		NULL::VARCHAR(1024) AS TP_APL_COMMENT1,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_UPDATE_DT,
		NULL::VARCHAR(16) AS TP_APL_FIX_EMP_CD,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_FIX_DT,
		NULL::VARCHAR(16) AS TP_APL_UPDATE_EMP_CD,
		NULL::VARCHAR(2) AS TP_APL_APPL_REL_FLG,
		NULL::VARCHAR(20) AS TP_APLD_CSTM_HEAD_OFFICE_CD,
		NULL::VARCHAR(40) AS TP_APLD_CONTRACT_NO,
		NULL::TIMESTAMP_NTZ(9) AS TP_APLD_UPDATE_DT,
		NULL::VARCHAR(16) AS TP_RES_APPLY_EMP_CD,
		NULL::VARCHAR(16) AS TP_RES_APPROVE_EMP_CD,
		NULL::VARCHAR(16) AS TP_RES_RECOGNIZE_EMP_CD,
		NULL::VARCHAR(20) AS TP_RES_PAYEE_CD,
		NULL::VARCHAR(20) AS TP_RES_BRANCH_CD,
		NULL::VARCHAR(2) AS TP_RES_PAYEE_TYP_CD,
		NULL::VARCHAR(2) AS TP_RES_DIRECT_FLG,
		NULL::VARCHAR(8) AS TP_RES_FISCAL_YEAR,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_CREATE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_APPLY_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_APPROVE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_RECOGNIZE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_PAYMENT_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_PAYMENT_PLAN_DT,
		NULL::VARCHAR(20) AS TP_RES_TRNSFR_DTL_CD,
		NULL::VARCHAR(1024) AS TP_RES_COMMENT1,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_UPDATE_DT,
		NULL::VARCHAR(2) AS TP_RES_TAX_FLG,
		NULL::VARCHAR(20) AS TP_RESD_CSTM_HEAD_OFFICE_CD,
		NULL::VARCHAR(2) AS TP_RESD_PAYEE_TYP_CD,
		NULL::VARCHAR(40) AS TP_RESD_CONTRACT_NO,
		NULL::VARCHAR(1024) AS TP_RESD_COMMENT1,
		NULL::VARCHAR(2) AS TP_RESD_DIRECT_DTL_FLG,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_SERVEY_TOTAL_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_RSLT_INPUT_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_CANCEL_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_UPDATE_DT,
		NULL::VARCHAR(4) AS TP_RESD_REASON_CD,
		NULL::NUMBER(8, 2) AS TP_RESD_TAX_RATE,
		NULL::NUMBER(20, 0) AS TP_RESD_TAX_AMT,
		plnt::VARCHAR(10) AS PLNT,
		SALES_GRP::VARCHAR(10) AS SALES_GRP,
		NULL::NUMBER(10, 0) AS SO_ID,
		NULL::NUMBER(10, 0) AS SO_JCP_REC_SEQ
	FROM tmp3
	)
select * from insert3

{% elif var("cte_to_execute") == 'sellout_integration_job' %}
tmp4
AS (
	SELECT 'SO' AS JCP_DATA_SOURCE,
		'Actual' AS JCP_PLAN_TYPE,
		'Sell-Out' AS JCP_ANALYSIS_TYPE,
		'Sell-Out' AS JCP_DATA_CATEGORY,
		T_IN.SHP_DATE AS JCP_DATE,
		T_IN.JCP_SHP_TO_CD AS JCP_CSTM_CD,
		T_IN.JCP_STR_CD AS JCP_STR_CD,
		T_STR_CHN.CHN_CD AS JCP_CHN_CD,
		T_STR_CHN.CHN_OFFC_CD AS JCP_CHN_OFFC_CD,
		T_IN.ITEM_CD AS JCP_JAN_CD,
		CASE 
			WHEN T_ITEM_M.PROM_GOODS_FLG IS NOT NULL
				THEN T_ITEM_M.PROM_GOODS_FLG
			ELSE 'N'
			END AS JCP_PLAN_ITEM_TYPE,
		CASE 
			WHEN 0 <= MONTHS_BETWEEN(T_IN.SHP_DATE, T_ITEM_M.REL_DT)
				AND MONTHS_BETWEEN(T_IN.SHP_DATE, T_ITEM_M.REL_DT) < 12
				THEN 'Y'
			ELSE 'N'
			END AS JCP_NEW_ITEM_TYPE,
		CASE 
			WHEN T_IN.TRADE_TYPE IN ('11', '12', '31', '32', '51', '52')
				THEN '402000'
			WHEN T_IN.TRADE_TYPE IN ('21', '22', '41', '42')
				THEN '402098'
			ELSE NULL
			END AS JCP_ACCOUNT,
		to_timestamp(TO_CHAR(current_timestamp(), 'YYYY-MM-DD HH24:MI:SS')) AS JCP_CREATE_DATE,
		T_IN.JCP_CREATE_DATE AS JCP_LOAD_DATE,
		CASE 
			WHEN T_IN.QTY <> 0
				THEN T_IN.JCP_NET_PRICE / T_IN.QTY
			ELSE NULL
			END AS JCP_UNIT_PRC,
		T_IN.QTY AS JCP_QTY,
		T_IN.JCP_NET_PRICE AS JCP_AMT,
        T_IN.ID AS SO_ID,
        T_IN.JCP_REC_SEQ AS SO_JCP_REC_SEQ
		T_IN.RCV_DT AS SO_RCV_DT,
		T_IN.WS_CD AS SO_WS_CD,
		T_IN.RTL_TYPE AS SO_RTL_TYPE,
		T_IN.RTL_CD AS SO_RTL_CD,
		T_IN.TRADE_TYPE AS SO_TRADE_TYPE,
		T_IN.SHP_NUM AS SO_SHP_NUM,
		T_IN.TRADE_CD AS SO_TRADE_CD,
		T_IN.DEP_CD AS SO_DEP_CD,
		T_IN.CHG_CD AS SO_CHG_CD,
		T_IN.PERSON_IN_CHARGE AS SO_PERSON_IN_CHARGE,
		T_IN.PERSON_NAME AS SO_PERSON_NAME,
		T_IN.RTL_NAME AS SO_RTL_NAME,
		T_IN.RTL_HO_CD AS SO_RTL_HO_CD,
		T_IN.RTL_ADDRESS_CD AS SO_RTL_ADDRESS_CD,
		T_IN.DATA_TYPE AS SO_DATA_TYPE,
		T_IN.OPT_FLD AS SO_OPT_FLD,
		T_IN.ITEM_NM AS SO_ITEM_NM,
		T_IN.ITEM_CD_TYP AS SO_ITEM_CD_TYP,
		T_IN.QTY_TYPE AS SO_QTY_TYPE,
		T_IN.PRICE AS SO_PRICE,
		T_IN.PRICE_TYPE AS SO_PRICE_TYPE,
		T_IN.SHP_WS_CD AS SO_SHP_WS_CD,
		T_IN.REP_NAME_KANJI AS SO_REP_NAME_KANJI,
		T_IN.REP_INFO AS SO_REP_INFO,
		T_IN.RTL_NAME_KANJI AS SO_RTL_NAME_KANJI,
		T_IN.ITEM_NM_KANJI AS SO_ITEM_NM_KANJI,
		T_IN.UNT_PRC AS SO_UNT_PRC,
		T_IN.NET_PRC AS SO_NET_PRC,
		T_IN.SALES_CHAN_TYPE AS SO_SALES_CHAN_TYPE
	FROM mt_constant_range3 mt,
		DW_SO_SELL_OUT_DLY T_IN
	LEFT OUTER JOIN (
		SELECT EDI_STORE_M.STR_CD,
			EDI_CHN_M.CHN_CD,
			EDI_CHN_M.CHN_OFFC_CD
		FROM EDI_STORE_M
		LEFT OUTER JOIN EDI_CHN_M ON EDI_STORE_M.CHN_CD = EDI_CHN_M.CHN_CD
		) T_STR_CHN ON T_IN.JCP_STR_CD = T_STR_CHN.STR_CD
	LEFT OUTER JOIN EDI_ITEM_M T_ITEM_M ON T_IN.ITEM_CD = T_ITEM_M.JAN_CD_SO
	WHERE T_IN.SHP_DATE BETWEEN mt.min_date
			AND mt.max_date
		AND BGN_SNDR_CD NOT LIKE 'PAN%'
	),
insert4
AS (
	SELECT JCP_DATA_SOURCE::VARCHAR(40) AS JCP_DATA_SOURCE,
		JCP_PLAN_TYPE::VARCHAR(20) AS JCP_PLAN_TYPE,
		JCP_ANALYSIS_TYPE::VARCHAR(40) AS JCP_ANALYSIS_TYPE,
		JCP_DATA_CATEGORY::VARCHAR(40) AS JCP_DATA_CATEGORY,
		JCP_DATE::TIMESTAMP_NTZ(9) AS JCP_DATE,
		JCP_CSTM_CD::VARCHAR(40) AS JCP_CSTM_CD,
		JCP_STR_CD::VARCHAR(40) AS JCP_STR_CD,
		JCP_CHN_CD::VARCHAR(40) AS JCP_CHN_CD,
		JCP_CHN_OFFC_CD::VARCHAR(40) AS JCP_CHN_OFFC_CD,
		JCP_JAN_CD::VARCHAR(40) AS JCP_JAN_CD,
		JCP_PLAN_ITEM_TYPE::VARCHAR(2) AS JCP_PLAN_ITEM_TYPE,
		JCP_NEW_ITEM_TYPE::VARCHAR(2) AS JCP_NEW_ITEM_TYPE,
		JCP_ACCOUNT::VARCHAR(40) AS JCP_ACCOUNT,
		JCP_CREATE_DATE::TIMESTAMP_NTZ(9) AS JCP_CREATE_DATE,
		JCP_LOAD_DATE::TIMESTAMP_NTZ(9) AS JCP_LOAD_DATE,
		JCP_UNIT_PRC::NUMBER(32, 10) AS JCP_UNIT_PRC,
		JCP_QTY::NUMBER(32, 10) AS JCP_QTY,
		JCP_AMT::NUMBER(32, 10) AS JCP_AMT,
		SO_RCV_DT::TIMESTAMP_NTZ(9) AS SO_RCV_DT,
		SO_WS_CD::VARCHAR(32) AS SO_WS_CD,
		SO_RTL_TYPE::VARCHAR(2) AS SO_RTL_TYPE,
		SO_RTL_CD::VARCHAR(32) AS SO_RTL_CD,
		SO_TRADE_TYPE::VARCHAR(4) AS SO_TRADE_TYPE,
		SO_SHP_NUM::VARCHAR(20) AS SO_SHP_NUM,
		SO_TRADE_CD::VARCHAR(14) AS SO_TRADE_CD,
		SO_DEP_CD::VARCHAR(6) AS SO_DEP_CD,
		SO_CHG_CD::VARCHAR(2) AS SO_CHG_CD,
		SO_PERSON_IN_CHARGE::VARCHAR(10) AS SO_PERSON_IN_CHARGE,
		SO_PERSON_NAME::VARCHAR(30) AS SO_PERSON_NAME,
		SO_RTL_NAME::VARCHAR(160) AS SO_RTL_NAME,
		SO_RTL_HO_CD::VARCHAR(64) AS SO_RTL_HO_CD,
		SO_RTL_ADDRESS_CD::VARCHAR(30) AS SO_RTL_ADDRESS_CD,
		SO_DATA_TYPE::VARCHAR(2) AS SO_DATA_TYPE,
		SO_OPT_FLD::VARCHAR(2) AS SO_OPT_FLD,
		SO_ITEM_NM::VARCHAR(160) AS SO_ITEM_NM,
		SO_ITEM_CD_TYP::VARCHAR(2) AS SO_ITEM_CD_TYP,
		SO_QTY_TYPE::VARCHAR(2) AS SO_QTY_TYPE,
		SO_PRICE::NUMBER(32, 10) AS SO_PRICE,
		SO_PRICE_TYPE::VARCHAR(2) AS SO_PRICE_TYPE,
		SO_SHP_WS_CD::VARCHAR(16) AS SO_SHP_WS_CD,
		SO_REP_NAME_KANJI::VARCHAR(60) AS SO_REP_NAME_KANJI,
		SO_REP_INFO::VARCHAR(28) AS SO_REP_INFO,
		SO_RTL_NAME_KANJI::VARCHAR(160) AS SO_RTL_NAME_KANJI,
		SO_ITEM_NM_KANJI::VARCHAR(160) AS SO_ITEM_NM_KANJI,
		SO_UNT_PRC::NUMBER(32, 10) AS SO_UNT_PRC,
		SO_NET_PRC::NUMBER(32, 10) AS SO_NET_PRC,
		SO_SALES_CHAN_TYPE::VARCHAR(2) AS SO_SALES_CHAN_TYPE,
		NULL::TIMESTAMP_NTZ(9) AS SI_CALDAY,
		NULL::VARCHAR(42) AS SI_FISCPER,
		NULL::VARCHAR(108) AS SI_MATERIAL,
		NULL::TIMESTAMP_NTZ(9) AS SI_JCP_CREATE_DT,
		NULL::VARCHAR(14) AS SI_JCP_PAN_FLG,
		NULL::TIMESTAMP_NTZ(9) AS SI_JCP_445_YMD_DT,
		NULL::VARCHAR(2) AS SI_JCP_UPDATE_FLG,
		NULL::TIMESTAMP_NTZ(9) AS SI_JCP_UPDATE_DT,
		NULL::VARCHAR(40) AS PN_CDDFC,
		NULL::VARCHAR(40) AS PN_CDDMP,
		NULL::VARCHAR(2) AS PN_ACCOUNT_SUB_CD,
		NULL::VARCHAR(400) AS PN_PLAN_TYPE,
		NULL::VARCHAR(400) AS PN_PROMOTION_NM,
		NULL::VARCHAR(400) AS PN_ITEM_GROUP,
		NULL::VARCHAR(20) AS TP_PROMO_CD,
		NULL::VARCHAR(160) AS TP_PROMO_NM,
		NULL::VARCHAR(20) AS TP_CSTM_CD,
		NULL::VARCHAR(2) AS TP_VAL_FIXED_TYPE,
		NULL::NUMBER(12, 0) AS TP_VAL_FIXED_APPL_CNT,
		NULL::TIMESTAMP_NTZ(9) AS TP_SAP_CNT_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_SAP_CANCEL_DT,
		NULL::VARCHAR(4) AS TP_PROMO_STATUS_CD,
		NULL::VARCHAR(4) AS TP_APPROVE_STATUS_CD,
		NULL::VARCHAR(4) AS TP_RSLT_STATUS_CD,
		NULL::VARCHAR(4) AS TP_FILE_STATUS_CD,
		NULL::VARCHAR(8) AS TP_CSTCTR_CD,
		NULL::VARCHAR(20) AS TP_TSP_ACNT_CD,
		NULL::VARCHAR(20) AS TP_BME_PROMO_CD,
		NULL::NUMBER(24, 0) AS TP_UNIT_COST,
		NULL::VARCHAR(16) AS TP_APL_CREATE_EMP_CD,
		NULL::VARCHAR(16) AS TP_APL_APPLY_EMP_CD,
		NULL::VARCHAR(16) AS TP_APL_APPROVE_EMP_CD,
		NULL::VARCHAR(10) AS TP_APL_TARGET_CHN_CD,
		NULL::VARCHAR(20) AS TP_APL_BRANCH_CD,
		NULL::VARCHAR(2) AS TP_APL_PAYEE_TYP_CD,
		NULL::VARCHAR(2) AS TP_APL_DIRECT_FLG,
		NULL::VARCHAR(2) AS TP_APL_MIDST_APPL_FLG,
		NULL::VARCHAR(8) AS TP_APL_FISCAL_YEAR,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_CREATE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPROVE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_BEGIN_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_APPLY_END_DT,
		NULL::VARCHAR(1024) AS TP_APL_COMMENT1,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_UPDATE_DT,
		NULL::VARCHAR(16) AS TP_APL_FIX_EMP_CD,
		NULL::TIMESTAMP_NTZ(9) AS TP_APL_FIX_DT,
		NULL::VARCHAR(16) AS TP_APL_UPDATE_EMP_CD,
		NULL::VARCHAR(2) AS TP_APL_APPL_REL_FLG,
		NULL::VARCHAR(20) AS TP_APLD_CSTM_HEAD_OFFICE_CD,
		NULL::VARCHAR(40) AS TP_APLD_CONTRACT_NO,
		NULL::TIMESTAMP_NTZ(9) AS TP_APLD_UPDATE_DT,
		NULL::VARCHAR(16) AS TP_RES_APPLY_EMP_CD,
		NULL::VARCHAR(16) AS TP_RES_APPROVE_EMP_CD,
		NULL::VARCHAR(16) AS TP_RES_RECOGNIZE_EMP_CD,
		NULL::VARCHAR(20) AS TP_RES_PAYEE_CD,
		NULL::VARCHAR(20) AS TP_RES_BRANCH_CD,
		NULL::VARCHAR(2) AS TP_RES_PAYEE_TYP_CD,
		NULL::VARCHAR(2) AS TP_RES_DIRECT_FLG,
		NULL::VARCHAR(8) AS TP_RES_FISCAL_YEAR,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_CREATE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_APPLY_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_APPROVE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_RECOGNIZE_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_PAYMENT_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_PAYMENT_PLAN_DT,
		NULL::VARCHAR(20) AS TP_RES_TRNSFR_DTL_CD,
		NULL::VARCHAR(1024) AS TP_RES_COMMENT1,
		NULL::TIMESTAMP_NTZ(9) AS TP_RES_UPDATE_DT,
		NULL::VARCHAR(2) AS TP_RES_TAX_FLG,
		NULL::VARCHAR(20) AS TP_RESD_CSTM_HEAD_OFFICE_CD,
		NULL::VARCHAR(2) AS TP_RESD_PAYEE_TYP_CD,
		NULL::VARCHAR(40) AS TP_RESD_CONTRACT_NO,
		NULL::VARCHAR(1024) AS TP_RESD_COMMENT1,
		NULL::VARCHAR(2) AS TP_RESD_DIRECT_DTL_FLG,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_SERVEY_TOTAL_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_RSLT_INPUT_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_CANCEL_DT,
		NULL::TIMESTAMP_NTZ(9) AS TP_RESD_UPDATE_DT,
		NULL::VARCHAR(4) AS TP_RESD_REASON_CD,
		NULL::NUMBER(8, 2) AS TP_RESD_TAX_RATE,
		NULL::NUMBER(20, 0) AS TP_RESD_TAX_AMT,
		NULL::VARCHAR(10) AS PLNT,
		NULL::VARCHAR(10) AS SALES_GRP,
		SO_ID::NUMBER(10, 0) AS SO_ID,
		SO_JCP_REC_SEQ::NUMBER(10, 0) AS SO_JCP_REC_SEQ
	FROM tmp4
	)
SELECT *
FROM insert4
{% endif %}