with source as 
(
    select * from {{ ref('ntaedw_integration__edw_vw_hk_pos') }}
),
final as 
(
    select
        subsource_type::varchar(12) as subsource_type,
        customer::varchar(50) as customer,
        vendor_desc::varchar(100) as vendor_desc,
        customer_product_code::varchar(200) as customer_product_code,
        jnj_sku_code::varchar(200) as jnj_sku_code,
        pka_product_key::varchar(68) as pka_product_key,
        pka_product_key_description::varchar(255) as pka_product_key_description,
        stronghold::varchar(30) as stronghold,
        gcph_needstate::varchar(50) as gcph_needstate,
        category_name::varchar(500) as category_name,
        age_group_name::varchar(500) as age_group_name,
        gcph_brand::varchar(100) as gcph_brand,
        mega_brnd_desc::varchar(100) as mega_brnd_desc,
        package::varchar(30) as package,
        size::varchar(30) as size,
        greenlight_sku_flag::varchar(5) as greenlight_sku_flag,
        usd_rt::number(38,10) as usd_rt,
        lcl_rt::number(38,10) as lcl_rt,
        year::number(18,0) as year,
        fisc_per::number(18,0) as fisc_per,
        qrtr_no::number(18,0) as qrtr_no,
        qrtr::varchar(14) as qrtr,
        mnth_id::varchar(23) as mnth_id,
        mnth_desc::varchar(15) as mnth_desc,
        mnth_no::number(18,0) as mnth_no,
        mnth_shrt::varchar(3) as mnth_shrt,
        mnth_long::varchar(9) as mnth_long,
        wk::varchar(19) as wk,
        mnth_wk_no::number(38,0) as mnth_wk_no,
        fisc_week_day_num::number(38,0) as fisc_week_day_num,
        mnth_day::number(38,0) as mnth_day,
        cal_year::number(18,0) as cal_year,
        cal_qrtr_no::number(18,0) as cal_qrtr_no,
        cal_mnth_id::number(18,0) as cal_mnth_id,
        cal_mnth_no::number(18,0) as cal_mnth_no,
        cal_mnth_nm::varchar(9) as cal_mnth_nm,
        cal_mnth_day::number(38,0) as cal_mnth_day,
        cal_mnth_wk_num::varchar(9) as cal_mnth_wk_num,
        cal_yr_wk_num::varchar(11) as cal_yr_wk_num,
        cal_week_day_num::number(38,0) as cal_week_day_num,
        promo_week::varchar(48) as promo_week,
        promo_month_week_num::number(31,0) as promo_month_week_num,
        promo_week_day_num::number(31,0) as promo_week_day_num,
        promo_month_shrt::varchar(60) as promo_month_shrt,
        promo_year::number(31,0) as promo_year,
        cal_day::date as cal_day,
        cal_date_id::varchar(52) as cal_date_id,
        pos_qty::number(18,0) as pos_qty,
        pos_sales::number(23,5) as pos_sales,
        sellin_qty::number(18,0) as sellin_qty,
        sellin_preww::number(18,0) as sellin_preww,
        sellin_nts::float as sellin_nts,
        customer_description::varchar(100) as customer_description,
        ciw_gts_lcy::number(38,15) as ciw_gts_lcy,
        ciw_gts_usd::number(38,15) as ciw_gts_usd,
        ciw_lcy::number(38,15) as ciw_lcy,
        ciw_usd::number(38,15) as ciw_usd,
        ciw_gts_prev_yr_mnth::number(38,15) as ciw_gts_prev_yr_mnth,
        ciw_prev_yr_mnth::number(38,15) as ciw_prev_yr_mnth,
        ciw_gts_lcy_prev_yr_mnth::number(38,15) as ciw_gts_lcy_prev_yr_mnth,
        ciw_lcy_prev_yr_mnth::number(38,15) as ciw_lcy_prev_yr_mnth,
        numerator::number(31,2) as numerator,
        denominator::number(31,2) as denominator,
        numerator_prev_yr::number(31,2) as numerator_prev_yr,
        denominator_prev_yr::number(31,2) as denominator_prev_yr,
        msl_complaince_numerator::number(38,15) as msl_complaince_numerator,
        msl_complaince_denominator::number(38,15) as msl_complaince_denominator,
        msl_complaince_denominator_wt::number(38,15) as msl_complaince_denominator_wt,
        osa_complaince_numerator::number(38,15) as osa_complaince_numerator,
        osa_complaince_denominator::number(38,15) as osa_complaince_denominator,
        osa_complaince_denominator_wt::number(38,15) as osa_complaince_denominator_wt,
        promo_complaince_numerator::number(38,15) as promo_complaince_numerator,
        promo_complaince_denominator::number(38,15) as promo_complaince_denominator,
        promo_complaince_denominator_wt::number(38,15) as promo_complaince_denominator_wt,
        display_complaince_numerator::number(38,15) as display_complaince_numerator,
        display_complaince_denominator::number(38,15) as display_complaince_denominator,
        display_complaince_denominator_wt::number(38,15) as display_complaince_denominator_wt,
        planogram_complaince_numerator::number(38,15) as planogram_complaince_numerator,
        planogram_complaince_denominator::number(38,15) as planogram_complaince_denominator,
        planogram_complaince_denominator_wt::number(38,15) as planogram_complaince_denominator_wt,
        sos_complaince_numerator::number(38,15) as sos_complaince_numerator,
        sos_complaince_denominator::number(38,15) as sos_complaince_denominator,
        sos_complaince_denominator_wt::number(38,15) as sos_complaince_denominator_wt,
        soa_complaince_numerator::number(38,15) as soa_complaince_numerator,
        soa_complaince_denominator::number(38,15) as soa_complaince_denominator,
        soa_complaince_denominator_wt::number(38,15) as soa_complaince_denominator_wt
    from source
)
select * from final